USE [ST_Daily]
GO

/****** Object:  View [APS].[TotalMemberDaysBySchool_2015]    Script Date: 3/9/2017 2:07:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [APS].[TotalMemberDaysBySchool_2015] AS

SELECT
	 ORGANIZATION_NAME,
	 SCHOOL_CODE,
	 SCHOOL_YEAR,
	 MAX(SCHOOLDAYNUMBER) as [TOTALDAYS]

FROM
	 [dbo].[CalDayTable2015]
INNER JOIN
	REV.REV_ORGANIZATION_YEAR YR
ON
	YR.ORGANIZATION_YEAR_GU = CalDayTable2015.OrgYrGu
INNER JOIN
	REV.REV_YEAR YR2 
ON 
	YR2.YEAR_GU = YR.YEAR_GU
INNER JOIN
	REV.REV_ORGANIZATION ORG
ON
	ORG.ORGANIZATION_GU = YR.ORGANIZATION_GU
INNER JOIN
	REV.EPC_SCH SCH
ON
	SCH.ORGANIZATION_GU = YR.ORGANIZATION_GU
GROUP BY
	ORGANIZATION_NAME,
	SCHOOL_YEAR,
	SCHOOL_CODE





GO


