/* Per Frank the only scores for Istation are for year 2016-2017


Requesting APS administrative data end of year 2016-17 (baseline)
Refresh at intervals indicated below in school years 2017-18, 2018-19, 2019-20, 2020-21:
Sandia Base ES
•         Scale scores and performance levels from interim assessments (3 sets per year grades K-6; IS THIS BOY, MOY, AND EOY? WHAT TESTS?
			IStation and Add+Vantage Math, end of fall semester and end of year), 
I'M NOT SURE HOW THIS READS.  IS IS THREE SETS PER YEAR GRADES K-6 FOR ALL TESTS? AND THEN ISTATION AND ADD_VANTAGE MATH FOR END OF FALL SEMESTER
AND END OF YEAR?

•         Unexcused absences end of fall semester and end of year (grades K-8), 
•         Grades in core courses in math and science end of fall semester and end of year (grades 6-8),
SIXTH-EIGHTH GRADE MATH COURSES PER COURSE TABLE
ALGEBRA
ALGEBRA 1 8TH
ALGEBRA I
ALGEBRA I BIL
ALGEBRA I DUAL
ALGEBRA I HON
ALGEBRA I HONOR
EXPL MATH STRATS 1
EXPL MATH STRATS 2
EXPL MATH STRATS 3
EXPL MATH STRATS 4
FUNC MTH
GEOM HON
HONORS ALGEBRA
HONORS GEOMETRY
MATH
MATH 6
MATH 6 BIL
MATH 6 DUAL
MATH 6 ENRICHED
MATH 6/7 AC BIL
MATH 6/7 ACC
MATH 6/7 ACCEL
MATH 7
MATH 7 BIL
MATH 7 DUAL
MATH 7 ENRICHED
MATH 7 REGULAR
MATH 7/8 AC BIL
MATH 7/8 ACC
MATH 7/8 ACCEL
MATH 8
MATH 8 BIL
MATH 8 DUAL
MATH 8 ENRICHED
MATH 8 REGULAR
MATH STRAT 6-8
MATH STRATS 2
MATH STRATS 3
MATH STRATS 4
MATH STRATS 6-8
MATH STRATS 6-8 BIL
MATH STRATS 6-8 SEM
MATH STRATS I
MATH TM
MATH6/7 AC DUAL
MATH7/8 AC DUAL
MATH8
PRE-ALGEBRA
Unidentified
ZMATH 6
ZMATH 7
ZMATH8

SIXTH-EIGHTH GRADE SCIENCE COURSES PER COURSE TABLE

COURSE_TITLE
AFFECTIVE SEMIN
CLASSROOM AIDE
GENERAL SCIENCE
INDIVIDUAL STUD
LATE ARRIVAL 2
LIBRARY/MEDIA A
OFFICE AIDE
SCIENCE
SCIENCE 6
SCIENCE 6 BIL
SCIENCE 6 DUAL
SCIENCE 7
SCIENCE 7 BIL
SCIENCE 7 DUAL
SCIENCE 8
SCIENCE 8 BIL
SCIENCE 8 DUAL
SRVY SCI
STUDENT AIDE
Unidentified
ZSCIENCE 6
ZSCIENCE 7
ZSCIENCE 8
ZSCIENCE8
                          
•         Scale scores and performance levels PARCC assessment in math on end of year (grades 3-8). SANDIA BASE ELEMENTARY ONLY GOES TO GRADE 5????
 
San Antonito ES
•         Scale scores and performance levels from interim assessments (3 sets per year grades K-5, end of fall semester and end of year), 

WHAT IS INCLUDED IN INTERIM ASSESSMENTS?

•         Unexcused absences end of fall semester and end of year (grades K-5), 
•         Grades in core courses in math and science end of fall semester and end of year (grade 6), 

GRADE 6 MATH CLASSES PER COURSE TABLE

COURSE_TITLE
LITERACY AND MA
MATH 6
MATH 6 BIL
MATH 6 DEVELOPM
MATH 6 DUAL
MATH 6 ENRICHED
MATH 6 REGULAR
MATH 8
MATH BILINGUAL
MATH DUAL LANGU

SIXTH-GRADE SCIENCE CLASSES PER COURSE TABLE

COURSE_TITLE
6TH GRADE ADVIS
EXPLORATORY ART
HOMEROOM 6TH GR
SCIENCE 6
SCIENCE 6 DUAL
SCIENCE 6 GFT
SCIENCE 6 REGUL
SCIENCE BILINGU
SCIENCE DUAL LA


•         Scale scores and performance levels PARCC assessment in math on end of year (grades 3-5).


Roosevelt MS
•         Scale scores and performance levels from interim assessments (3 sets per year grades 6-8, end of fall semester and end of year),
•         Unexcused absences end of fall semester and end of year (grades 6-8), 
•         Grades in core courses in math and science end of fall semester and end of year (grade 6), 
•         Scale scores and performance levels PARCC assessment in math on end of year (grades 6-8).
 

I AM REALLY NOT SURE WHAT THIS IS OR WHERE IT COMES FROM:
•         Teacher ratings from the Walkthrough Assessment (Differentiated Instruction items; end of year). Ratings from consenting teachers (UNM-CEPR and Lanny Leyba will provide list)

 */

;with ISTATION_READING
AS
(
SELECT
    LOCAL_SCHOOL_YEAR AS 'School Year'
 
    ,STUDENT_ID AS 'Student APS ID'
    ,TEST_STUDENT_GRADE as 'ISTATION_READING_GRADE'
    ,TEST_PRIMARY_RESULT AS ISTATION_READING_PERFORMANCE_LEVEL
    ,TEST_ADMIN_PERIOD
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_NAME = 'iStation - Reading - Overall - English'
AND LOCAL_SCHOOL_YEAR = '2016-2017'
)
--SELECT * FROM ISTATION_READING

,ISTATION_SPANISH
AS
(
SELECT 
    LOCAL_SCHOOL_YEAR AS 'School Year'
 
    ,STUDENT_ID AS 'Student APS ID'
    ,TEST_STUDENT_GRADE as 'ISTATION_SPANISH_GRADE'
    ,TEST_PRIMARY_RESULT AS ISTATION_SPANISH_PERFORMANCE_LEVEL
    ,TEST_ADMIN_PERIOD
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_NAME = 'iStation - Reading - Overall - Spanish'
AND LOCAL_SCHOOL_YEAR = '2016-2017'
)
--SELECT * FROM ISTATION_SPANISH 

,RESULTSCTE
AS
(
SELECT
	R.[Student APS ID],
	'Reading' as SUBJECT,
	R.ISTATION_READING_GRADE as GRADE,
	R.ISTATION_READING_PERFORMANCE_LEVEL AS PERF_LEVEL,
	R.TEST_ADMIN_PERIOD
FROM
	ISTATION_READING r
union all
select
	s.[Student APS ID],
	'Spanish',
	s.ISTATION_SPANISH_GRADE,
	s.ISTATION_SPANISH_PERFORMANCE_LEVEL,
	s.TEST_ADMIN_PERIOD
from
	istation_spanish S

)
--select * from RESULTSCTE
SELECT * INTO DBO.ISTATION_2016 FROM RESULTScte 

