BEGIN TRAN
EXECUTE AS LOGIN='QueryFileUser'
GO


;with Students
as
(
SELECT
	*
FROM
	OPENROWSET (
		'Microsoft.ACE.OLEDB.12.0', 
		'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
		'SELECT * from AIP_SAT_Or.csv')
)
--select * from Students
,DistinctRecords
as
(
select
	row_number() over(partition by sis_number order by sis_number) as rn,
	s.*
from
	Students s
where left(Document_Category,3) in ('AIP', 'SAT')
)
--select * from DistinctRecords
,Results
as
(
select
	*
from
	DistinctRecords 
where
	rn = 1
)
--select * from Results 
insert into REV.UD_STU
select
STUDENT_GU, --STUDENT_GU
GETDATE(), --ADD_DATE_TIME_STAMP
'9F899E44-0472-4F9E-AC07-2D234400337B', --ADD_ID_STAMP
'N',  --ATTENDED_PREK
NULL, --CHANGE_DATE_TIME_STAMP
NULL, --CHANGE_ID_STAMP
'N',  --EXCLUDE_BUSINESS
'N',  --EXCLUDE_MILITARY
'N',  --EXCLUDE_UNIVERSITY
NULL, -- PREK_PROGRAM
NULL, --TRANSITION_STATUS
NULL, --TUITION_PRICE
'N',  --ADVOCACY_COLLABORATION_WITH
'N',  --APS_SUPPORT
NULL, --ASSIGNED_OUTREACH_WORKER
'N',  --CAP_AND_GOWN_VOUCHER
'N',  --CHILD NUTRITION
'N',  --COMMUNITY_RESOURCE_GUIDE
'N',  --COMMUNITY SUPPORT
NULL, --FULLTIME_PARTTIME
'N',  --DISCUSSION_OF_MVRIGHTS
'N',  --EMERGENCY_CLOTHING_VOUCHER
'N',  --EMERGENCY_FOOD_BAG
'N',  --ENROLLMENT ASSISTANCE
'N',  --EXPEDITED_EVALUATION
'N',  --FAFSA_COLLEGE_FINANCIAL
NULL, --FAMILY_NUMBER
'N',  --FOOD_SERVICES
'N',  --HOLIDAY_ADOPTIONS
'N',  --HYGIENE_PRODUCTS
'N',  --MEDICAL_DENTAL_SERVICES
'N',  --MENTAL_HEALTH_SERVICES
'N',  --OTHER CLOTHING
'N',  --SCHOOL_RECORDS
'N',  --SCHOOL_SUPPLIES
'N',  --SCHOOL_UNIFORMS
'N',  --SUMMER_PROGRAM
'N',  --SUMMER_SCHOOL_ASSISTANCE_FE
'N',  --TRANSPORTATION
'N',  --TUTORING_PROGRAM
'N',  --ASSISTANCE_WITH_OTHER_SCHOO
NULL, --LAST_SCHOOL_ATTENDED
NULL, --LAST_SCHOOL_ATTENDED_CITY
NULL, --LAST_SCHOOL_ATTENDED_STATE
'N',  --HOME_VISIT
'N',  --SCHOOL_REFERRAL
NULL, --LUS_DATE_TRANSLATOR
NULL, --LUS_Q11_PARENT
NULL, --LUS_Q12_PARENT
NULL, --LUS_Q8_PARENT
NULL, --LUS_Q9A_PARENT
NULL, --LUS_Q9B_PARENT
NULL, --LUS_TRANSLATOR_LANGUAGE
NULL, --LUS_TRANSLATOR_NAME
NULL, --PROOF_OF_INSURANCE
NULL, --PROOF_OF_LICENSE
NULL, --PROOF_OF_REGISTRATION
NULL, --V1_COLOR
NULL, --V1_LICENSE_PLACE
NULL, --V1_MAKE
NULL, --V1_MODEL
NULL, --V2_COLOR
NULL, --V2_LICENSE_PLACE
NULL, --V2_MAKE
NULL, --V2_MODEL
NULL, --V3_COLOR
NULL, --V3_LICENSE_PLACE
NULL, --V3_MAKE
NULL, --V3_MODEL
NULL, --PARKING_PERMIT
'N',  --A_504
CASE
	WHEN LEFT(DOCUMENT_CATEGORY,3) = 'AIP' THEN 'Y'
	ELSE
	'N'
	END, --AIP
CASE
	WHEN LEFT(DOCUMENT_CATEGORY,3) = 'SAT' THEN 'Y'
	ELSE
	'N'
	END, --SAT
'N' --THREE_YEARS_US_SCHOOLS
FROM Results
--ROLLBACK
COMMIT
