
;with STUDENT_CTE
AS
(
SELECT
	PE.SCHOOL_NAME,
	PE.SCHOOL_CODE,
	BS.LAST_NAME,
	BS.FIRST_NAME,
	BS.MIDDLE_NAME,
	BS.SIS_NUMBER,
	PE.GRADE,
	BS.RACE_1,
	BS.RACE_2,
	BS.RACE_3,
	BS.RACE_4,
	BS.RACE_5,
	BS.RESOLVED_RACE,
	BS.HISPANIC_INDICATOR,
	BS.LUNCH_STATUS,
	BS.STUDENT_GU

FROM
	APS.PrimaryEnrollmentDetailsAsOf(getdate()) PE
INNER JOIN
	APS.BasicStudentWithMoreInfo BS
ON
	PE.STUDENT_GU = BS.STUDENT_GU
WHERE
	GRADE IN ('10', '11', '12')
)
--SELECT * FROM STUDENT_CTE

,IB_COURSE
AS
(
SELECT
	S.*,
	h.COURSE_ID,
	h.COURSE_TITLE,
	c.IB_INDICATOR
FROM
	STUDENT_CTE S
LEFT JOIN 
	aps.ScheduleDetailsAsOf(getdate()) h
ON
	S.STUDENT_GU = H.STUDENT_GU
INNER JOIN
	REV.EPC_CRS C
ON
	H.COURSE_GU = C.COURSE_GU
WHERE
	IB_INDICATOR  = 'y'
)

--SELECT * FROM IB_COURSE 
,AP_COURSE
AS
(
SELECT
	S.*,
	h.COURSE_ID,
	h.COURSE_TITLE,
	c.AP_INDICATOR
FROM
	STUDENT_CTE S
LEFT JOIN 
	aps.ScheduleDetailsAsOf(getdate()) h
ON
	S.STUDENT_GU = H.STUDENT_GU
INNER JOIN
	REV.EPC_CRS C
ON
	H.COURSE_GU = C.COURSE_GU
WHERE
	H.AP_INDICATOR  = 'y'
)

--SELECT * FROM AP_COURSE
--,AP_EXAM
--AS
--(
--SELECT 
--	ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER, TEST_NAME, ADMIN_DATE ORDER BY TEST_NAME DESC) AS RN,	
--	CAST (SIS_NUMBER AS INT) AS SIS_NUMBER,
--	TEST.TEST_NAME,
--	STU_PART.PERFORMANCE_LEVEL AS PL,
--	SCORES.TEST_SCORE,
--	STUDENTTEST.ADMIN_DATE,
--	STUDENT.STUDENT_GU
--FROM
--	rev.EPC_STU_TEST AS StudentTest
--JOIN
--	rev.EPC_TEST_PART AS PART
--ON 
--	StudentTest.TEST_GU = PART.TEST_GU
--JOIN
--	rev.EPC_STU_TEST_PART AS STU_PART
--ON
--	PART.TEST_PART_GU = STU_PART.TEST_PART_GU
--	AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU
--INNER JOIN
--	rev.EPC_STU_TEST_PART_SCORE AS SCORES
--ON
--	SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU
--LEFT JOIN
--	rev.EPC_TEST_SCORE_TYPE AS SCORET
--ON
--	SCORET.TEST_GU = StudentTest.TEST_GU
--	AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU
--LEFT JOIN
--	rev.EPC_TEST_DEF_SCORE AS SCORETDEF
--ON
--	SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU
--LEFT JOIN
--	rev.EPC_TEST AS TEST
--ON
--	TEST.TEST_GU = StudentTest.TEST_GU
--INNER JOIN
--	rev.EPC_STU AS Student
--ON
--	Student.STUDENT_GU = StudentTest.STUDENT_Gu
--INNER JOIN
--	rev.REV_PERSON AS Person
--ON
--	Person.PERSON_GU = StudentTest.STUDENT_GU
--LEFT JOIN
--	APS.PrimaryEnrollmentsAsOf(GETDATE()) AS Enroll
--ON
--	StudentTest.STUDENT_GU = Enroll.STUDENT_GU
--LEFT JOIN
--	rev.REV_ORGANIZATION_YEAR AS OrgYear
--ON
--	Enroll.ORGANIZATION_YEAR_GU = OrgYear.ORGANIZATION_YEAR_GU
--LEFT JOIN
--	rev.REV_ORGANIZATION AS Org
--ON
--	OrgYear.ORGANIZATION_GU = Org.ORGANIZATION_GU
--LEFT JOIN
--	APS.LookupTable('K12','Grade') AS GradeLevel
--ON
--	Enroll.GRADE = GradeLevel.VALUE_CODE
--LEFT JOIN
--	REV.EPC_GRAD_REQ_DEF_TST_GRPYT AS TST_GRPYT
--ON
--	TEST.TEST_GU = TST_GRPYT.TEST_GU
--	AND PART.TEST_PART_GU = TST_GRPYT.TEST_PART_GU
--LEFT JOIN
--	REV.EPC_GRAD_REQ_DEF_TST_GRPY AS TST_GRPY
--ON 
--	TST_GRPY.GRAD_REQ_DEF_TST_GRPY_GU = TST_GRPYT.GRAD_REQ_DEF_TST_GRPY_GU
--LEFT JOIN
--	REV.EPC_GRAD_REQ_DEF_GRPYT_REQ AS DEF_GRPYT
--ON
--	DEF_GRPYT.TEST_GU = TEST.TEST_GU
--	AND DEF_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU = TST_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU
--LEFT JOIN
--	REV.EPC_GRAD_REQ_DEF_GRPYT_PL AS GRPYT_PL
--ON
--	GRPYT_PL.GRAD_REQ_DEF_TST_GRPTY_GU = DEF_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU
--WHERE
--	1 = 1
--AND
--	 TEST_NAME LIKE 'AP %'
--AND
--	 YEAR(ADMIN_DATE) = '2017'
--)
--,AP_EXAM_RESULTS
--AS
--(
--SELECT 
--	STUDENT_GU,
--	SIS_NUMBER,
--	TEST_NAME,
--	PL,
--	TEST_SCORE,
--	ADMIN_DATE
--FROM
--	AP_EXAM
--WHERE
--	RN = 1
--)
--SELECT * FROM AP_EXAM_RESULTS
,RESULTS
AS
(
select
S.STUDENT_GU,
	s.SCHOOL_NAME,
	s.SCHOOL_CODE,
	s.LAST_NAME,
	s.FIRST_NAME,
	isnull(s.MIDDLE_NAME, ' ') aS MIDDLE_NAME,
	s.SIS_NUMBER,
	s.GRADE,
	isnull(s.RACE_1, '') AS RACE1,
	isnull(s.RACE_2, '') AS RACE2,
	isnull(s.RACE_3, '') AS RACE3,
	isnull(s.RACE_4, '') AS RACE4,
	isnull(s.RACE_5, '') AS RACE5,
	isnull(s.RESOLVED_RACE, '') AS RESOLVED_RACE,
	isnull(s.HISPANIC_INDICATOR, '') AS HISPANIC_INDICATOR,
	isnull(s.LUNCH_STATUS, '') AS LUNCH_STATUS,
	isnull(i.IB_INDICATOR, '') as IB_INDICATOR,
	isnull(i.COURSE_ID, '') AS IB_COURSE_ID,
	isnull(i.COURSE_TITLE, '') AS IB_COURSE_TITLE,
	--isnull(i.MARK, '') AS IB_COURSE_GRADE,
	isnull(a.AP_INDICATOR, '') AS AP_INDICATOR,
	isnull(a.COURSE_ID, '') AS AP_COURSE_ID,
	isnull(a.COURSE_TITLE, '') AS AP_COURSE_TITLE
	--isnull(a.MARK, '') AS AP_COURSE_GRADE,
	--isnull(R.TEST_NAME, '') AS AP_TEST_NAME,
	--isnull(r.TEST_SCORE, '') AS AP_TEST_SCORE
from
	Student_CTE S
left outer join
	IB_COURSE I
on
	s.student_gu = i.STUDENT_GU
left outer join
	AP_COURSE A
on
	s.STUDENT_GU = a.STUDENT_GU
)
select * from RESULTS
order by SCHOOL_NAME, SIS_NUMBER




