;with Main as
(
SELECT
	SCHOOL_NAME
	,SCHOOL_CODE
	,ZONE
	,SCHOOL_YEAR
	,EXTENSION
	,TERM_CODE
	,ISNULL(STUDENT_COUNT,0) AS STUDENT_COUNT
	,MAX_STUDENTS
	,COURSE_TITLE
	,COURSE_ID
	,ISNULL([BEP/ESL], 'N') AS [BEP/ESL]
	,SECTION_ID
	,ISNULL(PERKINS_IDENTIFIER, 'N') AS PERKINS_IDENTIFIER
	,ROOM_NAME
	,PERIOD_BEGIN
	,PERIOD_END
	,MEETING_DAYS
	,STAFF_NAME
	,BADGE_NUM
	,STATE_COURSE_CODE
	,ORGANIZATION_GU
FROM
(
SELECT DISTINCT
	SCHOOL_NAME
	,SCHOOL_CODE
	,ZONE
	,SCHOOL_YEAR
	,EXTENSION
	,TERM_CODE
	,STUDENT_COUNT
	,MAX_STUDENTS
	,COURSE_TITLE
	,COURSE_ID
	,[BEP/ESL]
	,SECTION_ID
	,PERKINS_IDENTIFIER
	,ROOM_NAME
	,PERIOD_BEGIN
	,PERIOD_END
	,MEETING_DAYS
	,STAFF_NAME
	,BADGE_NUM
	,STATE_COURSE_CODE
	,ORGANIZATION_GU

FROM
(

SELECT
	ORG.[ORGANIZATION_NAME] AS [SCHOOL_NAME]
	,YR.SCHOOL_YEAR
	,yr.extension
	,SECT.TERM_CODE
	,TOTAL_FEMALE + TOTAL_MALE AS STUDENT_COUNT
	,CASE WHEN TOTAL_FEMALE IS NULL THEN 0 ELSE TOTAL_FEMALE END AS TOTAL_FEMALE
	,CASE WHEN TOTAL_MALE IS NULL THEN 0 ELSE TOTAL_MALE END AS TOTAL_MALE
	,SECT.MAX_STUDENTS
	,CRSE.COURSE_TITLE AS COURSE_TITLE
	,CRSE.COURSE_ID AS COURSE_ID
	,CASE
		WHEN CLL.COURSE_LEVEL IN ('BEP', 'ESL') THEN 'Y'
		ELSE
		'N'
	END AS [BEP/ESL]
	,SECT.SECTION_ID
	,CASE
		WHEN SECT.SUPP_FUND_CAT = '1' THEN 'Y'
		ELSE
		'N'
	END AS PERKINS_IDENTIFIER
	,SECT.ROOM_SIMPLE
	,SECT.PERIOD_BEGIN
	,SECT.PERIOD_END
	, STUFF((SELECT ','+ left(symd.MEET_DAY_CODE,1)
	         FROM rev.EPC_SCH_YR_SECT        sec 	
	         JOIN rev.EPC_SCH_YR_SECT_MET_DY sysmd ON sysmd.SECTION_GU      = sec.SECTION_GU
	         JOIN rev.EPC_SCH_YR_MET_DY      symd  ON symd.SCH_YR_MET_DY_GU = sysmd.SCH_YR_MET_DY_GU
	       WHERE sec.SECTION_GU  = sect.SECTION_GU	
	       ORDER BY symd.ORDERBY	
	       FOR XML PATH('')
	     ),1,1,'') AS [MEETING_DAYS]
	,PER.FIRST_NAME + ' ' + PER.LAST_NAME AS STAFF_NAME
	,STAF.BADGE_NUM AS BADGE_NUM
	,CRSE.STATE_COURSE_CODE AS STATE_COURSE_CODE
	,CASE WHEN TAG.TAG IS NULL THEN '' ELSE TAG.TAG END AS TAG
	,ORG.ORGANIZATION_GU
	,SCH.SCHOOL_CODE
	,SCH.ALT_ID AS ZONE
	,ROOM.ROOM_NAME
FROM
rev.EPC_SCH_YR_SECT as sect
JOIN
REV.EPC_SCH_YR_CRS AS CRS
ON SECT.SCHOOL_YEAR_COURSE_GU = CRS.SCHOOL_YEAR_COURSE_GU

JOIN
REV.EPC_CRS AS CRSE
ON CRSE.COURSE_GU = CRS.COURSE_GU

join
rev.EPC_CRS_LEVEL_LST CLL
ON
CLL.COURSE_GU = CRSE.COURSE_GU

JOIN
REV.REV_ORGANIZATION_YEAR AS ORGY
ON ORGY.ORGANIZATION_YEAR_GU = CRS.ORGANIZATION_YEAR_GU

JOIN 
REV.REV_ORGANIZATION AS ORG
ON ORG.ORGANIZATION_GU = ORGY.ORGANIZATION_GU

JOIN
REV.EPC_SCH SCH
ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU

LEFT OUTER JOIN 
REV.EPC_STAFF_SCH_YR AS STY
ON STY.STAFF_SCHOOL_YEAR_GU = SECT.STAFF_SCHOOL_YEAR_GU

JOIN
REV.EPC_STAFF STAF
ON STAF.STAFF_GU = STY.STAFF_GU

JOIN
REV.REV_PERSON AS PER
ON PER.PERSON_GU = STY.STAFF_GU

JOIN
REV.REV_YEAR AS YR
ON YR.YEAR_GU = ORGY.YEAR_GU

LEFT JOIN
REV.UD_SECTION_TAG AS TAG
ON TAG.SECTION_GU = SECT.SECTION_GU

LEFT JOIN
REV.EPC_SCH_ROOM AS ROOM
ON ROOM.ROOM_GU = sect.ROOM_GU

WHERE 1 = 1
and
	 @Year = yr.year_gu
) AS MST_1411
WHERE 1 = 1
            AND [ORGANIZATION_GU] LIKE @School
            AND [TERM_CODE] LIKE @Term

UNION

SELECT DISTINCT
	SCHOOL_NAME
	,SCHOOL_CODE
	,ZONE
	,SCHOOL_YEAR
	,EXTENSION
	,TERM_CODE
	,STUDENT_COUNT
	,MAX_STUDENTS
	,COURSE_TITLE
	,COURSE_ID
	,[BEP/ESL]
	,SECTION_ID
	,PERKINS_IDENTIFIER
	,ROOM_NAME
	,PERIOD_BEGIN
	,PERIOD_END
	,MEETING_DAYS
	,STAFF_NAME
	,BADGE_NUM
	,STATE_COURSE_CODE
	,ORGANIZATION_GU

FROM
(
SELECT
	ORG.[ORGANIZATION_NAME] AS [SCHOOL_NAME]
	,YR.SCHOOL_YEAR
	,yr.extension
	,SECT.TERM_CODE
	,TOTAL_FEMALE + TOTAL_MALE AS STUDENT_COUNT
	,CASE WHEN TOTAL_FEMALE IS NULL THEN 0 ELSE TOTAL_FEMALE END AS TOTAL_FEMALE
	,CASE WHEN TOTAL_MALE IS NULL THEN 0 ELSE TOTAL_MALE END AS TOTAL_MALE
	,SECT.MAX_STUDENTS
	,CRSE.COURSE_TITLE AS COURSE_TITLE
	,CRSE.COURSE_ID AS COURSE_ID
	,CASE
		WHEN CLL.COURSE_LEVEL IN ('BEP', 'ESL') THEN 'Y'
		ELSE
		'N'
	END AS [BEP/ESL]

	,SECT.SECTION_ID
	,CASE
		WHEN SECT.SUPP_FUND_CAT = '1' THEN 'Y'
		ELSE
		'N'
	END AS PERKINS_IDENTIFIER

	,SECT.ROOM_SIMPLE
	,SECT.PERIOD_BEGIN
	,SECT.PERIOD_END
	, STUFF((SELECT ','+ left(symd.MEET_DAY_CODE,1)
	         FROM rev.EPC_SCH_YR_SECT        sec 	
	         JOIN rev.EPC_SCH_YR_SECT_MET_DY sysmd ON sysmd.SECTION_GU      = sec.SECTION_GU
	         JOIN rev.EPC_SCH_YR_MET_DY      symd  ON symd.SCH_YR_MET_DY_GU = sysmd.SCH_YR_MET_DY_GU
	       WHERE sec.SECTION_GU  = sect.SECTION_GU	
	       ORDER BY symd.ORDERBY	
	       FOR XML PATH('')
	     ),1,1,'') AS [MEETING_DAYS]
	,PER.FIRST_NAME + ' ' + PER.LAST_NAME AS STAFF_NAME
	,STAF.BADGE_NUM AS BADGE_NUM
	,CRSE.STATE_COURSE_CODE AS STATE_COURSE_CODE
	,CASE WHEN TAG.TAG IS NULL THEN '' ELSE TAG.TAG END AS TAG
	,ORG.ORGANIZATION_GU
	,SCH.SCHOOL_CODE
	,SCH.ALT_ID AS ZONE
	,ROOM.ROOM_NAME
FROM
rev.EPC_SCH_YR_SECT as sect
JOIN
REV.EPC_SCH_YR_CRS AS CRS
ON SECT.SCHOOL_YEAR_COURSE_GU = CRS.SCHOOL_YEAR_COURSE_GU

JOIN
REV.EPC_CRS AS CRSE
ON CRSE.COURSE_GU = CRS.COURSE_GU

join
rev.EPC_CRS_LEVEL_LST CLL
ON
CLL.COURSE_GU = CRSE.COURSE_GU


JOIN
REV.REV_ORGANIZATION_YEAR AS ORGY
ON ORGY.ORGANIZATION_YEAR_GU = CRS.ORGANIZATION_YEAR_GU

JOIN 
REV.REV_ORGANIZATION AS ORG
ON ORG.ORGANIZATION_GU = ORGY.ORGANIZATION_GU

JOIN
REV.EPC_SCH SCH
ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU

LEFT OUTER JOIN 
REV.EPC_STAFF_SCH_YR AS STY
ON STY.STAFF_SCHOOL_YEAR_GU = SECT.STAFF_SCHOOL_YEAR_GU

JOIN
REV.EPC_STAFF STAF
ON STAF.STAFF_GU = STY.STAFF_GU

JOIN
REV.REV_PERSON AS PER
ON PER.PERSON_GU = STY.STAFF_GU

JOIN
REV.REV_YEAR AS YR
ON YR.YEAR_GU = ORGY.YEAR_GU

LEFT JOIN
REV.UD_SECTION_TAG AS TAG
ON TAG.SECTION_GU = SECT.SECTION_GU

LEFT JOIN
REV.EPC_SCH_ROOM AS ROOM
ON ROOM.ROOM_GU = sect.ROOM_GU
WHERE 1 = 1
and
	 @Year = yr.year_gu
) AS MST_1411
WHERE 1 = 1
            AND [ORGANIZATION_GU] LIKE @School
            AND [TERM_CODE] LIKE @Term
) UNIONED
)
select * from main 
ORDER BY

	[SCHOOL_NAME]
	,[STAFF_NAME]
	,[COURSE_ID]