


; WITH
PERIOD_ATTENDANCE AS
(
SELECT
	-- GROUP DAILY TOTALS BY ABSENCE TYPE
	[STUDENT_GU]
	,SUM(CASE WHEN [ABSENCE CODE] = 'UX' THEN [ABSENCE PERIODS] ELSE 0 END) AS 'PERIOD UNEXCUSED'
	,SUM(CASE WHEN [ABSENCE CODE] = 'EX' THEN [ABSENCE PERIODS] ELSE 0 END) AS 'PERIOD EXCUSED'
	,SUM(CASE WHEN [ABSENCE CODE] = 'T' THEN [ABSENCE PERIODS] ELSE 0 END) AS 'PERIOD TARDY'
FROM
	(
	SELECT
		[STUDENT_GU]
		-- GET PERIOD TOTALS
		,COUNT([BELL_PERIOD]) AS [ABSENCE PERIODS]
		,[ABSENCE CODE]
	FROM	
		(
		SELECT 
			SIS_NUMBER
			, ORG.ORGANIZATION_NAME
			, ESAD.ABS_DATE
			, BELL_PERIOD
			, CASE
				WHEN ISNUMERIC(ECAR.ABBREVIATION) = 1 OR ECAR.ABBREVIATION = 'T' THEN 'T'  
				WHEN ECAR.ABBREVIATION = 'ABS' THEN 'UX'
				ELSE 'EX'END 
			AS [ABSENCE CODE]
			--,ECAR.ABBREVIATION AS [ABSENCE CODE]
			,S.STUDENT_GU
			, SSY.STUDENT_SCHOOL_YEAR_GU
			, ESAP.PERIOD_ATTEND_GU
			, ESAD.DAILY_ATTEND_GU
			
		FROM rev.EPC_STU_ATT_DAILY        AS ESAD
		LEFT JOIN rev.EPC_STU_ATT_PERIOD  AS ESAP   ON ESAP.DAILY_ATTEND_GU             = ESAD.DAILY_ATTEND_GU
		INNER JOIN rev.EPC_STU_ENROLL           AS ESE    ON ESE.ENROLLMENT_GU                = ESAD.ENROLLMENT_GU 
		INNER JOIN rev.EPC_STU_SCH_YR           AS SSY    ON SSY.STUDENT_SCHOOL_YEAR_GU       = ESE.STUDENT_SCHOOL_YEAR_GU 
		INNER JOIN rev.EPC_STU								AS S      ON S.STUDENT_GU = SSY.STUDENT_GU 
		INNER JOIN rev.REV_ORGANIZATION_YEAR AS ORGYR ON SSY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
		INNER JOIN rev.REV_ORGANIZATION AS ORG ON ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
		INNER JOIN rev.EPC_CODE_ABS_REAS_SCH_YR AS ECARSY ON ECARSY.CODE_ABS_REAS_SCH_YEAR_GU = ESAP.CODE_ABS_REAS_GU 
		AND  ECARSY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU 
		INNER JOIN rev.EPC_CODE_ABS_REAS        AS ECAR   ON ECAR.CODE_ABS_REAS_GU            = ECARSY.CODE_ABS_REAS_GU 
		INNER JOIN rev.REV_YEAR                 AS Y      ON Y.YEAR_GU                           = ORGYR.YEAR_GU 
							   --This view only runs for the current school year and Regular Extension
								AND Y.SCHOOL_YEAR  = (SELECT SCHOOL_YEAR FROM rev.SIF_22_Common_CurrentYear)
								AND Y.EXTENSION  = 'R'
		WHERE
			ECAR.ABBREVIATION != 'T'
			AND ESAD.ABS_DATE <= GETDATE()
			AND ECAR.ABBREVIATION NOT IN ('AC','CV','IA','IW','PAR','DCC')
		) AS [PERIOD_ATT]
		
	GROUP BY
		[STUDENT_GU]
		,[ABSENCE CODE]
	) AS [PERIOD_ATT]
	
GROUP BY
	[STUDENT_GU]
)

,ATTENDANCE_DETAILS AS
(

		SELECT 
			SIS_NUMBER
			, ORG.ORGANIZATION_NAME
			, ESAD.ABS_DATE
			, BELL_PERIOD
			, CASE
				WHEN ISNUMERIC(ECAR.ABBREVIATION) = 1 OR ECAR.ABBREVIATION = 'T' THEN 'T'  
				WHEN ECAR.ABBREVIATION = 'ABS' THEN 'UX'
				ELSE 'EX'END 
			AS [ABSENCE CODE]
			--,ECAR.ABBREVIATION AS [ABSENCE CODE]
			,S.STUDENT_GU
			, SSY.STUDENT_SCHOOL_YEAR_GU
			, ESAP.PERIOD_ATTEND_GU
			, ESAD.DAILY_ATTEND_GU
			, ECAR.ABBREVIATION
			
		FROM rev.EPC_STU_ATT_DAILY        AS ESAD
		LEFT JOIN rev.EPC_STU_ATT_PERIOD  AS ESAP   ON ESAP.DAILY_ATTEND_GU             = ESAD.DAILY_ATTEND_GU
		INNER JOIN rev.EPC_STU_ENROLL           AS ESE    ON ESE.ENROLLMENT_GU                = ESAD.ENROLLMENT_GU 
		INNER JOIN rev.EPC_STU_SCH_YR           AS SSY    ON SSY.STUDENT_SCHOOL_YEAR_GU       = ESE.STUDENT_SCHOOL_YEAR_GU 
		INNER JOIN rev.EPC_STU								AS S      ON S.STUDENT_GU = SSY.STUDENT_GU 
		INNER JOIN rev.REV_ORGANIZATION_YEAR AS ORGYR ON SSY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
		INNER JOIN rev.REV_ORGANIZATION AS ORG ON ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
		INNER JOIN rev.EPC_CODE_ABS_REAS_SCH_YR AS ECARSY ON ECARSY.CODE_ABS_REAS_SCH_YEAR_GU = ESAP.CODE_ABS_REAS_GU 
		AND  ECARSY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU 
		INNER JOIN rev.EPC_CODE_ABS_REAS        AS ECAR   ON ECAR.CODE_ABS_REAS_GU            = ECARSY.CODE_ABS_REAS_GU 
		INNER JOIN rev.REV_YEAR                 AS Y      ON Y.YEAR_GU                           = ORGYR.YEAR_GU 
							   --This view only runs for the current school year and Regular Extension
								AND Y.SCHOOL_YEAR  = (SELECT SCHOOL_YEAR FROM rev.SIF_22_Common_CurrentYear)
								AND Y.EXTENSION  = 'R'
		WHERE
			ECAR.ABBREVIATION != 'T'
			AND ESAD.ABS_DATE <= GETDATE()
			--AND ECAR.ABBREVIATION NOT IN ('AC','CV','IA','IW','PAR','DCC')

)
,STUDENT_DETAILS
AS
(
SELECT --TOP 100
	[STUDENT].STUDENT_GU,
	[Student].[FIRST_NAME]
	,[Student].[LAST_NAME]
	,[Student].[MIDDLE_NAME]
	,[Student].[SIS_NUMBER]
	,[Enrollments].[GRADE]
	,CONVERT(VARCHAR(10),[Enrollments].[ENTER_DATE],101) AS [ENTER_DATE]
    ,[Enrollments].[SCHOOL_NAME]
    ,[Enrollments].[SCHOOL_CODE]
    ,CASE WHEN [Student].[MAIL_ADDRESS] IS NULL THEN [Student].[HOME_ADDRESS] ELSE [Student].[MAIL_ADDRESS] END AS [ADDRESS]
    ,CASE WHEN [Student].[MAIL_ADDRESS] IS NULL THEN [Student].[HOME_ADDRESS_2] ELSE [Student].[MAIL_ADDRESS_2] END AS [ADDRESS_2]
    ,CASE WHEN [Student].[MAIL_CITY] IS NULL THEN [Student].[HOME_CITY] ELSE [Student].[MAIL_CITY] END AS [CITY]
    ,CASE WHEN [Student].[MAIL_STATE] IS NULL THEN [Student].[HOME_STATE] ELSE [Student].[MAIL_STATE] END AS [STATE]
    ,CASE WHEN [Student].[MAIL_ZIP] IS NULL THEN [Student].[HOME_ZIP] ELSE [Student].[MAIL_ZIP] END AS [ZIP]

	,PER.EMAIL AS [STUDENT_EMAIL]
    
    ,[ATTENDANCE].[PERIOD UNEXCUSED]
    ,[ATTENDANCE].[PERIOD EXCUSED]
    ,[ATTENDANCE].[PERIOD TARDY]
    --,[DETAILS].*
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]	
	INNER JOIN
	REV.REV_PERSON PER
	ON
	PER.PERSON_GU = STUDENT.STUDENT_GU
	LEFT OUTER JOIN
	PERIOD_ATTENDANCE AS [ATTENDANCE]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [ATTENDANCE].[STUDENT_GU]	
	
WHERE
	[Enrollments].[SCHOOL_CODE] NOT IN ('022','048','058','188','162','611','846','847','848','900','901','910')
	AND [Enrollments].[GRADE] IN ('09','10','11','12')
	
	AND (([ATTENDANCE].[PERIOD UNEXCUSED] = 0
	AND [ATTENDANCE].[PERIOD EXCUSED] = 0)
	OR [ATTENDANCE].[PERIOD UNEXCUSED] IS NULL)
	
	AND [ENROLLMENTS].[EXCLUDE_ADA_ADM] IS NULL
	AND ENROLLMENTS.SCHOOL_CODE NOT IN ('533','TRAN')
)

--SELECT * FROM STUDENT_DETAILS		
,PARENT_EMAIL
AS
(
SELECT
	ROW_NUMBER() OVER(PARTITION BY STUPAR.STUDENT_GU ORDER BY STUPAR.STUDENT_GU) AS RN,
	SD.STUDENT_GU,
	STUPAR.PARENT_GU,
	PER.EMAIL AS PARENT_EMAIL
FROM
	STUDENT_DETAILS SD
INNER JOIN
	REV.EPC_STU_PARENT STUPAR
ON
	SD.STUDENT_GU = STUPAR.STUDENT_GU
INNER JOIN
	REV.REV_PERSON PER
ON
	PER.PERSON_GU = STUPAR.PARENT_GU
)
--SELECT * FROM PARENT_EMAIL
SELECT
	--SD.STUDENT_GU,
	SD.[FIRST_NAME],
	SD.[LAST_NAME],
	SD.[MIDDLE_NAME],
	SD.[SIS_NUMBER],
	SD.[GRADE],
	SD.[ENTER_DATE],
    SD.[SCHOOL_NAME],
    SD.[SCHOOL_CODE],
	SD.[ADDRESS],
    SD.[ADDRESS_2],
    SD.[CITY],
    SD.[STATE],
    SD.[ZIP],
	SD.[STUDENT_EMAIL],
	MAX(CASE WHEN PD.RN = 1 THEN PD.PARENT_EMAIL END) AS P1EMAIL,
	MAX(CASE WHEN PD.RN = 2 THEN PD.PARENT_EMAIL END) AS P2EMAIL,
	MAX(CASE WHEN PD.RN = 3 THEN PD.PARENT_EMAIL END) AS P3EMAIL,

    SD.[PERIOD UNEXCUSED],
    SD.[PERIOD EXCUSED],
    SD.[PERIOD TARDY]

FROM
	STUDENT_DETAILS SD
INNER JOIN
	PARENT_EMAIL PD
ON
	PD.STUDENT_GU = SD.STUDENT_GU
GROUP BY
	SD.[PERIOD EXCUSED],
	SD.[SIS_NUMBER],
	SD.FIRST_NAME,
	SD.LAST_NAME,
	SD.MIDDLE_NAME,
	SD.GRADE,
	SD.ENTER_DATE,
	SD.SCHOOL_CODE,
	SD.SCHOOL_NAME,
	SD.[ADDRESS],
	SD.ADDRESS_2,
	SD.CITY,
	SD.STATE,
	SD.ZIP,
	SD.STUDENT_EMAIL,
	SD.[PERIOD UNEXCUSED],
	SD.[PERIOD TARDY]
ORDER BY
	SD.[PERIOD EXCUSED],
	SD.SIS_NUMBER