USE [ST_Production]
GO

/****** Object:  StoredProcedure [APS].[UpdateBEP]    Script Date: 10/12/2017 7:12:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



/*********************************************************************************

NIGHTLY PROCESS FOR BEP STUDENTS, MODELS, AND HOURS


**********************************************************************************/


 
ALTER PROC [APS].[UpdateBEP](
	@ValidateOnly INT
)

AS

BEGIN

BEGIN TRAN

/*******************************************************************************************
--UPDATE 1
-- CREATE NEW RECORDS WHERE THE MODEL OR HOURS DOES NOT MATCH

********************************************************************************************/

INSERT INTO REV.EPC_STU_PGM_ELL_BEP
(
STU_PGM_ELL_BEP_GU
,STUDENT_GU
,ENTER_DATE
,PROGRAM_CODE
,PROGRAM_INTENSITY
,EXIT_DATE
,ADD_ID_STAMP
,ADD_DATE_TIME_STAMP
,CHANGE_ID_STAMP
,CHANGE_DATE_TIME_STAMP
) 
SELECT DISTINCT 
------- THIS IS TO DEBUG ---------------------------------
	--T1.SIS_NUMBER
	--,T1.PROGRAM_CODE
	--,T1.PROGRAM_INTENSITY
	--,T1.ENTER_DATE
	--,T1.EXIT_DATE

	--,BEP2.PROGRAM_CODE
	--,BEP2.PROGRAM_INTENSITY
	--,BEP2.ENTER_DATE
	--,BEP2.EXIT_DATE
----------------------------------------------------------
	T1.STU_PGM_ELL_BEP AS STU_PGM_ELL_BEP
	,T1.STUDENT_GU AS STUDENT_GU
	,T1.ENTER_DATE AS ENTER_DATE
	,T1.PROGRAM_CODE AS PROGRAM_CODE
	,T1.PROGRAM_INTENSITY AS PROGRAM_INTENSITY
	,T1.EXIT_DATE AS EXIT_DATE
	,T1.[ADD_ID_STAMP] AS [ADD_ID_STAMP]
	,T1.ADD_DATE_TIME_STAMP AS [ADD_DATE_TIME_STAMP]
	,T1.CHANGE_ID_STAMP AS [CHANGE_ID_STAMP]
	,T1.CHANGE_DATE_TIME_STAMP AS [CHANGE_DATE_TIME_STAMP]
 FROM 	
(
SELECT DISTINCT 
	NEWID() AS STU_PGM_ELL_BEP
	,STU.STUDENT_GU AS STUDENT_GU
	,STU.SIS_NUMBER
	,MAX(SCH.COURSE_ENTER_DATE) AS ENTER_DATE
	,LU.VALUE_CODE AS PROGRAM_CODE
	,BEP.[HOUR] AS PROGRAM_INTENSITY
	--, BEP.MODEL, 
	,SCH.COURSE_LEAVE_DATE AS EXIT_DATE
	,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS [ADD_ID_STAMP]
	,GETDATE() AS [ADD_DATE_TIME_STAMP]
	, NULL AS [CHANGE_ID_STAMP]
	, NULL AS [CHANGE_DATE_TIME_STAMP]


 FROM 
	APS.NewBEPStudentsModelsAndHoursAsOf(GETDATE()) AS BEP
	INNER HASH JOIN 
	REV.EPC_STU AS STU
	ON
	BEP.SIS_NUMBER = STU.SIS_NUMBER
	INNER HASH JOIN 
	APS.NewBEPModelsAndHoursDetailsAsOf(GETDATE()) AS MODELS
	ON
	BEP.SIS_NUMBER = MODELS.SIS_NUMBER
	INNER HASH JOIN 
	APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
	ON
	SCH.SIS_NUMBER = MODELS.SIS_NUMBER
	AND SCH.ORGANIZATION_NAME = MODELS.SCHOOL_NAME
	AND SCH.COURSE_ID = MODELS.COURSE_ID
	AND SCH.SECTION_ID = MODELS.SECTION_ID
	INNER JOIN 
	APS.LookupTable ('K12.ProgramInfo', 'BEP_PROGRAM_CODE') AS LU
	ON
	LU.VALUE_DESCRIPTION = BEP.MODEL

--WHERE STU.SIS_NUMBER = 980001535

GROUP BY STU.STUDENT_GU, STU.SIS_NUMBER, BEP.[HOUR], BEP.MODEL, VALUE_CODE, COURSE_LEAVE_DATE



) AS T1

LEFT HASH JOIN 
(SELECT * FROM REV.EPC_STU_PGM_ELL_BEP WHERE ENTER_DATE > '20170701') AS BEP2
ON
BEP2.STUDENT_GU = T1.STUDENT_GU

WHERE 
	BEP2.STUDENT_GU = T1.STUDENT_GU
	AND (
	-- CREATE NEW RECORDS IF PROGRAM CODE OR MODEL DOES NOT MATCH 
	COALESCE(BEP2.PROGRAM_CODE, '') != T1.PROGRAM_CODE
	OR COALESCE(BEP2.PROGRAM_INTENSITY, '') != T1.PROGRAM_INTENSITY)



/*******************************************************************************************
--UPDATE 2
-- CLOSE OUT RECORDS WHERE THE MODEL AND HOURS MATCH 

********************************************************************************************/

UPDATE REV.EPC_STU_PGM_ELL_BEP
SET EXIT_DATE = T2.EXITDATE, [CHANGE_ID_STAMP] = '27CDCD0E-BF93-4071-94B2-5DB792BB735F', [CHANGE_DATE_TIME_STAMP] = GETDATE()



FROM(
SELECT 
	T1.SIS_NUMBER
	,T1.STUDENT_GU
	,T1.PROGRAM_CODE AS PROGRAMCODE
	,T1.PROGRAM_INTENSITY AS PROGRAMINTENSITY
	,T1.ENTER_DATE AS ENTERDATE
	,T1.EXIT_DATE AS EXITDATE

	,BEP2.PROGRAM_CODE
	,BEP2.PROGRAM_INTENSITY
	,BEP2.ENTER_DATE
	,BEP2.EXIT_DATE
	,BEP2.STU_PGM_ELL_BEP_GU

 FROM 	
(
SELECT 
	NEWID() AS STU_PGM_ELL_BEP
	,STU.STUDENT_GU AS STUDENT_GU
	,STU.SIS_NUMBER
	,MAX(SCH.COURSE_ENTER_DATE) AS ENTER_DATE
	,LU.VALUE_CODE AS PROGRAM_CODE
	,BEP.[HOUR] AS PROGRAM_INTENSITY
	--, BEP.MODEL, 
	,SCH.COURSE_LEAVE_DATE AS EXIT_DATE
	,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS [ADD_ID_STAMP]
	,GETDATE() AS [ADD_DATE_TIME_STAMP]
	, NULL AS [CHANGE_ID_STAMP]
	, NULL AS [CHANGE_DATE_TIME_STAMP]


 FROM 
	APS.NewBEPStudentsModelsAndHoursAsOf(GETDATE()) AS BEP
	INNER JOIN 
	REV.EPC_STU AS STU
	ON
	BEP.SIS_NUMBER = STU.SIS_NUMBER
	INNER HASH JOIN 
	APS.NewBEPModelsAndHoursDetailsAsOf(GETDATE()) AS MODELS
	ON
	BEP.SIS_NUMBER = MODELS.SIS_NUMBER
	INNER HASH JOIN 
	APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
	ON
	SCH.SIS_NUMBER = MODELS.SIS_NUMBER
	AND SCH.ORGANIZATION_NAME = MODELS.SCHOOL_NAME
	AND SCH.COURSE_ID = MODELS.COURSE_ID
	AND SCH.SECTION_ID = MODELS.SECTION_ID
	INNER JOIN 
	APS.LookupTable ('K12.ProgramInfo', 'BEP_PROGRAM_CODE') AS LU
	ON
	LU.VALUE_DESCRIPTION = BEP.MODEL

GROUP BY STU.STUDENT_GU, STU.SIS_NUMBER, BEP.[HOUR], BEP.MODEL, VALUE_CODE, COURSE_LEAVE_DATE

) AS T1

LEFT HASH JOIN 
(SELECT * FROM REV.EPC_STU_PGM_ELL_BEP WHERE ENTER_DATE > '20170701') AS BEP2
ON
BEP2.STUDENT_GU = T1.STUDENT_GU

WHERE 
	BEP2.STUDENT_GU = T1.STUDENT_GU
	AND COALESCE(BEP2.PROGRAM_CODE, '') = T1.PROGRAM_CODE
	AND COALESCE(BEP2.PROGRAM_INTENSITY, '') = T1.PROGRAM_INTENSITY
	--EXISTING RECORDS TO CLOSE OUT
	AND COALESCE(BEP2.EXIT_DATE, '') != T1.EXIT_DATE

) AS T2

WHERE
REV.EPC_STU_PGM_ELL_BEP.STU_PGM_ELL_BEP_GU = T2.STU_PGM_ELL_BEP_GU



/*******************************************************************************************
UPDATE 3 --
-- FOR RECORDS THAT ARE NOT PULLED WITH THE NIGHTLY PROCESS (BECAUSE OF BACKDATED SCHEDULES)
-- READ SCHEDULED FOR THE YEAR AND CLOSE OUT WITH COURSE EXIT DATE

********************************************************************************************/



UPDATE REV.EPC_STU_PGM_ELL_BEP 
	SET EXIT_DATE = COURSE_EXIT_DATE, [CHANGE_ID_STAMP] = '27CDCD0E-BF93-4071-94B2-5DB792BB735F', [CHANGE_DATE_TIME_STAMP] = GETDATE()


FROM (
SELECT 
	
	KIDSBACKDATED.SIS_NUMBER
	,KIDSBACKDATED.STU_PGM_ELL_BEP_GU
	,ESLBEPCLASSES.COURSE_EXIT_DATE

-----------------------FOR THESE STUDENTS -----------------------------------------
FROM (
 SELECT
	STU.STUDENT_GU, STU.SIS_NUMBER, BEP.STU_PGM_ELL_BEP_GU
 FROM 
REV.EPC_STU_PGM_ELL_BEP AS BEP
LEFT JOIN 
(
	SELECT 
		NEWID() AS STU_PGM_ELL_BEP
		,STU.STUDENT_GU AS STUDENT_GU
		,STU.SIS_NUMBER
		,MAX(SCH.COURSE_ENTER_DATE) AS ENTER_DATE
		,LU.VALUE_CODE AS PROGRAM_CODE
		,BEP.[HOUR] AS PROGRAM_INTENSITY
		--, BEP.MODEL, 
		,SCH.COURSE_LEAVE_DATE AS EXIT_DATE
		,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS [ADD_ID_STAMP]
		,GETDATE() AS [ADD_DATE_TIME_STAMP]
		, NULL AS [CHANGE_ID_STAMP]
		, NULL AS [CHANGE_DATE_TIME_STAMP]

	 FROM 
		APS.NewBEPStudentsModelsAndHoursAsOf(GETDATE()) AS BEP
		INNER HASH JOIN 
		REV.EPC_STU AS STU
		ON
		BEP.SIS_NUMBER = STU.SIS_NUMBER
		INNER HASH JOIN 
		APS.NewBEPModelsAndHoursDetailsAsOf(GETDATE()) AS MODELS
		ON
		BEP.SIS_NUMBER = MODELS.SIS_NUMBER
		INNER HASH JOIN 
		APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
		ON
		SCH.SIS_NUMBER = MODELS.SIS_NUMBER
		AND SCH.ORGANIZATION_NAME = MODELS.SCHOOL_NAME
		AND SCH.COURSE_ID = MODELS.COURSE_ID
		AND SCH.SECTION_ID = MODELS.SECTION_ID
		INNER JOIN 
		APS.LookupTable ('K12.ProgramInfo', 'BEP_PROGRAM_CODE') AS LU
		ON
		LU.VALUE_DESCRIPTION = BEP.MODEL

	--WHERE STU.SIS_NUMBER = 980001535

	GROUP BY STU.STUDENT_GU, STU.SIS_NUMBER, BEP.[HOUR], BEP.MODEL, VALUE_CODE, COURSE_LEAVE_DATE
) AS UNIQUERECORDS

	ON
	BEP.STUDENT_GU = UNIQUERECORDS.STUDENT_GU
	INNER JOIN 
	REV.EPC_STU AS STU
	ON
	STU.STUDENT_GU = BEP.STUDENT_GU
		
WHERE
	UNIQUERECORDS.STUDENT_GU IS NULL 
	AND BEP.EXIT_DATE IS NULL

) AS KIDSBACKDATED
-----------------------------------------------------------------------------------------------------------

LEFT JOIN 
(
SELECT 
	SCH.STUDENT_GU, MAX(COURSE_LEAVE_DATE) AS COURSE_EXIT_DATE
 FROM 
APS.ScheduleForYear('A3F9F1FB-4706-49AA-B3A3-21F153966191') AS SCH
INNER JOIN 
REV.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
WHERE COURSE_LEVEL IN ('BEP', 'ESL') AND COURSE_LEAVE_DATE IS NOT NULL
GROUP BY STUDENT_GU 
) AS ESLBEPCLASSES

ON
KIDSBACKDATED.STUDENT_GU = ESLBEPCLASSES.STUDENT_GU

) AS CLOSEOUT


WHERE

REV.EPC_STU_PGM_ELL_BEP.STU_PGM_ELL_BEP_GU = CLOSEOUT.STU_PGM_ELL_BEP_GU
AND CLOSEOUT.COURSE_EXIT_DATE IS NOT NULL




/*******************************************************************************************

-- FOR RECORDS THAT ARE NOT PULLED WITH THE NIGHTLY PROCESS (BECAUSE OF BACKDATED SCHEDULES)
-- AND DO NOT HAVE A COURSE LEAVE DATE, THESE MAY BE STUDENTS WHERE THE TEACHER CHANGED AND IS NOT QUALIFIED ANYMORE
-- USE CURRENT DATE TO CLOSE OUT 

********************************************************************************************/



UPDATE REV.EPC_STU_PGM_ELL_BEP 
	SET EXIT_DATE = GETDATE(), [CHANGE_ID_STAMP] = '27CDCD0E-BF93-4071-94B2-5DB792BB735F', [CHANGE_DATE_TIME_STAMP] = GETDATE()


FROM (
SELECT 
	
	KIDSBACKDATED.SIS_NUMBER
	,KIDSBACKDATED.STU_PGM_ELL_BEP_GU
	,ESLBEPCLASSES.COURSE_EXIT_DATE

-----------------------FOR THESE STUDENTS -----------------------------------------
FROM (
 SELECT
	STU.STUDENT_GU, STU.SIS_NUMBER, BEP.STU_PGM_ELL_BEP_GU
 FROM 
REV.EPC_STU_PGM_ELL_BEP AS BEP
LEFT JOIN 
(
	SELECT 
		NEWID() AS STU_PGM_ELL_BEP
		,STU.STUDENT_GU AS STUDENT_GU
		,STU.SIS_NUMBER
		,MAX(SCH.COURSE_ENTER_DATE) AS ENTER_DATE
		,LU.VALUE_CODE AS PROGRAM_CODE
		,BEP.[HOUR] AS PROGRAM_INTENSITY
		--, BEP.MODEL, 
		,SCH.COURSE_LEAVE_DATE AS EXIT_DATE
		,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS [ADD_ID_STAMP]
		,GETDATE() AS [ADD_DATE_TIME_STAMP]
		, NULL AS [CHANGE_ID_STAMP]
		, NULL AS [CHANGE_DATE_TIME_STAMP]

	 FROM 
		APS.NewBEPStudentsModelsAndHoursAsOf(GETDATE()) AS BEP
		INNER HASH JOIN 
		REV.EPC_STU AS STU
		ON
		BEP.SIS_NUMBER = STU.SIS_NUMBER
		INNER HASH JOIN 
		APS.NewBEPModelsAndHoursDetailsAsOf(GETDATE()) AS MODELS
		ON
		BEP.SIS_NUMBER = MODELS.SIS_NUMBER
		INNER HASH JOIN 
		APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
		ON
		SCH.SIS_NUMBER = MODELS.SIS_NUMBER
		AND SCH.ORGANIZATION_NAME = MODELS.SCHOOL_NAME
		AND SCH.COURSE_ID = MODELS.COURSE_ID
		AND SCH.SECTION_ID = MODELS.SECTION_ID
		INNER JOIN 
		APS.LookupTable ('K12.ProgramInfo', 'BEP_PROGRAM_CODE') AS LU
		ON
		LU.VALUE_DESCRIPTION = BEP.MODEL

	--WHERE STU.SIS_NUMBER = 980001535

	GROUP BY STU.STUDENT_GU, STU.SIS_NUMBER, BEP.[HOUR], BEP.MODEL, VALUE_CODE, COURSE_LEAVE_DATE
) AS UNIQUERECORDS

	ON
	BEP.STUDENT_GU = UNIQUERECORDS.STUDENT_GU
	INNER JOIN 
	REV.EPC_STU AS STU
	ON
	STU.STUDENT_GU = BEP.STUDENT_GU
		
WHERE
	UNIQUERECORDS.STUDENT_GU IS NULL 
	AND BEP.EXIT_DATE IS NULL

) AS KIDSBACKDATED
-----------------------------------------------------------------------------------------------------------

LEFT JOIN 
(
SELECT 
	SCH.STUDENT_GU, MAX(COURSE_LEAVE_DATE) AS COURSE_EXIT_DATE
 FROM 
APS.ScheduleForYear('A3F9F1FB-4706-49AA-B3A3-21F153966191') AS SCH
INNER JOIN 
REV.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
WHERE COURSE_LEVEL IN ('BEP', 'ESL') AND COURSE_LEAVE_DATE IS NOT NULL
GROUP BY STUDENT_GU 
) AS ESLBEPCLASSES

ON
KIDSBACKDATED.STUDENT_GU = ESLBEPCLASSES.STUDENT_GU

) AS CLOSEOUT


WHERE

REV.EPC_STU_PGM_ELL_BEP.STU_PGM_ELL_BEP_GU = CLOSEOUT.STU_PGM_ELL_BEP_GU
AND
 CLOSEOUT.COURSE_EXIT_DATE IS NULL



 

--Validation Check to see how many records will be processed, 0 = INSERT AND UPDATE, 1 = ROLLBACK - WILL NOT - UPDATE/INSERT
IF @ValidateOnly = 0
	BEGIN
		COMMIT 
	END
ELSE
	BEGIN
		ROLLBACK
	END
	

END



GO


