USE [ST_Production]
GO

/****** Object:  StoredProcedure [APS].[UpdateELLParticipationStatus]    Script Date: 10/12/2017 7:50:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






/************************************************************************

-- UPDATE PARTICIPATION STATUS NIGHTLY BECAUSE STUDENTS SCHEDULES CHANGE

*************************************************************************/



ALTER PROC [APS].[UpdateELLParticipationStatus](
	@ValidateOnly INT
)

AS
BEGIN

BEGIN TRANSACTION


--FIRST INITIALIZE THE FIELD
UPDATE REV.EPC_STU_PGM_ELL_HIS
SET PARTICIPATION_STATUS = NULL
WHERE PARTICIPATION_STATUS IS NOT NULL

--THEN WRITE CURRENT STATUS
UPDATE REV.EPC_STU_PGM_ELL_HIS
SET PARTICIPATION_STATUS = PARTICIPATION
FROM 
(
SELECT * FROM(
SELECT 
	
	CASE 
		-- PARENT REFUSAL MUST BE CURRENT YEAR -- AND PARENT_REFUSAL_STATUS = '' DAC 10/12/2017 PER JESSICA INCLUDE EXPIRED PARENT REFUSALS TO STATE SO THEY DON'T LOOK LIKE THEY'RE NOT RECEIVING SERVICE
		WHEN PARENT_REFUSED = 'Y' AND COURSE_ID IS NULL THEN 6
		-- ELEMENTARY RECEIVING SERVICE
		WHEN COURSE_ID IS NOT NULL AND GRADE IN ('K', '01', '02', '03', '04','05') AND QUALIFIED_CLASS IN ('Y', 'W') THEN 8
		-- SECONDARY RECEIVING SERVICE
		WHEN COURSE_ID IS NOT NULL AND GRADE NOT IN ('K', '01', '02', '03', '04','05') AND QUALIFIED_CLASS IN ('Y', 'W') THEN 9
	ELSE NULL END AS PARTICIPATION

	,COURSE_ID, GRADE, PARENT_REFUSED, STUDENT_GU

 FROM 
APS.LCEStudentsAndProvidersAsOf_2(GETDATE()) AS SERVICED 
INNER JOIN REV.EPC_STU AS STU
ON
SERVICED.SIS_NUMBER = STU.SIS_NUMBER
) AS T2
WHERE
PARTICIPATION IS NOT NULL

) AS T1

WHERE
REV.EPC_STU_PGM_ELL_HIS.EXIT_REASON IS NULL 
AND REV.EPC_STU_PGM_ELL_HIS.EXIT_DATE IS NULL
AND T1.STUDENT_GU = REV.EPC_STU_PGM_ELL_HIS.STUDENT_GU



--Validation Check to see how many records will be processed, 0 = INSERT AND UPDATE, 1 = ROLLBACK - WILL NOT - UPDATE/INSERT
IF @ValidateOnly = 0
	BEGIN
		COMMIT 
	END
ELSE
	BEGIN
		ROLLBACK
	END
		

END



GO


