/*

Data Pull for Brenda Martinez-Pappaoni


APS Graduates from 2008-2009 to 2015-2016:
•	Gender
•	Ethnicity
•	Race
•	Special Education Program
•	Gifted Program
•	FRPL 
•	ELL 
•	Cumulative GPA
•	ACT score if available
•	SAT score if available
•	Reading SBA/PARCC scaled scores and proficiency levels
•	Math SBA/PARCC scaled scores and proficiency levels

The graduates in years 2007 thru 2014 (i.e., 2006-2007 SY – 2013-2014 SY) should have taken the Standards-Based Assessment (SBA) for reading and math.
Graduates 2015 thru 2016 (i.e., 2014-2015 SY – 2015-2016 SY) should have PARCC scores for reading and math.  I would need their final/last year of scores – which would be 11th grade I think.  

*/
; with ACT2008_2013_ENGLISH
as
(
SELECT 
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, LOCAL_SCHOOL_YEAR) AS RN
    ,cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
	,TEST_SUBJECT
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,LOCAL_SCHOOL_YEAR 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_ENG_TEST_SCORE_2008
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_ENG_PERF_LEVEL_2008
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_ENG_TEST_SCORE_2009
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_ENG_PERF_LEVEL_2009
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_ENG_TEST_SCORE_2010
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_ENG_PERF_LEVEL_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_ENG_TEST_SCORE_2011
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_ENG_PERF_LEVEL_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_ENG_TEST_SCORE_2012
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_ENG_PERF_LEVEL_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_ENG_TEST_SCORE_2013
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_ENG_PERF_LEVEL_2013


from
	dbo.APSGrads g
INNER join
	 K12INTEL_DW.DTBL_STUDENTS 
ON
	cast(g.ID as nvarchar) = K12INTEL_dw.DTBL_STUDENTS.STUDENT_ID
left join
	k12intel_dw.FTBL_TEST_SCORES
on
	 DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
left JOIN
	 K12INTEL_DW.DTBL_TESTS
ON
	 DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
inner JOIN
	 K12INTEL_DW.DTBL_SCHOOLS
ON
	 DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
inner JOIN
	 K12INTEL_DW.DTBL_CALENDAR_DATES
ON
	 DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
inner JOIN 
	K12INTEL_DW.DTBL_SCHOOL_DATES
ON
	 DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY
where
	LOCAL_SCHOOL_YEAR IN ('2008-2009', '2009-2010', '2010-2011', '2011-2012', '2012-2013', '2013-2014') AND
	TEST_NAME LIKE 'ACT%' AND TEST_SUBJECT = 'ENGLISH'
	AND TEST_CLASS = 'COMPOSITE'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	LOCAL_SCHOOL_YEAR,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP

	
)
--SELECT MAX(RN) FROM ACT2008_2013
--SELECT * FROM ACT2008_2013_ENGLISH where SIS_NUMBER = 100000355

---------------------------------------------------------------------------------------

,ACT2008_2013_MATH
as
(
SELECT 
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, LOCAL_SCHOOL_YEAR) AS RN
    ,cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
	,TEST_SUBJECT
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,LOCAL_SCHOOL_YEAR 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_MATH_TEST_SCORE_2008
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_MATH_PERF_LEVEL_2008
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_MATH_TEST_SCORE_2009
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_MATH_PERF_LEVEL_2009
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_MATH_TEST_SCORE_2010
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_MATH_PERF_LEVEL_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_MATH_TEST_SCORE_2011
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_MATH_PERF_LEVEL_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_MATH_TEST_SCORE_2012
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_MATH_PERF_LEVEL_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' THEN CAST(TEST_SCORE_VALUE AS INT) ELSE 0 END) AS ACT_MATH_TEST_SCORE_2013
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE '' END) AS ACT_MATH_PERF_LEVEL_2013


from
	dbo.APSGrads g
INNER join
	 K12INTEL_DW.DTBL_STUDENTS 
ON
	cast(g.ID as nvarchar) = K12INTEL_dw.DTBL_STUDENTS.STUDENT_ID
left join
	k12intel_dw.FTBL_TEST_SCORES
on
	 DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
left JOIN
	 K12INTEL_DW.DTBL_TESTS
ON
	 DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
inner JOIN
	 K12INTEL_DW.DTBL_SCHOOLS
ON
	 DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
inner JOIN
	 K12INTEL_DW.DTBL_CALENDAR_DATES
ON
	 DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
inner JOIN 
	K12INTEL_DW.DTBL_SCHOOL_DATES
ON
	 DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY
where
	LOCAL_SCHOOL_YEAR IN ('2008-2009', '2009-2010', '2010-2011', '2011-2012', '2012-2013', '2013-2014') AND
	TEST_NAME LIKE 'ACT%' AND TEST_SUBJECT = 'MATH'
	AND TEST_CLASS = 'COMPOSITE'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	LOCAL_SCHOOL_YEAR,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP

	
)
--SELECT MAX(RN) FROM ACT2008_2013
--SELECT * FROM ACT2008_2013_MATH where sis_number = 100000355


,ACT2008_2013_ENG_RESULTS
AS
(
SELECT
	SIS_NUMBER,
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_TEST_SCORE_2008 ELSE 0 END) AS [ACT_ENG_SCORE_2008],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_PERF_LEVEL_2008 ELSE 0 END) AS [ACT_ENG_PERF_LEVEL_2008],


	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_TEST_SCORE_2009 ELSE 0 END) AS [ACT_ENG_SCORE_2009],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_PERF_LEVEL_2009 ELSE 0 END) AS [ACT_ENG_PERF_LEVEL_2009],

	
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_TEST_SCORE_2010 ELSE 0 END) AS [ACT_ENG_SCORE_2010],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_PERF_LEVEL_2010 ELSE 0 END) AS [ACT_ENG_PERF_LEVEL_2010],


	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_TEST_SCORE_2011 ELSE 0 END) AS [ACT_ENG_SCORE_2011],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_PERF_LEVEL_2011 ELSE 0 END) AS [ACT_ENG_PERF_LEVEL_2011],
	
	
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_TEST_SCORE_2012 ELSE 0 END) AS [ACT_ENG_SCORE_2012],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_PERF_LEVEL_2012 ELSE 0 END) AS [ACT_ENG_PERF_LEVEL_2012],
	
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_TEST_SCORE_2013 ELSE 0 END) AS [ACT_ENG_SCORE_2013],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_PERF_LEVEL_2013 ELSE 0 END) AS [ACT_ENG_PERF_LEVEL_2013]


FROM
	ACT2008_2013_ENGLISH
GROUP BY
	SIS_NUMBER
)
--select * from act_2008_2013_english where sis_number = '100000355'
------------------------------------------------------------------------------------------------

,ACT2008_2013_MATH_RESULTS
AS
(
SELECT
	SIS_NUMBER,
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_TEST_SCORE_2008 ELSE 0 END) AS [ACT_MATH_SCORE_2008],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2008-2009'AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_PERF_LEVEL_2008 ELSE 0 END) AS [ACT_MATH_PERF_LEVEL_2008],


	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_TEST_SCORE_2009 ELSE 0 END) AS [ACT_MATH_SCORE_2009],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_PERF_LEVEL_2009 ELSE 0 END) AS [ACT_MATH_PERF_LEVEL_2009],

	
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_TEST_SCORE_2010 ELSE 0 END) AS [ACT_MATH_SCORE_2010],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_PERF_LEVEL_2010 ELSE 0 END) AS [ACT_MATH_PERF_LEVEL_2010],


	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_TEST_SCORE_2011 ELSE 0 END) AS [ACT_MATH_SCORE_2011],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_PERF_LEVEL_2011 ELSE 0 END) AS [ACT_MATH_PERF_LEVEL_2011],
	
	
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_TEST_SCORE_2012 ELSE 0 END) AS [ACT_MATH_SCORE_2012],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_PERF_LEVEL_2012 ELSE 0 END) AS [ACT_MATH_PERF_LEVEL_2012],
	
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_TEST_SCORE_2013 ELSE 0 END) AS [ACT_MATH_SCORE_2013],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_PERF_LEVEL_2013 ELSE 0 END) AS [ACT_MATH_PERF_LEVEL_2013]

	 
FROM
	ACT2008_2013_MATH
GROUP BY
	SIS_NUMBER
)



--SELECT * FROM ACT2008_2013_RESULTS C 
,ACT2014_2016_ENG
as
(
SELECT 
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, LOCAL_SCHOOL_YEAR) AS RN
    ,cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
	,TEST_SUBJECT
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,LOCAL_SCHOOL_YEAR 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT_ENG_2014
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016' THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT_ENG_2015
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2016-2017' THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT_ENG_2016


FROM
dbo.APSGrads g
INNER join
	 K12INTEL_DW.DTBL_STUDENTS 
ON
	cast(g.ID as nvarchar) = K12INTEL_dw.DTBL_STUDENTS.STUDENT_ID
inner join
	k12intel_dw.FTBL_TEST_SCORES
on
	 DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN
	 K12INTEL_DW.DTBL_TESTS
ON
	 DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 

INNER JOIN
	 K12INTEL_DW.DTBL_SCHOOLS
ON
	 DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN
	 K12INTEL_DW.DTBL_CALENDAR_DATES
ON
	 DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN
	 K12INTEL_DW.DTBL_SCHOOL_DATES
ON
	 DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY

where
	LOCAL_SCHOOL_YEAR IN ('2014-2015', '2015-2016') AND
	TEST_NAME LIKE 'ACT%'  AND TEST_CLASS = 'COMPOSITE' AND TEST_SUBJECT = 'ENGLISH'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	LOCAL_SCHOOL_YEAR,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP

	
)

--SELECT * from ACT2014_2016
--select max(RN) FROM ACT2014_2016

,ACT_2004_2016_MATH
as
(
SELECT 
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, LOCAL_SCHOOL_YEAR) AS RN
    ,cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
	,TEST_SUBJECT
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,LOCAL_SCHOOL_YEAR 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT_MATH_2014
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016' THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT_MATH_2015
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2016-2017' THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT_MATH_2016


FROM
dbo.APSGrads g
INNER join
	 K12INTEL_DW.DTBL_STUDENTS 
ON
	cast(g.ID as nvarchar) = K12INTEL_dw.DTBL_STUDENTS.STUDENT_ID
inner join
	k12intel_dw.FTBL_TEST_SCORES
on
	 DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN
	 K12INTEL_DW.DTBL_TESTS
ON
	 DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 

INNER JOIN
	 K12INTEL_DW.DTBL_SCHOOLS
ON
	 DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN
	 K12INTEL_DW.DTBL_CALENDAR_DATES
ON
	 DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN
	 K12INTEL_DW.DTBL_SCHOOL_DATES
ON
	 DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY

where
	LOCAL_SCHOOL_YEAR IN ('2014-2015', '2015-2016') AND
	TEST_NAME LIKE 'ACT%'  AND TEST_CLASS = 'COMPOSITE' AND TEST_SUBJECT = 'MATH'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	LOCAL_SCHOOL_YEAR,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP

	
)

--SELECT * FROM ACT_2004_2016_MATH
,ACT2004_2016_ENG_RESULTS
AS
(
SELECT
	SIS_NUMBER,
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_2014 ELSE 0 END) AS [ACT_ENG_SCORE_2014],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2015-2016' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_2015 ELSE 0 END) AS [ACT_ENG_SCORE_2015],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2016-2017' AND TEST_SUBJECT = 'ENGLISH' THEN ACT_ENG_2016 ELSE 0 END) AS [ACT_ENG_SCORE_2016]
FROM
	ACT2014_2016_ENG
GROUP BY
	SIS_NUMBER
)

--SELECT * FROM ACT2004_2016_ENG_RESULTS

-------------------------------------------

,ACT2004_2016_MATH_RESULTS
AS
(
SELECT
	SIS_NUMBER,
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_2014 ELSE 0 END) AS [ACT_MATH_SCORE_2014],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2015-2016' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_2015 ELSE 0 END) AS [ACT_MATH_SCORE_2015],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2016-2017' AND TEST_SUBJECT = 'MATH' THEN ACT_MATH_2016 ELSE 0 END) AS [ACT_MATH_SCORE_2016]
FROM
	ACT_2004_2016_MATH
GROUP BY
	SIS_NUMBER
)
/*-------------------------------------------*/

,SAT
as
(
SELECT 
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, LOCAL_SCHOOL_YEAR) AS RN,
    cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
	,TEST_SUBJECT
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,LOCAL_SCHOOL_YEAR 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
    --,TEST_SCORE_VALUE 
    --,CAST(TEST_PRIMARY_RESULT AS NVARCHAR) AS PERFORMANCE_LEVEL
    --,CAST(SIS_SCHOOL_YEAR AS NVARCHAR) AS SCHOOL_YEAR
    --,CAST(TEST_CLASS AS nvarchar) AS TEST_CLASS
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP

	--no data for 2008-2010

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2011

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2012

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2013
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2013
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2013

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2014
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2014
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2014


	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016' AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2015
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016' AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2015
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016' AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2015


	--,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2016
	--,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2016
	--,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2016



FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY
inner join
dbo.APSGrads g
on CAST(g.ID AS NVARCHAR) = STUDENT_id
WHERE 
1 = 1
AND TEST_NAME like 'SAT%'
AND LOCAL_SCHOOL_YEAR in ('2011-2012', '2012-2013', '2013-2014', '2014-2015', '2015-2016')
--AND TEST_SUBGROUP IN ('Reading', 'Mathematics', 'Writing')
--AND TEST_GROUP = 'Test'
--and test_class = 'COMPONENT'
--and TEST_SUBJECT = 'overall'
--AND TEST_SUBGROUP IN ('TOT','Composite')
--AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUDENT_ID = '102903861'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	LOCAL_SCHOOL_YEAR,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP
	
)
--SELECT MAX(RN) FROM SAT
--SELECT * FROM SAT WHERE SIS_NUMBER = 244133286


,SAT_Results
as
(
SELECT
		--RN,
		SIS_NUMBER,
		--TEST_NAME,
		--TEST_SUBJECT,
		--TEST_STUDENT_GRADE,
		--TEST_PRODUCT,
		--TEST_GROUP,
		--TEST_SUBGROUP,
		
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2011 ELSE 0 END) AS [SAT_READING_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2011 ELSE 0 END) AS [SAT_WRITING_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2011 ELSE 0 END) AS [SAT_MATH_SCORE_2011],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2012 ELSE 0 END) AS [SAT_READING_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2012 ELSE 0 END) AS [SAT_WRITING_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2012 ELSE 0 END) AS [SAT_MATH_SCORE_2012],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2013 ELSE 0 END) AS [SAT_READING_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2013 ELSE 0 END) AS [SAT_WRITING_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2013 ELSE 0 END) AS [SAT_MATH_SCORE_2013],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2014 ELSE 0 END) AS [SAT_READING_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2014 ELSE 0 END) AS [SAT_WRITING_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2014 ELSE 0 END) AS [SAT_MATH_SCORE_2014],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2015-2016' AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2015 ELSE 0 END) AS [SAT_READING_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2015-2016' AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2015 ELSE 0 END) AS [SAT_WRITING_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2015-2016' AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2015 ELSE 0 END) AS [SAT_MATH_SCORE_2015]

FROM SAT

group by

	SIS_NUMBER
	
)

--select * from SAT_Results --where SIS_NUMBER = 102696358
/*-----------------------------------------------------------------*/

,SBA_2007_2013_MATH
AS
(
SELECT
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, LOCAL_SCHOOL_YEAR) as rn,
    cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
    ,TEST_NAME
	,TEST_SUBJECT
    ,TEST_STUDENT_GRADE
    ,LOCAL_SCHOOL_YEAR 
	,CAST(TEST_SCALED_SCORE AS INT) AS SCALED_SCORE
    ,CAST(TEST_PRIMARY_RESULT AS NVARCHAR) AS PERFORMANCE_LEVEL
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,TEST_PRODUCT

	/* note school_year is 2007-2008, but LOCAL_SCHOOL_YEAR is 2008 */
	--,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2007-2008' AND TEST_GROUP = 'MATH' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_MATH_SCALED_SCORE_2007
	--,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2007-2008' AND TEST_GROUP = 'MATH' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_MATH_PERF_LEVEL_2007
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'MATH' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_MATH_SCALED_SCORE_2008
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'MATH' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_MATH_PERF_LEVEL_2008
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'MATH' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_MATH_SCALED_SCORE_2009
	,MAX(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'MATH' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_MATH_PERF_LEVEL_2009
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'MATH' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_MATH_SCALED_SCORE_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'MATH' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_MATH_PERF_LEVEL_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'MATH' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_MATH_SCALED_SCORE_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'MATH' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_MATH_PERF_LEVEL_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'MATH' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_MATH_SCALED_SCORE_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'MATH' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_MATH_PERF_LEVEL_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'MATH' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_MATH_SCALED_SCORE_2013
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'MATH' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_MATH_PERF_LEVEL_2013

	FROM K12INTEL_DW.FTBL_TEST_SCORES
	INNER JOIN K12INTEL_DW.DTBL_TESTS
	ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
	INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
	ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
	INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
	ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
	INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
	ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
	INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
	ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY
	inner join
	dbo.APSGrads g
	on CAST(g.ID AS NVARCHAR) = STUDENT_id
	WHERE 
	1 = 1
	AND TEST_PRODUCT LIKE 'SBA%'
	AND LOCAL_SCHOOL_YEAR in ('2007-2008','2008-2009', '2009-2010', '2010-2011', '2011-2012', '2012-2013', '2013-2014')
	AND TEST_GROUP in ('Math')
	AND TEST_CLASS = 'COMPOSITE'
	GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	LOCAL_SCHOOL_YEAR,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP,
	FTBL_TEST_SCORES.TEST_SCALED_SCORE,
	FTBL_TEST_SCORES.TEST_PRIMARY_RESULT
	
)
--SELECT MAX(RN) FROM SBA_2007_2013_MATH
--SELECT * FROM SBA_2007_2013_MATH WHERE SIS_NUMBER = '100003516'

,SBA_2007_2013_READING
AS
(
SELECT
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, LOCAL_SCHOOL_YEAR) as rn,
    cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
    ,TEST_NAME
	,TEST_SUBJECT
    ,TEST_STUDENT_GRADE
    ,LOCAL_SCHOOL_YEAR 
	,CAST(TEST_SCALED_SCORE AS INT) AS SCALED_SCORE
    ,CAST(TEST_PRIMARY_RESULT AS NVARCHAR) AS PERFORMANCE_LEVEL
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,TEST_PRODUCT

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2007-2008' AND TEST_GROUP = 'READING' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_READING_SCALED_SCORE_2007
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2007-2008' AND TEST_GROUP = 'READING' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_READING_PERF_LEVEL_2007
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'READING' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_READING_SCALED_SCORE_2008
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'READING' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_READING_PERF_LEVEL_2008
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'READING' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_READING_SCALED_SCORE_2009
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'READING' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_READING_PERF_LEVEL_2009
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'READING' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_READING_SCALED_SCORE_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'READING' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_READING_PERF_LEVEL_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'READING' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_READING_SCALED_SCORE_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'READING' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_READING_PERF_LEVEL_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'READING' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_READING_SCALED_SCORE_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'READING' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_READING_PERF_LEVEL_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'READING' THEN CAST(TEST_SCALED_SCORE AS INT) ELSE 0 END) AS SBA_READING_SCALED_SCORE_2013
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'READING' THEN CAST(TEST_PRIMARY_RESULT AS NVARCHAR) ELSE ' ' END) AS SBA_READING_PERF_LEVEL_2013


FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY
inner join
dbo.APSGrads g
on CAST(g.ID AS NVARCHAR) = STUDENT_id
WHERE 
1 = 1
AND TEST_PRODUCT LIKE 'SBA%'
AND LOCAL_SCHOOL_YEAR in ('2007-2008', '2008-2009', '2009-2010', '2010-2011', '2011-2012', '2012-2013', '2013-2014')
--AND TEST_SUBGROUP IN ('Total Math')
AND TEST_GROUP in ('READING')
AND TEST_CLASS = 'COMPOSITE'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	LOCAL_SCHOOL_YEAR,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP,
	FTBL_TEST_SCORES.TEST_SCALED_SCORE,
	FTBL_TEST_SCORES.TEST_PRIMARY_RESULT
	
)
--SELECT MAX(RN) FROM SBA_2007_2013_READING
--SELECT * FROM SBA_2007_2013_READING WHERE SIS_NUMBER = '100003516'

,SBA_READING_RESULTS
AS
(
SELECT
		--RN,
		SIS_NUMBER,
		--TEST_NAME,
		--TEST_SUBJECT,
		--TEST_STUDENT_GRADE,
		--TEST_PRODUCT,
		--TEST_GROUP,
		--TEST_SUBGROUP,
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2007-2008' AND TEST_GROUP = 'READING' THEN SBA_READING_SCALED_SCORE_2007 ELSE 0 END) AS [SBA_READING_SCORE_2007],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2007-2008' AND TEST_GROUP = 'READING' THEN SBA_READING_PERF_LEVEL_2007 ELSE '' END) AS [SBA_READING_PERF_LEVEL_2007],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'READING' THEN SBA_READING_SCALED_SCORE_2008 ELSE 0 END) AS [SBA_READING_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'READING' THEN SBA_READING_PERF_LEVEL_2008 ELSE '' END) AS [SBA_READING_PERF_LEVEL_2008],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'READING' THEN SBA_READING_SCALED_SCORE_2009 ELSE 0 END) AS [SBA_READING_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'READING' THEN SBA_READING_PERF_LEVEL_2009 ELSE '' END) AS [SBA_READING_PERF_LEVEL_2009],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'READING' THEN SBA_READING_SCALED_SCORE_2010 ELSE 0 END) AS [SBA_READING_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'READING' THEN SBA_READING_PERF_LEVEL_2010 ELSE '' END) AS [SBA_READING_PERF_LEVEL_2010],
				
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'READING' THEN SBA_READING_SCALED_SCORE_2011 ELSE 0 END) AS [SBA_READING_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'READING' THEN SBA_READING_PERF_LEVEL_2011 ELSE '' END) AS [SBA_READING_PERF_LEVEL_2011],
				
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'READING' THEN SBA_READING_SCALED_SCORE_2012 ELSE 0 END) AS [SBA_READING_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'READING' THEN SBA_READING_PERF_LEVEL_2012 ELSE '' END) AS [SBA_READING_PERF_LEVEL_2012],
				
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'READING' THEN SBA_READING_SCALED_SCORE_2013 ELSE 0 END) AS [SBA_READING_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'READING' THEN SBA_READING_PERF_LEVEL_2013 ELSE '' END) AS [SBA_READING_PERF_LEVEL_2013]
		
FROM SBA_2007_2013_READING

group by

	SIS_NUMBER
)
	--SELECT * FROM SBA_READING_RESULTS

---------------------------------------------------------------------------------------------------------------
,SBA_MATH_RESULTS
AS
(
SELECT
		--RN,
		SIS_NUMBER,
		--TEST_NAME,
		--TEST_SUBJECT,
		--TEST_STUDENT_GRADE,
		--TEST_PRODUCT,
		--TEST_GROUP,
		--TEST_SUBGROUP,
		--MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2007-2008' AND TEST_GROUP = 'MATH' THEN SBA_MATH_SCALED_SCORE_2007 ELSE 0 END) AS [SBA_MATH_SCORE_2007],
		--MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2007-2008' AND TEST_GROUP = 'MATH' THEN SBA_MATH_PERF_LEVEL_2007 ELSE '' END) AS [SBA_MATH_PERF_LEVEL_2007],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'MATH' THEN SBA_MATH_SCALED_SCORE_2008 ELSE 0 END) AS [SBA_MATH_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'MATH' THEN SBA_MATH_PERF_LEVEL_2008 ELSE '' END) AS [SBA_MATH_PERF_LEVEL_2008],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'MATH' THEN SBA_MATH_SCALED_SCORE_2009 ELSE 0 END) AS [SBA_MATH_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'MATH' THEN SBA_MATH_PERF_LEVEL_2009 ELSE '' END) AS [SBA_MATH_PERF_LEVEL_2009],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'MATH' THEN SBA_MATH_SCALED_SCORE_2010 ELSE 0 END) AS [SBA_MATH_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'MATH' THEN SBA_MATH_PERF_LEVEL_2010 ELSE '' END) AS [SBA_MATH_PERF_LEVEL_2010],
				
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'MATH' THEN SBA_MATH_SCALED_SCORE_2011 ELSE 0 END) AS [SBA_MATH_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'MATH' THEN SBA_MATH_PERF_LEVEL_2011 ELSE '' END) AS [SBA_MATH_PERF_LEVEL_2011],
				
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'MATH' THEN SBA_MATH_SCALED_SCORE_2012 ELSE 0 END) AS [SBA_MATH_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'MATH' THEN SBA_MATH_PERF_LEVEL_2012 ELSE '' END) AS [SBA_MATH_PERF_LEVEL_2012],
				
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'MATH' THEN SBA_MATH_SCALED_SCORE_2013 ELSE 0 END) AS [SBA_MATH_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'MATH' THEN SBA_MATH_PERF_LEVEL_2013 ELSE '' END) AS [SBA_MATH_PERF_LEVEL_2013]
		
FROM SBA_2007_2013_MATH

group by

	SIS_NUMBER
)
	--SELECT * FROM SBA_MATH_RESULTS
/*-----------------------------------------------------------------*/
, PARCC
as
(
SELECT
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, LOCAL_SCHOOL_YEAR) AS RN,
    cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
	,TEST_SUBJECT
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,LOCAL_SCHOOL_YEAR 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
    --,TEST_SCORE_VALUE 
    --,CAST(TEST_PRIMARY_RESULT AS NVARCHAR) AS PERFORMANCE_LEVEL
    --,CAST(SIS_SCHOOL_YEAR AS NVARCHAR) AS SCHOOL_YEAR
    --,CAST(TEST_CLASS AS nvarchar) AS TEST_CLASS
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,TEST_SCORE_VALUE

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2008
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2008
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2008
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2008
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2008

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2009
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2009
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2009
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2009
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2009

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2010
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2010

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2011
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2011

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2012
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2012

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2013
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2013
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2013
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2013
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2013

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2014
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2014
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2014
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2014
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2014

	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2015
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2015
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2015
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2015
	,max(CASE WHEN LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2015

	--,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2016
	--,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2016
	--,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2016
	--,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2016
	--,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2016

FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY
inner join
dbo.APSGrads g
on CAST(g.ID AS NVARCHAR) = STUDENT_id
WHERE 
1 = 1
AND TEST_NAME like 'PARCC%'
AND LOCAL_SCHOOL_YEAR in ('2014-2015', '2015-2016')
AND TEST_SUBGROUP IN ('Overall')
--AND TEST_GROUP = 'Test'
--and test_class = 'COMPONENT'
--and TEST_SUBJECT = 'overall'
--AND TEST_SUBGROUP IN ('TOT','Composite')
--AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUDENT_ID = '318463353'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	LOCAL_SCHOOL_YEAR,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP,
	test_score_value
	
)
--SELECT MAX(RN) FROM PARCC
--SELECT * FROM PARCC WHERE SIS_NUMBER = 100020064 ORDER BY YEAR_VALUE --where SIS_NUMBER in ('61740', '71975', '76476', '186878', '187738', '188747', '189884')

,PARCC_Results
as
(
SELECT
		--RN,
		SIS_NUMBER,
		--TEST_NAME,
		--TEST_SUBJECT,
		--TEST_STUDENT_GRADE,
		--TEST_PRODUCT,
		--TEST_GROUP,
		--TEST_SUBGROUP,

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2008 ELSE 0 END) AS [PARCC_ELA_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2008 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2008 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2008 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2008-2009' AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2008 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2008],
		
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2009 ELSE 0 END) AS [PARCC_ELA_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2009 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2009 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2009 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2009-2010' AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2009 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2009],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2010 ELSE 0 END) AS [PARCC_ELA_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2010 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2010 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2010 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2010-2011' AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2010 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2010],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2011 ELSE 0 END) AS [PARCC_ELA_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2011 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2011 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2011 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2011-2012' AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2011 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2011],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2012 ELSE 0 END) AS [PARCC_ELA_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2012 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2012 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2012 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2012-2013' AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2012 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2012],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2013 ELSE 0 END) AS [PARCC_ELA_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2013 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2013 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2013 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2013-2014' AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2013 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2013],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2014 ELSE 0 END) AS [PARCC_ELA_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2014 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2014 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2014 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2014-2015' AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2014 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2014],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2015 ELSE 0 END) AS [PARCC_ELA_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2015 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2015 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2015 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND LOCAL_SCHOOL_YEAR = '2015-2016'  AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2015 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2015]

		--MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2016 ELSE 0 END) AS [PARCC_ELA_SCORE_2016],
		--MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2016 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2016],
		--MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2016 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2016],
		--MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2016 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2016],
		--MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2016 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2016]

FROM PARCC

group by

	SIS_NUMBER
)
--SELECT * FROM PARCC_Results

,All_Test_Results
as
(
select
	ROW_NUMBER() over(partition by cast(g.id as nvarchar) order by cast(g.id as nvarchar)) as RN,
	CAST(G.ID AS NVARCHAR) AS SIS_NUMBER,
	isnull(A.ACT_ENG_SCORE_2008,0) AS ACT_ENG_SCORE_2008,
	ISNULL(A.ACT_ENG_SCORE_2009,0) AS ACT_ENG_SCORE_2009,
	ISNULL(A.ACT_ENG_SCORE_2010,0) AS ACT_ENG_SCORE_2010,
	ISNULL(A.ACT_ENG_SCORE_2011,0) AS ACT_ENG_SCORE_2011,
	ISNULL(A.ACT_ENG_SCORE_2012,0) AS ACT_ENG_SCORE_2012,
	ISNULL(A.ACT_ENG_SCORE_2013,0) AS ACT_ENG_SCORE_2013,
	isnull(A2.ACT_MATH_SCORE_2008,0) AS ACT_MATH_SCORE_2008,
	ISNULL(A2.ACT_MATH_SCORE_2009,0) AS ACT_MATH_SCORE_2009,
	ISNULL(A2.ACT_MATH_SCORE_2010,0) AS ACT_MATH_SCORE_2010,
	ISNULL(A2.ACT_MATH_SCORE_2011,0) AS ACT_MATH_SCORE_2011,
	ISNULL(A2.ACT_MATH_SCORE_2012,0) AS ACT_MATH_SCORE_2012,
	ISNULL(A2.ACT_MATH_SCORE_2013,0) AS ACT_MATH_SCORE_2013,

	ISNULL(A3.ACT_ENG_SCORE_2014,0) AS ACT_ENG_SCORE_2014, 
	ISNULL(A3.ACT_ENG_SCORE_2015,0) AS ACT_ENG_SCORE_2015,

	ISNULL(A4.ACT_MATH_SCORE_2014,0) AS ACT_MATH_SCORE_2014, 
	ISNULL(A4.ACT_MATH_SCORE_2015,0) AS ACT_MATH_SCORE_2015,

	--A2.ACT_SCORE_2016,
	ISNULL(S.SAT_MATH_SCORE_2011,0) AS SAT_MATH_SCORE_2011,
	ISNULL(S.SAT_READING_SCORE_2011,0) AS SAT_READING_SCORE_2011,
	ISNULL(S.SAT_MATH_SCORE_2012,0) AS SAT_MATH_SCORE_2012,
	ISNULL(S.SAT_READING_SCORE_2012,0) AS SAT_READING_SCORE_2012,
	ISNULL(S.SAT_MATH_SCORE_2013,0) AS SAT_MATH_SCORE_2013,
	ISNULL(S.SAT_READING_SCORE_2013,0) AS SAT_READING_SCORE_2013,
	ISNULL(S.SAT_MATH_SCORE_2014,0) AS SAT_MATH_SCORE_2014,
	ISNULL(S.SAT_READING_SCORE_2014,0) AS SAT_READING_SCORE_2014,
	ISNULL(S.SAT_MATH_SCORE_2015,0) AS SAT_MATH_SCORE_2015,
	ISNULL(S.SAT_READING_SCORE_2015,0) AS SAT_READING_SCORE_2015,


	ISNULL(P.PARCC_ELA_SCORE_2008,0) AS PARCC_ELA_SCORE_2008,
	ISNULL(P.PARCC_ALGEBRA_I_SCORE_2008,0) AS PARCC_ALGEBRA_I_SCORE_2008,
	ISNULL(P.PARCC_ALGEBRA_II_SCORE_2008, 0) AS PARCC_ALGEBRA_II_SCORE_2008,
	ISNULL(P.PARCC_GEOMETRY_SCORE_2008,0) AS PARCC_GEOMETRY_SCORE_2008,
	ISNULL(P.PARCC_INT_MATH_SCORE_2008,0) AS PARCC_INT_MATH_SCORE_2008,
	ISNULL(P.PARCC_ELA_SCORE_2009,0) AS PARCC_ELA_SCORE_2009,
	ISNULL(P.PARCC_ALGEBRA_I_SCORE_2009,0) AS PARCC_ALGEBRA_I_SCORE_2009,
	ISNULL(P.PARCC_ALGEBRA_II_SCORE_2009,0) AS PARCC_ALGEBRA_II_SCORE_2009,
	ISNULL(P.PARCC_GEOMETRY_SCORE_2009,0) AS PARCC_GEOMETRY_SCORE_2009,
	ISNULL(P.PARCC_INT_MATH_SCORE_2009,0) AS PARCC_INT_MATH_SCORE_2009,
	ISNULL(P.PARCC_ELA_SCORE_2010,0) AS PARCC_ELA_SCORE_2010,
	ISNULL(P.PARCC_ALGEBRA_I_SCORE_2010,0) AS PARCC_ALGEBRA_I_SCORE_2010,
	ISNULL(P.PARCC_ALGEBRA_II_SCORE_2010,0) AS PARCC_ALGEBRA_II_SCORE_2010,
	ISNULL(P.PARCC_GEOMETRY_SCORE_2010,0) AS PARCC_GEOMETRY_SCORE_2010,
	ISNULL(P.PARCC_INT_MATH_SCORE_2010,0) AS PARCC_INT_MATH_SCORE_2010,
	ISNULL(P.PARCC_ELA_SCORE_2011,0) AS PARCC_ELA_SCORE_2011,
	ISNULL(P.PARCC_ALGEBRA_I_SCORE_2011,0) AS PARCC_ALGEBRA_I_SCORE_2011,
	ISNULL(P.PARCC_ALGEBRA_II_SCORE_2011,0) AS PARCC_ALGEBRA_II_SCORE_2011,
	ISNULL(P.PARCC_GEOMETRY_SCORE_2011,0) AS PARCC_GEOMETRY_SCORE_2011,
	ISNULL(P.PARCC_INT_MATH_SCORE_2011,0) AS PARCC_INT_MATH_SCORE_2011,
	ISNULL(P.PARCC_ELA_SCORE_2012,0) AS PARCC_ELA_SCORE_2012,
	ISNULL(P.PARCC_ALGEBRA_I_SCORE_2012,0) AS PARCC_ALGEBRA_I_SCORE_2012,
	ISNULL(P.PARCC_ALGEBRA_II_SCORE_2012,0) AS PARCC_ALGEBRA_II_SCORE_2012,
	ISNULL(P.PARCC_GEOMETRY_SCORE_2012,0) AS PARCC_GEOMETRY_SCORE_2012,
	ISNULL(P.PARCC_INT_MATH_SCORE_2012,0) AS PARCC_INT_MATH_SCORE_2012,
	ISNULL(P.PARCC_ELA_SCORE_2013,0) AS PARCC_ELA_SCORE_2013,
	ISNULL(P.PARCC_ALGEBRA_I_SCORE_2013,0) AS PARCC_ALGEBRA_I_SCORE_2013,
	ISNULL(P.PARCC_ALGEBRA_II_SCORE_2013,0) AS PARCC_ALGEBRA_II_SCORE_2013,
	ISNULL(P.PARCC_GEOMETRY_SCORE_2013,0) AS PARCC_GEOMETRY_SCORE_2013,
	ISNULL(P.PARCC_INT_MATH_SCORE_2013,0) AS PARCC_INT_MATH_SCORE_2013,
	ISNULL(P.PARCC_ELA_SCORE_2014,0) AS PARCC_ELA_SCORE_2014,
	ISNULL(P.PARCC_ALGEBRA_I_SCORE_2014,0) AS PARCC_ALGEBRA_I_SCORE_2014,
	ISNULL(P.PARCC_ALGEBRA_II_SCORE_2014,0) AS PARCC_ALGEBRA_II_SCORE_2014,
	ISNULL(P.PARCC_GEOMETRY_SCORE_2014,0) AS PARCC_GEOMETRY_SCORE_2014,
	ISNULL(P.PARCC_INT_MATH_SCORE_2014,0) AS PARCC_INT_MATH_SCORE_2014,
	ISNULL(P.PARCC_ELA_SCORE_2015,0) AS PARCC_ELA_SCORE_2015,
	ISNULL(P.PARCC_ALGEBRA_I_SCORE_2015,0) AS PARCC_ALGEBRA_I_SCORE_2015,
	ISNULL(P.PARCC_ALGEBRA_II_SCORE_2015,0) AS PARCC_ALGEBRA_II_SCORE_2015,
	ISNULL(p.PARCC_GEOMETRY_SCORE_2015,0) AS PARCC_GEOMETRY_SCORE_2015,
	ISNULL(P.PARCC_INT_MATH_SCORE_2015,0) AS PARCC_INT_MATH_SCORE_2015,

	--ISNULL(SBAM.SBA_MATH_SCORE_2007,0) AS SBA_MATH_SCALED_SCORE_2007,
	--ISNULL(SBAM.SBA_MATH_PERF_LEVEL_2007, '') AS SBA_MATH_PERF_LEVEL_2007,

	--ISNULL(SBAR.SBA_READING_SCORE_2007,0) AS SBA_READING_SCALED_SCORE_2007,
	--ISNULL(SBAR.SBA_READING_PERF_LEVEL_2007,'') AS SBA_READING_PERF_LEVEL_2007,

	ISNULL(SBAM.SBA_MATH_SCORE_2008,0) AS SBA_MATH_SCALED_SCORE_2008,
	ISNULL(SBAM.SBA_MATH_PERF_LEVEL_2008,'') AS SBA_MATH_PERF_LEVEL_2008,

	ISNULL(SBAR.SBA_READING_SCORE_2008,0) AS SBA_READING_SCALED_SCORE_2008,
	ISNULL(SBAR.SBA_READING_PERF_LEVEL_2008,'') AS SBA_READING_PERF_LEVEL_2008,

	ISNULL(SBAM.SBA_MATH_SCORE_2009,0) AS SBA_MATH_SCALED_SCORE_2009,
	ISNULL(SBAM.SBA_MATH_PERF_LEVEL_2009,'') AS SBA_MATH_PERF_LEVEL_2009,


	ISNULL(SBAR.SBA_READING_SCORE_2009,0) AS SBA_READING_SCALED_SCORE_2009,
	ISNULL(SBAR.SBA_READING_PERF_LEVEL_2009,'') AS SBA_READING_PERF_LEVEL_2009,

	ISNULL(SBAM.SBA_MATH_SCORE_2010,0) AS SBA_MATH_SCALED_SCORE_2010,
	ISNULL(SBAM.SBA_MATH_PERF_LEVEL_2010,'') AS SBA_MATH_PERF_LEVEL_2010,

	ISNULL(SBAR.SBA_READING_SCORE_2010,0) AS SBA_READING_SCALED_SCORE_2010,
	ISNULL(SBAR.SBA_READING_PERF_LEVEL_2010,'') AS SBA_READING_PERF_LEVEL_2010,

	ISNULL(SBAM.SBA_MATH_SCORE_2011,0) AS SBA_MATH_SCALED_SCORE_2011,
	ISNULL(SBAM.SBA_MATH_PERF_LEVEL_2011,'') AS SBA_MATH_PERF_LEVEL_2011,

	ISNULL(SBAR.SBA_READING_SCORE_2011,0) AS SBA_READING_SCALED_SCORE_2011,
	ISNULL(SBAR.SBA_READING_PERF_LEVEL_2011,'') AS SBA_READING_PERF_LEVEL_2011,

	ISNULL(SBAM.SBA_MATH_SCORE_2012,0) AS SBA_MATH_SCALED_SCORE_2012,
	ISNULL(SBAM.SBA_MATH_PERF_LEVEL_2012,'') AS SBA_MATH_PERF_LEVEL_2012,

	ISNULL(SBAR.SBA_READING_SCORE_2012,0) AS SBA_READING_SCALED_SCORE_2012,
	ISNULL(SBAR.SBA_READING_PERF_LEVEL_2012,'') AS SBA_READING_PERF_LEVEL_2012,

	ISNULL(SBAM.SBA_MATH_SCORE_2013,0) AS SBA_MATH_SCALED_SCORE_2013,
	ISNULL(SBAM.SBA_MATH_PERF_LEVEL_2013,'') AS SBA_MATH_PERF_LEVEL_2013,

	ISNULL(SBAR.SBA_READING_SCORE_2013,0) AS SBA_READING_SCALED_SCORE_2013,
	ISNULL(SBAR.SBA_READING_PERF_LEVEL_2013,'') AS SBA_READING_PERF_LEVEL_2013
	

from
	dbo.APSGrads G
LEFT JOIN
	ACT2008_2013_ENG_RESULTS A
ON
	A.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	ACT2008_2013_MATH_RESULTS A2
ON
	A2.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	ACT2004_2016_ENG_RESULTS A3
ON
	A3.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	ACT2004_2016_MATH_RESULTS A4
ON
	A4.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	SAT_Results S
ON
	S.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	PARCC_Results P
ON
	P.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	SBA_MATH_RESULTS SBAM
ON
	SBAM.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	SBA_READING_RESULTS SBAR
ON
	SBAR.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
)
--TRUNCATE TABLE DBO.ALLTESTRESULTS

/* create file and export to production to get the rest of the needed information */
--SELECT * INTO DBO.ALLTESTRESULTS FROM All_Test_Results 

--SELECT * FROM All_Test_Results --WHERE SIS_NUMBER = 100000355




--	select * from aps.CumGPA where SIS_NUMBER = '100060144'

--select
--	t.*,
--	bs.LAST_NAME,
--	bs.FIRST_NAME,
--	bs.GENDER,
--	bs.HISPANIC_INDICATOR,
--	bs.RESOLVED_RACE,
--	bs.SPED_STATUS,
--	bs.GIFTED_STATUS,
--	bs.LUNCH_STATUS,
--	bs.ELL_STATUS,
--	gpa.[HS Cum Flat],
--	gpa.[HS Cum Weighted]
--from                                                                                                     
--	dbo.alltestresults t
--left join
--	aps.BasicStudentWithMoreInfo bs
--on
--	t.sis_number = bs.SIS_NUMBER
--inner join
--	aps.CumGPA gpa
--on
--	t.sis_number = gpa.SIS_NUMBER
--ORDER BY
--	SIS_NUMBER

