/*
Pull data for for Beata
Council of the Great City Schools CGCS
KPI Request
*/


--***********************************************************
--total student enrollments from RDAVM/Synergy Data Set 1
; WITH STUDENTCTE 
AS
(
SELECT 
		'2015-2016' AS [SURVEY SCHOOL YEAR]
		,BS.SIS_NUMBER AS [APS ID]
		,[STUDENT ID] AS [STATE ID]
		--,ORG.ORGANIZATION_NAME AS [SCHOOL NAME]
		,BS.GENDER
		--,BS.HISPANIC_INDICATOR
		,BS.RACE_1
		,BS.RACE_2
		,BS.RACE_3
		,BS.RACE_4
		,BS.RACE_5
		,BS.RESOLVED_RACE
		,CASE	
			WHEN SPED_STATUS = 'Y' and GIFTED_STATUS = 'Y' 
				THEN 'N'
			WHEN SPED_STATUS = 'N' AND GIFTED_STATUS = 'N'
				THEN 'N'
			WHEN SPED_STATUS = 'Y' AND GIFTED_STATUS = 'N'
				THEN 'Y'
		END AS SPED_STATUS
		,BS.PRIMARY_DISABILITY_CODE
		,LU.VALUE_DESCRIPTION AS [PRIMARY DISABILITY DESCRIPTION]
		,CASE
			WHEN [ENGLISH PROFICIENCY] = '0' THEN 'Never Enrolled'
			WHEN [ENGLISH PROFICIENCY] = '1' THEN 'Currently Enrolled'
			WHEN [ENGLISH PROFICIENCY] = '2' THEN 'Exited One Year'
			WHEN [ENGLISH PROFICIENCY] = '3' THEN 'Exited Two Years'
			WHEN [ENGLISH PROFICIENCY] = '4' THEN 'Exited Three + Years'
		END AS [ELL STATUS]
		,E.EXIT_DATE
		,STARS.[ECONOMIC STATUS /FOOD PGM PARTICIPATION/] AS LUNCH_STATUS
		,[CURRENT GRADE LEVEL] AS [STUDENT GRADE LEVEL 2015]
		,p.AP_INDICATOR
		,p.DUAL_CREDIT
		,c.IB_INDICATOR
		,ROW_NUMBER() over(partition by BS.SIS_NUMBER order by bs.SIS_NUMBER) as RN
	FROM
	[RDAVM.APS.EDU.ACTD].[db_STARS_History].[dbo].[STUD_SNAPSHOT]  AS STARS
	LEFT JOIN 
	rev.EPC_SCH AS SCH
	ON
	STARS.[LOCATION CODE] = SCH.STATE_SCHOOL_CODE
	INNER JOIN 
	rev.REV_ORGANIZATION AS ORG
	ON
	ORG.ORGANIZATION_GU = SCH.ORGANIZATION_GU
	LEFT JOIN 
	APS.BasicStudentWithMoreInfo AS BS
	ON
	BS.SIS_NUMBER = [ALTERNATE STUDENT ID]
	LEFT JOIN 
	APS.LookupTable('K12.SpecialEd','DISABILITY_CODE') AS LU
	ON
	LU.VALUE_CODE = BS.PRIMARY_DISABILITY_CODE	
	LEFT JOIN 
	rev.EPC_STU_PGM_ELL e
	ON
	E.STUDENT_GU = BS.STUDENT_GU
	left join
	aps.ScheduleDetailsAsOf('2015-05-22') P
	on
	p.SIS_NUMBER = bs.SIS_NUMBER
	left join
	rev.EPC_CRS C
	on
	p.COURSE_GU = c.COURSE_GU
	WHERE
	[Period] = '2015-12-15'
	AND [District Code] = '001'
)
--SELECT * FROM STUDENTCTE where rn = 1 and [APS ID] = 100004464

/*
GRADE information for Data Set 1
AP
*/

, AP_Test
as
(
SELECT 
	ROW_NUMBER() over(partition by SIS_NUMBER, BASIC_SCHEDULE.SECTION_ID order by sis_number) as RN,
	[RevYear].[SCHOOL_YEAR]
	,[STUDENT].[SIS_NUMBER]
	,[COURSE].[COURSE_ID]
	,[COURSE].[COURSE_TITLE]
	,[BASIC_SCHEDULE].[SECTION_ID]
	,[BASIC_SCHEDULE].[TERM_CODE]
	
	,[COURSE].[AP_INDICATOR]
	,[COURSE].[ACADEMIC_TYPE]
	,[COURSE].[IB_INDICATOR]
	,MARK
	,CREDIT_COMPLETED
	
	
	--,[COURSE].*
	
FROM
	APS.BasicSchedule AS [BASIC_SCHEDULE]
	
	INNER JOIN
	rev.EPC_CRS AS [COURSE]
	ON
	[BASIC_SCHEDULE].[COURSE_GU] = [COURSE].[COURSE_GU]
	
	INNER JOIN	 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[BASIC_SCHEDULE].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	INNER JOIN
	rev.EPC_STU AS [STUDENT]
	ON
	[BASIC_SCHEDULE].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
    -- Get school name
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[BASIC_SCHEDULE].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
    
    -- Get school number
	LEFT JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[BASIC_SCHEDULE].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]

	LEFT HASH JOIN 
	(	 SELECT  CREDIT_COMPLETED, MARK, STU.STUDENT_GU, COURSE_ID, SECTION_ID
	 
	 FROM 

			rev.EPC_STU_CRS_HIS AS HIS
			INNER JOIN 
			REV.EPC_STU AS STU
			ON
			HIS.STUDENT_GU = STU.STUDENT_GU
			LEFT JOIN
			[rev].[EPC_REPEAT_TAG] AS [Repeat]
			ON
			HIS.[REPEAT_TAG_GU]=[Repeat].[REPEAT_TAG_GU]
) AS CRSHIST
ON
CRSHIST.STUDENT_GU = STUDENT.STUDENT_GU
AND COURSE.COURSE_ID = CRSHIST.COURSE_ID
	
WHERE
	[RevYear].[SCHOOL_YEAR] IN ('2015')
	AND [RevYear].[EXTENSION] = 'R'
	
	AND ( [COURSE].[AP_INDICATOR] = 'Y') --OR [COURSE].[ACADEMIC_TYPE] = 'Hon' OR [COURSE].[IB_INDICATOR] = 'Y'  )
)
,AP_PIVOT
AS
(
SELECT * FROM AP_TEST
pivot (MAX(MARK)
for term_code in ([S1], [S2])
)as 
pivtbl
where rn = 1
)


select 
	S.[APS ID],
	S.[STATE ID],
	S.GENDER,
	S.RACE_1,
	S.RACE_2,
	S.RACE_3,
	S.RACE_4,
	S.RACE_5,
	S.RESOLVED_RACE,
	S.SPED_STATUS,
	S.[PRIMARY DISABILITY DESCRIPTION],
	S.LUNCH_STATUS,
	S.[STUDENT GRADE LEVEL 2015],
	S.AP_INDICATOR,
	A.S1,
	A.S2,
	S.IB_INDICATOR,
	S.DUAL_CREDIT
from AP_PIVOT A
right join
STUDENTCTE S
on
s.[APS ID] = a.SIS_NUMBER


