
SELECT 
	STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
	,CASE WHEN ALLELSTUDENTS.ENGLISH_PROFICIENCY IS NOT NULL THEN ENGLISH_PROFICIENCY ELSE 0 END AS ENGLISH_PROFICIENCY

FROM
(
SELECT 
	SIS_NUMBER, STATE_STUDENT_NUMBER,
		CASE 
		WHEN HIST.STUDENT_GU IS NOT NULL  THEN 1 		
	ELSE 0 END AS ENGLISH_PROFICIENCY
	,PRIM.STUDENT_GU
 FROM 
APS.PrimaryEnrollmentDetailsAsOf('20171011') AS PRIM
INNER JOIN 
REV.EPC_STU_PGM_ELL_HIS AS HIST
ON
PRIM.STUDENT_GU = HIST.STUDENT_GU
INNER JOIN 
REV.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU
WHERE HIST.EXIT_DATE IS NULL AND EXIT_REASON IS NULL

UNION ALL

SELECT 
	SIS_NUMBER, STATE_STUDENT_NUMBER,
		CASE 
		WHEN EXIT_REASON = 'EY1' THEN 2
		WHEN EXIT_REASON = 'EY2' THEN 3
		WHEN EXIT_REASON = 'EY3' THEN 4
		WHEN EXIT_REASON = 'EY4' THEN 5
		WHEN EXIT_REASON = 'EY5' THEN 6
		
	ELSE 0 END AS ENGLISH_PROFICIENCY
	,PRIM.STUDENT_GU
 FROM 
APS.PrimaryEnrollmentDetailsAsOf('20171011') AS PRIM
INNER JOIN 
REV.EPC_STU_PGM_ELL_HIS AS HIST
ON
PRIM.STUDENT_GU = HIST.STUDENT_GU
INNER JOIN 
REV.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU

WHERE
HIST.EXIT_DATE >= '20170701' 

) AS ALLELSTUDENTS

RIGHT JOIN 
APS.PrimaryEnrollmentDetailsAsOf('20171011') AS PRIM
ON
ALLELSTUDENTS.STUDENT_GU = PRIM.STUDENT_GU
INNER JOIN 
REV.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU



