
SELECT STU.STATE_STUDENT_NUMBER ,LCE.SIS_NUMBER, ORGANIZATION_NAME, PARENT_REFUSED,[STATUS] FROM 
APS.LCEStudentsAndProvidersAsOf('02-08-2017') AS LCE
INNER JOIN rev.EPC_STU AS STU
ON
LCE.SIS_NUMBER = STU.SIS_NUMBER

WHERE
[STATUS] = 'No Appropriate Course Assigned'
AND PARENT_REFUSED = ''
