
SELECT ORGANIZATION_NAME,STU.STATE_STUDENT_NUMBER ,LCE.SIS_NUMBER, ORGANIZATION_NAME, GRADE, PARENT_REFUSED, COURSE_ID, COURSE_TITLE FROM 
APS.LCEStudentsAndProvidersAsOf('02-08-2017') AS LCE
INNER JOIN rev.EPC_STU AS STU
ON
LCE.SIS_NUMBER = STU.SIS_NUMBER

WHERE
COURSE_ID IS NOT NULL
