

SELECT ORGANIZATION_NAME,STU.STATE_STUDENT_NUMBER ,LCE.SIS_NUMBER,PARENT_REFUSED, PARENT_REFUSAL_STATUS, PARENT_REFUSED_ENTER_DATE
	,case when COURSE_ID IS NOT NULL THEN 'IN AN ESL CLASS' 
		ELSE 'Parent Refused'
		END AS [STATUS]
FROM 
APS.LCEStudentsAndProvidersAsOf_2('10-11-2017') AS LCE
INNER JOIN rev.EPC_STU AS STU
ON
LCE.SIS_NUMBER = STU.SIS_NUMBER

WHERE
PARENT_REFUSED = 'Y'
