

SELECT ORGANIZATION_NAME,STU.STATE_STUDENT_NUMBER ,LCE.SIS_NUMBER,PARENT_REFUSED
	,case when COURSE_ID IS NOT NULL THEN 'IN AN ESL CLASS' 
		ELSE 'Parent Refused'
		END AS [STATUS]
FROM 
APS.LCEStudentsAndProvidersAsOf('02-08-2017') AS LCE
INNER JOIN rev.EPC_STU AS STU
ON
LCE.SIS_NUMBER = STU.SIS_NUMBER

WHERE
PARENT_REFUSED = 'Y'
