
SELECT DISTINCT 
PRIM.Non_Primary_School,STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER, 

PRIM.GRADE, 
SCH.ORGANIZATION_NAME AS SCHEDULE_SCHOOL,
SCH.COURSE_ID, SECTION_ID, COURSE_TITLE, COURSE_ENTER_DATE, COURSE_LEAVE_DATE, TERM_CODE 
FROM 
APS.OpenNonPrimaryEnrollments AS PRIM
LEFT JOIN 
APS.PrimaryEnrollmentDetailsAsOf('20161201') AS ADA
ON
PRIM.STUDENT_GU = ADA.STUDENT_GU

INNER JOIN 
rev.EPC_STU AS STU
ON 
PRIM.STUDENT_GU = STU.STUDENT_GU
INNER JOIN 
APS.ScheduleDetailsAsOf('20161201') AS SCH
ON
PRIM.STUDENT_GU = SCH.STUDENT_GU

WHERE
ADA.STUDENT_GU IS NULL

ORDER BY SIS_NUMBER, SCHEDULE_SCHOOL, COURSE_ID