/*
	Created By:  Debbie Ann Chavez
	Date:  4/17/2015

	** Run this after NYR has been run **

	Part 2 Transfer Process - Update the SSY enrollment created by NYR 
		1.  Reason for Attendance - ATTEND_PERMIT_CODE with 'TRAN'
		2.  Reason for Attendance Date - ATTEND_PERMIT_DATE with current date

*/



EXECUTE AS LOGIN='QueryFileUser'
GO

BEGIN TRANSACTION

UPDATE rev.EPC_STU_SCH_YR
	SET ATTEND_PERMIT_CODE = 'TRAN', ATTEND_PERMIT_DATE = GETDATE()
	, CHANGE_DATE_TIME_STAMP = GETDATE(), CHANGE_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F'
FROM
(
SELECT [﻿SynSISNUMBER], ATTEND_PERMIT_CODE, ATTEND_PERMIT_DATE,STUDENT_SCHOOL_YEAR_GU
	,CASE WHEN NXTYR.SIS_NUMBER IS NULL THEN 'NO 2015 ENROLLMENT' ELSE '' END AS NEEDS_SSY 
FROM
      OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  --'Text;Database=\\SYNSECONDDB\D$\SQLWorkingFiles\;', 
				  'Text;Database=\\syntempssis.aps.edu.actd\Files\TempQuery;', 
                  'SELECT ﻿SynSISNUMBER from TEST.csv'
                ) AS [Approvals]
				
INNER JOIN
(
SELECT SIS_NUMBER, ATTEND_PERMIT_CODE, ATTEND_PERMIT_DATE,STUDENT_SCHOOL_YEAR_GU  FROM 
rev.EPC_STU_SCH_YR AS SSY
INNER JOIN
rev.EPC_STU AS STU
ON
SSY.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
SSY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_YEAR AS YRS
ON
ORGYR.YEAR_GU = YRS.YEAR_GU
WHERE
YRS.SCHOOL_YEAR = '2015'
)
AS NXTYR

ON
[Approvals].[﻿SynSISNUMBER] = NXTYR.SIS_NUMBER

) AS T2

WHERE

	T2.STUDENT_SCHOOL_YEAR_GU = rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU

ROLLBACK

      REVERT
GO