/*
	Created By:  Debbie Ann Chavez
	Date:  4/17/2015

	Part 1 Transfer Process - Update Next School and Next Grade
	The select creates a file for verification and error types.
	After this Update is run, then NYR must be run to create enrollments.

*/

/*
BEGIN TRANSACTION

UPDATE rev.EPC_STU_SCH_YR
	SET NEXT_GRADE_LEVEL = VALUE_CODE, NEXT_SCHOOL_GU = ORGANIZATION_GU
	, CHANGE_DATE_TIME_STAMP = GETDATE(), CHANGE_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F'
FROM
(
*/

EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT T2.*, SCH.ORGANIZATION_GU
, GRDE.VALUE_CODE 
FROM 
(
SELECT 
	SynSISNUMBER
	,[App Grde]
	,[APP School] 
	,[App Loc]
	,CASE WHEN S1 IS NOT NULL THEN S1 ELSE S2 END AS SSYGU

 FROM 

(

SELECT 
	[Approvals].*
	,CASE WHEN STU2.SIS_NUMBER IS NOT NULL THEN STU2.SIS_NUMBER ELSE STU.SIS_NUMBER END AS SynSISNUMBER
	,CASE WHEN ORG2.ORGANIZATION_NAME IS NOT NULL THEN ORG2.ORGANIZATION_NAME ELSE ORG.ORGANIZATION_NAME END AS SynPrimarySchool
	,CASE WHEN NXTSCH2.ORGANIZATION_NAME IS NOT NULL THEN NXTSCH2.ORGANIZATION_NAME ELSE NXTSCH.ORGANIZATION_NAME  END AS SynNextSchool
	,CASE WHEN GRADEL22.VALUE_DESCRIPTION IS NOT NULL THEN GRADEL22.VALUE_DESCRIPTION ELSE GRADEL.VALUE_DESCRIPTION END AS SynGrade
	,CASE WHEN GRADEL222.VALUE_DESCRIPTION IS NOT NULL THEN GRADEL222.VALUE_DESCRIPTION ELSE GRADEL2.VALUE_DESCRIPTION END AS SynNextGrade
	,CASE WHEN NXTYRENR2.STUDENT_GU IS NOT NULL THEN NXTYRENR2.SCHOOL_NAME ELSE NXTYRENR.SCHOOL_NAME END AS Syn20152016Enrollment

	,CASE 
		  WHEN SCHOOL.SCHOOL_CODE = [App Loc] THEN 'ALREADY AT TRANSFER SCHOOL'
		  WHEN NXTYRENR2.SCHOOL_CODE = [App Loc] THEN '2015 Enrollment at APP LOC'
		  WHEN NXTYRENR.SCHOOL_CODE =  [App Loc] THEN '2015 Enrollment at APP LOC'
		  WHEN ORG.ORGANIZATION_NAME IS NOT NULL AND GRADEL2.VALUE_DESCRIPTION = [Approvals].[App Grde] THEN 'UPDATE'
		  WHEN GRADEL2.VALUE_DESCRIPTION != [Approvals].[App Grde] THEN 'GRADE DOES NOT MATCH' 
		  WHEN GRADEL2.VALUE_DESCRIPTION IS NULL AND ORG.ORGANIZATION_NAME IS NOT NULL THEN 'GRADE DOES NOT MATCH'
		  WHEN ORG.ORGANIZATION_NAME IS NULL AND ORG2.ORGANIZATION_NAME IS NULL THEN 'NO PRIMARY ENROLLMENT'
		  WHEN STU2.SIS_NUMBER IS NOT NULL AND ORG2.ORGANIZATION_NAME IS NOT NULL THEN 'IDNBR AND PRIMARY ENROLLMENT FOUND'
		  		   
		  ELSE '' END AS [ACTION]
	,SSY.STUDENT_SCHOOL_YEAR_GU AS S1
	,SSY2.STUDENT_SCHOOL_YEAR_GU AS S2


FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from Approvals.csv'
                ) AS [Approvals]


LEFT JOIN 
rev.EPC_STU AS STU

ON
[Approvals].[APS ID] = STU.SIS_NUMBER

LEFT JOIN
APS.PrimaryEnrollmentsAsOf(GETDATE()) AS PE
ON
STU.STUDENT_GU = PE.STUDENT_GU

LEFT JOIN
rev.EPC_STU_SCH_YR AS SSY
ON
PE.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU

LEFT JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = SSY.ORGANIZATION_YEAR_GU

LEFT JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU


LEFT JOIN
rev.REV_ORGANIZATION AS NXTSCH
ON
SSY.NEXT_SCHOOL_GU = NXTSCH.ORGANIZATION_GU

LEFT JOIN
APS.LookupTable ('K12', 'Grade') AS GRADEL
ON
GRADEL.VALUE_CODE = SSY.GRADE

LEFT JOIN 
APS.LookupTable ('K12', 'Grade') AS GRADEL2
ON
GRADEL2.VALUE_CODE = SSY.NEXT_GRADE_LEVEL

LEFT JOIN
rev.REV_PERSON AS PERS
ON
PERS.LAST_NAME = [Approvals].Last
AND PERS.FIRST_NAME = [Approvals].First
--AND LEFT(PERS.MIDDLE_NAME,1) = LEFT([Approvals].Mid,1)
AND CAST(PERS.BIRTH_DATE AS DATE) = [Approvals].DOB
AND [Approvals].[APS ID] IS NULL

LEFT JOIN
rev.EPC_SCH AS SCHOOL
ON
SCHOOL.ORGANIZATION_GU = ORG.ORGANIZATION_GU 

-------------------------------------------------------------------------------
LEFT JOIN
rev.EPC_STU AS STU2
ON
STU2.STUDENT_GU = PERS.PERSON_GU

LEFT JOIN
APS.PrimaryEnrollmentsAsOf(GETDATE()) AS PE2
ON
STU2.STUDENT_GU = PE2.STUDENT_GU

LEFT JOIN
rev.EPC_STU_SCH_YR AS SSY2
ON
PE2.STUDENT_SCHOOL_YEAR_GU = SSY2.STUDENT_SCHOOL_YEAR_GU

LEFT JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR2
ON
ORGYR2.ORGANIZATION_YEAR_GU = SSY2.ORGANIZATION_YEAR_GU

LEFT JOIN
rev.REV_ORGANIZATION AS ORG2
ON
ORGYR2.ORGANIZATION_GU = ORG2.ORGANIZATION_GU


LEFT JOIN
rev.REV_ORGANIZATION AS NXTSCH2
ON
SSY2.NEXT_SCHOOL_GU = NXTSCH2.ORGANIZATION_GU

LEFT JOIN
APS.LookupTable ('K12', 'Grade') AS GRADEL22
ON
GRADEL22.VALUE_CODE = SSY2.GRADE

LEFT JOIN 
APS.LookupTable ('K12', 'Grade') AS GRADEL222
ON
GRADEL222.VALUE_CODE = SSY2.NEXT_GRADE_LEVEL

LEFT JOIN
rev.EPC_SCH AS SCHOOL2
ON
SCHOOL2.ORGANIZATION_GU = ORG2.ORGANIZATION_GU 

-----------------------------------------------------------------
LEFT JOIN
APS.PrimaryEnrollmentDetailsAsOf('2015-08-13') AS NXTYRENR
ON
NXTYRENR.STUDENT_GU = STU.STUDENT_GU

LEFT JOIN
APS.PrimaryEnrollmentDetailsAsOf('2015-08-13') AS NXTYRENR2
ON
NXTYRENR.STUDENT_GU = STU2.STUDENT_GU
------------------------------------------------------------------

) AS T1

WHERE 
	ACTION IN ('UPDATE', 'IDNBR AND PRIMARY ENROLLMENT FOUND')

) AS T2


--COMMENT THIS OUT FOR THE DETAILS FOR THE FILE TO REVIEW
INNER JOIN
rev.EPC_SCH AS SCH
ON
SCH.SCHOOL_CODE = [APP Loc]

INNER JOIN
APS.LookupTable ('K12','GRADE') AS GRDE
ON
GRDE.VALUE_DESCRIPTION = [App Grde]


--THIS NEEDED FOR THE UPDATE
/*
      REVERT
GO

) AS T3
WHERE
	T3.SSYGU = rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU
ROLLBACK
*/
