USE [ST_Production]
GO

/****** Object:  UserDefinedFunction [APS].[PHLOTEAsOf]    Script Date: 5/5/2017 10:32:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



/**
 * FUNCTION APS.PhloteStatusAsOf
 * Pulls StudentGUs of anyone who is PHLOTE
 * Tables Used: UD_HLS_HISTORY
 *
 * #param DATETIME @asOfDate Date to pull PHLOTE status from
 * 
 * #return TABLE PHLOTE Info as of date
 */
ALTER FUNCTION [APS].[PHLOTEAsOf](@asOfDate DATETIME)
RETURNS TABLE
AS
RETURN
SELECT STUDENT_GU
	,DATE_ASSIGNED 
FROM(
SELECT 
	STUDENT_GU
	,DATE_ASSIGNED
	,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY DATE_ASSIGNED DESC) AS RN

FROM (
SELECT 
*
FROM (
SELECT
	STUDENT_GU
	,DATE_ASSIGNED
FROM
	(
	SELECT
		STUDENT_GU
		,Q1_LANGUAGE_SPOKEN_MOST
		,Q2_CHILD_FIRST_LANGUAGE
		,Q3_LANGUAGES_SPOKEN
		,Q4_OTHER_LANG_UNDERSTOOD
		,Q5_OTHER_LANG_COMMUNICATED
		,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY DATE_ASSIGNED DESC) AS RN
		,DATE_ASSIGNED
	FROM
		rev.UD_HLS_HISTORY AS HLSHistory
	WHERE
		DATE_ASSIGNED <= @asOfDate
	) AS RowedHLS
WHERE
	RN = 1
	AND Q1_LANGUAGE_SPOKEN_MOST + Q2_CHILD_FIRST_LANGUAGE + Q3_LANGUAGES_SPOKEN + Q4_OTHER_LANG_UNDERSTOOD + Q5_OTHER_LANG_COMMUNICATED != '0000000000'

) AS OLDPHLOTE

/***********************************************************************************************************************************************

DAC 5/3/2017 - ADDED LOGIC TO PULL NEW LUS HLS SURVEY QUESTIONS IF ENTERED.  IF STUDENT HAS RECORDS IN BOTH TABLES, MOST RECENT RECORD IS CHOSEN.

*************************************************************************************************************************************************/

UNION ALL

SELECT 
	STUDENT_GU
	,DATE_ASSIGNED
	--,LUS_Q1_STUDENT
	--,LUS_Q2_STUDENT
	--,LUS_Q3_STUDENT
	--,LUS_Q4_STUDENT
	--,LUS_Q5_STUDENT
	--,LUS_Q6_STUDENT
	--,LUS_Q7A_STUDENT
	--,LUS_Q7B_STUDENT
	--,LUS_Q7C_STUDENT

 FROM 
REV.UD_LUS_HISTORY

WHERE
(Q1_STUDENT = 'Y' OR
 Q2_STUDENT = 'Y' OR
 Q3_STUDENT = 'Y' OR
 Q4_STUDENT = 'Y' OR
 Q5_STUDENT = 'Y' OR
 Q6_STUDENT = 'Y' OR
 Q7A_STUDENT != '00' OR
 Q7B_STUDENT != '00' OR
 Q7C_STUDENT != '00'
)
 ) AS ALLPHLOTE
 ) AS GETONEPHLOTE
 WHERE RN = 1
GO


