
/**
 * $Revision:1 $
 * $LastChangedBy: e104090 $
 * $LastChangedDate: 20140829 $
 */
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[APS].[LCEMostRecentTestWaiverAsOf]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
	EXEC('CREATE FUNCTION APS.LCEMostRecentTestWaiverAsOf()RETURNS TABLE AS RETURN (SELECT 0 AS DUMMY)')
GO


/*
*	Pull Most Recent Test Assessment Refusal or Sped Waiver
*/

ALTER FUNCTION APS.LCEMostRecentTestWaiverAsOf(@AsOfDate DATETIME)
RETURNS TABLE
AS
RETURN


SELECT 
	STU.STUDENT_GU
	,WAIVER_TYPE
	,WAIVER_ENTER_DATE
	,WAIVER_EXIT_DATE
FROM (

	SELECT
		STUDENT_GU
		,WAIVER_TYPE
		,WAIVER_ENTER_DATE
		,WAIVER_EXIT_DATE
		 ,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY WAIVER_ENTER_DATE DESC) AS RN
	 FROM
	rev.EPC_STU_PGM_ELL_WAV
	WHERE
	WAIVER_TYPE IN ('RTEST', 'RSPED')
	AND WAIVER_ENTER_DATE <= @AsOfDate
	AND 
		(WAIVER_EXIT_DATE IS NULL
		OR WAIVER_EXIT_DATE >=@AsOfDate)

	) AS ALLWAIVERS
INNER JOIN
rev.EPC_STU AS STU
ON
ALLWAIVERS.STUDENT_GU = STU.STUDENT_GU

WHERE
RN = 1