


SELECT 
	ORG.ORGANIZATION_NAME	
	,BS.SIS_NUMBER

	,BS.LAST_NAME AS STU_LAST
	,BS.FIRST_NAME AS STU_FIRST
	,GRADE.VALUE_DESCRIPTION AS GRADE
	,LE.TEST_NAME
	,LE.PERFORMANCE_LEVEL
	,ELL.ENTER_DATE
	,STAFF2.BADGE_NUM
	,COURSE_ID
	,SECTION_ID
	,COURSE_TITLE
	
	,STAFF.LAST_NAME AS STAFF_LAST
	,STAFF.FIRST_NAME AS STAFF_FIRST
	
	,PRIMARY_DISABILITY_CODE
	,PARENTREFUSAL.WAIVER_TYPE
	
 FROM

APS.ELLCalculatedAsOf (GETDATE()) AS ELL

INNER JOIN
APS.BasicStudent AS BS
ON
ELL.STUDENT_GU = BS.STUDENT_GU

INNER JOIN 
APS.LCELatestEvaluationAsOf (GETDATE()) AS LE
ON
LE.STUDENT_GU = ELL.STUDENT_GU

LEFT JOIN
(SELECT 
	SCH.STUDENT_GU
	,SCH.STAFF_GU
	,SCH.ORGANIZATION_GU
	,COURSE_ID
	,SCH.SECTION_ID
	,COURSE_TITLE
 FROM
APS.ScheduleAsOf (GETDATE()) AS SCH
INNER JOIN
APS.LCEClassesAllAsOf (GETDATE()) AS LC
ON
LC.SCHOOL_YEAR_COURSE_GU = SCH.SCHOOL_YEAR_COURSE_GU
AND
LC.COURSE_GU = SCH.COURSE_GU
AND 
SCH.SECTION_GU = LC.SECTION_GU
AND 
SCH.STAFF_SCHOOL_YEAR_GU = LC.STAFF_SCHOOL_YEAR_GU
AND 
LC.TAG = 'ALSES'
) AS TAGGED

ON
ELL.STUDENT_GU = TAGGED.STUDENT_GU

LEFT HASH JOIN
rev.REV_PERSON AS STAFF
ON
TAGGED.STAFF_GU = STAFF.PERSON_GU

LEFT HASH JOIN
(
SELECT
	CurrentSPED.STUDENT_GU
	,CurrentSPED.PRIMARY_DISABILITY_CODE
FROM	
	APS.PrimaryEnrollmentsAsOf(GETDATE()) AS Enrollment
	LEFT JOIN
	(
	SELECT
		STUDENT_GU
		,PRIMARY_DISABILITY_CODE
	FROM
		REV.EP_STUDENT_SPECIAL_ED AS SPED
	WHERE
		NEXT_IEP_DATE IS NOT NULL
		AND (
			EXIT_DATE IS NULL 
			OR EXIT_DATE >= CONVERT(DATE, GETDATE())
			)
	) AS CurrentSPED
	ON
	Enrollment.STUDENT_GU = CurrentSPED.STUDENT_GU
WHERE 
	CurrentSPED.STUDENT_GU IS NOT NULL

	) AS SPED

	ON
	ELL.STUDENT_GU = SPED.STUDENT_GU

	LEFT JOIN
	APS.LCEMostRecentALSRefusalAsOf (GETDATE()) AS PARENTREFUSAL
	ON
	PARENTREFUSAL.STUDENT_GU = ELL.STUDENT_GU

	INNER JOIN
	APS.LookupTable ('K12','Grade') GRADE
	ON
	ELL.GRADE = GRADE.VALUE_CODE

	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	ORGYR.ORGANIZATION_YEAR_GU = ELL.ORGANIZATION_YEAR_GU

	INNER JOIN
	rev.REV_ORGANIZATION AS ORG
	ON
	ORG.ORGANIZATION_GU = ORGYR.ORGANIZATION_GU

	LEFT HASH JOIN
	rev.EPC_STAFF AS STAFF2
	ON
	STAFF.PERSON_GU = STAFF2.STAFF_GU


ORDER BY SIS_NUMBER


