--DECLARE @YEAR INT = 2015
--DECLARE @SCHOOL VARCHAR(3) = '550'
/**
 * $Revision: 1 $
 * $LastChangedBy: e207878 $
 * $LastChangedDate: 2015-11-09 $
 */
 -- Add Procedure if it does not exist
IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[APS].[WithdrawAndReqTrackingAsOf]') AND type in (N'P', N'PC'))
	EXEC ('CREATE PROCEDURE [APS].WithdrawAndReqTrackingAsOf AS SELECT 0')
GO

ALTER PROC [APS].[WithdrawAndReqTrackingAsOf](
	@Year VARCHAR(150)
	,@School VARCHAR(150) 
)

AS
BEGIN

SET NOCOUNT ON
SET ANSI_WARNINGS OFF

SELECT
      [STUDENT].[SIS_NUMBER]
      ,[STUDENT].[STATE_STUDENT_NUMBER]
      ,[STUDENT].[FIRST_NAME]
      ,[STUDENT].[LAST_NAME]
      ,[STUDENT].[MIDDLE_NAME]
      ,[STUDENT].[GENDER]
      ,[ENROLLMENT].[SCHOOL_CODE]
      ,[ENROLLMENT].[SCHOOL_NAME]
      ,[ENROLLMENT].[SCHOOL_YEAR]
      ,[ENROLLMENT].[EXTENSION]
      ,[ENROLLMENT].[GRADE]
      ,[ENROLLMENT].[SUMMER_WITHDRAWL_CODE]
      ,CONVERT(VARCHAR(10),[StudentSchoolYear].[SUMMER_WITHDRAWL_DATE],101) AS [SUMMER_WITHDRAWL_DATE]
      ,[ENROLLMENT].[YEAR_END_STATUS]
      ,[ENROLLMENT].[EXCLUDE_ADA_ADM]
      ,[ENROLLMENT].[CONCURRENT]
      ,[ENROLLMENT].[ACCESS_504]
      ,CONVERT(VARCHAR(10),[ENROLLMENT].[ENTER_DATE],101) AS [ENTER_DATE]
      ,[ENROLLMENT].[ENTER_CODE]
      ,[ENTER_CODE].[ALT_CODE_2] AS [ENTER_STATE_CODE]
      ,[ENROLLMENT].[ENTER_DESCRIPTION]
      ,CONVERT(VARCHAR(10),[ENROLLMENT].[LEAVE_DATE],101) AS [LEAVE_DATE]
      ,[ENROLLMENT].[LEAVE_CODE]
      ,[LEAVE_CODE].[ALT_CODE_2] AS [LEAVE_STATE_CODE]
      ,[ENROLLMENT].[LEAVE_DESCRIPTION]
      ,[StudentSchoolYear].[ENR_USER_DD_4] AS [HOME/CHARTER]
	  ,NON_DISTRICT_SCHOOL.NAME AS [Non-District School]
	  ,REQUEST_TRACKING.PERSON_RELEASED_TO AS [Person Released To]
	  ,REQUEST_TRACKING.PERSON_TITLE AS [Title]
	  ,REQUEST_TRACKING.RELEASE_PURPOSE AS [Purpose]
	  ,REQUEST_TRACKING.DELIVERY_TYPE AS [Delivery Type]
	  ,UD_REQUEST_TRACKING.NOTES AS [Notes]
	
      
FROM
	APS.StudentEnrollmentDetails AS [ENROLLMENT]

	INNER JOIN
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
	ON
	[ENROLLMENT].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]

	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]

	LEFT JOIN
	APS.LookupTable('K12.ENROLLMENT','LEAVE_CODE') AS [LEAVE_CODE]
	ON
	[ENROLLMENT].[LEAVE_CODE] = [LEAVE_CODE].[VALUE_CODE]
	
	LEFT JOIN
	APS.LookupTable('K12.ENROLLMENT','ENTER_CODE') AS [ENTER_CODE]
	ON
	[ENROLLMENT].[ENTER_CODE] = [ENTER_CODE].[VALUE_CODE]
	
	LEFT JOIN
	rev.[EPC_STU_REQUEST_TRACKING] AS [REQUEST_TRACKING]
	ON
	[ENROLLMENT].[STUDENT_GU] = [REQUEST_TRACKING].[STUDENT_GU]
		
	LEFT JOIN 
	rev.[EPC_SCH_NON_DST] AS NON_DISTRICT_SCHOOL -- Contains the School Name
	ON 
	[REQUEST_TRACKING].[SCHOOL_NON_DISTRICT_GU] = [NON_DISTRICT_SCHOOL].[SCHOOL_NON_DISTRICT_GU]
		
	LEFT JOIN
	APS.LookupTable('K12.CourseHistoryInfo','RELEASE_PURPOSE') AS [RELEASE_PURPOSE]
	ON
	[REQUEST_TRACKING].[RELEASE_PURPOSE] = [RELEASE_PURPOSE].[VALUE_CODE]
		
	LEFT OUTER JOIN
	rev.UD_STU_REQUEST_TRACKING AS [UD_REQUEST_TRACKING]
	ON
	[REQUEST_TRACKING].[STU_REQUEST_TRACKING_GU] = [UD_REQUEST_TRACKING].[STU_REQUEST_TRACKING_GU]

      
WHERE
	[ENROLLMENT].YEAR_GU = @Year
	AND ENROLLMENT.ORGANIZATION_GU LIKE @School
	AND [ENROLLMENT].[LEAVE_CODE] IS NOT NULL

	SET NOCOUNT OFF
SET ANSI_WARNINGS ON

END -- END SRPOC