USE [ST_Production]
GO

/****** Object:  UserDefinedFunction [APS].[LCEMostRecentHLSAsOf]    Script Date: 5/5/2017 11:38:17 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER FUNCTION [APS].[LCEMostRecentHLSAsOf](@AsOfDate DATE)
RETURNS TABLE
AS
RETURN


/*************************************************************************************************

DAC 5/3/2017 --CHANGED THIS FUNCTION TO PULL MOST RECENT HLS QUESTIONS FROM OLD PHLOTE AND NEW PHLOTE TABLES

**************************************************************************************************/


SELECT STUDENT_GU
	,DATE_ASSIGNED 
	,Q1
	,Q2
	,Q3
	,Q4
	,Q5
	,Q6
	,Q7A
	,Q7B
	,Q7C

FROM(
SELECT 
	STUDENT_GU
	,DATE_ASSIGNED
	,Q1
	,Q2
	,Q3
	,Q4
	,Q5
	,Q6
	,Q7A
	,Q7B
	,Q7C
	,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY DATE_ASSIGNED DESC) AS RN

FROM (
SELECT 
*
FROM (
SELECT
	STUDENT_GU
	,DATE_ASSIGNED
	,Q1_LANGUAGE_SPOKEN_MOST AS Q1
	,Q2_CHILD_FIRST_LANGUAGE AS Q2
	,Q3_LANGUAGES_SPOKEN AS Q3
	,Q4_OTHER_LANG_UNDERSTOOD AS Q4
	,Q5_OTHER_LANG_COMMUNICATED AS Q5
	,'' AS Q6
	,'' AS Q7A
	,'' AS Q7B
	,'' AS Q7C
FROM
	(
	SELECT
		STUDENT_GU
		,Q1_LANGUAGE_SPOKEN_MOST
		,Q2_CHILD_FIRST_LANGUAGE
		,Q3_LANGUAGES_SPOKEN
		,Q4_OTHER_LANG_UNDERSTOOD
		,Q5_OTHER_LANG_COMMUNICATED
		,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY DATE_ASSIGNED DESC) AS RN
		,DATE_ASSIGNED
	FROM
		rev.UD_HLS_HISTORY AS HLSHistory
	WHERE
		DATE_ASSIGNED <= GETDATE()
	) AS RowedHLS
WHERE
	RN = 1
	
) AS OLDPHLOTE

UNION ALL


SELECT 
	STUDENT_GU
	,DATE_ASSIGNED
	,Q1_STUDENT
	,Q2_STUDENT
	,Q3_STUDENT
	,Q4_STUDENT
	,Q5_STUDENT
	,Q6_STUDENT
	,Q7A_STUDENT
	,Q7B_STUDENT
	,Q7C_STUDENT

 FROM 
REV.UD_LUS_HISTORY

 ) AS ALLPHLOTE
 ) AS GETONEPHLOTE
 
 
 WHERE RN = 1
	



GO


