

/****************************************************************

CREATED BY DEBBIE ANN CHAVEZ
DATE 8/22/2017

PULL CURRENT YEAR EXIT STUDENTS 

****************************************************************/


ALTER FUNCTION [APS].[LCECurrentExitStudentsAsOf](@AsOfDate DATE)
RETURNS TABLE
AS
RETURN	


SELECT 
	SCHOOL_CODE, SCHOOL_NAME, GRADE, STU.LAST_NAME, STU.FIRST_NAME, 
	SIS_NUMBER, STATE_STUDENT_NUMBER, HIST.ENTRY_DATE, LU.VALUE_DESCRIPTION AS EXIT_REASON
	,PRIM.ORGANIZATION_GU
FROM 
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS PRIM
INNER JOIN 
REV.EPC_STU_PGM_ELL_HIS AS HIST
ON
PRIM.STUDENT_GU = HIST.STUDENT_GU
INNER JOIN 
APS.BasicStudentWithMoreInfo AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU 
INNER JOIN 
APS.LookupTable ('K12.PROGRAMINFO', 'ELL_EXIT_REASON') AS LU
ON
LU.VALUE_CODE = HIST.EXIT_REASON


WHERE
	-- CHANGE DATE TO 07/01 AND WHATEVER THE CURRENT SCHOOL YEAR IS
	ENTRY_DATE = (SELECT CAST(SCHOOL_YEAR AS VARCHAR) + '0701' FROM REV.SIF_22_Common_CurrentYear)

--ORDER BY EXIT_REASON

