
/**
 * $Revision:1 $
 * $LastChangedBy: e201594 $
 * $LastChangedDate: 2014-10-02 07:50:52 -0600 (Thu, 02 Oct 2014) $
 */
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[APS].[LCEMostRecentTestWaiverAsOf]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
	EXEC('CREATE FUNCTION APS.LCEMostRecentTestWaiverAsOf()RETURNS TABLE AS RETURN (SELECT 0 AS DUMMY)')
GO

/*
*	Pull Most Recent LCE Test Assessment Refusal or Sped Waiver
*/

ALTER FUNCTION APS.LCEMostRecentTestWaiverAsOf(@AsOfDate DATETIME)
RETURNS TABLE
AS
RETURN

SELECT 
	STUDENT_GU
	,WAIVER_TYPE
	,WAIVER_ENTER_DATE
	,WAIVER_EXIT_DATE
FROM 
	(
	SELECT
		STUDENT_GU
		,WAIVER_TYPE
		,WAIVER_ENTER_DATE
		,WAIVER_EXIT_DATE
		--ORDER ALL OF THE WAIVERS BY MOST RECENT ENTER DATE
		 ,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY WAIVER_ENTER_DATE DESC) AS RN
	 FROM
		rev.EPC_STU_PGM_ELL_WAV
	 WHERE
	 --THESE ARE THE ONLY 2 TYPES OF WAIVERS FOR TEST ASSESSMENTS:  TEST REFUSALS - 'RTEST' AND 'RSPED' SPED WAIVER
	 WAIVER_TYPE IN ('RTEST', 'RSPED')
	 AND @AsOfDate BETWEEN WAIVER_ENTER_DATE AND COALESCE (WAIVER_EXIT_DATE, @asOfDate)
	 
	 ) AS ALLWAIVERS

--PULL MOST RECENT TEST ASSESSMENT
WHERE
	RN = 1