
--PULL 2 MONTHS BACK FOR THE PREVIOUS SCHOOL YEAR FOR STUDENTS THAT WERE ELL AT THAT TIME (USING MAY 30TH I DIDN'T GET AS BIG OF NUMBERS FOR ELL SO CHANGED TO 4/30)-- 
DECLARE @AsOfDate AS DATE = (SELECT MAX(DATEADD (month,-2,END_DATE)) FROM APS.YEARDATES AS YRDT INNER JOIN REV.REV_YEAR AS YRS ON YRDT.YEAR_GU = YRS.YEAR_GU AND YRS.EXTENSION = 'R'  WHERE SCHOOL_YEAR = (SELECT SCHOOL_YEAR-1 FROM REV.SIF_22_Common_CurrentYear))
DECLARE @CurrDate AS DATE = (SELECT START_DATE FROM APS.YEARDATES AS YRDT INNER JOIN REV.REV_YEAR AS YRS ON YRDT.YEAR_GU = YRS.YEAR_GU AND YRS.EXTENSION = 'R'  WHERE SCHOOL_YEAR = (SELECT SCHOOL_YEAR FROM REV.SIF_22_Common_CurrentYear))

SELECT 
	*
FROM 

	APS.ELLCalculatedAsOf(@AsOfDate) AS LASTYRELL
	INNER JOIN 
	APS.ELLCalculatedAsOf(@CurrDate) AS CURRENTELL
	ON
	LASTYRELL.STUDENT_GU = CURRENTELL.STUDENT_GU


