
EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT 
	ENROLL.SIS_NUMBER, ENROLL.STATE_STUDENT_NUMBER, SCHOOL_YEAR, SCHOOL_CODE, SCHOOL_NAME, GRADE, ENTER_DATE, ENTER_DESCRIPTION, LEAVE_DATE, LEAVE_DESCRIPTION
	,SUMMER_WITHDRAWL_CODE, 
	SUMMER_WITHDRAWL_DATE,
	CREDITS_EARNED,
	T1.*
	
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from AHAH2.csv'
                ) AS [T1]

INNER JOIN 
	(SELECT
		*
	FROM
		(
		SELECT
			ENROLLMENTS.*
			,ROW_NUMBER() OVER (PARTITION BY ENROLLMENTS.STUDENT_GU ORDER BY SCHOOL_YEAR DESC, ENTER_DATE DESC, EXCLUDE_ADA_ADM) AS RN
			,STATE_STUDENT_NUMBER
		FROM
			APS.StudentEnrollmentDetails AS [ENROLLMENTS]
			INNER JOIN 
			rev.EPC_STU AS STU
			ON
			ENROLLMENTS.STUDENT_GU = STU.STUDENT_GU
			
		WHERE
			 [ENROLLMENTS].[EXCLUDE_ADA_ADM] IS NULL
			
		) AS [LATEST_ENROLLMENT]
	WHERE
		[RN] = 1
		) AS ENROLL

		ON
		T1.[StudentID] = ENROLL.STATE_STUDENT_NUMBER

LEFT HASH JOIN 
(SELECT 
	SIS_NUMBER, STATE_STUDENT_NUMBER, 
	SUM(HIST.CREDIT_COMPLETED) AS CREDITS_EARNED
	
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from AHAH2NODUPS.csv'
                ) AS [T1]

LEFT JOIN 
rev.EPC_STU AS STU
ON
T1.StudentID = STU.STATE_STUDENT_NUMBER

LEFT JOIN 
rev.EPC_STU_CRS_HIS AS HIST
ON
STU.STUDENT_GU = HIST.STUDENT_GU
AND HIST.COURSE_HISTORY_TYPE = 'HIGH'


GROUP BY 
SIS_NUMBER, STATE_STUDENT_NUMBER
) AS GETCREDITS

ON
GETCREDITS.SIS_NUMBER = ENROLL.SIS_NUMBER

ORDER BY 
ENROLL.SIS_NUMBER

REVERT 
GO