
EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT 
	STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER, ENROLL.GRADE,
	ENROLL.ENTER_DATE, ENROLL.ENTER_DESCRIPTION, ENROLL.LEAVE_DATE, LEAVE_DESCRIPTION, SUMMER_WITHDRAWL_CODE
	,SUMMER_WITHDRAWL_DATE
	, SCHOOL_NAME

	,CREDITS_EARNED
	--,T1.*
	
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from AHAH2NODUPS.csv'
                ) AS [T1]

INNER JOIN 
rev.EPC_STU AS STU
ON
T1.StudentID = STU.STATE_STUDENT_NUMBER

INNER JOIN 
APS.StudentEnrollmentDetails AS ENROLL
ON
STU.STUDENT_GU = ENROLL.STUDENT_GU
AND SCHOOL_YEAR = '2015'



LEFT HASH JOIN 
(SELECT 
	SIS_NUMBER, STATE_STUDENT_NUMBER, 
	SUM(HIST.CREDIT_COMPLETED) AS CREDITS_EARNED
	
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from AHAH2NODUPS.csv'
                ) AS [T1]

LEFT JOIN 
rev.EPC_STU AS STU
ON
T1.StudentID = STU.STATE_STUDENT_NUMBER

LEFT JOIN 
rev.EPC_STU_CRS_HIS AS HIST
ON
STU.STUDENT_GU = HIST.STUDENT_GU
AND HIST.COURSE_HISTORY_TYPE = 'HIGH'


GROUP BY 
SIS_NUMBER, STATE_STUDENT_NUMBER
) AS GETCREDITS

ON
GETCREDITS.SIS_NUMBER = STU.SIS_NUMBER


	
REVERT
GO
