

SELECT 
	DISTINCT HIST.STUDENT_GU, SIS_NUMBER, alt.IS_ELL
 FROM
APS.LCELatestEvaluationAsOf(GETDATE()) AS ALT
INNER JOIN
rev.EPC_STU_PGM_ELL_HIS AS HIST
ON
ALT.STUDENT_GU = HIST.STUDENT_GU
INNER JOIN
rev.EPC_STU AS STU
ON
HIST.STUDENT_GU = STU.STUDENT_GU

WHERE
TEST_NAME = 'ALT ACCESS'
AND HIST.EXIT_DATE IS NOT NULL
