
SELECT SIS_NUMBER, T3.ENTRY_DATE, PROGRAM_CODE, PROGRAM_QUALIFICATION, EXIT_DATE, EXIT_REASON FROM (

SELECT COUNT (*)AS THECOUNT, ENTRY_DATE, STUDENT_GU 
FROM
(
SELECT * FROM
rev.EPC_STU_PGM_ELL_HIS

) AS T1
GROUP BY STUDENT_GU, ENTRY_DATE
) AS T2


INNER JOIN
rev.EPC_STU AS STU
ON
T2.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
rev.EPC_STU_PGM_ELL_HIS AS T3
ON
T3.STUDENT_GU = T2.STUDENT_GU

WHERE
THECOUNT > 1
ORDER BY SIS_NUMBER