
EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT 
	T1.*
	,MARK
	,COURSE_ID
	,COURSE_TITLE

FROM 
	
(
SELECT DISTINCT APS_ID	
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from CGCS.csv'
                ) AS README
) AS [T1]

LEFT HASH JOIN 
(
SELECT 
	HIS.STUDENT_GU, SIS_NUMBER, MARK, HIS.COURSE_ID, HIS.COURSE_TITLE, DEPARTMENT
FROM rev.EPC_STU_CRS_HIS AS HIS
INNER JOIN 
rev.EPC_STU AS STU
ON
HIS.STUDENT_GU = STU.STUDENT_GU
INNER JOIN 
rev.EPC_CRS AS CRS
ON
HIS.COURSE_GU = CRS.COURSE_GU

WHERE 
HIS.COURSE_HISTORY_TYPE = 'HIGH'
AND SCHOOL_YEAR = 2014
AND DEPARTMENT IN ('Eng', 'Math', 'Sci', 'Soc')
) AS CORE
ON
CORE.SIS_NUMBER = T1.APS_ID

REVERT
GO