
SELECT 
	 PROGRAM_CODE, COUNT (*) AS COUNT_OF_STUDENTS
	--SIS_NUMBER, PROGRAM_CODE, PROGRAM_INTENSITY
 FROM 
rev.EPC_STU_PGM_ELL_BEP AS BEP
INNER JOIN 
rev.EPC_STU AS STU
ON
BEP.STUDENT_GU = STU.STUDENT_GU

WHERE EXIT_DATE IS NULL

GROUP BY PROGRAM_CODE