
SELECT 
	PRIM.SCHOOL_NAME
	, COUNT(*) AS BEP_STUDENTS
	, SUM(CASE WHEN PROGRAM_INTENSITY = 1 THEN 1 ELSE 0 END) AS [1HR]
	, SUM(CASE WHEN PROGRAM_INTENSITY = 2 THEN 1 ELSE 0 END) AS [2HR]
	, SUM(CASE WHEN PROGRAM_INTENSITY = 3 THEN 1 ELSE 0 END) AS [3HR]

	, SUM(CASE WHEN PROGRAM_INTENSITY = 1 AND ELL.STUDENT_GU IS NOT NULL THEN 1 ELSE 0 END) AS [1HR ELL]
	, SUM(CASE WHEN PROGRAM_INTENSITY = 2 AND ELL.STUDENT_GU IS NOT NULL THEN 1 ELSE 0 END) AS [2HR ELL]
	, SUM(CASE WHEN PROGRAM_INTENSITY = 3 AND ELL.STUDENT_GU IS NOT NULL THEN 1 ELSE 0 END) AS [3HR ELL]

 FROM APS.LCEBilingualAsOf(GETDATE()) AS LCE
INNER JOIN
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS PRIM
ON
LCE.STUDENT_GU = PRIM.STUDENT_GU
LEFT JOIN
APS.ELLAsOf (GETDATE()) AS ELL
ON
PRIM.STUDENT_GU = ELL.STUDENT_GU

GROUP BY 
	PRIM.SCHOOL_NAME

ORDER BY SCHOOL_NAME
