
/*
SELECT 
	SIS_NUMBER, HISTORY.EXIT_REASON, EXIT_DATE, ENTRY_DATE
 FROM 
rev.EPC_STU_PGM_ELL_HIS AS HISTORY
INNER JOIN 
rev.EPC_STU AS STU
ON
HISTORY.STUDENT_GU = STU.STUDENT_GU
ASTAR
WHERE 
--EXIT_DATE IS NOT NULL AND EXIT_REASON = 'EY1'
*/

SELECT 
	--DISTINCT ADMIN_DATE
	SIS_NUMBER, LASTTEST.PERFORMANCE_LEVEL, LASTTEST.TEST_NAME, LASTTEST.ADMIN_DATE
 FROM 
APS.LCELatestEvaluationAsOf(GETDATE()) AS LASTTEST
INNER JOIN 
rev.EPC_STU AS STU 
ON
LASTTEST.STUDENT_GU = STU.STUDENT_GU

WHERE 
IS_ELL = 0
AND ADMIN_DATE BETWEEN '2014-07-01' AND '2015-07-01'