

SELECT SIS_NUMBER, THECOUNT FROM (

SELECT 
	COUNT (*) AS THECOUNT, STUDENT_GU
 FROM
	rev.EPC_STU_PGM_ELL_HIS AS HISTORY
GROUP BY STUDENT_GU

) AS T1

INNER JOIN
rev.EPC_STU AS STUDENT
ON
T1.STUDENT_GU = STUDENT.STUDENT_GU

WHERE THECOUNT =2
ORDER BY THECOUNT