

EXECUTE AS LOGIN='QueryFileUser'
GO

SELECT DISTINCT 
	LAST_NAME
	,FIRST_NAME
	,SIS_NUMBER
	, MID_SCHOOL_ATTENDED
	,HIGH_SCHOOL_ATTENDED
	,HIST.COURSE_ID
	,HIST.COURSE_TITLE
	,HIST.MARK
	,GRADE
	,SCHOOL_COURSE_TAKEN
 FROM 


(
SELECT 
	LAST_NAME
	,FIRST_NAME
	,SIS_NUMBER
	,MIDSCHOOL_ATTENDED.MIDSCHOOL AS MID_SCHOOL_ATTENDED
	,HIGHSCHOOL_ATTENDED.MIDSCHOOL AS HIGH_SCHOOL_ATTENDED
	,HIST.COURSE_ID
	,HIST.COURSE_TITLE
	,HIST.MARK
	,VALUE_DESCRIPTION AS GRADE
	,CASE WHEN ORG.ORGANIZATION_NAME IS NULL THEN NONSCH.NAME ELSE ORG.ORGANIZATION_NAME END AS SCHOOL_COURSE_TAKEN

FROM

            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT * from SET1.csv'
                ) AS [SET1]

INNER JOIN 
rev.EPC_STU_CRS_HIS AS HIST
ON
CAST(SET1.COURSE AS VARCHAR) = HIST.COURSE_ID

INNER JOIN 

(SELECT DISTINCT 
	STUDENT_GU
 FROM 
APS.StudentEnrollmentDetails AS ENR
WHERE
SCHOOL_YEAR = 2015
AND EXTENSION = 'R'
AND SUMMER_WITHDRAWL_CODE IS NULL)


 AS PRIM
ON
HIST.STUDENT_GU = PRIM.STUDENT_GU

INNER JOIN
rev.REV_PERSON AS PERS
ON
PRIM.STUDENT_GU = PERS.PERSON_GU

INNER JOIN 
rev.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU

LEFT JOIN
rev.EPC_SCH_NON_DST AS NONSCH
ON
NONSCH.SCHOOL_NON_DISTRICT_GU = HIST.SCHOOL_NON_DISTRICT_GU

LEFT JOIN
rev.REV_ORGANIZATION AS ORG
ON
HIST.SCHOOL_IN_DISTRICT_GU = ORG.ORGANIZATION_GU

LEFT HASH JOIN 
(
SELECT * FROM (
SELECT 
STUDENT_GU
,CASE WHEN ORG.ORGANIZATION_NAME IS NULL THEN NONSCH.NAME ELSE ORG.ORGANIZATION_NAME END AS MIDSCHOOL
,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY SCHOOL_YEAR DESC, MIDHIST.CALENDAR_MONTH) AS RN
 FROM 
rev.EPC_STU_CRS_HIS AS MIDHIST
LEFT JOIN
rev.EPC_SCH_NON_DST AS NONSCH
ON
NONSCH.SCHOOL_NON_DISTRICT_GU = MIDHIST.SCHOOL_NON_DISTRICT_GU

LEFT JOIN
rev.REV_ORGANIZATION AS ORG
ON
MIDHIST.SCHOOL_IN_DISTRICT_GU = ORG.ORGANIZATION_GU

WHERE
MIDHIST.COURSE_HISTORY_TYPE = 'MID'
) AS T2
WHERE
RN = 1
) AS MIDSCHOOL_ATTENDED

ON
MIDSCHOOL_ATTENDED.STUDENT_GU = PRIM.STUDENT_GU

LEFT HASH JOIN 
(
SELECT * FROM (
SELECT 
STUDENT_GU
,CASE WHEN ORG.ORGANIZATION_NAME IS NULL THEN NONSCH.NAME ELSE ORG.ORGANIZATION_NAME END AS MIDSCHOOL
,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY SCHOOL_YEAR DESC, HIGHHIST.CALENDAR_MONTH) AS RN
 FROM 
rev.EPC_STU_CRS_HIS AS HIGHHIST
LEFT JOIN
rev.EPC_SCH_NON_DST AS NONSCH
ON
NONSCH.SCHOOL_NON_DISTRICT_GU = HIGHHIST.SCHOOL_NON_DISTRICT_GU

LEFT JOIN
rev.REV_ORGANIZATION AS ORG
ON
HIGHHIST.SCHOOL_IN_DISTRICT_GU = ORG.ORGANIZATION_GU

WHERE
HIGHHIST.COURSE_HISTORY_TYPE = 'HIGH'
) AS T2
WHERE
RN = 1
) AS HIGHSCHOOL_ATTENDED

ON
PRIM.STUDENT_GU = HIGHSCHOOL_ATTENDED.STUDENT_GU

INNER JOIN 
APS.LookupTable ('K12','Grade') AS GRADE
ON
HIST.GRADE = GRADE.VALUE_CODE
) AS SET1

/***********************************

--ONLY WANT KIDS THAT ARE IN BOTH FILES

************************************/

INNER JOIN 
 (SELECT 
	LAST_NAME
	,FIRST_NAME
	,SIS_NUMBER
	,MIDSCHOOL_ATTENDED.MIDSCHOOL AS MID_SCHOOL_ATTENDED
	,HIGHSCHOOL_ATTENDED.MIDSCHOOL AS HIGH_SCHOOL_ATTENDED
	,HIST.COURSE_ID
	,HIST.COURSE_TITLE
	,HIST.MARK
	,VALUE_DESCRIPTION AS GRADE
	,CASE WHEN ORG.ORGANIZATION_NAME IS NULL THEN NONSCH.NAME ELSE ORG.ORGANIZATION_NAME END AS SCHOOL_COURSE_TAKEN

FROM

            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT * from SET2.csv'
                ) AS [SET2]

INNER JOIN 
rev.EPC_STU_CRS_HIS AS HIST
ON
CAST(SET2.COURSE AS VARCHAR) = HIST.COURSE_ID

INNER JOIN 

(SELECT DISTINCT 
	STUDENT_GU
 FROM 
APS.StudentEnrollmentDetails AS ENR
WHERE
SCHOOL_YEAR = 2015
AND EXTENSION = 'R'
AND SUMMER_WITHDRAWL_CODE IS NULL)


 AS PRIM
ON
HIST.STUDENT_GU = PRIM.STUDENT_GU

INNER JOIN
rev.REV_PERSON AS PERS
ON
PRIM.STUDENT_GU = PERS.PERSON_GU

INNER JOIN 
rev.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU

LEFT JOIN
rev.EPC_SCH_NON_DST AS NONSCH
ON
NONSCH.SCHOOL_NON_DISTRICT_GU = HIST.SCHOOL_NON_DISTRICT_GU

LEFT JOIN
rev.REV_ORGANIZATION AS ORG
ON
HIST.SCHOOL_IN_DISTRICT_GU = ORG.ORGANIZATION_GU

LEFT HASH JOIN 
(
SELECT * FROM (
SELECT 
STUDENT_GU
,CASE WHEN ORG.ORGANIZATION_NAME IS NULL THEN NONSCH.NAME ELSE ORG.ORGANIZATION_NAME END AS MIDSCHOOL
,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY SCHOOL_YEAR DESC, MIDHIST.CALENDAR_MONTH) AS RN
 FROM 
rev.EPC_STU_CRS_HIS AS MIDHIST
LEFT JOIN
rev.EPC_SCH_NON_DST AS NONSCH
ON
NONSCH.SCHOOL_NON_DISTRICT_GU = MIDHIST.SCHOOL_NON_DISTRICT_GU

LEFT JOIN
rev.REV_ORGANIZATION AS ORG
ON
MIDHIST.SCHOOL_IN_DISTRICT_GU = ORG.ORGANIZATION_GU

WHERE
MIDHIST.COURSE_HISTORY_TYPE = 'MID'
) AS T2
WHERE
RN = 1
) AS MIDSCHOOL_ATTENDED

ON
MIDSCHOOL_ATTENDED.STUDENT_GU = PRIM.STUDENT_GU

LEFT HASH JOIN 
(
SELECT * FROM (
SELECT 
STUDENT_GU
,CASE WHEN ORG.ORGANIZATION_NAME IS NULL THEN NONSCH.NAME ELSE ORG.ORGANIZATION_NAME END AS MIDSCHOOL
,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY SCHOOL_YEAR DESC, HIGHHIST.CALENDAR_MONTH) AS RN
 FROM 
rev.EPC_STU_CRS_HIS AS HIGHHIST
LEFT JOIN
rev.EPC_SCH_NON_DST AS NONSCH
ON
NONSCH.SCHOOL_NON_DISTRICT_GU = HIGHHIST.SCHOOL_NON_DISTRICT_GU

LEFT JOIN
rev.REV_ORGANIZATION AS ORG
ON
HIGHHIST.SCHOOL_IN_DISTRICT_GU = ORG.ORGANIZATION_GU

WHERE
HIGHHIST.COURSE_HISTORY_TYPE = 'HIGH'
) AS T2
WHERE
RN = 1
) AS HIGHSCHOOL_ATTENDED

ON
PRIM.STUDENT_GU = HIGHSCHOOL_ATTENDED.STUDENT_GU

INNER JOIN 
APS.LookupTable ('K12','Grade') AS GRADE
ON
HIST.GRADE = GRADE.VALUE_CODE

) AS SET2

ON
SET1.SIS_NUMBER = SET2.SIS_NUMBER


      REVERT
GO