
SELECT ORGANIZATION_NAME
,PROGRAM_MODEL

FROM

(
SELECT DISTINCT
	ORGANIZATION_NAME
	,'2-Way Dual' AS PROGRAM_MODEL
FROM

	(
	SELECT 
	STUDENT_GU
	,PROGRAM_CODE 
	FROM(
	SELECT 
		STUDENT_GU
		,PROGRAM_CODE
		,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY ENTER_DATE DESC) AS RN
	FROM
		REV.EPC_STU_PGM_ELL_BEP
	)AS MOSTRECENTBEP
	WHERE
	RN = 1
	) AS BEP

	INNER JOIN
	rev.EPC_STU AS STU
	ON
	BEP.STUDENT_GU = STU.STUDENT_GU
	LEFT JOIN
	APS.LCELatestSpanishEvaluationAsOf(GETDATE()) AS TESTS
	ON
	STU.STUDENT_GU = TESTS.STUDENT_GU
	LEFT JOIN
	APS.LookupTable ('K12.TestInfo','PERFORMANCE_LEVELS') AS PL
	ON
	PL.VALUE_CODE = TESTS.PERFORMANCE_LEVEL

	INNER JOIN
	rev.EPC_STU_YR AS SSY
	ON
	SSY.STUDENT_GU = STU.STUDENT_GU
	AND SSY.YEAR_GU = (SELECT * FROM rev.SIF_22_Common_CurrentYearGU)

	INNER JOIN
	rev.EPC_STU_SCH_YR AS SSY2
	ON
	SSY2.STUDENT_SCHOOL_YEAR_GU = SSY.STU_SCHOOL_YEAR_GU

	INNER JOIN
	APS.LookupTable ('K12', 'GRADE') AS GRADEL
	ON
	GRADEL.VALUE_CODE = SSY2.GRADE

	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	SSY2.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU

	INNER JOIN
	rev.REV_ORGANIZATION AS ORG
	ON
	ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

	INNER JOIN
	APS.LookupTable ('K12.ProgramInfo', 'BEP_PROGRAM_CODE') AS MODEL
	ON
	BEP.PROGRAM_CODE = MODEL.VALUE_CODE

WHERE
	ADMIN_DATE > '2014-08-01'

) AS T1

UNION ALL

SELECT DISTINCT
	ORGANIZATION_NAME
	,'Maintenance' AS TWO
FROM

	(
	SELECT 
	STUDENT_GU
	,PROGRAM_CODE 
	FROM(
	SELECT 
		STUDENT_GU
		,PROGRAM_CODE
		,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY ENTER_DATE DESC) AS RN
	FROM
		REV.EPC_STU_PGM_ELL_BEP
	)AS MOSTRECENTBEP
	WHERE
	RN = 1
	) AS BEP

	INNER JOIN
	rev.EPC_STU AS STU
	ON
	BEP.STUDENT_GU = STU.STUDENT_GU
	LEFT JOIN
	APS.LCELatestSpanishEvaluationAsOf(GETDATE()) AS TESTS
	ON
	STU.STUDENT_GU = TESTS.STUDENT_GU
	LEFT JOIN
	APS.LookupTable ('K12.TestInfo','PERFORMANCE_LEVELS') AS PL
	ON
	PL.VALUE_CODE = TESTS.PERFORMANCE_LEVEL

	INNER JOIN
	rev.EPC_STU_YR AS SSY
	ON
	SSY.STUDENT_GU = STU.STUDENT_GU
	AND SSY.YEAR_GU = (SELECT * FROM rev.SIF_22_Common_CurrentYearGU)

	INNER JOIN
	rev.EPC_STU_SCH_YR AS SSY2
	ON
	SSY2.STUDENT_SCHOOL_YEAR_GU = SSY.STU_SCHOOL_YEAR_GU

	INNER JOIN
	APS.LookupTable ('K12', 'GRADE') AS GRADEL
	ON
	GRADEL.VALUE_CODE = SSY2.GRADE

	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	SSY2.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU

	INNER JOIN
	rev.REV_ORGANIZATION AS ORG
	ON
	ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

	INNER JOIN
	APS.LookupTable ('K12.ProgramInfo', 'BEP_PROGRAM_CODE') AS MODEL
	ON
	BEP.PROGRAM_CODE = MODEL.VALUE_CODE

WHERE
	ADMIN_DATE > '2014-08-01'


UNION ALL

SELECT DISTINCT
	ORGANIZATION_NAME
	,'Enrichment' AS Three
FROM

	(
	SELECT 
	STUDENT_GU
	,PROGRAM_CODE 
	FROM(
	SELECT 
		STUDENT_GU
		,PROGRAM_CODE
		,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY ENTER_DATE DESC) AS RN
	FROM
		REV.EPC_STU_PGM_ELL_BEP
	)AS MOSTRECENTBEP
	WHERE
	RN = 1
	) AS BEP

	INNER JOIN
	rev.EPC_STU AS STU
	ON
	BEP.STUDENT_GU = STU.STUDENT_GU
	LEFT JOIN
	APS.LCELatestSpanishEvaluationAsOf(GETDATE()) AS TESTS
	ON
	STU.STUDENT_GU = TESTS.STUDENT_GU
	LEFT JOIN
	APS.LookupTable ('K12.TestInfo','PERFORMANCE_LEVELS') AS PL
	ON
	PL.VALUE_CODE = TESTS.PERFORMANCE_LEVEL

	INNER JOIN
	rev.EPC_STU_YR AS SSY
	ON
	SSY.STUDENT_GU = STU.STUDENT_GU
	AND SSY.YEAR_GU = (SELECT * FROM rev.SIF_22_Common_CurrentYearGU)

	INNER JOIN
	rev.EPC_STU_SCH_YR AS SSY2
	ON
	SSY2.STUDENT_SCHOOL_YEAR_GU = SSY.STU_SCHOOL_YEAR_GU

	INNER JOIN
	APS.LookupTable ('K12', 'GRADE') AS GRADEL
	ON
	GRADEL.VALUE_CODE = SSY2.GRADE

	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	SSY2.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU

	INNER JOIN
	rev.REV_ORGANIZATION AS ORG
	ON
	ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

	INNER JOIN
	APS.LookupTable ('K12.ProgramInfo', 'BEP_PROGRAM_CODE') AS MODEL
	ON
	BEP.PROGRAM_CODE = MODEL.VALUE_CODE

WHERE
	ADMIN_DATE > '2014-08-01'
	
ORDER BY ORGANIZATION_NAME, PROGRAM_MODEL
