
--DROP TABLE MEMBERDAYS_2013

--CREATE TABLE MEMBERDAYS_2013 (
--   IDNBR           VARCHAR (9)
-- , SCHYR         VARCHAR (4)
-- , SCHNBR    VARCHAR(3)
-- , NONADA	VARCHAR (4)
--, GRADE     VARCHAR(2)
-- , MEMBERDAYS INT
-- )

INSERT INTO MEMBERDAYS_2013

SELECT ENR.ID_NBR, ENR.SCH_YR, ENR.SCH_NBR, ENR.NONADA_SCH, ENR.GRDE, MEM.MemberDays
	
 FROM 
APS.EnrollmentMemberDaysAsOf('2014-05-22') AS MEM
INNER JOIN 
DBTSIS.ST010 AS ENR
ON
MEM.Enrollment_Id = ENR._Id

WHERE
SCH_YR = '2014'
--AND ENR.NONADA_SCH != 'X'



