--DROP TABLE ATTENDANCE_2012

CREATE TABLE ATTENDANCE_2014 
(
   TOTAL_ABSENCE_DAYS   VARCHAR (9)
 , SCHYR				VARCHAR (4)
 , SCHNBR				VARCHAR(4)
 , IDNBR				VARCHAR(9)
)

INSERT INTO ATTENDANCE_2014


--LEFT HASH JOIN 
--(
SELECT 
	CAST(SUM(TOTAL_FULLDAYS + TOTAL_HALFDAYS)AS VARCHAR) AS TOTAL_ABSENCE_DAYS 
	,CAST(SCH_YR AS VARCHAR) AS SCHYR
	,SCH_NBR
	,CAST(ID_NBR AS VARCHAR) AS IDNBR
FROM (
SELECT 
CAST(USRDATA AS INT) AS TOTALS
, SCH_YR, ID_NBR, SCH_NBR 
,FIELDNUM
,CASE WHEN FIELDNUM IN ('50', '55') THEN CAST(USRDATA AS INT) * .5 ELSE 0 END AS TOTAL_HALFDAYS
,CASE WHEN FIELDNUM IN ('0', '5') THEN CAST(USRDATA AS INT) ELSE 0 END AS TOTAL_FULLDAYS
FROM 
DBTSIS.IV030_V
WHERE
SCH_NBR != ''
AND ISPECNAME = 'ATDAY'
AND FIELDNUM IN ('50', '55', '0', '5')
AND SCH_YR = 2014
--ORDER BY SCH_YR
) AS T1
GROUP BY  SCH_YR, ID_NBR, SCH_NBR
--) AS ATTENDANCE