

SELECT SIS_NUMBER, SCHOOL_YEAR, EXTENSION, SCHOOL_CODE, SCHOOL_NAME

, ENR.ENTER_DATE AS ENR_ENTER_DATE
, ENR.ENTER_CODE AS ENR_ENTER_CODE
, ENR.LEAVE_DATE AS ENR_LEAVE_DATE
, ENR.LEAVE_CODE AS ENR_LEAVE_CODE 

, SSY.ENTER_DATE AS SSY_ENTER_DATE
, SSY.ENTER_CODE AS SSY_ENTER_CODE
, SSY.LEAVE_DATE AS SSY_LEAVE_DATE
, SSY.LEAVE_CODE AS SSY_LEAVE_CODE


FROM 
APS.StudentEnrollmentDetails AS ENR
INNER JOIN 
rev.EPC_STU_SCH_YR AS SSY
ON
ENR.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU
INNER JOIN 
REV.EPC_STU_ENROLL AS ENROLL
ON
ENROLL.STUDENT_SCHOOL_YEAR_GU = ENR.STUDENT_SCHOOL_YEAR_GU


WHERE
SCHOOL_YEAR = '2016'
AND EXTENSION = 'R'
AND SCHOOL_NAME LIKE 'COMMUNITY%'
AND ENR.LEAVE_DATE IS NULL

ORDER BY SIS_NUMBER