

BEGIN TRANSACTION

UPDATE rev.EPC_STU_SCH_YR
	SET LEAVE_DATE = '2017-05-01', LEAVE_CODE = 'TRAPS', CHANGE_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F', CHANGE_DATE_TIME_STAMP = GETDATE()
FROM
(
SELECT SIS_NUMBER, SCHOOL_YEAR, EXTENSION, SCHOOL_CODE, SCHOOL_NAME, SSY.STUDENT_SCHOOL_YEAR_GU

, ENR.ENTER_DATE AS ENR_ENTER_DATE
, ENR.ENTER_CODE AS ENR_ENTER_CODE
, ENR.LEAVE_DATE AS ENR_LEAVE_DATE
, ENR.LEAVE_CODE AS ENR_LEAVE_CODE 

, SSY.ENTER_DATE AS SSY_ENTER_DATE
, SSY.ENTER_CODE AS SSY_ENTER_CODE
, SSY.LEAVE_DATE AS SSY_LEAVE_DATE
, SSY.LEAVE_CODE AS SSY_LEAVE_CODE

FROM 
APS.StudentEnrollmentDetails AS ENR
INNER JOIN 
rev.EPC_STU_SCH_YR AS SSY
ON
ENR.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU
INNER JOIN 
REV.EPC_STU_ENROLL AS ENROLL
ON
ENROLL.STUDENT_SCHOOL_YEAR_GU = ENR.STUDENT_SCHOOL_YEAR_GU


WHERE
SCHOOL_YEAR = '2016'
AND EXTENSION = 'R'
AND SCHOOL_NAME LIKE 'COMMUNITY%'
AND ENR.LEAVE_DATE IS NULL

--ORDER BY SIS_NUMBER
) AS T1

WHERE
rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU = T1.STUDENT_SCHOOL_YEAR_GU

COMMIT

BEGIN TRANSACTION

UPDATE rev.EPC_STU_ENROLL
	SET LEAVE_DATE = '2017-05-01', LEAVE_CODE = 'TRAPS', CHANGE_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F', CHANGE_DATE_TIME_STAMP = GETDATE()
FROM
(
SELECT SIS_NUMBER, SCHOOL_YEAR, EXTENSION, SCHOOL_CODE, SCHOOL_NAME, ENROLL.ENROLLMENT_GU, ENROLL.STUDENT_SCHOOL_YEAR_GU

, ENR.ENTER_DATE AS ENR_ENTER_DATE
, ENR.ENTER_CODE AS ENR_ENTER_CODE
, ENR.LEAVE_DATE AS ENR_LEAVE_DATE
, ENR.LEAVE_CODE AS ENR_LEAVE_CODE 

, SSY.ENTER_DATE AS SSY_ENTER_DATE
, SSY.ENTER_CODE AS SSY_ENTER_CODE
, SSY.LEAVE_DATE AS SSY_LEAVE_DATE
, SSY.LEAVE_CODE AS SSY_LEAVE_CODE

FROM 
APS.StudentEnrollmentDetails AS ENR
INNER JOIN 
rev.EPC_STU_SCH_YR AS SSY
ON
ENR.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU
INNER JOIN 
REV.EPC_STU_ENROLL AS ENROLL
ON
ENROLL.STUDENT_SCHOOL_YEAR_GU = ENR.STUDENT_SCHOOL_YEAR_GU


WHERE
SCHOOL_YEAR = '2016'
AND EXTENSION = 'R'
AND SCHOOL_NAME LIKE 'COMMUNITY%'
AND ENROLL.LEAVE_DATE IS NULL

--ORDER BY SIS_NUMBER
) AS T1

WHERE
rev.EPC_STU_ENROLL.STUDENT_SCHOOL_YEAR_GU = T1.STUDENT_SCHOOL_YEAR_GU
AND rev.EPC_STU_ENROLL.ENROLLMENT_GU = T1.ENROLLMENT_GU

COMMIT


BEGIN TRANSACTION

UPDATE rev.EPC_STU_SCH_YR
	SET [STATUS] = 'I', CHANGE_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F', CHANGE_DATE_TIME_STAMP = GETDATE()
FROM
(
SELECT SIS_NUMBER, SCHOOL_YEAR, EXTENSION, SCHOOL_CODE, SCHOOL_NAME, SSY.STUDENT_SCHOOL_YEAR_GU

, ENR.ENTER_DATE AS ENR_ENTER_DATE
, ENR.ENTER_CODE AS ENR_ENTER_CODE
, ENR.LEAVE_DATE AS ENR_LEAVE_DATE
, ENR.LEAVE_CODE AS ENR_LEAVE_CODE 

, SSY.ENTER_DATE AS SSY_ENTER_DATE
, SSY.ENTER_CODE AS SSY_ENTER_CODE
, SSY.LEAVE_DATE AS SSY_LEAVE_DATE
, SSY.LEAVE_CODE AS SSY_LEAVE_CODE

FROM 
APS.StudentEnrollmentDetails AS ENR
INNER JOIN 
rev.EPC_STU_SCH_YR AS SSY
ON
ENR.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU
INNER JOIN 
REV.EPC_STU_ENROLL AS ENROLL
ON
ENROLL.STUDENT_SCHOOL_YEAR_GU = ENR.STUDENT_SCHOOL_YEAR_GU


WHERE
SCHOOL_YEAR = '2016'
AND EXTENSION = 'R'
AND SCHOOL_NAME LIKE 'COMMUNITY%'
--AND ENR.LEAVE_DATE IS NULL

--ORDER BY SIS_NUMBER
) AS T1

WHERE
rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU = T1.STUDENT_SCHOOL_YEAR_GU

COMMIT