


-- 2017 - A3F9F1FB-4706-49AA-B3A3-21F153966191
-- 2016 - F7D112F7-354D-4630-A4BC-65F586BA42EC
-- 2015 - BCFE2270-A461-4260-BA2B-0087CB8EC26A
-- 2014 - 26F066A3-ABFC-4EDB-B397-43412EDABC8B

SELECT 
	ORGANIZATION_NAME, BS.LAST_NAME, BS.FIRST_NAME, BS.SIS_NUMBER, SCH.COURSE_ID, CRS.STATE_COURSE_CODE, SCH.COURSE_TITLE, SCH.COURSE_ENTER_DATE, SCH.COURSE_LEAVE_DATE
	,IND.END_OF_COURSE_INDICATOR
	--,CRS.CTE_COURSE_LEVEL, CRS.CTE_CREDIT_EQUIVALENCY, CRS.CTE_CREDITS_REQ, CRS.CTE_CRS_EQUIVALENCY_ID, CRS.CTE_GENDER_TYPE, CRS.CTE_TOTAL_DURATION
	,CTEPROG.TITLE,  PROG.CODE, CLSTR.CAREER_CLUSTER, LU.VALUE_DESCRIPTION AS CTE_CAREER_CLUSTER
	, TESTS.*

 FROM 
APS.ScheduleForYear('26F066A3-ABFC-4EDB-B397-43412EDABC8B') AS SCH
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU 
INNER JOIN 
APS.BasicStudent AS BS
ON
SCH.STUDENT_GU = BS.STUDENT_GU
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU
LEFT JOIN 
REV.EPC_MN_CRS AS IND
ON
IND.COURSE_GU = CRS.COURSE_GU


LEFT JOIN 
REV.EPC_CTE_PROGRAM_CRS AS CTE1
ON
CTE1.COURSE_GU = CRS.COURSE_GU

LEFT JOIN 
REV.EPC_CTE_PROGRAM AS PROG
ON
PROG.CTE_PROGRAM_GU = CTE1.CTE_PROGRAM_GU

LEFT JOIN 
REV.EPC_CTE_PROG_CAREER_CLSTR AS CLSTR
ON
CLSTR.CTE_PROGRAM_GU = CTE1.CTE_PROGRAM_GU
LEFT JOIN 
REV.EPC_CTE_PROGRAM AS CTEPROG
ON
CTEPROG.CTE_PROGRAM_GU = CTE1.CTE_PROGRAM_GU

LEFT JOIN 
APS.LookupTable ('K12.CourseInfo', 'CTE_CAREER_CLUSTERS') AS LU
ON
LU.VALUE_CODE = CLSTR.CAREER_CLUSTER

LEFT JOIN 
(SELECT 
--DISTINCT SIS_NUMBER, SCHOOL

       SCHOOL
	   ,SYN.FIRST_NAME
       ,SYN.LAST_NAME
      -- ,ACCU.STUDENT_CODE
       ,SIS_NUMBER
       ,GRADE
	   ,TEST_NAME
      -- ,ACCU.TEST_SECTION_NAME
       ,PART_DESCRIPTION
       ,SCORE_DESCRIPTION
       ,PERFORMANCE_LEVEL
       ,TEST_SCORE
       --,ACCU.SCALED_SCORE
       ,CAST (ADMIN_DATE AS DATE) AS DATES
       ,ADMIN_DATE
       ,PART_NUMBER


FROM
(
SELECT 
       ORG.ORGANIZATION_NAME AS SCHOOL
	   ,PERSON.FIRST_NAME
       ,PERSON.LAST_NAME
       ,SIS_NUMBER
       ,GRADE.VALUE_DESCRIPTION AS GRADE
	   ,TEST.TEST_NAME
      /*
	   ,CASE 
             WHEN PART.PART_DESCRIPTION = 'ELEMENTARY ALGEGRA' THEN 'Elementary Algebra'
             ELSE PART.PART_DESCRIPTION
       END AS PART_DESCRIPTION
	   */
	   ,PART_DESCRIPTION
       ,SCORE_DESCRIPTION
       ,STU_PART.PERFORMANCE_LEVEL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
       ,PART.PART_NUMBER
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

       INNER JOIN
       rev.REV_PERSON AS Person
       ON Person.PERSON_GU = StudentTest.STUDENT_GU

       INNER JOIN
       APS.PrimaryEnrollmentsAsOf(GETDATE()) AS Enroll
       ON
       StudentTest.STUDENT_GU = Enroll.STUDENT_GU

       INNER JOIN
       rev.REV_ORGANIZATION_YEAR AS OrgYear
       ON
       Enroll.ORGANIZATION_YEAR_GU = OrgYear.ORGANIZATION_YEAR_GU

       INNER JOIN
       rev.REV_ORGANIZATION AS Org
       ON
       OrgYear.ORGANIZATION_GU = Org.ORGANIZATION_GU

       LEFT JOIN
       APS.LookupTable('K12','Grade') AS GRADE
       ON
       Enroll.GRADE = GRADE.VALUE_CODE


WHERE
       TEST_NAME like '%EOC%'
	  
) AS SYN
) AS TESTS

ON 
BS.SIS_NUMBER = TESTS.SIS_NUMBER


WHERE
SUBSTRING(CRS.STATE_COURSE_CODE,5,1) = '7'

ORDER BY ORGANIZATION_NAME