


-- 2017 - A3F9F1FB-4706-49AA-B3A3-21F153966191
-- 2016 - F7D112F7-354D-4630-A4BC-65F586BA42EC
-- 2015 - BCFE2270-A461-4260-BA2B-0087CB8EC26A
-- 2014 - 26F066A3-ABFC-4EDB-B397-43412EDABC8B

SELECT 
	ORGANIZATION_NAME, BS.LAST_NAME, BS.FIRST_NAME, BS.SIS_NUMBER, SCH.COURSE_ID, CRS.STATE_COURSE_CODE, SCH.COURSE_TITLE, SCH.COURSE_ENTER_DATE, SCH.COURSE_LEAVE_DATE
	,IND.END_OF_COURSE_INDICATOR
	--,CRS.CTE_COURSE_LEVEL, CRS.CTE_CREDIT_EQUIVALENCY, CRS.CTE_CREDITS_REQ, CRS.CTE_CRS_EQUIVALENCY_ID, CRS.CTE_GENDER_TYPE, CRS.CTE_TOTAL_DURATION
	,CTEPROG.TITLE,  PROG.CODE, CLSTR.CAREER_CLUSTER, LU.VALUE_DESCRIPTION AS CTE_CAREER_CLUSTER
 FROM 
APS.ScheduleForYear('26F066A3-ABFC-4EDB-B397-43412EDABC8B') AS SCH
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU 
INNER JOIN 
APS.BasicStudent AS BS
ON
SCH.STUDENT_GU = BS.STUDENT_GU
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN 
REV.EPC_MN_CRS AS IND
ON
IND.COURSE_GU = CRS.COURSE_GU


LEFT JOIN 
REV.EPC_CTE_PROGRAM_CRS AS CTE1
ON
CTE1.COURSE_GU = CRS.COURSE_GU

LEFT JOIN 
REV.EPC_CTE_PROGRAM AS PROG
ON
PROG.CTE_PROGRAM_GU = CTE1.CTE_PROGRAM_GU

LEFT JOIN 
REV.EPC_CTE_PROG_CAREER_CLSTR AS CLSTR
ON
CLSTR.CTE_PROGRAM_GU = CTE1.CTE_PROGRAM_GU
LEFT JOIN 
REV.EPC_CTE_PROGRAM AS CTEPROG
ON
CTEPROG.CTE_PROGRAM_GU = CTE1.CTE_PROGRAM_GU

LEFT JOIN 
APS.LookupTable ('K12.CourseInfo', 'CTE_CAREER_CLUSTERS') AS LU
ON
LU.VALUE_CODE = CLSTR.CAREER_CLUSTER

WHERE
SUBSTRING(CRS.STATE_COURSE_CODE,5,1) = '7'

ORDER BY ORGANIZATION_NAME