
SELECT  

	CRS.COURSE_ID, CRS.COURSE_TITLE, CRS.COURSE_SHORT_TITLE,crs.CREDIT, CRS.COURSE_HISTORY_TYPE, CRS.ACADEMIC_TYPE, 
	CRS.STATE_COURSE_CODE, 
	
	--CTE1.TECHNICAL_PROVIDER, CTE1.COURSE_LEVEL , cte1.CREDITS_REQ
	crs.TECHNICAL_PROVIDER, crs.CTE_COURSE_LEVEL, crs.CTE_CREDITS_REQ, crs.PERKINS_FUNDED, crs.GENDER_REQUIREMENT

	--, cte1.PERKINS_FUNDED, PROG.GENDER
	, LST.COURSE_LEVEL,

	IND.END_OF_COURSE_INDICATOR,
	PROG.CODE, 
	--,CRS.CTE_COURSE_LEVEL, CRS.CTE_CREDIT_EQUIVALENCY, CRS.CTE_CREDITS_REQ, CRS.CTE_CRS_EQUIVALENCY_ID, CRS.CTE_GENDER_TYPE, CRS.CTE_TOTAL_DURATION
	CTEPROG.TITLE,  CLSTR.CAREER_CLUSTER, LU.VALUE_DESCRIPTION AS CTE_CAREER_CLUSTER
FROM 
REV.EPC_CRS AS CRS

LEFT JOIN 
REV.EPC_MN_CRS AS IND
ON
IND.COURSE_GU = CRS.COURSE_GU


LEFT JOIN 
REV.EPC_CTE_PROGRAM_CRS AS CTE1
ON
CTE1.COURSE_GU = CRS.COURSE_GU

LEFT JOIN 
REV.EPC_CTE_PROGRAM AS PROG
ON
PROG.CTE_PROGRAM_GU = CTE1.CTE_PROGRAM_GU

LEFT JOIN 
REV.EPC_CTE_PROG_CAREER_CLSTR AS CLSTR
ON
CLSTR.CTE_PROGRAM_GU = CTE1.CTE_PROGRAM_GU
LEFT JOIN 
REV.EPC_CTE_PROGRAM AS CTEPROG
ON
CTEPROG.CTE_PROGRAM_GU = CTE1.CTE_PROGRAM_GU

LEFT JOIN 
APS.LookupTable ('K12.CourseInfo', 'CTE_CAREER_CLUSTERS') AS LU
ON
LU.VALUE_CODE = CLSTR.CAREER_CLUSTER

LEFT JOIN 
REV.EPC_CRS_LEVEL_LST AS LST
ON
CRS.COURSE_GU = LST.COURSE_GU


WHERE
LST.COURSE_LEVEL = 'C'
--AND CRS.INACTIVE = 'N'


ORDER BY COURSE_ID