
SELECT * FROM (
SELECT

	CRS.COURSE_ID, CRS.COURSE_TITLE, CRS.COURSE_SHORT_TITLE,crs.CREDIT, CRS.COURSE_HISTORY_TYPE, CRS.ACADEMIC_TYPE, 
	CRS.STATE_COURSE_CODE, 
	
	--CTE1.TECHNICAL_PROVIDER, CTE1.COURSE_LEVEL , cte1.CREDITS_REQ
	crs.TECHNICAL_PROVIDER, crs.CTE_COURSE_LEVEL, crs.CTE_CREDITS_REQ, crs.PERKINS_FUNDED, crs.GENDER_REQUIREMENT

	--, cte1.PERKINS_FUNDED, PROG.GENDER
	, LST.COURSE_LEVEL

	--IND.END_OF_COURSE_INDICATOR,
	--PROG.CODE, 
	--,CRS.CTE_COURSE_LEVEL, CRS.CTE_CREDIT_EQUIVALENCY, CRS.CTE_CREDITS_REQ, CRS.CTE_CRS_EQUIVALENCY_ID, CRS.CTE_GENDER_TYPE, CRS.CTE_TOTAL_DURATION
	--CTEPROG.TITLE,  CLSTR.CAREER_CLUSTER, LU.VALUE_DESCRIPTION AS CTE_CAREER_CLUSTER
FROM 
REV.EPC_CRS AS CRS

LEFT JOIN 
REV.EPC_CRS_LEVEL_LST AS LST
ON
CRS.COURSE_GU = LST.COURSE_GU


WHERE
--LST.COURSE_LEVEL = 'C'
--AND 
CRS.INACTIVE = 'N'
) AS DCM

PIVOT
(
MAX(COURSE_LEVEL)
FOR COURSE_LEVEL IN ([BEP],[N],[H],[E],[A],[EXG],[D],[P],[L],[G],[GFT],[ESL],[C],[BLOCK],[EXA],[I]) 
) AS PIVOTME