

/*

-- MUST RUN EACH ONE INDIVIDUALLY -- REFERENTIAL INTEGRITY EXISTS IN THESE TABLES:  

REV.EPC_STU_ENROLL_ACTIVITY - ENROLLMENT_GU
rev.EPC_STU_ATT_DAILY -ENROLLMENT_GU
REV.EPC_STU_ENROLL - ENROLLMENT_GU
REV.EPC_STU_YR - STU_SCHOOL_YEAR_GU
REV.EPC_STU_CLASS - STUDENT_SCHOOL_YEAR_GU
rev.EPC_STU_SCH_YR - STUDENT_SCHOOL_YEAR_GU

*/

EXECUTE AS LOGIN='QueryFileUser'
GO

BEGIN TRAN

DELETE rev.EPC_STU_SCH_YR

--DELETE rev.EPC_STU_SCH_YR

FROM
(

SELECT STUDENT_SCHOOL_YEAR_GU FROM 

(
SELECT 
	STU.SIS_NUMBER, ENR.SCHOOL_NAME AS JUMP_SCHOOL
	,CASE WHEN LEFT(ENR.SCHOOL_NAME,5) != LEFT(T1.[Homeschool Site],5) THEN 'NOT AT JUMP SCHOOL'
		  WHEN STU.SIS_NUMBER IS NULL THEN 'NO SIS NUMBER'
		  WHEN ENR.SCHOOL_NAME IS NULL THEN 'NO JUMPSTART ENROLLMENT FOUND'

		  ELSE '' END AS CHANGES
	, T1.* 
	,ENR.STUDENT_SCHOOL_YEAR_GU
	--,ENROLL.ENROLLMENT_GU
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from JumpStart.csv'
                ) AS [T1]

	LEFT JOIN
	REV.EPC_STU AS STU
	ON
	T1.[Student's ID] = STU.SIS_NUMBER

	LEFT JOIN 
	APS.StudentEnrollmentDetails AS ENR
	ON
	ENR.STUDENT_GU = STU.STUDENT_GU
	AND ENR.SCHOOL_YEAR = '2017'
	AND ENR.EXTENSION = 'N'
	--AND LEFT(ENR.SCHOOL_NAME,5) != LEFT(T1.[Homeschool Site],5) 


--comment out ENROLL ONCE DELETED

	--INNER JOIN 
	--REV.EPC_STU_ENROLL AS ENROLL
	--ON
	--ENR.STUDENT_SCHOOL_YEAR_GU = ENROLL.STUDENT_SCHOOL_YEAR_GU



	) AS T2

	WHERE 
	T2.CHANGES = 'NOT AT JUMP SCHOOL'

) AS T3

WHERE
T3.STUDENT_SCHOOL_YEAR_GU = rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU


ROLLBACK


	REVERT
GO