BEGIN TRANSACTION 
DELETE rev.EPC_STREET

FROM 
(
SELECT STREETS.* FROM 
rev.EPC_STREET AS STREETS
INNER JOIN
rev.EPC_GRID AS GRIDS
ON
STREETS.GRID_GU = GRIDS.GRID_GU

WHERE
GRID_CODE = '204420530' AND STREETS.SCHOOL_YEAR = '2016'
--ORDER BY STREET_NAME, STREET_LOW_ADDRESS
) AS T1
WHERE
rev.EPC_STREET.STREET_GU = T1.STREET_GU

ROLLBACK 


