
/*
CREATE TABLE PART2LASTEXC
(
 student_gu uniqueidentifier,
 SIS_NUMBER VARCHAR (9),
 SCHOOL_CODE VARCHAR (4),
 CAL_DATE DATE,
 ROTATION VARCHAR (5),
 CLASS_COUNT DECIMAL (5,2)
 )
 */


DECLARE @startDate DATE = '20161202'
DECLARE @endDate DATE = '20170208'

INSERT INTO dbo.PART2LASTEXC
SELECT 

    [stu].[STUDENT_GU]
    ,[stu].[SIS_NUMBER]
    ,class.SCHOOL_CODE
    ,[cal].[CAL_DATE]
    ,[cal].[ROTATION]
    ,COUNT (*) AS [Total Classes]

FROM 
       (
		SELECT 
				BS.COURSE_ENTER_DATE,BS.COURSE_LEAVE_DATE ,BS.TERM_CODE ,BS.SECTION_GU,BS.SECTION_ID
			   ,BS.STUDENT_SCHOOL_YEAR_GU ,BS.COURSE_GU ,BS.SCHOOL_YEAR_COURSE_GU  ,BS.ORGANIZATION_GU
			   ,BS.ORGANIZATION_YEAR_GU,BS.STUDENT_GU,SYMD.MEET_DAY_CODE,SCHOOL_CODE
			   FROM 
				APS.BASICSCHEDULE AS BS
				INNER JOIN
			   [APS].[YearDates] AS [yr] WITH (NOLOCK)  ON   BS.[YEAR_GU]=[yr].[YEAR_GU] 
			   AND ('20160218' BETWEEN [yr].[START_DATE] AND [yr].[END_DATE])
			   AND [yr].EXTENSION = 'R'
			   INNER JOIN rev.EPC_SCH_YR_SECT_MET_DY   sysmd ON sysmd.SECTION_GU      = BS.SECTION_GU
			   INNER JOIN rev.EPC_SCH_YR_MET_DY        symd  ON symd.SCH_YR_MET_DY_GU = sysmd.SCH_YR_MET_DY_GU
			   INNER JOIN  rev.EPC_SCH AS SCH    ON    BS.ORGANIZATION_GU = SCH.ORGANIZATION_GU
			   INNER JOIN  REV.EPC_SCH_YR_OPT AS SETUP	ON	SETUP.ORGANIZATION_YEAR_GU = BS.ORGANIZATION_YEAR_GU

			   WHERE SETUP.SCHOOL_ATT_TYPE IN ('P', 'B')

		)AS Class    
        
    INNER JOIN
    [rev].[EPC_SCH_YR_SECT] AS [Section] WITH (NOLOCK)
    ON
    [Class].[SECTION_GU]=[Section].[SECTION_GU]
    AND CLASS.SCHOOL_YEAR_COURSE_GU = SECTION.SCHOOL_YEAR_COURSE_GU
    AND [Section].[EXCLUDE_ATTENDANCE]='Y'
       

    INNER JOIN
    [rev].[EPC_STU] AS [stu] WITH (NOLOCK)
    ON
    Class.[STUDENT_GU]=[stu].[STUDENT_GU]

    INNER JOIN
    [rev].[EPC_SCH_ATT_CAL] AS [cal] WITH (NOLOCK)
    ON
    Class.[ORGANIZATION_YEAR_GU]=[cal].[SCHOOL_YEAR_GU]
    AND CAL.ROTATION = CLASS.MEET_DAY_CODE
    AND  [cal].[CAL_DATE]>=[Class].[COURSE_ENTER_DATE] 
    AND 
    ([cal].[CAL_DATE]<=[Class].[COURSE_LEAVE_DATE] 
    OR [Class].[COURSE_LEAVE_DATE] IS NULL)


WHERE 
      -- ([cal].[CAL_DATE]>=@startDate AND [cal].[CAL_DATE]<=@endDate)
       CAL.CAL_DATE = '20160218'
       GROUP BY 
            [stu].[STUDENT_GU]
			,[stu].[SIS_NUMBER]
			,class.SCHOOL_CODE
			,[cal].[CAL_DATE]
			,[cal].[ROTATION]
