SELECT School.SCHOOL_CODE, COUNT (*)AS ENROLL_COUNT 
		/*
		School.SCHOOL_CODE,Organization.ORGANIZATION_NAME, Student.SIS_NUMBER, RevYear.SCHOOL_YEAR, Enroll.EXCLUDE_ADA_ADM
		,(CONVERT (VARCHAR (8), Enroll.LEAVE_DATE, 112)) AS LEAVEDATE
		,(CONVERT (VARCHAR (8), Enroll.ENTER_DATE, 112)) AS ENTERDATE
		,StudentSchoolYear.STUDENT_SCHOOL_YEAR_GU
		,Enroll.CHANGE_DATE_TIME_STAMP
		,Enroll.CHANGE_ID_STAMP
		,Enroll.ADD_DATE_TIME_STAMP
		,Enroll.ADD_ID_STAMP
		*/
	FROM
		[011-SYNERGYDB].ST_Production.rev.EPC_STU_SCH_YR AS StudentSchoolYear
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.EPC_STU AS Student
		ON 
		Student.STUDENT_GU = StudentSchoolYear.STUDENT_GU
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.REV_ORGANIZATION_YEAR AS OrgYear 
		ON 
		OrgYear.ORGANIZATION_YEAR_GU = StudentSchoolYear.ORGANIZATION_YEAR_GU
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.REV_ORGANIZATION AS Organization 
		ON 
		Organization.ORGANIZATION_GU=OrgYear.ORGANIZATION_GU
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.EPC_SCH AS School 
		ON 
		School.ORGANIZATION_GU =OrgYear.ORGANIZATION_GU
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.REV_YEAR AS RevYear 
		ON 
		RevYear.YEAR_GU = OrgYear.YEAR_GU 
		AND RevYear.SCHOOL_YEAR = 2013
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.EPC_STU_ENROLL AS Enroll
		ON 
		Enroll.STUDENT_SCHOOL_YEAR_GU = StudentSchoolYear.STUDENT_SCHOOL_YEAR_GU
		
	WHERE
		--NO_SHOW_STUDENT = 'N'
		--AND
		(RevYear.SCHOOL_YEAR = 2013 AND RevYear.EXTENSION = 'S')
		--AND SCHOOL_CODE = '540'

GROUP BY 
	School.SCHOOL_CODE 
ORDER BY School.SCHOOL_CODE


SELECT  COUNT (*)
		/*
		School.SCHOOL_CODE,Organization.ORGANIZATION_NAME, Student.SIS_NUMBER, RevYear.SCHOOL_YEAR, Enroll.EXCLUDE_ADA_ADM
		,(CONVERT (VARCHAR (8), Enroll.LEAVE_DATE, 112)) AS LEAVEDATE
		,(CONVERT (VARCHAR (8), Enroll.ENTER_DATE, 112)) AS ENTERDATE
		,StudentSchoolYear.STUDENT_SCHOOL_YEAR_GU
		,Enroll.CHANGE_DATE_TIME_STAMP
		,Enroll.CHANGE_ID_STAMP
		,Enroll.ADD_DATE_TIME_STAMP
		,Enroll.ADD_ID_STAMP
		*/
	FROM
		[011-SYNERGYDB].ST_Production.rev.EPC_STU_SCH_YR AS StudentSchoolYear
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.EPC_STU AS Student
		ON 
		Student.STUDENT_GU = StudentSchoolYear.STUDENT_GU
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.REV_ORGANIZATION_YEAR AS OrgYear 
		ON 
		OrgYear.ORGANIZATION_YEAR_GU = StudentSchoolYear.ORGANIZATION_YEAR_GU
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.REV_ORGANIZATION AS Organization 
		ON 
		Organization.ORGANIZATION_GU=OrgYear.ORGANIZATION_GU
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.EPC_SCH AS School 
		ON 
		School.ORGANIZATION_GU =OrgYear.ORGANIZATION_GU
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.REV_YEAR AS RevYear 
		ON 
		RevYear.YEAR_GU = OrgYear.YEAR_GU 
		AND RevYear.SCHOOL_YEAR = 2013
		INNER JOIN 
		[011-SYNERGYDB].ST_Production.rev.EPC_STU_ENROLL AS Enroll
		ON 
		Enroll.STUDENT_SCHOOL_YEAR_GU = StudentSchoolYear.STUDENT_SCHOOL_YEAR_GU
		
	WHERE
		--NO_SHOW_STUDENT = 'N'
		--AND
		(RevYear.SCHOOL_YEAR = 2013 AND RevYear.EXTENSION = 'S')
		--AND SCHOOL_CODE = '540'
