

SELECT ORGANIZATION_NAME, COURSE_ID, COURSE_TITLE, COUNT(*) AS UNIQUE_STUDENT_COUNT_BY_COURSE
FROM(
SELECT DISTINCT ORGANIZATION_NAME, COURSE_ID, COURSE_TITLE, SIS_NUMBER
FROM (

SELECT 
	
	SCH.ORGANIZATION_NAME
	,SCH.SIS_NUMBER, PERS.LAST_NAME, PERS.FIRST_NAME, PERS.MIDDLE_NAME, SCH.COURSE_ID, SCH.SECTION_ID, SCH.COURSE_TITLE, SCH.TERM_CODE, GRP.[GROUP]

 FROM 
APS.ScheduleDetailsAsOf('20180523') AS SCH
INNER JOIN 
REV.UD_CRS_GROUP AS GRP
ON
SCH.COURSE_GU = GRP.COURSE_GU
INNER JOIN 
REV.REV_PERSON AS PERS
ON
SCH.STUDENT_GU = PERS.PERSON_GU


WHERE
[GROUP] LIKE 'ETHNIC%'
order by ORGANIZATION_NAME

) AS T1

) AS T2
GROUP BY 
ORGANIZATION_NAME,COURSE_ID, COURSE_TITLE
ORDER BY ORGANIZATION_NAME