
BEGIN TRANSACTION

UPDATE REV.REV_USER
SET EXEMPT_FROM_LDAP = 'Y' , DISABLED = CSVFILE.DISABLED

FROM 
REV.REV_USER

INNER JOIN
OPENROWSET ('MSDASQL', 'Driver={Microsoft Access Text Driver (*.txt, *.csv)};DBQ=D:\SQLWorkingFiles;', 'SELECT * from "EXEMPTUSERS.csv"')
AS CSVFILE

ON
CSVFILE.USER_GU = REV_USER.USER_GU

ROLLBACK

