
SELECT * FROM 
(
SELECT SIS_NUMBER, ELL2.PROGRAM_CODE, ELL2.ENTRY_DATE, ELL2.EXIT_DATE, ELL2.EXIT_REASON, 
ROW_NUMBER() OVER (PARTITION BY SIS_NUMBER ORDER BY ELL2.EXIT_DATE DESC) AS RN 

FROM 

(
SELECT DISTINCT SIS_NUMBER, STUDENT_GU FROM
(
SELECT 
	PROGRAM_CODE, ENTRY_DATE, EXIT_DATE, EXIT_REASON, SIS_NUMBER, ELL.STUDENT_GU,
	ROW_NUMBER() OVER (PARTITION BY SIS_NUMBER ORDER BY EXIT_DATE DESC) AS RN
 FROM
	rev.EPC_STU_PGM_ELL_HIS AS ELL
	INNER JOIN
	rev.EPC_STU AS STU
	ON
	ELL.STUDENT_GU = STU.STUDENT_GU

)
AS MORETHANONE

WHERE
	RN > 1
) AS GETONE

INNER JOIN 
rev.EPC_STU_PGM_ELL_HIS AS ELL2
ON
GETONE.STUDENT_GU= ELL2.STUDENT_GU

) AS BADEXITS

--WHERE
	--RN = 1 AND EXIT_REASON = 'EY1'

ORDER BY SIS_NUMBER, EXIT_REASON DESC

