
EXECUTE AS LOGIN='QueryFileUser'
GO

BEGIN TRANSACTION
UPDATE rev.EPC_STU_PGM_ELL_HIS
SET ENTRY_DATE = CAREER.ENTRY_DATE, EXIT_DATE = CAREER.EXIT_DATE, EXIT_REASON = CAREER.EXIT_REASON

--SELECT 
	--CAREER.*, ELLHIS.*

 FROM
             OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT * from EXITYEARTOFIX.csv'
                ) AS [CAREER]

INNER JOIN 
rev.EPC_STU AS STU

ON
[CAREER].SIS_NUMBER = STU.SIS_NUMBER


INNER JOIN
rev.EPC_STU_PGM_ELL_HIS AS ELLHIS
ON
ELLHIS.STUDENT_GU = STU.STUDENT_GU
AND 
CAREER.ENTRY_DATE != ELLHIS.ENTRY_DATE
AND 
CAREER.EXIT_DATE != ELLHIS.EXIT_DATE
AND 
CAREER.EXIT_REASON != ELLHIS.EXIT_REASON

AND CAREER.RN = 1


WHERE
	STU_PGM_ELL_HIS_GU = ELLHIS.STU_PGM_ELL_HIS_GU

COMMIT

      REVERT
GO