
EXECUTE AS LOGIN='QueryFileUser'
GO

BEGIN TRANSACTION

UPDATE REV.EPC_STU_SCH_YR 
	SET GRADE = NEW_GRADE	
		,CHANGE_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F'
		,CHANGE_DATE_TIME_STAMP = GETDATE()

FROM 
(
SELECT 
	
		PRIM.STUDENT_SCHOOL_YEAR_GU
		,T1.SIS_NUMBER
		,PRIM.GRADE
		
		,CASE WHEN T1.GRADE = '09'  THEN 190
				 WHEN T1.GRADE = '10' THEN 200
				 ELSE ''END AS NEW_GRADE 
		
	
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from Reclassify.csv'
                ) AS [T1]

	INNER JOIN 
	rev.EPC_STU AS STU
	ON
	T1.SIS_NUMBER = STU.SIS_NUMBER 

	INNER JOIN 
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS PRIM
	ON
	STU.STUDENT_GU = PRIM.STUDENT_GU 

WHERE
	T1.GRADE = '09' AND T1.EXPECTED_GRADUATION_YEAR = '2020'
	OR 
	T1.GRADE = '10' AND T1.EXPECTED_GRADUATION_YEAR = '2019'
	OR
	T1.GRADE = '11' AND T1.EXPECTED_GRADUATION_YEAR = '2018'
	OR 
	T1.GRADE = '12' AND T1.EXPECTED_GRADUATION_YEAR = '2017'

) AS UPGRADEME

WHERE
rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU = UPGRADEME.STUDENT_SCHOOL_YEAR_GU

COMMIT
	
REVERT
GO