

SELECT * FROM 
(
SELECT * FROM (

SELECT 
	ROW_NUMBER() OVER (PARTITION BY LOGIN_NAME ORDER BY LOGIN_NAME DESC) AS RN
	,LOGIN_NAME
	,STF.[TYPE]
	,USERGROUP_NAME
	,ORGANIZATION_NAME
	,CASE 
		WHEN USERGROUP_NAME LIKE '%FAMILY SCHOOL%' AND ORGANIZATION_NAME LIKE '%FAMILY SCHOOL%' THEN 1
		WHEN USERGROUP_NAME LIKE '%EUBANK%' AND ORGANIZATION_NAME LIKE '%EUBANK%' THEN 1
	
	ELSE 0 END AS KEEP_ME
	
	,USR.USER_GU,
	FOCUS_YEAR_GU
	,YEAR_GU
	
	--,usrgrp.*
 FROM 
REV.REV_USER AS USR
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
USR.FOCUS_ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN 
REV.REV_YEAR AS YRS
ON
YRS.YEAR_GU = USR.FOCUS_YEAR_GU
AND YRS.SCHOOL_YEAR = '2016'

LEFT JOIN 
rev.REV_USER_USERGROUP AS USRGRP
ON
USR.USER_GU = USRGRP.USER_GU
INNER JOIN 
REV.REV_USERGROUP AS USRG
ON
USRG.USERGROUP_GU = USRGRP.USERGROUP_GU
AND USERGROUP_NAME LIKE 'UPDATE%'
AND USERGROUP_NAME NOT LIKE '%District%'
AND USERGROUP_NAME NOT LIKE '%Special Education%'
AND USERGROUP_NAME NOT LIKE '%TEP%'
AND USERGROUP_NAME NOT LIKE '%Transition%'
AND USERGROUP_NAME NOT LIKE '%Interim%'
AND USERGROUP_NAME NOT LIKE '%Summer%'
AND USERGROUP_NAME NOT LIKE '%Homebound%'
AND USERGROUP_NAME NOT LIKE '%Child Find%'
AND USERGROUP_NAME NOT LIKE '%Continuation%'

INNER JOIN 
rev.EPC_STAFF AS STF
ON
STF.STAFF_GU = USR.USER_GU

WHERE 
SUBSTRING(USERGROUP_NAME,10,3) != SUBSTRING(ORGANIZATION_NAME,1,3)

) AS T1

WHERE
KEEP_ME = 0
) AS T3

LEFT JOIN 
(SELECT * FROM (

SELECT 
	ROW_NUMBER() OVER (PARTITION BY LOGIN_NAME ORDER BY LOGIN_NAME DESC) AS RN
	,LOGIN_NAME
	,STF.[TYPE]
	,USERGROUP_NAME
	,ORGANIZATION_NAME
	,CASE 
		WHEN USERGROUP_NAME LIKE '%FAMILY SCHOOL%' AND ORGANIZATION_NAME LIKE '%FAMILY SCHOOL%' THEN 1
		WHEN USERGROUP_NAME LIKE '%EUBANK%' AND ORGANIZATION_NAME LIKE '%EUBANK%' THEN 1
	
	ELSE 0 END AS KEEP_ME
	
	,USR.USER_GU,
	FOCUS_YEAR_GU
	,YEAR_GU
	
	--,usrgrp.*
 FROM 
REV.REV_USER AS USR
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
USR.FOCUS_ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN 
REV.REV_YEAR AS YRS
ON
YRS.YEAR_GU = USR.FOCUS_YEAR_GU
AND YRS.SCHOOL_YEAR = '2016'

LEFT JOIN 
rev.REV_USER_USERGROUP AS USRGRP
ON
USR.USER_GU = USRGRP.USER_GU
INNER JOIN 
REV.REV_USERGROUP AS USRG
ON
USRG.USERGROUP_GU = USRGRP.USERGROUP_GU
AND USERGROUP_NAME LIKE 'UPDATE%'
AND USERGROUP_NAME NOT LIKE '%District%'
AND USERGROUP_NAME NOT LIKE '%Special Education%'
AND USERGROUP_NAME NOT LIKE '%TEP%'
AND USERGROUP_NAME NOT LIKE '%Transition%'
AND USERGROUP_NAME NOT LIKE '%Interim%'
AND USERGROUP_NAME NOT LIKE '%Summer%'
AND USERGROUP_NAME NOT LIKE '%Homebound%'
AND USERGROUP_NAME NOT LIKE '%Child Find%'
AND USERGROUP_NAME NOT LIKE '%Continuation%'

INNER JOIN 
rev.EPC_STAFF AS STF
ON
STF.STAFF_GU = USR.USER_GU

WHERE 
SUBSTRING(USERGROUP_NAME,10,3) != SUBSTRING(ORGANIZATION_NAME,1,3)

) AS T1

WHERE
KEEP_ME = 0
AND RN > 1
) AS T4

ON
T3.LOGIN_NAME = T4.LOGIN_NAME

WHERE
T4.LOGIN_NAME IS NULL

ORDER BY T3.LOGIN_NAME