
BEGIN TRAN
UPDATE REV.REV_ANNOUNCEMENT
SET HTML_ANNOUNCEMENT = REPLACE(CAST(HTML_ANNOUNCEMENT AS NVARCHAR(MAX)),'&nbsp', '')

WHERE REV_ANNOUNCEMENT_GU = 'C40B011D-80A3-43A1-B1EE-8677B529C8AA'
COMMIT

SELECT ANNOUNCEMENT, HTML_ANNOUNCEMENT
--,REPLACE(
,REPLACE(CAST(HTML_ANNOUNCEMENT AS NVARCHAR(MAX)),'&nbsp', '')
,REV_ANNOUNCEMENT_GU
 FROM 
REV.REV_ANNOUNCEMENT
ORDER BY DISPLAY_DATE DESC

