
EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT 
	 T1.*
	,ENR.SIS_NUMBER,PERS.LAST_NAME, PERS.FIRST_NAME, PERS.BIRTH_DATE
	,ENR.SCHOOL_NAME
	,ENR.SCHOOL_CODE
	,ENR.GRADE
	,ENR.ENTER_DATE
	,ENR.LEAVE_DATE
	,CASE WHEN PHL.DATE_ASSIGNED IS NOT NULL THEN 'Y' ELSE 'N' END AS PhloteStatus
	,BS.HOME_LANGUAGE
	
	--SMAX
	,MEM12.MEMBERDAYS AS [Member Days 2011-2012]
	,ATT12.[TOTAL_ABSENCE_DAYS] AS [Attendance_2011-2012_Total_Exc_Unex]
	
	,MEM13.MEMBERDAYS AS [Member Days 2012-2013]
	,ATT13.[TOTAL_ABSENCE_DAYS] AS [Attendance_2012-2013_Total_Exc_Unex]

	,MEM14.MEMBERDAYS AS [Member Days 2013-2014]
	,ATT14.[TOTAL_ABSENCE_DAYS] AS [Attendance_2013-2014_Total_Exc_Unex]
	
	--SYNERGY		
	,MEMDAYS.MEMBER_DAYS AS [Member Days 2014-2015]
	,ATT2014.[Total_Exc_Unex] AS [Attendance_2014-2015_Total_Exc_Unex]
	
	,MEMDAYS2.MEMBER_DAYS AS [Member Days 2015-2016]
	,ATT2015.[Total_Exc_Unex] AS [Attendance_2015-2016_Total_Exc_Unex]


	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from Horizons.csv'
                ) AS [T1]
	
LEFT JOIN 
REV.REV_PERSON AS PERS
ON
T1.[Student Last Name] = PERS.LAST_NAME
AND T1.[Student First Name] = PERS.FIRST_NAME
AND T1.[Birth date] = PERS.BIRTH_DATE

LEFT JOIN 
APS.PHLOTEAsOf(GETDATE()) AS PHL
ON
PERS.PERSON_GU = PHL.STUDENT_GU

LEFT JOIN 
APS.StudentEnrollmentDetails AS ENR
ON
ENR.STUDENT_GU = PERS.PERSON_GU

LEFT JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
BS.STUDENT_GU = PERS.PERSON_GU

LEFT JOIN 
STUDENT_SCHOOL_MEMBERDAYS_2014 AS MEMDAYS
ON
MEMDAYS.STUID = BS.SIS_NUMBER
AND MEMDAYS.SCHOOL_CODE = ENR.SCHOOL_CODE
AND ENR.ORGANIZATION_YEAR_GU = MEMDAYS.org_year_gu

LEFT JOIN 
STUDENT_ATTENDANCE_2014 AS ATT2014
ON
ATT2014.[SIS Number] = ENR.SIS_NUMBER
AND ATT2014.[School Code] = ENR.SCHOOL_CODE
AND ATT2014.[Grade] = ENR.GRADE

LEFT JOIN 
STUDENT_SCHOOL_MEMBERDAYS_2015 AS MEMDAYS2
ON
MEMDAYS2.STUID = BS.SIS_NUMBER
AND MEMDAYS2.SCHOOL_CODE = ENR.SCHOOL_CODE
AND ENR.ORGANIZATION_YEAR_GU = MEMDAYS2.org_year_gu

LEFT JOIN 
STUDENT_ATTENDANCE_2015 AS ATT2015
ON
ATT2015.[SIS Number] = ENR.SIS_NUMBER
AND ATT2015.[School Code] = ENR.SCHOOL_CODE
AND ATT2015.[Grade] = ENR.GRADE

LEFT JOIN 
[180-SMAXODS-01.APS.EDU.ACTD].[PR].dbo.ATTENDANCE_2012 AS ATT12
ON
ENR.SIS_NUMBER = ATT12.IDNBR collate database_default
AND ATT12.SCHNBR = ENR.SCHOOL_CODE  collate database_default
AND ATT12.SCHYR = ENR.SCHOOL_YEAR +1 

LEFT JOIN 
[180-SMAXODS-01.APS.EDU.ACTD].[PR].dbo.MEMBERDAYS_2012 AS MEM12
ON 
ENR.SIS_NUMBER = MEM12.IDNBR collate database_default
AND MEM12.SCHNBR = ENR.SCHOOL_CODE  collate database_default
AND MEM12.SCHYR = ENR.SCHOOL_YEAR +1 
AND MEM12.GRADE = ENR.GRADE collate database_default


LEFT JOIN 
[180-SMAXODS-01.APS.EDU.ACTD].[PR].dbo.ATTENDANCE_2013 AS ATT13
ON
ENR.SIS_NUMBER = ATT13.IDNBR collate database_default
AND ATT13.SCHNBR = ENR.SCHOOL_CODE  collate database_default
AND ATT13.SCHYR = ENR.SCHOOL_YEAR +1 

LEFT JOIN 
[180-SMAXODS-01.APS.EDU.ACTD].[PR].dbo.MEMBERDAYS_2013 AS MEM13
ON 
ENR.SIS_NUMBER = MEM13.IDNBR collate database_default
AND MEM13.SCHNBR = ENR.SCHOOL_CODE  collate database_default
AND MEM13.SCHYR = ENR.SCHOOL_YEAR +1 
AND MEM13.GRADE = ENR.GRADE collate database_default

LEFT JOIN 
[180-SMAXODS-01.APS.EDU.ACTD].[PR].dbo.ATTENDANCE_2014 AS ATT14
ON
ENR.SIS_NUMBER = ATT14.IDNBR collate database_default
AND ATT14.SCHNBR = ENR.SCHOOL_CODE  collate database_default
AND ATT14.SCHYR = ENR.SCHOOL_YEAR +1 

LEFT JOIN 
[180-SMAXODS-01.APS.EDU.ACTD].[PR].dbo.MEMBERDAYS_2014 AS MEM14
ON 
ENR.SIS_NUMBER = MEM14.IDNBR collate database_default
AND MEM14.SCHNBR = ENR.SCHOOL_CODE  collate database_default
AND MEM14.SCHYR = ENR.SCHOOL_YEAR +1 
AND MEM14.GRADE = ENR.GRADE collate database_default


ORDER BY PERS.LAST_NAME, ENR.ENTER_DATE


REVERT
GO