


SELECT 
	EMPLOYEE.LAST_NAME
	,EMPLOYEE.FIRST_NAME
	,LAWSON.*
	,CASE WHEN T1.USERGROUP LIKE 'UPDATE%'  OR T1.USERGROUP = 'SynDailyTeacherAttendance' THEN 'HAS UPDATE SCHOOL OR DAILY ATTEND' 
	ELSE 'NOT IN SECURITY OVERRIDE' END AS MSG

 FROM 

(SELECT * FROM 

Paemppos
WHERE 
USER_LEVEL = '0022'
AND END_DATE IS NULL
AND (POSITION LIKE '%A TCHIA%'
	OR POSITION LIKE '%A TCHIM%')
) AS LAWSON

LEFT HASH JOIN
(
SELECT SUBSTRING(T3.BADGE_NUMBER,2,6) AS BADGE, T3.USERGROUP

FROM 


(
	SELECT * FROM 
	APS.SynergyGroupPull
	WHERE
	(USERGROUP LIKE 'UPDATE%'  
	OR USERGROUP = 'SynDailyTeacherAttendance')
	) AS T2

	INNER HASH JOIN

	(SELECT * FROM 
	APS.SynergyGroupPull
	WHERE
	ISNUMERIC(SUBSTRING(BADGE_NUMBER,2,1)) = 1
	) AS T3

ON
T2.BADGE_NUMBER = T3.BADGE_NUMBER
AND T2.USERGROUP = T3.USERGROUP

) AS T1


ON
LAWSON.EMPLOYEE = T1.BADGE


INNER JOIN
Employee
ON
EMPLOYEE.EMPLOYEE = LAWSON.EMPLOYEE


