USE ST_Production
GO

SELECT 
	SIS_NUMBER
	,STATE_STUDENT_NUMBER
	,Students.CHANGE_DATE_TIME_STAMP
	,LAST_NAME
	,FIRST_NAME

	 FROM
rev.EPC_STU AS Students
INNER JOIN
rev.REV_PERSON AS PERSON
ON
Students.STUDENT_GU = PERSON.PERSON_GU

WHERE
LEN(SIS_NUMBER) > 9
OR
LEN (STATE_STUDENT_NUMBER) > 9 

OR
LEN(STATE_STUDENT_NUMBER) < 9