
EXECUTE AS LOGIN='QueryFileUser'
GO

BEGIN TRANSACTION

INSERT rev.UD_CRS_GROUP

SELECT 
NEWID() AS UDCRS_GROUP_GU
,GETDATE() AS ADD_DATE_TIME_STAMP
,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS ADD_ID_STAMP
,NULL AS CHANGE_DATE_TIME_STAMP
,NULL AS CHANGE_ID_STAMP
,T3.COURSE_GU AS COURSE_GU
,[Group Name2] AS [GROUP]
,[GROUP] AS [CODE]

/*
UPDATE rev.UD_CRS_GROUP 
SET [GROUP] = T3.[Group Name]
*/
FROM
(
SELECT 
	T1.*, T2.*
	
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from CourseGroups.csv'
                ) AS [T1]
INNER JOIN 
(
SELECT COURSE_ID AS COURSE, CRS.COURSE_GU 
--,[GROUP] AS GROUPS, GRP.UDCRS_GROUP_GU 
--FROM 
--rev.UD_CRS_GROUP AS GRP
--INNER JOIN 
FROM
rev.EPC_CRS AS CRS
--ON
--GRP.COURSE_GU = CRS.COURSE_GU
) AS T2
ON
T1.COURSE_ID = T2.COURSE
--AND CAST(T1.[GROUP] AS VARCHAR) = T2.[GROUPS]
WHERE
	[Group Name2] IS NOT NULL

) AS T3

--WHERE
--T3.UDCRS_GROUP_GU = rev.UD_CRS_GROUP.UDCRS_GROUP_GU

--SELECT * FROM 
--rev.UD_CRS_GROUP


COMMIT

	
REVERT
GO