
SELECT DISTINCT
	T1.SIS_NUMBER, T1.LAST_NAME, T1.FIRST_NAME, T1.GRADE, T1.SPED_STATUS, T1.ELL_STATUS
	,SCH2.ORGANIZATION_NAME, SCH2.COURSE_ID, SCH2.SECTION_ID, SCH2.COURSE_TITLE, TERM_CODE, I AS [Intervention]
 FROM 
(
SELECT DISTINCT 
	BS.SIS_NUMBER, BS.LAST_NAME, BS.FIRST_NAME, PRIM.SCHOOL_CODE, PRIM.SCHOOL_NAME, PRIM.EXCLUDE_ADA_ADM, PRIM.GRADE
	,BS.SPED_STATUS, BS.ELL_STATUS
	,BS.STUDENT_GU
FROM 
 APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS PRIM
 INNER JOIN 
 APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
 ON
 PRIM.STUDENT_GU = SCH.STUDENT_GU
 INNER JOIN
(
SELECT * FROM 
(
SELECT
       [COURSE_GU]
       ,[COURSE_LEVEL]
FROM
       rev.EPC_CRS_LEVEL_LST 
) [LIST]
             PIVOT (MIN([COURSE_LEVEL]) FOR [COURSE_LEVEL] IN ([N],[H],[A],[D],[L],[G],[GFT],[C],[I]) ) AS [LIST_PIVOT]
       
)AS [COURSE_LIST]

ON
[COURSE_LIST].COURSE_GU = SCH.COURSE_GU
AND COURSE_LIST.I = 'I'
 INNER JOIN
APS.BasicStudentWithMoreInfo AS BS
ON
PRIM.[STUDENT_GU] = BS.[STUDENT_GU]
) AS T1

INNER JOIN 
APS.ScheduleDetailsAsOf(GETDATE()) AS SCH2
ON
T1.STUDENT_GU = SCH2.STUDENT_GU
LEFT JOIN
(
SELECT * FROM 
(
SELECT
       [COURSE_GU]
       ,[COURSE_LEVEL]
FROM
       rev.EPC_CRS_LEVEL_LST 
) [LIST]
             PIVOT (MIN([COURSE_LEVEL]) FOR [COURSE_LEVEL] IN ([N],[H],[A],[D],[L],[G],[GFT],[C],[I]) ) AS [LIST_PIVOT]
       
)AS [COURSE_LIST]

ON
[COURSE_LIST].COURSE_GU = SCH2.COURSE_GU




ORDER BY SIS_NUMBER