
SELECT DISTINCT 
	ALLTAGSALLSTAFF.ORGANIZATION_NAME
			,ALLTAGSALLSTAFF.COURSE_ID
			,ALLTAGSALLSTAFF.SECTION_ID
			,ALLTAGSALLSTAFF.BADGE_NUM
			,ALLTAGSALLSTAFF.ADD_STAFF
		--COMMENT THIS OUT FOR UNIQUE SCH, CRS, SEC, BADGE
			,ALLTAGSALLSTAFF.TAG

FROM (

 		SELECT 	
			ORGANIZATION_NAME
			,CRS.COURSE_ID
			,	SEC.SECTION_ID
			, TAGS.TAG
			,STAFF.BADGE_NUM
			,SCHTYP.SCHOOL_TYPE	
			,0 AS ADD_STAFF

			--FOR ELEMENTARY GRADE K-5, AN ELEMENTARY CREDENTIAL IS REQUIRED
			--FOR MIDDLE, EITHER AN ELEMENTARY OR SECONDARY APPLIES
			--FOR HIGH SCHOOL, ONLY SECONDARY APPLIES
			,CASE 
					WHEN SCHTYP.SCHOOL_TYPE = 1 THEN Creds.ElementaryTESOL 
					WHEN SCHTYP. SCHOOL_TYPE = 2 AND (Creds.ElementaryTESOL = 1 OR Creds.SecondaryTESOL = 1) THEN 1
					WHEN SCHTYP.SCHOOL_TYPE IN (3,4) THEN Creds.SecondaryTESOL 
					ELSE 0
			END 
			 AS TeacherTESOL

			 ,CASE 
					WHEN SCHTYP.SCHOOL_TYPE = 1 THEN Creds.ElementaryBilingual 
					WHEN SCHTYP.SCHOOL_TYPE= 2 AND (Creds.ElementaryBilingual = 1 OR Creds.SecondaryBilingual = 1) THEN 1
					WHEN SCHTYP.SCHOOL_TYPE  IN (3,4) THEN Creds.SecondaryBilingual 
					ELSE 0
				END 
				AS TeacherBilingual

			,CASE 
					WHEN SCHTYP.SCHOOL_TYPE  = 1 THEN Creds.ElementaryESL 
					WHEN SCHTYP.SCHOOL_TYPE= 2 AND (Creds.ElementaryESL = 1 OR Creds.SecondaryESL = 1) THEN 1
					WHEN SCHTYP.SCHOOL_TYPE  IN (3,4)THEN Creds.SecondaryESL 
					ELSE 0
				END 
				AS TeacherESL
			,Creds.Navajo AS TeacherNavajo
			,CASE 
					WHEN SCHTYP.SCHOOL_TYPE  = 1 THEN Creds.ElementaryBilingualWaiverOnly
					WHEN SCHTYP.SCHOOL_TYPE = 2 AND (Creds.ElementaryBilingualWaiverOnly = 1 OR Creds.SecondaryBilingualWaiverOnly = 1) THEN 1
					WHEN SCHTYP.SCHOOL_TYPE  IN (3,4) THEN Creds.SecondaryBilingualWaiverOnly 
					ELSE 0
			END 
			AS TeacherBilingualWaiverOnly

			,CASE 
					WHEN SCHTYP.SCHOOL_TYPE  = 1 THEN Creds.ElementaryTESOLWaiverOnly 
					WHEN SCHTYP.SCHOOL_TYPE = 2 AND (Creds.ElementaryTESOLWaiverOnly = 1 OR Creds.SecondaryTESOLWaiverOnly= 1) THEN 1
					WHEN SCHTYP.SCHOOL_TYPE  IN (3,4) THEN Creds.SecondaryTESOLWaiverOnly 
					ELSE 0
			END 
			AS TeacherTESOLWaiverOnly


	 FROM
		rev.UD_SECTION_TAG AS TAGS
		INNER JOIN
		rev.EPC_SCH_YR_SECT AS SEC
		ON
		TAGS.SECTION_GU = SEC.SECTION_GU
	
		INNER JOIN
		rev.EPC_SCH_YR_CRS AS CRSYR
		ON
		SEC.SCHOOL_YEAR_COURSE_GU = CRSYR.SCHOOL_YEAR_COURSE_GU
	
		INNER JOIN
		rev.EPC_CRS AS CRS
		ON
		CRSYR.COURSE_GU = CRS.COURSE_GU

		INNER JOIN
		rev.EPC_SCH_YR_SECT AS SECYR
		ON
		SECYR.ORGANIZATION_YEAR_GU = CRSYR.ORGANIZATION_YEAR_GU
		AND 
		SECYR.SECTION_GU = SEC.SECTION_GU

		INNER JOIN
		rev.EPC_STAFF_SCH_YR AS STAFFYR
		ON
		STAFFYR.STAFF_SCHOOL_YEAR_GU = SECYR.STAFF_SCHOOL_YEAR_GU
	
		INNER JOIN
		rev.EPC_STAFF AS STAFF
		ON
		STAFFYR.STAFF_GU = STAFF.STAFF_GU
	
		INNER JOIN
		rev.EPC_SCH_YR_OPT AS SCHTYP
		ON
		SCHTYP.ORGANIZATION_YEAR_GU = SECYR.ORGANIZATION_YEAR_GU

		INNER JOIN
		APS.LCETeacherEndorsementsAsOf(GETDATE()) AS Creds
		ON
		Creds.STAFF_GU = STAFF.STAFF_GU

		INNER JOIN
		rev.REV_ORGANIZATION_YEAR AS ORGYR
		ON
		ORGYR.ORGANIZATION_YEAR_GU = CRSYR.ORGANIZATION_YEAR_GU

		INNER JOIN
		rev.REV_ORGANIZATION AS ORG
		ON
		ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU


	/**********************************************************************************************************************************************************************
	GET ADDITIONAL STAFF - same logic as above except different table for additional staff
	***********************************************************************************************************************************************************************/
	UNION
	
	SELECT 	
	
		ORGANIZATION_NAME
		,CRS.COURSE_ID
		,	SEC.SECTION_ID
		, TAGS.TAG
		,STAFF2.BADGE_NUM
		,SCHTYP.SCHOOL_TYPE	
		,1 AS ADD_STAFF

		--FOR ELEMENTARY GRADE K-5, AN ELEMENTARY CREDENTIAL IS REQUIRED
		--FOR MIDDLE, EITHER AN ELEMENTARY OR SECONDARY APPLIES
		--FOR HIGH SCHOOL, ONLY SECONDARY APPLIES
		,CASE 
				WHEN SCHTYP.SCHOOL_TYPE = 1 THEN Creds.ElementaryTESOL 
				WHEN SCHTYP. SCHOOL_TYPE = 2 AND (Creds.ElementaryTESOL = 1 OR Creds.SecondaryTESOL = 1) THEN 1
				WHEN SCHTYP.SCHOOL_TYPE IN (3,4) THEN Creds.SecondaryTESOL 
				ELSE 0
		END 
		 AS TeacherTESOL

		 ,CASE 
				WHEN SCHTYP.SCHOOL_TYPE = 1 THEN Creds.ElementaryBilingual 
				WHEN SCHTYP.SCHOOL_TYPE= 2 AND (Creds.ElementaryBilingual = 1 OR Creds.SecondaryBilingual = 1) THEN 1
				WHEN SCHTYP.SCHOOL_TYPE  IN (3,4) THEN Creds.SecondaryBilingual 
				ELSE 0
			END 
			AS TeacherBilingual

		,CASE 
				WHEN SCHTYP.SCHOOL_TYPE  = 1 THEN Creds.ElementaryESL 
				WHEN SCHTYP.SCHOOL_TYPE= 2 AND (Creds.ElementaryESL = 1 OR Creds.SecondaryESL = 1) THEN 1
				WHEN SCHTYP.SCHOOL_TYPE  IN (3,4)THEN Creds.SecondaryESL 
				ELSE 0
			END 
			AS TeacherESL


		,Creds.Navajo AS TeacherNavajo

			,CASE 
				WHEN SCHTYP.SCHOOL_TYPE  = 1 THEN Creds.ElementaryBilingualWaiverOnly
				WHEN SCHTYP.SCHOOL_TYPE = 2 AND (Creds.ElementaryBilingualWaiverOnly = 1 OR Creds.SecondaryBilingualWaiverOnly = 1) THEN 1
				WHEN SCHTYP.SCHOOL_TYPE  IN (3,4) THEN Creds.SecondaryBilingualWaiverOnly 
				ELSE 0
			END 
			AS TeacherBilingualWaiverOnly

			,CASE 
				WHEN SCHTYP.SCHOOL_TYPE  = 1 THEN Creds.ElementaryTESOLWaiverOnly 
				WHEN SCHTYP.SCHOOL_TYPE = 2 AND (Creds.ElementaryTESOLWaiverOnly = 1 OR Creds.SecondaryTESOLWaiverOnly= 1) THEN 1
				WHEN SCHTYP.SCHOOL_TYPE  IN (3,4) THEN Creds.SecondaryTESOLWaiverOnly 
				ELSE 0
			END 
			AS TeacherTESOLWaiverOnly
		
	FROM
	rev.UD_SECTION_TAG AS TAGS
	INNER JOIN
	rev.EPC_SCH_YR_SECT AS SEC
	ON
	TAGS.SECTION_GU = SEC.SECTION_GU
	
	INNER JOIN
	rev.EPC_SCH_YR_CRS AS CRSYR
	ON
	SEC.SCHOOL_YEAR_COURSE_GU = CRSYR.SCHOOL_YEAR_COURSE_GU
	
	INNER JOIN
	rev.EPC_CRS AS CRS
	ON
	CRSYR.COURSE_GU = CRS.COURSE_GU

	INNER JOIN
	rev.EPC_SCH_YR_SECT AS SECYR
	ON
	SECYR.ORGANIZATION_YEAR_GU = CRSYR.ORGANIZATION_YEAR_GU
	AND 
	SECYR.SECTION_GU = SEC.SECTION_GU
	
	INNER JOIN
	rev.EPC_SCH_YR_SECT_STF AS ADDSTAFF
	ON
	ADDSTAFF.SECTION_GU = SEC.SECTION_GU

	INNER JOIN
	rev.EPC_STAFF_SCH_YR AS STAFFYR2
	ON
	STAFFYR2.STAFF_SCHOOL_YEAR_GU = ADDSTAFF.STAFF_SCHOOL_YEAR_GU

	INNER JOIN
	rev.EPC_STAFF AS STAFF2
	ON
	STAFF2.STAFF_GU = STAFFYR2.STAFF_GU
	
	
	INNER JOIN
	rev.EPC_SCH_YR_OPT AS SCHTYP
	ON
	SCHTYP.ORGANIZATION_YEAR_GU = SECYR.ORGANIZATION_YEAR_GU

	INNER JOIN
	APS.LCETeacherEndorsementsAsOf(GETDATE()) AS Creds
	ON
	Creds.STAFF_GU = STAFF2.STAFF_GU

	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	ORGYR.ORGANIZATION_YEAR_GU = CRSYR.ORGANIZATION_YEAR_GU

	INNER JOIN
	rev.REV_ORGANIZATION AS ORG
	ON
	ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

	) AS ALLTAGSALLSTAFF

	LEFT JOIN
	APS.LCEClassesUniqueDetailAsOf (GETDATE()) AS LCEDETAILS
	ON
	LCEDETAILS.ORGANIZATION_NAME = ALLTAGSALLSTAFF.ORGANIZATION_NAME
	AND 
	LCEDETAILS.COURSE_ID = ALLTAGSALLSTAFF.COURSE_ID
	AND 
	LCEDETAILS.SECTION_ID = ALLTAGSALLSTAFF.SECTION_ID
	AND
	LCEDETAILS.BADGE_NUM = ALLTAGSALLSTAFF.BADGE_NUM

	WHERE

	LCEDETAILS.BADGE_NUM IS NULL



	ORDER BY ALLTAGSALLSTAFF.ORGANIZATION_NAME, ALLTAGSALLSTAFF.COURSE_ID, ALLTAGSALLSTAFF.SECTION_ID, ALLTAGSALLSTAFF.ADD_STAFF