
SELECT SIS_NUMBER, ELL.EXIT_DATE, ELL.EXIT_REASON FROM 
rev.EPC_STU_PGM_ELL AS ELL
INNER JOIN
rev.EPC_STU AS STU
ON
ELL.STUDENT_GU = STU.STUDENT_GU

WHERE
EXIT_DATE IS NULL AND EXIT_REASON IS NOT NULL