
SELECT 
	ORGANIZATION_NAME AS SCHOOL_NAME
	,SIS_NUMBER
	,VALUE_DESCRIPTION AS GRADE
	
FROM 
	APS.ELLAsOf(GETDATE()) AS ELL
	INNER JOIN
	APS.PrimaryEnrollmentsAsOf(GETDATE()) AS PRIM
	ON
	ELL.STUDENT_GU = PRIM.STUDENT_GU
	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	PRIM.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
	INNER JOIN
	rev.REV_ORGANIZATION AS ORG
	ON
	ORG.ORGANIZATION_GU = ORGYR.ORGANIZATION_GU
	INNER JOIN
	rev.EPC_STU AS STU
	ON
	ELL.STUDENT_GU = STU.STUDENT_GU
	INNER JOIN
	APS.LookupTable('K12', 'Grade') AS LU
	ON
	LU.VALUE_CODE = PRIM.GRADE