/*
*	Created For Shayne
*	Date: 7/14/2014
*
*	Create 61 Dosage records from a Las Cruces file.
* 
*/



BEGIN TRANSACTION


INSERT INTO rev.EPC_VACCINATION_DEF_DOSAGE

(VACCINATION_DOSAGE_DEF_GU
,VACCINATION_SCH_YR_GU
,DOSAGE_ORDER
,DOSAGE_INTERVAL
,INTERVAL_TYPE
,GRACE_PERIOD
,GRACE_INTERVAL_TYPE
,CHANGE_DATE_TIME_STAMP
,CHANGE_ID_STAMP
,ADD_DATE_TIME_STAMP
,ADD_ID_STAMP
)


SELECT 

NEWID() --AS VACCINATION_DOSAGE_DEF_GU
,CSVFILE.VACCINATION_SCH_YR_GU --AS VACCINATION_SCH_YR_GU
,CSVFILE.DOSAGE_ORDER --AS DOSAGE_ORDER
,CSVFILE.DOSAGE_INTERVAL --AS DOSAGE_INTERVAL
,right('00'+convert(varchar(2), CSVFILE.INTERVAL_TYPE), 2)
--,CSVFILE.INTERVAL_TYPE--AS INTERNAL_TYPE
,CSVFILE.GRACE_PERIOD--AS GRACE_PERIOD
,right('00'+convert(varchar(2), CSVFILE.GRACE_INTERVAL_TYPE), 2)
--,CSVFILE.GRACE_INTERVAL_TYPE --AS GRACE _INTERVAL_TYPE
,NULL --AS CHANGE_DATE_STAMP
,NULL --AS CHANGE_ID_STAMP
,GETDATE() --AS ADD_DATE_TIME_STAMP
,'29F18B95-1E2A-4618-B232-FB346114992D' --AS ADD_ID_STAMP


 FROM

OPENROWSET ('MSDASQL', 'Driver={Microsoft Access Text Driver (*.txt, *.csv)};DBQ=D:\SQLWorkingFiles;', 'SELECT * from "DOSAGE.csv"')
		AS CSVFILE

ROLLBACK

