
SELECT 
	SIS_NUMBER, ADAS.GRADE, PRIMARIES.*
 FROM 
(SELECT STUDENT_GU, GRADE, SCHOOL_CODE, ENTER_DATE, ENTER_DESCRIPTION, LEAVE_DATE, LEAVE_DESCRIPTION FROM 
APS.StudentEnrollmentDetails
WHERE
SCHOOL_YEAR = '2015'
AND EXTENSION = 'R'
AND SUMMER_WITHDRAWL_CODE IS NULL
AND EXCLUDE_ADA_ADM IS NULL 
) AS PRIMARIES

INNER JOIN 

(SELECT STUDENT_GU, GRADE, SCHOOL_CODE, ENTER_DATE, ENTER_DESCRIPTION, LEAVE_DATE, LEAVE_DESCRIPTION FROM 
APS.StudentEnrollmentDetails
WHERE
SCHOOL_YEAR = '2015'
AND EXTENSION = 'R'
AND SUMMER_WITHDRAWL_CODE IS NULL
AND EXCLUDE_ADA_ADM IS NOT NULL 
) AS ADAS

ON
ADAS.STUDENT_GU = PRIMARIES.STUDENT_GU

INNER JOIN 
rev.EPC_STU AS STU
ON
PRIMARIES.STUDENT_GU = STU.STUDENT_GU

WHERE
ADAS.GRADE != PRIMARIES.GRADE





