

/*
	Created By:  Debbie Ann Chavez
	Date:  4/17/2015

	Part 1 Transfer Process - Update Next School and Next Grade
	The select creates a file for verification and error types.
	After this Update is run, then NYR must be run to create enrollments.
*/

EXECUTE AS LOGIN='QueryFileUser'
GO



BEGIN TRANSACTION
UPDATE rev.EPC_STU_SCH_YR
	SET NEXT_GRADE_LEVEL = NEXT_YEAR_GRADE_CODE, NEXT_SCHOOL_GU = NEXT_SCHOOL_ORGGU
	, CHANGE_DATE_TIME_STAMP = GETDATE(), CHANGE_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F'


 FROM 

(
 

/*****************************************************************************************************

--COMMENT OUT EVERYTHING ABOVE THIS TO ONLY PULL DETAILS

******************************************************************************************************/

SELECT 

	[File].*
	
	,SSY.NEXT_SCHOOL_GU AS CURRENT_NEXT_SCHOOL
	,SCHOOL2.SCHOOL_CODE AS CURRENT_SCHOOL_CODE
	,GRADEL.VALUE_DESCRIPTION AS CURRENT_GRADE
	,GRADEL.ALT_CODE_SIF AS NEXT_YEAR_GRADE
	,GRADEL2.VALUE_CODE AS NEXT_YEAR_GRADE_CODE

	,SCHOOL3.SCHOOL_CODE AS NEXT_SCHOOL_FROMFILE
	,SCHOOL3.ORGANIZATION_GU AS NEXT_SCHOOL_ORGGU
	,SSY.STUDENT_SCHOOL_YEAR_GU

	--2017R
	--,'A3F9F1FB-4706-49AA-B3A3-21F153966191' AS YEAR_GU

FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from ReplaceFile.csv'
                ) AS [File]


LEFT JOIN 
rev.EPC_STU AS STU

ON
[File].[SIS_NUMBER] = STU.SIS_NUMBER

LEFT JOIN
APS.PrimaryEnrollmentsAsOf(GETDATE()) AS PE
ON
STU.STUDENT_GU = PE.STUDENT_GU

LEFT JOIN
rev.EPC_STU_SCH_YR AS SSY
ON
PE.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU

LEFT JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = SSY.ORGANIZATION_YEAR_GU

LEFT JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU


LEFT JOIN
rev.REV_ORGANIZATION AS NXTSCH
ON
SSY.NEXT_SCHOOL_GU = NXTSCH.ORGANIZATION_GU

LEFT JOIN
rev.EPC_SCH AS SCHOOL2
ON
SCHOOL2.ORGANIZATION_GU = NXTSCH.ORGANIZATION_GU 


LEFT JOIN
APS.LookupTable ('K12', 'Grade') AS GRADEL
ON
GRADEL.VALUE_CODE = SSY.GRADE

LEFT JOIN 
APS.LookupTable ('K12', 'Grade') AS GRADEL2
ON
GRADEL.ALT_CODE_SIF = GRADEL2.VALUE_DESCRIPTION

LEFT JOIN
rev.EPC_SCH AS SCHOOL3
ON
SCHOOL3.SCHOOL_CODE = CAST([File].NEXT_SCHOOL AS VARCHAR)

) AS T1

 WHERE 
rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU = T1.STUDENT_SCHOOL_YEAR_GU

ROLBACK

 REVERT
GO





