EXECUTE AS LOGIN='QueryFileUser'
GO

BEGIN TRAN

UPDATE REV.EPC_STREET 

SET STREET_POST_DIRECTION = T3.STREET_POST_DIRECTION, STREET_TYPE = T3.STREET_TYPE

FROM 
(
SELECT 
	t1.STREET_TYPE AS FILE_STREET_TYPE, t1.STREET_POST_DIRECTION AS FILE_POST_DIRECTION, T1.STREET_NAME, T1.STREET_LOW_ADDRESS
	,STREET2.STREET_TYPE, STREET2.STREET_POST_DIRECTION, STREET2.STREET_GU

 FROM (

SELECT 
	--T3.*
	'' AS OBJECTID
	,T1.[GridCode]
	,STREET_NUMBER as STREET_LOW_ADDRESS
	,STREET_NAME
	,STREET_TYPE_DESC AS STREET_TYPE
	,STREET_POST_DIRECTION
	,STUADDRESS.CITY AS STREET_CITY
	,STUADDRESS.[STATE] AS STREET_STATE
	,ZIP_5
	,T1.APS_STUID
	,STU.SIS_NUMBER
	,VALUE_CODE

FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from KidsAddressToChangeGrid.csv'
                ) AS [T1]

LEFT JOIN 
REV.EPC_STU AS STU
ON
T1.APS_STUID = STU.SIS_NUMBER

LEFT JOIN 
(SELECT 
	SIS_NUMBER
	,ADR.STREET_NUMBER, ADR.STREET_NAME, ADR.STREET_TYPE, LU.VALUE_DESCRIPTION AS STREET_TYPE_DESC
	,ADR.STREET_POST_DIRECTION
	,ADR.CITY
	,ADR.STATE
	,ADR.ZIP_5
	,ADR.STREET_EXTRA
	,LU.VALUE_CODE
 FROM 
APS.BasicStudentWithMoreInfo AS BS
INNER JOIN 
REV.REV_ADDRESS AS ADR
ON
BS.HOME_ADDRESS_GU = ADR.ADDRESS_GU
LEFT JOIN 
APS.LookupTable('K12.AddressInfo','STREET_TYPE') AS LU
ON
LU.VALUE_CODE = ADR.STREET_TYPE
) AS STUADDRESS
ON
STUADDRESS.SIS_NUMBER = STU.SIS_NUMBER

INNER JOIN 
(
SELECT * 
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from OrigFile2018Street.csv'
                ) AS [T2]
) AS T3

ON
T1.APS_STUID = T3.APS_STUID

WHERE STREET_POST_DIRECTION IS NULL

--ORDER BY STU.SIS_NUMBER

) AS T1

/*
 FILE HAD INCORRECT POST DIRECTION AND STREET TYPE'S SO I HAD TO READ STREET FOR LAST YEAR TO GET GOOD VALUES

*/

INNER JOIN 
REV.EPC_STREET AS STREET2
ON
STREET2.STREET_LOW_ADDRESS = T1.STREET_LOW_ADDRESS
AND STREET2.STREET_NAME = T1.STREET_NAME
AND STREET2.CITY = T1.STREET_CITY
AND STREET2.[STATE] = T1.STREET_STATE
AND STREET2.SCHOOL_YEAR = '2017'

WHERE 
STREET2.STREET_POST_DIRECTION IS NOT NULL
OR STREET2.STREET_TYPE IS NOT NULL

) AS T3

WHERE
rev.EPC_STREET.STREET_GU = T3.STREET_GU

COMMIT

REVERT 
GO