EXECUTE AS LOGIN='QueryFileUser'
GO

SELECT 
	--T3.*
	'' AS OBJECTID
	,T1.[GridCode]
	,STREET_NUMBER as STREET_LOW_ADDRESS
	,STREET_NAME
	,STREET_TYPE_DESC AS STREET_TYPE
	,STREET_POST_DIRECTION
	,STUADDRESS.CITY AS STREET_CITY
	,STUADDRESS.[STATE] AS STREET_STATE
	,ZIP_5
	,T1.APS_STUID
	,STU.SIS_NUMBER
	,VALUE_CODE

FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from KidsAddressToChangeGrid.csv'
                ) AS [T1]

LEFT JOIN 
REV.EPC_STU AS STU
ON
T1.APS_STUID = STU.SIS_NUMBER

LEFT JOIN 
(SELECT 
	SIS_NUMBER
	,ADR.STREET_NUMBER, ADR.STREET_NAME, ADR.STREET_TYPE, LU.VALUE_DESCRIPTION AS STREET_TYPE_DESC
	,ADR.STREET_POST_DIRECTION
	,ADR.CITY
	,ADR.STATE
	,ADR.ZIP_5
	,ADR.STREET_EXTRA
	,LU.VALUE_CODE
 FROM 
APS.BasicStudentWithMoreInfo AS BS
INNER JOIN 
REV.REV_ADDRESS AS ADR
ON
BS.HOME_ADDRESS_GU = ADR.ADDRESS_GU
LEFT JOIN 
APS.LookupTable('K12.AddressInfo','STREET_TYPE') AS LU
ON
LU.VALUE_CODE = ADR.STREET_TYPE
) AS STUADDRESS
ON
STUADDRESS.SIS_NUMBER = STU.SIS_NUMBER

INNER JOIN 
(
SELECT * 
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from OrigFile2018Street.csv'
                ) AS [T2]
) AS T3

ON
T1.APS_STUID = T3.APS_STUID

--WHERE STREET_TYPE IS NULL

ORDER BY STU.SIS_NUMBER

REVERT 
GO