

SELECT 
SCHOOL_NAME, ENR.GRADE, SIS_NUMBER, LAST_NAME, FIRST_NAME 
,VALUE_DESCRIPTION AS NEXT_GRADE_LEVEL, ORG.ORGANIZATION_NAME AS NEXT_SCHOOL, ENR.YEAR_END_STATUS

 FROM 
APS.StudentEnrollmentDetails AS ENR
INNER JOIN 
REV.EPC_STU_SCH_YR AS SSY
ON
ENR.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU
AND ENR.SCHOOL_YEAR = '2017' AND EXTENSION = 'R'

INNER JOIN 
REV.REV_PERSON AS PERS
ON
ENR.STUDENT_GU = PERS.PERSON_GU 

LEFT JOIN 
REV.REV_ORGANIZATION AS ORG
ON
SSY.NEXT_SCHOOL_GU = ORG.ORGANIZATION_GU
LEFT JOIN 
APS.LookupTable('K12', 'GRADE') AS GRADE
ON
GRADE.VALUE_CODE = SSY.NEXT_GRADE_LEVEL

WHERE

ENR.YEAR_END_STATUS IS NOT NULL
OR NEXT_GRADE_LEVEL IS NOT NULL
OR NEXT_SCHOOL_GU IS NOT NULL

ORDER BY 
SCHOOL_NAME, GRADE, LAST_NAME, FIRST_NAME
--YEAR_END_STATUS DESC