

SELECT SIS_NUMBER, Q1_LANGUAGE_SPOKEN_MOST, Q2_CHILD_FIRST_LANGUAGE, Q3_LANGUAGES_SPOKEN, Q4_OTHER_LANG_COMMUNICATED,Q5_OTHER_LANG_UNDERSTOOD
FROM 
REV.UD_STU AS STU
INNER JOIN 
rev.EPC_STU AS STU2
ON
STU.STUDENT_GU = STU2.STUDENT_GU
WHERE
Q1_LANGUAGE_SPOKEN_MOST IS NOT NULL OR
Q2_CHILD_FIRST_LANGUAGE  IS NOT NULL OR
Q3_LANGUAGES_SPOKEN  IS NOT NULL OR
Q4_OTHER_LANG_COMMUNICATED  IS NOT NULL OR
Q5_OTHER_LANG_UNDERSTOOD IS NOT NULL