

SELECT STU.SIS_NUMBER, ENTER_DATE, LEAVE_DATE, SCHOOL_NAME, STATE_STUDENT_NUMBER FROM 
REV.EPC_STU AS STU
INNER JOIN 
APS.StudentEnrollmentDetails AS ENR
ON
STU.STUDENT_GU = ENR.STUDENT_GU

WHERE
STU.SIS_NUMBER IN (103397196, 980020988)


