
SELECT 
	SCH.ID_NBR
	,CAL.CAL_DT
	,CYC.CYCLE_DAY 
	,COUNT (*) AS [Total Classes]
	--,SCH.CRS_ASG
	--,CYC.PERIOD
	--,DATE_ASG
	--,DATE_DROP
	--,TERMS.TERM_CD
FROM 
DBTSIS.SC055_V AS SCH
INNER JOIN 
DBTSIS.SC065_V AS CYC
ON
SCH.DST_NBR = CYC.DST_NBR
AND SCH.SCH_YR = CYC.SCH_YR
AND SCH.VERSION = CYC.VERSION
AND SCH.SCH_NBR = CYC.SCH_NBR
AND SCH.CRS_ASG = CYC.COURSE
AND SCH.SECT_ASG = CYC.XSECTION

INNER JOIN 
DBTSIS.SC060_V AS TERMS
ON
TERMS.DST_NBR = SCH.DST_NBR
AND TERMS.SCH_YR = SCH.SCH_YR
AND TERMS.VERSION = SCH.VERSION
AND TERMS.SCH_NBR = SCH.SCH_NBR
AND TERMS.COURSE = SCH.CRS_ASG
AND TERMS.XSECTION = SCH.SECT_ASG


INNER JOIN 
DBTSIS.CA005_V AS CAL
ON
CAL.DST_NBR = SCH.DST_NBR
AND CAL.SCH_YR = SCH.SCH_YR
AND CAL.SCH_NBR = SCH.SCH_NBR
AND CAL.CYCLE_DAY = CYC.CYCLE_DAY
AND (CAL.CAL_DT>=SCH.DATE_ASG  OR SCH.DATE_ASG= 0) 
AND (CAL.CAL_DT<=SCH.DATE_DROP OR SCH.DATE_DROP = 0)

INNER JOIN 
APS.SchoolTermsAndDates AS TRMS
ON
TRMS.DST_NBR = SCH.DST_NBR
AND TRMS.SCH_YR = SCH.SCH_YR
AND TRMS.VERSION = SCH.VERSION
AND TRMS.SCH_NBR = SCH.SCH_NBR
AND TERMS.TERM_CD = TRMS.TERM_CD
AND CAL.CAL_DT BETWEEN TRMS.BEG_DT AND TRMS.END_DT

WHERE
ID_NBR = 102785458
--AND CAL.CAL_DT = '20130820'

AND SCH.DST_NBR = 1
AND SCH.SCH_YR = 2014
AND SCH.VERSION = '00'
AND SCH.SCH_NBR = '550'


GROUP BY 
	SCH.ID_NBR
	,CAL.CAL_DT
	,CYC.CYCLE_DAY 

ORDER BY CAL.CAL_DT

