

EXECUTE AS LOGIN='QueryFileUser'
GO






SELECT 
	ROLL.APS_ID, SIS_NUMBER, ROLL.[FIRST], ROLL.[LAST], ROLL.[APP LOC]
	,'2015-01-31' AS [TRANSFER_DATE_APPROVED]

	,SSY.SCHOOL_CODE
	,SSY.SCHOOL_NAME
	,SSY2.ATTEND_PERMIT_CODE
	,SSY2.ATTEND_PERMIT_DATE

 FROM
 OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from ROLLOVERS2017.csv'
                ) AS [ROLL]
			INNER JOIN 
			rev.EPC_STU AS STU
			ON
			ROLL.APS_ID = STU.SIS_NUMBER

INNER JOIN 
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS SSY
ON
SSY.STUDENT_GU = STU.STUDENT_GU

INNER JOIN 
rev.EPC_STU_SCH_YR AS SSY2
ON
SSY.STUDENT_SCHOOL_YEAR_GU = SSY2.STUDENT_SCHOOL_YEAR_GU

--WHERE ATTEND_PERMIT_CODE IS NULL
WHERE SIS_NUMBER = 970027595

ORDER BY SSY.STUDENT_GU

