
EXECUTE AS LOGIN='QueryFileUser'
GO

SELECT * FROM 
(
SELECT
            ROW_NUMBER() OVER (PARTITION BY T1.SIS_NUMBER, SERVICE_DESCRIPTION ORDER BY T2.START_DATE DESC) AS RN
			
			,PERS.LAST_NAME
			,PERS.FIRST_NAME
			,PERS.MIDDLE_NAME
			,T1.SIS_NUMBER
			,STU.STATE_STUDENT_NUMBER

			,ORG.ORGANIZATION_NAME
			, SCH.SCHOOL_CODE
			, SCH.STATE_SCHOOL_CODE
	
            ,T1.PRIMARY_DISABILITY_CODE
			,CASE WHEN IEP.IEP_STATUS = 'CU' THEN 'Current' ELSE '' END AS IEP_STATUS

			--,IEP.PREVIOUS_EVAL_DATE ?? IDK WHAT THIS IS
			--,IEP.IEP_DATE?? OR THIS ONE 

			,T1.NEXT_IEP_DATE AS REVIEW_DATE
			,CURRENT_IEP_DATE AS PREVIOUS_IEP_DATE


			--,T2.IEP_DATE

			,T2.START_DATE
			,T2.END_DATE

			,T2.SERVICE_DESCRIPTION
			,T2.STATE_REPORTING_CODE
			,T2.NUM_MINUTES
			,T2.FREQUENCY
			,T2.INTEGRATED_STATUS


FROM   
            APS.PrimaryEnrollmentsAsOf('2016-02-10') AS Enrollment
            INNER JOIN
            (
            SELECT
                        STU.SIS_NUMBER
						,SPED.STUDENT_GU
                        ,PRIMARY_DISABILITY_CODE
						,NEXT_IEP_DATE
						,CURRENT_IEP_DATE
            FROM
                        REV.EP_STUDENT_SPECIAL_ED AS SPED
						INNER JOIN
						rev.EPC_STU AS STU
						ON
						SPED.STUDENT_GU = STU.STUDENT_GU
				
            WHERE
                        NEXT_IEP_DATE IS NOT NULL
                        AND (
                                    EXIT_DATE IS NULL 
                                    OR EXIT_DATE >= CONVERT(DATE, '2016-02-10')
                                    )
			) as t1

			ON
			Enrollment.STUDENT_GU = T1.STUDENT_GU

					INNER JOIN 
						rev.EP_STUDENT_IEP AS IEP
						ON 
						IEP.STUDENT_GU = T1.STUDENT_GU
						AND IEP.IEP_STATUS = 'CU'

				INNER JOIN
						rev.EPC_STU AS STU
						ON
						T1.STUDENT_GU = STU.STUDENT_GU
				INNER JOIN 
					REV.REV_PERSON AS PERS
				ON
				STU.STUDENT_GU = PERS.PERSON_GU

				INNER JOIN 
				rev.REV_ORGANIZATION_YEAR AS ORGYR
				ON
				ENROLLMENT.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU

				INNER JOIN 
				rev.REV_ORGANIZATION AS ORG
				ON
				ORG.ORGANIZATION_GU = ORGYR.ORGANIZATION_GU

				INNER JOIN
				rev.EPC_SCH AS SCH
				ON
				ORG.ORGANIZATION_GU = SCH.ORGANIZATION_GU


/*******************************************************************


********************************************************************/
INNER JOIN 
(
SELECT 
STU.STUDENT_GU 
,IEP.IEP_GU

,IEP.IEP_DATE

,SERV.START_DATE
,SERV.END_DATE

,SIS_NUMBER
,rs.SERVICE_DESCRIPTION 
,RS.STATE_REPORTING_CODE, NUM_MINUTES
, FREQ2.VALUE_DESCRIPTION AS FREQUENCY
,CASE WHEN SERV.INTERACTION = 'Y' THEN 'Special Ed Setting' ELSE 'Regular Ed Setting' END AS INTEGRATED_STATUS


FROM 
rev.EP_STUDENT_IEP AS IEP

INNER JOIN
rev.EP_STU_IEP_SERVICE  AS SERV
ON
SERV.IEP_GU = IEP.IEP_GU
AND IEP.IEP_STATUS = 'CU'

INNER JOIN 
rev.EP_SPECIAL_ED_SERVICE AS RS
ON
SERV.SERVICE_GU = RS.SERVICE_GU
AND STATE_REPORTING_CODE IS NOT NULL

INNER JOIN
rev.EPC_STU AS STU
ON
IEP.STUDENT_GU = STU.STUDENT_GU

LEFT JOIN 
(SELECT STUDENT_GU, SERVICE_CODE, IEP_GU, SERVICE_CYCLE, SNAPSHOT_TYPE FROM 
(select row_number() over (partition by STUDENT_GU order by SNAPSHOT_TYPE desc) RowNum,*
      from rev.EPC_NM_STU_SPED_RPT
      where SCHOOL_YEAR = (select SCHOOL_YEAR from rev.SIF_22_Common_CurrentYear))
	   sr
		inner join rev.EPC_NM_STU_SPED_RPT_SRV srsv on (srsv.STU_SPED_RPT_GU = sr.STU_SPED_RPT_GU and sr.RowNum = 1)
) AS T1

ON
T1.STUDENT_GU = STU.STUDENT_GU
AND IEP.IEP_GU = T1.IEP_GU
AND SERV.VIEW_ORDER = T1.SNAPSHOT_TYPE

LEFT JOIN 
APS.LookupTable('K12.SpecialEd.IEP','SPED_SERVICE') AS FREQ
ON
T1.SERVICE_CODE = FREQ.VALUE_CODE

LEFT JOIN 
APS.LookupTable('K12.SpecialEd.IEP','SERVICE_FREQUENCY') AS FREQ2
ON
FREQUENCY_UNIT_DD = FREQ2.VALUE_CODE

) AS T2

ON T2.STUDENT_GU = T1.STUDENT_GU

WHERE
T1.NEXT_IEP_DATE <= '2016-02-10'

) AS PULLMORE

WHERE
RN = 1
AND SIS_NUMBER NOT IN (
SELECT SIS_NUMBER FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT * FROM SPED.csv'
                ) AS [SET1]		

) 


REVERT 
GO	







