
SELECT BADGE_NUM, SUBSTRING(USER_LEVEL,2,4) AS SCHOOL_CODE 
,CASE WHEN USER_LEVEL = '0060' THEN 'Indian Education Department' 
		WHEN USER_LEVEL = '0162' THEN 'Health & Wellness Department'
ELSE ORGANIZATION_NAME END AS SCHOOL_NAME

, CREDENTIAL_TYPE, VALUE_DESCRIPTION AS CREDENTIAL_DESCRIPTION
	
 FROM 
rev.EPC_STAFF_CRD AS CRD
INNER JOIN 
rev.EPC_STAFF AS STF
ON
CRD.STAFF_GU = STF.STAFF_GU
INNER JOIN 
APS.LookupTable ('K12.Staff', 'Cred_Type') AS LU
ON
CRD.CREDENTIAL_TYPE = LU.VALUE_CODE
INNER JOIN 
(SELECT EMPLOYEE, USER_LEVEL 
FROM 
[180-SMAXODS-01.APS.EDU.ACTD].Lawson.dbo.PAEMPPOS 
WHERE
END_DATE IS NULL 
OR END_DATE > GETDATE()) AS T1

LEFT JOIN 
rev.EPC_SCH AS SCH
ON
SUBSTRING(USER_LEVEL,2,4) = SCH.SCHOOL_CODE

ON
T1.EMPLOYEE = STF.STATE_ID

LEFT JOIN 
rev.REV_ORGANIZATION AS ORG
ON
SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU

WHERE
CREDENTIAL_TYPE = '0520'

