
SELECT 
STUGRD.*

 FROM 
APS.StudentGrades AS STUGRD
INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
STUGRD.ORGANIZATION_NAME = ORG.ORGANIZATION_NAME
INNER JOIN
rev.EPC_SCH AS SCHOOL
ON
ORG.ORGANIZATION_GU = SCHOOL.ORGANIZATION_GU

WHERE
SCHOOL_CODE LIKE '4%'
AND GRADE_PERIOD IN ( 'Q2',  'S1 Grade', 'EXPL Q2 or S1 Exam')
AND CREDIT = '0.250'

ORDER BY ORGANIZATION_NAME, SIS_NUMBER, GRADE_PERIOD, COURSE_ID