
SELECT 
	STUDENT.SIS_NUMBER
	,STUDENT.STATE_STUDENT_NUMBER
	,CASE WHEN ELL.STUDENT_GU IS NOT NULL THEN 'Y' ELSE 'N' END AS ELL
	,CASE WHEN ELL.STUDENT_GU IS NOT NULL THEN 'Y' ELSE 'N' END AS LEP

 FROM
APS.PrimaryEnrollmentsAsOf (GETDATE()) AS PE
INNER JOIN
APS.ELLAsOf(GETDATE()) AS ELL
ON
PE.STUDENT_GU = ELL.STUDENT_GU

INNER JOIN
rev.EPC_STU AS STUDENT
ON
PE.STUDENT_GU = STUDENT.STUDENT_GU

