
EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT 
--PED FILE	
	[id], [SchoolYear], [DistrictCode], [DistrictName], [LocationID], [SchoolName], [StudentID], [LastName], [FirstName], [DOB], [Grade], [Gender], [Ethnicity], [SPED], [Migrant]
	,[FRL], [ELL], [Homeless], [Private], [ReasonForLeaving], [WithdrawalCode], [GED], [gedid], [HomeSchool], [HomeSchoolID], [GraduationStatus], [LastAttended], [Comments]

--LAST PRIMARY ENROLLMENT DATA
	,ALLCRSDATA.SIS_NUMBER, ENTER_DATE, SCHOOL_NAME, SCHOOL_YEAR, EXTENSION, LEAVE_CODE, LEAVE_DATE, LEAVE_DESCRIPTION, SUMMER_WITHDRAWL_CODE, SUMMER_WITHDRAWL_DATE

--COURSE VERIFICATION DATA PIVOTED 
	, CASE WHEN RELEASE_DATE1 = '1900-01-01 00:00:00' THEN NULL ELSE RELEASE_DATE1 END AS RELEASE_DATE1
	, NON_DISTRICT_SCHOOL1
	, PERSON_RELEASED_TO1
	, PERSON_TITLE_DESC1
	, RELEASE_PURPOSE_DESC1
	, DELIVERY_TYPE1
	, CASE WHEN REQUEST_DATE1 = '1900-01-01 00:00:00' THEN NULL ELSE REQUEST_DATE1  END AS REQUEST_DATE1
	, TRACKING_NOTES1
	
	, CASE WHEN RELEASE_DATE2 = '1900-01-01 00:00:00' THEN NULL ELSE RELEASE_DATE2 END AS RELEASE_DATE2
	, NON_DISTRICT_SCHOOL2
	, PERSON_RELEASED_TO2
	, PERSON_TITLE_DESC2
	, RELEASE_PURPOSE_DESC2
	, DELIVERY_TYPE2
	, CASE WHEN REQUEST_DATE2 = '1900-01-01 00:00:00' THEN NULL ELSE REQUEST_DATE2 END AS REQUEST_DATE2
	, TRACKING_NOTES2

	, CASE WHEN RELEASE_DATE3 = '1900-01-01 00:00:00' THEN NULL ELSE RELEASE_DATE3 END AS RELEASE_DATE3
	, NON_DISTRICT_SCHOOL3
	,PERSON_RELEASED_TO3
	, PERSON_TITLE_DESC3
	, RELEASE_PURPOSE_DESC3
	, DELIVERY_TYPE3
	, CASE WHEN REQUEST_DATE3 = '1900-01-01 00:00:00' THEN NULL ELSE REQUEST_DATE3 END AS REQUEST_DATE3
	,TRACKING_NOTES3
	

 FROM 

(
SELECT 
	
	[id], [SchoolYear], [DistrictCode], [DistrictName], [LocationID], [SchoolName], [StudentID], [LastName], [FirstName], [DOB], [Grade], [Gender], [Ethnicity], [SPED], [Migrant]
	,[FRL], [ELL], [Homeless], [Private], [ReasonForLeaving], [WithdrawalCode], [GED], [gedid], [HomeSchool], [HomeSchoolID], [GraduationStatus], [LastAttended], [Comments]

	,T1.SIS_NUMBER	
	
	
	,MAX(CASE WHEN RN = 1 THEN RELEASE_DATE ELSE '' END) AS RELEASE_DATE1
	,MAX(CASE WHEN RN = 1 THEN NON_DISTRICT_SCHOOL ELSE '' END) AS NON_DISTRICT_SCHOOL1
	,MAX(CASE WHEN RN = 1 THEN PERSON_RELEASED_TO ELSE '' END) AS PERSON_RELEASED_TO1
	,MAX(CASE WHEN RN = 1 THEN PERSON_TITLE_DESC ELSE '' END) AS PERSON_TITLE_DESC1
	,MAX(CASE WHEN RN = 1 THEN RELEASE_PURPOSE_DESC ELSE '' END) AS RELEASE_PURPOSE_DESC1
	,MAX(CASE WHEN RN = 1 THEN DELIVERY_TYPE ELSE '' END) AS DELIVERY_TYPE1
	,MAX(CASE WHEN RN = 1 THEN REQUEST_DATE ELSE '' END) AS REQUEST_DATE1
	,MAX(CASE WHEN RN = 1 THEN TRACKING_NOTES ELSE '' END) AS TRACKING_NOTES1
	
	,MAX(CASE WHEN RN = 2 THEN RELEASE_DATE ELSE '' END) AS RELEASE_DATE2
	,MAX(CASE WHEN RN = 2 THEN NON_DISTRICT_SCHOOL ELSE '' END) AS NON_DISTRICT_SCHOOL2
	,MAX(CASE WHEN RN = 2 THEN PERSON_RELEASED_TO ELSE '' END) AS PERSON_RELEASED_TO2
	,MAX(CASE WHEN RN = 2 THEN PERSON_TITLE_DESC ELSE '' END) AS PERSON_TITLE_DESC2
	,MAX(CASE WHEN RN = 2 THEN RELEASE_PURPOSE_DESC ELSE '' END) AS RELEASE_PURPOSE_DESC2
	,MAX(CASE WHEN RN = 2 THEN DELIVERY_TYPE ELSE '' END) AS DELIVERY_TYPE2
	,MAX(CASE WHEN RN = 2 THEN REQUEST_DATE ELSE '' END) AS REQUEST_DATE2
	,MAX(CASE WHEN RN = 2 THEN TRACKING_NOTES ELSE '' END) AS TRACKING_NOTES2

	,MAX(CASE WHEN RN = 3 THEN RELEASE_DATE ELSE '' END) AS RELEASE_DATE3
	,MAX(CASE WHEN RN = 3 THEN NON_DISTRICT_SCHOOL ELSE '' END) AS NON_DISTRICT_SCHOOL3
	,MAX(CASE WHEN RN = 3 THEN PERSON_RELEASED_TO ELSE '' END) AS PERSON_RELEASED_TO3
	,MAX(CASE WHEN RN = 3 THEN PERSON_TITLE_DESC ELSE '' END) AS PERSON_TITLE_DESC3
	,MAX(CASE WHEN RN = 3 THEN RELEASE_PURPOSE_DESC ELSE '' END) AS RELEASE_PURPOSE_DESC3
	,MAX(CASE WHEN RN = 3 THEN DELIVERY_TYPE ELSE '' END) AS DELIVERY_TYPE3
	,MAX(CASE WHEN RN = 3 THEN REQUEST_DATE ELSE '' END) AS REQUEST_DATE3
	,MAX(CASE WHEN RN = 3 THEN TRACKING_NOTES ELSE '' END) AS TRACKING_NOTES3

 FROM (

SELECT 
	ROW_NUMBER() OVER (PARTITION BY STATE_STUDENT_NUMBER ORDER BY STATE_STUDENT_NUMBER, RELEASE_DATE DESC,LU2.VALUE_DESCRIPTION DESC ) AS RN
	,T1.*
	,STU.SIS_NUMBER
	,HIST.RELEASE_DATE
	,NONS.NAME AS NON_DISTRICT_SCHOOL
	,HIST.PERSON_RELEASED_TO
	--,HIST.PERSON_TITLE
	,LU.VALUE_DESCRIPTION AS PERSON_TITLE_DESC
	--,HIST.RELEASE_PURPOSE
	,LU2.VALUE_DESCRIPTION AS RELEASE_PURPOSE_DESC

	,LU3.VALUE_DESCRIPTION AS DELIVERY_TYPE
	,HIST.REQUEST_DATE
	,TRANSOPT.TRANS_OPT_NAME
	,REPLACE(REPLACE(REPLACE(
	CAST(TRACK.NOTES AS VARCHAR (100))
	, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS TRACKING_NOTES
	--,TRACK.NOTES AS TRACKING_NOTES

	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from DDCS_updated.csv'
                ) AS [T1]

INNER JOIN 
REV.EPC_STU AS STU
ON
[T1].[StudentID] = stu.STATE_STUDENT_NUMBER

LEFT JOIN 
REV.EPC_STU_REQUEST_TRACKING AS HIST
ON
HIST.STUDENT_GU = STU.STUDENT_GU

LEFT JOIN 
REV.EPC_SCH_NON_DST AS NONS
ON
NONS.SCHOOL_NON_DISTRICT_GU = HIST.SCHOOL_NON_DISTRICT_GU

LEFT JOIN 
REV.EPC_SCH_YR_TRANS_OPT AS TRANSOPT
ON
TRANSOPT.SCH_YR_TRANS_OPT_GU = HIST.SCH_YR_TRANS_OPT_GU

LEFT JOIN 
REV.UD_STU_REQUEST_TRACKING AS TRACK
ON
TRACK.STU_REQUEST_TRACKING_GU = HIST.STU_REQUEST_TRACKING_GU

LEFT JOIN 
APS.LookupTable('K12.CourseHistoryInfo', 'PERSON_TITLE') AS LU
ON
LU.VALUE_CODE = HIST.PERSON_TITLE

LEFT JOIN 
APS.LookupTable('K12.CourseHistoryInfo', 'RELEASE_PURPOSE') AS LU2
ON
LU2.VALUE_CODE = HIST.RELEASE_PURPOSE

LEFT JOIN 
APS.LookupTable('K12.CourseHistoryInfo', 'DELIVERY_TYPE') AS LU3
ON
LU3.VALUE_CODE = HIST.DELIVERY_TYPE


) AS T1

--WHERE [StudentID] = 648462950

--ORDER BY [StudentID]

GROUP BY 	[id], [SchoolYear], [DistrictCode], [DistrictName], [LocationID], [SchoolName], [StudentID], [LastName], [FirstName], [DOB], [Grade], [Gender], [Ethnicity], [SPED], [Migrant]
	,[FRL], [ELL], [Homeless], [Private], [ReasonForLeaving], [WithdrawalCode], [GED], [gedid], [HomeSchool], [HomeSchoolID], [GraduationStatus], [LastAttended], [Comments]

	,T1.SIS_NUMBER
) AS ALLCRSDATA

LEFT HASH JOIN 
(	SELECT
		SIS_NUMBER, ENTER_DATE, SCHOOL_NAME, SCHOOL_YEAR, EXTENSION, LEAVE_CODE, LEAVE_DATE, LEAVE_DESCRIPTION, SUMMER_WITHDRAWL_CODE, SUMMER_WITHDRAWL_DATE
	FROM
		(
		SELECT
			SIS_NUMBER, ENTER_DATE, SCHOOL_NAME, SCHOOL_YEAR, EXTENSION, LEAVE_CODE, LEAVE_DATE, LEAVE_DESCRIPTION, SUMMER_WITHDRAWL_CODE, SUMMER_WITHDRAWL_DATE
			,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY SCHOOL_YEAR DESC, ENTER_DATE DESC) AS RN
		FROM
			APS.StudentEnrollmentDetails AS [ENROLLMENTS]
		WHERE 
			EXCLUDE_ADA_ADM IS NULL
		) AS [LATEST_ENROLLMENT]
	WHERE
		[RN] = 1
) AS ENROLLS

ON
ALLCRSDATA.SIS_NUMBER = ENROLLS.SIS_NUMBER	
			
REVERT
GO