

EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT DISTINCT
UNM.*
,STU.SIS_NUMBER
,GRADES.COURSE_ID
,GRADES.COURSE_TITLE
,GRADES.MARK
,GRADES.CREDIT
,CRS.COURSE_ID AS DCM_COURSE_ID
,CRS.CREDIT AS DCM_CREDIT
,CRSHST.COURSE_ID
,CRSHST.COURSE_TITLE
,CRSHST.MARK
,CRSHST.CREDIT_COMPLETED
, CASE WHEN UNM.FINAL_GRADE != GRADES.MARK THEN 'X'
		WHEN UNM.FINAL_GRADE != CRSHST.MARK THEN 'X'
	ELSE '' END AS MARK_DOESNT_MATCH

,CASE WHEN CRS.CREDIT != CRSHST.CREDIT_COMPLETED AND CRSHST.MARK NOT IN ('N', 'I', 'W', 'WF', 'F') THEN 'X' ELSE '' END AS CREDIT_DOESNT_MATCH


FROM

            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT * from UNM.csv'
                ) AS [UNM]

LEFT JOIN 
rev.EPC_STU AS STU

ON
UNM.STARRsID = STU.STATE_STUDENT_NUMBER

LEFT JOIN
APS.StudentGrades AS GRADES
ON
STU.STUDENT_GU = GRADES.STUDENT_GU
AND COALESCE(SUBJECT, '')+ COALESCE(CAST(COURSE_NUMBER AS VARCHAR), '')= GRADES.COURSE_ID
AND GRADES.ORGANIZATION_NAME LIKE ('University%')

LEFT JOIN
rev.EPC_CRS AS CRS
ON
GRADES.COURSE_ID = CRS.COURSE_ID

LEFT JOIN
rev.EPC_STU_CRS_HIS AS CRSHST
ON
STU.STUDENT_GU = CRSHST.STUDENT_GU
AND COALESCE(SUBJECT, '')+ COALESCE(CAST(COURSE_NUMBER AS VARCHAR), '') = CRSHST.COURSE_ID


      REVERT
GO