

SELECT 
LEFT(CONVERT(nvarchar(30), CAL.CAL_DATE, 112),8) AS CALDATE , SCHOOL_YEAR, EXTENSION, SCH.SCHOOL_CODE, CAL.HOLIDAY
FROM
[SYNSECONDDB.APS.EDU.ACTD].ST_Implement.rev.EPC_SCH_ATT_CAL AS CAL

INNER JOIN
[SYNSECONDDB.APS.EDU.ACTD].ST_Implement.rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = CAL.SCHOOL_YEAR_GU

INNER JOIN
[SYNSECONDDB.APS.EDU.ACTD].ST_Implement.rev.EPC_SCH_ATT_CAL_OPT AS OPT
ON 
OPT.ORG_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU

INNER JOIN
[SYNSECONDDB.APS.EDU.ACTD].ST_Implement.rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

INNER JOIN 
[SYNSECONDDB.APS.EDU.ACTD].ST_Implement.rev.EPC_SCH AS SCH
ON
ORG.ORGANIZATION_GU = SCH.ORGANIZATION_GU

INNER JOIN
[SYNSECONDDB.APS.EDU.ACTD].ST_Implement.rev.REV_YEAR AS YEARS
ON
ORGYR.YEAR_GU = YEARS.YEAR_GU

WHERE
 (CAL.CAL_DATE >= OPT.START_DATE AND CAL.CAL_DATE <= OPT.END_DATE)
 AND SCHOOL_CODE = '240'
 AND SCHOOL_YEAR = '2012'

 ORDER BY CALDATE