
SELECT STU.SIS_NUMBER, BS.LAST_NAME, BS.FIRST_NAME
,ELEM.SCHOOL_NAME
,ELEM.SCHOOL_YEAR AS SCHOOL_YEAR_LAST_ENROLLED
,ELEM.GRADE
, BS.BIRTH_DATE, BS.GENDER, BS.RESOLVED_RACE, BS.HISPANIC_INDICATOR, BS.RACE_1, BS.RACE_2, BS.RACE_3, BS.RACE_4, BS.RACE_5, EXIT_REASON,
FRM.VALUE_DESCRIPTION AS LUNCH_STATUS,
BS.HOME_LANGUAGE, HLS_Q1, HLS_Q2, HLS_Q3, HLS_Q4, HLS_Q5,
GETGPA.[HS Cum Flat], GETGPA.[HS Cum Weighted], GETGPA.[MS Cum Flat]
,BS.STUDENT_GU

 FROM 
	
	(SELECT 

	EY2.STUDENT_GU, EXIT_REASON FROM 
	rev.EPC_STU_PGM_ELL AS EY2
	
	LEFT JOIN
	APS.LCELatestEvaluationAsOf(GETDATE()) AS LCE1
	ON
	LCE1.STUDENT_GU = EY2.STUDENT_GU

	WHERE
	EXIT_REASON = 'EY2'
	AND 
	LCE1.ADMIN_DATE > '2014-01-01'
	) AS EY2

	INNER JOIN
	rev.EPC_STU AS STU
	ON
	EY2.STUDENT_GU = STU.STUDENT_GU
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS BS
	ON
	BS.STUDENT_GU = STU.STUDENT_GU
	INNER JOIN
	APS.LookupTable('K12.ProgramInfo', 'FRM_CODE') AS FRM
	ON
	BS.LUNCH_STATUS = FRM.VALUE_CODE

	LEFT JOIN
	(SELECT 
HLS.STUDENT_GU
,HOME.VALUE_DESCRIPTION AS HLS_Q1
,HOME2.VALUE_DESCRIPTION AS HLS_Q2
,HOME3.VALUE_DESCRIPTION AS HLS_Q3
,HOME4.VALUE_DESCRIPTION AS HLS_Q4
,HOME5.VALUE_DESCRIPTION AS HLS_Q5

FROM 
APS.LCEMostRecentHLSAsOf(GETDATE()) AS HLS
INNER JOIN
APS.LookupTable('K12', 'LANGUAGE') AS HOME
ON
HLS.Q1_LANGUAGE_SPOKEN_MOST = HOME.VALUE_CODE

INNER JOIN
APS.LookupTable('K12', 'LANGUAGE') AS HOME2
ON
HLS.Q2_CHILD_FIRST_LANGUAGE = HOME2.VALUE_CODE

INNER JOIN
APS.LookupTable('K12', 'LANGUAGE') AS HOME3
ON
HLS.Q3_LANGUAGES_SPOKEN = HOME3.VALUE_CODE

INNER JOIN
APS.LookupTable('K12', 'LANGUAGE') AS HOME4
ON
HLS.Q4_OTHER_LANG_UNDERSTOOD = HOME4.VALUE_CODE

INNER JOIN
APS.LookupTable('K12', 'LANGUAGE') AS HOME5
ON
HLS.Q5_OTHER_LANG_COMMUNICATED = HOME5.VALUE_CODE
) AS HLS
ON
BS.STUDENT_GU = HLS.STUDENT_GU


/*******************************************************************************

GET GPA
********************************************************************************/
LEFT JOIN
(
SELECT
	CASE WHEN T2.SIS_NUMBER IS NOT NULL THEN T2.SIS_NUMBER ELSE T4.SIS_NUMBER END AS SIS_NUMBER
	,CASE WHEN T2.SCHOOL_YEAR IS NOT NULL THEN T2.SCHOOL_YEAR ELSE T4.SCHOOL_YEAR END AS SCHOOL_YEAR
	,CASE WHEN T2.SCHOOL_NAME IS NOT NULL THEN T2.SCHOOL_NAME ELSE T4.SCHOOL_NAME END AS SCHOOL_NAME
	,CASE WHEN T2.GRADE IS NOT NULL THEN T2.GRADE ELSE T4.GRADE END AS GRADE
	,[HS Cum Flat]
	,[HS Cum Weighted]
	,[MS Cum Flat]

FROM	
	(
	SELECT 
	SIS_NUMBER
	,SCHOOL_YEAR
	,SCHOOL_NAME
	,GRADE
	,[HS Cum Flat]
	,[HS Cum Weighted]
	FROM
	(
	SELECT 
	SIS_NUMBER
	,SCHOOL_YEAR
	,SCHOOL_NAME
	,GRADE
	,[HS Cum Flat]
	,[HS Cum Weighted]
	,ROW_NUMBER() OVER (PARTITION BY [StudentSchoolYear].STUDENT_GU ORDER BY  ENTER_DATE DESC,  [HS Cum Weighted] DESC, [HS Cum Flat] DESC) AS RN
	FROM		
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		INNER JOIN
		APS.StudentEnrollmentDetails AS [StudentSchoolYear]
		ON
		STUDENT.STUDENT_GU = [StudentSchoolYear].STUDENT_GU
		LEFT OUTER JOIN
		(
		SELECT DISTINCT
			[GPA].[STUDENT_SCHOOL_YEAR_GU]
			
			,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] IN ( 'HSCF', 'HSF') THEN [GPA].[GPA] ELSE 0 END) AS [HS Cum Flat]
			,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] IN ( 'HSCW', 'HSW') THEN [GPA].[GPA] ELSE 0 END) AS [HS Cum Weighted]
			
		FROM	
			rev.[EPC_STU_GPA] AS [GPA]  
				
			INNER JOIN
			rev.[EPC_SCH_YR_GPA_TYPE_RUN] [GPA_RUN]
			ON
			[GPA].[SCHOOL_YEAR_GPA_TYPE_RUN_GU] = [GPA_RUN].[SCHOOL_YEAR_GPA_TYPE_RUN_GU]
			AND [GPA_RUN].[SCHOOL_YEAR_GRD_PRD_GU] IS NULL
			
			INNER JOIN
			rev.[EPC_GPA_DEF_TYPE] [GPA_TYPE] 
			ON 
			[GPA_RUN].[GPA_DEF_TYPE_GU] = [GPA_TYPE].[GPA_DEF_TYPE_GU]
			AND (
				[GPA_TYPE].[GPA_TYPE_NAME] = 'HS Cum Flat' 
				OR
				[GPA_TYPE].[GPA_TYPE_NAME] = 'HS Cum Weighted' 
				)
					
			INNER JOIN 
			rev.[EPC_GPA_DEF] [GPA_DEF]  
			ON 
			[GPA_TYPE].[GPA_DEF_GU] = [GPA_DEF].[GPA_DEF_GU]
			GROUP BY
			[GPA].[STUDENT_SCHOOL_YEAR_GU]
			
			)  AS [CUM_GPA]
		ON
		[StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU] = [CUM_GPA].[STUDENT_SCHOOL_YEAR_GU]

WHERE
	([HS Cum Flat] IS NOT NULL
	OR [HS Cum Weighted] IS NOT NULL)
) AS T1
WHERE
	RN = 1
) AS T2

FULL OUTER JOIN

(
SELECT 
	SIS_NUMBER
	,SCHOOL_YEAR
	,SCHOOL_NAME
	,GRADE
	,[MS Cum Flat]
FROM
(
	SELECT 
	SIS_NUMBER
	,SCHOOL_YEAR
	,SCHOOL_NAME
	,GRADE
	,[MS Cum Flat]
	,ROW_NUMBER() OVER (PARTITION BY [StudentSchoolYear].STUDENT_GU ORDER BY  ENTER_DATE DESC, [MS Cum Flat] DESC) AS RN

	FROM		
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		INNER JOIN
		APS.StudentEnrollmentDetails AS [StudentSchoolYear]
		ON
		STUDENT.STUDENT_GU = [StudentSchoolYear].STUDENT_GU
		LEFT OUTER JOIN
		(
		SELECT DISTINCT
			[GPA].[STUDENT_SCHOOL_YEAR_GU]
			
			,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] IN ('MSCF', 'MSF') THEN [GPA].[GPA] ELSE 0 END) AS [MS Cum Flat]	
		FROM	
			rev.[EPC_STU_GPA] AS [GPA]  		
			INNER JOIN
			rev.[EPC_SCH_YR_GPA_TYPE_RUN] [GPA_RUN]
			ON
			[GPA].[SCHOOL_YEAR_GPA_TYPE_RUN_GU] = [GPA_RUN].[SCHOOL_YEAR_GPA_TYPE_RUN_GU]
			AND [GPA_RUN].[SCHOOL_YEAR_GRD_PRD_GU] IS NULL
			
			INNER JOIN
			rev.[EPC_GPA_DEF_TYPE] [GPA_TYPE] 
			ON 
			[GPA_RUN].[GPA_DEF_TYPE_GU] = [GPA_TYPE].[GPA_DEF_TYPE_GU]
			AND (
				[GPA_TYPE].[GPA_TYPE_NAME] = 'MS Cum Flat'
				)
					
			INNER JOIN 
			rev.[EPC_GPA_DEF] [GPA_DEF]  
			ON 
			[GPA_TYPE].[GPA_DEF_GU] = [GPA_DEF].[GPA_DEF_GU]
			GROUP BY
			[GPA].[STUDENT_SCHOOL_YEAR_GU]
			
			)  AS [CUM_GPA]
		ON
		[StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU] = [CUM_GPA].[STUDENT_SCHOOL_YEAR_GU]

WHERE
	[MS Cum Flat] IS NOT NULL

) AS T3
	WHERE
		RN = 1
) AS T4

ON
T2.SIS_NUMBER = T4.SIS_NUMBER

) AS GETGPA
ON
BS.SIS_NUMBER = GETGPA.SIS_NUMBER


LEFT JOIN 
(
SELECT * FROM (
SELECT 
	SCHOOL_NAME
	,SCHOOL_YEAR
	,GRADE
	,SIS_NUMBER
	,ROW_NUMBER() OVER (PARTITION BY [StudentSchoolYear].STUDENT_GU ORDER BY  ENTER_DATE DESC) AS RN

	FROM		
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		INNER JOIN
		APS.StudentEnrollmentDetails AS [StudentSchoolYear]
		ON
		STUDENT.STUDENT_GU = [StudentSchoolYear].STUDENT_GU
) AS ELEMENROLL
WHERE
	RN = 1
) AS ELEM

ON
BS.SIS_NUMBER = ELEM.SIS_NUMBER


ORDER BY STU.SIS_NUMBER


/*******************************************************************************


GET ACCESS STUFF - SEPERATE GRID



********************************************************************************/


SELECT STU.SIS_NUMBER, BS.LAST_NAME, BS.FIRST_NAME, T1.TEST_NAME, T1.PERFORMANCE_LEVEL, T1.TEST_DATE, [Overall LP] AS OVERALL_LP, Scale AS SCALE
  

 FROM 
		(SELECT 

	EY2.STUDENT_GU, EXIT_REASON FROM 
	rev.EPC_STU_PGM_ELL AS EY2
	
	LEFT JOIN
	APS.LCELatestEvaluationAsOf(GETDATE()) AS LCE1
	ON
	LCE1.STUDENT_GU = EY2.STUDENT_GU

	WHERE
	EXIT_REASON = 'EY2'
	AND 
	LCE1.ADMIN_DATE > '2014-01-01'
	) AS EY2

	INNER JOIN
	rev.EPC_STU AS STU
	ON
	EY2.STUDENT_GU = STU.STUDENT_GU
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS BS
	ON
	BS.STUDENT_GU = STU.STUDENT_GU


/*******************************************************************************

GET TEST STUFF AND PIVOT
********************************************************************************/
LEFT JOIN
(
SELECT * FROM 
(
SELECT 

	   FIRST_NAME
       ,LAST_NAME
       ,SIS_NUMBER
	   ,TEST_NAME
       ,SCORE_DESCRIPTION
       ,PERFORMANCE_LEVEL
       ,TEST_SCORE
       ,CAST (ADMIN_DATE AS DATE) AS TEST_DATE
       ,ADMIN_DATE
FROM
(
SELECT 

	   PERSON.FIRST_NAME
       ,PERSON.LAST_NAME
       ,SIS_NUMBER
	   ,TEST.TEST_NAME
       ,SCORE_DESCRIPTION
       --,STU_PART.PERFORMANCE_LEVEL
	   ,VALUE_DESCRIPTION AS PERFORMANCE_LEVEL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

       INNER JOIN
       rev.REV_PERSON AS Person
       ON Person.PERSON_GU = StudentTest.STUDENT_GU

	     INNER JOIN
	   	APS.LookupTable('K12.TestInfo', 'PERFORMANCE_LEVELS') AS ACCESS
		ON
		ACCESS.VALUE_CODE = STU_PART.PERFORMANCE_LEVEL


WHERE
       TEST_NAME like '%ACCESS%'

) AS SYN
) AS GETALLTOPIVOT

PIVOT
	(
	MAX(TEST_SCORE)
	FOR SCORE_DESCRIPTION IN ([Overall LP], [Scale])
	) AS PIVOTME
) AS T1
ON
T1.SIS_NUMBER = STU.SIS_NUMBER


ORDER BY STU.SIS_NUMBER, TEST_DATE


/*******************************************************************************


GET PARCC STUFF - SEPERATE GRID



********************************************************************************/


SELECT STU.SIS_NUMBER, BS.LAST_NAME, BS.FIRST_NAME, T1.TEST_NAME, PERFORMANCE_LEVEL,T1.TEST_DATE, TEST_SCORE, SCORE_DESCRIPTION

 FROM 
(SELECT 

	EY2.STUDENT_GU, EXIT_REASON FROM 
	rev.EPC_STU_PGM_ELL AS EY2
	
	LEFT JOIN
	APS.LCELatestEvaluationAsOf(GETDATE()) AS LCE1
	ON
	LCE1.STUDENT_GU = EY2.STUDENT_GU

	WHERE
	EXIT_REASON = 'EY2'
	AND 
	LCE1.ADMIN_DATE > '2014-01-01'
	) AS EY2

	INNER JOIN
	rev.EPC_STU AS STU
	ON
	EY2.STUDENT_GU = STU.STUDENT_GU
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS BS
	ON
	BS.STUDENT_GU = STU.STUDENT_GU

/*******************************************************************************

GET TEST STUFF
********************************************************************************/
LEFT JOIN
(
SELECT * FROM 
(
SELECT 

	   FIRST_NAME
       ,LAST_NAME
       ,SIS_NUMBER
	   ,TEST_NAME
       ,SCORE_DESCRIPTION
       --,PERFORMANCE_LEVEL
	   ,PERFORMANCE_LEVEL
       ,TEST_SCORE
       ,CAST (ADMIN_DATE AS DATE) AS TEST_DATE
       ,ADMIN_DATE
FROM
(
SELECT 

	   PERSON.FIRST_NAME
       ,PERSON.LAST_NAME
       ,SIS_NUMBER
	   ,TEST.TEST_NAME
       ,SCORE_DESCRIPTION
	   --,STU_PART.PERFORMANCE_LEVEL
	   ,VALUE_DESCRIPTION AS PERFORMANCE_LEVEL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

       INNER JOIN
       rev.REV_PERSON AS Person
       ON Person.PERSON_GU = StudentTest.STUDENT_GU

	   INNER JOIN
	   	APS.LookupTable('K12.TestInfo', 'PERFORMANCE_LEVELS') AS PARCC
		ON
		PARCC.VALUE_CODE = STU_PART.PERFORMANCE_LEVEL


WHERE
       TEST_NAME like '%PARCC%'

) AS SYN
) AS GETALLTOPIVOT

) AS T1
ON
T1.SIS_NUMBER = STU.SIS_NUMBER


ORDER BY STU.SIS_NUMBER, TEST_DATE



/*******************************************************************************


GET SBA - SEPERATE GRID



********************************************************************************/


SELECT STU.SIS_NUMBER, BS.LAST_NAME, BS.FIRST_NAME, T1.TEST_NAME, PART_DESCRIPTION
, T1.PERFORMANCE_LEVEL
, T1.TEST_DATE,[Language],[Raw], [Scale], [SBA Grade Level]
  
 FROM 
		(SELECT 

	EY2.STUDENT_GU, EXIT_REASON FROM 
	rev.EPC_STU_PGM_ELL AS EY2
	
	LEFT JOIN
	APS.LCELatestEvaluationAsOf(GETDATE()) AS LCE1
	ON
	LCE1.STUDENT_GU = EY2.STUDENT_GU

	WHERE
	EXIT_REASON = 'EY2'
	AND 
	LCE1.ADMIN_DATE > '2014-01-01'
	) AS EY2

	INNER JOIN
	rev.EPC_STU AS STU
	ON
	EY2.STUDENT_GU = STU.STUDENT_GU
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS BS
	ON
	BS.STUDENT_GU = STU.STUDENT_GU


/*******************************************************************************

GET TEST STUFF AND PIVOT
********************************************************************************/
LEFT JOIN
(
SELECT * FROM 
(
SELECT 

	   FIRST_NAME
       ,LAST_NAME
       ,SIS_NUMBER
	   ,TEST_NAME
       ,SCORE_DESCRIPTION
	   ,PART_DESCRIPTION
       ,PERFORMANCE_LEVEL
       ,TEST_SCORE
       ,CAST (ADMIN_DATE AS DATE) AS TEST_DATE
       ,ADMIN_DATE
FROM
(
SELECT 

	   PERSON.FIRST_NAME
       ,PERSON.LAST_NAME
       ,SIS_NUMBER
	   ,TEST.TEST_NAME
       ,SCORE_DESCRIPTION
       ,PART_DESCRIPTION
	   ,VALUE_DESCRIPTION AS PERFORMANCE_LEVEL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

       INNER JOIN
       rev.REV_PERSON AS Person
       ON Person.PERSON_GU = StudentTest.STUDENT_GU

	     INNER JOIN
	   	APS.LookupTable('K12.TestInfo', 'PERFORMANCE_LEVELS') AS ACCESS
		ON
		ACCESS.VALUE_CODE = STU_PART.PERFORMANCE_LEVEL


WHERE
       TEST_NAME like '%SBA%'

) AS SYN
) AS GETALLTOPIVOT

PIVOT
	(
	MAX(TEST_SCORE)
	FOR SCORE_DESCRIPTION IN ([Language],[Raw], [Scale], [SBA Grade Level])
	) AS PIVOTME
) AS T1

ON
T1.SIS_NUMBER = STU.SIS_NUMBER


ORDER BY STU.SIS_NUMBER, TEST_DATE