

EXECUTE AS LOGIN='QueryFileUser'
GO

SELECT 

UNM.*
,STU.SIS_NUMBER
/*,GRADES.COURSE_ID
,GRADES.COURSE_TITLE
,GRADES.MARK
,GRADES.CREDIT
*/
,CRS.COURSE_ID AS DCM_COURSE_ID
,CRS.CREDIT AS DCM_CREDIT


,CRSHST.COURSE_ID
,CRSHST.COURSE_TITLE
,CRSHST.MARK
,CRSHST.CREDIT_COMPLETED



FROM

            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT DISTINCT STARRsID from CNM.csv'
                ) AS [UNM]


INNER JOIN 
rev.EPC_STU AS STU

ON
UNM.STARRsID = STU.STATE_STUDENT_NUMBER
/*
INNER JOIN
APS.StudentGrades AS GRADES
ON
STU.STUDENT_GU = GRADES.STUDENT_GU
AND (GRADES.ORGANIZATION_NAME LIKE ('Central%') OR
GRADES.ORGANIZATION_NAME LIKE ('University%'))
*/

INNER JOIN
rev.EPC_STU_CRS_HIS AS CRSHST
ON
STU.STUDENT_GU = CRSHST.STUDENT_GU
AND CRSHST.SCHOOL_IN_DISTRICT_GU IN ('C41B0D77-A6C0-42E0-A3FE-8A17312129CE', 'ADCACC5A-C6EA-4B8F-AFE0-910133ED1160')


INNER JOIN
rev.EPC_CRS AS CRS
ON
CRSHST.COURSE_ID = CRS.COURSE_ID
				
      REVERT
GO