


EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT 
	Sheet3.*
	,LAST_NAME
	,FIRST_NAME
	,T3.GRADE
	,T3.ORGANIZATION_NAME
	,T3.ENTER_DATE
	,T3.LEAVE_DATE	

FROM

            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT * from Sheet3.csv'
                ) AS Sheet3

INNER JOIN
rev.EPC_STU AS STU
ON
Sheet3.[Student ID] = STU.SIS_NUMBER

INNER JOIN
rev.REV_PERSON AS PERS
ON
PERS.PERSON_GU = STU.STUDENT_GU

INNER JOIN
(SELECT * FROM
(SELECT * FROM
(
SELECT 
	ORGANIZATION_NAME
	,SIS_NUMBER
	,ENTER_DATE
	, LEAVE_DATE
	,YEARS.SCHOOL_YEAR
	,LU.VALUE_DESCRIPTION AS GRADE
	,ROW_NUMBER() OVER (PARTITION BY STUDENT.STUDENT_GU ORDER BY ENTER_DATE DESC) AS RN
 FROM
rev.EPC_STU_YR AS SOR
INNER JOIN
rev.EPC_STU AS STUDENT
ON
SOR.STUDENT_GU = STUDENT.STUDENT_GU
INNER JOIN
rev.EPC_STU_SCH_YR AS SSY
ON
SSY.STUDENT_SCHOOL_YEAR_GU = SOR.STU_SCHOOL_YEAR_GU

INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = SSY.ORGANIZATION_YEAR_GU

INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

INNER JOIN
rev.REV_YEAR AS YEARS
ON
YEARS.YEAR_GU = ORGYR.YEAR_GU

INNER JOIN
APS.LookupTable('K12', 'Grade') AS LU
ON
LU.VALUE_CODE = SSY.GRADE

WHERE
SCHOOL_YEAR < 2015
AND YEARS.EXTENSION != 'S'
) AS T1
WHERE
RN = 1
)AS T2) AS T3

ON
T3.SIS_NUMBER = Sheet3.[Student ID]

ORDER BY Sheet3.[Student ID]

      REVERT
GO