

SELECT 
	SCHOOL.SCHOOL_CODE
	,SCH.ORGANIZATION_NAME
	,SIS_NUMBER
	,VALUE_DESCRIPTION AS GRADE
	,GPA
	,YEARS.SCHOOL_YEAR
	,EXTENSION
	,CODES.GPA_TYPE_NAME

 FROM
rev.EPC_STU_GPA AS GPA
INNER JOIN
rev.EPC_STU_SCH_YR AS SSY
ON
GPA.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = SSY.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_YEAR AS YEARS
ON
YEARS.YEAR_GU = ORGYR.YEAR_GU
INNER JOIN
rev.EPC_STU AS STU
ON
SSY.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
rev.EPC_SCH_YR_GPA_TYPE_RUN AS GPATYPE
ON
GPA.SCHOOL_YEAR_GPA_TYPE_RUN_GU = GPATYPE.SCHOOL_YEAR_GPA_TYPE_RUN_GU
INNER JOIN
rev.EPC_GPA_DEF_TYPE AS CODES
ON
GPATYPE.GPA_DEF_TYPE_GU = CODES.GPA_DEF_TYPE_GU
INNER JOIN
rev.REV_ORGANIZATION AS SCH
ON
ORGYR.ORGANIZATION_GU = SCH.ORGANIZATION_GU
INNER JOIN
rev.EPC_SCH AS SCHOOL
ON
SCH.ORGANIZATION_GU = SCHOOL.ORGANIZATION_GU
INNER JOIN
APS.LookupTable ('K12','Grade') AS GRADE
ON
GRADE.VALUE_CODE = SSY.GRADE

WHERE
--SSY.STUDENT_GU = 'A33C78F4-2C03-4434-8113-6280F7802499'

 SCHOOL_YEAR = '2013' AND EXTENSION = 'R'
AND SCHOOL_CODE LIKE '5%'
--AND SCHOOL_CODE != '512'
--AND SCHOOL_CODE < '591'
--AND GPA > '0.0'

ORDER BY 
GPA ASC