
SELECT 
	DURATION
	,COUNT(*) AS [COUNT]
 FROM 

(
SELECT 
TCH.*
,EMP.LAST_NAME
,EMP.FIRST_NAME
,EEO_CLASS
,SEX
,CAST(DATE_HIRED AS DATE) AS DATE_HIRED
, CASE WHEN DATE_HIRED > '2015-03-22' THEN '1 YEAR' 
		WHEN DATE_HIRED BETWEEN '2013-03-22' AND '2015-03-22' THEN '1-3 YEARS'
		WHEN DATE_HIRED BETWEEN '2008-03-22'AND '2011-03-22'  THEN '5-10 YEARS'
		WHEN DATE_HIRED < '2008-03-22' THEN '10+ YEARS'
ELSE '' 
END AS DURATION


FROM

            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\180-SMAXODS-01\SqlWorkingFiles\;', 
                  'SELECT * from teachers.csv'
                ) AS [TCH]


LEFT JOIN
Employee AS EMP
ON
TCH.MAIL = EMP.EMAIL_ADDRESS

LEFT JOIN
Paemployee AS PEMP
ON
EMP.EMPLOYEE = PEMP.EMPLOYEE

--ORDER BY EMP.EMPLOYEE

) AS T1
GROUP BY 
DURATION





