
BEGIN TRANSACTION

UPDATE rev.EPC_SCH_YR_OPT 
SET EXCLUDE_FROM_OLR = 'Y'

FROM 
(
SELECT EXCLUDE_FROM_OLR, ORGANIZATION_NAME, SCHOOL_YEAR, EXTENSION, OPT.ORGANIZATION_YEAR_GU FROM 
rev.EPC_SCH_YR_OPT AS OPT
INNER JOIN 
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
OPT.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN 
REV.REV_YEAR AS YRS
ON
ORGYR.YEAR_GU = YRS.YEAR_GU
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

WHERE
SCHOOL_YEAR = '2017'
AND EXTENSION = 'R'
AND EXCLUDE_FROM_OLR = 'N'
) AS T1

WHERE rev.EPC_SCH_YR_OPT.ORGANIZATION_YEAR_GU = T1.ORGANIZATION_YEAR_GU

ROLLBACK

