USE ST_Production
GO

select 
	t1.*
	,PERSON.FIRST_NAME
	,PERSON.LAST_NAME
	,USERS.LOGIN_NAME
	from (

SELECT * FROM (
SELECT 
	BADGE_NUM
	,ROW_NUMBER () OVER (PARTITION BY BADGE_NUM ORDER BY BADGE_NUM) AS RN
	,staff.STAFF_GU
FROM
	rev.EPC_STAFF  AS STAFF
	
	) AS ALLSTAFF
WHERE
	RN > 1
	) as t1

INNER JOIN
	rev.REV_PERSON AS PERSON
	ON
	t1.STAFF_GU = PERSON.PERSON_GU
	LEFT JOIN
	rev.REV_USER AS USERS
	ON
	USERS.USER_GU = t1.STAFF_GU