
SELECT DISTINCT SIS_NUMBER, STATE_STUDENT_NUMBER, PROG.VALUE_DESCRIPTION AS PROGRAM_DESCRIPTION, PROGRAM_INTENSITY AS PROGRAM_HOURS 
, ENTER_DATE, EXIT_DATE
FROM 
(SELECT
	STUDENT_GU
	,PROGRAM_CODE
	,PROGRAM_INTENSITY
	,ENTER_DATE
	,EXIT_DATE
FROM
	(
	SELECT
		STUDENT_GU
		,PROGRAM_CODE
		,PROGRAM_INTENSITY
		,ENTER_DATE
		,EXIT_DATE
		,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY ENTER_DATE DESC) AS RN
	FROM
		REV.EPC_STU_PGM_ELL_BEP
	WHERE
		ENTER_DATE >= '2015-08-13'
	) AS RowedBEP
WHERE
	RN = 1

) AS BIL
INNER JOIN 
rev.EPC_STU AS STU
ON
STU.STUDENT_GU = BIL.STUDENT_GU
LEFT JOIN 
APS.LookupTable ('K12.ProgramInfo','BEP_PROGRAM_CODE') AS PROG
ON
BIL.PROGRAM_CODE = PROG.VALUE_CODE

ORDER BY SIS_NUMBER

