

EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT 
	
	FLAGS.*
	,CASE WHEN H IS NOT NULL THEN 'H' ELSE '' END AS [HONORS IND]
	,CASE WHEN COURSE.AP_INDICATOR = 'Y' THEN 'AP' ELSE'' END AS [AP IND]
	,CASE WHEN CTE.COURSEID IS NOT NULL THEN 'CTE' ELSE '' END AS [CTE IND]
	,CASE WHEN GFT IS NOT NULL THEN 'GFT' ELSE '' END AS [GIFTED IND]
	,'' AS [REMEDIAL IND]
	,'' AS [BASIC IND]
	,CASE WHEN A IS NOT NULL THEN 'A' ELSE '' END AS [SPED IND]
	,CASE WHEN COURSE.IB_INDICATOR = 'Y'THEN 'IB' ELSE '' END AS [IB IND]
	,CASE WHEN COURSE.DEPARTMENT = 'Ele' THEN 'E' ELSE '' END AS [ELECTIVE IND] 
	,CASE WHEN L IS NOT NULL THEN 'L' ELSE '' END AS [LAB IND]
	, '' AS [ADVANCED IND]

FROM

            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT * from 40DCOURSEINSTRUCT.csv'
                ) AS [FLAGS]

INNER JOIN
rev.EPC_STAFF AS STAFF
ON
FLAGS.[APS instr] = STAFF.BADGE_NUM

INNER JOIN
	APS.SectionsAndAllStaffAssignedAsOf(GETDATE()) AS SECTIONS
ON
SECTIONS.SECTION_ID = FLAGS.[APS section]
AND STAFF.STAFF_GU = SECTIONS.STAFF_GU

INNER JOIN
rev.EPC_CRS AS COURSE
ON
COURSE.COURSE_ID = FLAGS.[APS course]

INNER JOIN
rev.EPC_STAFF_SCH_YR AS StaffYear
ON
StaffYear.STAFF_SCHOOL_YEAR_GU = SECTIONS.STAFF_SCHOOL_YEAR_GU

INNER JOIN 
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
StaffYear.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU

INNER JOIN
rev.EPC_SCH AS SCHOOL
ON
ORGYR.ORGANIZATION_GU = SCHOOL.ORGANIZATION_GU
AND SCHOOL.SCHOOL_CODE = FLAGS.[LOCATION CODE]


LEFT JOIN
(
SELECT * FROM 
(
SELECT
	[COURSE_GU]
	,[COURSE_LEVEL]
FROM
	rev.EPC_CRS_LEVEL_LST 
) [LIST]
		PIVOT (MIN([COURSE_LEVEL]) FOR [COURSE_LEVEL] IN ([N],[H],[A],[D],[L],[G],[GFT],[C]) ) AS [LIST_PIVOT]
	
)AS [COURSE_LIST]

ON
[COURSE_LIST].COURSE_GU = COURSE.COURSE_GU



LEFT JOIN 
	      OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT * from CTECOURSES.csv'
                ) AS CTE

CTE.COURSEID = COURSE.COURSE_ID



ORDER BY [APS instr]

      REVERT
GO