
SELECT SIS_NUMBER, SCHOOL_YEAR, EXTENSION, SCHOOL_CODE, SCHOOL_NAME, GRADE, SUMMER_WITHDRAWL_CODE, SUMMER_WITHDRAWL_DATE, ENTER_DATE, ENTER_DESCRIPTION, LEAVE_CODE, LEAVE_DESCRIPTION 
FROM 
	APS.STUDENTENROLLMENTDETAILS
WHERE
SCHOOL_YEAR = '2016'
AND SUMMER_WITHDRAWL_CODE = 'WG'



