

--PULL BEP
SELECT * FROM 
	[046-WS02].[db_STARS_History].dbo.PROGRAMS_FACT
WHERE
	[DISTRICT CODE] = '001'
	AND SY = '2015'
	AND [Field6] = '2015-06-01'
	AND [Field5] = 'BEP'
	
-- PULL ALL ELL, AND EXIT YEAR
SELECT 
	[STUDENT ID], [LOCATION CODE], [Period], [ALTERNATE STUDENT ID], [ENGLISH PROFICIENCY]  FROM 
	[046-WS02].[db_STARS_History].dbo.STUD_SNAPSHOT
WHERE
	[DISTRICT CODE] = '001'
	AND [Period] = '2015-06-01'

