
--BEGIN TRANSACTION

--DELETE rev.EPC_STU_PGM_ELL_HIS

--UPDATE rev.EPC_STU_PGM_ELL_HIS
--SET EXIT_REASON = NULL, EXIT_DATE = NULL 


SELECT GU, BADEXITS.SIS_NUMBER, ENTRY_DATE, EXIT_DATE, EXIT_REASON, MAX_SCORE,
	ROW_NUMBER() OVER (PARTITION BY BADEXITS.SIS_NUMBER ORDER BY ENTRY_DATE, EXIT_DATE) AS RN 
 FROM 

(
SELECT SIS_NUMBER, ELL2.PROGRAM_CODE, ELL2.ENTRY_DATE, ELL2.EXIT_DATE, ELL2.EXIT_REASON, ELL2.STU_PGM_ELL_HIS_GU AS GU
,ROW_NUMBER() OVER (PARTITION BY SIS_NUMBER ORDER BY ELL2.EXIT_DATE DESC) AS RN 

FROM 

(
SELECT DISTINCT SIS_NUMBER, STUDENT_GU FROM
(
SELECT 
	PROGRAM_CODE, ENTRY_DATE, EXIT_DATE, EXIT_REASON, SIS_NUMBER, ELL.STUDENT_GU,
	ROW_NUMBER() OVER (PARTITION BY SIS_NUMBER ORDER BY EXIT_DATE DESC) AS RN
 FROM
	rev.EPC_STU_PGM_ELL_HIS AS ELL
	INNER JOIN
	rev.EPC_STU AS STU
	ON
	ELL.STUDENT_GU = STU.STUDENT_GU

)
AS MORETHANONE

WHERE
	RN > 1
) AS GETONE


--GET ALL THE OTHER RECORDS BACK--------------------------------------------------------------------------------------------
INNER JOIN 
rev.EPC_STU_PGM_ELL_HIS AS ELL2
ON
GETONE.STUDENT_GU= ELL2.STUDENT_GU

) AS BADEXITS


--GET SCORE------------------------------------------------------------------------------------------------------------------
INNER JOIN 
(SELECT
	SIS_NUMBER
	,MAX(NEWSCORE) AS MAX_SCORE

FROM
	(
	SELECT
		SIS_NUMBER
		,TestDefinition.TEST_GU
		,TestDefinition.TEST_NAME
		,StudentTest.STUDENT_GU
		,StudentTest.STUDENT_TEST_GU
		,StudentTest.ADMIN_DATE
		,StudentTest.Organization_GU
		,StudentTest.GRADE
		,StudentTestPart.PERFORMANCE_LEVEL
		,CASE WHEN StudentTestPartScore.TEST_SCORE IN ('LEP', 'LEPE', 'LEPA', 'LEPB', 'LEPC', 'LEPD', 'NEP') THEN '1'
			  WHEN StudentTestPartScore.TEST_SCORE LIKE 'FEP%' THEN '5'
			  ELSE StudentTestPartScore.TEST_SCORE
		END AS NEWSCORE

		,COALESCE(TestLevels.IS_ELL,-1) AS IS_ELL
		,ROW_NUMBER() OVER (PARTITION BY StudentTest.STUDENT_GU ORDER BY ADMIN_DATE DESC) AS RN
	FROM
		rev.EPC_TEST AS TestDefinition
		INNER JOIN
		rev.EPC_STU_TEST AS StudentTest
		ON
		TestDefinition.TEST_GU = StudentTest.TEST_GU

		--assuming one part per ELL Test only
		INNER JOIN
		rev.EPC_STU_TEST_PART AS StudentTestPart
		ON
		StudentTest.STUDENT_TEST_GU = StudentTestPart.STUDENT_TEST_GU
	
		 --Shouldn't need this part as we only look at performance levels
		INNER JOIN
		rev.EPC_STU_TEST_PART_SCORE AS StudentTestPartScore
		ON
		StudentTestPart.STU_TEST_PART_GU = StudentTestPartScore.STU_TEST_PART_GU

	LEFT JOIN
	rev.EPC_TEST_SCORE_TYPE AS SCORET
	ON
	SCORET.TEST_GU = StudentTest.TEST_GU
	AND StudentTestPartScore.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

	LEFT JOIN
	rev.EPC_TEST_DEF_SCORE AS SCORETDEF
	ON
	SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU
	

		LEFT JOIN
		rev.UD_ELL_TEST_ELIGIBILITY AS TestLevels
		ON
		StudentTestPart.PERFORMANCE_LEVEL = TestLevels.LEVEL
		AND TestDefinition.TEST_NAME = TestLevels.TEST

		INNER JOIN
		rev.EPC_STU AS STU
		ON
		StudentTest.STUDENT_GU = STU.STUDENT_GU

	WHERE
		TestDefinition.TEST_TYPE = 'ALTRN' -- ALL ELL tests
		AND StudentTest.ADMIN_DATE <= GETDATE()
		AND StudentTestPart.PERFORMANCE_LEVEL != 'INCOM'  -- If a test has an incomplete performance level, do not use it
		AND SCORE_DESCRIPTION = 'Overall LP'
		
	) AS ELLTests


	GROUP BY SIS_NUMBER

)AS TESTSTUFF

ON
TESTSTUFF.SIS_NUMBER = BADEXITS.SIS_NUMBER

--WHERE
	--MAX_SCORE > '5'
	
	--AND BADEXITS.EXIT_DATE IS NOT NULL AND BADEXITS.EXIT_REASON != 'EY-'

--RN > 1

--AND rev.EPC_STU_PGM_ELL_HIS.STU_PGM_ELL_HIS_GU = GU

--COMMIT