

SELECT VUES.*  FROM 
rev.REV_USER_NON_SYS AS VUES
INNER JOIN
rev.EPC_PARENT AS PARENT
ON
VUES.PERSON_GU = PARENT.PARENT_GU
WHERE 
	USER_ID IS NOT NULL
	AND USER_ID < 'a'

	ORDER BY USER_ID 