

SELECT 
	SIS_NUMBER, EXIT_DATE, EXIT_REASON, LU.VALUE_DESCRIPTION AS EXIT_DESCRIPTION, TEST_NAME, PERFORMANCE_LEVEL, ADMIN_DATE
FROM 
rev.EPC_STU_PGM_ELL AS ELL
INNER JOIN
rev.EPC_STU AS STU
ON
ELL.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
	APS.LOOKUPTABLE ('K12.ProgramInfo', 'ELL_EXIT_REASON') AS LU
ON
LU.VALUE_CODE = ELL.EXIT_REASON

LEFT JOIN
APS.LCELatestEvaluationAsOf(GETDATE()) AS LCE
ON
LCE.STUDENT_GU = ELL.STUDENT_GU

WHERE 

EXIT_REASON = 'EY1'

ORDER BY EXIT_REASON, EXIT_DATE