
SELECT 
	CLUSTERNAME.ORGANIZATION_NAME AS CLUSTER_NAME, ORG.ORGANIZATION_NAME, SIS_NUMBER, PHL.DATE_ASSIGNED AS PHL_DATE_ASSIGNED
	--COUNT(PHL.STUDENT_GU) AS PHLOTE 
 FROM 

APS.PrimaryEnrollmentsAsOf('2015-05-22')AS PE
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
PE.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN
rev.EPC_SCH AS SCHOOL
ON
SCHOOL.ORGANIZATION_GU = ORG.ORGANIZATION_GU

------------------------------------------------
INNER JOIN
rev.EPC_SCH AS CLUSTER
ON
SCHOOL.ALT_FUNDING_SCHOOL_CODE = CLUSTER.SCHOOL_CODE

INNER JOIN
rev.REV_ORGANIZATION AS CLUSTERNAME
ON
CLUSTER.ORGANIZATION_GU = CLUSTERNAME.ORGANIZATION_GU
-----------------------------------------------------------

INNER JOIN
APS.PHLOTEAsOf('2015-05-22') AS PHL
ON
PHL.STUDENT_GU = PE.STUDENT_GU

INNER JOIN
rev.EPC_STU AS STU
ON
PHL.STUDENT_GU = STU.STUDENT_GU

WHERE
CLUSTER.ALT_FUNDING_SCHOOL_CODE = '570'
AND
	PE.GRADE NOT IN  ('050', '070', '090', '230', '240', '250', '260', '270', '280', '290', '300')
