

select * from rev.EPC_STU_SCH_YR_OEN_MOD
Where STUDENT_SCHOOL_YEAR_GU in (
select om.STUDENT_SCHOOL_YEAR_GU from rev.EPC_STU_SCH_YR_OEN_MOD om join rev.EPC_STU_SCH_YR ssy on ssy.STUDENT_SCHOOL_YEAR_GU = om.STUDENT_SCHOOL_YEAR_GU join rev.EPC_STU s on s.STUDENT_GU = ssy.STUDENT_GU join rev.REV_ORGANIZATION_YEAR oy on oy.ORGANIZATION_YEAR_GU = ssy.ORGANIZATION_YEAR_GU join rev.REV_ORGANIZATION o on o.ORGANIZATION_GU = oy.ORGANIZATION_GU where s.SIS_NUMBER = '1926878')
