

EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT * FROM 
(
SELECT 
	SIS_NUMBER
	,T1.IDNBR, T1.GRADE AS APP_GRADE, T1.SCHOOL
	,ENR.SCHOOL_CODE
	,ENR.GRADE AS ENR_GRADE
	,LU1.VALUE_DESCRIPTION AS NEXT_GRADE
	,NXTSCH.ORGANIZATION_NAME AS NEXT_SCH
	,SCH.SCHOOL_CODE AS NEXT_SCH_CODE

	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from DOUBLECHECK.csv'
                ) AS [T1]

INNER JOIN 
REV.EPC_STU AS STU
ON
T1.IDNBR = STU.SIS_NUMBER

INNER JOIN 
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS ENR
ON
STU.STUDENT_GU = ENR.STUDENT_GU

INNER JOIN 
rev.EPC_STU_SCH_YR AS SSY
ON
SSY.STUDENT_SCHOOL_YEAR_GU = ENR.STUDENT_SCHOOL_YEAR_GU

INNER JOIN 
APS.LookupTable('K12', 'GRADE') AS LU1
ON
LU1.VALUE_CODE = SSY.NEXT_GRADE_LEVEL

INNER JOIN 
rev.REV_ORGANIZATION AS NXTSCH
ON
SSY.NEXT_SCHOOL_GU = NXTSCH.ORGANIZATION_GU

INNER JOIN 
rev.EPC_SCH AS SCH
ON
SCH.ORGANIZATION_GU = NXTSCH.ORGANIZATION_GU

) AS T1

WHERE
T1.SCHOOL != NEXT_SCH_CODE

	
REVERT
GO