SELECT 

	CLUSTER
	,SCHOOL
	,SCH.SCHOOL_CODE
	,CASE WHEN SIS_NUMBER IS NULL THEN 0 ELSE SIS_NUMBER END AS [Current Quarter 5/22/2015 Needs EPT]

 FROM


----------------------------------------------------------------------------------------------
--YEAR AGO TABLE
--NO HLS AND NO TEST

           dbo.[LCE_NO_HLS] AS CLUSTER

			LEFT JOIN
			rev.REV_ORGANIZATION AS ORG
			ON
			ORG.ORGANIZATION_NAME = CLUSTER.SCHOOL

------------------------------------------------------------------------------------------
--STUDENTS THAT HAD NO HLS ON THE LAST DAY
LEFT JOIN
(
SELECT ORG.ORGANIZATION_GU, COUNT(*) AS [Current Quarter 5/22/2015 no HLS] 

FROM 
	APS.PrimaryEnrollmentsAsOf('2015-05-22') AS PRIM
	LEFT JOIN
	(SELECT DISTINCT STUDENT_GU FROM rev.UD_HLS_HISTORY)AS NOHLS
	ON
	PRIM.STUDENT_GU = NOHLS.STUDENT_GU
	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	ORGYR.ORGANIZATION_YEAR_GU = PRIM.ORGANIZATION_YEAR_GU
	INNER JOIN
	rev.REV_ORGANIZATION AS ORG
	ON
	ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

	WHERE
	NOHLS.STUDENT_GU IS NULL
	AND PRIM.GRADE NOT IN  ('050', '070', '090', '230', '240', '250', '260', '270', '280', '290', '300')

	GROUP BY ORG.ORGANIZATION_GU
) AS T4

ON
T4.ORGANIZATION_GU = ORG.ORGANIZATION_GU

LEFT JOIN
(
SELECT 
				SchoolName
				--,COUNT (*) AS [Current Quarter 5/22/2014]
				,SIS_NUMBER
			 FROM 
			APS.LCEStudentsNeedingTestingAsOf('2015-05-22') AS LCE
			INNER JOIN
			rev.EPC_STU AS STU
			ON
			LCE.STUDENT_GU = STU.STUDENT_GU


			--GROUP BY 
				--SchoolName
			) AS T1

			ON 
			T1.SchoolName = ORG.ORGANIZATION_NAME

			LEFT JOIN
			rev.EPC_SCH AS SCH
			ON
			SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU