SELECT 
	STRT.STREET_GU, GRD.GRID_CODE, STREET_LOW_ADDRESS, STREET_NAME, LU.VALUE_DESCRIPTION AS STREET_TYPE, STREET_POST_DIRECTION, CITY, STATE, ZIP_5
 FROM 
rev.EPC_STREET AS STRT
INNER JOIN 
rev.EPC_GRID AS GRD
ON
STRT.GRID_GU = GRD.GRID_GU
AND GRD.SCHOOL_YEAR = STRT.SCHOOL_YEAR
LEFT JOIN 
	 [APS].[LookupTable]('K12.AddressInfo','STREET_TYPE') AS LU
	 ON
	 LU.VALUE_CODE = STRT.[STREET_TYPE] 
WHERE
STRT.SCHOOL_YEAR = 2016
