
SELECT CSVFILE.*, EMP.EMPLOYEE, EMP.FICA_NBR, EMP.EMAIL_ADDRESS,PAE.BIRTHDATE 

FROM 
	OPENROWSET ('MSDASQL', 'Driver={Microsoft Access Text Driver (*.txt, *.csv)};DBQ=E:\SQLWorkingFiles;', 'SELECT * from "KINDER.csv"')
		AS CSVFILE
	LEFT JOIN
	Employee AS EMP
	ON
	CSVFILE.StaffAltID = EMP.EMPLOYEE
	LEFT JOIN
	Paemployee AS PAE
	ON
	EMP.EMPLOYEE = PAE.EMPLOYEE

ORDER BY EMP.EMPLOYEE