
EXECUTE AS LOGIN='QueryFileUser'
GO

SELECT 
	T1.*, HIST.COURSE_ID, MARK, HIST.TERM_CODE, CREDIT_COMPLETED, SCHOOL_YEAR
	,SCH.COURSE_ENTER_DATE, SCH.COURSE_LEAVE_DATE	

	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from MISSING.csv'
                ) AS [T1]

INNER JOIN 
rev.EPC_STU AS STU
ON
STU.STATE_STUDENT_NUMBER = T1.[Student_ID]

LEFT JOIN 
rev.EPC_STU_CRS_HIS AS HIST
ON
STU.STUDENT_GU = HIST.STUDENT_GU
AND HIST.COURSE_ID = [APS course]

LEFT JOIN 
APS.StudentScheduleDetails AS SCH
ON
SCH.COURSE_ID = T1.[APS course]
--AND SCH.SECTION_ID = HIST.SECTION_ID
AND SCH.STUDENT_GU = STU.STUDENT_GU
AND SCH.YEAR_GU = 'BCFE2270-A461-4260-BA2B-0087CB8EC26A'
	
ORDER BY HIST.STUDENT_GU

REVERT
GO