

/*
			--NOTE - SCHOOL_YEAR IS STARTING YEAR 

			2002-2003	3D95815E-93DB-4E7A-9741-4252AB7D1DAA
			2003-2004	A1A45208-69FC-4E58-99B3-7501E9108D70
			2004-2005	F4F41066-7955-45DF-AD43-24A1462BFDAD
			2005-2006	BE3706A7-1239-4DAE-A038-F9A949DAA041
			2006-2007	CC1DCB76-576C-4414-B4BA-323A26EC8EBE
			2007-2008	48ADBFD4-1987-4E7C-9C22-6FD91E8FE424
			2008-2009	94A5BA26-69AD-4ADB-80E0-7FEDB7E686C9
			2009-2010	E5D120A6-6A1C-4C42-B1F0-4ADB36DE27EF
			2010-2011	87F1A309-F058-43E4-B55B-EF9AE4602639
			2011-2012	3732B795-5856-430E-996D-B75E6475EC32
			2012-2013	9864A8F3-6130-4F95-86D6-860A517D38D1
			2013-2014	1E61EA89-3410-49F8-909B-1B749957EDDA
			2014-2015	26F066A3-ABFC-4EDB-B397-43412EDABC8B
			2015-2016	BCFE2270-A461-4260-BA2B-0087CB8EC26A
			2016-2017	F7D112F7-354D-4630-A4BC-65F586BA42EC
			2017-2018   A3F9F1FB-4706-49AA-B3A3-21F153966191
			*/



 --THIS UNPIVOTS THE 5 RECORDS INTO MANY ROWS 
SELECT SIS_NUMBER, STATE_STUDENT_NUMBER,DATES, DATES2
FROM
(
SELECT	SIS_NUMBER, STATE_STUDENT_NUMBER
,CAST( ENTER_ELL_DATE AS VARCHAR) AS ENTER_ELL_DATE
,CAST( CLOSE_OUT_ELL_DATE AS VARCHAR) AS CLOSE_OUT_ELL_DATE
,CAST( ENTER_DATE_FOR_EXIT1 AS VARCHAR) AS ENTER_DATE_FOR_EXIT1
,CAST( EXIT_DATE_FOR_EXIT1 AS VARCHAR) AS EXIT_DATE_FOR_EXIT1
,CAST( ENTER_DATE_FOR_EXIT2 AS VARCHAR) AS ENTER_DATE_FOR_EXIT2
,CAST( EXIT_DATE_FOR_EXIT2 AS VARCHAR) AS EXIT_DATE_FOR_EXIT2
,CAST( ENTER_DATE_FOR_EXIT3 AS VARCHAR) AS ENTER_DATE_FOR_EXIT3
,CAST( EXIT_DATE_FOR_EXIT3 AS VARCHAR) AS EXIT_DATE_FOR_EXIT3
,CAST( ENTER_DATE_FOR_EXIT4 AS VARCHAR) AS ENTER_DATE_FOR_EXIT4
,CAST( EXIT_DATE_FOR_EXIT4 AS VARCHAR) AS EXIT_DATE_FOR_EXIT4
,CAST( ENTER_DATE_FOR_EXIT5 AS VARCHAR) AS ENTER_DATE_FOR_EXIT5
,CAST( EXIT_DATE_FOR_EXIT5 AS VARCHAR) AS EXIT_DATE_FOR_EXIT5 

 FROM (

-- THIS WHOLE THING PULLS ONE RECORD PER STUDENT WITH THEIR 5 EXITS

SELECT 
	
	SIS_NUMBER, STATE_STUDENT_NUMBER

	,MAX(CASE WHEN [ENTER] = 'ELL' THEN CAST(CAST(FIRSTTEST_ADMIN_DATE AS DATE) AS VARCHAR) ELSE NULL END) AS ENTER_ELL_DATE
	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 1 THEN CAST(CAST(LATEST_ADMIN_DATE AS DATE) AS VARCHAR) ELSE NULL END) AS CLOSE_OUT_ELL_DATE
	
	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 1 THEN CAST([EXIT] AS VARCHAR) + '-07-01' END) AS ENTER_DATE_FOR_EXIT1
	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 1 THEN CAST([EXIT] + 1 AS VARCHAR) + '-06-30' END) AS EXIT_DATE_FOR_EXIT1

	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 2 THEN CAST([EXIT] AS VARCHAR) + '-07-01' END) AS ENTER_DATE_FOR_EXIT2
	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 2 THEN CAST([EXIT] + 1 AS VARCHAR) + '-06-30' END) AS EXIT_DATE_FOR_EXIT2

	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 3 THEN CAST([EXIT] AS VARCHAR) + '-07-01' END) AS ENTER_DATE_FOR_EXIT3
	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 3 THEN CAST([EXIT] + 1 AS VARCHAR) + '-06-30' END) AS EXIT_DATE_FOR_EXIT3

	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 4 THEN CAST([EXIT] AS VARCHAR) + '-07-01' END) AS ENTER_DATE_FOR_EXIT4
	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 4 THEN CAST([EXIT] + 1 AS VARCHAR) + '-06-30' END) AS EXIT_DATE_FOR_EXIT4

	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 5 THEN CAST([EXIT] AS VARCHAR) + '-07-01' END) AS ENTER_DATE_FOR_EXIT5
	,MAX(CASE WHEN [EXIT] != 9999 AND RN = 5 THEN CAST([EXIT] + 1 AS VARCHAR) + '-06-30' END) AS EXIT_DATE_FOR_EXIT5

FROM (
SELECT 	
	ROW_NUMBER() OVER (PARTITION BY SIS_NUMBER ORDER BY [EXIT]) AS RN
	,*
 FROM(

		--THIS SELECT PUTS ALL THE UNIONS TOGETHER
		--UNIONS ARE USED TO "UNPIVOT" DATA
		SELECT 
			* 
		FROM
		(
			
			/*************************************************************************************************************************************************
			
			--IN THE SUMMER ADD THE NEXT SCHOOL YEAR, CUT AND PASTE ENTIRE SELECT FOR EXISTING YEAR TO ADD TO THE UNIONS BELOW
			-- THIS IS CURRENTLY 2017-2018

			**************************************************************************************************************************************************/
			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2017].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20170701' THEN 2017 ELSE 9999 END AS [EXIT]
					,CASE WHEN [2017].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2016' AND '07-01-2017' THEN 'ELL' ELSE'0'END AS [ENTER]
					,CASE WHEN [2017].STUDENT_GU IS NOT NULL THEN '2017' ELSE '0' END AS [ENROLL]
			
			FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('A3F9F1FB-4706-49AA-B3A3-21F153966191') AS [2017]
			ON
			STU.STUDENT_GU = [2017].STUDENT_GU

			

) AS REC1

			/*************************************************************************************************************************************************
			--2016-2017
			**************************************************************************************************************************************************/

			UNION ALL
			
			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2016].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20160701' THEN 2016 ELSE 9999 END AS [2016_EXIT]
					,CASE WHEN [2016].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2015' AND '07-01-2016' THEN 'ELL' ELSE'0'END AS [2016_ENTER]
					,CASE WHEN [2016].STUDENT_GU IS NOT NULL THEN '2016' ELSE '0' END AS [2016_ENROLL]
						

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('F7D112F7-354D-4630-A4BC-65F586BA42EC') AS [2016]
			ON
			STU.STUDENT_GU = [2016].STUDENT_GU

		

			/*************************************************************************************************************************************************
			--2015-2016
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2015].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20150701' THEN 2015 ELSE 9999 END AS [2015_EXIT]
					,CASE WHEN [2015].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2014' AND '07-01-2015' THEN 'ELL' ELSE'0'END AS [2015_ENTER]
					,CASE WHEN [2015].STUDENT_GU IS NOT NULL THEN '2015' ELSE '0' END AS [2015_ENROLL]
						

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('BCFE2270-A461-4260-BA2B-0087CB8EC26A') AS [2015]
			ON
			STU.STUDENT_GU = [2015].STUDENT_GU

			

			/*************************************************************************************************************************************************
			--2014-2015
			**************************************************************************************************************************************************/

			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2014].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20140701' THEN 2014 ELSE 9999 END AS [2014_EXIT]
					,CASE WHEN [2014].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2013' AND '07-01-2014' THEN 'ELL' ELSE'0'END AS [2014_ENTER]
					,CASE WHEN [2014].STUDENT_GU IS NOT NULL THEN '2014' ELSE '0' END AS [2014_ENROLL]
						

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('26F066A3-ABFC-4EDB-B397-43412EDABC8B') AS [2014]
			ON
			STU.STUDENT_GU = [2014].STUDENT_GU

		


			/*************************************************************************************************************************************************
			--2013-2014
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2013].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20130701' THEN 2013 ELSE 9999 END AS [2013_EXIT]
					,CASE WHEN [2013].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2012' AND '07-01-2013' THEN 'ELL' ELSE'0'END AS [2013_ENTER]
					,CASE WHEN [2013].STUDENT_GU IS NOT NULL THEN '2013' ELSE '0' END AS [2013_ENROLL]
						

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('1E61EA89-3410-49F8-909B-1B749957EDDA') AS [2013]
			ON
			STU.STUDENT_GU = [2013].STUDENT_GU

			

			/*************************************************************************************************************************************************
			--2012-2013
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2012].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20120701' THEN 2012 ELSE 9999 END AS [2012_EXIT]
					,CASE WHEN [2012].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2011' AND '07-01-2012' THEN 'ELL' ELSE'0'END AS [2012_ENTER]
					,CASE WHEN [2012].STUDENT_GU IS NOT NULL THEN '2012' ELSE '0' END AS [2012_ENROLL]
						

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('9864A8F3-6130-4F95-86D6-860A517D38D1') AS [2012]
			ON
			STU.STUDENT_GU = [2012].STUDENT_GU

			

			/*************************************************************************************************************************************************
			--2011-2012
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2011].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20110701' THEN 2011 ELSE 9999 END AS [2011_EXIT]
					,CASE WHEN [2011].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2010' AND '07-01-2011' THEN 'ELL' ELSE'0'END AS [2011_ENTER]
					,CASE WHEN [2011].STUDENT_GU IS NOT NULL THEN '2011' ELSE '0' END AS [2011_ENROLL]
		

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('3732B795-5856-430E-996D-B75E6475EC32') AS [2011]
			ON
			STU.STUDENT_GU = [2011].STUDENT_GU

	


			
			/*************************************************************************************************************************************************
			--2010-2011
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2010].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20100701' THEN 2010 ELSE 9999 END AS [2010_EXIT]
					,CASE WHEN [2010].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2009' AND '07-01-2010' THEN 'ELL' ELSE'0'END AS [2010_ENTER]
					,CASE WHEN [2010].STUDENT_GU IS NOT NULL THEN '2010' ELSE '0' END AS [2010_ENROLL]
		

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('87F1A309-F058-43E4-B55B-EF9AE4602639') AS [2010]
			ON
			STU.STUDENT_GU = [2010].STUDENT_GU

		



			/*************************************************************************************************************************************************
			--2009-2010
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2009].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20090701' THEN 2009 ELSE 9999 END AS [2009_EXIT]
					,CASE WHEN [2009].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2008' AND '07-01-2009' THEN 'ELL' ELSE'0'END AS [2009_ENTER]
					,CASE WHEN [2009].STUDENT_GU IS NOT NULL THEN '2009' ELSE '0' END AS [2009_ENROLL]
		

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('E5D120A6-6A1C-4C42-B1F0-4ADB36DE27EF') AS [2009]
			ON
			STU.STUDENT_GU = [2009].STUDENT_GU

			

			/*************************************************************************************************************************************************
			--2008-2009
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2008].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20080701' THEN 2008 ELSE 9999 END AS [2008_EXIT]
					,CASE WHEN [2008].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2007' AND '07-01-2008' THEN 'ELL' ELSE'0'END AS [2008_ENTER]
					,CASE WHEN [2008].STUDENT_GU IS NOT NULL THEN '2008' ELSE '0' END AS [2008_ENROLL]

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('94A5BA26-69AD-4ADB-80E0-7FEDB7E686C9') AS [2008]
			ON
			STU.STUDENT_GU = [2008].STUDENT_GU

	


			/*************************************************************************************************************************************************
			--2007-2008
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2007].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20070701' THEN 2007 ELSE 9999 END AS [2007_EXIT]
					,CASE WHEN [2007].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2006' AND '07-01-2007' THEN 'ELL' ELSE'0'END AS [2007_ENTER]
					,CASE WHEN [2007].STUDENT_GU IS NOT NULL THEN '2007' ELSE '0' END AS [2007_ENROLL]

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('48ADBFD4-1987-4E7C-9C22-6FD91E8FE424') AS [2007]
			ON
			STU.STUDENT_GU = [2007].STUDENT_GU

			


			/*************************************************************************************************************************************************
			--2006-2007
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2006].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20060701' THEN 2006 ELSE 9999 END AS [2006_EXIT]
					,CASE WHEN [2006].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2005' AND '07-01-2006' THEN 'ELL' ELSE'0'END AS [2006_ENTER]
					,CASE WHEN [2006].STUDENT_GU IS NOT NULL THEN '2006' ELSE '0' END AS [2006_ENROLL]

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('CC1DCB76-576C-4414-B4BA-323A26EC8EBE') AS [2006]
			ON
			STU.STUDENT_GU = [2006].STUDENT_GU

		


			/*************************************************************************************************************************************************
			--2005-2006
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2005].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20050701' THEN 2005 ELSE 9999 END AS [2005_EXIT]
					,CASE WHEN [2005].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2004' AND '07-01-2005' THEN 'ELL' ELSE'0'END AS [2005_ENTER]
					,CASE WHEN [2005].STUDENT_GU IS NOT NULL THEN '2005' ELSE '0' END AS [2005_ENROLL]

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('BE3706A7-1239-4DAE-A038-F9A949DAA041') AS [2005]
			ON
			STU.STUDENT_GU = [2005].STUDENT_GU

			

			/*************************************************************************************************************************************************
			--2004-2005
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2004].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20040701' THEN 2004 ELSE 9999 END AS [2004_EXIT]
					,CASE WHEN [2004].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2003' AND '07-01-2004' THEN 'ELL' ELSE'0'END AS [2004_ENTER]
					,CASE WHEN [2004].STUDENT_GU IS NOT NULL THEN '2004' ELSE '0' END AS [2004_ENROLL]

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('F4F41066-7955-45DF-AD43-24A1462BFDAD') AS [2004]
			ON
			STU.STUDENT_GU = [2004].STUDENT_GU

			

		
			/*************************************************************************************************************************************************
			--2003-2004 -- THIS IS THE FIRST YEAR IN SYNERGY
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					,CASE WHEN [2003].STUDENT_GU IS NOT NULL AND TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20030701' THEN 2003 ELSE 9999 END AS [2003_EXIT]
					,CASE WHEN [2003].STUDENT_GU IS NOT NULL AND FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2002' AND '07-01-2003' THEN 'ELL' ELSE'0'END AS [2003_ENTER]
					,CASE WHEN [2003].STUDENT_GU IS NOT NULL THEN '2003' ELSE '0' END AS [2003_ENROLL]

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU
			
			--2003-2004
			LEFT JOIN 
			APS.LatestPrimaryEnrollmentInYear('A1A45208-69FC-4E58-99B3-7501E9108D70') AS [2003]
			ON
			STU.STUDENT_GU = [2003].STUDENT_GU

			

			/*************************************************************************************************************************************************
			--2002-2003 -- NO ENROLLMENTS THIS SCHOOL YEAR
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					--2002-2003 -- NO ENROLLMENTS THIS SCHOOL YEAR
					,CASE WHEN  TEST.IS_ELL = 0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20010701' THEN 2002 ELSE 9999 END AS [2002_EXIT]
					,CASE WHEN  FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2001' AND '07-01-2002' THEN 'ELL' ELSE'0'END AS [2002_ENTER]
					,2002 AS [2002_ENROLL]

			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

		

		


			/*************************************************************************************************************************************************
			--2001-2002
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					---- NO ENROLLMENTS PRIOR TO 2002 ----
					,CASE WHEN TEST.IS_ELL =0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20010701' THEN 2001 ELSE 9999 END AS [2001_EXIT]
					,CASE WHEN FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-2000' AND '07-01-2001' THEN 'ELL' ELSE'0'END AS [2001_ENTER]
					,2001 AS ENROLL
			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

		

			/*************************************************************************************************************************************************
			--2000-2001
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					---- NO ENROLLMENTS PRIOR TO 2002 ----
					,CASE WHEN TEST.IS_ELL =0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '20000701' THEN 2000 ELSE 9999 END AS [2000_EXIT]
					,CASE WHEN FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-1999' AND '07-01-2000' THEN 'ELL' ELSE'0'END AS [2000_ENTER]
					,2000 AS ENROLL
			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

		

			/*************************************************************************************************************************************************
			--1999-2000
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					---- NO ENROLLMENTS PRIOR TO 2002 ----
					,CASE WHEN TEST.IS_ELL =0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '19990701' THEN 1999 ELSE 9999 END AS [1999_EXIT]
					,CASE WHEN FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-1998' AND '07-01-1999' THEN 'ELL' ELSE'0'END AS [1999_ENTER]
					,1999 AS ENROLL
			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			

			/*************************************************************************************************************************************************
			--1998-1999
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					---- NO ENROLLMENTS PRIOR TO 2002 ----
					,CASE WHEN TEST.IS_ELL =0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '19980701' THEN 1998 ELSE 9999 END AS [1998_EXIT]
					,CASE WHEN FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-1997' AND '07-01-1998' THEN 'ELL' ELSE'0'END AS [1998_ENTER]
					,1998 AS ENROLL
			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			

			/*************************************************************************************************************************************************
			--1997-1998
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					---- NO ENROLLMENTS PRIOR TO 2002 ----
					,CASE WHEN TEST.IS_ELL =0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '19970701' THEN 1997 ELSE 9999 END AS [1997_EXIT]
					,CASE WHEN FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-1996' AND '07-01-1997' THEN 'ELL' ELSE'0'END AS [1997_ENTER]
					,1997 AS ENROLL
			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

			

			/*************************************************************************************************************************************************
			--1996-1997
			**************************************************************************************************************************************************/
			UNION ALL

			SELECT 
		
				
				STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER
				,TEST.ADMIN_DATE AS LATEST_ADMIN_DATE, TEST.TEST_NAME AS LATEST_TEST_NAME, TEST.PERFORMANCE_LEVEL AS LATEST_PERFORMANCE_LEVEL, TEST.IS_ELL AS LATEST_IS_ELL
				,FIRSTTEST.ADMIN_DATE AS FIRSTTEST_ADMIN_DATE, FIRSTTEST.TEST_NAME AS FIRSTTEST_TEST_NAME, FIRSTTEST.PERFORMANCE_LEVEL AS FIRSTTEST_PERFORMANCE_LEVEL, FIRSTTEST.IS_ELL AS FIRSTTEST_IS_ELL
		
					---- NO ENROLLMENTS PRIOR TO 2002 ----
					,CASE WHEN TEST.IS_ELL =0 AND TEST.TEST_NAME NOT IN ('PRE-LAS', 'WAPT', 'SCREENER', 'SCRE') AND TEST.ADMIN_DATE < '19960701' THEN 1996 ELSE 9999 END AS [1996_EXIT]
					,CASE WHEN FIRSTTEST.IS_ELL =1 AND FIRSTTEST.ADMIN_DATE BETWEEN '07-01-1995' AND '07-01-1996' THEN 'ELL' ELSE'0'END AS [1996_ENTER]
					,1996 AS ENROLL
			 FROM 
			rev.EPC_STU AS STU

			INNER JOIN
			APS.LCELatestEvaluationAsOf('20170814') AS TEST
			ON
			TEST.STUDENT_GU = STU.STUDENT_GU

			INNER JOIN
			APS.LCEFirstEvaluationAsOf('20170814') AS FIRSTTEST
			ON
			FIRSTTEST.STUDENT_GU = STU.STUDENT_GU

	


	) AS ALLYEARS

) AS ROWNUMBERME

GROUP BY SIS_NUMBER, STATE_STUDENT_NUMBER

) AS ONEROWPERSTUDENT

WHERE
	ENTER_ELL_DATE IS NOT NULL 

) AS ALLOFME

UNPIVOT
	(DATES FOR DATES2 IN 
	(ENTER_ELL_DATE, CLOSE_OUT_ELL_DATE, ENTER_DATE_FOR_EXIT1, EXIT_DATE_FOR_EXIT1, ENTER_DATE_FOR_EXIT2, EXIT_DATE_FOR_EXIT2,ENTER_DATE_FOR_EXIT3, EXIT_DATE_FOR_EXIT3,ENTER_DATE_FOR_EXIT4, EXIT_DATE_FOR_EXIT4,ENTER_DATE_FOR_EXIT5, EXIT_DATE_FOR_EXIT5)
	) AS UNPVT
