SELECT STU.STUDENT_GU FROM 

(SELECT * FROM
(
SELECT 
	/*T1.CLUSTER_NAME, T1.ORGANIZATION_NAME, T1.SIS_NUMBER, T1.PHL_DATE_ASSIGNED
	,T2.CLUSTER_NAME, T2.ORGANIZATION_NAME,T2.SIS_NUMBER
	,CASE WHEN T2.SIS_NUMBER IS NOT NULL THEN 'X' ELSE '' END AS ELL
	,T3.ORGANIZATION_NAME, T3.SIS_NUMBER, T3.PERFORMANCE_LEVEL
	,CASE WHEN T3.SIS_NUMBER IS NOT NULL THEN 'FEP' ELSE '' END AS FEP
	*/
	CASE WHEN T2.SIS_NUMBER IS NOT NULL THEN 0
		WHEN  T3.SIS_NUMBER IS NOT NULL THEN 0
		ELSE T1.SIS_NUMBER END AS KEEPME


 FROM 
(
SELECT 
	CLUSTERNAME.ORGANIZATION_NAME AS CLUSTER_NAME, ORG.ORGANIZATION_NAME, SIS_NUMBER, PHL.DATE_ASSIGNED AS PHL_DATE_ASSIGNED, STU.STUDENT_GU
	--COUNT(PHL.STUDENT_GU) AS PHLOTE 
 FROM 

APS.PrimaryEnrollmentsAsOf('2015-05-22')AS PE
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
PE.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN
rev.EPC_SCH AS SCHOOL
ON
SCHOOL.ORGANIZATION_GU = ORG.ORGANIZATION_GU

------------------------------------------------
INNER JOIN
rev.EPC_SCH AS CLUSTER
ON
SCHOOL.ALT_FUNDING_SCHOOL_CODE = CLUSTER.SCHOOL_CODE

INNER JOIN
rev.REV_ORGANIZATION AS CLUSTERNAME
ON
CLUSTER.ORGANIZATION_GU = CLUSTERNAME.ORGANIZATION_GU
-----------------------------------------------------------

INNER JOIN
APS.PHLOTEAsOf('2015-05-22') AS PHL
ON
PHL.STUDENT_GU = PE.STUDENT_GU

INNER JOIN
rev.EPC_STU AS STU
ON
PHL.STUDENT_GU = STU.STUDENT_GU

--WHERE
--CLUSTER.ALT_FUNDING_SCHOOL_CODE = '570'
AND
	PE.GRADE NOT IN  ('050', '070', '090', '230', '240', '250', '260', '270', '280', '290', '300')

) AS T1

LEFT JOIN
(SELECT 
	CLUSTERNAME.ORGANIZATION_NAME AS CLUSTER_NAME, ORG.ORGANIZATION_NAME, SIS_NUMBER, T1.GRADE, TEST_NAME, PERFORMANCE_LEVEL

 FROM 


	(SELECT 
			*
	FROM 

	(
	SELECT 
			ESL.*
			,STU.STUDENT_GU 
			,ROW_NUMBER() OVER (PARTITION BY ESL.SIS_NUMBER ORDER BY STATUS DESC) AS RN
	 FROM 
	APS.LCEStudentsAndProvidersAsOf('2015-05-22') AS ESL
	INNER JOIN
	rev.EPC_STU AS STU
	ON
	ESL.SIS_NUMBER = STU.SIS_NUMBER

	) AS T1
	WHERE RN =1
	AND GRADE NOT IN ('P1', 'P2', 'PK', 'T1', 'T2', 'T3', 'T4', 'C1', 'C2', 'C3', 'C4')

	) AS T1


INNER JOIN
APS.PrimaryEnrollmentsAsOf('2015-05-22')AS PE
	
ON
T1.STUDENT_GU = PE.STUDENT_GU

INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
PE.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN
rev.EPC_SCH AS SCHOOL
ON
SCHOOL.ORGANIZATION_GU = ORG.ORGANIZATION_GU

------------------------------------------------
INNER JOIN
rev.EPC_SCH AS CLUSTER
ON
SCHOOL.ALT_FUNDING_SCHOOL_CODE = CLUSTER.SCHOOL_CODE

INNER JOIN
rev.REV_ORGANIZATION AS CLUSTERNAME
ON
CLUSTER.ORGANIZATION_GU = CLUSTERNAME.ORGANIZATION_GU


--WHERE
	--CLUSTER.ALT_FUNDING_SCHOOL_CODE = '570'
	) AS T2

	ON

T1.SIS_NUMBER = T2.SIS_NUMBER


FULL OUTER JOIN
(SELECT --PRIM.STUDENT_GU, PERFORMANCE_LEVEL, PRIM.GRADE, TEST_NAME, SCHOOL.ALT_FUNDING_SCHOOL_CODE 
	 ORGANIZATION_NAME, LU.VALUE_DESCRIPTION AS GRADE, SIS_NUMBER, PHL.DATE_ASSIGNED AS PHL_DATEASSIGNED, TEST_NAME, PERFORMANCE_LEVEL

FROM 
APS.PHLOTEAsOf('2015-05-22') AS PHL
INNER JOIN
APS.PrimaryEnrollmentsAsOf('2015-05-22') AS PRIM
ON
PHL.STUDENT_GU = PRIM.STUDENT_GU
INNER JOIN
APS.LCELatestEvaluationAsOf('2015-05-22') AS LCE
ON
LCE.STUDENT_GU = PRIM.STUDENT_GU
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = PRIM.ORGANIZATION_YEAR_GU
INNER JOIN
rev.EPC_SCH AS SCHOOL
ON
SCHOOL.ORGANIZATION_GU = ORGYR.ORGANIZATION_GU
INNER JOIN
rev.EPC_STU AS STU
ON
STU.STUDENT_GU = PRIM.STUDENT_GU
INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORG.ORGANIZATION_GU = ORGYR.ORGANIZATION_GU
INNER JOIN
APS.LookupTable ('K12', 'Grade') AS LU
ON
LU.VALUE_CODE = PRIM.GRADE

WHERE
	PRIM.GRADE NOT IN  ('050', '070', '090', '230', '240', '250', '260', '270', '280', '290', '300')
	AND PERFORMANCE_LEVEL IN ('ADV','BRIDG', 'FEP', 'REACH','C-PRO')
	--AND ALT_FUNDING_SCHOOL_CODE = '570'

	) AS T3

ON
T3.SIS_NUMBER = T1.SIS_NUMBER

) AS T4
WHERE
KEEPME != 0
) AS PART1
INNER JOIN
rev.EPC_STU AS STU
ON
STU.SIS_NUMBER = PART1.KEEPME
