

select s.SIS_NUMBER, (p.LAST_NAME++', '++p.FIRST_NAME) STUDENT,
Convert(varchar(11),s.GRADUATION_DATE,1) GRAD_DATE, o.ORGANIZATION_NAME, grd.VALUE_DESCRIPTION GRADE 
,TOTAL AS TOTAL_EARNED_CREDITS
from rev.REV_PERSON p
join rev.epc_stu s on s.student_gu = p.PERSON_GU and s.GRADUATION_DATE >= '2016-05-26' and s.GRADUATION_DATE < '2016-08-01'
join rev.EPC_STU_YR sy on sy.STUDENT_GU = s.STUDENT_GU
join rev.EPC_STU_SCH_YR ssy on ssy.STUDENT_SCHOOL_YEAR_GU = sy.STU_SCHOOL_YEAR_GU
join rev.REV_BOD_LOOKUP_VALUES grd on grd.VALUE_CODE = ssy.GRADE and grd.LOOKUP_DEF_GU =
      (select LOOKUP_DEF_GU from rev.REV_BOD_LOOKUP_DEF d where d.LOOKUP_DEF_CODE = 'Grade' and LOOKUP_NAMESPACE = 'k12')
join rev.REV_ORGANIZATION_YEAR oy on oy.ORGANIZATION_YEAR_GU = ssy.ORGANIZATION_YEAR_GU
join rev.REV_ORGANIZATION o on o.ORGANIZATION_GU = oy.ORGANIZATION_GU
join rev.REV_YEAR y on y.YEAR_GU = sy.YEAR_GU and y.SCHOOL_YEAR = '2015'

LEFT JOIN
(
		SELECT 
				SUM(CREDIT_COMPLETED) AS TOTAL
				,STU.STUDENT_GU 
			 FROM 

			rev.EPC_STU_CRS_HIS AS HIS
			INNER JOIN 
			REV.EPC_STU AS STU
			ON
			HIS.STUDENT_GU = STU.STUDENT_GU
			LEFT JOIN
			[rev].[EPC_REPEAT_TAG] AS [Repeat]
			ON
			HIS.[REPEAT_TAG_GU]=[Repeat].[REPEAT_TAG_GU]

			WHERE
			HIS.COURSE_HISTORY_TYPE = 'HIGH'
			 AND ISNULL([Repeat].[REPEAT_CODE],'')!='R'
			 GROUP BY STU.STUDENT_GU
			 ) AS T1

			 ON
			 T1.STUDENT_GU= S.STUDENT_GU