

SELECT STY.* FROM 
REV.EPC_STAFF_SCH_YR AS STY
INNER JOIN 
REV.EPC_STAFF AS STF
ON
STY.STAFF_GU = STF.STAFF_GU
INNER JOIN 
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
STY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
WHERE
BADGE_NUM = 'e210377'
AND ORGANIZATION_NAME LIKE 'HIGHLAND%'
/*
UPDATE REV.EPC_STAFF_SCH_YR
SET SIS_NUMBER = 210377
WHERE
STAFF_SCHOOL_YEAR_GU = '3780B552-6C9F-42A5-ADB4-1A3FC7E9980D'
*/