
SELECT DISTINCT
           STU.SIS_NUMBER                       
         , PER.FIRST_NAME + ' ' + PER.LAST_NAME AS STUDENT_NAME
		 , SIBS.SIS_NUMBER AS SIBLING_SIS_NUMBER
		 , SIBP.FIRST_NAME + ' ' + SIBP.LAST_NAME AS SIBLING_NAME
FROM     
		 REV.EPC_STU AS STU
         INNER JOIN rev.REV_PERSON AS PER  
		 ON PER.PERSON_GU = STU.STUDENT_GU

		 INNER JOIN rev.EPC_STU_PARENT AS SPAR 
		 ON SPAR.STUDENT_GU = STU.STUDENT_GU
		 
		 INNER JOIN rev.EPC_PARENT AS PAR 
		 ON PAR.PARENT_GU = SPAR.PARENT_GU
		 
		 INNER JOIN rev.EPC_STU_PARENT AS PPAR 
		 ON PPAR.PARENT_GU = PAR.PARENT_GU
		 
		 INNER JOIN rev.EPC_STU AS SIBS 
		 ON SIBS.STUDENT_GU = ppar.STUDENT_GU
		 
		 INNER JOIN rev.REV_PERSON AS SIBP 
		 ON SIBP.PERSON_GU = SIBS.STUDENT_GU

WHERE    
STU.STUDENT_GU != PPAR.STUDENT_GU 

ORDER BY STU.SIS_NUMBER
