

SELECT 
	ORGANIZATION_NAME
	,SIS_NUMBER
	,ENTER_DATE
	, LEAVE_DATE
 FROM
rev.EPC_STU_YR AS SOR
INNER JOIN
rev.EPC_STU AS STUDENT
ON
SOR.STUDENT_GU = STUDENT.STUDENT_GU
INNER JOIN
rev.EPC_STU_SCH_YR AS SSY
ON
SSY.STUDENT_SCHOOL_YEAR_GU = SOR.STU_SCHOOL_YEAR_GU

INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = SSY.ORGANIZATION_YEAR_GU

INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

INNER JOIN
rev.REV_YEAR AS YEARS
ON
YEARS.YEAR_GU = ORGYR.YEAR_GU

WHERE
SCHOOL_YEAR = 2014


ORDER BY  SIS_NUMBER, ORGANIZATION_NAME