
SELECT 
--DISTINCT
	ENR.SIS_NUMBER
	,ORGANIZATION_NAME
	,LAST_NAME
	,FIRST_NAME
	,ENR.GRADE
	,STU.EXPECTED_GRADUATION_YEAR
	,STU.GRADUATION_DATE
	,STU.DIPLOMA_TYPE
	,STU.POST_SECONDARY
	,STU.GRADUATION_STATUS
	,TOTAL

 FROM 
APS.StudentEnrollmentDetails AS ENR
INNER JOIN 
		(
		SELECT * FROM (
		SELECT 
				SUM(CREDIT_COMPLETED) AS TOTAL
				,STU.STUDENT_GU 
			 FROM 

			rev.EPC_STU_CRS_HIS AS HIS
			INNER JOIN 
			REV.EPC_STU AS STU
			ON
			HIS.STUDENT_GU = STU.STUDENT_GU
			LEFT JOIN
			[rev].[EPC_REPEAT_TAG] AS [Repeat]
			ON
			HIS.[REPEAT_TAG_GU]=[Repeat].[REPEAT_TAG_GU]

			WHERE
			HIS.COURSE_HISTORY_TYPE = 'HIGH'
			 AND ISNULL([Repeat].[REPEAT_CODE],'')!='R'
			 GROUP BY STU.STUDENT_GU
			 ) AS T1
			 WHERE
				TOTAL >='25.00'

) AS CREDITS
ON
ENR.STUDENT_GU = CREDITS.STUDENT_GU

INNER JOIN 
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = ENR.ORGANIZATION_YEAR_GU
INNER JOIN 
rev.REV_ORGANIZATION AS ORG
ON
ORG.ORGANIZATION_GU = ORGYR.ORGANIZATION_GU
INNER JOIN 
rev.REV_PERSON AS PERS
ON
ENR.STUDENT_GU = PERS.PERSON_GU
INNER JOIN 
rev.EPC_STU AS STU
ON 
ENR.STUDENT_GU = STU.STUDENT_GU

WHERE
ENR.SCHOOL_YEAR = '2015'

ORDER BY SIS_NUMBER



