
SELECT 
	STF.STATE_ID, STF.TYPE, STF.BADGE_NUM, LAWS.POSITION, LAWS.SCHEDULE, LAWS.LOCATION, LAWS.LAST_NAME, LAWS.FIRST_NAME, 
	LAWS.MIDDLE_NAME
 FROM 
[180-SMAXODS-01.APS.EDU.ACTD].Lawson.APS.ActiveEmployeesAllAssignments AS LAWS
INNER JOIN 
(SELECT * FROM rev.EPC_STAFF WHERE TYPE IN ('SSS', 'SCA', 'TE', 'SA'))  AS STF
ON
STF.STATE_ID = CAST(LAWS.EMPLOYEE AS VARCHAR)

LEFT JOIN 
	(SELECT ORGANIZATION_NAME, YRS.SCHOOL_YEAR,STFYR.STAFF_GU FROM 
	rev.EPC_STAFF_SCH_YR AS STFYR
	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	STFYR.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
	INNER JOIN 
	rev.EPC_STAFF AS STF
	ON
	STF.STAFF_GU = STFYR.STAFF_GU
	INNER JOIN 
	rev.REV_ORGANIZATION AS ORG
	ON
	ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
	INNER JOIN 
	rev.REV_YEAR AS YRS
	ON
	ORGYR.YEAR_GU = YRS.YEAR_GU
	WHERE
	SCHOOL_YEAR = 2016
	) STFYR
ON
STF.STAFF_GU = STFYR.STAFF_GU

WHERE
STFYR.STAFF_GU IS NULL
