
SELECT * FROM (

SELECT 
SCHOOL_CODE, SCHOOL_NAME,SIS_NUMBER, LAST_NAME, FIRST_NAME, GRADE, BIRTH_DATE 
,CASE WHEN (DATEADD(year,DATEDIFF(year, BIRTH_DATE  ,GETDATE()) , BIRTH_DATE) > GETDATE())THEN DATEDIFF(year, BIRTH_DATE  ,GETDATE()) -1
	ELSE DATEDIFF(year, BIRTH_DATE  ,GETDATE()) END AS AGE
,BS.SPED_STATUS
,BS.ELL_STATUS
,BS.LUNCH_STATUS
,BS.GENDER
,BS.RACE_1
,BS.RACE_2
,BS.RACE_3
,BS.RACE_4
,BS.RACE_5
,BS.RESOLVED_RACE
,BS.HOME_ADDRESS
,CREDITS_EARNED

FROM 
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
LEFT JOIN 
(
SELECT SUM(HIST.CREDIT_COMPLETED) AS CREDITS_EARNED, ENR.STUDENT_GU 
FROM 
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS ENR
INNER JOIN 
rev.EPC_STU_CRS_HIS AS HIST
ON
ENR.STUDENT_GU = HIST.STUDENT_GU
AND HIST.COURSE_HISTORY_TYPE = 'HIGH'
GROUP BY ENR.STUDENT_GU
) AS GETCR
ON
GETCR.STUDENT_GU = BS.STUDENT_GU

) AS T1
WHERE
SCHOOL_CODE > '500'

ORDER BY 
SCHOOL_CODE
,GRADE
,LAST_NAME
,FIRST_NAME
