
BEGIN TRANSACTION 

UPDATE rev.EPC_SCH_YR_SECT 
SET STAFF_SCHOOL_YEAR_GU = NULL 

FROM
(
SELECT SCHOOL_YEAR, EXTENSION, STF.BADGE_NUM
, SECT.SECTION_ID , SECT.TERM_CODE
, SEC.STAFF_SCHOOL_YEAR_GU
,SECT.SECTION_GU 
FROM 
rev.EPC_STAFF_SCH_YR AS SEC
INNER JOIN 
rev.EPC_STAFF AS STF
ON
SEC.STAFF_GU = STF.STAFF_GU
INNER JOIN 
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
SEC.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN 
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN 
rev.REV_YEAR AS YRS
ON
YRS.YEAR_GU = ORGYR.YEAR_GU
INNER JOIN 
rev.EPC_SCH_YR_SECT AS SECT
ON
SEC.STAFF_SCHOOL_YEAR_GU = SECT.STAFF_SCHOOL_YEAR_GU
INNER JOIN 
rev.EPC_SCH_YR_CRS AS CRS
ON
SECT.SCHOOL_YEAR_COURSE_GU = CRS.SCHOOL_YEAR_COURSE_GU
INNER JOIN 
rev.EPC_CRS AS CRS2
ON
CRS.COURSE_GU = CRS2.COURSE_GU

WHERE
SCHOOL_YEAR = '2016'
AND EXTENSION = 'R'
AND COURSE_ID = 'ESL'
AND ORGANIZATION_NAME LIKE '%ELEM%'
) AS T1

WHERE
T1.STAFF_SCHOOL_YEAR_GU = rev.EPC_SCH_YR_SECT.STAFF_SCHOOL_YEAR_GU
AND T1.SECTION_GU = rev.EPC_SCH_YR_SECT.SECTION_GU

ROLLBACK
