

/*
BEGIN TRANSACTION 

UPDATE REV.EPC_STU_SCH_YR

SET GRADE = SSYFIX.SSY_LU_GRADE

FROM 

(
*/
SELECT 
	STU.SIS_NUMBER, PRIMARIES.GRADE AS SSY_PRIMARY_GRADE,  SSYADAS.GRADE AS SSY_ADAS_GRADE,
	PRIMARIES.LU_GRADE AS SSY_LU_GRADE, SSYADAS.LU_GRADE AS SSYADAS_LU_GRADE, SSYADAS.STUDENT_SCHOOL_YEAR_GU, ORGANIZATION_NAME AS PRIM, Non_Primary_school

 FROM 
(SELECT STUDENT_GU, LU.VALUE_DESCRIPTION AS GRADE, STUDENT_SCHOOL_YEAR_GU
,LU.VALUE_CODE AS LU_GRADE, PRIM.ENROLLMENT_GU, ORGANIZATION_NAME

 FROM APS.PrimaryEnrollmentsAsOf(GETDATE()) AS PRIM
INNER JOIN 
APS.LookupTable('K12', 'GRADE') AS LU
ON
PRIM.GRADE = LU.VALUE_CODE


INNER JOIN 
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
PRIM.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN 
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

) AS PRIMARIES


--GET SECONDARY ENROLLMENTS
INNER JOIN 
 (SELECT * FROM  APS.OpenNonPrimaryEnrollments 
 WHERE Primary_School IS NOT NULL)
 
 AS SSYADAS

ON
SSYADAS.STUDENT_GU = PRIMARIES.STUDENT_GU

INNER JOIN 
rev.EPC_STU AS STU
ON
PRIMARIES.STUDENT_GU = STU.STUDENT_GU


WHERE
SSYADAS.LU_GRADE != PRIMARIES.LU_GRADE
AND  PRIMARIES.GRADE NOT IN ('PK', 'P1', 'P2')


/*
) AS SSYFIX

WHERE

rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU = SSYFIX.STUDENT_SCHOOL_YEAR_GU


ROLLBACK

*/



