

/**********************************************************

--THE FIRST UPDATE WILL UPDATE STUDENTS WITH A GRAD STATUS 

***********************************************************/

BEGIN TRANSACTION 

UPDATE rev.EPC_NM_STU_SPED_RPT
SET IEP_TRANSITION_STATUS = T2.IEPSTAT

FROM
(
SELECT 

	T1.GRADUATION_STATUS
	,CASE	
			
			WHEN T1.GRADUATION_STATUS = 6 THEN 40
			WHEN T1.GRADUATION_STATUS = 7 THEN 50
	ELSE NULL END AS IEPSTAT
	,STU_SPED_RPT_GU
	
	FROM
(SELECT GRAD_STATUS.STUDENT_GU, GRADUATION_STATUS, STU_SPED_RPT_GU FROM

(SELECT SIS_NUMBER, GRADUATION_DATE, GRADUATION_STATUS, PRIM.STUDENT_GU FROM 
REV.EPC_STU AS STU
INNER JOIN 
APS.PrimaryEnrollmentDetailsAsOf('2017-05-25') AS PRIM
ON
STU.STUDENT_GU = PRIM.STUDENT_GU

WHERE
GRADUATION_STATUS IN ( '6', '7')

) AS GRAD_STATUS

LEFT JOIN 
	(SELECT IEP_TRANSITION_STATUS, STUDENT_GU, STU_SPED_RPT_GU FROM 
rev.EPC_NM_STU_SPED_RPT
WHERE
SCHOOL_YEAR = 2016
AND SNAPSHOT_TYPE = 4
) AS SPED

ON
SPED.STUDENT_GU = GRAD_STATUS.STUDENT_GU
) AS T1
) AS T2

WHERE

rev.EPC_NM_STU_SPED_RPT.STU_SPED_RPT_GU = T2.STU_SPED_RPT_GU

ROLLBACK


/***************************************************************

--THE SECOND UPDATE WILL UPDATE STUDENTS WITH A YEAR END STATUS 

****************************************************************/


BEGIN TRANSACTION 

UPDATE rev.EPC_NM_STU_SPED_RPT
SET IEP_TRANSITION_STATUS = T2.IEPSTAT

FROM
(
SELECT 

	T1.YEAR_END_STATUS
	,CASE	
			WHEN YEAR_END_STATUS = 'C' THEN '20'
	ELSE NULL END AS IEPSTAT
	,STU_SPED_RPT_GU
	
	FROM
(SELECT YEAR_END_STATUS, YEAR_END_STATUS.STUDENT_GU, STU_SPED_RPT_GU  FROM

(SELECT PRIM.YEAR_END_STATUS, PRIM.STUDENT_GU FROM 
APS.PrimaryEnrollmentDetailsAsOf('2017-05-25') AS PRIM
INNER JOIN 
REV.EPC_STU_SCH_YR AS SSY
ON
PRIM.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU
WHERE
PRIM.YEAR_END_STATUS = 'C'

) AS YEAR_END_STATUS

LEFT JOIN 
	(SELECT IEP_TRANSITION_STATUS, STUDENT_GU, STU_SPED_RPT_GU FROM 
rev.EPC_NM_STU_SPED_RPT
WHERE
--
SCHOOL_YEAR = 2016
AND SNAPSHOT_TYPE = 4
) AS SPED

ON
SPED.STUDENT_GU = YEAR_END_STATUS.STUDENT_GU
) AS T1
) AS T2

WHERE

rev.EPC_NM_STU_SPED_RPT.STU_SPED_RPT_GU = T2.STU_SPED_RPT_GU

--ORDER BY SPED.STUDENT_GU DESC

ROLLBACK
