

EXECUTE AS LOGIN='QueryFileUser'
GO

BEGIN TRANSACTION

UPDATE rev.EPC_NM_STU_SPED_RPT
SET IEP_TRANSITION_STATUS = T2.IEPSTAT
FROM 
(

SELECT 

	T1.GRADUATION_STATUS, SPED.*
	,CASE	WHEN T1.GRADUATION_STATUS = 4 THEN 20
			WHEN T1.GRADUATION_STATUS = 6 THEN 40
			WHEN T1.GRADUATION_STATUS = 7 THEN 50
	ELSE NULL END AS IEPSTAT

	
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from GradStatus.csv'
                ) AS [T1]
	
	INNER JOIN 
		REV.EPC_STU AS STU
		ON
		T1.SIS_NUMBER = STU.SIS_NUMBER

	LEFT JOIN 
	(SELECT IEP_TRANSITION_STATUS, STUDENT_GU, STU_SPED_RPT_GU FROM 
rev.EPC_NM_STU_SPED_RPT
WHERE
SCHOOL_YEAR = 2015
AND SNAPSHOT_TYPE = 4
) AS SPED

ON
SPED.STUDENT_GU = STU.STUDENT_GU

) AS T2 

WHERE

rev.EPC_NM_STU_SPED_RPT.STU_SPED_RPT_GU = T2.STU_SPED_RPT_GU

--ORDER BY SPED.STUDENT_GU DESC


COMMIT

REVERT
GO