BEGIN TRANSACTION 

UPDATE rev.EPC_STU_SCH_YR 
SET ORGANIZATION_YEAR_GU = '47F74A41-949F-43BD-B5CF-BE9B7FEF3437', CHANGE_DATE_TIME_STAMP = GETDATE()

FROM 
(
SELECT * FROM 
APS.StudentEnrollmentDetails
WHERE
SCHOOL_YEAR = '2016'
AND EXTENSION = 'R'
AND GRADE = '03'
AND SCHOOL_NAME LIKE 'HELEN%'
) AS T1

WHERE
T1.STUDENT_SCHOOL_YEAR_GU = rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU

ROLLBACK