--47,677

SELECT GETPARENTS.*
, TotalMemberDays
, ISNULL(TOTAL_ABSENCE_DAYS,0) AS Total_Absences
, ISNULL(TotalMemberDays,0) - ISNULL(TOTAL_ABSENCE_DAYS,0) AS Total_Present_Days
FROM 

--THIS PART1 GETS THE PARENTS
(
SELECT 
	T1.*
	,PARENTS_NAME
	,PARENTS_ADDRESS
	,PARENTS_CITY
	,PARENTS_STATE
	,PARENTS_ZIP

FROM
           OPENROWSET ('MSDASQL', 'Driver={Microsoft Access Text Driver (*.txt, *.csv)};
		   DBQ=E:\SQLWorkingFiles;'
		   , 'SELECT * from "0809.txt"') AS [T1]

LEFT HASH JOIN 
(SELECT 
	ID_NBR
	,STATE_ID
	,CASE WHEN [HoH2 FirstName] IS NULL THEN [HoH1 FirstName]  + ' ' + [HoH1 LastName] 
			WHEN [HoH2 FirstName] IS NOT NULL THEN [HoH1 FirstName]  + ' ' + [HoH1 LastName] + ', ' + [HoH2 FirstName] +' '+ [HoH2 LastName] ELSE '' END AS PARENTS_NAME
	,ADDR_LNE_1 AS [PARENTS_ADDRESS]
	,CITY AS PARENTS_CITY
	,[STATE] AS PARENTS_STATE
	,LEFT(ZIP_CD, 5) AS PARENTS_ZIP

 FROM 
(
SELECT 
	ID_NBR
	,STATE_ID	
	,ROW_NUMBER() OVER (PARTITION BY ID_NBR,[Primary Family Number] ORDER BY [Primary Family Number] ) AS RN
	,[Primary Family Number]
	,FAM.[HoH1 FirstName], FAM.[HoH1 LastName], FAM.[HoH2 FirstName], FAM.[HoH2 LastName]
	--,ADDR_TO AS PARENT_NAME
	,ADDR_LNE_1 
	,ADDR_LNE_2
	,CITY
	,[STATE]
	,ZIP_CD

 FROM
APS.StudentWithFamily AS STU
INNER HASH JOIN 
APS.FamilyInformation AS FAM
ON
STU.[Primary Family Number] = FAM.FAM_NBR
) AS T1
WHERE
RN = 1) AS STUFAM
ON
STUFAM.ID_NBR = T1.[APS ID] collate database_default

) AS GETPARENTS


--THIS PART GETS THE MEMBER DAYS 

LEFT HASH JOIN 
(SELECT SUM(MemberDays) AS TotalMemberDays, ID_NBR, SCH_YR
--SCH_NBR, SCH_YR, MemberDays, Enrollment_Id 
FROM 
APS.EnrollmentMemberDaysAsOf('2014-06-30') AS ENR
INNER JOIN 
DBTSIS.ST010 AS ENR2
ON
ENR2._Id = ENR.Enrollment_Id
AND ENR2.NONADA_SCH = ''
WHERE SCH_YR >= '2009'
GROUP BY ID_NBR, SCH_YR
) AS MEMBERDAYS
ON
MEMBERDAYS.ID_NBR = GETPARENTS.[APS ID]
AND MEMBERDAYS.SCH_YR = GETPARENTS.[SY]


--THIS PART TOTALS UP ABSENCES PER STUDENT, PER YEAR
LEFT HASH JOIN 
(SELECT 
	SUM(TOTAL_FULLDAYS + TOTAL_HALFDAYS) AS TOTAL_ABSENCE_DAYS 
	,SCH_YR
	,ID_NBR
FROM (
SELECT 
CAST(USRDATA AS INT) AS TOTALS
, SCH_YR, ID_NBR  
,FIELDNUM
,CASE WHEN FIELDNUM IN ('50', '55') THEN CAST(USRDATA AS INT) * .5 ELSE 0 END AS TOTAL_HALFDAYS
,CASE WHEN FIELDNUM IN ('0', '5') THEN CAST(USRDATA AS INT) ELSE 0 END AS TOTAL_FULLDAYS
FROM 
DBTSIS.IV030_V
WHERE
SCH_NBR = ''
AND ISPECNAME = 'ATDAY'
--ORDER BY SCH_YR
) AS T1
GROUP BY  SCH_YR, ID_NBR
) AS ATTENDANCE
ON
ATTENDANCE.ID_NBR = GETPARENTS.[APS ID]
AND ATTENDANCE.SCH_YR = GETPARENTS.[SY]





