
--2015:  BCFE2270-A461-4260-BA2B-0087CB8EC26A
--2014:  26F066A3-ABFC-4EDB-B397-43412EDABC8B

SELECT MRE.SIS_NUMBER, MRE.SCHOOL_NAME, MRE.YEAR_END_STATUS, MRE.ENTER_DATE, MRE.LEAVE_DATE, SUMMER_WITHDRAWL_CODE, SUMMER_WITHDRAWL_DATE 
FROM 
APS.LatestPrimaryEnrollmentInYear('BCFE2270-A461-4260-BA2B-0087CB8EC26A') AS MRE
WHERE
MRE.LEAVE_DATE IS NULL AND MRE.YEAR_END_STATUS IS NULL 
AND (MRE.SUMMER_WITHDRAWL_CODE IS NULL OR SUMMER_WITHDRAWL_DATE IS NULL) 
AND SCHOOL_NAME NOT LIKE 'PRE%'

SELECT MRE.SIS_NUMBER, MRE.SCHOOL_NAME, MRE.YEAR_END_STATUS, MRE.ENTER_DATE, MRE.LEAVE_DATE, SUMMER_WITHDRAWL_CODE, SUMMER_WITHDRAWL_DATE 
FROM 
APS.LatestPrimaryEnrollmentInYear('26F066A3-ABFC-4EDB-B397-43412EDABC8B') AS MRE
WHERE
LEAVE_DATE IS NULL AND YEAR_END_STATUS IS NULL
AND (SUMMER_WITHDRAWL_CODE IS NULL OR SUMMER_WITHDRAWL_DATE IS NULL)
 