/* Pull graduate test data for Brenda Martinez Papponi
Written by:		JoAnn Smith
Date Written:	7/27/2017

This script pulls ACT, SAT and PARCC data for years 2008-2016.
SAT scores do not have overall scores for earlier years, so pulled
Math, Reading and Writing scores.  ACT scoring changed in 2014, so
pulls for the previous years (2008-2013) had to be pulled separately.
PARCC had no overall scores so scores were pulled for all test 
groups.  

This data was then generated into a file dbo.AllTestResults and
exported to SYNSECONDDB so that it could be combined with the
table DBO.APSGrads.

*/



; with ACT2008_2013
as
(
SELECT 
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, YEAR_VALUE) AS RN
    ,cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,YEAR_VALUE 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
	,LOCAL_SCHOOL_YEAR
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,max(CASE WHEN YEAR_VALUE = 2008 THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT2008
	,max(CASE WHEN YEAR_VALUE = 2009 THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT2009
	,max(CASE WHEN YEAR_VALUE = 2010 THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT2010
	,max(CASE WHEN YEAR_VALUE = 2011 THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT2011
	,max(CASE WHEN YEAR_VALUE = 2012 THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT2012
	,max(CASE WHEN YEAR_VALUE = 2013 THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT2013


from
	dbo.APSGrads g
INNER join
	 K12INTEL_DW.DTBL_STUDENTS 
ON
	cast(g.ID as nvarchar) = K12INTEL_dw.DTBL_STUDENTS.STUDENT_ID
left join
	k12intel_dw.FTBL_TEST_SCORES
on
	 DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
left JOIN
	 K12INTEL_DW.DTBL_TESTS
ON
	 DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
inner JOIN
	 K12INTEL_DW.DTBL_SCHOOLS
ON
	 DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
inner JOIN
	 K12INTEL_DW.DTBL_CALENDAR_DATES
ON
	 DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
inner JOIN 
	K12INTEL_DW.DTBL_SCHOOL_DATES
ON
	 DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY
where
	LOCAL_SCHOOL_YEAR IN ('2008-2009', '2009-2010', '2010-2011', '2011-2012', '2012-2013', '2013-2014') AND
	TEST_NAME LIKE 'ACT%' AND TEST_SUBJECT = 'OVERALL'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	DTBL_CALENDAR_DATES.YEAR_VALUE,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP

	
)
--SELECT MAX(RN) FROM ACT2008_2013

,ACT2008_2013_RESULTS
AS
(
SELECT
	SIS_NUMBER,
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND YEAR_VALUE = 2008 THEN ACT2008 ELSE 0 END) AS [ACT_SCORE_2008],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND YEAR_VALUE = 2009 THEN ACT2009 ELSE 0 END) AS [ACT_SCORE_2009],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND YEAR_VALUE = 2010 THEN ACT2010 ELSE 0 END) AS [ACT_SCORE_2010],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND YEAR_VALUE = 2011 THEN ACT2011 ELSE 0 END) AS [ACT_SCORE_2011],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND YEAR_VALUE = 2012 THEN ACT2012 ELSE 0 END) AS [ACT_SCORE_2012],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND YEAR_VALUE = 2013 THEN ACT2013 ELSE 0 END) AS [ACT_SCORE_2013]
FROM
	ACT2008_2013
GROUP BY
	SIS_NUMBER
)

--SELECT * FROM ACT2008_2013_RESULTS
,ACT2014_2016
as
(
SELECT 
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, YEAR_VALUE) AS RN
    ,cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,YEAR_VALUE 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
	,LOCAL_SCHOOL_YEAR
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,max(CASE WHEN YEAR_VALUE = 2014 THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT2014
	,max(CASE WHEN YEAR_VALUE = 2015 THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT2015
	,max(CASE WHEN YEAR_VALUE = 2016 THEN TEST_SCORE_VALUE ELSE 0 END) AS ACT2016


FROM
dbo.APSGrads g
INNER join
	 K12INTEL_DW.DTBL_STUDENTS 
ON
	cast(g.ID as nvarchar) = K12INTEL_dw.DTBL_STUDENTS.STUDENT_ID
inner join
	k12intel_dw.FTBL_TEST_SCORES
on
	 DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN
	 K12INTEL_DW.DTBL_TESTS
ON
	 DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 

INNER JOIN
	 K12INTEL_DW.DTBL_SCHOOLS
ON
	 DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN
	 K12INTEL_DW.DTBL_CALENDAR_DATES
ON
	 DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN
	 K12INTEL_DW.DTBL_SCHOOL_DATES
ON
	 DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY

where
	LOCAL_SCHOOL_YEAR IN ('2014-2015', '2015-2016', '2016-2017') AND
	TEST_NAME LIKE 'ACT%'  AND TEST_CLASS = 'COMPOSITE' AND TEST_SUBGROUP = 'TOTAL'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	DTBL_CALENDAR_DATES.YEAR_VALUE,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP

	
)

--SELECT * from ACT2014_2016
--select max(RN) FROM ACT2014_2016
,ACT2004_2016_RESULTS
AS
(
SELECT
	SIS_NUMBER,
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND YEAR_VALUE = 2014 THEN ACT2014 ELSE 0 END) AS [ACT_SCORE_2014],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND YEAR_VALUE = 2015 THEN ACT2015 ELSE 0 END) AS [ACT_SCORE_2015],
	MAX(CASE WHEN RN = 1  or RN = 2 OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 OR RN = 7 AND YEAR_VALUE = 2016 THEN ACT2016 ELSE 0 END) AS [ACT_SCORE_2016]
FROM
	ACT2014_2016
GROUP BY
	SIS_NUMBER
)

/*-------------------------------------------*/

,SAT
as
(
SELECT 
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, YEAR_VALUE) AS RN,
    cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
	,TEST_SUBJECT
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,YEAR_VALUE 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
    --,TEST_SCORE_VALUE 
    --,CAST(TEST_PRIMARY_RESULT AS NVARCHAR) AS PERFORMANCE_LEVEL
    --,CAST(SIS_SCHOOL_YEAR AS NVARCHAR) AS SCHOOL_YEAR
	,LOCAL_SCHOOL_YEAR
    --,CAST(TEST_CLASS AS nvarchar) AS TEST_CLASS
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP

	--no data for 2008-2010

	,max(CASE WHEN YEAR_VALUE = 2011 AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2011
	,max(CASE WHEN YEAR_VALUE = 2011 AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2011
	,max(CASE WHEN YEAR_VALUE = 2011 AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2011

	,max(CASE WHEN YEAR_VALUE = 2012 AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2012
	,max(CASE WHEN YEAR_VALUE = 2012 AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2012
	,max(CASE WHEN YEAR_VALUE = 2012 AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2012

	,max(CASE WHEN YEAR_VALUE = 2013 AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2013
	,max(CASE WHEN YEAR_VALUE = 2013 AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2013
	,max(CASE WHEN YEAR_VALUE = 2013 AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2013

	,max(CASE WHEN YEAR_VALUE = 2014 AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2014
	,max(CASE WHEN YEAR_VALUE = 2014 AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2014
	,max(CASE WHEN YEAR_VALUE = 2014 AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2014


	,max(CASE WHEN YEAR_VALUE = 2015 AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2015
	,max(CASE WHEN YEAR_VALUE = 2015 AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2015
	,max(CASE WHEN YEAR_VALUE = 2015 AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2015


	,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_SUBGROUP = 'READING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_READING_2016
	,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_SUBGROUP = 'WRITING' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_WRITING_2016
	,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_SUBGROUP = 'MATHEMATICS' THEN TEST_SCORE_VALUE ELSE 0 END) AS SAT_MATH_2016



FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY
inner join
dbo.APSGrads g
on CAST(g.ID AS NVARCHAR) = STUDENT_id
WHERE 
1 = 1
AND TEST_NAME like 'SAT%'
AND LOCAL_SCHOOL_YEAR in ('2011-2012', '2012-2013', '2013-2014', '2014-2015', '2015-2016', '2016-2017')
--AND TEST_SUBGROUP IN ('Reading', 'Mathematics', 'Writing')
--AND TEST_GROUP = 'Test'
--and test_class = 'COMPONENT'
--and TEST_SUBJECT = 'overall'
--AND TEST_SUBGROUP IN ('TOT','Composite')
--AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUDENT_ID = '102903861'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	DTBL_CALENDAR_DATES.YEAR_VALUE,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP
	
)
--SELECT MAX(RN) FROM SAT
--SELECT * FROM SAT WHERE SIS_NUMBER = 244133286


,SAT_Results
as
(
SELECT
		--RN,
		SIS_NUMBER,
		--TEST_NAME,
		--TEST_SUBJECT,
		--TEST_STUDENT_GRADE,
		--TEST_PRODUCT,
		--TEST_GROUP,
		--TEST_SUBGROUP,
		
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2011 AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2011 ELSE 0 END) AS [SAT_READING_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2011 AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2011 ELSE 0 END) AS [SAT_WRITING_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2011 AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2011 ELSE 0 END) AS [SAT_MATH_SCORE_2011],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2012 AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2012 ELSE 0 END) AS [SAT_READING_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2012 AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2012 ELSE 0 END) AS [SAT_WRITING_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2012 AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2012 ELSE 0 END) AS [SAT_MATH_SCORE_2012],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2013 AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2013 ELSE 0 END) AS [SAT_READING_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2013 AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2013 ELSE 0 END) AS [SAT_WRITING_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2013 AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2013 ELSE 0 END) AS [SAT_MATH_SCORE_2013],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2014 AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2014 ELSE 0 END) AS [SAT_READING_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2014 AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2014 ELSE 0 END) AS [SAT_WRITING_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2014 AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2014 ELSE 0 END) AS [SAT_MATH_SCORE_2014],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2015 AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2015 ELSE 0 END) AS [SAT_READING_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2015 AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2015 ELSE 0 END) AS [SAT_WRITING_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2015 AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2015 ELSE 0 END) AS [SAT_MATH_SCORE_2015],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_SUBGROUP = 'READING' THEN SAT_READING_2016 ELSE 0 END) AS [SAT_READING_SCORE_2016],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_SUBGROUP = 'WRITING' THEN SAT_WRITING_2016 ELSE 0 END) AS [SAT_WRITING_SCORE_2016],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_SUBGROUP = 'MATHEMATICS' THEN SAT_MATH_2016 ELSE 0 END) AS [SAT_MATH_SCORE_2016]

FROM SAT

group by

	SIS_NUMBER
	
)

--select * from SAT_Results --where SIS_NUMBER = 102696358


/*-----------------------------------------------------------------*/
,PARCC
as
(
SELECT
	ROW_NUMBER() OVER(PARTITION BY STUDENT_id ORDER BY STUDENT_ID, YEAR_VALUE) AS RN,
    cast(STUDENT_ID as nvarchar) AS SIS_NUMBER
	--,CAST(G.ID AS NVARCHAR) AS id
    ,TEST_NAME
	,TEST_SUBJECT
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,YEAR_VALUE 
    ,TEST_PRODUCT 
    ,DTBL_CALENDAR_DATES.DATE_VALUE
    --,TEST_SCORE_VALUE 
    --,CAST(TEST_PRIMARY_RESULT AS NVARCHAR) AS PERFORMANCE_LEVEL
    --,CAST(SIS_SCHOOL_YEAR AS NVARCHAR) AS SCHOOL_YEAR
	,LOCAL_SCHOOL_YEAR
    --,CAST(TEST_CLASS AS nvarchar) AS TEST_CLASS
    ,TEST_GROUP
    ,CAST(TEST_SUBGROUP AS NVARCHAR) AS TEST_SUBGROUP
	,TEST_SCORE_VALUE

	,max(CASE WHEN YEAR_VALUE = 2008 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2008
	,max(CASE WHEN YEAR_VALUE = 2008 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2008
	,max(CASE WHEN YEAR_VALUE = 2008 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2008
	,max(CASE WHEN YEAR_VALUE = 2008 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2008
	,max(CASE WHEN YEAR_VALUE = 2008 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2008

	,max(CASE WHEN YEAR_VALUE = 2009 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2009
	,max(CASE WHEN YEAR_VALUE = 2009 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2009
	,max(CASE WHEN YEAR_VALUE = 2009 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2009
	,max(CASE WHEN YEAR_VALUE = 2009 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2009
	,max(CASE WHEN YEAR_VALUE = 2009 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2009

	,max(CASE WHEN YEAR_VALUE = 2010 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2010
	,max(CASE WHEN YEAR_VALUE = 2010 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2010
	,max(CASE WHEN YEAR_VALUE = 2010 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2010
	,max(CASE WHEN YEAR_VALUE = 2010 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2010
	,max(CASE WHEN YEAR_VALUE = 2010 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2010

	,max(CASE WHEN YEAR_VALUE = 2011 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2011
	,max(CASE WHEN YEAR_VALUE = 2011 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2011
	,max(CASE WHEN YEAR_VALUE = 2011 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2011
	,max(CASE WHEN YEAR_VALUE = 2011 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2011
	,max(CASE WHEN YEAR_VALUE = 2011 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2011

	,max(CASE WHEN YEAR_VALUE = 2012 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2012
	,max(CASE WHEN YEAR_VALUE = 2012 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2012
	,max(CASE WHEN YEAR_VALUE = 2012 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2012
	,max(CASE WHEN YEAR_VALUE = 2012 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2012
	,max(CASE WHEN YEAR_VALUE = 2012 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2012

	,max(CASE WHEN YEAR_VALUE = 2013 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2013
	,max(CASE WHEN YEAR_VALUE = 2013 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2013
	,max(CASE WHEN YEAR_VALUE = 2013 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2013
	,max(CASE WHEN YEAR_VALUE = 2013 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2013
	,max(CASE WHEN YEAR_VALUE = 2013 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2013

	,max(CASE WHEN YEAR_VALUE = 2014 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2014
	,max(CASE WHEN YEAR_VALUE = 2014 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2014
	,max(CASE WHEN YEAR_VALUE = 2014 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2014
	,max(CASE WHEN YEAR_VALUE = 2014 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2014
	,max(CASE WHEN YEAR_VALUE = 2014 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2014

	,max(CASE WHEN YEAR_VALUE = 2015 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2015
	,max(CASE WHEN YEAR_VALUE = 2015 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2015
	,max(CASE WHEN YEAR_VALUE = 2015 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2015
	,max(CASE WHEN YEAR_VALUE = 2015 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2015
	,max(CASE WHEN YEAR_VALUE = 2015 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2015

	,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'ELA' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ELA_2016
	,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'Algebra I' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_I_2016
	,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'Algebra II' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_ALGEBRA_II_2016
	,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'Geometry' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_GEOMETRY_2016
	,max(CASE WHEN YEAR_VALUE = 2016 AND TEST_GROUP = 'Integrated Mathematics III' THEN TEST_SCORE_VALUE ELSE 0 END) AS PARCC_INT_MATH_2016

FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY
inner join
dbo.APSGrads g
on CAST(g.ID AS NVARCHAR) = STUDENT_id
WHERE 
1 = 1
AND TEST_NAME like 'PARCC%'
AND LOCAL_SCHOOL_YEAR in ('2008-2009', '2009-2010', '2010-2011','2011-2012', '2012-2013', '2013-2014', '2014-2015', '2015-2016', '2016-2017')
AND TEST_SUBGROUP IN ('Overall')
--AND TEST_GROUP = 'Test'
--and test_class = 'COMPONENT'
--and TEST_SUBJECT = 'overall'
--AND TEST_SUBGROUP IN ('TOT','Composite')
--AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUDENT_ID = '318463353'
GROUP BY
	STUDENT_ID,
	DTBL_CALENDAR_DATES.DATE_VALUE,
	DTBL_CALENDAR_DATES.YEAR_VALUE,
	TEST_NAME,
	DTBL_SCHOOLS.SCHOOL_CODE,
	FTBL_TEST_SCORES.TEST_STUDENT_GRADE,
	DTBL_TESTS.TEST_PRODUCT,
	DTBL_SCHOOL_DATES.LOCAL_SCHOOL_YEAR,
	DTBL_TESTS.TEST_GROUP,
	DTBL_TESTS.TEST_SUBJECT,
	DTBL_TESTS.TEST_SUBGROUP,
	test_score_value
	
)
--SELECT MAX(RN) FROM PARCC
--SELECT * FROM PARCC WHERE SIS_NUMBER = 100020064 ORDER BY YEAR_VALUE --where SIS_NUMBER in ('61740', '71975', '76476', '186878', '187738', '188747', '189884')

,PARCC_Results
as
(
SELECT
		--RN,
		SIS_NUMBER,
		--TEST_NAME,
		--TEST_SUBJECT,
		--TEST_STUDENT_GRADE,
		--TEST_PRODUCT,
		--TEST_GROUP,
		--TEST_SUBGROUP,

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2008 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2008 ELSE 0 END) AS [PARCC_ELA_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2008 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2008 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2008 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2008 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2008 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2008 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2008],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2008 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2008 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2008],
		
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2009 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2009 ELSE 0 END) AS [PARCC_ELA_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2009 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2009 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2009 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2009 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2009 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2009 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2009],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2009 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2009 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2009],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2010 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2010 ELSE 0 END) AS [PARCC_ELA_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2010 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2010 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2010 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2010 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2010 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2010 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2010],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2010 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2010 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2010],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2011 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2011 ELSE 0 END) AS [PARCC_ELA_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2011 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2011 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2011 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2011 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2011 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2011 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2011],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2011 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2011 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2011],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2012 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2012 ELSE 0 END) AS [PARCC_ELA_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2012 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2012 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2012 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2012 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2012 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2012 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2012],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2012 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2012 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2012],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2013 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2013 ELSE 0 END) AS [PARCC_ELA_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2013 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2013 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2013 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2013 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2013 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2013 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2013],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2013 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2013 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2013],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2014 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2014 ELSE 0 END) AS [PARCC_ELA_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2014 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2014 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2014 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2014 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2014 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2014 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2014],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2014 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2014 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2014],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2015 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2015 ELSE 0 END) AS [PARCC_ELA_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2015 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2015 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2015 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2015 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2015 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2015 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2015],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2015 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2015 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2015],

		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'ELA' THEN PARCC_ELA_2016 ELSE 0 END) AS [PARCC_ELA_SCORE_2016],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'Algebra I' THEN PARCC_ALGEBRA_I_2016 ELSE 0 END) AS [PARCC_ALGEBRA_I_SCORE_2016],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'Algebra II' THEN PARCC_ALGEBRA_II_2016 ELSE 0 END) AS [PARCC_ALGEBRA_II_SCORE_2016],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'Geometry' THEN PARCC_GEOMETRY_2016 ELSE 0 END) AS [PARCC_GEOMETRY_SCORE_2016],
		MAX(CASE WHEN RN = 1  or RN = 2  OR RN = 3 OR RN = 4 OR RN = 5 OR RN = 6 AND YEAR_VALUE = 2016 AND TEST_GROUP = 'Integrated Mathematics III' THEN PARCC_INT_MATH_2016 ELSE 0 END) AS [PARCC_INT_MATH_SCORE_2016]

FROM PARCC

group by

	SIS_NUMBER
)
--SELECT * FROM PARCC_Results

,All_Test_Results
as
(
select
	CAST(G.ID AS NVARCHAR) AS SIS_NUMBER,
	A.ACT_SCORE_2008,
	A.ACT_SCORE_2009,
	A.ACT_SCORE_2010,
	A.ACT_SCORE_2011,
	A.ACT_SCORE_2012,
	A.ACT_SCORE_2013,
	A2.ACT_SCORE_2014, 
	A2.ACT_SCORE_2015,
	A2.ACT_SCORE_2016,
	S.SAT_MATH_SCORE_2011,
	S.SAT_READING_SCORE_2011,
	S.SAT_MATH_SCORE_2012,
	S.SAT_READING_SCORE_2012,
	S.SAT_MATH_SCORE_2013,
	S.SAT_READING_SCORE_2013,
	S.SAT_MATH_SCORE_2014,
	S.SAT_READING_SCORE_2014,
	S.SAT_MATH_SCORE_2015,
	S.SAT_READING_SCORE_2015,
	S.SAT_MATH_SCORE_2016,
	S.SAT_READING_SCORE_2016,
	P.PARCC_ELA_SCORE_2008,
	P.PARCC_ALGEBRA_I_SCORE_2008,
	P.PARCC_ALGEBRA_II_SCORE_2008,
	P.PARCC_GEOMETRY_SCORE_2008,
	P.PARCC_INT_MATH_SCORE_2008,
	P.PARCC_ELA_SCORE_2009,
	P.PARCC_ALGEBRA_I_SCORE_2009,
	P.PARCC_ALGEBRA_II_SCORE_2009,
	P.PARCC_GEOMETRY_SCORE_2009,
	P.PARCC_INT_MATH_SCORE_2009,
	P.PARCC_ELA_SCORE_2010,
	P.PARCC_ALGEBRA_I_SCORE_2010,
	P.PARCC_ALGEBRA_II_SCORE_2010,
	P.PARCC_GEOMETRY_SCORE_2010,
	P.PARCC_INT_MATH_SCORE_2010,
	P.PARCC_ELA_SCORE_2011,
	P.PARCC_ALGEBRA_I_SCORE_2011,
	P.PARCC_ALGEBRA_II_SCORE_2011,
	P.PARCC_GEOMETRY_SCORE_2011,
	P.PARCC_INT_MATH_SCORE_2011,
	P.PARCC_ELA_SCORE_2012,
	P.PARCC_ALGEBRA_I_SCORE_2012,
	P.PARCC_ALGEBRA_II_SCORE_2012,
	P.PARCC_GEOMETRY_SCORE_2012,
	P.PARCC_INT_MATH_SCORE_2012,
	P.PARCC_ELA_SCORE_2013,
	P.PARCC_ALGEBRA_I_SCORE_2013,
	P.PARCC_ALGEBRA_II_SCORE_2013,
	P.PARCC_GEOMETRY_SCORE_2013,
	P.PARCC_INT_MATH_SCORE_2013,
	P.PARCC_ELA_SCORE_2014,
	P.PARCC_ALGEBRA_I_SCORE_2014,
	P.PARCC_ALGEBRA_II_SCORE_2014,
	P.PARCC_GEOMETRY_SCORE_2014,
	P.PARCC_INT_MATH_SCORE_2014,
	P.PARCC_ELA_SCORE_2015,
	P.PARCC_ALGEBRA_I_SCORE_2015,
	P.PARCC_ALGEBRA_II_SCORE_2015,
	p.PARCC_GEOMETRY_SCORE_2015,
	P.PARCC_INT_MATH_SCORE_2015,
	P.PARCC_ELA_SCORE_2016,
	P.PARCC_ALGEBRA_I_SCORE_2016,
	P.PARCC_ALGEBRA_II_SCORE_2016,
	P.PARCC_GEOMETRY_SCORE_2016,
	P.PARCC_INT_MATH_SCORE_2016

from
	dbo.APSGrads G
LEFT JOIN
	ACT2008_2013_RESULTS A
ON
	A.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	ACT2004_2016_RESULTS A2
ON
	A2.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	SAT_Results S
ON
	S.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
LEFT JOIN
	PARCC_Results P
ON
	P.SIS_NUMBER = CAST(G.ID AS NVARCHAR)
)
--TRUNCATE TABLE DBO.ALLTESTRESULTS
SELECT * INTO DBO.ALLTESTRESULTS FROM All_Test_Results 

--SELECT * FROM DBO.ALLTESTRESULTS WHERE SIS_NUMBER = 102952116

