SELECT
	SynObject.NAMESPACE
	,SynObject.NAME AS ObjectName
	,Prop.PROPERTY_NAME
	,Prop.TYPE
	,Prop.LOOKUP_TYPE
	,Prop.LABEL
	,Bind.TABLE_NAME
	,Bind.COLUMN_NAME
FROM
	rev.REV_BOD_OBJECT AS SynObject
	INNER JOIN
	rev.REV_BOD_OBJECT_PROP As Prop
	ON
	SynObject.BOD_OBJECT_GU = Prop.BOD_OBJECT_GU
	INNER JOIN
	rev.REV_BOD_OBJECT_PROP_BIND AS Bind
	ON
	Prop.BOD_OBJECT_PROP_GU = Bind.BOD_OBJECT_PROP_GU
--WHERE
--	SynObject.NAME LIKE '%ELLH%'