SELECT
	Organization.ORGANIZATION_NAME
	,GradeLevel.VALUE_DESCRIPTION AS GradeLevel
	,COUNT(*) AS TheCoount
FROM
	APS.PrimaryEnrollmentsAsOf('7/8/2014') AS Enroll
	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS OrgYear
	ON
	Enroll.ORGANIZATION_YEAR_GU = OrgYear.ORGANIZATION_YEAR_GU

	INNER JOIN
	rev.REV_ORGANIZATION AS Organization
	ON
	OrgYear.ORGANIZATION_GU = Organization.ORGANIZATION_GU

	INNER JOIN
	APS.LookupTable('K12','Grade') AS GradeLevel
	ON
	Enroll.GRADE = GradeLevel.VALUE_CODE

WHERE
	GRADE BETWEEN 100 AND 130
GROUP BY
	Organization.ORGANIZATION_NAME
	,GradeLevel.VALUE_DESCRIPTION 
	,GradeLevel.LIST_ORDER
ORDER BY
	Organization.ORGANIZATION_NAME
	,GradeLevel.LIST_ORDER
