SELECT
--COUNT(*)
--/*
	Student.SIS_NUMBER
	,Student.STATE_STUDENT_NUMBER
	,Organization.ORGANIZATION_NAME
	,School.SCHOOL_CODE
	,School.STATE_SCHOOL_CODE
	,SSY.ENTER_DATE AS EnrollmentEnterDate
	,SSY.LEAVE_DATE AS EnrollmentLeaveDate
	,SSY.SUMMER_WITHDRAWL_CODE
	,SSY.SUMMER_WITHDRAWL_DATE
	,SSY.EXCLUDE_ADA_ADM
	,Grades.VALUE_DESCRIPTION AS GradeLevel

	,DCM.COURSE_ID
	,DCM.STATE_COURSE_CODE
	,DCM.COURSE_TITLE
	,Section.SECTION_ID
	,Staff.BADGE_NUM AS EmployeeNumber

	,Class.ENTER_DATE AS ClassEnterDate
	,Class.Leave_DATE AS ClassLeaveDate

	,ROW_NUMBER() OVER (PARTITION BY SSY.STUDENT_SCHOOL_YEAR_GU ORDER BY Class.ENTER_DATE DESC, Class.LEAVE_DATE DESC) AS ClassRowNum

	,CASE 
		WHEN Section.SECTION_ID BETWEEN '2000' AND '2999' THEN 'K3+' 
		WHEN Section.SECTION_ID BETWEEN '3000' AND '3999' THEN 'Remedial'
		WHEN Section.SECTION_ID BETWEEN '5000' AND '5999' THEN 'StartSmart' 
		ELSE 'Unknown'
	END AS Program
--*/
FROM 
	rev.EPC_STU_SCH_YR AS SSY
	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS OrgYear
	ON SSY.ORGANIZATION_YEAR_GU = OrgYear.ORGANIZATION_YEAR_GU
	AND OrgYear.YEAR_GU = 'AA26EA9A-B72D-45B6-8D7F-F1078FB756EA'--(select YEAR_GU from rev.REV_YEAR WHERE SCHOOL_YEAR = 2013 AND EXTENSION = 'S')

	INNER JOIN 
	rev.EPC_STU AS Student
	ON SSY.STUDENT_GU = Student.STUDENT_GU

	INNER JOIN 
	rev.EPC_SCH AS School
	ON OrgYear.ORGANIZATION_GU = School.ORGANIZATION_GU

	INNER JOIN rev.EPC_STU_CLASS AS Class
	ON Class.STUDENT_SCHOOL_YEAR_GU  = SSY.STUDENT_SCHOOL_YEAR_GU

	INNER JOIN 
	rev.EPC_SCH_YR_SECT AS Section
	ON Class.SECTION_GU = Section.SECTION_GU

	INNER JOIN 
	rev.EPC_SCH_YR_CRS AS SchoolYearCourse
	ON SchoolYearCourse.SCHOOL_YEAR_COURSE_GU = Section.SCHOOL_YEAR_COURSE_GU

	INNER JOIN 
	rev.EPC_CRS AS DCM 
	ON 
	DCM.COURSE_GU = SchoolYearCourse.COURSE_GU

	INNER JOIN
	REV.REV_ORGANIZATION AS Organization
	ON
	OrgYear.ORGANIZATION_GU = Organization.ORGANIZATION_GU

	INNER JOIN
	APS.LookupTable('K12','GRADE') AS Grades
	ON SSY.GRADE = Grades.VALUE_CODE

	LEFT JOIN
	rev.EPC_STAFF_SCH_YR AS StaffSchoolYear
	ON
	Section.STAFF_SCHOOL_YEAR_GU = StaffSchoolYear.STAFF_SCHOOL_YEAR_GU

	LEFT JOIN
	rev.EPC_STAFF AS Staff
	ON
	StaffSchoolYear.STAFF_GU = Staff.STAFF_GU
WHERE
	SSY.GRADE BETWEEN 0 AND 150
--	Section.SECTION_ID BETWEEN '2000' AND '2999'
--	OR Section.SECTION_ID BETWEEN '3000' AND '3999'
--	OR Section.SECTION_ID BETWEEN '5000' AND '5999'
ORDER BY
	School.SCHOOL_CODE
	,Grades.LIST_ORDER
	,Student.SIS_NUMBER
	,Class.ENTER_DATE DESC