SELECT NAME, HIST.*  FROM

rev.EPC_STU_CRS_HIS AS HIST
INNER JOIN
rev.EPC_SCH_NON_DST AS NONSCH
ON
NONSCH.SCHOOL_NON_DISTRICT_GU = HIST.SCHOOL_NON_DISTRICT_GU

WHERE
NONSCH.NAME IN ('CUBA ES, NM', 'CUBA MS, NM')
--NONSCH.NAME LIKE ('CUBA')