BEGIN TRAN

UPDATE [COURSE_HISTORY]
	SET [COURSE_HISTORY].[SCHOOL_IN_DISTRICT_GU] = [ENROLLMENTS].[ORGANIZATION_GU]
	,[COURSE_HISTORY].[SCHOOL_NON_DISTRICT_GU] = NULL

--SELECT
--	[Organization].[ORGANIZATION_NAME] AS [IN_DISTRICT_NAME]
--	,[NON_DISTRICT].[NAME] AS [NON_DISTRICT_NAME]
--	,[COURSE_HISTORY].[SCHOOL_YEAR]
--	,[COURSE_HISTORY].[TERM_CODE]
--	,[COURSE_HISTORY].[COURSE_ID]
--	,[COURSE_HISTORY].[COURSE_TITLE]
--	,[STUDENT].[SIS_NUMBER]
--	,[STUDENT].[FIRST_NAME]
--	,[STUDENT].[LAST_NAME]
--	,[STUDENT].[MIDDLE_NAME]
	
--	--,CONVERT(VARCHAR(2),[COURSE_HISTORY].[CALENDAR_MONTH]) + '/01/' + CONVERT(VARCHAR(4),[COURSE_HISTORY].[CALENDAR_YEAR])
	
--	,[ENROLLMENTS].[GRADE]
--	,[ENROLLMENTS].[SCHOOL_CODE]
--	,[ENROLLMENTS].[SCHOOL_NAME]
--	,[ENROLLMENTS].[ENTER_DATE]
--	,[ENROLLMENTS].[LEAVE_DATE]
	
FROM
	rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
	
	LEFT OUTER JOIN
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[COURSE_HISTORY].[SCHOOL_IN_DISTRICT_GU] = [Organization].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN
	rev.EPC_SCH_NON_DST AS [NON_DISTRICT]
	ON
	[COURSE_HISTORY].[SCHOOL_NON_DISTRICT_GU] = [NON_DISTRICT].[SCHOOL_NON_DISTRICT_GU]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[COURSE_HISTORY].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU], [SCHOOL_YEAR], [EXTENSION] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
	WHERE
		EXCLUDE_ADA_ADM IS NULL
	) AS [ENROLLMENTS]
	ON
	[COURSE_HISTORY].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]
	--AND CONVERT(DATETIME,CONVERT(VARCHAR(2),[COURSE_HISTORY].[CALENDAR_MONTH]) + '/01/' + CONVERT(VARCHAR(4),[COURSE_HISTORY].[CALENDAR_YEAR])) BETWEEN [ENROLLMENTS].[ENTER_DATE] AND [ENROLLMENTS].[LEAVE_DATE]
	AND [COURSE_HISTORY].[SCHOOL_YEAR] = [ENROLLMENTS].[SCHOOL_YEAR]
	AND [ENROLLMENTS].[EXTENSION] = 'R'
	AND [ENROLLMENTS].[RN] = 1
	
	
WHERE
	[Organization].[ORGANIZATION_NAME] LIKE '%GRADPOINT%'
	OR [NON_DISTRICT].[NAME] LIKE '%GRADPOINT%'
	
--ROLLBACK
COMMIT
	