
--2013 -- 1E61EA89-3410-49F8-909B-1B749957EDDA
--2014 -- 26F066A3-ABFC-4EDB-B397-43412EDABC8B
--2015 -- BCFE2270-A461-4260-BA2B-0087CB8EC26A
--2016 -- F7D112F7-354D-4630-A4BC-65F586BA42EC


SELECT 
	SCHOOL_YEAR, SIS_NUMBER, GETENROLL.SCHNBR, GRADE, MEMBER_DAYS, [1/2-day Unexcused Absences], [Full-day Unexcused Absences], [1/2-day Excused Absences], [Full-Day Excused Absences]

 FROM 

(
SELECT 
	ENROLLS.SCHOOL_YEAR, ENROLLS.SIS_NUMBER, GETMEM.SCHNBR, SUM(CAST(GETMEM.MEMBERDAYS AS INT)) AS MEMBER_DAYS
	,ENROLLS.GRADE
 FROM 
(
SELECT * FROM 
APS.LatestPrimaryEnrollmentInYear('1E61EA89-3410-49F8-909B-1B749957EDDA') AS LATEST
WHERE
SCHOOL_CODE IN  ('410', '413', '416', '420', '427', '440', '448', '470')
) AS ENROLLS

INNER JOIN 
dbo.ATTENDANCE_2013 AS GETMEM
ON
ENROLLS.SIS_NUMBER = GETMEM.IDNBR
AND ENROLLS.SCHOOL_CODE = GETMEM.SCHNBR

INNER JOIN 
(SELECT 
	SUM(CAST(MEMBERDAYS AS INT)) AS TOTAL_MEMBER, IDNBR 
FROM 
dbo.ATTENDANCE_2013 
WHERE NONADA = ''
GROUP BY IDNBR
) AS TOTALS
ON
ENROLLS.SIS_NUMBER = TOTALS.IDNBR

GROUP BY ENROLLS.SCHOOL_YEAR, ENROLLS.SIS_NUMBER, GETMEM.SCHNBR, ENROLLS.GRADE
) AS GETENROLL

LEFT HASH JOIN 
(
SELECT
	
	 att.IDNBR as [Student APS ID],
	 ATT.SCHNBR,
	 case 
		when sa.ID_NBR is null then '0.00' else	sa.UNEXCUSED_HALF_DAY end as [1/2-day Unexcused Absences],
	 case 
		when sa.ID_NBR is null then '0.00' else SA.UNEXCUSED_FULL_DAY end as [Full-day Unexcused Absences],
	 case 
		when sa.ID_NBR is null then '0.00' else SA.EXCUSED_HALF_DAY end as [1/2-day Excused Absences],
	 case 
		when sa.ID_NBR is null then '0.00' else SA.EXCUSED_FULL_DAY end as [Full-Day Excused Absences]
	 
FROM 
	dbo.ATTENDANCE_2013 ATT
LEFT join
	(SELECT SA.ID_NBR, SA.SCH_NBR, 

	 MAX(CASE WHEN ATT_TYPE = 'E' THEN HALF_DAY ELSE '0.00' END) AS EXCUSED_HALF_DAY,
	 MAX(CASE WHEN ATT_TYPE = 'E' THEN FULL_DAY ELSE '0.00' END) AS EXCUSED_FULL_DAY,
	  MAX(CASE WHEN ATT_TYPE = 'U' THEN HALF_DAY ELSE '0.00' END) AS UNEXCUSED_HALF_DAY,
	 MAX(CASE WHEN ATT_TYPE = 'U' THEN FULL_DAY ELSE '0.00' END) AS UNEXCUSED_FULL_DAY

 FROM 
[180-SMAXODS-01.APS.EDU.ACTD].PR.dbo.ATTENDANCE_2013_2 AS SA

GROUP BY ID_NBR, SCH_NBR
) AS SA

on
	sa.ID_NBR = att.IDNBR COLLATE DATABASE_DEFAULT
	and sa.SCH_NBR= att.SCHNBR  COLLATE DATABASE_DEFAULT
) AS GETATT

ON
GETENROLL.SIS_NUMBER = GETATT.[Student APS ID]
AND GETENROLL.SCHNBR = GETATT.SCHNBR





order by SIS_NUMBER


