EXECUTE AS LOGIN='QueryFileUser'
GO


BEGIN TRANSACTION

UPDATE rev.EPC_STREET
SET GRID_GU = GRID_GU, STREET_TYPE = T3.VALUE_CODE, STREET_POST_DIRECTION = T3.STREET_POST_DIRECTION, CITY = T3.CITY 
,ADD_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F'
,ADD_DATE_TIME_STAMP = GETDATE()

FROM (

SELECT 
	LU2.VALUE_CODE
	,LU2.VALUE_DESCRIPTION
	,T2.*
 FROM( 
SELECT
	T1.*
	,STREET.*
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from ADDCHGSTREET.csv'
                ) AS [T1]

LEFT JOIN 
	 (SELECT STREET1.STREET_LOW_ADDRESS AS STREET_LOW, 
	 STREET1.STREET_NAME AS STREET
	 ,STREET1.CITY AS STREET_CITY
	 ,STREET1.STATE AS STREET_STATE
	 ,STREET1.ZIP_5 AS ZIP
	 ,STREET1.SCHOOL_YEAR
	 ,STREET1.STREET_GU
	 , VALUE_DESCRIPTION AS STREET_TYPE_DESCR 
	 
	 FROM 
	 rev.EPC_STREET AS STREET1
	 LEFT JOIN 
	 [APS].[LookupTable]('K12.AddressInfo','STREET_TYPE') AS LU
	 ON
	 LU.VALUE_CODE = [STREET_TYPE] 
	 WHERE SCHOOL_YEAR = 2016
	 ) AS STREET
ON
ISNULL(CAST(T1.STREET_LOW_ADDRESS AS INT),'') = ISNULL(STREET.STREET_LOW,'')
AND ISNULL(T1.STREET_NAME,'') = ISNULL(STREET.STREET,'')
--AND ISNULL(T1.STREET_TYPE,'') = ISNULL(STREET.STREET_TYPE_DESCR,'') 
--AND ISNULL(T1.STREET_POST_DIRECTION,'') = ISNULL(STREET.STREET_POST_DIRECTION,'')
AND ISNULL(T1.CITY,'') = ISNULL(STREET.STREET_CITY,'')
AND ISNULL(T1.STATE,'') = ISNULL(STREET.STREET_STATE,'')
AND ISNULL(T1.ZIP_5,'') = ISNULL(STREET.ZIP,'')
AND STREET.SCHOOL_YEAR = 2016

WHERE
STREET_GU IS NOT NULL
) AS T2

LEFT JOIN 
	 [APS].[LookupTable]('K12.AddressInfo','STREET_TYPE') AS LU2
	 ON
	 LU2.VALUE_DESCRIPTION = T2.STREET_TYPE


) AS T3

WHERE
rev.EPC_STREET.STREET_GU = T3.STREET_GU

ROLLBACK

REVERT
GO