
/*********************************************************************************
Created by Debbie Ann Chavez
Date  8/15/2016

This pulls active staff from Lawson and for Specific Synergy Staff Types, it creates a Staff School Year Entry. 
These are the specific TYPE’s that are hardcoded:  ('SSS', 'SCA', 'SA', 'TE')

And this only runs for locations > 200.  

--Change School Year and YEAR GU - hard coded

*This was needed because LDAP was not creating some school year entries.


**********************************************************************************/



BEGIN TRANSACTION 


INSERT INTO REV.EPC_STAFF_SCH_YR
( [STAFF_SCHOOL_YEAR_GU] ,[STAFF_GU] ,[ORGANIZATION_YEAR_GU] ,[SIS_NUMBER] ,[HOMEROOM_GU],[DEPARTMENT] ,[CHANGE_DATE_TIME_STAMP]
      ,[CHANGE_ID_STAMP] ,[ADD_DATE_TIME_STAMP] ,[ADD_ID_STAMP] ,[FTE] ,[JOB_CLASS]
	  )

SELECT 
	NEWID() AS STAFF_SCHOOL_YEAR_GU
	,T2.STAFF_GU AS STAFF_GU
	,T2.ORGANIZATION_YEAR_GU AS ORGANIZATION_YEAR_GU
	,EMPLOYEE AS SIS_NUMBER
	,NULL AS HOMEROOM_GU
	,NULL AS DEPARTMENT
	,NULL AS CHANGE_DATE_TIME_STAMP
	,NULL AS CHANGE_ID_STAMP
	,GETDATE() AS ADD_DATE_TIME_STAMP
	,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS ADD_ID_STAMP
	,NULL AS FTE
	,NULL AS JOB_CLASS



 
--SELECT STAFF_GU, ORGANIZATION_GU, ORGANIZATION_YEAR_GU
--, EMPLOYEE, LOCATION

 FROM 
(
SELECT DISTINCT T1.EMPLOYEE, T1.LOCATION, T1.STAFF_GU,SCH.ORGANIZATION_GU, RORGYR.ORGANIZATION_YEAR_GU FROM 
(
SELECT * FROM 
[180-SMAXODS-01.APS.EDU.ACTD].LAWSON.APS.ActiveEmployeesAllAssignments AS ACTIVES
INNER JOIN 
(SELECT STAFF_GU, STATE_ID, [TYPE], BADGE_NUM
FROM REV.EPC_STAFF
WHERE [TYPE] IN ('SSS', 'SCA', 'SA', 'TE')
) AS STF
ON
CAST(ACTIVES.EMPLOYEE AS VARCHAR) = STF.STATE_ID
) AS T1

LEFT JOIN 
(
SELECT STAFF_GU, ORGANIZATION_NAME, SCHOOL_YEAR, STFYR.STAFF_SCHOOL_YEAR_GU, YRS.YEAR_GU
 FROM 
REV.EPC_STAFF_SCH_YR AS STFYR

INNER JOIN 
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
STFYR.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN 
REV.REV_YEAR AS YRS
ON
ORGYR.YEAR_GU = YRS.YEAR_GU
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

WHERE
YRS.SCHOOL_YEAR = 2016
) AS STFYR

ON
STFYR.STAFF_GU = T1.STAFF_GU

INNER JOIN 
REV.EPC_SCH AS SCH
ON
T1.LOCATION = SCH.SCHOOL_CODE

INNER JOIN
REV.REV_ORGANIZATION_YEAR AS RORGYR
ON
RORGYR.ORGANIZATION_GU = SCH.ORGANIZATION_GU
AND RORGYR.YEAR_GU = 'F7D112F7-354D-4630-A4BC-65F586BA42EC'

WHERE
STFYR.STAFF_SCHOOL_YEAR_GU IS NULL
AND LOCATION > '200'
) AS T2

ROLLBACK