

/************************************************************************************
CREATED BY DEBBIE ANN CHAVEZ
DATE 8/15/2016

This sets a user's focus to what their Usergroup school they have assigned only if they have a staff school year entry.
  Example 'UPDATE - Rio' Will set to Focus to Rio.  

Important to remember this only sets Focus for singleton users.  Meaning only one school assignment.  
If a user has multiple assignments at different schools Focus has to be set manually per our discussion today

************************************************************************************/

BEGIN TRANSACTION

UPDATE rev.REV_USER 
SET FOCUS_ORGANIZATION_GU = T10.ORGANIZATION_GU, FOCUS_YEAR_GU = T10.YEAR_GU

 FROM 
--JUST PULL THE EMPLOYEES
(SELECT STFYR.* FROM 

(

SELECT T3.* FROM 
(
SELECT * FROM (

SELECT 
	ROW_NUMBER() OVER (PARTITION BY LOGIN_NAME ORDER BY LOGIN_NAME DESC) AS RN
	,LOGIN_NAME
	,STF.[TYPE]
	,USERGROUP_NAME
	,ORGANIZATION_NAME
	,CASE 
		WHEN USERGROUP_NAME LIKE '%FAMILY SCHOOL%' AND ORGANIZATION_NAME LIKE '%FAMILY SCHOOL%' THEN 1
		WHEN USERGROUP_NAME LIKE '%EUBANK%' AND ORGANIZATION_NAME LIKE '%EUBANK%' THEN 1
	
	ELSE 0 END AS KEEP_ME
	
	,USR.USER_GU,
	FOCUS_YEAR_GU
	,ORG.ORGANIZATION_GU
	,YEAR_GU
	,USRGRP.USER_USERGROUP_GU
	
	--,usrgrp.*
 FROM 
REV.REV_USER AS USR
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
USR.FOCUS_ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN 
REV.REV_YEAR AS YRS
ON
YRS.YEAR_GU = USR.FOCUS_YEAR_GU
AND YRS.SCHOOL_YEAR = '2016'

LEFT JOIN 
rev.REV_USER_USERGROUP AS USRGRP
ON
USR.USER_GU = USRGRP.USER_GU
INNER JOIN 
REV.REV_USERGROUP AS USRG
ON
USRG.USERGROUP_GU = USRGRP.USERGROUP_GU
AND USERGROUP_NAME LIKE 'UPDATE%'
AND USERGROUP_NAME NOT LIKE '%District%'
AND USERGROUP_NAME NOT LIKE '%Special Education%'
AND USERGROUP_NAME NOT LIKE '%TEP%'
AND USERGROUP_NAME NOT LIKE '%Transition%'
AND USERGROUP_NAME NOT LIKE '%Interim%'
AND USERGROUP_NAME NOT LIKE '%Summer%'
AND USERGROUP_NAME NOT LIKE '%Homebound%'
AND USERGROUP_NAME NOT LIKE '%Child Find%'
AND USERGROUP_NAME NOT LIKE '%Continuation%'

INNER JOIN 
rev.EPC_STAFF AS STF
ON
STF.STAFF_GU = USR.USER_GU

WHERE 
SUBSTRING(USERGROUP_NAME,10,3) != SUBSTRING(ORGANIZATION_NAME,1,3)

) AS T1

WHERE
KEEP_ME = 0
) AS T3

LEFT JOIN 
(SELECT * FROM (

SELECT 
	ROW_NUMBER() OVER (PARTITION BY LOGIN_NAME ORDER BY LOGIN_NAME DESC) AS RN
	,LOGIN_NAME
	,STF.[TYPE]
	,USERGROUP_NAME
	,ORGANIZATION_NAME
	,CASE 
		WHEN USERGROUP_NAME LIKE '%FAMILY SCHOOL%' AND ORGANIZATION_NAME LIKE '%FAMILY SCHOOL%' THEN 1
		WHEN USERGROUP_NAME LIKE '%EUBANK%' AND ORGANIZATION_NAME LIKE '%EUBANK%' THEN 1
	
	ELSE 0 END AS KEEP_ME
	
	,USR.USER_GU,
	USR.FOCUS_YEAR_GU
	,YEAR_GU
	
	--,usrgrp.*
 FROM 
REV.REV_USER AS USR
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
USR.FOCUS_ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN 
REV.REV_YEAR AS YRS
ON
YRS.YEAR_GU = USR.FOCUS_YEAR_GU
AND YRS.SCHOOL_YEAR = '2016'

LEFT JOIN 
rev.REV_USER_USERGROUP AS USRGRP
ON
USR.USER_GU = USRGRP.USER_GU
INNER JOIN 
REV.REV_USERGROUP AS USRG
ON
USRG.USERGROUP_GU = USRGRP.USERGROUP_GU
AND USERGROUP_NAME LIKE 'UPDATE%'
AND USERGROUP_NAME NOT LIKE '%District%'
AND USERGROUP_NAME NOT LIKE '%Special Education%'
AND USERGROUP_NAME NOT LIKE '%TEP%'
AND USERGROUP_NAME NOT LIKE '%Transition%'
AND USERGROUP_NAME NOT LIKE '%Interim%'
AND USERGROUP_NAME NOT LIKE '%Summer%'
AND USERGROUP_NAME NOT LIKE '%Homebound%'
AND USERGROUP_NAME NOT LIKE '%Child Find%'
AND USERGROUP_NAME NOT LIKE '%Continuation%'

INNER JOIN 
rev.EPC_STAFF AS STF
ON
STF.STAFF_GU = USR.USER_GU

WHERE 
SUBSTRING(USERGROUP_NAME,10,3) != SUBSTRING(ORGANIZATION_NAME,1,3)

) AS T1

WHERE
KEEP_ME = 0
AND RN > 1
) AS T4

ON
T3.LOGIN_NAME = T4.LOGIN_NAME

WHERE
T4.LOGIN_NAME IS NULL
) AS MISSING


/***************************************************************************************
* PULL ORG AND YEAR FROM STAFF SCHOOL YEAR ENTRY TO POPULATE USER FOCUS ORG AND YEAR 
***************************************************************************************/
INNER JOIN 

(SELECT ORGANIZATION_NAME, YRS.SCHOOL_YEAR,STFYR.STAFF_GU, ORGYR.ORGANIZATION_YEAR_GU
	,ORG.ORGANIZATION_GU, YRS.YEAR_GU
 FROM 
	rev.EPC_STAFF_SCH_YR AS STFYR
	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	STFYR.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
	INNER JOIN 
	rev.EPC_STAFF AS STF
	ON
	STF.STAFF_GU = STFYR.STAFF_GU
	INNER JOIN 
	rev.REV_ORGANIZATION AS ORG
	ON
	ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
	INNER JOIN 
	rev.REV_YEAR AS YRS
	ON
	ORGYR.YEAR_GU = YRS.YEAR_GU
	WHERE
	SCHOOL_YEAR = 2016
	) AS STFYR


	--match name of security group to staff school year
	ON
	MISSING.USER_GU = STFYR.STAFF_GU
	AND SUBSTRING(MISSING.USERGROUP_NAME,10,3) = SUBSTRING(STFYR.ORGANIZATION_NAME,1,3)

) AS T10
--WHERE
--STFYR.STAFF_GU IS NULL

WHERE
T10.STAFF_GU = REV.REV_USER.USER_GU

ROLLBACK