

/************************************************************************************
CREATED BY DEBBIE ANN CHAVEZ
DATE 8/15/2016

This sets a user's focus to what their Usergroup school they have assigned only if they have a staff school year entry.
  Example 'UPDATE - Rio' Will set to Focus to Rio.  

Important to remember this only sets Focus for singleton users.  Meaning only one school assignment.  
If a user has multiple assignments at different schools Focus has to be set manually per our discussion today

************************************************************************************/

BEGIN TRANSACTION

UPDATE rev.REV_USER 
SET FOCUS_ORGANIZATION_GU = T10.ORGANIZATION_GU, FOCUS_YEAR_GU = T10.YEAR_GU

 FROM 
--JUST PULL THE EMPLOYEES
(SELECT T4.* FROM 

/****************************************************************************
* THIS PULLS ONLY SINGLETON LOGIN USERS WHERE THEY HAVE A LEGIT UPDATE SCHOOL
*****************************************************************************/
(
SELECT * FROM (
SELECT MAX(RN) AS SINGLETONS, FRIST.LOGIN_NAME
FROM (
SELECT 
	ROW_NUMBER() OVER (PARTITION BY LOGIN_NAME ORDER BY LOGIN_NAME DESC) AS RN
	,LOGIN_NAME
	--,STF.[TYPE]
	,USERGROUP_NAME
 FROM 
REV.REV_USER AS USR
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
USR.FOCUS_ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN 
REV.REV_YEAR AS YRS
ON
YRS.YEAR_GU = USR.FOCUS_YEAR_GU
AND YRS.SCHOOL_YEAR = '2016'
LEFT JOIN 
rev.REV_USER_USERGROUP AS USRGRP
ON
USR.USER_GU = USRGRP.USER_GU
INNER JOIN 
REV.REV_USERGROUP AS USRG
ON
USRG.USERGROUP_GU = USRGRP.USERGROUP_GU

INNER JOIN 
rev.EPC_STAFF AS STF
ON
STF.STAFF_GU = USR.USER_GU
WHERE
(USERGROUP_NAME LIKE 'Update - %'
OR USERGROUP_NAME LIKE 'View - District')
) AS FRIST
GROUP BY FRIST.LOGIN_NAME
) AS SEC
WHERE
SINGLETONS =1
) AS T3

/****************************************************************************
* THIS PULLS THOSE SINGLETON USERS, USERGROUP INFO
*****************************************************************************/

INNER JOIN 
(
SELECT 
	ROW_NUMBER() OVER (PARTITION BY LOGIN_NAME ORDER BY LOGIN_NAME DESC) AS RN
	,LOGIN_NAME
	,STF.[TYPE]
	,USERGROUP_NAME
	,ORGANIZATION_NAME
	,ORG.ORGANIZATION_GU
	,CASE 
		WHEN USERGROUP_NAME LIKE '%FAMILY SCHOOL%' AND ORGANIZATION_NAME LIKE '%FAMILY SCHOOL%' THEN 1
		WHEN USERGROUP_NAME LIKE '%EUBANK%' AND ORGANIZATION_NAME LIKE '%EUBANK%' THEN 1
	ELSE 0 END AS KEEP_ME
	,USR.USER_GU
	,USR.FOCUS_YEAR_GU
	,YEAR_GU
	,STAFF_GU
FROM 
REV.REV_USER AS USR
INNER JOIN 
REV.REV_ORGANIZATION AS ORG
ON
USR.FOCUS_ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN 
REV.REV_YEAR AS YRS
ON
YRS.YEAR_GU = USR.FOCUS_YEAR_GU
AND YRS.SCHOOL_YEAR = '2016'

LEFT JOIN 
rev.REV_USER_USERGROUP AS USRGRP
ON
USR.USER_GU = USRGRP.USER_GU
INNER JOIN 
REV.REV_USERGROUP AS USRG
ON
USRG.USERGROUP_GU = USRGRP.USERGROUP_GU
AND USERGROUP_NAME LIKE 'UPDATE%'
AND USERGROUP_NAME NOT LIKE '%District%'
AND USERGROUP_NAME NOT LIKE '%Special Education%'
AND USERGROUP_NAME NOT LIKE '%TEP%'
AND USERGROUP_NAME NOT LIKE '%Transition%'
AND USERGROUP_NAME NOT LIKE '%Interim%'
AND USERGROUP_NAME NOT LIKE '%Summer%'
AND USERGROUP_NAME NOT LIKE '%Homebound%'
AND USERGROUP_NAME NOT LIKE '%Child Find%'
AND USERGROUP_NAME NOT LIKE '%Continuation%'

INNER JOIN 
rev.EPC_STAFF AS STF
ON
STF.STAFF_GU = USR.USER_GU

) AS T4

ON
T3.LOGIN_NAME = T4.LOGIN_NAME

--T4.LOGIN_NAME IS NULL
--AND 

WHERE 
SUBSTRING(USERGROUP_NAME,10,3) != SUBSTRING(ORGANIZATION_NAME,1,3)
AND KEEP_ME = 0

) AS T10
--WHERE
--STFYR.STAFF_GU IS NULL

WHERE
T10.STAFF_GU = REV.REV_USER.USER_GU

ROLLBACK