---this script will delete ALL standards data/results/assignment correlations from an environment
--DO NOT run on any database with actual teacher standards data.

BEGIN TRANSACTION

DELETE FROM REV.EGB_REPORTCARDITEMSXREF
WHERE STANDARDID IS NOT NULL

DELETE FROM REV.EGB_RCSC_BYSTANDARD

DELETE FROM REV.EGB_GBXREF 
WHERE STANDARDID IS NOT NULL

DELETE FROM REV.EGB_STANDARDS_CLASS

DELETE FROM REV.EGB_GBSTANDARDSRESULT

DELETE FROM REV.EPC_CRS_STN

DELETE FROM REV.EGB_RCSC_BYMEASURETYPE_STD

DELETE FROM REV.EGB_STANDARDS_NEW

DELETE FROM REV.EGB_STANDARDSTYPES
ROLLBACK