


SELECT
	[COURSES].[COURSE_ID]
	,[COURSES].[COURSE_TITLE]
	,COUNT([COURSES].[STUDENT_GU]) AS [TOTAL]
	,SUM(CASE WHEN [COURSES].[MARK] LIKE 'A%' THEN 1 ELSE 0 END) AS 'GRADE A COUNT'
	,SUM(CASE WHEN [COURSES].[MARK] LIKE 'B%' THEN 1 ELSE 0 END) AS 'GRADE B COUNT'
	,SUM(CASE WHEN [COURSES].[MARK] LIKE 'C%' THEN 1 ELSE 0 END) AS 'GRADE C COUNT'
FROM
	(
	SELECT --DISTINCT
		[COURSE_HISTORY].[COURSE_ID]
		,[COURSE_HISTORY].[COURSE_TITLE]
		,[COURSE_HISTORY].[STUDENT_GU]
		--,[STUDENT].[SIS_NUMBER]
		,[COURSE_HISTORY].[MARK]
		,[Grades].[LIST_ORDER]
		,[CourseMaster].[DUAL_CREDIT]
		
		
		--,[COURSE_HISTORY].*
		
		,ROW_NUMBER() OVER (PARTITION BY [COURSE_HISTORY].[STUDENT_GU], [COURSE_HISTORY].[COURSE_ID] ORDER BY [Grades].[LIST_ORDER]) [RN]
		
	FROM
		rev.EPC_STU_CRS_HIS AS [COURSE_HISTORY]
		--APS.ScheduleAsOf(GETDATE()) AS [SCHEDULE]
		
		INNER JOIN
		rev.EPC_CRS AS [CourseMaster]
		ON
		[COURSE_HISTORY].[COURSE_GU] = [CourseMaster].[COURSE_GU]
		
		--INNER JOIN
		--APS.BasicStudent AS [STUDENT]
		--ON
		--[COURSE_HISTORY].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		INNER JOIN
		APS.LookupTable('K12.CourseHistoryInfo','MARK') AS [Grades]
		ON
		[COURSE_HISTORY].[MARK] = [Grades].[VALUE_DESCRIPTION]
		
	WHERE
		[COURSE_HISTORY].[SCHOOL_YEAR] = '2013'
		AND [CourseMaster].[DUAL_CREDIT] = 'Y'
		
		--AND [COURSE_HISTORY].[STUDENT_GU] = '0F72639D-FF23-4956-96F7-00606C26817E'
	) AS [COURSES]
	
WHERE
	[COURSES].[RN] = 1
	
GROUP BY
	[COURSES].[COURSE_ID]
	,[COURSES].[COURSE_TITLE]
	
--ORDER BY
--	[COURSE_HISTORY].[STUDENT_GU]
--	,[COURSE_HISTORY].[COURSE_TITLE]