












; WITH

ASOF_ENROLLMENTS AS
(
SELECT
	[StudentSchoolYear].[STUDENT_GU]
	,[StudentSchoolYear].[ORGANIZATION_YEAR_GU]
	,[Organization].[ORGANIZATION_GU]
	,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
	,[School].[SCHOOL_CODE]
	,[Organization].[ORGANIZATION_NAME] AS [SCHOOL]
	,[StudentSchoolYear].[ENTER_DATE]
	,[StudentSchoolYear].[LEAVE_DATE]
	,[StudentSchoolYear].[EXCLUDE_ADA_ADM]
	,[RevYear].[SCHOOL_YEAR]
	,[RevYear].[EXTENSION]
FROM
	APS.PrimaryEnrollmentsAsOf(GETDATE()) AS [Enrollments]
	
	INNER JOIN
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
	ON
	[Enrollments].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
	ON 
	[StudentSchoolYear].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[OrgYear].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','Grade') AS [Grades]
	ON
	[StudentSchoolYear].[GRADE] = [Grades].[VALUE_CODE]
	
	INNER JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
)

--From Student Enrollment [EPC_STU_ENROLL]
, DETAIL_ENROLLMENTS AS
(
SELECT
	[StudentSchoolYear].[STUDENT_GU]
	,[StudentSchoolYear].[ORGANIZATION_YEAR_GU]
	,[Organization].[ORGANIZATION_GU]
	,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
	,[School].[SCHOOL_CODE]
	,[Organization].[ORGANIZATION_NAME] AS [SCHOOL]
	,[StudentSchoolYear].[ENTER_DATE]
	,[StudentSchoolYear].[LEAVE_DATE]
	,[EnrollmentDetails].[EXCLUDE_ADA_ADM]
	,[EnrollmentDetails].[ACCESS_504]
	,[StudentSchoolYear].[YEAR_GU]
	,[RevYear].[SCHOOL_YEAR]
	,[RevYear].[EXTENSION]
	--[EnrollmentDetails].*
	,ROW_NUMBER() OVER(PARTITION BY [StudentSchoolYear].[STUDENT_GU], [StudentSchoolYear].[YEAR_GU] ORDER BY [StudentSchoolYear].[ENTER_DATE] DESC) [RN]
FROM
	rev.EPC_STU_ENROLL AS [EnrollmentDetails]
		
	LEFT OUTER JOIN
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear]	
	ON
	[EnrollmentDetails].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
	ON 
	[StudentSchoolYear].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[OrgYear].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','Grade') AS [Grades]
	ON
	[StudentSchoolYear].[GRADE] = [Grades].[VALUE_CODE]
	
	INNER JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
)



-- From APS.BasicStudent
, STUDENT_DETAILS AS
(
SELECT
	-- Basic Student Demographics
	[STUDENT].[STUDENT_GU]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[STUDENT].[BIRTH_DATE]
	,[STUDENT].[GENDER]
	,[STUDENT].[CLASS_OF]	
	,[STUDENT].[HOME_ADDRESS] AS [HOME_ADDRESS]
	,[STUDENT].[HOME_ADDRESS_2] AS [HOME_ADDRESS_2]
	,[STUDENT].[HOME_CITY] AS [HOME_CITY]
	,[STUDENT].[HOME_STATE] AS [HOME_STATE]
	,[STUDENT].[HOME_ZIP] AS [HOME_ZIP]
	,[STUDENT].[MAIL_ADDRESS] AS [MAIL_ADDRESS]
	,[STUDENT].[MAIL_ADDRESS_2] AS [MAIL_ADDRESS_2]
	,[STUDENT].[MAIL_CITY] AS [MAIL_CITY]
	,[STUDENT].[MAIL_STATE] AS [MAIL_STATE]
	,[STUDENT].[MAIL_ZIP] AS [MAIL_ZIP]
	
	-- Format Primary Phone
	,'(' + left([PERSON].[PRIMARY_PHONE],3) + ')' 
       + substring([PERSON].[PRIMARY_PHONE], 4,3)+ '-'
                   + RIGHT([PERSON].[PRIMARY_PHONE],4) AS [PRIMARY_PHONE]
    
    -- Most Recent Lunch Status
    ,[FRMHistory].[FRM_CODE]
    
    -- Most Recent ELL Status
    ,CASE WHEN [ELL_PGM].[PROGRAM_CODE] = '1' AND [ELL_PGM].[EXIT_DATE] IS NULL THEN 'Y' ELSE 'N' END AS [ELL_STATUS]
    
    -- Current SPED or Gifted Status
    ,[CurrentSPED].[PRIMARY_DISABILITY_CODE]
    -- SPED Not Gifted
    ,CASE WHEN [CurrentSPED].[PRIMARY_DISABILITY_CODE] != 'GI' AND [CurrentSPED].[PRIMARY_DISABILITY_CODE] IS NOT NULL THEN 'Y' ELSE 'N' END AS [SPED_STATUS]
    ,CASE WHEN [CurrentSPED].[PRIMARY_DISABILITY_CODE] = 'GI' OR [CurrentSPED].[SECONDARY_DISABILITY_CODE] = 'GI' THEN 'Y' ELSE 'N' END AS [GIFTED_STATUS]
    
    -- Prefered Home Contact Language
    ,CASE WHEN [Contact_Language].[VALUE_DESCRIPTION] IS NULL THEN [STUDENT].[HOME_LANGUAGE] ELSE [Contact_Language].[VALUE_DESCRIPTION] END AS [HOME_LANGUAGE]
    
    ,[STUDENT].[HISPANIC_INDICATOR]
    ,[ETHNIC_CODES].[RACE_1]
    ,[ETHNIC_CODES].[RACE_2]
    ,[ETHNIC_CODES].[RACE_3]
    ,[ETHNIC_CODES].[RACE_4]
    ,[ETHNIC_CODES].[RACE_5]
    
FROM
	APS.BasicStudent AS [STUDENT]
	
	INNER JOIN
	rev.REV_PERSON AS [PERSON]
	ON
	[STUDENT].[STUDENT_GU] = [PERSON].[PERSON_GU]
	
	LEFT JOIN
    (
    SELECT
               *
    FROM
                REV.EP_STUDENT_SPECIAL_ED AS SPED
    WHERE
                NEXT_IEP_DATE IS NOT NULL
                AND (
                            EXIT_DATE IS NULL 
                            OR EXIT_DATE >= CONVERT(DATE, GETDATE())
                            )
    ) AS [CurrentSPED]
    ON
    [STUDENT].[STUDENT_GU] = [CurrentSPED].[STUDENT_GU]
    
    LEFT JOIN
    rev.EPC_STU_PGM_ELL AS [ELL_PGM]
    ON
    [STUDENT].[STUDENT_GU] = [ELL_PGM].[STUDENT_GU] 
    
    LEFT JOIN
    (
	SELECT
		  ROW_NUMBER() OVER (PARTITION BY [STU].[STUDENT_GU] order by [FRM].[ENTER_DATE] DESC,[STU].[STUDENT_GU]) [RN]
		, [STU].[STUDENT_GU]
		, [FRM].[FRM_CODE]
	FROM 
		rev.EPC_STU [STU]
		
		LEFT JOIN 
		rev.EPC_STU_PGM_FRM_HIS [FRM] 
		ON
		[FRM].[STUDENT_GU] = [STU].[STUDENT_GU]
		AND [FRM].[ENTER_DATE] IS NOT NULL 
		--AND ([FRM].[EXIT_DATE] IS NOT NULL OR [FRM].[EXIT_DATE] > GETDATE())
	) AS [FRMHistory]
	ON
	[STUDENT].[STUDENT_GU] = [FRMHistory].[STUDENT_GU]
	AND [FRMHistory].[RN] = 1
	
	-- Get Home Contact Language
	LEFT JOIN
	APS.LookupTable ('K12', 'Language') AS [Contact_Language]	
	ON
	[ELL_PGM].[LANGUAGE_TO_HOME] = [Contact_Language].[VALUE_CODE]
	
	-- Get All Racial Codes
	LEFT HASH JOIN
	(
	SELECT
		[ETHNIC_PIVOT].[PERSON_GU]
		,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable ('Revelation', 'ETHNICITY') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[1]) AS [RACE_1]
		,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable ('Revelation', 'ETHNICITY') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[2]) AS [RACE_2]
		,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable ('Revelation', 'ETHNICITY') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[3]) AS [RACE_3]
		,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable ('Revelation', 'ETHNICITY') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[4]) AS [RACE_4]
		,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable ('Revelation', 'ETHNICITY') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[5]) AS [RACE_5]
	FROM
		(
		SELECT
			[SECONDARY_ETHNIC_CODES].[PERSON_GU]
			,[SECONDARY_ETHNIC_CODES].[ETHNIC_CODE]
			,ROW_NUMBER() OVER(PARTITION by [SECONDARY_ETHNIC_CODES].[PERSON_GU] order by [SECONDARY_ETHNIC_CODES].[ETHNIC_CODE]) [RN]
		FROM
			rev.REV_PERSON_SECONDRY_ETH_LST AS [SECONDARY_ETHNIC_CODES]
		) [PVT]
		PIVOT (MIN(ETHNIC_CODE) FOR [RN] IN ([1],[2],[3],[4],[5])) AS [ETHNIC_PIVOT]
	) AS [ETHNIC_CODES]
	ON
	[STUDENT].[STUDENT_GU] = [ETHNIC_CODES].[PERSON_GU]
	
)

,CURRENT_ENROLLMENT_HISTORY AS
(
SELECT
	[CURRENT_ENROLLMENT_HISTORY].[STUDENT_GU]
	,[CURRENT_ENROLLMENT_HISTORY].[YEAR_GU]
	--,[RevYear].[SCHOOL_YEAR]
	--,[RevYear].[EXTENSION]
	
	,[StudentSchoolYear_1].[STUDENT_SCHOOL_YEAR_GU]
	,[StudentSchoolYear_1].[ORGANIZATION_YEAR_GU] AS [ORGANIZATION_YEAR_GU_1]
	,[School_1].[SCHOOL_CODE] AS [SCHOOL_CODE_1]
	,[Organization_1].[ORGANIZATION_NAME] AS [SCHOOL_NAME_1]
	,[StudentSchoolYear_1].[ENTER_DATE] AS [ENTER_DATE_1]
	,[StudentSchoolYear_1].[LEAVE_DATE] AS [LEAVE_DATE_1]
	
	,[StudentSchoolYear_2].[ORGANIZATION_YEAR_GU] AS [ORGANIZATION_YEAR_GU_2]
	,[School_2].[SCHOOL_CODE] AS [SCHOOL_CODE_2]
	,[Organization_2].[ORGANIZATION_NAME] AS [SCHOOL_NAME_2]
	,[StudentSchoolYear_2].[ENTER_DATE] AS [ENTER_DATE_2]
	,[StudentSchoolYear_2].[LEAVE_DATE] AS [LEAVE_DATE_2]
	
	,[StudentSchoolYear_3].[ORGANIZATION_YEAR_GU] AS [ORGANIZATION_YEAR_GU_3]
	,[School_3].[SCHOOL_CODE] AS [SCHOOL_CODE_3]
	,[Organization_3].[ORGANIZATION_NAME] AS [SCHOOL_NAME_3]
	,[StudentSchoolYear_3].[ENTER_DATE] AS [ENTER_DATE_3]
	,[StudentSchoolYear_3].[LEAVE_DATE] AS [LEAVE_DATE_3]
	
	,[StudentSchoolYear_3].[ORGANIZATION_YEAR_GU] AS [ORGANIZATION_YEAR_GU_4]
	,[School_4].[SCHOOL_CODE] AS [SCHOOL_CODE_4]
	,[Organization_4].[ORGANIZATION_NAME] AS [SCHOOL_NAME_4]
	,[StudentSchoolYear_3].[ENTER_DATE] AS [ENTER_DATE_4]
	,[StudentSchoolYear_3].[LEAVE_DATE] AS [LEAVE_DATE_4]
FROM
	(
	SELECT
		[STUDENT_GU]
		,[YEAR_GU]
		,[1] AS [SSY_1]
		,[2] AS [SSY_2]
		,[3] AS [SSY_3]
		,[4] AS [SSY_4]
	FROM
		(
		SELECT
			[StudentSchoolYear].[STUDENT_GU]
			,[StudentSchoolYear].[ORGANIZATION_YEAR_GU]
			,[StudentSchoolYear].[YEAR_GU]
			,ROW_NUMBER() OVER(PARTITION BY [StudentSchoolYear].[STUDENT_GU], [StudentSchoolYear].[YEAR_GU] ORDER BY [StudentSchoolYear].[ENTER_DATE] DESC) [RN]
		FROM
			rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
			
		WHERE
			[StudentSchoolYear].EXCLUDE_ADA_ADM IS NULL
		) AS [ENR_HST]
		PIVOT (MIN([ORGANIZATION_YEAR_GU]) FOR [RN] IN ([1],[2],[3],[4])) AS [ENR_PIVOT]
	) AS [CURRENT_ENROLLMENT_HISTORY]
	
	--INNER JOIN 
	--rev.REV_YEAR AS [RevYear] -- Contains the School Year
	--ON 
	--[CURRENT_ENROLLMENT_HISTORY].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	INNER JOIN 
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear_1]
	ON
	[CURRENT_ENROLLMENT_HISTORY].[STUDENT_GU] = [StudentSchoolYear_1].[STUDENT_GU]
	AND [CURRENT_ENROLLMENT_HISTORY].[SSY_1] = [StudentSchoolYear_1].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear_1] -- Links between School and Year
	ON 
	[StudentSchoolYear_1].[ORGANIZATION_YEAR_GU] = [OrgYear_1].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization_1] -- Contains the School Name
	ON 
	[OrgYear_1].[ORGANIZATION_GU] = [Organization_1].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.EPC_SCH AS [School_1] -- Contains the School Code / Number
	ON 
	[Organization_1].[ORGANIZATION_GU] = [School_1].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN 
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear_2]
	ON
	[CURRENT_ENROLLMENT_HISTORY].[STUDENT_GU] = [StudentSchoolYear_2].[STUDENT_GU]
	AND [CURRENT_ENROLLMENT_HISTORY].[SSY_2] = [StudentSchoolYear_2].[ORGANIZATION_YEAR_GU]
	
	LEFT OUTER JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear_2] -- Links between School and Year
	ON 
	[StudentSchoolYear_2].[ORGANIZATION_YEAR_GU] = [OrgYear_2].[ORGANIZATION_YEAR_GU]
	
	LEFT OUTER JOIN 
	rev.REV_ORGANIZATION AS [Organization_2] -- Contains the School Name
	ON 
	[OrgYear_2].[ORGANIZATION_GU] = [Organization_2].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN 
	rev.EPC_SCH AS [School_2] -- Contains the School Code / Number
	ON 
	[Organization_2].[ORGANIZATION_GU] = [School_2].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN 
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear_3]
	ON
	[CURRENT_ENROLLMENT_HISTORY].[STUDENT_GU] = [StudentSchoolYear_3].[STUDENT_GU]
	AND [CURRENT_ENROLLMENT_HISTORY].[SSY_3] = [StudentSchoolYear_3].[ORGANIZATION_YEAR_GU]
	
	LEFT OUTER JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear_3] -- Links between School and Year
	ON 
	[StudentSchoolYear_3].[ORGANIZATION_YEAR_GU] = [OrgYear_3].[ORGANIZATION_YEAR_GU]
	
	LEFT OUTER JOIN 
	rev.REV_ORGANIZATION AS [Organization_3] -- Contains the School Name
	ON 
	[OrgYear_3].[ORGANIZATION_GU] = [Organization_3].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN 
	rev.EPC_SCH AS [School_3] -- Contains the School Code / Number
	ON 
	[Organization_3].[ORGANIZATION_GU] = [School_3].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN 
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear_4]
	ON
	[CURRENT_ENROLLMENT_HISTORY].[STUDENT_GU] = [StudentSchoolYear_4].[STUDENT_GU]
	AND [CURRENT_ENROLLMENT_HISTORY].[SSY_4] = [StudentSchoolYear_4].[ORGANIZATION_YEAR_GU]
	
	LEFT OUTER JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear_4] -- Links between School and Year
	ON 
	[StudentSchoolYear_4].[ORGANIZATION_YEAR_GU] = [OrgYear_4].[ORGANIZATION_YEAR_GU]
	
	LEFT OUTER JOIN 
	rev.REV_ORGANIZATION AS [Organization_4] -- Contains the School Name
	ON 
	[OrgYear_4].[ORGANIZATION_GU] = [Organization_4].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN 
	rev.EPC_SCH AS [School_4] -- Contains the School Code / Number
	ON 
	[Organization_4].[ORGANIZATION_GU] = [School_4].[ORGANIZATION_GU]
)

------------------------------------------------------------------

SELECT
	[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL]
	,[ENROLLMENTS].[STUDENT_GU]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[STUDENT].[BIRTH_DATE]
	,[ENROLLMENTS].[GRADE]
	,[STUDENT].[GENDER]
	,[STUDENT].[HISPANIC_INDICATOR]
    ,[STUDENT].[RACE_1]
    ,[STUDENT].[RACE_2]
    ,[STUDENT].[RACE_3]
    ,[STUDENT].[RACE_4]
    ,[STUDENT].[RACE_5]
    ,[TRIBAL_COMMUNITY].[VALUE_DESCRIPTION] AS [TRIBE]
    ,CASE WHEN [TRIBAL_COMMUNITY].[VALUE_DESCRIPTION] LIKE '%_%' THEN [TRIBAL_COMMUNITY].[VALUE_DESCRIPTION] ELSE '' END AS [NEW_MEXICO_TRIBE]
    
    ,[STUDENT].[HOME_LANGUAGE] AS [CONTACT_LANGAUGE]
    
    ,[STUDENT].[FRM_CODE]
    
    --,[ELL_PROGRAM].[EXIT_DATE]
    --,[ELL_PROGRAM].[EXIT_REASON]
    --,[ELL_PROGRAM].[PROGRAM_CODE]
    --,[LCE_LATEST_EVALUATION].[IS_ELL]
    
    ,CASE 
		WHEN [ELL_PROGRAM].[PROGRAM_CODE] IS NULL AND [LCE_LATEST_EVALUATION].[IS_ELL] = 0 THEN '4' 
		WHEN [ELL_PROGRAM].[EXIT_REASON] = 'EY3' OR [ELL_PROGRAM].[EXIT_REASON] = 'EY-' THEN '3'
		WHEN [ELL_PROGRAM].[EXIT_REASON] = 'EY1' OR [ELL_PROGRAM].[EXIT_REASON] = 'EY2' THEN '2'
		WHEN [ELL_PROGRAM].[PROGRAM_CODE] =  1 AND [ELL_PROGRAM].[EXIT_DATE] IS NULL THEN '1'
		WHEN [ELL_PROGRAM].[PROGRAM_CODE] IS NULL THEN '0'
	END AS [ENGLISH_LEARNER]
	,[ELL_PROGRAM].[EXIT_DATE] AS [ELL_PROGRAM_EXIT_DATE]
    
    ,[LCE_LATEST_EVALUATION].[TEST_NAME] AS [LATEST_EVALUATION]
    ,[LCE_LATEST_EVALUATION].[PERFORMANCE_LEVEL]
    ,[LCE_LATEST_EVALUATION].[ADMIN_DATE] AS [LATEST_EVALUATION_DATE]
    
    ,[STUDENT].[SPED_STATUS]
    ,[STUDENT].[GIFTED_STATUS]
    
    ,[ENROLLMENTS].[ACCESS_504]
	
	,CASE WHEN ISNUMERIC([EPC_STU].[GRID_CODE]) = 0 OR [EPC_STU].[GRID_CODE] = '99999' THEN [EPC_STU].[GRID_CODE] ELSE LEFT([EPC_STU].[GRID_CODE],3) END AS [GRID_CODE_ES]
	,[ELEMENTARY_SCHOOL].[ORGANIZATION_NAME] AS [ELEM SCHOOL]
	,CASE WHEN ISNUMERIC([EPC_STU].[GRID_CODE]) = 0 OR [EPC_STU].[GRID_CODE] = '99999' THEN '' ELSE RIGHT(LEFT([EPC_STU].[GRID_CODE],6),3) END AS [GRID_CODE_MS]
	,[MIDDLE_SCHOOL].[ORGANIZATION_NAME] AS [MID SCHOOL]
	,CASE WHEN ISNUMERIC([EPC_STU].[GRID_CODE]) = 0 OR [EPC_STU].[GRID_CODE] = '99999' THEN '' ELSE RIGHT([EPC_STU].[GRID_CODE],3) END AS [GRID_CODE_ES]
	,[HIGH_SCHOOL].[ORGANIZATION_NAME] AS [HIGH SCHOOL]
	
	,[CURRENT_ENROLLMENT_HISTORY].[ENTER_DATE_1] AS [CURRENT_ENROLLMENT_DATE]
	
	,[CURRENT_ENROLLMENT_HISTORY].[SCHOOL_CODE_2] AS [PREVIOUS_SCH_CODE_1]
	,[CURRENT_ENROLLMENT_HISTORY].[SCHOOL_NAME_2] AS [PREVIOUS_SCH_NAME_1]
	,[CURRENT_ENROLLMENT_HISTORY].[ENTER_DATE_2] AS [PREVIOUS_ENTER_DATE_1]
	,[CURRENT_ENROLLMENT_HISTORY].[LEAVE_DATE_2] AS [PREVIOUS_LEAVE_DATE_1]
	
	,[CURRENT_ENROLLMENT_HISTORY].[SCHOOL_CODE_3] AS [PREVIOUS_SCH_CODE_2]
	,[CURRENT_ENROLLMENT_HISTORY].[SCHOOL_NAME_3] AS [PREVIOUS_SCH_NAME_2]
	,[CURRENT_ENROLLMENT_HISTORY].[ENTER_DATE_3] AS [PREVIOUS_ENTER_DATE_2]
	,[CURRENT_ENROLLMENT_HISTORY].[LEAVE_DATE_3] AS [PREVIOUS_LEAVE_DATE_2]
	
	,[CURRENT_ENROLLMENT_HISTORY].[SCHOOL_CODE_4] AS [PREVIOUS_SCH_CODE_3]
	,[CURRENT_ENROLLMENT_HISTORY].[SCHOOL_NAME_4] AS [PREVIOUS_SCH_NAME_3]
	,[CURRENT_ENROLLMENT_HISTORY].[ENTER_DATE_4] AS [PREVIOUS_ENTER_DATE_3]
	,[CURRENT_ENROLLMENT_HISTORY].[LEAVE_DATE_4] AS [PREVIOUS_LEAVE_DATE_3]
	
FROM
	DETAIL_ENROLLMENTS AS [ENROLLMENTS]
	
	INNER JOIN
	STUDENT_DETAILS AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.EPC_STU AS [EPC_STU]
	ON
	[STUDENT].[STUDENT_GU] = [EPC_STU].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.EPC_GRID AS [SCHOOL_GRID]
	ON
	[EPC_STU].[GRID_CODE] = [SCHOOL_GRID].[GRID_CODE]
	AND [ENROLLMENTS].[SCHOOL_YEAR] = [SCHOOL_GRID].[SCHOOL_YEAR]
	
	LEFT OUTER JOIN
	rev.EPC_STU_NATIVE_AMERICAN AS [NATIVE_AMERICAN]
	ON
	[STUDENT].[STUDENT_GU] = [NATIVE_AMERICAN].[STUDENT_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable ('K12.DemographicInfo', 'Tribal_Community') AS [TRIBAL_COMMUNITY]
	ON
	[NATIVE_AMERICAN].[TRIBAL_COMMUNITY] = [TRIBAL_COMMUNITY].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LCELatestEvaluationAsOf(GETDATE()) AS [LCE_LATEST_EVALUATION]
	ON
	[STUDENT].[STUDENT_GU] = [LCE_LATEST_EVALUATION].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.EPC_STU_PGM_ELL AS [ELL_PROGRAM]
	ON
	[STUDENT].[STUDENT_GU] = [ELL_PROGRAM].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.REV_ORGANIZATION AS [ELEMENTARY_SCHOOL]
	ON
	[SCHOOL_GRID].[ELEM_SCHOOL_GU] = [ELEMENTARY_SCHOOL].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN
	rev.REV_ORGANIZATION AS [MIDDLE_SCHOOL]
	ON
	[SCHOOL_GRID].[JR_HIGH_SCHOOL_GU] = [MIDDLE_SCHOOL].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN
	rev.REV_ORGANIZATION AS [HIGH_SCHOOL]
	ON
	[SCHOOL_GRID].[SR_HIGH_SCHOOL_GU] = [HIGH_SCHOOL].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN
	CURRENT_ENROLLMENT_HISTORY AS [CURRENT_ENROLLMENT_HISTORY]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [CURRENT_ENROLLMENT_HISTORY].[STUDENT_GU]
	AND [ENROLLMENTS].[YEAR_GU] = [CURRENT_ENROLLMENT_HISTORY].[YEAR_GU]
	
	
WHERE	
	[ENROLLMENTS].[ENTER_DATE] <= GETDATE()
	AND [ENROLLMENTS].[RN] = 1
	AND [ENROLLMENTS].[SCHOOL_YEAR] = '2014'
	AND [ENROLLMENTS].[EXTENSION] = 'R'
	--[ENROLLMENTS].[GRADE] = '08'
	--AND [STUDENT].[SPED_STATUS] = 'Y'
	--[TRIBAL_COMMUNITY].[VALUE_DESCRIPTION] like '%_%'
	--AND [STUDENT].[SIS_NUMBER] = '970003604'

--SELECT TOP 100
--	*
--FROM
	--rev.EPC_STU_SCH_YR
	--rev.EPC_STU_ENROLL
	--APS.LCELatestEvaluationAsOf(GETDATE())
--	APS.LookupTable ('K12.DemographicInfo', 'Tribal_Community') --AS [Contact_Language]
	--rev.EPC_STU_PGM_ELL
	