

	SELECT
		[BasicStudent].[SIS_NUMBER]
		--,[Student].*
		,[BasicStudent].[LAST_NAME]
		,[BasicStudent].[FIRST_NAME]
		,[School].[SCHOOL_CODE]
		,[Organization].[ORGANIZATION_NAME]	AS [SCHOOL_NAME]
		,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
		,[COMPLETED_2013_ENROLLMENTS].[ENTER_DATE]
		,[COMPLETED_2013_ENROLLMENTS].[LEAVE_DATE]
		,[EnrollmentDetails].[LEAVE_CODE]
		--,[LEAVE_DESCRIPTION].[VALUE_DESCRIPTION]
		,[StudentSchoolYear].[YEAR_END_STATUS]
		,[Student].[GRADUATION_DATE]
		,CASE 
			WHEN [StudentSchoolYear].[YEAR_END_STATUS] IS NOT NULL THEN [StudentSchoolYear].[YEAR_END_STATUS]
			WHEN [StudentSchoolYear].[YEAR_END_STATUS] = 'P' THEN 'PROMOTED'
			WHEN [StudentSchoolYear].[YEAR_END_STATUS] = 'R' THEN 'RETAINED'
			WHEN [Student].[GRADUATION_DATE] IS NOT NULL THEN 'GRADUATED'
		END AS [END_STATUS]
		
		,[REQUEST_TRACKING].[RELEASE_DATE]
		--,[REQUEST_TRACKING].*
		,[SCHOOL_Non_District].[NAME]
		--,[SCHOOL_Non_District].[CITY]
		--,[SCHOOL_Non_District].[STATE]
		,[REQUEST_TRACKING_NOTES].[NOTES]
	FROM
		APS.PrimaryEnrollmentsAsOf('05/22/2014') AS [COMPLETED_2013_ENROLLMENTS]
		
		LEFT OUTER JOIN
		APS.PrimaryEnrollmentsAsOf(GETDATE()) AS [CURRENT_ENROLLMENTS]
		ON
		[COMPLETED_2013_ENROLLMENTS].[STUDENT_GU] = [CURRENT_ENROLLMENTS].[STUDENT_GU]
		
		INNER JOIN 
		rev.EPC_STU_ENROLL AS [EnrollmentDetails] -- Contains Grade and Start Date
		ON 
		[COMPLETED_2013_ENROLLMENTS].[ENROLLMENT_GU] = [EnrollmentDetails].[ENROLLMENT_GU]
		
		INNER JOIN
		rev.EPC_STU_SCH_YR AS [StudentSchoolYear] -- Contains Grade and Start Date 	
		ON
		[EnrollmentDetails].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','LEAVE_CODE') AS [LEAVE_DESCRIPTION]
		ON
		[StudentSchoolYear].[LEAVE_CODE] = [LEAVE_DESCRIPTION].[VALUE_CODE]
		
		-- Get location year
		LEFT OUTER JOIN 
		rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
		ON 
		[COMPLETED_2013_ENROLLMENTS].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
		
		-- Get location details and name
		LEFT OUTER JOIN
		rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
		ON 
		[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
		
		-- Get the location code
		LEFT OUTER JOIN
		rev.EPC_SCH AS [School] -- Contains the School Code / Number
		ON 
		[OrgYear].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
		
		INNER JOIN
		APS.BasicStudent AS [BasicStudent]
		ON
		[COMPLETED_2013_ENROLLMENTS].[STUDENT_GU] = [BasicStudent].[STUDENT_GU]
		
		INNER JOIN
		rev.EPC_STU AS [Student]
		ON
		[BasicStudent].[STUDENT_GU] = [Student].[STUDENT_GU]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','Grade') AS [Grades]
		ON
		[COMPLETED_2013_ENROLLMENTS].[GRADE] = [Grades].[VALUE_CODE]
		
		LEFT OUTER JOIN
		rev.[EPC_STU_REQUEST_TRACKING] AS [REQUEST_TRACKING]
		ON
		[COMPLETED_2013_ENROLLMENTS].[STUDENT_GU] = [REQUEST_TRACKING].[STUDENT_GU]
		
		LEFT OUTER JOIN
		rev.[UD_STU_REQUEST_TRACKING] AS [REQUEST_TRACKING_NOTES]
		ON
		[REQUEST_TRACKING].[STU_REQUEST_TRACKING_GU] = [REQUEST_TRACKING_NOTES].[STU_REQUEST_TRACKING_GU]
		
		-- Get location details and name
		LEFT OUTER JOIN
		rev.[EPC_SCH_NON_DST] AS [SCHOOL_Non_District] -- Contains the School Name
		ON 
		[REQUEST_TRACKING].[SCHOOL_NON_DISTRICT_GU] = [SCHOOL_Non_District].[SCHOOL_NON_DISTRICT_GU]
		
	WHERE
		[CURRENT_ENROLLMENTS].[STUDENT_GU] IS NULL


--SELECT	TOP 100
--	*
--FROM
	--rev.EPC_STU_CRS_HIS AS [CRS_HISTORY]
	--rev.EPC_STU_ATT_LETTER_HIS
	--rev.EPC_STU_REQUEST_TRACKING AS [REQUEST_TRACKING]
	--rev.EPC_STU_SCH_YR_ADD_INFO
	
	--INNER JOIN
	--rev.UD_STU_REQUEST_TRACKING AS [REQUEST_TRACKING_NOTES]
	--ON
	--[REQUEST_TRACKING].[STU_REQUEST_TRACKING_GU] = [REQUEST_TRACKING_NOTES].[STU_REQUEST_TRACKING_GU]
	
	--STU_REQUEST_TRACKING_GU