




SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLL_2014].[SCHOOL_CODE]
	,[ENROLL_2014].[SCHOOL_NAME]
	,[ENROLL_2014].[SCHOOL_YEAR]
	,[ENROLL_2014].[GRADE]
	,[ENROLL_2014].[ENTER_DATE]
	,[ENROLL_2014].[LEAVE_DATE]
	,[ENROLL_2014].[LEAVE_DESCRIPTION]
	,''
	,[ENROLL_2015].[SCHOOL_CODE]
	,[ENROLL_2015].[SCHOOL_NAME]
	,[ENROLL_2015].[SCHOOL_YEAR]
	,[ENROLL_2015].[GRADE]
	,[ENROLL_2015].[ENTER_DATE]
	,[ENROLL_2015].[LEAVE_DATE]
	,[ENROLL_2015].[LEAVE_DESCRIPTION]
FROM
	(
	SELECT
		*
	FROM
		APS.StudentEnrollmentDetails AS [ENROLLMENT]
		
	WHERE
		[ENROLLMENT].[SCHOOL_YEAR] = '2014'
		AND [ENROLLMENT].[EXTENSION] = 'R'
		AND [ENROLLMENT].[GRADE] IN ('05','08')
		AND [ENROLLMENT].[ENTER_DATE] IS NOT NULL
		AND [ENROLLMENT].[EXCLUDE_ADA_ADM] IS NULL
	) AS [ENROLL_2014]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLL_2014].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	(
	SELECT
		*
	FROM
		APS.StudentEnrollmentDetails AS [ENROLLMENT]
		
	WHERE
		[ENROLLMENT].[SCHOOL_YEAR] = '2015'
		AND [ENROLLMENT].[EXTENSION] = 'R'
		--AND [ENROLLMENT].[GRADE] IN ('05','08')
		AND [ENROLLMENT].[ENTER_DATE] IS NOT NULL
		AND [ENROLLMENT].[EXCLUDE_ADA_ADM] IS NULL
	) AS [ENROLL_2015]
	ON
	[ENROLL_2014].[STUDENT_GU] = [ENROLL_2015].[STUDENT_GU]