


EXECUTE AS LOGIN='QueryFileUser'
GO
SELECT
	*
FROM
	(
	SELECT
		[STUDENT].[LAST_NAME]
		,[STUDENT].[FIRST_NAME]
		,[FILE].[STUDENT_ID]
		,[ENROLLMENTS].[SCHOOL_NAME]
		,[STUDENT].[HOME_ADDRESS]
		,[STUDENT].[HOME_CITY]
		,[STUDENT].[HOME_STATE]
		,[STUDENT].[HOME_ZIP]
		,[STUDENT].[PRIMARY_PHONE]
		,[STUDENT_EXCEPTIONS].[EXCLUDE_BUSINESS]
		,[STUDENT_EXCEPTIONS].[EXCLUDE_UNIVERSITY]
		,[STUDENT_EXCEPTIONS].[EXCLUDE_MILITARY]
		,ROW_NUMBER() OVER (PARTITION BY [FILE].[STUDENT_ID] ORDER BY [ENROLLMENTS].[ENTER_DATE] DESC) AS RN
	FROM
		OPENROWSET (
				'Microsoft.ACE.OLEDB.12.0', 
				'Text;Database=\\SynTempSSIS\Files\TempQuery\;',
				'SELECT * from APEX_Student_list_0601315.csv' 
			)AS [FILE]
			
		LEFT OUTER JOIN
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		ON
		[FILE].[STUDENT_ID] = [STUDENT].[SIS_NUMBER]
		
		LEFT OUTER JOIN
		APS.StudentEnrollmentDetails AS [ENROLLMENTS]
		ON
		[STUDENT].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]
		
		LEFT JOIN
		rev.[UD_STU] AS [STUDENT_EXCEPTIONS]
		ON
		[Student].[STUDENT_GU] = [STUDENT_EXCEPTIONS].[STUDENT_GU]
	) AS [SUB_1]
	
WHERE
	[SUB_1].[RN] = 1
	AND [EXCLUDE_BUSINESS] = 'N'
	AND [EXCLUDE_UNIVERSITY] = 'N'
	AND [EXCLUDE_MILITARY] = 'N'
		

REVERT
GO