




DECLARE @SchoolYear INT  = 2013
--DECLARE @Grade VARCHAR(2) = '09'

SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	--,[STUDENT].[STUDENT_GU]
	,[STUDENT].[FIRST_NAME] 
	,[STUDENT].[LAST_NAME] 
	,[STUDENT].[MIDDLE_NAME]
	,CONVERT(VARCHAR(10),[STUDENT].[BIRTH_DATE],126) AS [BIRTH_DATE]
	,[STUDENT].[CLASS_OF]
	,[ENROLLMENTS].[SCHOOL_NAME] 	
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[GRADE]
	,[STUDENT].[RESOLVED_RACE]
	,[STUDENT].[GENDER]
	,[STUDENT].[LUNCH_STATUS]
	,[STUDENT].[ELL_STATUS]
	,[STUDENT].[SPED_STATUS]
	,CASE WHEN [AVID_STUDENTS].[STUDENT_GU] IS NOT NULL THEN 'Y' ELSE 'N' END AS [TOOK AT LEAST 1 AVID CLASS THIS YEAR]
	
	--,CASE WHEN [Attendance].[TOTAL UNEXCUSED] IS NULL THEN '0.0' ELSE [Attendance].[TOTAL UNEXCUSED] END AS [TOTAL UNEXCUSED]
	,[PERIOD_ATTENDANCE].[Full Days Unexcused] + ([PERIOD_ATTENDANCE].[Half Days Unexcused]/2) AS [TOTAL UNEXCUSED]
	
	--,[GPA].[HS Cum Flat]
	--,[GPA].[HS Cum Weighted]
	,[CumulativeGPA].[Cumulative Flat GPA]
	,[CumulativeGPA].[Cumulative Weighted GPA]
	--,[CumulativeGPA].[TOTAL CREDITS]
	
	,[CREDITS].[MATH_CREDITS]
	,[CREDITS].[ENGLISH_CREDITS]
	--,[CREDITS].[TOTAL_CREDITS]
	
	--,[COURSE_HISTORY].[COURSE_TITLE]
	--,[COURSE_HISTORY].[CREDIT_COMPLETED]
	
	--,[AVID_STUDENTS].*
	
FROM
	APS.StudentEnrollmentDetails AS [ENROLLMENTS]
	
	INNER HASH JOIN
	--INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	/*
	-- GET ATTENDANCE FROM SMAX
	LEFT OUTER HASH JOIN
	--LEFT OUTER JOIN
	(
	SELECT
		IV3.DST_NBR
		,IV3.MNT_DT
		--,IV3.SCH_NBR
		,IV3.ID_NBR
		,IV3.SCH_YR
		--,IV3.KEYVALUE
		
		--SUM The absence types into their respective columns. UX = Unexcused, EX = Excused. 
		,SUM(CASE WHEN (IV3.FIELDNUM=80) THEN 1.0 ELSE 0.0 END) AS UX_FULL_DAY
		,SUM(CASE WHEN (IV3.FIELDNUM=82) THEN 1.0 ELSE 0.0 END) AS UX_HALF_DAY
		,SUM(CASE WHEN (IV3.FIELDNUM=84) THEN 1.0 ELSE 0.0 END) AS EX_FULL_DAY
		,SUM(CASE WHEN (IV3.FIELDNUM=86) THEN 1.0 ELSE 0.0 END) AS EX_HALF_DAY
	
		,SUM(CASE WHEN (IV3.FIELDNUM=80) THEN 1.0 ELSE 0.0 END) 
		+SUM(CASE WHEN (IV3.FIELDNUM=82) THEN 1.0 ELSE 0.0 END)/2.0
		+SUM(CASE WHEN (IV3.FIELDNUM=84) THEN 1.0 ELSE 0.0 END) 
		+SUM(CASE WHEN (IV3.FIELDNUM=86) THEN 1.0 ELSE 0.0 END)/2.0 AS [TOTAL ABSENCES]
		,SUM(CASE WHEN (IV3.FIELDNUM=80) THEN 1.0 ELSE 0.0 END) 
		+SUM(CASE WHEN (IV3.FIELDNUM=82) THEN 1.0 ELSE 0.0 END)/2.0 AS [TOTAL UNEXCUSED]
					
	FROM
		--Join IV table to CurrentPrimaryEnrollment 
		[SMAXDBDEV.APS.EDU.ACTD].[PR].[DBTSIS].[IV030_V] AS [IV3]

	WHERE
		IV3.DST_NBR = 1
		AND IV3.SCH_YR = @SchoolYear + 1
		--AND IV3.KEYVALUE <= @REPORTINGDATE
		--AND IV3.KEYVALUE IS NOT NULL
		AND IV3.SCH_NBR != ''
		
	GROUP BY 
		IV3.DST_NBR
		,IV3.ID_NBR
		--,IV3.SCH_NBR
		,IV3.MNT_DT
		,IV3.SCH_YR
	) AS [Attendance]
	ON
	[STUDENT].[SIS_NUMBER] = [Attendance].[ID_NBR]
	--*/
	-- GET ATTENDANCE FROM SYNERGY
	LEFT OUTER JOIN
	APS.PeriodAttendanceAsOf('05/20/2015') AS [PERIOD_ATTENDANCE]
	ON
	[STUDENT].[SIS_NUMBER] = [PERIOD_ATTENDANCE].[SIS_NUMBER]
	AND [ENROLLMENTS].[SCHOOL_CODE] = [PERIOD_ATTENDANCE].[SCHOOL_CODE]
	
	-- GET STUDENT AVID COURSES
	LEFT OUTER HASH JOIN
	--LEFT OUTER JOIN
	(
	SELECT DISTINCT
		[SCHEDULE].[STUDENT_GU]
		--,[COURSE].[COURSE_ID]
		--,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
	FROM
		-- Get full schedule
		APS.BasicSchedule AS [SCHEDULE]
		
		INNER JOIN
		-- Get Course details
		rev.EPC_CRS AS [COURSE]
		ON
		[SCHEDULE].[COURSE_GU] = [COURSE].[COURSE_GU]
		
		INNER JOIN 
		rev.REV_YEAR AS [RevYear] -- Contains the School Year
		ON 
		[SCHEDULE].[YEAR_GU] = [RevYear].[YEAR_GU]
		
		INNER JOIN
		rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
		ON
		[SCHEDULE].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','Grade') AS [Grades]
		ON
		[StudentSchoolYear].[GRADE] = [Grades].[VALUE_CODE]
		
	WHERE
		[COURSE].[COURSE_ID] IN ('55507','555071','555072','55508','555081','555082','555091','555092','555101','555102','555111','555112','555121','555122','55506E')
		--AND [SCHEDULE].[ORGANIZATION_GU] LIKE @School
		AND [RevYear].[SCHOOL_YEAR] = @SchoolYear
		
	) AS [AVID_STUDENTS]
	ON
	[STUDENT].[STUDENT_GU] = [AVID_STUDENTS].[STUDENT_GU]
	
	/*
	-- GET GPA FROM SYNERGY
	LEFT OUTER HASH JOIN
	--LEFT OUTER JOIN
	APS.CumGPA AS [GPA]
	ON
	[STUDENT].[SIS_NUMBER] = [GPA].[SIS_NUMBER]
	AND [GPA].[SCHOOL_YEAR] = @SchoolYear
	--*/
	
	--/*
	LEFT OUTER HASH JOIN
	(
	SELECT
		--*
		DST_NBR
		,ID_NBR
		,CASE WHEN SUM([Attempted Credits]) != 0 THEN
			SUM([FLAT GPA]*[Attempted Credits])/SUM([Attempted Credits])+SUM([Honors Points]) 
		 ELSE 0
		 END AS [Cumulative Weighted GPA]
		 
		,CASE WHEN SUM([Attempted Credits]) != 0 THEN
			SUM([FLAT GPA]*[Attempted Credits])/SUM([Attempted Credits]) 
		 ELSE 0
		 END AS [Cumulative Flat GPA]
		 
		,CASE WHEN SUM([Attempted Credits]) != 0 THEN
			SUM([Earned Credits])
		 ELSE 0
		 END AS [TOTAL CREDITS]		 
	FROM
		[SMAXDBDEV.APS.EDU.ACTD].[PR].APS.BasicGPA
	WHERE
		ENR_GRDE > '08'	
		AND 
		SCH_YR <= @SchoolYear + 1
	GROUP BY
		DST_NBR
		,ID_NBR
	) AS [CumulativeGPA]	
	ON
	[CumulativeGPA].[DST_NBR] = 1
	AND [STUDENT].[SIS_NUMBER] = [CumulativeGPA].[ID_NBR]
	--*/
	
	-- GET CREDITS EARNED FROM SYNERGY
	LEFT OUTER HASH JOIN
	--LEFT OUTER JOIN
	(
	SELECT
		[STUDENT_GU]
		,[SCHOOL_YEAR]
		,SUM([MATH_CREDITS]) AS [MATH_CREDITS]
		,SUM([ENGLISH_CREDITS]) AS [ENGLISH_CREDITS]
		,SUM([CREDIT_COMPLETED]) AS [TOTAL_CREDITS]
	FROM
		(
		SELECT
			[COURSE_HISTORY].[STUDENT_GU]
			,[COURSE_HISTORY].[SCHOOL_YEAR]
			,[COURSE].[DEPARTMENT]
			,CASE WHEN [COURSE].[DEPARTMENT] = 'Math' THEN [COURSE_HISTORY].[CREDIT_COMPLETED] END AS [MATH_CREDITS]
			,CASE WHEN [COURSE].[DEPARTMENT] = 'Eng' THEN [COURSE_HISTORY].[CREDIT_COMPLETED] END AS [ENGLISH_CREDITS]
			,[COURSE_HISTORY].[CREDIT_COMPLETED]
			,[COURSE_HISTORY].[REPEAT_TAG_GU]
			
		FROM
			rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
			
			INNER JOIN
			rev.[EPC_CRS] AS [COURSE]
			ON
			[COURSE_HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
			
		WHERE
			[COURSE_HISTORY].[SCHOOL_YEAR] = @SchoolYear
			AND ([COURSE_HISTORY].[REPEAT_TAG_GU] IS NULL OR [COURSE_HISTORY].[REPEAT_TAG_GU] != '92E81AF7-962A-4D66-ADF9-5FD3FD88FA7D')
			--AND [COURSE].[DEPARTMENT] IN ('Math','Eng')
			--AND [COURSE_HISTORY].[STUDENT_GU] = '7B8C7FEE-4A70-4D1F-9F27-0D78E17C890C'
		) AS [SUB1]
	
	--/*	
	GROUP BY
		[STUDENT_GU]
		,[SCHOOL_YEAR]
	) AS [CREDITS]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [CREDITS].[STUDENT_GU]
	AND [ENROLLMENTS].[SCHOOL_YEAR] = [CREDITS].[SCHOOL_YEAR]
	--*/
	
	--LEFT OUTER HASH JOIN
	--rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
	--ON
	--[ENROLLMENTS].[STUDENT_GU] = [COURSE_HISTORY].[STUDENT_GU]
	--AND [ENROLLMENTS].[SCHOOL_YEAR] = [COURSE_HISTORY].[SCHOOL_YEAR]
	
WHERE
	[ENROLLMENTS].[SCHOOL_YEAR] = @SchoolYear
	AND [ENROLLMENTS].[GRADE] IN ('09','10','11')
	--AND [ENROLLMENTS].[SCHOOL_NAME] LIKE '%ATRISCO%'
	--AND [ENROLLMENTS].[SCHOOL_CODE] IN ('520','570','590','514','540','576','530','560')
	AND [ENROLLMENTS].[SUMMER_WITHDRAWL_CODE] IS NULL
	AND [ENROLLMENTS].[EXCLUDE_ADA_ADM] IS NULL
	AND [ENROLLMENTS].[EXTENSION] = 'R'
	--AND [STUDENT].[SIS_NUMBER] = '970020796'
	--AND [AVID_STUDENTS].[STUDENT_GU] IS NOT NULL