



EXECUTE AS LOGIN='QueryFileUser'
GO


	SELECT
		[FILE].*
		,CASE WHEN [STUDENT].[SIS_NUMBER] IS NULL THEN 'N' ELSE 'Y' END AS [STUDENT_RECORD_FOUND]
		,CASE WHEN [ENROLLMENT].[STUDENT_GU] IS NULL THEN 'N' ELSE 'Y' END AS [2014_ENROLLMENT_RECORD_FOUND]
		,[ENROLLMENT].[SCHOOL_CODE]
		,[ENROLLMENT].[SCHOOL_NAME]
		,[ENROLLMENT].[ENTER_DATE]
		,[ENROLLMENT].[ENTER_DESCRIPTION]
		,[ENROLLMENT].[LEAVE_DATE]
		,[ENROLLMENT].[LEAVE_CODE]		
		,[ENROLLMENT].[LEAVE_DESCRIPTION]
		,[ENROLLMENT].[EXCLUDE_ADA_ADM]
		,[STUDENT].[DIPLOMA_TYPE]
		,[New Diploma].[VALUE_DESCRIPTION] AS [DIP_TYP_DESC]
		,[STUDENT].[GRADUATION_DATE]
		,[STUDENT].[GRADUATION_STATUS]
		,[GRADUATION_STATUS].[VALUE_DESCRIPTION] AS [GRAD_STAT_DESC]
		,[STUDENT].[POST_SECONDARY]
		,[POST_SECONDARY].[VALUE_DESCRIPTION] AS [PST_SCND_DESC]
		,[EARNED_CREDITS].[TOTAL_CREDITS]
		
	FROM
		OPENROWSET (
			'Microsoft.ACE.OLEDB.12.0', 
			'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
			--'SELECT * from Personal_Needs_Profile_Export_20141125_FULL_DISTRICT.csv'
			'SELECT DISTINCT * from CNM_Summer_students.csv' 
		)AS [FILE]
		
		LEFT OUTER JOIN
		rev.EPC_STU AS [STUDENT]
		ON
		[FILE].[Perm ID] = [STUDENT].[SIS_NUMBER]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','DIPLOMA_TYPE') AS [New Diploma]
		ON
		[STUDENT].[DIPLOMA_TYPE] = [New Diploma].[VALUE_CODE]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','GRADUATION_STATUS') AS [GRADUATION_STATUS]
		ON
		[STUDENT].[GRADUATION_STATUS] = [GRADUATION_STATUS].[VALUE_CODE]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12.Demographics','POST_SECONDARY') AS [POST_SECONDARY]
		ON
		[STUDENT].[POST_SECONDARY] = [POST_SECONDARY].[VALUE_CODE]
		
		LEFT OUTER JOIN
		APS.PrimaryEnrollmentDetailsAsOf('05/22/2015') AS [ENROLLMENT]
		ON
		[STUDENT].[STUDENT_GU] = [ENROLLMENT].[STUDENT_GU] 
		
		LEFT OUTER JOIN
		(
		SELECT
			[HISTORY].[STUDENT_GU]
			,SUM([HISTORY].[CREDIT_COMPLETED]) AS [TOTAL_CREDITS]
			
		FROM
			rev.[EPC_STU_CRS_HIS] AS [HISTORY]
			
			LEFT OUTER JOIN
			APS.LookupTable('K12','Grade') AS [Grades]
			ON
			[HISTORY].[GRADE] = [Grades].[VALUE_CODE]
			
		WHERE
			[Grades].[VALUE_DESCRIPTION] >= '09'
			AND ([HISTORY].[REPEAT_TAG_GU] != '92E81AF7-962A-4D66-ADF9-5FD3FD88FA7D' OR [HISTORY].[REPEAT_TAG_GU] IS NULL)
			
		GROUP BY
			[HISTORY].[STUDENT_GU]
		) AS [EARNED_CREDITS]
		ON
		[STUDENT].[STUDENT_GU] = [EARNED_CREDITS].[STUDENT_GU]
	
REVERT
GO