


DECLARE @GRADE AS VARCHAR(2) = '11'

SELECT
	[SCHOOL_CODE]
	,[SCHOOL_NAME]
	,SUM(CASE WHEN [GENDER] = 'M' THEN 1 ELSE 0 END) AS [MALE]
	,SUM(CASE WHEN [GENDER] = 'F' THEN 1 ELSE 0 END) AS [FEMALE]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'African-American' THEN 1 ELSE 0 END) AS [African-American]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'Hispanic' THEN 1 ELSE 0 END) AS [Hispanic]
	,SUM(CASE WHEN [RESOLVED_RACE] != 'African-American' AND [RESOLVED_RACE] != 'Hispanic' AND [RESOLVED_RACE] != 'White' THEN 1 ELSE 0 END) AS [OTHER]
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[ENROLLMENTS].[GRADE] = @GRADE
	
GROUP BY
	[SCHOOL_CODE]
	,[SCHOOL_NAME]