

SELECT
	COUNT([SIS_NUMBER]) AS [TOTAL]
	,SUM([FREE]) AS [FREE]
	,SUM([PRIORITY 2]) AS [PRIORITY 2]
	,SUM([REDUCED]) AS [REDUCED]
FROM
	(
	SELECT
		[SIS_NUMBER]
		,CASE WHEN [FRMHistory].[FRM_CODE] = 'F' THEN 1 ELSE 0 END AS [FREE]
		,CASE WHEN [FRMHistory].[FRM_CODE] = '2' THEN 1 ELSE 0 END AS [PRIORITY 2]
		,CASE WHEN [FRMHistory].[FRM_CODE] = 'R' THEN 1 ELSE 0 END AS [REDUCED]
	FROM
		APS.PrimaryEnrollmentsAsOf(Getdate()) AS [ENROLLMENTS]
		
		INNER JOIN
		APS.BasicStudent AS [STUDENT]
		ON
		[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		LEFT JOIN
		(
		SELECT
			  ROW_NUMBER() OVER (PARTITION BY [STU].[STUDENT_GU] order by [FRM].[ENTER_DATE],[STU].[STUDENT_GU]) [RN]
			, [STU].[STUDENT_GU]
			, [FRM].[FRM_CODE]
		FROM 
			rev.EPC_STU [STU]
			
			LEFT JOIN 
			rev.EPC_STU_PGM_FRM_HIS [FRM] 
			ON
			[FRM].[STUDENT_GU] = [STU].[STUDENT_GU]
			AND [FRM].[ENTER_DATE] IS NOT NULL 
			AND ([FRM].[EXIT_DATE] IS NOT NULL OR [FRM].[EXIT_DATE] > GETDATE())
		) AS [FRMHistory]
		ON
		[STUDENT].[STUDENT_GU] = [FRMHistory].[STUDENT_GU]
		AND [FRMHistory].[RN] = 1
	) AS [STUDENT LUNCH STATUS]