




SELECT
	[SCHOOL_CODE]
	,[SCHOOL_NAME]
	,SUM(CASE WHEN [GENDER] = 'M' THEN 1 ELSE 0 END) AS [MALE]
	,SUM(CASE WHEN [GENDER] = 'F' THEN 1 ELSE 0 END) AS [FEMALE]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'African-American' THEN 1 ELSE 0 END) AS [African-American]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'Hispanic' THEN 1 ELSE 0 END) AS [Hispanic]
	,SUM(CASE WHEN [RESOLVED_RACE] != 'African-American' AND [RESOLVED_RACE] != 'Hispanic' AND [RESOLVED_RACE] != 'White' THEN 1 ELSE 0 END) AS [OTHER]
FROM
	(
	SELECT
		[STUDENT].*
		,[STU].[GRADUATION_DATE]
		,[STU].[GRADUATION_PLAN]
		,[STU].[GRADUATION_SEMESTER]
		,[STU].[GRADUATION_STATUS]
		,[STU].[GRAD_REQ_DEF_GU]
		,[LAST_ENROLLMENT].[SCHOOL_CODE]
		,[LAST_ENROLLMENT].[SCHOOL_NAME]
	FROM
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		
		INNER JOIN
		rev.EPC_STU AS [STU]
		ON
		[STUDENT].[STUDENT_GU] = [STU].[STUDENT_GU]
		
		INNER JOIN
		(
		SELECT
			[ENROLLMENTS].[SCHOOL_CODE]
			,[ENROLLMENTS].[SCHOOL_NAME]
			,[ENROLLMENTS].[SCHOOL_YEAR]
			,[ENROLLMENTS].[STUDENT_GU]
			,ROW_NUMBER() OVER (PARTITION BY [ENROLLMENTS].[STUDENT_GU] ORDER BY [ENROLLMENTS].[ENTER_DATE] DESC) AS [RN]
		FROM
			APS.StudentEnrollmentDetails AS [ENROLLMENTS]
		WHERE
			[SCHOOL_YEAR] = '2014'
			AND [EXCLUDE_ADA_ADM] IS NULL
		) AS [LAST_ENROLLMENT]
		ON
		[STUDENT].[STUDENT_GU] = [LAST_ENROLLMENT].[STUDENT_GU]
		AND [RN] = 1
		
	WHERE
		[STU].[GRADUATION_STATUS] = 2
		AND [STU].[GRADUATION_DATE] IN ('2015-05-22','2015-07-24')
		
	) AS [GRADUATES]
	
GROUP BY
	[SCHOOL_CODE]
	,[SCHOOL_NAME]