



SELECT
	[COURSE_GU]
	,[COURSE_ID]
	,[SUBJECT_AREA_1]
	,[SUBJECT_AREA_2]
	,[SUBJECT_AREA_3]
	,[STATE_COURSE_CODE]
	,RIGHT(LEFT([STATE_COURSE_CODE],5),1) AS [5TH DIGIT FROM LEFT]
FROM
	rev.[EPC_CRS]
	
WHERE
	[INACTIVE] = 'N'
	
ORDER BY
	RIGHT(LEFT([STATE_COURSE_CODE],5),1)