





--SELECT
--	*
--FROM
--	rev.EPC_CRS_LEVEL_LST

SELECT --DISTINCT
	[COURSE].[COURSE_ID]
	,[COURSE].[STATE_COURSE_CODE]
	,[COURSE].[COURSE_TITLE]
	,[COURSE].[DEPARTMENT]
	,[COURSE].[SUBJECT_AREA_1]
	,[COURSE].[SUBJECT_AREA_2]
	,[COURSE].[SUBJECT_AREA_3]
	,[COURSE].[TECHNICAL_PROVIDER]
	,[COURSE].[OTHER_PROVIDER_NAME]
	,[COURSE].[DUAL_CREDIT]
	,[COURSE_LIST].*
	
FROM
	--(
	--SELECT DISTINCT
	--	[COURSE_ID]
	--	,[COURSE_GU]
	--FROM
	--	APS.ScheduleAsOf(GETDATE()) AS [SCHEDULE]
	--) AS [ACTIVE_COURSES]
	
	--INNER JOIN
	rev.EPC_CRS AS [COURSE]
	--ON
	--[ACTIVE_COURSES].[COURSE_GU] = [COURSE].[COURSE_GU]
	
	LEFT OUTER JOIN
	(
	SELECT
		[LIST_PIVOT].*		
	FROM
		(
		SELECT
			[COURSE_GU]
			,[COURSE_LEVEL]
		FROM
			rev.EPC_CRS_LEVEL_LST 
		) [LIST]
		PIVOT (MIN([COURSE_LEVEL]) FOR [COURSE_LEVEL] IN ([N],[H],[A],[D],[L],[G],[GFT],[C]) ) AS [LIST_PIVOT]
	)AS [COURSE_LIST]
	ON
	[COURSE].[COURSE_GU] = [COURSE_LIST].[COURSE_GU]
	
	--LEFT OUTER JOIN
	--rev.EPC_CRS_LEVEL_LST AS [COURSE_LIST]
	--ON
	--[COURSE].[COURSE_GU] = [COURSE_LIST].[COURSE_GU]
	
WHERE
	--[COURSE].[COURSE_ID] = 'ACAD101'
	[COURSE].[DUAL_CREDIT] = 'Y'
	--AND ([COURSE_LIST].[D] IS NULL)
	
ORDER BY
	[COURSE].[COURSE_ID]
	
	
	
--SELECT DISTINCT
--	[COURSE_LEVEL]
--FROM
--	rev.EPC_CRS_LEVEL_LST 