

SELECT
	[Section].[EXCLUDE_ATTENDANCE]
	,[Section].[EXCLUDE_GRADING]
FROM
	(
		SELECT DISTINCT
			[ENROLLMENT].[SCHOOL_NAME]
			,[SCHEDULE].[COURSE_ID]
			,[SCHEDULE].[SECTION_ID]
			,[SCHEDULE].[COURSE_TITLE]
			,[STAFF_PERSON].[FIRST_NAME]
			,[STAFF_PERSON].[LAST_NAME]
			,[SCHEDULE].[SECTION_GU]
			--,[SCHEDULE].[COURSE_GU]
			--,[ENROLLMENT].[STUDENT_GU]
			,[SCHEDULE].[PERIOD_BEGIN]
			,[SCHEDULE].[PERIOD_END]
			--,[SCHEDULE].*
			
			,[Section].[EXCLUDE_ATTENDANCE]
			,[Section].[EXCLUDE_GRADING]
			
		FROM
			APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENT]
			
			INNER JOIN
			APS.ScheduleAsOf(GETDATE()) AS [SCHEDULE]
			ON
			[ENROLLMENT].[STUDENT_GU] = [SCHEDULE].[STUDENT_GU]
			AND [ENROLLMENT].[STUDENT_SCHOOL_YEAR_GU] = [SCHEDULE].[STUDENT_SCHOOL_YEAR_GU]	
			
			INNER JOIN
			rev.[EPC_SCH_YR_SECT] AS [Section]
			ON
			[SCHEDULE].[SECTION_GU] = [Section].[SECTION_GU]
			
			LEFT OUTER JOIN
			rev.EPC_STAFF AS [STAFF]
			ON
			[SCHEDULE].[STAFF_GU] = [STAFF].[STAFF_GU]
			
			LEFT OUTER JOIN
			rev.REV_PERSON AS [STAFF_PERSON]
			ON
			[SCHEDULE].[STAFF_GU] = [STAFF_PERSON].[PERSON_GU]
			
		WHERE
			[ENROLLMENT].[SCHOOL_CODE] BETWEEN '200' AND '399'
			AND [SCHEDULE].[PERIOD_BEGIN] IN ('10','11','12','13')
	) AS [LIST]
	
	INNER JOIN
	rev.[EPC_SCH_YR_SECT] AS [Section]
	ON
	[LIST].[SECTION_GU] = [Section].[SECTION_GU]
