




SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[GENDER]
	,[STUDENT].[RESOLVED_RACE]
	,[ENROLLMENT].[GRADE]
	,[ENROLLMENT].[SCHOOL_CODE]
	,[ENROLLMENT].[SCHOOL_NAME]
	,CONVERT(VARCHAR(10),[ELL_HISTORY].[EXIT_DATE],101)
	,[ELL_HISTORY].[EXIT_REASON]
	,CASE 
		WHEN [ELL_HISTORY].[EXIT_REASON] = 'EY1' THEN 'Exit Year 1'
		WHEN [ELL_HISTORY].[EXIT_REASON] = 'EY2' THEN 'Exit Year 2'
		WHEN [ELL_HISTORY].[EXIT_REASON] = 'EY3' THEN 'Exit Year 3'
	END AS [EXIT_REASON_DESCRIPTION]
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENT]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.[EPC_STU_PGM_ELL_HIS] AS [ELL_HISTORY]
	ON
	[ENROLLMENT].[STUDENT_GU] = [ELL_HISTORY].[STUDENT_GU]
	
WHERE
	[ELL_HISTORY].[EXIT_REASON] IS NOT NULL
	--AND [ENROLLMENT].[ORGANIZATION_GU] = @School