



EXECUTE AS LOGIN='QueryFileUser'
GO


--SELECT
--	*
--FROM
--	(
	SELECT
		[STUDENT].[SIS_NUMBER]
		,[STUDENT].[STATE_STUDENT_NUMBER]
		,[STUDENT].[FIRST_NAME]
		,[STUDENT].[LAST_NAME]
		,[STUDENT].[MIDDLE_NAME]
		,[ENROLLMENT].[SCHOOL_CODE]
		,[ENROLLMENT].[SCHOOL_NAME]
		,[ENROLLMENT].[SCHOOL_YEAR]
		,[ENROLLMENT].[EXTENSION]
		,[ENROLLMENT].[ENTER_DATE]
		,[ENROLLMENT].[LEAVE_DATE]
		,[ENROLLMENT].[EXCLUDE_ADA_ADM]
		,[ENROLLMENT].[LEAVE_CODE]
		,[ENROLLMENT].[LEAVE_DESCRIPTION]
		
		,[REQUEST_TRACKING].[PERSON_RELEASED_TO]
		,[REQUEST_TRACKING].[RELEASE_DATE]
		,[REQUEST_TRACKING].[RELEASE_PURPOSE]
		,[UD_REQUEST_TRACKING].[NOTES]
		,[RELEASE_PURPOSE].[VALUE_DESCRIPTION]
		,[NON_DISTRICT_SCHOOL].[NAME] AS [TRANSFER_TO_NAME]
		
		--,ROW_NUMBER() OVER (PARTITION BY [FILE].[Student ID] ORDER BY [ENROLLMENT].[ENTER_DATE] DESC) AS RN
	FROM
		APS.BasicStudent AS [STUDENT]
		
		LEFT OUTER JOIN
		APS.StudentEnrollmentDetails AS [ENROLLMENT]
		ON
		[STUDENT].[STUDENT_GU] = [ENROLLMENT].[STUDENT_GU]
		AND [ENROLLMENT].[EXCLUDE_ADA_ADM] IS NULL
		--AND [ENROLLMENT].[SCHOOL_YEAR] = '2014'
		--AND [ENROLLMENT].[EXTENSION] = 'R'
		
		LEFT JOIN
		rev.[EPC_STU_REQUEST_TRACKING] AS [REQUEST_TRACKING]
		ON
		[ENROLLMENT].[STUDENT_GU] = [REQUEST_TRACKING].[STUDENT_GU]
		
		LEFT JOIN 
		rev.[EPC_SCH_NON_DST] AS [NON_DISTRICT_SCHOOL] -- Contains the School Name
		ON 
		[REQUEST_TRACKING].[SCHOOL_NON_DISTRICT_GU] = [NON_DISTRICT_SCHOOL].[SCHOOL_NON_DISTRICT_GU]
		
		LEFT JOIN
		APS.LookupTable('K12.CourseHistoryInfo','RELEASE_PURPOSE') AS [RELEASE_PURPOSE]
		ON
		[REQUEST_TRACKING].[RELEASE_PURPOSE] = [RELEASE_PURPOSE].[VALUE_CODE]
		
		LEFT OUTER JOIN
		rev.UD_STU_REQUEST_TRACKING AS [UD_REQUEST_TRACKING]
		ON
		[REQUEST_TRACKING].[STU_REQUEST_TRACKING_GU] = [UD_REQUEST_TRACKING].[STU_REQUEST_TRACKING_GU]
		
	WHERE
		[ENROLLMENT].[LEAVE_DATE] IS NOT NULL
		
	ORDER BY
		[STUDENT].[SIS_NUMBER]
		
--	) AS [STUDENT_ENROLLMENTS]
	
--WHERE
--	[RN] = 1
	
--ORDER BY
--	[ENROLLMENT].[SCHOOL_CODE]

REVERT
GO