



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[2015_ENROLLMENTS].[GRADE]
	,[2015_ENROLLMENTS].[SCHOOL_CODE]
	,[2015_ENROLLMENTS].[SCHOOL_NAME]
	,CONVERT(VARCHAR(10),[2015_ENROLLMENTS].[ENTER_DATE],101) AS [ENTER_DATE]
	,CONVERT(VARCHAR(10),[2015_ENROLLMENTS].[LEAVE_DATE],101) AS [LEAVE_DATE]
	,[2015_ENROLLMENTS].[LEAVE_CODE]
	,[2015_ENROLLMENTS].[LEAVE_DESCRIPTION]
	
	--,[2015_ENROLLMENTS].*
	
	,[SOR].[ATTEND_PERMIT_CODE]
	
	--,[PREVIOUS_ENROLLMENTS].*
	
	,CASE WHEN ISNUMERIC([EPC_STU].[GRID_CODE]) = 0 OR [EPC_STU].[GRID_CODE] = '99999' THEN [EPC_STU].[GRID_CODE] ELSE LEFT([EPC_STU].[GRID_CODE],3) END AS [GRID_CODE_ES]
	,[ELEMENTARY_SCHOOL].[ORGANIZATION_NAME] AS [ELEM SCHOOL]
	,CASE WHEN ISNUMERIC([EPC_STU].[GRID_CODE]) = 0 OR [EPC_STU].[GRID_CODE] = '99999' THEN '' ELSE RIGHT(LEFT([EPC_STU].[GRID_CODE],6),3) END AS [GRID_CODE_MS]
	,[MIDDLE_SCHOOL].[ORGANIZATION_NAME] AS [MID SCHOOL]
	,CASE WHEN ISNUMERIC([EPC_STU].[GRID_CODE]) = 0 OR [EPC_STU].[GRID_CODE] = '99999' THEN '' ELSE RIGHT([EPC_STU].[GRID_CODE],3) END AS [GRID_CODE_ES]
	,[HIGH_SCHOOL].[ORGANIZATION_NAME] AS [HIGH SCHOOL]
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [2015_ENROLLMENTS]	
	
	INNER JOIN
	APS.BASICSTUDENT AS [STUDENT]
	ON
	[2015_ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.EPC_STU AS [EPC_STU]
	ON
	[STUDENT].[STUDENT_GU] = [EPC_STU].[STUDENT_GU]
	
	INNER JOIN
	rev.EPC_STU_SCH_YR AS [SOR]
	ON
	[2015_ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [SOR].[STUDENT_SCHOOL_YEAR_GU]
	
	--LEFT OUTER JOIN
	--(
	--SELECT
	--	*
	--	,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	--FROM
	--	APS.StudentEnrollmentDetails
		
	--WHERE
	--	SCHOOL_YEAR <= 2015
	--	AND 
	--	EXTENSION = 'R'
	--	--AND EXCLUDE_ADA_ADM IS NULL
	--	--AND (LEAVE_DATE IS NOT NULL OR SCHOOL_YEAR = 2014)
	--	AND [SCHOOL_CODE] NOT IN ('410','416')
	--) AS [PREVIOUS_ENROLLMENTS]
	--ON
	--[2015_ENROLLMENTS].[STUDENT_GU] = [PREVIOUS_ENROLLMENTS].[STUDENT_GU]
	--AND [PREVIOUS_ENROLLMENTS].[RN] = 1
	
	LEFT OUTER JOIN
	rev.EPC_GRID AS [SCHOOL_GRID]
	ON
	[EPC_STU].[GRID_CODE] = [SCHOOL_GRID].[GRID_CODE]
	AND [2015_ENROLLMENTS].[SCHOOL_YEAR] = [SCHOOL_GRID].[SCHOOL_YEAR]
	
	LEFT OUTER JOIN
	rev.REV_ORGANIZATION AS [ELEMENTARY_SCHOOL]
	ON
	[SCHOOL_GRID].[ELEM_SCHOOL_GU] = [ELEMENTARY_SCHOOL].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN
	rev.REV_ORGANIZATION AS [MIDDLE_SCHOOL]
	ON
	[SCHOOL_GRID].[JR_HIGH_SCHOOL_GU] = [MIDDLE_SCHOOL].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN
	rev.REV_ORGANIZATION AS [HIGH_SCHOOL]
	ON
	[SCHOOL_GRID].[SR_HIGH_SCHOOL_GU] = [HIGH_SCHOOL].[ORGANIZATION_GU]
	
WHERE
	[2015_ENROLLMENTS].[SCHOOL_CODE] IN ('410','416')
	AND [2015_ENROLLMENTS].[GRADE] IN ('06','07','08')
	AND [SOR].[ATTEND_PERMIT_CODE] = 'TRAN'
	--AND [STUDENT].[SIS_NUMBER] = '970019628' 
	--AND [STUDENT].[SIS_NUMBER] = '577698434'
	
ORDER BY
	[2015_ENROLLMENTS].[SCHOOL_NAME]