
/*
15-16 '10/14/2015'
14-15 '10/8/2014'
13-14 '10/9/2013'
*/



SELECT
	[ENROLLMENT].[SCHOOL_CODE]
	,[ENROLLMENT].[SCHOOL_NAME]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENT].[GRADE]
	,[STUDENT].[GENDER]
	--,[STUDENT].[HISPANIC_INDICATOR]
	--,[STUDENT].[RACE_1]
	,[STUDENT].[RESOLVED_RACE]
	
	--,[ATTENDANCE].*
	,[SMAX_STUDENT].*
	
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf('10/9/2013') AS [ENROLLMENT]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	--LEFT OUTER JOIN
	--APS.PeriodUnexcusedAsOf('10/14/2015') AS [ATTENDANCE]
	--ON
	--[STUDENT].[SIS_NUMBER] = [ATTENDANCE].[SIS_NUMBER]
	
	LEFT OUTER JOIN
		OPENQUERY([011-SYNERGYDB.APS.EDU.ACTD],'
			SELECT
			IV3.DST_NBR
			--,IV3.MNT_DT
			--,IV3.SCH_NBR
			,IV3.ID_NBR
			,IV3.SCH_YR
			--,IV3.KEYVALUE
			
			--SUM The absence types into their respective columns. UX = Unexcused, EX = Excused. 
			,SUM(CASE WHEN (IV3.FIELDNUM=80) THEN 1.0 ELSE 0.0 END) AS UX_FULL_DAY
			,SUM(CASE WHEN (IV3.FIELDNUM=82) THEN 1.0 ELSE 0.0 END) AS UX_HALF_DAY
			,SUM(CASE WHEN (IV3.FIELDNUM=84) THEN 1.0 ELSE 0.0 END) AS EX_FULL_DAY
			,SUM(CASE WHEN (IV3.FIELDNUM=86) THEN 1.0 ELSE 0.0 END) AS EX_HALF_DAY
		
			,SUM(CASE WHEN (IV3.FIELDNUM=80) THEN 1.0 ELSE 0.0 END) 
			+SUM(CASE WHEN (IV3.FIELDNUM=82) THEN 1.0 ELSE 0.0 END)/2.0
			+SUM(CASE WHEN (IV3.FIELDNUM=84) THEN 1.0 ELSE 0.0 END) 
			+SUM(CASE WHEN (IV3.FIELDNUM=86) THEN 1.0 ELSE 0.0 END)/2.0 AS [TOTAL ABSENCES]
						
		FROM
			--Join IV table to CurrentPrimaryEnrollment 
			PR.DBTSIS.IV030_V AS IV3

		WHERE
			IV3.DST_NBR = 1
			AND IV3.SCH_YR = 2013
			AND IV3.KEYVALUE <= 20131009
			--AND IV3.KEYVALUE IS NOT NULL
			
		GROUP BY 
			IV3.DST_NBR
			,IV3.ID_NBR
			--,IV3.SCH_NBR
			--,IV3.MNT_DT
			,IV3.SCH_YR
			') AS [SMAX_STUDENT]
		ON
		[STUDENT].[SIS_NUMBER] = [SMAX_STUDENT].[ID_NBR]
	
WHERE
	[ENROLLMENT].[SCHOOL_CODE] IN ('410','416')
	
	--410 416