



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[2015_ENROLLMENTS].[GRADE]
	,[2015_ENROLLMENTS].[SCHOOL_CODE]
	,[2015_ENROLLMENTS].[SCHOOL_NAME]
	--,[2015_ENROLLMENTS].[ORGANIZATION_GU]
	--,[2015_ENROLLMENTS].[YEAR_GU]
	,CONVERT(VARCHAR(10),[2015_ENROLLMENTS].[ENTER_DATE],101) AS [ENTER_DATE]
	,CONVERT(VARCHAR(10),[2015_ENROLLMENTS].[LEAVE_DATE],101) AS [LEAVE_DATE]
	,[2015_ENROLLMENTS].[LEAVE_CODE]
	,[2015_ENROLLMENTS].[LEAVE_DESCRIPTION]
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [2015_ENROLLMENTS]	
	
	INNER JOIN
	APS.BASICSTUDENT AS [STUDENT]
	ON
	[2015_ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[2015_ENROLLMENTS].[SCHOOL_CODE] IN ('410','416')
	AND [2015_ENROLLMENTS].[GRADE] IN ('07','08')
	AND [2015_ENROLLMENTS].[STUDENT_GU] NOT IN (SELECT [STUDENT_GU] FROM APS.PrimaryEnrollmentDetailsAsOf('05/22/2015') )
	
ORDER BY
	[2015_ENROLLMENTS].[SCHOOL_NAME]