
/*
15-16 '10/14/2015'
14-15 '10/8/2014'
13-14 '10/9/2013'
*/

SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENT].[GRADE]
	,[STUDENT].[GENDER]
	--,[STUDENT].[HISPANIC_INDICATOR]
	--,[STUDENT].[RACE_1]
	,[STUDENT].[RESOLVED_RACE]
	
	,[DISCIPLINE].*
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf('10/9/2013') AS [ENROLLMENT]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	(
	SELECT
		COUNT([DISCIPLINE].[INCIDENT_ROLE]) AS [TOTAL]
		,[DISCIPLINE].[STUDENT_GU]
		,[StudentSchoolYear].[YEAR_GU]
	FROM
		rev.EPC_STU_INC_DISCIPLINE AS [DISCIPLINE]
		
		INNER JOIN
		rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
		ON
		[DISCIPLINE].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
		
	GROUP BY
		[DISCIPLINE].[STUDENT_GU]
		,[StudentSchoolYear].[YEAR_GU]
	) AS [DISCIPLINE]
	ON
	[ENROLLMENT].[STUDENT_GU] = [DISCIPLINE].[STUDENT_GU]
	AND [ENROLLMENT].[YEAR_GU] = [DISCIPLINE].[YEAR_GU]
	
WHERE
	[ENROLLMENT].[SCHOOL_CODE] IN ('410','416')
	
	--410 416