



SELECT --DISTINCT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENT].[GRADE]
	,[ENROLLMENT].[SCHOOL_CODE]
	,[ENROLLMENT].[SCHOOL_NAME]
	
	,[STUDENT_FEES].[TRANSACTION_DATE]
	,[STUDENT_FEES].[DESCRIPTION]
	,[STUDENT_FEES].[FEE_CATEGORY]
	,[STUDENT_FEES].[FEE_CODE_GU]
	,[STUDENT_FEES].[CREDIT_AMOUNT]
	,[STUDENT_FEES].[NOTE]
	,[STUDENT_FEES].[REFUND_NEEDED]
	,[STUDENT_FEES].[FEE_STATUS]
	,[STUDENT_FEES].[ADD_DATE_TIME_STAMP]
	
FROM
	[rev].[EPC_STU_FEE] AS [STUDENT_FEES]
	
	LEFT OUTER JOIN
	[rev].[EPC_STU_FEE_PAYMENT] AS [PAYMENT]
	ON
	[STUDENT_FEES].[STUDENT_FEE_GU] = [PAYMENT].[STU_FEE_GU]
	
	LEFT OUTER JOIN
	[rev].[EPC_STU_FEE_PAY_TRANS] AS [PAYMENT_TRANSACTION]
	ON
	[PAYMENT].[STU_FEE_PAY_TRANS_GU] = [PAYMENT_TRANSACTION].[STU_FEE_PAY_TRANS_GU]
	
	LEFT OUTER JOIN
	APS.StudentEnrollmentDetails AS [ENROLLMENT]
	ON
	[STUDENT_FEES].[STUDENT_SCHOOL_YEAR_GU] = [ENROLLMENT].[STUDENT_SCHOOL_YEAR_GU]
	
	LEFT OUTER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[STUDENT_FEES].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[ENROLLMENT].[SCHOOL_CODE] IN ('540','550','560','576','580')
	AND [STUDENT_FEES].[FEE_CATEGORY] = 'ACT'
	--AND [STUDENT_FEES].[DESCRIPTION] IN ('Damaged Textbook','Lost Textbook')
	AND [STUDENT_FEES].[DESCRIPTION] LIKE '%Textbook%'
	
	