
DECLARE @School VARCHAR = '%'
DECLARE @Year VARCHAR = '%'


SET @Year = '26F066A3-ABFC-4EDB-B397-43412EDABC8B'


SELECT
	[Organization].[ORGANIZATION_NAME]
	,[School].[SCHOOL_CODE]
	,[GENERAL_HEALTH].[TOTAL] AS [GENERAL SCREENINGS]
	,[VISION_HEALTH].[TOTAL] AS [VISION SCREENINGS]
	,[AUD_HEALTH].[TOTAL] AS [AUDIO SCREENINGS]
	,[DEN_HEALTH].[TOTAL] AS [DENTAL SCREENINGS]
	
	--,[RevYear].[YEAR_GU]
	--,[School].*
FROM
	rev.REV_ORGANIZATION_YEAR AS [OrgYear]
	
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[OrgYear].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	LEFT OUTER JOIN
	(
	SELECT
		[ORGANIZATION_YEAR_GU]
		,COUNT([SCREEN_DATE]) [TOTAL]
	FROM
		rev.[EPC_STU_HEALTH_SCR_GEN]	
	GROUP BY
		[ORGANIZATION_YEAR_GU]
	) AS [GENERAL_HEALTH]
	ON
	[OrgYear].[ORGANIZATION_YEAR_GU] = [GENERAL_HEALTH].[ORGANIZATION_YEAR_GU]
	
	LEFT OUTER JOIN	
	(
	SELECT
		[ORGANIZATION_YEAR_GU]
		,COUNT([SCREEN_DATE]) [TOTAL]
	FROM
		rev.[EPC_STU_HEALTH_SCR_VISION]	
	GROUP BY
		[ORGANIZATION_YEAR_GU]
	) AS [VISION_HEALTH]
	ON
	[OrgYear].[ORGANIZATION_YEAR_GU] = [VISION_HEALTH].[ORGANIZATION_YEAR_GU]

	LEFT OUTER JOIN
	(
	SELECT
		[ORGANIZATION_YEAR_GU]
		,COUNT([SCREEN_DATE]) [TOTAL]
	FROM
		rev.[EPC_STU_HEALTH_SCR_AUD]	
	GROUP BY
		[ORGANIZATION_YEAR_GU]
	) AS [AUD_HEALTH]
	ON
	[OrgYear].[ORGANIZATION_YEAR_GU] = [AUD_HEALTH].[ORGANIZATION_YEAR_GU]
	
	LEFT OUTER JOIN
	(
	SELECT
		[ENROLLMENT].[ORGANIZATION_YEAR_GU]
		,COUNT([DENTAL].[SCREEN_DATE]) AS [TOTAL]
	FROM
		rev.EPC_STU_HEALTH_SCR_DEN AS [DENTAL]
		
		INNER JOIN
		(
		SELECT
			[StudentSchoolYear].[STUDENT_GU]
			,[StudentSchoolYear].[ORGANIZATION_YEAR_GU]
			,[StudentSchoolYear].[ENTER_DATE]
			,[StudentSchoolYear].[LEAVE_DATE]
			,YearDates.[END_DATE]
			,ROW_NUMBER() OVER (PARTITION BY [StudentSchoolYear].[STUDENT_GU], [StudentSchoolYear].[YEAR_GU] ORDER BY [StudentSchoolYear].[ENTER_DATE] DESC) AS RN
		FROM
			rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
			INNER JOIN
			APS.YearDates
			ON
			[StudentSchoolYear].[YEAR_GU] = YearDates.[YEAR_GU]
		WHERE
			[StudentSchoolYear].[EXCLUDE_ADA_ADM] IS NULL
		) AS [ENROLLMENT]
		ON
		[DENTAL].[STUDENT_GU] = [ENROLLMENT].[STUDENT_GU]
		AND [DENTAL].[SCREEN_DATE] BETWEEN [ENROLLMENT].[ENTER_DATE] AND COALESCE([ENROLLMENT].LEAVE_DATE, [ENROLLMENT].END_DATE)
		AND [ENROLLMENT].[RN] = 1
		
	GROUP BY
		[ENROLLMENT].[ORGANIZATION_YEAR_GU]
	) AS [DEN_HEALTH]
	ON
	[OrgYear].[ORGANIZATION_YEAR_GU] = [DEN_HEALTH].[ORGANIZATION_YEAR_GU]
	
	
WHERE
	--[RevYear].[SCHOOL_YEAR] = '2014'
	--AND [RevYear].[EXTENSION] = 'R'
	[OrgYear].[ORGANIZATION_GU] LIKE @School
	AND [RevYear].[YEAR_GU] LIKE @Year
	--AND [RevYear].[YEAR_GU] = '26F066A3-ABFC-4EDB-B397-43412EDABC8B'
	
	AND [School].[STATE_SCHOOL_CODE] IS NOT NULL
	AND ISNUMERIC([School].[SCHOOL_CODE]) = 1
	
ORDER BY
	--[OrgYear].[ORGANIZATION_YEAR_GU]
	--[School].[SCHOOL_CODE]
	[Organization].[ORGANIZATION_NAME]
	
	
