





SELECT DISTINCT
	[ENROLLMENT].[SCHOOL_CODE]
	,[ENROLLMENT].[SCHOOL_NAME]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[GENDER]
	,[ENROLLMENT].[GRADE]
	,[STUDENT].[RESOLVED_RACE]
	,[STUDENT].HISPANIC_INDICATOR
	,[STUDENT].[SPED_STATUS]
	,[STUDENT].[ELL_STATUS]
	,[SCHEDULE].[SECTION_ID]
	,[SCHEDULE].[COURSE_ID]
	,[SCHEDULE].[COURSE_TITLE]
	--,[ASSIGNED_STAFF].[PRIMARY_TEACHER]
	--,[STAFF_PERSON].[LAST_NAME]
	--,[STAFF_PERSON].[FIRST_NAME]
	,[SCHEDULE].[TERM_CODE]
	,[SCHEDULE].[ROOM_SIMPLE]
	,[SCHEDULE].[PERIOD_BEGIN]
	,[SCHEDULE].[PERIOD_END]
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENT]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	APS.ScheduleAsOf(GETDATE()) AS [SCHEDULE]
	ON
	[ENROLLMENT].[STUDENT_GU] = [SCHEDULE].[STUDENT_GU]
	AND [ENROLLMENT].[ORGANIZATION_YEAR_GU] = [SCHEDULE].[ORGANIZATION_YEAR_GU]
	
	--LEFT OUTER JOIN
	--APS.SectionsAndAllStaffAssignedAsOf(GETDATE()) AS [ASSIGNED_STAFF]
	--ON
	--[SCHEDULE].[SECTION_GU] = [ASSIGNED_STAFF].[SECTION_GU]
	
	--LEFT OUTER JOIN
	--rev.EPC_STAFF AS [STAFF]
	--ON
	--[ASSIGNED_STAFF].[STAFF_GU] = [STAFF].[STAFF_GU]
	
	--LEFT OUTER JOIN
	--rev.REV_PERSON AS [STAFF_PERSON]
	--ON
	--[ASSIGNED_STAFF].[STAFF_GU] = [STAFF_PERSON].[PERSON_GU]
	
WHERE
	[SCHEDULE].[SECTION_ID] LIKE 'i%'