




DECLARE @AsOfDate DATETIME = GETDATE()


SELECT
	[SCHOOL_NAME]
	,[COURSE_ID]
	,[SECTION_ID]
	,[STAF_PERSON].[FIRST_NAME]
	,[STAF_PERSON].[LAST_NAME]
	,[STUDENT_COUNT]
	,[MAX_GRADE]
	,[ASSIGNED_STAFF]
	,CASE 
		WHEN [COURSE_ID] IN ('00004000','00008000') AND [STUDENT_COUNT] > 15 AND [ASSIGNED_STAFF] < 2 THEN 'Y'
		WHEN [COURSE_ID] IN ('00014000','00018000','00052015','00056015') AND [STUDENT_COUNT] > 21 AND [ASSIGNED_STAFF] < 2 THEN 'Y'
		ELSE 'N'
	END AS [OVERLOAD]
FROM
	(
	SELECT
		[SCHOOL_NAME]
		--,[SCHOOL_CODE]
		,[COURSE_ID]
		,[SECTION_ID]
		,[CLASS_COUNTS].[SECTION_GU]
		
		--,[STAFF_PERSON].[FIRST_NAME]
		--,[STAFF_PERSON].[LAST_NAME]
		--,[ASSIGNED_STAFF].[PRIMARY_TEACHER]
		,[STUDENT_COUNT]
		--,[MAX_GRADE]
		,[Grades].[VALUE_DESCRIPTION] AS [MAX_GRADE]
		,COUNT(DISTINCT [STAFF].[BADGE_NUM]) AS [ASSIGNED_STAFF]
	FROM
		(
		SELECT
			[SCHOOL_NAME]
			,[SCHOOL_CODE]
			,[COURSE_ID]
			,[SECTION_ID]
			,[SECTION_GU]
			,COUNT([STUDENT_GU]) AS [STUDENT_COUNT]
			,MAX([LIST_ORDER]) AS [MAX_GRADE]
		FROM
			(
			SELECT
				[ENROLLMENT].[GRADE]
				,[ENROLLMENT].[LIST_ORDER]
				,[ENROLLMENT].[SCHOOL_CODE]
				,[ENROLLMENT].[SCHOOL_NAME]
				,[SCHEDULE].[COURSE_ID]
				,[SCHEDULE].[SECTION_ID]
				,[SCHEDULE].[COURSE_TITLE]
				,[SCHEDULE].[SECTION_GU]
				,[SCHEDULE].[COURSE_GU]
				,[ENROLLMENT].[STUDENT_GU]
				--,[SCHEDULE].*
			FROM
				APS.PrimaryEnrollmentDetailsAsOf(@AsOfDate) AS [ENROLLMENT]
				
				INNER JOIN
				APS.ScheduleAsOf(@AsOfDate) AS [SCHEDULE]
				ON
				[ENROLLMENT].[STUDENT_GU] = [SCHEDULE].[STUDENT_GU]
				AND [ENROLLMENT].[STUDENT_SCHOOL_YEAR_GU] = [SCHEDULE].[STUDENT_SCHOOL_YEAR_GU]		
				
			WHERE
				[SCHEDULE].[COURSE_ID] IN ('00004000','00008000','00014000','00018000','00052015','00056015')
				AND [ENROLLMENT].[ORGANIZATION_GU] LIKE @School
			) AS [CLASSES]
			
		GROUP BY
			[SCHOOL_NAME]
			,[SCHOOL_CODE]
			,[COURSE_ID]
			,[SECTION_ID]
			,[SECTION_GU]
		) AS [CLASS_COUNTS]
		
		LEFT OUTER JOIN
		APS.SectionsAndAllStaffAssigned AS [ASSIGNED_STAFF]
		ON
		[CLASS_COUNTS].[SECTION_GU] = [ASSIGNED_STAFF].[SECTION_GU]
		
		LEFT OUTER JOIN
		rev.EPC_STAFF AS [STAFF]
		ON
		[ASSIGNED_STAFF].[STAFF_GU] = [STAFF].[STAFF_GU]
		
		LEFT OUTER JOIN
		rev.REV_PERSON AS [STAFF_PERSON]
		ON
		[ASSIGNED_STAFF].[STAFF_GU] = [STAFF_PERSON].[PERSON_GU]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','Grade') AS [Grades]
		ON
		[MAX_GRADE] = [Grades].[LIST_ORDER]
		
	WHERE
		[MAX_GRADE] NOT IN ('60','70')
		
	GROUP BY
		[SCHOOL_NAME]
		,[COURSE_ID]
		,[SECTION_ID]
		,[CLASS_COUNTS].[SECTION_GU]
		,[STUDENT_COUNT]
		,[Grades].[VALUE_DESCRIPTION]
	) AS [STAFF_AND_STUDENTS]
	
	LEFT OUTER JOIN
	APS.SectionsAndAllStaffAssigned AS [PRIMARY_STAFF]
	ON
	[STAFF_AND_STUDENTS].[SECTION_GU] = [PRIMARY_STAFF].[SECTION_GU]
	AND [PRIMARY_STAFF].[PRIMARY_TEACHER] = 'Y'
	
	LEFT OUTER JOIN
	rev.REV_PERSON AS [STAF_PERSON]
	ON
	[PRIMARY_STAFF].[STAFF_GU] = [STAF_PERSON].[PERSON_GU]
	
ORDER BY
	[SCHOOL_NAME]