



SELECT DISTINCT
	[ENROLLMENT].[SCHOOL_CODE]
	,[ENROLLMENT].[SCHOOL_NAME]
	,REPLACE([STAFF].[BADGE_NUM],'e','') AS [BADGE_NUM]
	,[STAFF_PERSON].[LAST_NAME]
	,[STAFF_PERSON].[FIRST_NAME]
	,[STAFF_PERSON].[MIDDLE_NAME]
	,[STAFF_PERSON].[EMAIL]
	,[SCHEDULE].[DEPARTMENT]
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENT]
	
	INNER JOIN
	APS.ScheduleDetailsAsOf(GETDATE()) AS [SCHEDULE]
	ON
	[ENROLLMENT].[STUDENT_GU] = [SCHEDULE].[STUDENT_GU]
	AND [ENROLLMENT].[ORGANIZATION_YEAR_GU] = [SCHEDULE].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN
	rev.[EPC_STAFF] AS [STAFF]
	ON
	[SCHEDULE].[STAFF_GU] = [STAFF].[STAFF_GU]
	
	INNER JOIN
	rev.[REV_PERSON] AS [STAFF_PERSON]
	ON
	[STAFF].[STAFF_GU] = [STAFF_PERSON].[PERSON_GU]
	
WHERE
	[ENROLLMENT].[GRADE] >= '06'
	AND [SCHEDULE].[DEPARTMENT] IN ('Math','Sci')