



EXECUTE AS LOGIN='QueryFileUser'
GO

	SELECT DISTINCT
		--[FILE].[ID_NBR]
		[STUDENT].[SIS_NUMBER]
		--,[STUDENT].[FIRST_NAME]
		--,[STUDENT].[LAST_NAME]
		--,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
		--,[COURSE_HISTORY].[SCHOOL_YEAR]
		--,[COURSE_HISTORY].[COURSE_ID]
		--,[COURSE_HISTORY].[COURSE_TITLE]
		----,[COURSE].[DEPARTMENT]
		--,[COURSE_HISTORY].[TERM_CODE]
		--,[COURSE_HISTORY].[REPEAT_TAG_GU]
		--,[COURSE_HISTORY].[MARK]
		--,[COURSE_HISTORY].[CREDIT_ATTEMPTED]
		--,[COURSE_HISTORY].[CREDIT_COMPLETED]
		--,[COURSE_HISTORY].[COURSE_HISTORY_TYPE]
		
	FROM
		OPENROWSET (
			'Microsoft.ACE.OLEDB.12.0', 
			'Text;Database=\\SynTempSSIS\Files\TempQuery\;',
			'SELECT * from Algebra1UniqueIDs.csv' 
		)AS [FILE]
		
		LEFT JOIN
		APS.BasicStudent AS [STUDENT]
		ON
		[FILE].[ID_NBR] = [STUDENT].[SIS_NUMBER]
		
		LEFT JOIN
		rev.EPC_STU_CRS_HIS AS [COURSE_HISTORY]
		ON
		[STUDENT].[STUDENT_GU] = [COURSE_HISTORY].[STUDENT_GU]
		
		LEFT JOIN
		rev.EPC_CRS AS [COURSE]
		ON
		[COURSE_HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','Grade') AS [Grades]
		ON
		[COURSE_HISTORY].[GRADE] = [Grades].[VALUE_CODE]
	
	WHERE
		[COURSE].[DEPARTMENT] = 'Math'
		
	
REVERT
GO