



--SELECT
--	[STUDENTS].[SIS_NUMBER]
--	,[STUDENTS].[FIRST_NAME]
--	,[STUDENTS].[LAST_NAME]
--	,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
--	,[COURSE_HISTORY].[SCHOOL_YEAR]
--	,[COURSE_HISTORY].[COURSE_ID]
--	,[COURSE_HISTORY].[COURSE_TITLE]
--	,[COURSE].[DEPARTMENT]
--	,[COURSE_HISTORY].[TERM_CODE]
	
--FROM
--	(
	SELECT
		[STUDENT].[SIS_NUMBER]
		,[STUDENT].[FIRST_NAME]
		,[STUDENT].[LAST_NAME]
		--,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
		--,CASE WHEN [Organization].[ORGANIZATION_NAME] IS NULL THEN [NON_DST_SCHOOL].[NAME] ELSE [Organization].[ORGANIZATION_NAME] END AS [SCHOOL_NAME]
		,[ENROLLMENTS_9].GRADE AS [GRADE_ENTERED_APS_HS]
		,[ENROLLMENTS_9].[SCHOOL_CODE] AS [SCHOOL_CODE_1ST_HS]
		,[ENROLLMENTS_9].[SCHOOL_NAME] AS [SCHOOL_NAME]
		,[COURSE_HISTORY].[SCHOOL_YEAR]
		,[Grades].[VALUE_DESCRIPTION] AS [GRADE_ALG1_TAKEN]
		,[COURSE_HISTORY].[COURSE_ID]
		,[COURSE_HISTORY].[COURSE_TITLE]
		,[COURSE].[DEPARTMENT]
		,[COURSE_HISTORY].[TERM_CODE]
		,[COURSE_HISTORY].[REPEAT_TAG_GU]
		,[COURSE_HISTORY].[MARK]
		,[COURSE_HISTORY].[COURSE_HISTORY_TYPE]
		,[COURSE_HISTORY].[STUDENT_GU]
		
		,[NON_DIST].[NAME] AS [NON_DISTRICT_SCHOOL]
		
	FROM
		rev.EPC_STU_CRS_HIS AS [COURSE_HISTORY]
		
		INNER JOIN
		rev.EPC_CRS AS [COURSE]
		ON
		[COURSE_HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
		
		INNER JOIN
		APS.BasicStudent AS [STUDENT] 
		ON
		[COURSE_HISTORY].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		LEFT OUTER JOIN 
		rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
		ON 
		[COURSE_HISTORY].[SCHOOL_IN_DISTRICT_GU] = [Organization].[ORGANIZATION_GU]
		
		LEFT OUTER JOIN
		rev.EPC_SCH_NON_DST AS [NON_DST_SCHOOL]
		ON
		[COURSE_HISTORY].[SCHOOL_NON_DISTRICT_GU] = [NON_DST_SCHOOL].[SCHOOL_NON_DISTRICT_GU]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','Grade') AS [Grades]
		ON
		[COURSE_HISTORY].[GRADE] = [Grades].[VALUE_CODE]
		
		INNER JOIN
		rev.[EPC_SCH_NON_DST] AS [NON_DIST]
		ON
		[COURSE_HISTORY].[SCHOOL_NON_DISTRICT_GU] = [NON_DIST].[SCHOOL_NON_DISTRICT_GU]
		
		-- GET FIRST HIGH SCHOOL THAT THEY ENTERED APS
		LEFT OUTER JOIN
		(
		SELECT
			[STUDENT_GU]
			,[SCHOOL_CODE]
			,[SCHOOL_NAME]
			,GRADE
			,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY GRADE ASC, ENTER_DATE DESC) AS RN
		FROM
			APS.StudentEnrollmentDetails
		WHERE
			--SCHOOL_YEAR = '2014'
			--AND EXTENSION = 'R'
			GRADE IN ('09','10','11','12')
			AND EXCLUDE_ADA_ADM IS NULL
			AND ENTER_DATE IS NOT NULL
			AND LEAVE_DATE IS NULL
		
		)  AS [ENROLLMENTS_9]
		ON
		[COURSE_HISTORY].[STUDENT_GU] = [ENROLLMENTS_9].[STUDENT_GU]
		AND [ENROLLMENTS_9].[RN] = 1
		
	WHERE
		[SCHOOL_YEAR] = '2014'
	--	[STUDENT].[SIS_NUMBER] = '970112082'
		--AND [Grades].[VALUE_DESCRIPTION] IN ('06','07','08')
		AND [COURSE_HISTORY].[COURSE_ID] IN
		('330400', 
		'330401', 
		'330402', 
		'330403', 
		'330471', 
		'330472', 
		'330801', 
		'330802', 
		'330811', 
		'330812', 
		'3304000', 
		'060C41', 
		'060C42', 
		'061C1', 
		'061C11', 
		'061C12', 
		'061C41', 
		'061C42', 
		'061C51', 
		'061C52', 
		'062C11', 
		'062C12', 
		'33040C', 
		'33040C1', 
		'33040C2', 
		'33040DE1', 
		'33040DE2', 
		'33040DI1', 
		'33040DI2', 
		'3304A1', 
		'3304A2', 
		'MATH322', 
		'330401de1', 
		'330401de2', 
		'311001', 
		'311002', 
		'3110B1', 
		'3110B2', 
		'3110D1', 
		'3110D2', 
		'312001', 
		'312002', 
		'312101', 
		'312102',
		'3110B',
		'3110D',
		'31100')
		
	--ORDER BY
	--	[STUDENT].[SIS_NUMBER]
	--	,[COURSE_HISTORY].[TERM_CODE]
--	) AS [STUDENTS]
	
--	INNER JOIN
--	rev.EPC_STU_CRS_HIS AS [COURSE_HISTORY]
--	ON
--	[STUDENTS].[STUDENT_GU] = [COURSE_HISTORY].[STUDENT_GU]
	
--	INNER JOIN
--	rev.EPC_CRS AS [COURSE]
--	ON
--	[COURSE_HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
	
--	INNER JOIN
--	APS.LookupTable('K12','Grade') AS [Grades]
--	ON
--	[COURSE_HISTORY].[GRADE] = [Grades].[VALUE_CODE]
	
--WHERE
--	[Grades].[VALUE_DESCRIPTION] = '09'
--	AND [COURSE].[DEPARTMENT] = 'Math'