




	
	

SELECT
	*
FROM
	(
	SELECT --TOP 100
		ST010.DST_NBR,
		ST010.SCH_NBR,
		ST010.GRDE,
		ST010.ID_NBR,
		ST010.SCH_YR,
		ST010.BEG_ENR_DT,
		ST010.END_ENR_DT,
		ST010.END_STAT
		
	FROM
		[011-SYNERGYDB.APS.EDU.ACTD].PR.DBTSIS.ST010 WITH(NOLOCK)
		
	WHERE
		DST_NBR = 1
		AND SCH_YR = '2014'
	) AS [SMAX_ENROLLMENTS]
	
	LEFT OUTER JOIN
	(
	SELECT
		[STUDENT].[SIS_NUMBER]
		,[ENROLLMENTS].[SCHOOL_CODE]
		,[ENROLLMENTS].[SCHOOL_NAME]
		,[ENROLLMENTS].[SCHOOL_YEAR]
		,[ENROLLMENTS].[ENTER_DATE]
		,[ENROLLMENTS].[LEAVE_DATE]
		,[ENROLLMENTS].[GRADE]
		,[ENROLLMENTS].[SUMMER_WITHDRAWL_CODE]
		,[StudentSchoolYear].[SUMMER_WITHDRAWL_DATE]
		,CONVERT(VARCHAR(4),DATEPART(YEAR,[ENROLLMENTS].[ENTER_DATE])) + RIGHT('00' + CONVERT(VARCHAR(2),MONTH([ENROLLMENTS].[ENTER_DATE])),2) + RIGHT('00' + CONVERT(VARCHAR(2),DATEPART(DD,[ENROLLMENTS].[ENTER_DATE])),2) AS [BEGIN_DATE]
		,CONVERT(VARCHAR(4),DATEPART(YEAR,[ENROLLMENTS].[LEAVE_DATE])) + RIGHT('00' + CONVERT(VARCHAR(2),MONTH([ENROLLMENTS].[LEAVE_DATE])),2) + RIGHT('00' + CONVERT(VARCHAR(2),DATEPART(DD,[ENROLLMENTS].[LEAVE_DATE])),2) AS [END_DATE]
		,CONVERT(VARCHAR(4),DATEPART(YEAR,[StudentSchoolYear].[SUMMER_WITHDRAWL_DATE])) + RIGHT('00' + CONVERT(VARCHAR(2),MONTH([StudentSchoolYear].[SUMMER_WITHDRAWL_DATE])),2) + RIGHT('00' + CONVERT(VARCHAR(2),DATEPART(DD,[StudentSchoolYear].[SUMMER_WITHDRAWL_DATE])),2) AS [SUMMER_DATE]
	FROM
		APS.StudentEnrollmentDetails AS [ENROLLMENTS]
		
		INNER JOIN
		APS.BasicStudent AS [STUDENT]
		ON
		[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		INNER JOIN
		rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
		ON
		[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
		
	) AS [SYN_ENROLLMENTS]
	ON
	[SMAX_ENROLLMENTS].[SCH_NBR] = [SYN_ENROLLMENTS].[SCHOOL_CODE] COLLATE Latin1_General_BIN
	AND [SMAX_ENROLLMENTS].[SCH_YR] = [SYN_ENROLLMENTS].[SCHOOL_YEAR] + 1 --COLLATE Latin1_General_BIN
	AND [SMAX_ENROLLMENTS].[ID_NBR] = [SYN_ENROLLMENTS].[SIS_NUMBER] COLLATE Latin1_General_BIN
	AND [SMAX_ENROLLMENTS].[GRDE] = [SYN_ENROLLMENTS].[GRADE] COLLATE Latin1_General_BIN
	AND ([SMAX_ENROLLMENTS].[BEG_ENR_DT] = [SYN_ENROLLMENTS].[BEGIN_DATE] OR [SMAX_ENROLLMENTS].[END_ENR_DT] = '20130000')
	--AND [SMAX_ENROLLMENTS].[END_ENR_DT] = [SYN_ENROLLMENTS].[SUMMER_DATE]
	
WHERE
	--[SMAX_ENROLLMENTS].[END_ENR_DT] NOT IN ('20130522','20130725')
	[SYN_ENROLLMENTS].[SIS_NUMBER] IS NULL
	--[SMAX_ENROLLMENTS].[END_ENR_DT] = '20120000'
	
ORDER BY
	[SMAX_ENROLLMENTS].[ID_NBR]
	,[SMAX_ENROLLMENTS].[SCH_NBR]