

;WITH
REQUEST_TRACKING AS
(
SELECT --TOP 100
	[NON_DST].[NAME]
	,[REQUEST_TRACKING].[RELEASE_DATE]
	,[REQUEST_TRACKING].[PERSON_RELEASED_TO]
	,[PERSON_TITLE].[VALUE_DESCRIPTION] AS [PERSON_TITLE]
	,[RELEASE_PURPOSE].[VALUE_DESCRIPTION] AS [RELEASE_PURPOSE]
	,[REQUEST_TRACKING].[STUDENT_GU]
FROM
	rev.EPC_STU_REQUEST_TRACKING AS [REQUEST_TRACKING]
	
	LEFT OUTER JOIN
	rev.EPC_SCH_NON_DST AS [NON_DST]
	ON
	[REQUEST_TRACKING].[SCHOOL_NON_DISTRICT_GU] = [NON_DST].[SCHOOL_NON_DISTRICT_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12.CourseHistoryInfo','PERSON_TITLE') AS [PERSON_TITLE]
	ON
	[REQUEST_TRACKING].[PERSON_TITLE] = [PERSON_TITLE].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12.CourseHistoryInfo','RELEASE_PURPOSE') AS [RELEASE_PURPOSE]
	ON
	[REQUEST_TRACKING].[RELEASE_PURPOSE] = [RELEASE_PURPOSE].[VALUE_CODE]
)



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[OLD_ENROLL].[GRADE]
	,[OLD_ENROLL].[SCHOOL_CODE]
	,[OLD_ENROLL].[SCHOOL_NAME]
	,[OLD_ENROLL].[ENTER_DATE]
	,[OLD_ENROLL].[LEAVE_DATE]
	,[OLD_ENROLL].[LEAVE_CODE]
	,[OLD_ENROLL].[LEAVE_DESCRIPTION]
	,[STU].[GRADUATION_DATE]
	,[STU].[GRADUATION_PLAN]
	,[STU].[GRADUATION_SEMESTER]
	,[STU].[GRADUATION_STATUS]
	,[OLD_ENROLL].[YEAR_END_STATUS]
	,[NEW_ENROLL].[SUMMER_WITHDRAWL_CODE]
	
	,[REQUEST_TRACKING].*
	
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf('05/22/2015') AS [OLD_ENROLL]
	
	LEFT OUTER JOIN
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = '2015'
		AND EXTENSION = 'R'
	) AS [NEW_ENROLL]
	ON
	[OLD_ENROLL].[STUDENT_GU] = [NEW_ENROLL].[STUDENT_GU]
	--AND [NEW_ENROLL].[SCHOOL_YEAR] = '2015'
	--AND [NEW_ENROLL].[EXTENSION] = 'R'
	AND [RN] = 1
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[OLD_ENROLL].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.EPC_STU AS [STU]
	ON
	[OLD_ENROLL].[STUDENT_GU] = [STU].[STUDENT_GU]
	
	INNER JOIN
	REQUEST_TRACKING AS [REQUEST_TRACKING]
	ON
	[OLD_ENROLL].[STUDENT_GU] = [REQUEST_TRACKING].[STUDENT_GU]
	
WHERE
	[NEW_ENROLL].[STUDENT_GU] IS NULL
	OR [NEW_ENROLL].[SUMMER_WITHDRAWL_CODE] IS NOT NULL