


SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENT].[GRADE]
	,[ENROLLMENT].[SCHOOL_CODE]
	,[ENROLLMENT].[SCHOOL_NAME]
	,[STUDENT].[CONTACT_LANGUAGE]
	,[STUDENT].[HOME_LANGUAGE]
	,[STUDENT].[ELL_STATUS]
	,[STUDENT].[RACE_1]
	,[STUDENT].[RACE_2]
	,[STUDENT].[RACE_3]
	,[STUDENT].[RACE_4]
	,[STUDENT].[RACE_5]
	,[STUDENT].[HISPANIC_INDICATOR]
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENT]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	([STUDENT].[RACE_1] = 'Native American'
	OR [STUDENT].[RACE_2] = 'Native American'
	OR [STUDENT].[RACE_3] = 'Native American'
	OR [STUDENT].[RACE_4] = 'Native American'
	OR [STUDENT].[RACE_5] = 'Native American')
	AND [STUDENT].[ELL_STATUS] = 'Y'