


SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME] 
	,[STUDENT].[LAST_NAME] 
	,[STUDENT].[MIDDLE_NAME] 
	,[ENROLLMENTS].[SCHOOL_NAME] 
	,[ENROLLMENTS].[SCHOOL_CODE] 
	,[COURSE].[COURSE_ID]
	,[COURSE].[COURSE_TITLE]
	,[SCHEDULE].[SECTION_ID]
	,[SCHEDULE].[TERM_CODE]
	,[SCHEDULE].[COURSE_ENTER_DATE] 
	,[SCHEDULE].[COURSE_LEAVE_DATE]
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	APS.BasicSchedule AS [SCHEDULE]
	ON
	[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [SCHEDULE].[STUDENT_SCHOOL_YEAR_GU]
	
	INNER JOIN
	rev.EPC_CRS AS [COURSE]
	ON
	[SCHEDULE].[COURSE_GU] = [COURSE].[COURSE_GU]
	
WHERE
	[COURSE].[COURSE_ID] IN ('644111','644112','61110C4','61110C3','611101','611102','61111C4','61111C3','611111','611112','611121','611122')
