





EXECUTE AS LOGIN='QueryFileUser'
GO

SELECT
	[FILE].*
	
	,[STUDENT].[SPED_STATUS]
	,[STUDENT].[PRIMARY_DISABILITY_CODE]
	,[STUDENT].[ELL_STATUS]
	,[STUDENT].[LUNCH_STATUS]
	,[STUDENT].[CONTACT_LANGUAGE]
	,[STUDENT].[HOME_LANGUAGE]
	
	,[REFUSAL].[WAIVER_ENTER_DATE]
	,[REFUSAL].[WAIVER_EXIT_DATE]
	,[REFUSAL].[WAIVER_TYPE]
	
	,[PROVIDER].[STATUS]
	
FROM
	OPENROWSET (
		'Microsoft.ACE.OLEDB.12.0', 
		'Text;Database=\\SynTempSSIS.aps.edu.actd\Files\TempQuery\;HDR=YES;', 
		'SELECT * from Active_Native_American_Students_030916.csv'
		) AS [FILE]
		
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[FILE].[Perm ID] = [STUDENT].[SIS_NUMBER]
	
	LEFT OUTER JOIN
	APS.LCEMostRecentALSRefusalAsOf (GETDATE()) AS [REFUSAL]
	ON
	[STUDENT].[STUDENT_GU] = [REFUSAL].[STUDENT_GU]
	
	LEFT OUTER JOIN
	APS.LCEStudentsAndProvidersAsOf(GETDATE()) AS [PROVIDER]
	ON
	[STUDENT].[SIS_NUMBER] = [PROVIDER].[SIS_NUMBER]

REVERT
GO