



SELECT
	[NF_ENROLLMENTS].[DST_NBR]
	,[NF_ENROLLMENTS].[ID_NBR]
	,[STUDENT].[FRST_NME]
	,[STUDENT].[LST_NME]
	,[PREV_Enrollments].[SCH_YR]
	,[PREV_Enrollments].[SCH_NBR]
	,[PREV_Enrollments].[GRDE]
	,[PREV_Enrollments].[BEG_ENR_DT]
	,[PREV_Enrollments].[END_ENR_DT]
	,[PREV_Enrollments].[END_STAT]
	,[NF_ENROLLMENTS].[SCH_YR]
	,[NF_ENROLLMENTS].[SCH_NBR]
	,[NF_ENROLLMENTS].[GRDE]
	,[NF_ENROLLMENTS].[BEG_ENR_DT]
	,[NF_ENROLLMENTS].[END_ENR_DT]
	,[NF_ENROLLMENTS].[END_STAT]
FROM
	(
	SELECT DISTINCT
		*
	FROM
		-- Get Primary Enrollments
		(
		SELECT DISTINCT
			_Id,
			DST_NBR,
			SCH_YR,
			SCH_NBR,
			GRDE,
			ID_NBR,
			BEG_ENR_DT,
			END_ENR_DT,
			END_STAT
		FROM 
			(
			SELECT
				ST010._Id,
				ST010.DST_NBR,
				ST010.SCH_NBR,
				ST010.GRDE,
				ST010.ID_NBR,
				ST010.SCH_YR,
				ST010.BEG_ENR_DT,
				ST010.END_ENR_DT,
				ST010.END_STAT,
				ROW_NUMBER() OVER (PARTITION BY ST010.DST_NBR, ST010.ID_NBR ORDER BY ST010.BEG_ENR_DT DESC) AS RN
			FROM
				[PR].[DBTSIS].[ST010] WITH(NOLOCK) 
			WHERE
				  SCH_YR = 2014
				  AND NONADA_SCH != 'X'
				  AND END_ENR_DT > BEG_ENR_DT

			) AS ST010CURR
		WHERE RN = 1
		) AS [Enrollments]		
		
	WHERE
		[Enrollments].[DST_NBR] = 1
		AND [Enrollments].[SCH_YR] = 2014
		
		--AND [Enrollments].[END_STAT] IN (''67'')
		AND [Enrollments].[SCH_NBR] = '549'
	) AS [NF_ENROLLMENTS]
	
	LEFT OUTER JOIN
	(
		SELECT DISTINCT
			_Id,
			DST_NBR,
			SCH_YR,
			SCH_NBR,
			GRDE,
			ID_NBR,
			BEG_ENR_DT,
			END_ENR_DT,
			END_STAT
		FROM 
			(
			SELECT
				ST010._Id,
				ST010.DST_NBR,
				ST010.SCH_NBR,
				ST010.GRDE,
				ST010.ID_NBR,
				ST010.SCH_YR,
				ST010.BEG_ENR_DT,
				ST010.END_ENR_DT,
				ST010.END_STAT,
				ROW_NUMBER() OVER (PARTITION BY ST010.DST_NBR, ST010.ID_NBR ORDER BY ST010.BEG_ENR_DT DESC) AS RN
			FROM
				[PR].[DBTSIS].[ST010] WITH(NOLOCK) 
			WHERE
				  SCH_YR = 2013
				  AND NONADA_SCH != 'X'
				  AND END_ENR_DT > BEG_ENR_DT

			) AS ST010CURR
		WHERE RN = 1
		) AS [PREV_Enrollments]
		ON
		[NF_ENROLLMENTS].[DST_NBR] = [PREV_Enrollments].[DST_NBR]
		AND [NF_ENROLLMENTS].[ID_NBR] = [PREV_Enrollments].[ID_NBR]
		--AND [NF_ENROLLMENTS].[SCH_NBR] != [PREV_Enrollments].[SCH_NBR]
		
		INNER JOIN
		APS.BasicStudent AS [STUDENT]
		ON
		[NF_ENROLLMENTS].[DST_NBR] = [STUDENT].[DST_NBR]
		AND [NF_ENROLLMENTS].[ID_NBR] = [STUDENT].[ID_NBR]
		
ORDER BY
	[NF_ENROLLMENTS].[ID_NBR]