

SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[SCHOOL_YEAR]
	,[ENROLLMENTS].[EXTENSION]
	,[ENROLLMENTS].[ENTER_DATE]
	,[ENROLLMENTS].[LEAVE_DATE]
	,[ENROLLMENTS].[LEAVE_CODE]
	,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	,[ENROLLMENTS].[SUMMER_WITHDRAWL_CODE]
	,[StudentSchoolYear].[SUMMER_WITHDRAWL_DATE]
	
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [ENROLLMENTS].[STUDENT_GU] ORDER BY [ENROLLMENTS].[ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails AS [ENROLLMENTS]
		
	WHERE
		[ENROLLMENTS].[SCHOOL_YEAR] >= '2014'
		--AND [ENROLLMENTS].[EXTENSION] = 'R'		
	) AS [ENROLLMENTS]
	
	INNER JOIN
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
	ON
	[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[ENROLLMENTS].[RN] = 1
	AND [ENROLLMENTS].[SCHOOL_YEAR] = '2014'
	AND [ENROLLMENTS].[SUMMER_WITHDRAWL_CODE] IN ('51','52')