




--SELECT
--	*
--FROM
--	rev.EPC_SCH_NON_DST
	
	
	




SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	--,[ENROLLMENTS].[SCHOOL_YEAR]
	--,[ENROLLMENTS].[SCHOOL_CODE]
	
	,[COURSE_HISTORY].[SCHOOL_YEAR]
	--,[COURSE_HISTORY].[TEACHER_NAME]
	
	,[NON-DISTRICT].[NAME] AS [Non_District_Name]
	
	,[COURSE_HISTORY].[TERM_CODE]
	,[COURSE_HISTORY].[COURSE_ID]
	,[COURSE_HISTORY].[COURSE_TITLE]
	,[COURSE].[DEPARTMENT]	
	
	--,'COURSE HISTORY/TRANSCRIPT' AS [TYPE]
	,[COURSE].[SUBJECT_AREA_1]
	,[COURSE].[SUBJECT_AREA_2]
	,[COURSE].[SUBJECT_AREA_3]
	,[COURSE].[SUBJECT_AREA_4]
	,[COURSE].[SUBJECT_AREA_5]
	,[COURSE_HISTORY].[MARK] AS [GRADE]
	
FROM
	APS.StudentEnrollmentDetails AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [COURSE_HISTORY].[STUDENT_GU]
	
	LEFT OUTER JOIN
	-- Get Course details
	rev.EPC_CRS AS [COURSE]
	ON
	[COURSE_HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
	
	INNER JOIN
	rev.EPC_SCH_NON_DST AS [NON-DISTRICT]
	ON
	[COURSE_HISTORY].[SCHOOL_NON_DISTRICT_GU] = [NON-DISTRICT].[SCHOOL_NON_DISTRICT_GU]
	
WHERE
	[NON-DISTRICT].[NAME] IN

(
'FAMILY SCHOOL',
'HAYES MS',
'MADISON MS',
'UNM SS',
'VALLEY HS SS',
'GARFIELD MS',
'HIGHLAND HS SS',
'TRUMAN MS',
'CNM SS',
'ECA',
'ALBUQUERQUE HS',
'HOOVER MS',
'ALBUQUERQUE EVENING HS',
'SANDIA HS  SS',
'CLEVELAND MS, NM',
'DEL NORTE HS SS',
'DESERT RIDGE MS',
'HIGHLAND HS',
'SCHOOL ON WHEELS SS',
'LB JOHNSON MS',
'VOLCANO VISTA HS',
'JUVENILE DET CENTER',
'HARRISION MS',
'FREEDOM HS',
'SANDIA HS',
'CIBOLA HS',
'EISENHOWER MS',
'TONY HILLERMAN MS',
'CNM',
'DEL NORTE HS',
'POLK MS',
'CONTINUATION SCHOOL',
'ELDORADO HS SS',
'FREEDOM HS SS',
'JEFFERSON MS',
'TAYLOR MS',
'WILSON MS',
'ERNIE PYLE MS',
'HOME SCHOOL',
'VAN BUREN MS',
'RIO GRANDE HS SS',
'ELDORADO HS',
'LA CUEVA HS',
'SCHOOL ON WHEELS',
'WASHINGTON MS',
'NEW FUTURES HS',
'ALBUQUERQUE HS SS',
'JIMMY CARTER MS',
'SANDIA HS SS',
'LA CUEVA HS SS',
'HOME HOSPITAL',
'JOHN ADAMS MS',
'KENNEDY MS',
'WEST MESA HS SS',
'MCKINLEY MS',
'ROOSEVELT MS',
'ABQ PUBLIC SCHOOLS',
'GRANT MS',
'JAMES MONROE MS',
'TAFT MS',
'MANZANO HS SS',
'MANZANO HS',
'WEST MESA HS',
'JACKSON MS',
'RIO GRANDE HS',
'UNM',
'ALBUQUERQE EVENING HS')
	
ORDER BY
	[STUDENT].[SIS_NUMBER]