

SELECT
	[SCHOOL_CODE]
	,[SCHOOL_NAME]
	--,COUNT([SIS_NUMBER]) AS [TOTAL ENROLLMENTS]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'Hispanic' THEN 1 ELSE 0 END) AS [Hispanic]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'African-American' THEN 1 ELSE 0 END) AS [African-American]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'Asian' THEN 1 ELSE 0 END) AS [Asian]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'White' THEN 1 ELSE 0 END) AS [White]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'Pacific Islander' THEN 1 ELSE 0 END) AS [Pacific Islander]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'Native American' THEN 1 ELSE 0 END) AS [Native American]
	,SUM(CASE WHEN [RESOLVED_RACE] = 'Two or More' THEN 1 ELSE 0 END) AS [Two or More]
FROM
	(
	SELECT
		[ENROLLMENT].[SCHOOL_CODE]
		,[ENROLLMENT].[SCHOOL_NAME]
		,[STUDENT].[SIS_NUMBER]
		,[STUDENT].[FIRST_NAME]
		,[STUDENT].[LAST_NAME]
		,[STUDENT].[MIDDLE_NAME]
		,[STUDENT].[GENDER]
		,[ENROLLMENT].[GRADE]
		,[STUDENT].[LUNCH_STATUS]
		,[STUDENT].[RESOLVED_RACE]

	FROM
		APS.PrimaryEnrollmentDetailsAsOf('08/13/2015') AS [ENROLLMENT]
		
		INNER JOIN
		APS.BasicStudentWithMoreInfo [STUDENT]
		ON
		[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
	WHERE
		[ENROLLMENT].[SCHOOL_CODE] IN ('550','570')
		--AND [STUDENT].[LUNCH_STATUS] IN ('F','R')
		--AND [STUDENT].[RESOLVED_RACE] LIKE '%AMERICAN%'
		
	) AS [STUDENTS]
	
GROUP BY
	[SCHOOL_CODE]
	,[SCHOOL_NAME]