

SELECT
	*
FROM
	
	(
	SELECT
		[STUDENT_SNAP].[STUDENT ID] AS [STARS EOY STATE ID]
		,[STUDENT_SNAP].[ALTERNATE STUDENT ID] AS [STARS EOY SMAX ID]
		,[STUDENT_SNAP].[FIRST NAME LONG] + ' ' + [STUDENT_SNAP].[LAST NAME LONG] AS [STARS EOY STUDENT NAME]
		,[STUDENT_SNAP].[CURRENT GRADE LEVEL] AS [STARS EOY CURRENT GRADE]
		,[STUDENT_SNAP].[LOCATION CODE] AS [STARS EOY SCHOOL NUMBER]
		,[STUDENT_SNAP].[ETHNIC CODE SHORT] AS [STARS EOY PRIMARY RACE]
		--,*
	FROM
		[046-WS02].[db_STARS_History].[dbo].[STUD_SNAPSHOT] AS [STUDENT_SNAP]
		
	WHERE
		[Period] = '2014-06-01'
	) AS [EOY_STARS]
	
	LEFT OUTER HASH JOIN
	(
	SELECT
		*
	FROM
		OPENQUERY([SYNERGYDBDC.APS.EDU.ACTD],'
		SELECT
			--[StudentSchoolYear].[STUDENT_GU]
			--,[StudentSchoolYear].[ORGANIZATION_YEAR_GU]
			--,[Organization].[ORGANIZATION_GU]
			
			[School].[SCHOOL_CODE] AS [SOR SCHOOL CODE]
			,[Organization].[ORGANIZATION_NAME] AS [SOR SCHOOL NAME]
			,[Grades].[VALUE_DESCRIPTION] AS [SOR GRADE]
			--,[StudentSchoolYear].[ENTER_DATE]
			--,[StudentSchoolYear].[LEAVE_DATE]
			--,[StudentSchoolYear].[EXCLUDE_ADA_ADM]
			--,[RevYear].[SCHOOL_YEAR]
			--,[RevYear].[EXTENSION]
			
			,[STUDENT].[SIS_NUMBER] AS [SOR SIS NUMBER]
			,[STUDENT].[STATE_STUDENT_NUMBER] AS [SOR STATE STUDENT NUMBER]
			,[STUDENT].[FIRST_NAME] + '' '' + [STUDENT].[LAST_NAME] AS [SOR STUDENT NAME]
				
			,[STUDENT].[HISPANIC_INDICATOR] AS [SOR HISANIC INDICATOR]
			,[ETHNIC_CODES].[RACE_1] AS [SOR RACE 1]
			,[ETHNIC_CODES].[RACE_2] AS [SOR RACE 2]
			,[ETHNIC_CODES].[RACE_3] AS [SOR RACE 3]
			,[ETHNIC_CODES].[RACE_4] AS [SOR RACE 4]
			,[ETHNIC_CODES].[RACE_5] AS [SOR RACE 5]
			,CASE WHEN [ETHNIC_CODES].[RACE_2] IS NOT NULL THEN ''Two or More'' ELSE [ETHNIC_CODES].[RACE_1] END AS [SOR RESOLVED RACE]
		FROM
			APS.PrimaryEnrollmentsAsOf(GETDATE()) AS [Enrollments]
			
			INNER JOIN
			rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
			ON
			[Enrollments].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
			
			INNER JOIN 
			rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
			ON 
			[StudentSchoolYear].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
			
			INNER JOIN 
			rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
			ON 
			[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
			
			INNER JOIN 
			rev.REV_YEAR AS [RevYear] -- Contains the School Year
			ON 
			[OrgYear].[YEAR_GU] = [RevYear].[YEAR_GU]
			
			LEFT OUTER JOIN
			APS.LookupTable(''K12'',''Grade'') AS [Grades]
			ON
			[StudentSchoolYear].[GRADE] = [Grades].[VALUE_CODE]
			
			INNER JOIN 
			rev.EPC_SCH AS [School] -- Contains the School Code / Number
			ON 
			[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
			
			INNER JOIN
			APS.BasicStudent AS [STUDENT]
			ON
			[Enrollments].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
			
			-- Get All Racial Codes
			LEFT JOIN
			(
			SELECT
				[ETHNIC_PIVOT].[PERSON_GU]
				,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable (''Revelation'', ''ETHNICITY'') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[1]) AS [RACE_1]
				,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable (''Revelation'', ''ETHNICITY'') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[2]) AS [RACE_2]
				,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable (''Revelation'', ''ETHNICITY'') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[3]) AS [RACE_3]
				,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable (''Revelation'', ''ETHNICITY'') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[4]) AS [RACE_4]
				,(SELECT [VALUE_DESCRIPTION] FROM APS.LookupTable (''Revelation'', ''ETHNICITY'') WHERE [VALUE_CODE] = [ETHNIC_PIVOT].[5]) AS [RACE_5]
			FROM
				(
				SELECT
					[SECONDARY_ETHNIC_CODES].[PERSON_GU]
					,[SECONDARY_ETHNIC_CODES].[ETHNIC_CODE]
					,ROW_NUMBER() OVER(PARTITION by [SECONDARY_ETHNIC_CODES].[PERSON_GU] order by [SECONDARY_ETHNIC_CODES].[ETHNIC_CODE]) [RN]
				FROM
					rev.REV_PERSON_SECONDRY_ETH_LST AS [SECONDARY_ETHNIC_CODES]
				) [PVT]
				PIVOT (MIN(ETHNIC_CODE) FOR [RN] IN ([1],[2],[3],[4],[5])) AS [ETHNIC_PIVOT]
			) AS [ETHNIC_CODES]
			ON
			[STUDENT].[STUDENT_GU] = [ETHNIC_CODES].[PERSON_GU]
		
		') AS [Enrollments]
	) AS [CURRENT_SOR_STUDENT]
	ON
	[EOY_STARS].[STARS EOY SMAX ID] = [CURRENT_SOR_STUDENT].[SOR SIS NUMBER]