



SELECT
	[STUDENT_RACE].[SCHOOL_CODE]
	,[STUDENT_RACE].[SCHOOL_NAME]
	,SUM(CASE WHEN [STUDENT_RACE].[RESOLVED_RACE] = 'White' THEN 1 ELSE 0 END) AS [WHITE]
	,SUM(CASE WHEN [STUDENT_RACE].[RESOLVED_RACE] = 'Hispanic' THEN 1 ELSE 0 END) AS [HISPANIC]
	,SUM(CASE WHEN [STUDENT_RACE].[RESOLVED_RACE] = 'Native American' THEN 1 ELSE 0 END) AS [NATIVE AMERICAN]
	,SUM(CASE WHEN [STUDENT_RACE].[RESOLVED_RACE] = 'African-American' THEN 1 ELSE 0 END) AS [AFRICAN-AMERICAN]
	,SUM(CASE WHEN [STUDENT_RACE].[RESOLVED_RACE] = 'Asian' THEN 1 ELSE 0 END) AS [ASIAN]
	,SUM(CASE WHEN [STUDENT_RACE].[RESOLVED_RACE] = 'Pacific Islander' THEN 1 ELSE 0 END) AS [PACIFIC ISLANDER]
	,SUM(CASE WHEN [STUDENT_RACE].[RESOLVED_RACE] = 'Two or More' THEN 1 ELSE 0 END) AS [TWO OR MORE]
	
	--*
	
FROM
	(
	SELECT
		[ENROLLMENT].[SCHOOL_CODE]
		,[ENROLLMENT].[SCHOOL_NAME]
		,[STUDENT].[SIS_NUMBER]
		,[STUDENT].[FIRST_NAME]
		,[STUDENT].[LAST_NAME]
		,[STUDENT].[MIDDLE_NAME]
		,[ENROLLMENT].[GRADE]
		,[STUDENT].[HISPANIC_INDICATOR]
		,[STUDENT].[RACE_1]
		,[STUDENT].[RACE_2]
		,[STUDENT].[RACE_3]
		,[STUDENT].[RACE_4]
		,[STUDENT].[RACE_5]
		,[STUDENT].[RESOLVED_RACE]
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT].[SIS_NUMBER] ORDER BY [ENROLLMENT].[ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails AS [ENROLLMENT]
		
		INNER JOIN
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		ON
		[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
	WHERE
		--[ENROLLMENT].[SCHOOL_CODE] BETWEEN '500' AND '599'
		[ENROLLMENT].[GRADE] BETWEEN '09' AND '12'
		AND [ENROLLMENT].[SCHOOL_YEAR] = '2014'
		AND [ENROLLMENT].[EXTENSION] = 'R'
	) AS [STUDENT_RACE]
	
WHERE
	[STUDENT_RACE].[RN] = 1
	
GROUP BY
	[STUDENT_RACE].[SCHOOL_CODE]
	,[STUDENT_RACE].[SCHOOL_NAME]
	
ORDER BY
	[STUDENT_RACE].[SCHOOL_NAME]