




SELECT DISTINCT
	[SCHEDULE].[COURSE_ID]
	,[SCHEDULE].[SECTION_ID]
	,[SCHEDULE].[COURSE_TITLE]
	,[SCHEDULE].[DEPARTMENT]
	,[TAGS].[TAG]
	,[SECTAG].[VALUE_DESCRIPTION] AS [TAG_DESCRIPTION]
	,[STAFF_PERSON].[FIRST_NAME]
	,[STAFF_PERSON].[LAST_NAME]
	
	,[School].[SCHOOL_CODE]
	,[Organization].[ORGANIZATION_NAME] AS [SCHOOL_NAME]
	
FROM
	APS.ScheduleAsOf(GETDATE()) AS [SCHEDULE]
	
	INNER JOIN
	rev.UD_SECTION_TAG AS [TAGS]
	ON
	[SCHEDULE].[SECTION_GU] = [TAGS].[SECTION_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12.ScheduleInfo','Section_Tag') AS [SECTAG]
	ON
	[TAGS].[TAG] = [SECTAG].[VALUE_CODE]
	
	INNER JOIN
	APS.SectionsAndAllStaffAssigned AS [ASTAFF]
	ON
	[SCHEDULE].[SECTION_GU] = [ASTAFF].[SECTION_GU]
	
	--INNER JOIN
	--rev.EPC_STAFF  AS [STAFF]
	--ON
	--[ASTAFF].[STAFF_GU] = [STAFF].[STAFF_GU]
	
	INNER JOIN
	rev.REV_PERSON AS [STAFF_PERSON]
	ON
	[ASTAFF].[STAFF_GU] = [STAFF_PERSON].[PERSON_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[SCHEDULE].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
	
WHERE
	[SCHEDULE].[ORGANIZATION_GU] = @School
	
ORDER BY
	[Organization].[ORGANIZATION_NAME]
	,[SCHEDULE].[COURSE_ID]
	,[SCHEDULE].[SECTION_ID]