






SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[GRADE] AS [CURRENT_GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE] AS [CURRENT_SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME] AS [CURRENT_SCHOOL_NAME]
	,[ENROLLMENTS].[ENTER_DATE] AS [CURRENT_ENTER_DATE]
	,[ENROLLMENTS].[LEAVE_DATE] AS [CURRENT_LEAVE_DATE]
	,[ENROLLMENTS].[LEAVE_CODE] AS [CURRENT__LEAVE_CODE]
	,[ENROLLMENTS].[LEAVE_DESCRIPTION] AS [CURRENT_LEAVE_DESCRIPTION]
	
	,[PREVIOUS_ENROLLMENTS].[GRADE] AS [PREVIOUS_GRADE]
	,[PREVIOUS_ENROLLMENTS].[SCHOOL_CODE] AS [PREVIOUS_SCHOOL_CODE]
	,[PREVIOUS_ENROLLMENTS].[SCHOOL_NAME] AS [PREVIOUS_SCHOOL_NAME]
	,[PREVIOUS_ENROLLMENTS].[SCHOOL_YEAR] AS [PREVIOUS_SCHOOL_YEAR]
	,[PREVIOUS_ENROLLMENTS].[ENTER_DATE] AS [PREVIOUS_ENTER_DATE]
	,[PREVIOUS_ENROLLMENTS].[LEAVE_DATE] AS [PREVIOUS_LEAVE_DATE]
	,[PREVIOUS_ENROLLMENTS].[LEAVE_CODE] AS [PREVIOUS_LEAVE_CODE]
	,[PREVIOUS_ENROLLMENTS].[LEAVE_DESCRIPTION] AS [PREVIOUS_LEAVE_DESCRIPTION]
	
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2015
		AND EXTENSION = 'R'
		--AND EXCLUDE_ADA_ADM IS NULL
		--AND SCHOOL_NAME LIKE '%NEX%'
		-- 592 597 596 591 549 516
		AND SCHOOL_CODE IN ('592','597','596','591','549','516')
		AND ENTER_DATE IS NOT NULL
		
	) AS [ENROLLMENTS]
	
	LEFT OUTER JOIN
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		EXCLUDE_ADA_ADM IS NULL
		AND SCHOOL_CODE NOT IN ('592','597','596','591','549','516')
		AND ENTER_DATE IS NOT NULL
		
	) AS [PREVIOUS_ENROLLMENTS]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [PREVIOUS_ENROLLMENTS].[STUDENT_GU]
	AND [PREVIOUS_ENROLLMENTS].[RN] = 1
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[ENROLLMENTS].[RN] = 1