



EXECUTE AS LOGIN='QueryFileUser'
GO


	SELECT DISTINCT
		[FILE].STUDENTID,
		[FILE].SY,
		CONVERT(VARCHAR(10),[FILE].Period,120) AS Period,
		[FILE].DISTRICTCODE,
		[FILE].FIRSTNAMELONG,
		[FILE].MIDDLEINITIAL,
		[FILE].LASTNAMELONG,
		CONVERT(VARCHAR(10),[FILE].BIRTHDATE,120) AS BIRTHDATE,
		[FILE].GENDERCODE,
		[FILE].ECONOMICSTATUSFOODPGMPARTICIPATION,
		[FILE].LEPELLELIGIBILITY,
		CONVERT(VARCHAR(10),[FILE].STATUSDATE,120) AS STATUSDATE,
		[FILE].STUDENTSTATUS,
		[FILE].DIPLOMATYPECODE,
		[FILE].[CURRENT DIPLOMA DESCRIPTION],
		[FILE].LOCATIONCODE,
		[FILE].CURRENTGRADELEVEL,
		[FILE].Field11,
		[FILE].ALTERNATESTUDENTID,
		[FILE].ETHNICCODESHORT,
		[FILE].HISPANICINDICATOR,
		[FILE].GRADUATE_DATE,
		[FILE].GRADELEVEL_1516,
		[FILE].ENTER_DATE_1516,
		[FILE].LEAVE_DATE_1516,
		[STUDENT].[SPED_STATUS],
		[ENROLLMENTS].[GRADE] AS [GRADELEVEL_1415]
		
	FROM
		
			OPENROWSET (
				'Microsoft.ACE.OLEDB.12.0', 
				'Text;Database=\\SynTempSSIS\Files\TempQuery\;',
				'SELECT * from SPRING_SUMMER_GRADUATES_W40DAYCHECK_004.csv' 
			)AS [FILE]
			
			--INNER JOIN
			--APS.BasicStudent AS [STUDENT]
			--ON
			--[FILE].[STUDENTID] = [STUDENT].[STATE_STUDENT_NUMBER]
			
			LEFT OUTER JOIN
			APS.BasicStudentWithMoreInfo AS [STUDENT]
			ON
			[FILE].[STUDENTID] = [STUDENT].[STATE_STUDENT_NUMBER]
			
			--LEFT OUTER JOIN
			--APS.LookupTable('K12','DIPLOMA_TYPE') AS [Diploma]
			--ON
			--[STUDENT].[DIPLOMA_TYPE] = [Diploma].[VALUE_CODE]
			
			LEFT OUTER JOIN
			(
			SELECT
				*
				,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
			FROM
				APS.StudentEnrollmentDetails
				
			WHERE
				SCHOOL_YEAR = 2014
				AND EXTENSION = 'R'
				AND EXCLUDE_ADA_ADM IS NULL
				
			) AS [ENROLLMENTS]
			--APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENTS]
			ON
			[STUDENT].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]
			AND [ENROLLMENTS].[RN] = 1
			
	--WHERE
	--	[FILE].STUDENTID = '102726387'	
			
		
	
REVERT
GO