


SELECT
	[STUDENT].[SIS_NUMBER]
	,[AT_RISK]
	--,[STUDENT].[STUDENT_GU]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[STUDENT].[ELL_STATUS]
	,[STUDENT].[SPED_STATUS]
	,[STUDENT].[LUNCH_STATUS]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[SCHOOL_YEAR]
	,[CUM_GPA].[HS Cum Flat]
	,[CUM_GPA].[HS Cum Weighted]
	,[CREDITS].[CREDITS]
		
FROM 
	(
	SELECT DISTINCT
		[STUDENT_CRS_ATT].[SIS_NUMBER]
		,[STUDENT_CRS_ATT].[STUDENT_GU]
		,[STUDENT_CRS_ATT].[FIRST_NAME]
		,[STUDENT_CRS_ATT].[LAST_NAME]
		,[STUDENT_CRS_ATT].[MIDDLE_NAME]
		--,[STUDENT_CRS_ATT].[ELL_STATUS]
		--,[STUDENT_CRS_ATT].[SPED_STATUS]
		--,[STUDENT_CRS_ATT].[LUNCH_STATUS]
		--,[STUDENT_CRS_ATT].[GRADE]
		--,[STUDENT_CRS_ATT].[SCHOOL_CODE]
		--,[STUDENT_CRS_ATT].[SCHOOL_NAME]
		--,[STUDENT_CRS_ATT].[SCHOOL_YEAR]
		--,[STUDENT_CRS_ATT].[COURSE_ID]
		--,[STUDENT_CRS_ATT].[COURSE_TITLE]
		--,[STUDENT_CRS_ATT].[DEPARTMENT]
		--,[STUDENT_CRS_ATT].[MARK]
		--,[STUDENT_CRS_ATT].[Full Days Unexcused]
		,CASE WHEN [AT_RISK] = 1 THEN 'Y' ELSE 'N' END AS [AT_RISK]
	FROM
		(
		SELECT
			[STUDENT_ATTENDANCE].*
			,[COURSE_HISTORY].[SCHOOL_YEAR] AS [CRS_HST_SCHOOL_YEAR]
			,[COURSE_HISTORY].[COURSE_ID]
			,[COURSE_HISTORY].[COURSE_TITLE]
			,[COURSE].[DEPARTMENT]
			,[COURSE_HISTORY].[MARK]
			,CASE WHEN [STUDENT_ATTENDANCE].[Full Days Unexcused] > 5 AND [COURSE_HISTORY].[MARK] = 'F' THEN '1' ELSE '0' END AS [AT_RISK]
			
		FROM
			(
			SELECT
				[STUDENT].[SIS_NUMBER]
				--,[STUDENT].[STUDENT_GU]
				,[STUDENT].[FIRST_NAME]
				,[STUDENT].[LAST_NAME]
				,[STUDENT].[MIDDLE_NAME]
				--,[STUDENT].[ELL_STATUS]
				--,[STUDENT].[SPED_STATUS]
				--,[STUDENT].[LUNCH_STATUS]
				,[ENROLLMENTS].[GRADE]
				,[ENROLLMENTS].[SCHOOL_CODE]
				,[ENROLLMENTS].[SCHOOL_NAME]
				,[ENROLLMENTS].[SCHOOL_YEAR]
				,CASE WHEN [PERIOD_ATTENDANCE].[Full Days Unexcused] IS NULL THEN 0 ELSE [PERIOD_ATTENDANCE].[Full Days Unexcused] END AS [Full Days Unexcused]
				,[ENROLLMENTS].[STUDENT_GU]	
				
			FROM
				(
				SELECT
					*
					,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
				FROM
					APS.StudentEnrollmentDetails
					
				WHERE
					SCHOOL_YEAR = 2014
					AND EXTENSION = 'R'
					AND GRADE = '08'
					
				) AS [ENROLLMENTS]
				
				INNER JOIN
				APS.BasicStudent AS [STUDENT]
				ON
				[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
				
				LEFT OUTER HASH JOIN
				APS.PeriodAttendanceAsOf('05/22/2015') AS [PERIOD_ATTENDANCE]
				ON
				[STUDENT].[SIS_NUMBER] = [PERIOD_ATTENDANCE].[SIS_NUMBER]
				--AND [ENROLLMENTS].[SCHOOL_CODE] = [PERIOD_ATTENDANCE].[SCHOOL_CODE]
			) AS [STUDENT_ATTENDANCE]
			
			LEFT OUTER JOIN
			rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
			ON
			[STUDENT_ATTENDANCE].[STUDENT_GU] = [COURSE_HISTORY].[STUDENT_GU]
			AND [STUDENT_ATTENDANCE].[SCHOOL_YEAR] = [COURSE_HISTORY].[SCHOOL_YEAR]
			
			LEFT OUTER JOIN
			rev.EPC_CRS AS [COURSE]
			ON
			[COURSE_HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
			
		WHERE
			[COURSE].[DEPARTMENT] IN ('Math','Eng','Sci','Soc')
			--AND [SIS_NUMBER] = '100506153'
			
			
		) AS [STUDENT_CRS_ATT]
		
	WHERE
		[STUDENT_CRS_ATT].[AT_RISK] = 1
		
	--ORDER BY
	--	[STUDENT_CRS_ATT].[AT_RISK] DESC
	--	,[STUDENT_CRS_ATT].[Full Days Unexcused] DESC
	--	,[STUDENT_CRS_ATT].[SIS_NUMBER]
	) AS [AT_RISK]
	
	LEFT OUTER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[AT_RISK].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENTS]
	ON
	[AT_RISK].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]
	
	--LEFT OUTER JOIN
	--(
	--SELECT DISTINCT
	--	[GPA].[STUDENT_SCHOOL_YEAR_GU]
		
	--	,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] = 'HSCF' THEN [GPA].[GPA] ELSE 0 END) AS [HS Cum Flat]
	--	,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] = 'HSCW' THEN [GPA].[GPA] ELSE 0 END) AS [HS Cum Weighted]
	--	,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] = 'MSCF' THEN [GPA].[GPA] ELSE 0 END) AS [MS Cum Flat]
		
	--FROM	
	--	rev.[EPC_STU_GPA] AS [GPA]  
			
	--	INNER JOIN
	--	rev.[EPC_SCH_YR_GPA_TYPE_RUN] [GPA_RUN]
	--	ON
	--	[GPA].[SCHOOL_YEAR_GPA_TYPE_RUN_GU] = [GPA_RUN].[SCHOOL_YEAR_GPA_TYPE_RUN_GU]
	--	AND [GPA_RUN].[SCHOOL_YEAR_GRD_PRD_GU] IS NULL
		
	--	INNER JOIN
	--	rev.[EPC_GPA_DEF_TYPE] [GPA_TYPE] 
	--	ON 
	--	[GPA_RUN].[GPA_DEF_TYPE_GU] = [GPA_TYPE].[GPA_DEF_TYPE_GU]
	--	AND (
	--		[GPA_TYPE].[GPA_TYPE_NAME] = 'HS Cum Flat' 
	--		OR
	--		[GPA_TYPE].[GPA_TYPE_NAME] = 'HS Cum Weighted' 
	--		--OR
	--		--[GPA_TYPE].[GPA_TYPE_NAME] = 'MS Cum Flat'
	--		)
				
	--	INNER JOIN 
	--	rev.[EPC_GPA_DEF] [GPA_DEF]  
	--	ON 
	--	[GPA_TYPE].[GPA_DEF_GU] = [GPA_DEF].[GPA_DEF_GU]
		
	--GROUP BY
	--	[GPA].[STUDENT_SCHOOL_YEAR_GU]
	--) AS [CUM_GPA]
	--ON
	--[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [CUM_GPA].[STUDENT_SCHOOL_YEAR_GU]
	
	LEFT OUTER JOIN
	APS.CumGPA AS [CUM_GPA]
	ON
	[STUDENT].[SIS_NUMBER] = [CUM_GPA].[SIS_NUMBER]
	
	LEFT OUTER JOIN
	(
	SELECT --DISTINCT
		[COURSE_HISTORY].[STUDENT_GU]
		,SUM([COURSE_HISTORY].[CREDIT_COMPLETED]) AS [CREDITS]
	FROM
		rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
		
	WHERE
		[COURSE_HISTORY].[SCHOOL_YEAR] = '2015'
		AND [COURSE_HISTORY].[GRADE] = 190
		AND (
			[COURSE_HISTORY].[REPEAT_TAG_GU] IS NULL
			OR
			[COURSE_HISTORY].[REPEAT_TAG_GU] = '92E81AF7-962A-4D66-ADF9-5FD3FD88FA7D'
			)
			
	GROUP BY
		[COURSE_HISTORY].[STUDENT_GU]
	) AS [CREDITS]
	ON
	[AT_RISK].[STUDENT_GU] = [CREDITS].[STUDENT_GU]
	
	
