



SELECT
	[STUDENT_LIST].*
	--,[HISTORY].[COURSE_ID]
	--,[HISTORY].[COURSE_TITLE]
	--,[HISTORY].[MARK]
	--,[HISTORY].[CREDIT_COMPLETED]
	--,[HISTORY].[SCHOOL_YEAR]
FROM
	(
	SELECT
		[STUDENT].[SIS_NUMBER]
		,[STUDENT].[FIRST_NAME]
		,[STUDENT].[MIDDLE_NAME]
		,[STUDENT].[LAST_NAME]
		,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
		,[School].[SCHOOL_CODE]
		,[Organization].[ORGANIZATION_NAME] AS [SCHOOL_NAME]
		,[HISTORY].[COURSE_ID]
		,[HISTORY].[COURSE_TITLE]
		,[HISTORY].[TERM_CODE]	
		,[HISTORY].[MARK]
		,[STUDENT].[STUDENT_GU]
		
	FROM
		rev.[EPC_STU_CRS_HIS] AS [HISTORY]
		
		INNER JOIN
		APS.BasicStudent AS [STUDENT]
		ON
		[HISTORY].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		INNER JOIN 
		rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
		ON 
		[HISTORY].[SCHOOL_IN_DISTRICT_GU] = [Organization].[ORGANIZATION_GU]
		
		INNER JOIN 
		rev.EPC_SCH AS [School] -- Contains the School Code / Number
		ON 
		[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','Grade') AS [Grades]
		ON
		[HISTORY].[GRADE] = [Grades].[VALUE_CODE]
		
	WHERE
		--[HISTORY].[SCHOOL_YEAR] = '2015'
		--AND 
		[HISTORY].[COURSE_ID] LIKE ('trdr1102')
	) [STUDENT_LIST]
	
	--LEFT OUTER JOIN
	--rev.[EPC_STU_CRS_HIS] AS [HISTORY]
	--ON
	--[STUDENT_LIST].[STUDENT_GU] = [HISTORY].[STUDENT_GU]
	--AND [HISTORY].[COURSE_ID] IN ('10043', '10043de', '10043B') 