


SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[GENDER]
	,[STUDENT].[RESOLVED_RACE]
	,[STUDENT].[SPED_STATUS]
	,[STUDENT].[PRIMARY_DISABILITY_CODE]
	,[STARS].[LEVEL OF INTEGRATION] AS [ELL_STATUS]
	,[STUDENT].[LUNCH_STATUS]
	,[STUDENT].[CLASS_OF]
	
	,[STU].[GRADUATION_DATE]
	,[STU].[GRADUATION_STATUS]
	,[GRAD_STATUS].[VALUE_DESCRIPTION] AS [GRAD_STAT_DEF]
	
	,[CUMGPA].[HS Cum Flat]
	,[CUMGPA].[HS Cum Weighted]
	
FROM
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	
	INNER JOIN
	rev.[EPC_STU] AS [STU]
	ON
	[STUDENT].[STUDENT_GU] = [STU].[STUDENT_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','GRADUATION_STATUS') AS [GRAD_STATUS]
	ON
	[STU].[GRADUATION_STATUS] = [GRAD_STATUS].[VALUE_CODE]
	
	-- ELL STATUS FROM STARS
	INNER HASH JOIN
	(
	SELECT
		[SY]
		,[Period]
		,[STUDENT ID]
		,[LEVEL OF INTEGRATION]
		
	FROM
		[RDAVM.APS.EDU.ACTD].[db_STARS_History].dbo.[STUD_SNAPSHOT]
		
	WHERE
		[Period] = '2014-12-15'
		AND [DISTRICT CODE] = '001'
	) AS [STARS]
	ON
	[STUDENT].[STATE_STUDENT_NUMBER] = [STARS].[STUDENT ID]
	
	LEFT OUTER JOIN
	APS.CumGPA AS [CUMGPA]
	ON
	[STUDENT].[SIS_NUMBER] = [CUMGPA].[SIS_NUMBER]
	
WHERE
	[STUDENT].[CLASS_OF] IN ('2014','2015')
	
	--AND [STUDENT].[SIS_NUMBER] = '980011520'