


EXECUTE AS LOGIN='QueryFileUser'
GO

	SELECT
		[FILE].*
		,[STUDENT].[STATE_STUDENT_NUMBER]
		,'' AS [ENROLLMENT 10/14/2015 >>>]
		,[PRIMARY].[SCHOOL_CODE]
		,[PRIMARY].[SCHOOL_NAME]
		,[PRIMARY].[GRADE]
		,[PRIMARY].[SCHOOL_YEAR]
		,[PRIMARY].[ENTER_DATE]
		,[PRIMARY].[LEAVE_DATE]
		,[PRIMARY].[LEAVE_CODE]
		,[PRIMARY].[LEAVE_DESCRIPTION]
		,[PRIMARY].[EXCLUDE_ADA_ADM]
		,[PRIMARY].[SUMMER_WITHDRAWL_CODE]
		,[PRIMARY].[YEAR_END_STATUS]
		,'' [MOST RECENT ENROLLMENT >>>]
		,[ENROLLMENT].[SCHOOL_CODE]
		,[ENROLLMENT].[SCHOOL_NAME]
		,[ENROLLMENT].[GRADE]
		,[ENROLLMENT].[SCHOOL_YEAR]
		,[ENROLLMENT].[ENTER_DATE]
		,[ENROLLMENT].[LEAVE_DATE]
		,[ENROLLMENT].[LEAVE_CODE]
		,[ENROLLMENT].[LEAVE_DESCRIPTION]
		,[ENROLLMENT].[EXCLUDE_ADA_ADM]
		,[ENROLLMENT].[SUMMER_WITHDRAWL_CODE]
		,[ENROLLMENT].[YEAR_END_STATUS]
		
	FROM
		OPENROWSET (
			'Microsoft.ACE.OLEDB.12.0', 
			'Text;Database=\\SynTempSSIS\Files\TempQuery\;',
			'SELECT * from Student_Roster_2015.csv' 
		)AS [FILE]
		
		INNER HASH JOIN
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		ON
		[FILE].[StudentID] = [STUDENT].[SIS_NUMBER]
		
		LEFT OUTER JOIN
		APS.PrimaryEnrollmentDetailsAsOf('10/14/2015') AS [PRIMARY]
		ON
		[STUDENT].[STUDENT_GU] = [PRIMARY].[STUDENT_GU]
		
		LEFT OUTER HASH JOIN
		(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY ENTER_DATE DESC) AS RN
		FROM
			APS.[StudentEnrollmentDetails]
		WHERE
			SCHOOL_YEAR <= '2015'
			AND EXTENSION = 'R'
		
		)  AS [ENROLLMENT]
		ON
		[STUDENT].[STUDENT_GU] = [ENROLLMENT].[STUDENT_GU]
		AND [ENROLLMENT].[RN] = 1


REVERT
GO