



--SELECT TOP 1000
--	*
--FROM
--	[046-WS02.APS.EDU.ACTD].[db_STARS_History].[dbo].[STUD_SNAPSHOT]


SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[GENDER]
	,[STUDENT].[RESOLVED_RACE]
	,[STUDENT].[CLASS_OF]
	,[ENROLLMENTS].[GRADE]
	,[STUDENT].[SPED_STATUS]
	,[STUDENT].[PRIMARY_DISABILITY_CODE]
	--,[STUDENT].[ELL_STATUS]
	,[STARS].[LEVEL OF INTEGRATION] AS [ELL_STATUS]
	
	,[ALGEBRA].[ALGEBRA_YEAR]
	
	,[COURSE_HISTORY].[COURSE_TITLE]
	,[COURSE_HISTORY].[COURSE_ID]
	,[COURSE_HISTORY].[TERM_CODE]
	,[COURSE].[DEPARTMENT]
	,[COURSE_HISTORY].[MARK]
	
	,[CUMGPA].[HS Cum Flat]
	,[CUMGPA].[HS Cum Weighted]
	
	
FROM
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	
	-- COUNT TOTAL 9TH GRADE ENROLLMENTS
	--LEFT OUTER JOIN
	--(
	--SELECT
	--	[STUDENT_GU]
	--	,COUNT(DISTINCT [SCHOOL_YEAR]) AS [TOTAL]
	--FROM
	--	APS.StudentEnrollmentDetails
	--WHERE
	--	SCHOOL_YEAR <= 2015
	--	AND EXTENSION = 'R'
	--	AND EXCLUDE_ADA_ADM IS NULL
	--	AND SUMMER_WITHDRAWL_CODE IS NULL
	--	AND GRADE = '09'
	--GROUP BY
	--	[STUDENT_GU]
	--) AS [ENROLLMENT_COUNT]
	--ON
	--[STUDENT].[STUDENT_GU] = [ENROLLMENT_COUNT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU], [SCHOOL_YEAR], [EXTENSION] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
	WHERE
		SCHOOL_YEAR = 2014
		AND EXTENSION = 'R'
		AND EXCLUDE_ADA_ADM IS NULL
		AND SUMMER_WITHDRAWL_CODE IS NULL
		AND LEAVE_DATE IS NULL
	) AS [ENROLLMENTS]
	ON
	[STUDENT].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]
	
	-- ELL STATUS FROM STARS
	INNER HASH JOIN
	(
	SELECT
		[SY]
		,[Period]
		,[STUDENT ID]
		,[LEVEL OF INTEGRATION]
		
	FROM
		[RDAVM.APS.EDU.ACTD].[db_STARS_History].dbo.[STUD_SNAPSHOT]
		
	WHERE
		[Period] = '2014-12-15'
		AND [DISTRICT CODE] = '001'
	) AS [STARS]
	ON
	[STUDENT].[STATE_STUDENT_NUMBER] = [STARS].[STUDENT ID]
	
	LEFT OUTER JOIN
	rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
	ON
	[STUDENT].[STUDENT_GU] = [COURSE_HISTORY].[STUDENT_GU]
	AND [COURSE_HISTORY].[SCHOOL_YEAR] = '2014'
	
	LEFT OUTER JOIN
	rev.EPC_CRS AS [COURSE]
	ON
	[COURSE_HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
	
	-- GET FIRST YEAR STUDENT TOOK ALGEBRA
	LEFT OUTER HASH JOIN
	(
	SELECT
		[STUDENT_GU]
		,MIN([ALGEBRA_YEAR]) AS [ALGEBRA_YEAR]
	FROM
		(
		SELECT
			[COURSE_HISTORY].[STUDENT_GU]
			,[SCHOOL_YEAR] AS [ALGEBRA_YEAR]
			,SUM([COURSE_HISTORY].[CREDIT_COMPLETED]) AS [CREDIT_COMPLETED]
		FROM
			rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]

		WHERE
			--[COURSE_HISTORY].[CREDIT_COMPLETED] ! = 0
			--AND 
			[COURSE_HISTORY].[COURSE_ID] IN 
		(
		'330471',
		'330472',
		'330801',
		'330802',
		'330811',
		'330812',
		'3304000',
		'060C41',
		'060C42',
		'061C1',
		'061C11',
		'061C12',
		'061C41',
		'061C42',
		'061C51',
		'061C52',
		'062C11',
		'062C12',
		'3110B1',
		'3110B',
		'3110D',
		'3110B2',
		'3110D1',
		'31100',
		'3110D2',
		'330401de1',
		'330401de2',
		'33040C',
		'33040C1',
		'33040C2',
		'33040DE1',
		'33040DE2',
		'33040DI1',
		'33040DI2',
		'3304A1',
		'3304A2',
		'MATH322',
		'330401',
		'330402',
		'330403',
		'311001',
		'311002',
		'36040DE1',
		'36040DE2',
		'3604A1',
		'3604A2',
		'360350',
		'360351',
		'360352',
		'3603500',
		'060C71',
		'060C72',
		'061C71',
		'061C72',
		'062D11',
		'062D12',
		'36035DE1',
		'36035DE2',
		'360801',
		'360802',
		'MATH421',
		'MATH2810',
		'MATH312')

		GROUP BY
			[COURSE_HISTORY].[STUDENT_GU]
			,[SCHOOL_YEAR]
		) AS [CREDITS]
		
	WHERE
		[CREDIT_COMPLETED] = 1
		
	GROUP BY
		[STUDENT_GU]
	) AS [ALGEBRA]
	ON
	[STUDENT].[STUDENT_GU] = [ALGEBRA].[STUDENT_GU]
	
	LEFT OUTER JOIN
	APS.CumGPA AS [CUMGPA]
	ON
	[STUDENT].[SIS_NUMBER] = [CUMGPA].[SIS_NUMBER]
	
WHERE
	[STUDENT].[CLASS_OF] = '2018'
	AND [ENROLLMENTS].[GRADE] = '09'
	--AND [ENROLLMENTS].[YEAR_END_STATUS] != 'R'
	AND [COURSE].[DEPARTMENT] IN ('Math','Eng','Sci','Soc')
	
	--AND [STUDENT].[SIS_NUMBER] = '143559'