




SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	--,[ENROLLMENTS].[ORGANIZATION_GU]
	--,[ENROLLMENTS].[YEAR_GU]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[ENTER_DATE],101) AS [ENTER_DATE]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[LEAVE_DATE],101) AS [LEAVE_DATE]
	,[ENROLLMENTS].[LEAVE_CODE]
	,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	,[ENROLLMENTS].[YEAR_END_STATUS]
	,[ENROLLMENTS].[SUMMER_WITHDRAWL_CODE]
	,[ENROLL].[PREVIOUS_YEAR_END_STATUS]
	
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2015
		AND EXTENSION = 'R'
		--AND EXCLUDE_ADA_ADM IS NULL
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.EPC_STU_ENROLL AS [ENROLL]
	ON
	[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [ENROLL].[STUDENT_SCHOOL_YEAR_GU]
	
WHERE
	--[ENROLLMENTS].[YEAR_END_STATUS] IS NOT NULL
	[ENROLL].[PREVIOUS_YEAR_END_STATUS] IS NULL
	AND [ENROLLMENTS].[SUMMER_WITHDRAWL_CODE] IS NOT NULL