




SELECT
	RIGHT(LEFT([COURSE].[STATE_COURSE_CODE],5),1) AS [FIFTH_DIGIT]
	,[COURSE].[STATE_COURSE_CODE]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[SCHEDULE].[COURSE_ID]
	--,[COURSE].[STATE_COURSE_CODE]
	,[SCHEDULE].[COURSE_TITLE]
	,[SCHEDULE].[SECTION_ID]
	,[SCHEDULE].[COURSE_ENTER_DATE]
	,[SCHEDULE].[COURSE_LEAVE_DATE]
FROM
	APS.ScheduleAsOf(GETDATE()) AS [SCHEDULE]
	
	INNER JOIN
	rev.EPC_CRS AS [COURSE]
	ON
	[SCHEDULE].[COURSE_GU] = [COURSE].[COURSE_GU]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[SCHEDULE].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENTS]
	ON
	[SCHEDULE].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]

WHERE
	--RIGHT(LEFT([COURSE].[STATE_COURSE_CODE],5),1) = '2'
	[COURSE].[STATE_COURSE_CODE] = '28022000'