





SELECT --TOP 100
	COUNT([STUDENT ID]) AS [COUNT]
	,[CURRENT GRADE LEVEL]
	--*
FROM
	[046-WS02.APS.EDU.ACTD].[db_STARS_History].[dbo].[STUD_SNAPSHOT]
	
WHERE
	[PERIOD] = '2015-03-01'
	AND [CURRENT GRADE LEVEL] BETWEEN '03' AND '11'
	AND [DISTRICT CODE] = '001'
	
GROUP BY
	[CURRENT GRADE LEVEL]