



SELECT
	[HISTORY].*
FROM
	APS.PrimaryEnrollmentDetailsAsOf('08/13/2015') AS [ENROLLMENT]
	
	INNER JOIN
	rev.[EPC_STU_CRS_HIS] AS [HISTORY]
	ON
	[ENROLLMENT].[STUDENT_GU] = [HISTORY].[STUDENT_GU]
	
	INNER JOIN
	rev.[EPC_SCH_NON_DST] AS [NON_DIST]
	ON
	[HISTORY].[SCHOOL_NON_DISTRICT_GU] = [NON_DIST].[SCHOOL_NON_DISTRICT_GU]
	
WHERE
	[ENROLLMENT].[GRADE] = '09'
	AND [NON_DIST].[NAME] LIKE 'COTTONWOOD CLASSICAL, NM'