




	
DECLARE @SchoolGu VARCHAR = '%'
DECLARE @Grade AS VARCHAR(2) = '%'
	

SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,CONVERT(VARCHAR(10),[STUDENT].[BIRTH_DATE],101) AS [BIRTH_DATE]
	,CASE
	WHEN dateadd(year, datediff (year, [STUDENT].[BIRTH_DATE], GETDATE()),[STUDENT].[BIRTH_DATE]) > GETDATE()
	THEN datediff (year, [STUDENT].[BIRTH_DATE], GETDATE()) - 1
	ELSE datediff (year, [STUDENT].[BIRTH_DATE], GETDATE()) END AS [AGE]
	,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
	,[Grades].[LIST_ORDER]
	,[School].[SCHOOL_CODE]
	,[Organization].[ORGANIZATION_NAME] AS [SCHOOL_NAME]
	,[RevYear].[SCHOOL_YEAR]
	,'MMR' AS [VACCINATION_NAME]
	,[VACCINATIONS].[EXEMPT]
	,[VACCINATIONS].[EXEMPT REASON]
	,[VACCINATIONS].[EXEMPT_GRANTED]
	,[VACCINATIONS].[DOSAGE_1]
	,[VACCINATIONS].[DOSAGE_2]
	,[VACCINATIONS].[DOSAGE_3]
	
	,[VACCINATIONS].[VACCINATION_NAME] AS [RULE_1_TYPE]
	,[VACCINATIONS].[EXEMPT] AS [RULE_2_EXEMPT]
	,DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_1]) AS [RULE_3_FIRST_DOSAGE_MONTHS]
	,DATEDIFF(WEEK,[VACCINATIONS].[DOSAGE_1],[VACCINATIONS].[DOSAGE_2]) AS [RULE_4_SECOND_DOSAGE_WEEKS]
	,DATEDIFF(YEAR,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_1]) AS [RULE_5_FIRST_DOSAGE_AGE]
	,DATEDIFF(YEAR,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_2]) AS [RULE_6_SECOND_DOSAGE_AGE]
	
	,DATEDIFF(WEEK,[VACCINATIONS].[DOSAGE_1],GETDATE()) AS [WORKING]
	
	,DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_1],DATEADD(YEAR,1,[STUDENT].[BIRTH_DATE]))
	
	,DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_2],[VACCINATIONS].[DOSAGE_3]) AS [THIRD_DOSAGE_DAYS]
	
	,CASE
		  WHEN [VACCINATIONS].[EXEMPT] IS NOT NULL THEN 'EXEMPT'
		  		  
		   -- IN PROGRESS 
		  WHEN DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_1],GETDATE()) <= 28 THEN 'IN PROGRESS'
		  
		  -- 1ST DOSAGE BAD BUT 2ND AND 3RD ARE GOOD
		  WHEN (DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_1]) < 12	-- FIRST DOSAGE UNDER 12 MONTHS
		  AND DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_1],DATEADD(YEAR,1,[STUDENT].[BIRTH_DATE])) > 4) -- 4 DAY GRACE PERIOD
		  AND DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_2]) >= 12		-- SECOND DOSAGE AFTER 11 MONTHS
		  AND DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_2],[VACCINATIONS].[DOSAGE_3]) >= 24	-- THIRD DOSAGE NO SOONER THAN 4 WEEKS
		  THEN 'COMPLIANT'
		  
		  -- SECOND DOSAGE TAKEN WITHIN 4 WEEKS OF FIRST DOSAGE
		  WHEN DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_1],[VACCINATIONS].[DOSAGE_2]) < 24	-- SECOND DOSAGE WITHIN 4 WEEKS
		  AND DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_2]) >= 12	-- SECOND DOSAGE AFTER 11 MONTHS
		  AND DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_2],[VACCINATIONS].[DOSAGE_3]) >= 24	-- THIRD DOSAGE NO SOONER THAN 4 WEEKS
		  THEN 'COMPLIANT'
		  
		  WHEN (DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_1]) < 12	-- FIRST DOSAGE UNDER 12 MONTHS
		  AND DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_1],DATEADD(YEAR,1,[STUDENT].[BIRTH_DATE])) > 4) -- 4 DAY GRACE PERIOD
		  OR DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_1],[VACCINATIONS].[DOSAGE_2]) < 24		-- SECOND DOSAGE WITHIN 4 WEEKS
		  --OR (DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_1]) / 12) >= 4		-- FIRST DOSAGE AFTER AGE 4
		  OR [VACCINATIONS].[DOSAGE_1] IS NULL											-- NO FIRST DOSAGE
		  OR ((DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],GETDATE()) / 12) >= 4 AND [VACCINATIONS].[DOSAGE_2] IS NULL) -- NO SECOND DOSAGE AFTER AGE 4
		  THEN 'NOT COMPLIANT'
		   
		  -- STUDENTS UNDER AGE 4 AND ONLY ONE DOSAGE
		  WHEN (DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],GETDATE()) / 12) < 4				-- AGE LESS THAN 4
		  AND DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_1]) >= 12	-- FIRST DOSAGE AFTER 12 MONTHS
		  AND [VACCINATIONS].[DOSAGE_2] IS NULL											-- SECOND DOSAGE
		  THEN 'COMPLIANT'
		  
		  -- STUDENTS UNDER AGE 4 WITH TWO DOSAGES
		  WHEN (DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],GETDATE()) / 12) < 4				-- AGE LESS THAN 4
		  AND DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_1]) >= 12	-- FIRST DOSAGE AFTER 12 MONTHS
		  AND DATEDIFF(WEEK,[VACCINATIONS].[DOSAGE_1],[VACCINATIONS].[DOSAGE_2]) >= 4	-- SECOND DOSAGE NO SOONER THAN 4 WEEKS
		  THEN 'COMPLIANT'
		  
		  -- STUDENTS AGE 4 AND OLDER
		  WHEN (DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],GETDATE()) / 12) >= 4				-- AGE GREATER THAN OR EQUAL TO 4 
		  AND (DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_1]) >= 12	-- FIRST DOSAGE AFTER 12 MONTHS
		  OR DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_1],DATEADD(YEAR,1,[STUDENT].[BIRTH_DATE])) <= 4) -- 4 DAY GRACE PERIOD
		  AND DATEDIFF(DAY,[VACCINATIONS].[DOSAGE_1],[VACCINATIONS].[DOSAGE_2]) >= 24	-- SECOND DOSAGE NO SOONER THAN 4 WEEKS
		  --AND (DATEDIFF(MONTH,[STUDENT].[BIRTH_DATE],[VACCINATIONS].[DOSAGE_1]) / 12) < 4		-- FIRST DOSAGE BEFORE AGE 4
		  THEN 'COMPLIANT'
		   
		  END AS [COMPLIANCE_THIS_MONTH]		
	
FROM
	APS.PrimaryEnrollmentsAsOf(GETDATE()) AS [Enrollments]
	
	INNER JOIN
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
	ON
	[Enrollments].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
	ON 
	[StudentSchoolYear].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[OrgYear].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','Grade') AS [Grades]
	ON
	[StudentSchoolYear].[GRADE] = [Grades].[VALUE_CODE]
	
	INNER JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
	--------------------------------------------------------------
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[Enrollments].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	---------------------------------------------------------------
	LEFT OUTER JOIN
	APS.StudentImmunizations AS [VACCINATIONS]
	ON
	[Enrollments].[STUDENT_GU] = [VACCINATIONS].[STUDENT_GU]
	AND [VACCINATIONS].[VACCINATION_NAME] = 'MMR'	
	
WHERE
	--[Organization].[ORGANIZATION_GU] LIKE @SchoolGu
	--AND [Grades].[VALUE_DESCRIPTION] LIKE @Grade
	--[STUDENT].[SIS_NUMBER] IN ('970110805')
	--OR
	--[STUDENT].[STATE_STUDENT_NUMBER] IN ('102735586','97007228','104306162')
	
	[VACCINATIONS].[DOSAGE_3] IS NOT NULL

ORDER BY
	[Organization].[ORGANIZATION_NAME]
	,[Grades].[VALUE_DESCRIPTION]