



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[Organization].[ORGANIZATION_NAME] AS [SCHOOL_NAME]
	,[HISTORY].[COURSE_TITLE]
	,[HISTORY].[COURSE_ID]
	,[HISTORY].[SCHOOL_YEAR]
	,[HISTORY].[CALENDAR_YEAR]
	,[HISTORY].[CALENDAR_MONTH]
	,[Grades].[VALUE_DESCRIPTION] AS [GRADE_LEVEL]
	,[HISTORY].[MARK]
	,[HISTORY].[COURSE_HISTORY_TYPE]
	,[HISTORY].[CREDIT_COMPLETED]
FROM
	rev.[EPC_STU_CRS_HIS] AS [HISTORY]
	
	INNER JOIN
	rev.EPC_CRS AS [COURSE]
	ON
	[HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[HISTORY].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[HISTORY].[SCHOOL_IN_DISTRICT_GU] = [Organization].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','Grade') AS [Grades]
	ON
	[HISTORY].[GRADE] = [Grades].[VALUE_CODE]
	
WHERE
	[HISTORY].[SCHOOL_YEAR] = '2015'
	
	AND
	(
	[COURSE].[DISTANCE_LEARNING]  = 'Y'
	OR [COURSE].[ONLINE_COURSE] = 'Y'
	)