

DECLARE @AsOfDate DATETIME = GETDATE()

SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,CONVERT(VARCHAR(10),[STUDENT].[BIRTH_DATE],101) AS [BIRTH_DATE]
	,[STUDENT].[GENDER]
	,[ENROLLMENT].[GRADE]
	,[ENROLLMENT].[SCHOOL_CODE]
	,[ENROLLMENT].[SCHOOL_NAME]
	,[HLS].[DATE_ASSIGNED]
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf(@AsOfDate) AS [ENROLLMENT]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.UD_HLS_HISTORY AS [HLS]
	ON
	[ENROLLMENT].[STUDENT_GU] = [HLS].[STUDENT_GU]
	
WHERE
	[HLS].[UDHLS_HISTORY_GU] IS NULL