


SELECT TOP 100
	R0.[LAST_NAME]
	,R0.[FIRST_NAME]
	,R1.[STUDENT_GU]
	,R0.[MIDDLE_NAME]
	,R2.[SIS_NUMBER]
	,R3.[IEP_GU]
	,R3.[LEVEL_INTEGRATION]
	,R3.[LEVEL_INTEGRATION_EC]
	,R5.[ORGANIZATION_YEAR_GU]
	
	,R4.*
FROM 
	rev.[EP_STU] R1 
	
	LEFT OUTER JOIN 
	rev.[EPC_STU_SCH_YR] R5 
	ON 
	(R1.STUDENT_GU=R5.STUDENT_GU) 
	
	INNER JOIN 
	rev.[EPC_STU] R2 
	ON 
	(R1.STUDENT_GU=R2.STUDENT_GU) 
	
	LEFT OUTER JOIN 
	rev.[REV_PERSON] R0 
	ON 
	(R1.STUDENT_GU=R0.PERSON_GU) 
	
	LEFT OUTER JOIN 
	rev.[EP_STUDENT_IEP] R4 
	ON (R1.STUDENT_GU=R4.STUDENT_GU) 
	
	LEFT OUTER JOIN 
	rev.[EP_AZ_IEP_LRE] R3 
	ON 
	(R4.IEP_GU=R3.IEP_GU)
	
	
SELECT TOP 100
	*
FROM
	rev.EPC_NM_STU_SPED_RPT 