


SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[COURSE_HISTORY].[COURSE_ID]
	,[COURSE_HISTORY].[COURSE_TITLE]
	,[COURSE_HISTORY].[SCHOOL_YEAR]
	,[COURSE_HISTORY].[TERM_CODE]
	,[COURSE_HISTORY].[TEACHER_NAME]
	,[COURSE_HISTORY].[MARK]
	,[COURSE_HISTORY].[CREDIT_COMPLETED]
	,[Organization].[ORGANIZATION_NAME] AS [SCHOOL_NAME]
	
FROM
	rev.EPC_STU_CRS_HIS AS [COURSE_HISTORY]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[COURSE_HISTORY].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[COURSE_HISTORY].[SCHOOL_IN_DISTRICT_GU] = [Organization].[ORGANIZATION_GU]
	
WHERE
	[COURSE_HISTORY].[COURSE_ID] IN ('STAT145','HIST226','10043','10043DE','10043B')


--SELECT --TOP 100
--	*
--FROM
--	--[DBTSIS].[TN020_V] AS [Transcripts]
--	[DBTSIS].[SC031_V] AS [CourseMaster]

--WHERE
--	[CourseMaster].[COURSE] LIKE '%MATH%'
	
--ORDER BY
--	[CourseMaster].[COURSE]