



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ALL_ENROLLMENTS].[GRADE]
	,[ALL_ENROLLMENTS].[SCHOOL_CODE]
	,[ALL_ENROLLMENTS].[SCHOOL_NAME]
	--,[ALL_ENROLLMENTS].[ORGANIZATION_GU]
	--,[ALL_ENROLLMENTS].[YEAR_GU]
	,CONVERT(VARCHAR(10),[ALL_ENROLLMENTS].[ENTER_DATE],101) AS [ENTER_DATE]
	,CONVERT(VARCHAR(10),[ALL_ENROLLMENTS].[LEAVE_DATE],101) AS [LEAVE_DATE]
	,[ALL_ENROLLMENTS].[LEAVE_CODE]
	,[ALL_ENROLLMENTS].[LEAVE_DESCRIPTION]
	,[ALL_ENROLLMENTS].[YEAR_END_STATUS]
	,[ALL_ENROLLMENTS].[SUMMER_WITHDRAWL_CODE]
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENTS]
	
	INNER JOIN
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR <= 2015
	--	AND EXTENSION = 'R'
		--AND EXCLUDE_ADA_ADM IS NULL
	) AS [ALL_ENROLLMENTS]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [ALL_ENROLLMENTS].[STUDENT_GU]
	--AND [ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] != [OLD_ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[ENROLLMENTS].[SCHOOL_CODE] = '255'
	
ORDER BY
	[STUDENT].[SIS_NUMBER]