

DECLARE @School UNIQUEIDENTIFIER = '5A7A23CB-3B89-4A45-8F78-A08E391B7EEF'
--DECLARE @Student UNIQUEIDENTIFIER = '%'
DECLARE @Student INT = 111216

SELECT DISTINCT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[ORGANIZATION_GU]
	,[ENROLLMENTS].[YEAR_GU]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[ENTER_DATE],101) AS [ENTER_DATE]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[LEAVE_DATE],101) AS [LEAVE_DATE]
	,[ENROLLMENTS].[LEAVE_CODE]
	,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	
	,'TRUANCY' AS [LOG_TYPE]
	,1 AS [LOG_ORDER]
	
	,[UD_STU].[COMMUNITY_SUPPORT]
	
	,[TRUANT_STUDENT].[SCHOOL_YEAR]
	,CASE WHEN [TRUANT_STUDENT].[TWO_DAY_TRUANT] = 1 THEN 'Y' ELSE 'N' END AS [TWO_DAY_TRUANT]
	,CASE WHEN [TRUANT_STUDENT].[FIVE_DAY_TRUANT] = 1 THEN 'Y' ELSE 'N' END AS [FIVE_DAY_TRUANT]
	,CASE WHEN [TRUANT_STUDENT].[TEN_DAY_TRUANT] = 1 THEN 'Y' ELSE 'N' END AS [TEN_DAY_TRUANT]
	
	,CONVERT(VARCHAR(10),[TRUANCY_LOG].[ADD_DATE_TIME_STAMP],101) AS [CONTACT_DATE]
	,NULL AS [CONTACT_TIME]
	,[TRUANCY_LOG].[CONTACT_TYPE]
	,[CONTACT_TYPE].[VALUE_DESCRIPTION] AS [CONTACT_TYPE_DESC]
	,[TRUANCY_LOG].[CONTACT_WITH] AS [PERSON_CONTACTED]
	,[CONTACT_WITH].[VALUE_DESCRIPTION] AS [CONTACT_WITH_DESC]
	,CONVERT(VARCHAR,[TRUANCY_LOG].[NOTES]) AS [NOTES_COMMENTS]
	,[TRUANCY_LOG].[OUTCOME_1]
	,[OUTCOME_1].[VALUE_DESCRIPTION] AS [OUTCOME_1_DESC]
	,[TRUANCY_LOG].[OUTCOME_2]
	,[OUTCOME_2].[VALUE_DESCRIPTION] AS [OUTCOME_2_DESC]
	,[TRUANCY_LOG].[TRUANCY_STAFF] AS [STAFF_CODE]
	,[TRUANCY_STAFF].[VALUE_DESCRIPTION] AS [CONTACT_BY]
	,[TRUANCY_LOG].[TRUANCY_STAFF_TITLE] AS [STAFF_TITLE]
	,[TRUANCY_STAFF_TITLE].[VALUE_DESCRIPTION] AS [STAFF_TITLE_DESC]
	
FROM
	--APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENTS]
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2015
		AND EXTENSION = 'R'
		--AND EXCLUDE_ADA_ADM IS NULL
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.UD_STU AS [UD_STU]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [UD_STU].[STUDENT_GU]
	
	LEFT OUTER JOIN
	(
		SELECT
		[TRUANT_STUDENT].[STUDENT_GU]
		,[TRUANT_STUDENT].[SCHOOL_YEAR]
		,SUM(CASE WHEN [TRUANT_STUDENT].[TWO_DAY_TRUANT] = 'Y' THEN 1 ELSE 0 END) AS [TWO_DAY_TRUANT]
		,SUM(CASE WHEN [TRUANT_STUDENT].[FIVE_DAY_TRUANT] = 'Y' THEN 1 ELSE 0 END) AS [FIVE_DAY_TRUANT]
		,SUM(CASE WHEN [TRUANT_STUDENT].[TEN_DAY_TRUANT] = 'Y' THEN 1 ELSE 0 END) AS [TEN_DAY_TRUANT]
	FROM
		rev.UD_TRUANT_STUDENT AS [TRUANT_STUDENT]
		
	GROUP BY
		[TRUANT_STUDENT].[STUDENT_GU]
		,[TRUANT_STUDENT].[SCHOOL_YEAR]
	) AS [TRUANT_STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [TRUANT_STUDENT].[STUDENT_GU]
	
	
	LEFT OUTER JOIN
	rev.UD_TRUANCY_LOG AS [TRUANCY_LOG]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [TRUANCY_LOG].[STUDENT_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('Revelation.UD.Truancy','OUTCOME_1') AS [OUTCOME_1]
	ON
	[TRUANCY_LOG].[OUTCOME_1] = [OUTCOME_1].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LookupTable('Revelation.UD.Truancy','OUTCOME_1') AS [OUTCOME_2]
	ON
	[TRUANCY_LOG].[OUTCOME_2] = [OUTCOME_2].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LookupTable('Revelation.UD.Truancy','CONTACT_TYPE') AS [CONTACT_TYPE]
	ON
	[TRUANCY_LOG].[CONTACT_TYPE] = [CONTACT_TYPE].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LookupTable('Revelation.UD.Truancy','CONTACT_WITH') AS [CONTACT_WITH]
	ON
	[TRUANCY_LOG].[CONTACT_WITH] = [CONTACT_WITH].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LookupTable('Revelation.UD.Truancy','TRUANCY_STAFF') AS [TRUANCY_STAFF]
	ON
	[TRUANCY_LOG].[TRUANCY_STAFF] = [TRUANCY_STAFF].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LookupTable('Revelation.UD.Truancy','TRUANCY_STAFF_TITLE') AS [TRUANCY_STAFF_TITLE]
	ON
	[TRUANCY_LOG].[TRUANCY_STAFF_TITLE] = [TRUANCY_STAFF_TITLE].[VALUE_CODE]
	
WHERE
	[ENROLLMENTS].[ORGANIZATION_GU] LIKE @School
	AND [STUDENT].[SIS_NUMBER] = @Student
	
UNION
	
	
SELECT DISTINCT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[ORGANIZATION_GU]
	,[ENROLLMENTS].[YEAR_GU]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[ENTER_DATE],101) AS [ENTER_DATE]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[LEAVE_DATE],101) AS [LEAVE_DATE]
	,[ENROLLMENTS].[LEAVE_CODE]
	,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	
	,'STUDENT CONTACT' AS [LOG_TYPE]
	,4 AS [LOG_ORDER]
	
	,NULL AS [COMMUNITY_SUPPORT]
	
	,NULL AS [SCHOOL_YEAR]
	,NULL AS [TWO_DAY_TRUANT]
	,NULL AS [FIVE_DAY_TRUANT]
	,NULL AS [TEN_DAY_TRUANT]
	
	,CONVERT(VARCHAR(10),[PERSON_CONTACT].[CONTACT_DATE],101) AS [CONTACT_DATE]
	,CONVERT(VARCHAR(10),[PERSON_CONTACT].[CONTACT_TIME],108) AS [CONTACT_TIME]
	,[PERSON_CONTACT].[CONTACT_TYPE]
	,[CONTACT_TYPE].[VALUE_DESCRIPTION] AS [CONTACT_TYPE_DESC]
	,[PERSON_CONTACT].[PERSON_CONTACTED]
	,NULL AS [CONTACT_WITH_DESC]
	,CONVERT(VARCHAR,[PERSON_CONTACT].[COMMENT]) AS [NOTES_COMMENTS]
	,[PERSON_CONTACT].[OUTCOME] AS [OUTCOME_1]
	,[OUTCOME_1].[VALUE_DESCRIPTION] AS [OUTCOME_1_DESC]
	,NULL AS [OUTCOME_2]
	,NULL AS [OUTCOME_2_DESC]	
	,NULL [STAFF_CODE]	
	,[PERSON_CONTACT].[CONTACT_BY]
	,NULL AS [STAFF_TITLE]
	,NULL AS [STAFF_TITLE_DESC]
	
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2015
		AND EXTENSION = 'R'
		--AND EXCLUDE_ADA_ADM IS NULL
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.REV_PERSON_CONTACT AS [PERSON_CONTACT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [PERSON_CONTACT].[PERSON_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('Revelation','CONTACT_OUTCOME') AS [OUTCOME_1]
	ON
	[PERSON_CONTACT].[OUTCOME] = [OUTCOME_1].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','CONTACT_TYPE') AS [CONTACT_TYPE]
	ON
	[PERSON_CONTACT].[CONTACT_TYPE] = [CONTACT_TYPE].[VALUE_CODE]
	
WHERE
	[ENROLLMENTS].[ORGANIZATION_GU] LIKE @School
	AND [PERSON_CONTACT].[CONTACT_DATE] IS NOT NULL
	AND [STUDENT].[SIS_NUMBER] = @Student
	
UNION

SELECT DISTINCT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[ORGANIZATION_GU]
	,[ENROLLMENTS].[YEAR_GU]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[ENTER_DATE],101) AS [ENTER_DATE]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[LEAVE_DATE],101) AS [LEAVE_DATE]
	,[ENROLLMENTS].[LEAVE_CODE]
	,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	
	,'SE CONTACT' AS [LOG_TYPE]
	,3 AS [LOG_ORDER]
	
	,NULL AS [COMMUNITY_SUPPORT]
	
	,NULL AS [SCHOOL_YEAR]
	,NULL AS [TWO_DAY_TRUANT]
	,NULL AS [FIVE_DAY_TRUANT]
	,NULL AS [TEN_DAY_TRUANT]
	
	,CONVERT(VARCHAR(10),[AZ_CONTACT].[CONTACT_DATE],101) AS [CONTACT_DATE]
	,CONVERT(VARCHAR(10),[AZ_CONTACT].[CONTACT_TIME],108) AS [CONTACT_TIME]
	,[AZ_CONTACT].[CONTACT_TYPE]
	,[CONTACT_TYPE].[VALUE_DESCRIPTION] AS [CONTACT_TYPE_DESC]
	,[AZ_CONTACT].[PERSON_CONTACTED]
	,NULL AS [CONTACT_WITH_DESC]
	,CONVERT(VARCHAR,[AZ_CONTACT].[COMMENT]) AS [NOTES_COMMENTS]
	,[AZ_CONTACT].[OUTCOME] AS [OUTCOME_1]
	,[OUTCOME_1].[VALUE_DESCRIPTION] AS [OUTCOME_1_DESC]
	,NULL AS [OUTCOME_2]
	,NULL AS [OUTCOME_2_DESC]	
	,NULL [STAFF_CODE]	
	,[AZ_CONTACT].[CONTACT_BY]
	,NULL AS [STAFF_TITLE]
	,NULL AS [STAFF_TITLE_DESC]
	
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2015
		AND EXTENSION = 'R'
		--AND EXCLUDE_ADA_ADM IS NULL
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.EP_AZ_STU_PERSON_CONTACT AS [AZ_CONTACT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [AZ_CONTACT].[PERSON_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','CONTACT_TYPE') AS [CONTACT_TYPE]
	ON
	[AZ_CONTACT].[CONTACT_TYPE] = [CONTACT_TYPE].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LookupTable('Revelation','CONTACT_OUTCOME') AS [OUTCOME_1]
	ON
	[AZ_CONTACT].[OUTCOME] = [OUTCOME_1].[VALUE_CODE]
	
WHERE
	[ENROLLMENTS].[ORGANIZATION_GU] LIKE @School
	AND [AZ_CONTACT].[CONTACT_DATE] IS NOT NULL
	AND [STUDENT].[SIS_NUMBER] = @Student
	
UNION
	
SELECT DISTINCT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[ORGANIZATION_GU]
	,[ENROLLMENTS].[YEAR_GU]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[ENTER_DATE],101) AS [ENTER_DATE]
	,CONVERT(VARCHAR(10),[ENROLLMENTS].[LEAVE_DATE],101) AS [LEAVE_DATE]
	,[ENROLLMENTS].[LEAVE_CODE]
	,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	
	,'HEALTH CONTACT' AS [LOG_TYPE]
	,2 AS [LOG_ORDER]
	
	,NULL AS [COMMUNITY_SUPPORT]
	
	,NULL AS [SCHOOL_YEAR]
	,NULL AS [TWO_DAY_TRUANT]
	,NULL AS [FIVE_DAY_TRUANT]
	,NULL AS [TEN_DAY_TRUANT]
	
	,CONVERT(VARCHAR(10),[HEALTH].[COMMENT_DATE],101) AS [CONTACT_DATE]
	,NULL AS [CONTACT_TIME]
	,NULL AS [CONTACT_TYPE]
	,NULL AS [CONTACT_TYPE_DESC]
	,NULL AS [PERSON_CONTACTED]
	,NULL AS [CONTACT_WITH_DESC]
	,CONVERT(VARCHAR,[HEALTH].[COMMENT]) AS [NOTES_COMMENTS]
	,NULL AS [OUTCOME_1]
	,NULL AS [OUTCOME_1_DESC]
	,NULL AS [OUTCOME_2]
	,NULL AS [OUTCOME_2_DESC]	
	,NULL [STAFF_CODE]	
	--,[PERSON].[FIRST_NAME] + ' ' + [PERSON].[LAST_NAME] AS [CONTACT_BY] 
	,[STAFF].[BADGE_NUM] AS [CONTACT_BY]
	,NULL AS [STAFF_TITLE]
	,NULL AS [STAFF_TITLE_DESC]
	
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2015
		AND EXTENSION = 'R'
		--AND EXCLUDE_ADA_ADM IS NULL
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.EPC_STU_HEALTH_PRIVATE AS [HEALTH]
	ON
	[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [HEALTH].[STUDENT_SCHOOL_YEAR_GU]
	
	LEFT OUTER JOIN
	rev.EPC_STAFF AS [STAFF]
	ON
	[HEALTH].[ENTERED_BY_GU] = [STAFF].[STAFF_GU]
	
WHERE
	[ENROLLMENTS].[ORGANIZATION_GU] LIKE @School
	AND [HEALTH].[COMMENT_DATE] IS NOT NULL	
	AND [STUDENT].[SIS_NUMBER] = @Student
	
ORDER BY
	[LOG_ORDER]