





SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[SCHOOL_YEAR]
	,[CourseMaster].[COURSE_ID]
	,[SCHEDULE].[SECTION_ID]
	,[CourseMaster].[COURSE_TITLE]
	,[SCHEDULE].[TERM_CODE]
	,[COURSE_HISTORY].[MARK]
	,[STAFF_PERSON].[FIRST_NAME] + ' ' + [STAFF_PERSON].[LAST_NAME] AS [TEACHER]
	,[STAFF].[BADGE_NUM]
FROM
	APS.BasicSchedule AS [SCHEDULE]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[SCHEDULE].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.EPC_CRS AS [CourseMaster]
	ON
	[SCHEDULE].[COURSE_GU] = [CourseMaster].[COURSE_GU]
	
	INNER JOIN
	rev.REV_ORGANIZATION AS [ORG]
	ON
	[SCHEDULE].[ORGANIZATION_GU] = [ORG].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[SCHEDULE].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	INNER HASH JOIN
	rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
	ON
	[SCHEDULE].[STUDENT_GU] = [COURSE_HISTORY].[STUDENT_GU]
	AND [SCHEDULE].[COURSE_GU] = [COURSE_HISTORY].[COURSE_GU]
	AND [COURSE_HISTORY].[SCHOOL_YEAR] = '2014'
	
	INNER JOIN
	APS.StudentEnrollmentDetails AS [ENROLLMENTS]
	ON
	[SCHEDULE].[STUDENT_SCHOOL_YEAR_GU] = [ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU]
	
	INNER JOIN
	rev.REV_PERSON AS [STAFF_PERSON]
	ON
	[SCHEDULE].[STAFF_GU] = [STAFF_PERSON].[PERSON_GU]
	
	INNER JOIN
	rev.EPC_STAFF AS [STAFF]
	ON
	[SCHEDULE].[STAFF_GU] = [STAFF].[STAFF_GU]
	
WHERE
	[RevYear].[SCHOOL_YEAR] = '2014'
	AND [RevYear].[EXTENSION] = 'R'
	AND ([SCHEDULE].[COURSE_LEAVE_DATE] IS NULL OR [SCHEDULE].[TERM_CODE] IN ('S1','FY','YR','Q1','Q2'))
	AND [ENROLLMENTS].[GRADE] BETWEEN '06' AND '12'
	AND [CourseMaster].[DEPARTMENT] IN ('Math','Eng')