


SELECT
	[STUDENTS].[SCHOOL_CODE]
	,[STUDENTS].[SCHOOL_NAME]
	,COUNT([STUDENTS].[SIS_NUMBER]) AS [STUDENTS]
FROM
	(
	SELECT
		[STUDENT].[SIS_NUMBER]
		,[STUDENT].[FIRST_NAME]
		,[STUDENT].[LAST_NAME]
		,[STUDENT].[MIDDLE_NAME]
		,[ENROLLMENT_2015].[GRADE]
		,[ENROLLMENT_2015].[SCHOOL_CODE]
		,[ENROLLMENT_2015].[SCHOOL_NAME]
		,[ENROLLMENT_2014].[GRADE] AS [2014_GRADE]
		,[ENROLLMENT_2014].[SCHOOL_CODE] AS [2014_CODE]
		,[ENROLLMENT_2014].[SCHOOL_NAME] AS [2014_LOCATION]
		,[ENROLLMENT_2014].[ENTER_DATE]
		
	FROM
		(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY [ENROLLMENT_2015].[STUDENT_GU] ORDER BY [ENROLLMENT_2015].[ENTER_DATE] DESC) AS RN
		FROM
			APS.StudentEnrollmentDetails AS [ENROLLMENT_2015]
			
		WHERE
			[ENROLLMENT_2015].[SCHOOL_YEAR] = '2015'
			AND [ENROLLMENT_2015].[EXTENSION] = 'R'
			AND [ENROLLMENT_2015].[SCHOOL_NAME] LIKE '%ELEMENTARY%'
			AND [ENROLLMENT_2015].[HOMEROOM_SECTION_GU] IS NULL
		) AS [ENROLLMENT_2015]
		
		INNER JOIN
		(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY [ENROLLMENT_2014].[STUDENT_GU] ORDER BY [ENROLLMENT_2014].[ENTER_DATE] DESC) AS RN
		FROM
			APS.StudentEnrollmentDetails AS [ENROLLMENT_2014]
			
		WHERE
			[ENROLLMENT_2014].[SCHOOL_YEAR] = '2014'
			AND [ENROLLMENT_2014].[EXTENSION] = 'R'
		) AS [ENROLLMENT_2014]
		ON
		[ENROLLMENT_2015].[STUDENT_GU] = [ENROLLMENT_2014].[STUDENT_GU]
		AND [ENROLLMENT_2014].[RN] = 1
		
		INNER JOIN
		APS.BasicStudent AS [STUDENT]
		ON
		[ENROLLMENT_2015].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
	WHERE
		[ENROLLMENT_2015].[RN] = 1
	) AS [STUDENTS]
	
GROUP BY
	[STUDENTS].[SCHOOL_CODE]
	,[STUDENTS].[SCHOOL_NAME]
	
ORDER BY
	[STUDENTS].[SCHOOL_CODE]	
	