



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].FIRST_NAME
	,[STUDENT].[LAST_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_YEAR] AS [LAST_SCHOOL_YEAR]
	,[ENROLLMENTS].[SCHOOL_CODE] AS [LAST_LOCATION_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME] AS [LAST_SCHOOL_NAME]
	,[STU_ADR_HST].[HOME_LESS]
	,[STU_ADR_HST].[GRID_CODE]
	,[STU_ADR_HST].[DWELLING_TYPE]
	,[ADDRESS].[ADDRESS] AS [HOME_ADDRESS]
	,[ADDRESS].[ADDRESS2] AS [HOME_ADDRESS_2]
	,[ADDRESS].[CITY] AS [HOME_CITY]
	,[ADDRESS].[STATE] AS [HOME_STATE]
	,[ADDRESS].[ZIP_5] AS [HOME_ZIP]
FROM
	rev.EPC_STU_ADDRESS_HISTORY AS [STU_ADR_HST]
	
	INNER JOIN
	rev.REV_ADDRESS_HISTORY AS [ADR_HST]
	ON
	[STU_ADR_HST].[ADDRESS_HISTORY_GU] = [ADR_HST].[ADDRESS_HISTORY_GU]
	
	-- Get Home Address
	LEFT OUTER JOIN
	rev.REV_ADDRESS AS [ADDRESS]
	ON
	[ADR_HST].[ADDRESS_GU] = [ADDRESS].[ADDRESS_GU]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ADR_HST].[PERSON_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
		FROM
			APS.StudentEnrollmentDetails
			
		WHERE
			SCHOOL_YEAR IN ('2013','2014','2015')
			AND EXTENSION = 'R'
			--AND EXCLUDE_ADA_ADM IS NULL
	) AS [ENROLLMENTS]
	ON
	[STUDENT].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]
	AND [ENROLLMENTS].[RN] = 1
	
WHERE
	[STU_ADR_HST].[HOME_LESS] IS NOT NULL
	