





SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[School].[SCHOOL_CODE]
	,[Organization].[ORGANIZATION_NAME] AS [APS_SCHOOL_LOCATION]
	,[NON_DIST].[NAME] AS [NON_DISTRICT_SCHOOL]
	,[COURSE_HISTORY].[SCHOOL_YEAR]
	,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
	,[COURSE].[COURSE_ID]
	,[COURSE].[COURSE_TITLE]
	,[COURSE_HISTORY].[TERM_CODE]
	,[STUDENT].[SPED_STATUS]
	
	,[COURSE_HISTORY].[MARK]
	
	--,[COURSE_HISTORY].[SCHOOL_NON_DISTRICT_GU]
FROM
	rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
	
	INNER JOIN
	rev.EPC_CRS AS [COURSE]
	ON
	[COURSE_HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[COURSE_HISTORY].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','Grade') AS [Grades]
	ON
	[COURSE_HISTORY].[GRADE] = [Grades].[VALUE_CODE]
	
	LEFT OUTER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[COURSE_HISTORY].[SCHOOL_IN_DISTRICT_GU] = [Organization].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN
	rev.EPC_SCH_NON_DST AS [NON_DIST]
	ON
	[COURSE_HISTORY].[SCHOOL_NON_DISTRICT_GU] = [NON_DIST].[SCHOOL_NON_DISTRICT_GU]
	
WHERE
	([COURSE].[COURSE_ID] LIKE '5%'
	OR [COURSE].[COURSE_ID] LIKE '6%'
	OR [COURSE].[COURSE_ID] LIKE '7%'
	OR [COURSE].[COURSE_ID] LIKE '8%')
	AND [COURSE_HISTORY].[SCHOOL_YEAR] IN ('2012','2013','2014')
	AND [Grades].[VALUE_DESCRIPTION] IN ('09','10','11','12')
	
	--AND [STUDENT].[SIS_NUMBER] = '980012355'