


SELECT
	--[STUDENT].[SIS_NUMBER]
	--,[STUDENT].FIRST_NAME
	--,[STUDENT].[LAST_NAME]
	--,[ENROLLMENTS].[GRADE]
	--,[ENROLLMENTS].[SCHOOL_YEAR]
	--,[ENROLLMENTS].[SCHOOL_CODE]
	--,[ENROLLMENTS].[SCHOOL_NAME]
	
	SUM(CASE WHEN [STUDENT].[LUNCH_STATUS] = 'F' THEN 1 ELSE 0 END) AS [FREE]
	,SUM(CASE WHEN [STUDENT].[LUNCH_STATUS] = '2' THEN 1 ELSE 0 END) AS [PRIORITY 2]
	,SUM(CASE WHEN [STUDENT].[LUNCH_STATUS] = 'R' THEN 1 ELSE 0 END) AS [REDUCED]
	,SUM(CASE WHEN [STUDENT].[LUNCH_STATUS] = 'N' THEN 1 ELSE 0 END) AS [NON-PARTICIPANT]
FROM
	APS.PrimaryEnrollmentDetailsAsOf('10/14/2015') AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[ENROLLMENTS].[SCHOOL_CODE] = '496'