



SELECT
	[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]	
	,[STUDENT].[MAIL_ADDRESS]
	,[STUDENT].[MAIL_CITY]
	,[STUDENT].[MAIL_STATE]
	,[STUDENT].[MAIL_ZIP]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[STUDENT].[PRIMARY_PHONE]
	,[PERSON].[EMAIL]
	,[CUM_GPA].[HS Cum Weighted]
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.REV_PERSON AS [PERSON]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [PERSON].[PERSON_GU]
	
	INNER JOIN
	APS.CUMGPA AS [CUM_GPA]
	ON
	[STUDENT].[SIS_NUMBER] = [CUM_GPA].[SIS_NUMBER]
	
WHERE
	[ENROLLMENTS].[GRADE] = '10'
	AND [CUM_GPA].[HS Cum Weighted] >= 3.2