





SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[EPC_STU].[GRID_CODE]
	,[PRIMARY].[GRADE]	AS [GRADE_16]
	,[PRIMARY].[SCHOOL_YEAR] AS [SCHOOL_YEAR_16]
	,[PRIMARY].[SCHOOL_CODE] AS [SCHOOL_CODE_16]
	,[PRIMARY].[SCHOOL_NAME] AS [SCHOOL_NAME_16]
	,[PRIMARY].[ENTER_DATE] AS [ENTER_DATE_16]
	,[PRIMARY].[LEAVE_DATE] AS [LEAVE_DATE_16]
	,[PRIMARY].[EXCLUDE_ADA_ADM] AS [EXCLUDE_ADA_ADM_16]
	,[PRIMARY].[CONCURRENT] AS [CONCURRENT_16]
	,'' AS [SPACE]
	,[PREVIOUS_ENROLLMENTS].[GRADE] AS [GRADE_15]
	,[PREVIOUS_ENROLLMENTS].[SCHOOL_YEAR] AS [SCHOOL_YEAR_15]
	,[PREVIOUS_ENROLLMENTS].[SCHOOL_CODE] AS [SCHOOL_CODE_15]
	,[PREVIOUS_ENROLLMENTS].[SCHOOL_NAME] AS [SCHOOL_NAME_15]
	,[PREVIOUS_ENROLLMENTS].[ENTER_DATE] AS [ENTER_DATE_15]
	,[PREVIOUS_ENROLLMENTS].[LEAVE_DATE] AS [LEAVE_DATE_15]
	,[PREVIOUS_ENROLLMENTS].[EXCLUDE_ADA_ADM] AS [EXCLUDE_ADA_ADM_15]
	,[PREVIOUS_ENROLLMENTS].[CONCURRENT] AS [CONCURRENT_15]
FROM
	APS.PrimaryEnrollmentDetailsAsOf('8/11/2016') AS [PRIMARY]
	
	LEFT OUTER JOIN
	APS.StudentEnrollmentDetails AS [PREVIOUS_ENROLLMENTS]
	ON
	[PRIMARY].[STUDENT_GU] = [PREVIOUS_ENROLLMENTS].[STUDENT_GU]
	AND [PREVIOUS_ENROLLMENTS].[SCHOOL_YEAR] = '2015'
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[PRIMARY].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.EPC_STU AS [EPC_STU]
	ON
	[STUDENT].[STUDENT_GU] = [EPC_STU].[STUDENT_GU]
	
WHERE
	[PRIMARY].[GRADE] = 'K'