


SELECT
	[GROUP].[CODE]
	,[GROUP].[DESCRIPTION]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[ENROLLMENTS].[GRADE]
	,[STUDENT].[CLASS_OF]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[STUDENT].[SPED_STATUS]
	
FROM
	APS.StudentEnrollmentDetails AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.EPC_STU_GROUP AS [GROUP_STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [GROUP_STUDENT].[STUDENT_SCHOOL_YEAR_GU]
	
	INNER JOIN
	rev.EPC_STU_GROUP_SCH_YR AS [GROUP_SCHOOL]
	ON
	[GROUP_STUDENT].[STU_GROUP_SCH_YEAR_GU] = [GROUP_SCHOOL].[STU_GROUP_SCH_YEAR_GU]
	
	INNER JOIN
	rev.EPC_GROUP AS [GROUP]
	ON
	[GROUP_SCHOOL].[GROUP_GU] = [GROUP].[GROUP_GU]
	
WHERE
	[ENROLLMENTS].[SCHOOL_YEAR] = '2015'
	AND [ENROLLMENTS].[EXTENSION] = 'R'
	
	AND [GROUP_SCHOOL].[CODE] IN 
	('BPA',
	'DECA',
	'FCCLA',
	'FEA',
	'HOSA',
	'NFFA',
	'SKILLS',
	'TSA')
	
ORDER BY
	[GROUP].[CODE]
