






SELECT
	[FIRST_INCIDENT].*
FROM
	(
	SELECT
		[ENROLLMENTS].[SCHOOL_YEAR]
		,[ENROLLMENTS].[SCHOOL_CODE]
		,[ENROLLMENTS].[SCHOOL_NAME]
		,[STUDENT].[SIS_NUMBER]
		,[STUDENT].[FIRST_NAME]
		,[STUDENT].[LAST_NAME]
		,[ENROLLMENTS].[GRADE]
		,[STUDENT].[GENDER]
		,[STUDENT].[ELL_STATUS]
		,[STUDENT].[SPED_STATUS]
		
		,[INCIDENT].[SCH_INCIDENT_GU]
		,[INCIDENT].[INCIDENT_DATE]
		,[INCIDENT].[INCIDENT_TIME]
		,[INCIDENT].[INCIDENT_ID]
		,[INCIDENT].[ENTERED_BY_GU]
		,[INCIDENT].[REFERRED_BY_FNAME]
		,[INCIDENT].[REFERRED_BY_LNAME]
		,[INCIDENT].[REFFERAL_DATE]
		,[INCIDENT].[DESCRIPTION]
		,[INCIDENT].[GANG_RELATED]
		,[INCIDENT].[HATE_RELATED]
		,[INCIDENT].[REFER_LAW_ENFORCEMENT]
		
		
		--,[INCIDENT].*	
		
	FROM
		(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
		FROM
			APS.StudentEnrollmentDetails
			
		WHERE
			SCHOOL_YEAR = 2014
			AND EXTENSION = 'R'
			--AND EXCLUDE_ADA_ADM IS NULL
		) AS [ENROLLMENTS]
		
		INNER JOIN
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		ON
		[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		INNER JOIN
		[rev].[EPC_STU_INC_DISCIPLINE] AS [Discipline]
		ON
		[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [Discipline].[STUDENT_SCHOOL_YEAR_GU]
	    
		INNER JOIN
		rev.EPC_SCH_INCIDENT AS [INCIDENT]
		ON
		[Discipline].[SCH_INCIDENT_GU] = [INCIDENT].[SCH_INCIDENT_GU]
		
	) AS [FIRST_INCIDENT]	
	
	INNER JOIN		
	(
	SELECT
		[ENROLLMENTS].[SCHOOL_YEAR]
		,[ENROLLMENTS].[SCHOOL_CODE]
		,[ENROLLMENTS].[SCHOOL_NAME]
		,[STUDENT].[SIS_NUMBER]
		,[STUDENT].[FIRST_NAME]
		,[STUDENT].[LAST_NAME]
		,[ENROLLMENTS].[GRADE]
		,[STUDENT].[GENDER]
		,[STUDENT].[ELL_STATUS]
		,[STUDENT].[SPED_STATUS]
		
		,[INCIDENT].[INCIDENT_DATE]
		,[INCIDENT].[INCIDENT_ID]
		,[INCIDENT].[ENTERED_BY_GU]
		,[INCIDENT].[INCIDENT_TIME]
				
	FROM
		(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
		FROM
			APS.StudentEnrollmentDetails
			
		WHERE
			SCHOOL_YEAR = 2014
			AND EXTENSION = 'R'
			--AND EXCLUDE_ADA_ADM IS NULL
		) AS [ENROLLMENTS]
		
		INNER JOIN
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		ON
		[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		INNER JOIN
		[rev].[EPC_STU_INC_DISCIPLINE] AS [Discipline]
		ON
		[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [Discipline].[STUDENT_SCHOOL_YEAR_GU]
	    
		INNER JOIN
		rev.EPC_SCH_INCIDENT AS [INCIDENT]
		ON
		[Discipline].[SCH_INCIDENT_GU] = [INCIDENT].[SCH_INCIDENT_GU]
	
	) AS [SECOND_INCIDENT]
	ON
	[FIRST_INCIDENT].[SCHOOL_CODE] = [SECOND_INCIDENT].[SCHOOL_CODE]
	AND [FIRST_INCIDENT].[SIS_NUMBER] = [SECOND_INCIDENT].[SIS_NUMBER]
	AND [FIRST_INCIDENT].[INCIDENT_ID] != [SECOND_INCIDENT].[INCIDENT_ID]
	AND [FIRST_INCIDENT].[INCIDENT_DATE] = [SECOND_INCIDENT].[INCIDENT_DATE]
	AND [FIRST_INCIDENT].[INCIDENT_TIME] = [SECOND_INCIDENT].[INCIDENT_TIME]
	AND [FIRST_INCIDENT].[ENTERED_BY_GU] = [SECOND_INCIDENT].[ENTERED_BY_GU]
	
--WHERE
--	[FIRST_INCIDENT].[SIS_NUMBER] = '970052509'
	
ORDER BY
	[FIRST_INCIDENT].[INCIDENT_DATE]
	,[FIRST_INCIDENT].[SIS_NUMBER]
	