

DECLARE @DEPARTMENT VARCHAR(10)  = 'Math', @SUBJECTAREA VARCHAR(10) = 'Math'
DECLARE @SCHOOL VARCHAR(128) = '542DF5D7-0D20-413A-B9BA-5BDD0F6D5E1A'

SELECT DISTINCT
	--[DISTRICT_COURSE].[COURSE_GU]
	[DISTRICT_COURSE].[COURSE_ID]
	,[SECTION_SCHOOL_YEAR].[SECTION_ID]
	,[DISTRICT_COURSE].[COURSE_TITLE]
	,[DISTRICT_COURSE].[DEPARTMENT]
	,[DISTRICT_COURSE].[SUBJECT_AREA_1]
	,[DISTRICT_COURSE].[SUBJECT_AREA_2]
	,[DISTRICT_COURSE].[SUBJECT_AREA_3]
	,[DISTRICT_COURSE].[STATE_COURSE_CODE]
	
	,[SECTION_SCHOOL_YEAR].[SECTION_GU]
	,[COURSE_SCHOOL_YEAR].[SCHOOL_YEAR_COURSE_GU]
	,[STAFF].[STAFF_GU]
	
	,[Organization].[ORGANIZATION_NAME] AS [School Name]
	,[PERSON].[LAST_NAME]
	,[PERSON].[FIRST_NAME]
	,[PERSON].[EMAIL]
	,[PERSON].[JOB_TITLE]
	,[PERSON].[PRIMARY_PHONE]
	,SUBSTRING([STAFF].[BADGE_NUM],2,99) AS [BADGE_NUM]
	,[STAFF].[STATE_ID]
	--,[STAFF_SCHOOL_YEAR].*
FROM
	rev.[EPC_CRS] AS [DISTRICT_COURSE]
	
	INNER JOIN
    rev.[EPC_SCH_YR_CRS] AS [COURSE_SCHOOL_YEAR]
    ON
    [DISTRICT_COURSE].[COURSE_GU] = [COURSE_SCHOOL_YEAR].[COURSE_GU]
    
    INNER JOIN
    rev.[EPC_SCH_YR_SECT] AS [SECTION_SCHOOL_YEAR]
    ON
    [SECTION_SCHOOL_YEAR].[SCHOOL_YEAR_COURSE_GU] = [COURSE_SCHOOL_YEAR].[SCHOOL_YEAR_COURSE_GU]
    
    INNER JOIN
    rev.[EPC_STAFF_SCH_YR] AS [STAFF_SCHOOL_YEAR]
    ON
    [SECTION_SCHOOL_YEAR].[STAFF_SCHOOL_YEAR_GU] = [STAFF_SCHOOL_YEAR].[STAFF_SCHOOL_YEAR_GU]
    
    INNER JOIN 
	[SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
	ON 
	[STAFF_SCHOOL_YEAR].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
    
    INNER JOIN 
	[SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
    
    INNER JOIN
    rev.[EPC_STAFF] AS [STAFF]
    ON
    [STAFF_SCHOOL_YEAR].[STAFF_GU] = [STAFF].[STAFF_GU]
    
    INNER JOIN
    rev.[REV_PERSON] AS [PERSON]
    ON
    [STAFF].[STAFF_GU] = [PERSON].[PERSON_GU]
	
WHERE
	[DISTRICT_COURSE].[INACTIVE] = 'N'
	AND [DISTRICT_COURSE].[DEPARTMENT] = COALESCE(@DEPARTMENT,[DISTRICT_COURSE].[DEPARTMENT])
	AND [DISTRICT_COURSE].[SUBJECT_AREA_1] = COALESCE(@SUBJECTAREA,[DISTRICT_COURSE].[SUBJECT_AREA_1])
	AND [STAFF_SCHOOL_YEAR].[ORGANIZATION_YEAR_GU] LIKE @SCHOOL
	AND [STAFF].[STATE_ID] = '32614'
	
	

/*	
	INNER JOIN
    rev.EPC_SCH_YR_SECT AS SEC
    ON
    TAGS.SECTION_GU = SEC.SECTION_GU
    
    INNER JOIN
    rev.EPC_SCH_YR_CRS AS CRSYR
    ON
    SEC.SCHOOL_YEAR_COURSE_GU = CRSYR.SCHOOL_YEAR_COURSE_GU
    
    INNER JOIN
    rev.EPC_CRS AS CRS
    ON
    CRSYR.COURSE_GU = CRS.COURSE_GU

    INNER JOIN
    rev.EPC_SCH_YR_SECT AS SECYR
    ON
    SECYR.ORGANIZATION_YEAR_GU = CRSYR.ORGANIZATION_YEAR_GU
    AND 
    SECYR.SECTION_GU = SEC.SECTION_GU

    INNER JOIN
    rev.EPC_STAFF_SCH_YR AS STAFFYR
    ON
    STAFFYR.STAFF_SCHOOL_YEAR_GU = SECYR.STAFF_SCHOOL_YEAR_GU
    
    INNER JOIN
    rev.EPC_STAFF AS STAFF
    ON
    STAFFYR.STAFF_GU = STAFF.STAFF_GU

*/
