

DECLARE @AsOfDate DATE = GETDATE()

SELECT
	[HISTORY].[ADD_DATE_TIME_STAMP]
	,[HISTORY].[CHANGE_DATE_TIME_STAMP]
	,[HISTORY].[DATE_RUN]
	,[HISTORY].[OLD_PERM_ID]
	,[HISTORY].[OLD_STATE_ID]
	,[HISTORY].[REASON]
	,[HISTORY].[USER_RAN]
FROM
	rev.UD_UD_EPC_STU_MERGE_HISTORY AS [HISTORY]
	
WHERE
	[HISTORY].[DATE_RUN] <= @AsOfDate