


BEGIN TRAN

UPDATE [STREET]
--	SET [EPC_STU].[GRID_CODE] = '227420530'
  SET [STREET].[GRID_GU] = 'E79C8D12-E6C8-4FE0-8C4D-BE06476DF134'

--SELECT DISTINCT
--	[STUDENT_DETAILS].[SIS_NUMBER]
--	,[STUDENT_DETAILS].[FIRST_NAME]
--	,[STUDENT_DETAILS].[LAST_NAME]
--	,[ENROLLMENTS].[EXCLUDE_ADA_ADM]
--	,[ENROLLMENTS].[CONCURRENT]
--	,[ENROLLMENTS].[SCHOOL_CODE]
--	,[ENROLLMENTS].[SCHOOL_NAME]
--	,[ENROLLMENTS].[ENTER_DATE]
--	,[ENROLLMENTS].[LEAVE_DATE]
--	,[EPC_STU].[GRID_CODE] AS [STUDENT_GRID(EPC_STU)]
--	--[STUDENT_DETAILS].*
--	,[HOME_ADDRESS].[ADDRESS] AS [HOME_ADDRESS]
--	,[HOME_ADDRESS].[CITY] AS [HOME_CITY]
--	,[HOME_ADDRESS].[STATE] AS [HOME_STATE]
--	,[HOME_ADDRESS].[ZIP_5] AS [HOME_ZIP]
--	--,[STREET].*
--	--,'' AS [SPACE]
--	--,[EPC_STU].*
--	--[Person].*
--	,[STREET].[GRID_GU]
--	,[STREET_GRID].[GRID_CODE] AS [STREET_GRID_CODE]
--	,[STREET_GRID].[GRID_GU]
--	--,[STREET_GRID].*
--	--,[STREET].[STREET_HIGH_ADDRESS]
--	--,[STREET].[STREET_LOW_ADDRESS]
--	--,[STREET].[STREET_NAME]
--	--,[STREET].[CITY] AS [STREET_CITY]
--	--,[STREET].[STATE] AS [STREET_STATE]
--	--,[STREET].[ZIP_5] AS [STREET_ZIP_5]
FROM
	APS.StudentEnrollmentDetails AS [ENROLLMENTS]

	INNER JOIN
	APS.BasicStudent AS [STUDENT_DETAILS]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT_DETAILS].[STUDENT_GU]
	
	INNER JOIN
	rev.EPC_STU AS [EPC_STU]
	ON
	[STUDENT_DETAILS].[STUDENT_GU] = [EPC_STU].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.REV_ADDRESS AS [HOME_ADDRESS]
	ON
	[STUDENT_DETAILS].[HOME_ADDRESS_GU] = [HOME_ADDRESS].[ADDRESS_GU]
	
	LEFT OUTER JOIN
	rev.EPC_STREET AS [STREET]
	ON
	[HOME_ADDRESS].[STREET_NUMBER] BETWEEN [STREET].[STREET_HIGH_ADDRESS] AND [STREET].[STREET_LOW_ADDRESS]
	AND [HOME_ADDRESS].[ZIP_5] = [STREET].[ZIP_5]
	AND [HOME_ADDRESS].[STREET_NAME] = [STREET].[STREET_NAME]
	AND [HOME_ADDRESS].[CITY] = [STREET].[CITY]
	
	LEFT OUTER JOIN
	rev.EPC_GRID AS [STREET_GRID]
	ON
	[STREET].[GRID_GU] = [STREET_GRID].[GRID_GU]
	
	--INNER JOIN
	--rev.REV_PERSON AS [Person]
	--ON
	--[STUDENT_DETAILS].[STUDENT_GU] = [Person].[PERSON_GU]

WHERE
	[ENROLLMENTS].[SCHOOL_YEAR] = '2016'
	AND 
	(
		--CONVERT(VARCHAR(9),[EPC_STU].[GRID_CODE]) LIKE '204%'
		--OR
		CONVERT(VARCHAR(9),[STREET_GRID].[GRID_CODE]) LIKE '204%'
	)
	
--ROLLBACK
COMMIT