

UPDATE [STUDENT]
	SET [STUDENT].[ENROLL_LESS_THREE_OVR] = 'Y'

--SELECT
--	[STUDENT].[SIS_NUMBER]
--	--,[STUDENT].[STUDENT_GU]
--	,[STUDENT].[ENROLL_LESS_THREE_OVR]
--	,[PERSON].[LAST_NAME]
--	,[PERSON].[FIRST_NAME]
--	,[School].[SCHOOL_CODE] 
--	,[Organization].[ORGANIZATION_NAME] AS [SCHOOL_NAME]
--	--,[RevYear].[SCHOOL_YEAR]
--	,[ENROLLMENTS].[GRADE]
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails 
		
	WHERE
		SCHOOL_YEAR = 2015
		AND EXTENSION = 'R'
		--AND EXCLUDE_ADA_ADM IS NULL
		AND LIST_ORDER <= 40
	) AS [ENROLLMENTS]
		
	INNER JOIN
	rev.[EPC_STU] AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.[REV_PERSON] AS [PERSON]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [PERSON].[PERSON_GU]
	
	LEFT JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
	ON 
	[ENROLLMENTS].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
	
	LEFT JOIN 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[OrgYear].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	LEFT JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[OrgYear].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
	
WHERE
	[ENROLLMENTS].[RN] = 1
--	[STUDENT].[SIS_NUMBER] = '980014132'
	AND [STUDENT].[ENROLL_LESS_THREE_OVR] = 'N'