


; WITH 
-- From Student School Year [EPC_STU_SCH_YR]
SSY_ENROLLMENTS AS
(
SELECT
	[StudentSchoolYear].[STUDENT_GU]
	,[StudentSchoolYear].[ORGANIZATION_YEAR_GU]
	,[Organization].[ORGANIZATION_GU]
	,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
	,[School].[SCHOOL_CODE]
	,[Organization].[ORGANIZATION_NAME] AS [SCHOOL_NAME]
	,[StudentSchoolYear].[ENTER_DATE]
	,[StudentSchoolYear].[LEAVE_DATE]
	,[StudentSchoolYear].[EXCLUDE_ADA_ADM]
	,[RevYear].[SCHOOL_YEAR]
	,[RevYear].[EXTENSION]
FROM
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
	
	INNER JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
	ON 
	[StudentSchoolYear].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[OrgYear].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','Grade') AS [Grades]
	ON
	[StudentSchoolYear].[GRADE] = [Grades].[VALUE_CODE]
	
	INNER JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
)



SELECT DISTINCT
	[STUDENT].[SIS_NUMBER] AS [APS_STUDENT_ID]
	,SUBSTRING([STAFF].[BADGE_NUM],2,99) AS [APS_TEACHER_ID]
	--,[ALL_STAFF_SCH_YR].[STAFF_GU]
	--,[SECTION_SCHOOL_YEAR].[STAFF_SCHOOL_YEAR_GU]
	--,[SCHEDULE].[SCHOOL_YEAR_COURSE_GU]
	--,[ALL_STAFF_SCH_YR].[PRIMARY_STAFF] AS [PRIMARY_TEACHER]
	,[ASSIGNED_STAFF].[PRIMARY_TEACHER]
	,CASE WHEN [SCHEDULE].[PERIOD_BEGIN] = 1 THEN 'Y' ELSE 'N' END AS [HOMEROOM_TEACHER]
	,'2014 - 2015' AS [SCHOOL_YEAR]
	,[SCHEDULE].[COURSE_ID]
	,[SCHEDULE].[SECTION_ID]
	,[SCHEDULE].[COURSE_TITLE]
	,[SCHEDULE].[DEPARTMENT]
	,[SCHEDULE].[COURSE_ENTER_DATE]
	,[SCHEDULE].[COURSE_LEAVE_DATE]
	--,'' AS [COURSE_TY]
	,[ENROLLMENTS].[GRADE] AS [STUDENT_GRADE_LEVEL]
	,[COURSE_GRADE_LOW].[VALUE_DESCRIPTION] + ' - ' + [COURSE_GRADE_LOW].[VALUE_DESCRIPTION] AS [COURSE_GRADE_RANGE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[SCHEDULE].[TERM_CODE]
	,'' AS [CURRENT_GRADE]
	--,'' AS [GRADE_TYPE]
	--,[SECTION_SCHOOL_YEAR].*
	
	--,[SCHEDULE].*
FROM
	SSY_ENROLLMENTS AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT JOIN
	APS.ScheduleWithFutureAsOf(GETDATE()) AS [SCHEDULE]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [SCHEDULE].[STUDENT_GU]
	AND [ENROLLMENTS].[ORGANIZATION_YEAR_GU] = [SCHEDULE].[ORGANIZATION_YEAR_GU]
	
	LEFT JOIN
	APS.SectionsAndAllStaffAssigned AS [ASSIGNED_STAFF]
	ON
	[SCHEDULE].[SECTION_GU] = [ASSIGNED_STAFF].[SECTION_GU]
    
    LEFT JOIN
    rev.[EPC_STAFF] AS [STAFF]
    ON
    [ASSIGNED_STAFF].[STAFF_GU] = [STAFF].[STAFF_GU]
    
    LEFT JOIN
    rev.[REV_PERSON] AS [PERSON]
    ON
    [STAFF].[STAFF_GU] = [PERSON].[PERSON_GU]
    
    LEFT OUTER JOIN
	APS.LookupTable('K12','Grade') AS [COURSE_GRADE_LOW]
	ON
	[SCHEDULE].[GRADE_RANGE_LOW] = [COURSE_GRADE_LOW].[VALUE_CODE]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','Grade') AS [COURSE_GRADE_HIGH]
	ON
	[SCHEDULE].[GRADE_RANGE_HIGH] = [COURSE_GRADE_HIGH].[VALUE_CODE]
	
WHERE
	[ENROLLMENTS].[SCHOOL_YEAR] = '2014'
	AND [ENROLLMENTS].[EXTENSION] = 'R'
	AND [ENROLLMENTS].[GRADE] IN ('04','05','06')
	AND (
		([SCHEDULE].[DEPARTMENT] = 'Elem' AND [SCHEDULE].[PERIOD_BEGIN] = 1)
		OR
		([SCHEDULE].[DEPARTMENT] IN ('Math','Eng'))
		)
		
	--AND [ASSIGNED_STAFF].[PRIMARY_TEACHER] = 'N'	
	--AND [STUDENT].[SIS_NUMBER] = '104308382'
		
	