


--SCHOOL_CODE	SCHOOL_NAME	PERIOD_BEGIN	COURSE_TITLE	COURSE_ID	TEACHER FIRST NAME	TEACHER LAST NAME	SIS_NUMBER	STUDENT FIRST NAME	STUDENT LAST NAME


SELECT
	[ENROLLMENT].[SCHOOL_CODE]
	,[ENROLLMENT].[SCHOOL_NAME]
	,[SCHEDULE].[PERIOD_BEGIN]
	,[SCHEDULE].[PERIOD_END]
	,[SCHEDULE].[COURSE_TITLE]
	,[SCHEDULE].[COURSE_ID]
	,[TEACHER_PERSON].[FIRST_NAME] AS [TEACHER FIRST NAME]
	,[TEACHER_PERSON].[LAST_NAME] AS [TEACHER LAST NAME]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME] AS [STUDENT FIRST NAME]
	,[STUDENT].[LAST_NAME] AS [STUDENT LAST NAME]
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENT]
	
	INNER JOIN
	APS.ScheduleDetailsAsOf(GETDATE()) AS [SCHEDULE]
	ON
	[ENROLLMENT].[STUDENT_GU] = [SCHEDULE].[STUDENT_GU]
	AND [ENROLLMENT].[ORGANIZATION_YEAR_GU] = [SCHEDULE].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.REV_PERSON AS [TEACHER_PERSON]
	ON
	[SCHEDULE].[STAFF_GU] = [TEACHER_PERSON].[PERSON_GU]
	
WHERE
	[ENROLLMENT].[SCHOOL_CODE] IN  ('420')
	AND ([SCHEDULE].[PERIOD_BEGIN] = 2 OR [SCHEDULE].[PERIOD_END] = 2)
	