


SELECT
      [STUDENT].[SIS_NUMBER]
      ,[STUDENT].[STATE_STUDENT_NUMBER]
      ,[STUDENT].[FIRST_NAME]
      ,[STUDENT].[LAST_NAME]
      ,[STUDENT].[MIDDLE_NAME]
      ,[STUDENT].[GENDER]
      ,[ENROLLMENT].[ENTER_DATE]
      ,[ENROLLMENT].[LEAVE_DATE]
      ,[ENROLLMENT].[LEAVE_CODE]
      ,[LEAVE_CODE].[ALT_CODE_2] AS [STATE_CODE]
      ,[StudentSchoolYear].[ENR_USER_DD_4] AS [HOME/CHARTER]
      
      --,[LEAVE_CODE].*
      
FROM
	APS.StudentEnrollmentDetails AS [ENROLLMENT]

	INNER JOIN
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
	ON
	[ENROLLMENT].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]

	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]

	LEFT OUTER JOIN
	APS.LookupTable('K12.ENROLLMENT','LEAVE_CODE') AS [LEAVE_CODE]
	ON
	[ENROLLMENT].[LEAVE_CODE] = [LEAVE_CODE].[VALUE_CODE]
      
WHERE
      --[ENROLLMENT].[SCHOOL_YEAR] = '2014'
      --AND [ENROLLMENT].[EXTENSION] = 'R'
      [ENROLLMENT].[ENTER_DATE] BETWEEN '05/23/2014' AND '05/22/2015'
      
      --AND [ENR_USER_DD_4] IS NOT NULL
