
/*
	
	CREATED BY: DEBBIE ANN CHAVEZ 
	DATE:  8/11/2016
	PULL RETAINED KIDS
	FIRST READ IS DETAILS
	2ND READ IS COUNTS OF RETAINED
	3RD READ IS COUNTS OF ENROLLED

*/

-- DETAILS FOR RETAINED KIDS
SELECT * FROM 
(
SELECT DISTINCT SIS_NUMBER, GRADE, GENDER, HISPANIC_INDICATOR
,CASE WHEN RESOLVED_RACE = 'TWO OR MORE' THEN RACE_1 ELSE RESOLVED_RACE END AS RACE FROM 
(
SELECT MAX(GRADE) AS GRADE, ENR.SIS_NUMBER ,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE  

FROM 
APS.STUDENTENROLLMENTDETAILS AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
WHERE
SCHOOL_YEAR = 2015
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL
AND SUMMER_WITHDRAWL_CODE IS NULL

GROUP BY ENR.SIS_NUMBER,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE 
) AS SCH
) AS SCH1

INNER JOIN 
(SELECT DISTINCT SIS_NUMBER, GRADE, GENDER, HISPANIC_INDICATOR
,CASE WHEN RESOLVED_RACE = 'TWO OR MORE' THEN RACE_1 ELSE RESOLVED_RACE END AS RACE FROM 
(
SELECT MAX(GRADE) AS GRADE, ENR.SIS_NUMBER ,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE  

FROM 
APS.STUDENTENROLLMENTDETAILS AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
WHERE
SCHOOL_YEAR = 2016
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL
AND SUMMER_WITHDRAWL_CODE IS NULL

GROUP BY ENR.SIS_NUMBER,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE 
) AS SCH2
)AS SCH3

ON 
SCH1.SIS_NUMBER = SCH3.SIS_NUMBER
AND SCH1.GRADE = SCH3.GRADE 


/**********************************************************************************************

COUNTS FOR RETAINED BY GRADE, GENDER AND ETHNICITY

***********************************************************************************************/

SELECT 
	SCH1.GRADE 
	,SUM(CASE WHEN SCH1.GENDER = 'M' THEN 1 ELSE 0 END) AS Male
	,SUM(CASE WHEN SCH1.GENDER = 'F' THEN 1 ELSE 0 END) AS Female

	,SUM(CASE WHEN SCH1.RACE = 'African-American' THEN 1 ELSE 0 END) AS African_American
	,SUM(CASE WHEN SCH1.RACE = 'Native American' THEN 1 ELSE 0 END) AS Native_American
	,SUM(CASE WHEN SCH1.RACE = 'Asian' THEN 1 ELSE 0 END) AS Asian
	,SUM(CASE WHEN SCH1.RACE = 'White' THEN 1 ELSE 0 END) AS White
	,SUM(CASE WHEN SCH1.RACE = 'Hispanic' THEN 1 ELSE 0 END) AS Hispanic
	,SUM(CASE WHEN SCH1.RACE = 'Pacific Islander' THEN 1 ELSE 0 END) AS Pacific_Islander

 FROM 

(
SELECT DISTINCT SIS_NUMBER, GRADE, GENDER, HISPANIC_INDICATOR
,CASE WHEN RESOLVED_RACE = 'TWO OR MORE' THEN RACE_1 ELSE RESOLVED_RACE END AS RACE FROM 
(
SELECT MAX(GRADE) AS GRADE, ENR.SIS_NUMBER ,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE  

FROM 
APS.STUDENTENROLLMENTDETAILS AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
WHERE
SCHOOL_YEAR = 2015
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL
AND SUMMER_WITHDRAWL_CODE IS NULL
AND ENR.SIS_NUMBER NOT IN (970078675, 970055481)

GROUP BY ENR.SIS_NUMBER,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE 
) AS SCH
) AS SCH1

INNER HASH JOIN 
(SELECT DISTINCT SIS_NUMBER, GRADE, GENDER, HISPANIC_INDICATOR
,CASE WHEN RESOLVED_RACE = 'TWO OR MORE' THEN RACE_1 ELSE RESOLVED_RACE END AS RACE FROM 
(
SELECT MAX(GRADE) AS GRADE, ENR.SIS_NUMBER ,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE  

FROM 
APS.STUDENTENROLLMENTDETAILS AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
WHERE
SCHOOL_YEAR = 2016
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL
AND SUMMER_WITHDRAWL_CODE IS NULL
AND ENR.SIS_NUMBER NOT IN (970078675, 970055481)

GROUP BY ENR.SIS_NUMBER,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE 
) AS SCH2
)AS SCH3

ON 
SCH1.SIS_NUMBER = SCH3.SIS_NUMBER
AND SCH1.GRADE = SCH3.GRADE 

--) AS T1

GROUP BY SCH1.GRADE  ORDER BY SCH1.GRADE 


/**********************************************************************************************

COUNTS FOR ENROLLED BY GRADE, GENDER AND ETHNICITY

***********************************************************************************************/


SELECT 
	GRADE 
	,SUM(CASE WHEN GENDER = 'M' THEN 1 ELSE 0 END) AS Male
	,SUM(CASE WHEN GENDER = 'F' THEN 1 ELSE 0 END) AS Female

	,SUM(CASE WHEN RACE = 'African-American' THEN 1 ELSE 0 END) AS African_American
	,SUM(CASE WHEN RACE = 'Native American' THEN 1 ELSE 0 END) AS Native_American
	,SUM(CASE WHEN RACE = 'Asian' THEN 1 ELSE 0 END) AS Asian
	,SUM(CASE WHEN RACE = 'White' THEN 1 ELSE 0 END) AS White
	,SUM(CASE WHEN RACE = 'Hispanic' THEN 1 ELSE 0 END) AS Hispanic
	,SUM(CASE WHEN RACE = 'Pacific Islander' THEN 1 ELSE 0 END) AS Pacific_Islander

 FROM (

SELECT DISTINCT SIS_NUMBER, GRADE, GENDER, HISPANIC_INDICATOR
,CASE WHEN RESOLVED_RACE = 'TWO OR MORE' THEN RACE_1 ELSE RESOLVED_RACE END AS RACE FROM 
(
SELECT MAX(GRADE) AS GRADE, ENR.SIS_NUMBER ,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE  

FROM 
APS.STUDENTENROLLMENTDETAILS AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
WHERE
SCHOOL_YEAR = 2016
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL
AND SUMMER_WITHDRAWL_CODE IS NULL
AND ENR.SIS_NUMBER NOT IN (970078675, 970055481)

GROUP BY ENR.SIS_NUMBER,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE 
) AS SCH2

) AS T1

GROUP BY [GRADE]  ORDER BY GRADE 