SELECT SCH3.* FROM 
(
SELECT DISTINCT SIS_NUMBER, GRADE, GENDER, HISPANIC_INDICATOR
,CASE WHEN RESOLVED_RACE = 'TWO OR MORE' THEN RACE_1 ELSE RESOLVED_RACE END AS RACE FROM 
(
SELECT MAX(GRADE) AS GRADE, ENR.SIS_NUMBER ,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE  

FROM 
APS.STUDENTENROLLMENTDETAILS AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
WHERE
SCHOOL_YEAR = 2015
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL
AND SUMMER_WITHDRAWL_CODE IS NULL

GROUP BY ENR.SIS_NUMBER,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE 
) AS SCH
) AS SCH1

INNER JOIN 
(SELECT DISTINCT SIS_NUMBER, GRADE, GENDER, HISPANIC_INDICATOR
,CASE WHEN RESOLVED_RACE = 'TWO OR MORE' THEN RACE_1 ELSE RESOLVED_RACE END AS RACE 
,SCHOOL_NAME, SCHOOL_CODE
FROM 
(
SELECT MAX(GRADE) AS GRADE, ENR.SIS_NUMBER ,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE, ENR.SCHOOL_NAME, SCHOOL_CODE  

FROM 
APS.STUDENTENROLLMENTDETAILS AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
WHERE
SCHOOL_YEAR = 2016
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL
AND SUMMER_WITHDRAWL_CODE IS NULL
AND GRADE IN ('01', '02' ,'03') 

GROUP BY ENR.SIS_NUMBER,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE, SCHOOL_NAME, SCHOOL_CODE 
) AS SCH2
)AS SCH3

ON 
SCH1.SIS_NUMBER = SCH3.SIS_NUMBER
AND SCH1.GRADE = SCH3.GRADE 

ORDER BY SIS_NUMBER

/******************************************************************************************************



*******************************************************************************************************/

SELECT 
	SCH3.GRADE, COUNT(*) AS COUNT_BY_GRADE 
	/*
	,SUM(CASE WHEN SCH1.GENDER = 'M' THEN 1 ELSE 0 END) AS Male
	,SUM(CASE WHEN SCH1.GENDER = 'F' THEN 1 ELSE 0 END) AS Female

	,SUM(CASE WHEN SCH1.RACE = 'African-American' THEN 1 ELSE 0 END) AS African_American
	,SUM(CASE WHEN SCH1.RACE = 'Native American' THEN 1 ELSE 0 END) AS Native_American
	,SUM(CASE WHEN SCH1.RACE = 'Asian' THEN 1 ELSE 0 END) AS Asian
	,SUM(CASE WHEN SCH1.RACE = 'White' THEN 1 ELSE 0 END) AS White
	,SUM(CASE WHEN SCH1.RACE = 'Hispanic' THEN 1 ELSE 0 END) AS Hispanic
	,SUM(CASE WHEN SCH1.RACE = 'Pacific Islander' THEN 1 ELSE 0 END) AS Pacific_Islander
	*/
 FROM 

(
SELECT DISTINCT SIS_NUMBER, GRADE, GENDER, HISPANIC_INDICATOR
,CASE WHEN RESOLVED_RACE = 'TWO OR MORE' THEN RACE_1 ELSE RESOLVED_RACE END AS RACE

 FROM 
(
SELECT MAX(GRADE) AS GRADE, ENR.SIS_NUMBER ,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE

FROM 
APS.STUDENTENROLLMENTDETAILS AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
WHERE
SCHOOL_YEAR = 2015
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL
AND SUMMER_WITHDRAWL_CODE IS NULL
AND ENR.SIS_NUMBER NOT IN (970078675, 970055481)

GROUP BY ENR.SIS_NUMBER,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE 
) AS SCH
) AS SCH1

INNER HASH JOIN 
(SELECT DISTINCT SIS_NUMBER, GRADE, GENDER, HISPANIC_INDICATOR
,CASE WHEN RESOLVED_RACE = 'TWO OR MORE' THEN RACE_1 ELSE RESOLVED_RACE END AS RACE
, SCHOOL_NAME, SCHOOL_CODE
 FROM 
(
SELECT MAX(GRADE) AS GRADE, ENR.SIS_NUMBER ,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE, SCHOOL_NAME, SCHOOL_CODE

FROM 
APS.STUDENTENROLLMENTDETAILS AS ENR
INNER JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU
WHERE
SCHOOL_YEAR = 2016
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL
AND SUMMER_WITHDRAWL_CODE IS NULL
--AND ENR.SIS_NUMBER NOT IN (970078675, 970055481)
AND GRADE IN ('01', '02' ,'03') 

GROUP BY ENR.SIS_NUMBER,GENDER, HISPANIC_INDICATOR, RACE_1, RESOLVED_RACE, SCHOOL_NAME, SCHOOL_CODE 
) AS SCH2
)AS SCH3

ON 
SCH1.SIS_NUMBER = SCH3.SIS_NUMBER
AND SCH1.GRADE = SCH3.GRADE 

--) AS T1

GROUP BY SCH3.GRADE  ORDER BY SCH3.GRADE 
