
/*
*	CREATED BY:  DEBBIE ANN CHAVEZ
*	DATE:  8/7/2014
*
*	THIS PULLS DATA FROM SMAXDBPROD - SYNERGY CONVERSION DATABASE
*
*	Pull HLS data from Schoomax NM030 (did not include '999').  
*  Load into synergy User Defined table UD_HLS_HISTORY where student exists.
*	
*
*/

USE ST_Production
GO

BEGIN TRANSACTION

INSERT INTO rev.UD_HLS_HISTORY

(UDHLS_HISTORY_GU, ADD_DATE_TIME_STAMP, ADD_ID_STAMP, CHANGE_DATE_TIME_STAMP, CHANGE_ID_STAMP, DATE_ASSIGNED, Q1_LANGUAGE_SPOKEN_MOST, Q2_CHILD_FIRST_LANGUAGE
,Q3_LANGUAGES_SPOKEN, Q4_OTHER_LANG_UNDERSTOOD, Q5_OTHER_LANG_COMMUNICATED, STUDENT_GU)

SELECT 
	
	NEWID() AS UDHLS_HISTORY_GU
	,GETDATE() AS ADD_DATE_TIME_STAMP
	,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS ADD_ID_STAMP
	,NULL AS CHANGE_DATE_TIME_STAMP
	,NULL AS CHANGE_ID_STAMP
	,SMAXLANG.DATE_ASSIGNED AS DATE_ASSIGNED
	,SMAXLANG.Q1 AS Q1_LANGUAGE_SPOKEN_MOST
	,SMAXLANG.Q2 AS Q2_CHILD_FIRST_LANGUAGE
	,SMAXLANG.Q3 AS Q3_LANGUAGES_SPOKEN
	,SMAXLANG.Q4 AS Q4_OTHER_LANG_UNDERSTOOD
	,SMAXLANG.Q5 AS Q5_OTHER_LANG_COMMUNICATED
	,Student.STUDENT_GU AS STUDENT_GU
	
FROM
[SMAXDBPROD.APS.EDU.ACTD].[SynergyConversion].dbo.StudentLanguage AS SMAXLANG
INNER JOIN
rev.EPC_STU AS Student
ON
SMAXLANG.SIS_NUMBER = Student.SIS_NUMBER

ROLLBACK


