
/*
*	CREATED BY:  DEBBIE ANN CHAVEZ
*	DATE:  8/7/2014
*
*	THIS PULLS A FILE FOR LYNNE OF STUDENTS THAT DID NOT EXIST IN SYNERGY AND 
*	HLS RECORDS FROM SCHOOLMAX THAT WERE NOT LOADED.
*
*/


SELECT 	
	SMAXLANG.SIS_NUMBER
	,DATE_ASSIGNED	
FROM
[SMAXDBPROD.APS.EDU.ACTD].[SynergyConversion].dbo.StudentLanguage AS SMAXLANG
LEFT JOIN
rev.EPC_STU AS Student
ON
SMAXLANG.SIS_NUMBER = Student.SIS_NUMBER

WHERE
Student.SIS_NUMBER IS NULL