
/*
*	CREATED BY:  DEBBIE ANN CHAVEZ
*	DATE:  8/7/2014
*
*	THIS PULLS THE STUDENT RECORDS FROM THE SYNERGY ELL TABLE:
	1.  MUST HAVE A COMPLETE RECORD ENTERED
	2.  MUST NOT HAVE ANSWERED 15, OR 999 - - 'LANGUAGE SURVEY DECLINED', 'OTHER LANGUAGE'
*	
*  PULL WHERE A SMAX HLS RECORD DOES NOT EXIST - GIVE THIS FILE TO LYNNE TO REVIEW.
*
*	THESE ARE THE "NEWBIES"
*
*/


SELECT * FROM(

SELECT 
		SIS_NUMBER
		   ,HOMELANGUAGE.VALUE_DESCRIPTION AS HOME_LANGUAGE
		   ,HOMELANGUAGE2.VALUE_DESCRIPTION AS LANGUAGE_FIRST_LEARN 
		   ,HOMELANGUAGE3.VALUE_DESCRIPTION AS LANGUAGE_BY_HOME
		   ,HOMELANGUAGE4.VALUE_DESCRIPTION AS LANGUAGE_TO_HOME
		   ,HOMELANGUAGE5.VALUE_DESCRIPTION AS LANGUAGE_BY_ADULT_HOME
		   ,MAX(GRADE.ALT_CODE_1) AS GRADE

FROM

	rev.EPC_STU AS Student		
	LEFT JOIN
	rev.EPC_STU_PGM_ELL AS LANGUAGES
	ON
	LANGUAGES.STUDENT_GU = Student.STUDENT_GU

	LEFT JOIN
	APS.LookupTable ('K12', 'Language')AS HOMELANGUAGE

	ON
	Student.HOME_LANGUAGE = HOMELANGUAGE.VALUE_CODE

	LEFT JOIN
	APS.LookupTable ('K12', 'Language') AS HOMELANGUAGE2

	ON
	LANGUAGES.LANGUAGE_FIRST_LEARN = HOMELANGUAGE2.VALUE_CODE

		LEFT JOIN
	APS.LookupTable ('K12', 'Language')AS HOMELANGUAGE3

	ON
	LANGUAGES.LANGUAGE_BY_HOME = HOMELANGUAGE3.VALUE_CODE

		LEFT JOIN
	APS.LookupTable ('K12', 'Language') AS HOMELANGUAGE4

	ON
	LANGUAGES.LANGUAGE_TO_HOME = HOMELANGUAGE4.VALUE_CODE

	LEFT JOIN
	APS.LookupTable ('K12', 'Language') AS HOMELANGUAGE5
	ON
	LANGUAGES.LANGUAGE_BY_ADULT_HOME = HOMELANGUAGE5.VALUE_CODE

	LEFT JOIN

	rev.UD_UD_HLSHISTORY AS NEWBIES
	ON
	Student.STUDENT_GU = NEWBIES.STUDENT_GU


LEFT JOIN
rev.EPC_STU_SCH_YR AS ENROLL
ON
Student.STUDENT_GU = ENROLL.STUDENT_GU

LEFT JOIN
	APS.LookupTable ('K12', 'Grade') AS GRADE

ON
GRADE.VALUE_CODE = ENROLL.GRADE


WHERE
	NEWBIES.STUDENT_GU IS NULL
	-- MUST HAVE AN ENTIRE RECORD ENTERED
	AND HOME_LANGUAGE IS NOT NULL
	AND LANGUAGE_FIRST_LEARN IS NOT NULL
	AND LANGUAGE_BY_HOME IS NOT NULL
	AND LANGUAGE_TO_HOME IS NOT NULL
	AND LANGUAGE_BY_ADULT_HOME IS NOT NULL

	--MUST NOT HAVE ANY 15 OR 999 VALUES - 'LANGUAGE SURVEY DECLINED', 'OTHER LANGUAGE'
	AND LANGUAGE_FIRST_LEARN NOT IN ('15','999')
	AND LANGUAGE_BY_HOME NOT IN ('15','999')
	AND LANGUAGE_TO_HOME NOT IN ('15','999')
	AND LANGUAGE_BY_ADULT_HOME NOT IN ('15','999')
	
	GROUP BY
		SIS_NUMBER
		   ,HOMELANGUAGE.VALUE_DESCRIPTION 
		   ,HOMELANGUAGE2.VALUE_DESCRIPTION 
		   ,HOMELANGUAGE3.VALUE_DESCRIPTION 
		   ,HOMELANGUAGE4.VALUE_DESCRIPTION 
		   ,HOMELANGUAGE5.VALUE_DESCRIPTION
	   

		   ) AS DONTEXIST

