

/*
*	CREATED BY:  DEBBIE ANN CHAVEZ
*	DATE:  8/7/2014
*
*	DELETE THE ELL RECORDS THAT ARE NOT "NEWBIES"
*	1.  Record already exists in UD_HLS_HISTORY table
*  2.  Record was not bad in synergy - '15', '999', or incomplete
*
*/

BEGIN TRANSACTION

--DELETE rev.EPC_STU_PGM_ELL

SELECT * 
FROM
--START WITH ALL RECORDS IN THE ELL TABLE
rev.EPC_STU_PGM_ELL AS NOTELL
--READ STUDENTS THAT HAVE AN ELL RECORD THAT DID NOT COME FROM SMAX "NEWBIES"
LEFT JOIN
(
SELECT 
		SIS_NUMBER
		   ,HOMELANGUAGE.VALUE_DESCRIPTION AS HOME_LANGUAGE
		   ,HOMELANGUAGE2.VALUE_DESCRIPTION AS LANGUAGE_FIRST_LEARN 
		   ,HOMELANGUAGE3.VALUE_DESCRIPTION AS LANGUAGE_BY_HOME
		   ,HOMELANGUAGE4.VALUE_DESCRIPTION AS LANGUAGE_TO_HOME
		   ,HOMELANGUAGE5.VALUE_DESCRIPTION AS LANGUAGE_BY_ADULT_HOME
		   ,MAX(GRADE.ALT_CODE_1) AS GRADE
		   ,Student.STUDENT_GU
FROM

	rev.EPC_STU AS Student		
	LEFT JOIN
	rev.EPC_STU_PGM_ELL AS LANGUAGES
	ON
	LANGUAGES.STUDENT_GU = Student.STUDENT_GU

	LEFT JOIN
	APS.LookupTable ('K12', 'Language')AS HOMELANGUAGE

	ON
	Student.HOME_LANGUAGE = HOMELANGUAGE.VALUE_CODE

	LEFT JOIN
	APS.LookupTable ('K12', 'Language') AS HOMELANGUAGE2

	ON
	LANGUAGES.LANGUAGE_FIRST_LEARN = HOMELANGUAGE2.VALUE_CODE

		LEFT JOIN
	APS.LookupTable ('K12', 'Language')AS HOMELANGUAGE3

	ON
	LANGUAGES.LANGUAGE_BY_HOME = HOMELANGUAGE3.VALUE_CODE

		LEFT JOIN
	APS.LookupTable ('K12', 'Language') AS HOMELANGUAGE4

	ON
	LANGUAGES.LANGUAGE_TO_HOME = HOMELANGUAGE4.VALUE_CODE

	LEFT JOIN
	APS.LookupTable ('K12', 'Language') AS HOMELANGUAGE5
	ON
	LANGUAGES.LANGUAGE_BY_ADULT_HOME = HOMELANGUAGE5.VALUE_CODE

	LEFT JOIN

	rev.UD_UD_HLSHISTORY AS NEWBIES
	ON
	Student.STUDENT_GU = NEWBIES.STUDENT_GU


LEFT JOIN
rev.EPC_STU_SCH_YR AS ENROLL
ON
Student.STUDENT_GU = ENROLL.STUDENT_GU

LEFT JOIN
	APS.LookupTable ('K12', 'Grade') AS GRADE

ON
GRADE.VALUE_CODE = ENROLL.GRADE


WHERE
	NEWBIES.STUDENT_GU IS NULL
	
		-- MUST HAVE AN ENTIRE RECORD ENTERED - DELETE THESE
	AND HOME_LANGUAGE IS NULL
	AND LANGUAGE_FIRST_LEARN IS NULL
	AND LANGUAGE_BY_HOME IS NULL
	AND LANGUAGE_TO_HOME IS NULL
	AND LANGUAGE_BY_ADULT_HOME IS NULL

	--MUST NOT HAVE ANY 15 OR 999 VALUES - 'LANGUAGE SURVEY DECLINED', 'OTHER LANGUAGE' - DELETE THESE
	AND LANGUAGE_FIRST_LEARN  IN ('15','999')
	AND LANGUAGE_BY_HOME  IN ('15','999')
	AND LANGUAGE_TO_HOME IN ('15','999')
	AND LANGUAGE_BY_ADULT_HOME IN ('15','999')


	GROUP BY
		SIS_NUMBER
		   ,HOMELANGUAGE.VALUE_DESCRIPTION 
		   ,HOMELANGUAGE2.VALUE_DESCRIPTION 
		   ,HOMELANGUAGE3.VALUE_DESCRIPTION 
		   ,HOMELANGUAGE4.VALUE_DESCRIPTION 
		   ,HOMELANGUAGE5.VALUE_DESCRIPTION
			,Student.STUDENT_GU
) AS ELL

ON
ELL.STUDENT_GU = NOTELL.STUDENT_GU

--GIVE ME THE ELL RECORDS THAT ARE NOT THE NEWBIES - DELETE THESE
WHERE
	ELL.STUDENT_GU IS NULL

	
ROLLBACK