/*
*	CREATED BY:  DEBBIE ANN CHAVEZ
*	DATE:  8/7/2014
*
*	LOAD NEWBIES FROM ELL TABLE TO HLS HISTORY TABLE
*	  
*	Only the Newbie records are left in this table (Hopefull Live not currently entering).  Check count.
*/


BEGIN TRANSACTION

INSERT INTO rev.UD_HLS_HISTORY
(UDHLS_HISTORY_GU
, ADD_DATE_TIME_STAMP
, ADD_ID_STAMP
, CHANGE_DATE_TIME_STAMP
, CHANGE_ID_STAMP
, DATE_ASSIGNED
,Q1_LANGUAGE_SPOKEN_MOST
, Q2_CHILD_FIRST_LANGUAGE
, Q3_LANGUAGES_SPOKEN
, Q4_OTHER_LANG_UNDERSTOOD
, Q5_OTHER_LANG_COMMUNICATED
,STUDENT_GU)

SELECT 
	NEWID() AS UD_HLSHISTORY_GU
	,GETDATE() AS ADD_DATE_TIME_STAMP
	,'27CDCD0E-BF93-4071-94B2-5DB792BB735F'  AS ADD_ID_STAMP
	,NULL AS CHANGE_DATE_TIME_STAMP
	,NULL AS CHANGE_ID_STAMP
	,GETDATE() AS DATE_ASSIGNED
	,STUDENT.HOME_LANGUAGE AS Q1_LANGUAGE_SPOKEN_MOST
	,LANGUAGE_FIRST_LEARN AS Q2_CHILD_FIRST_LANGUAGE
	,LANGUAGE_BY_HOME AS Q3_LANGUAGES_SPOKEN
	,LANGUAGE_TO_HOME AS Q4_OTHER_LANG_UNDERSTOOD
	,LANGUAGE_BY_ADULT_HOME AS Q5_OTHER_LANG_COMMUNICATED
	,ELL.STUDENT_GU AS STUDENT_GU
	
FROM
	--GET 4 QUESTIONS
	rev.EPC_STU_PGM_ELL AS ELL
	INNER JOIN
	--GET HOME LANGUAGE
	rev.EPC_STU AS STUDENT
	ON
	ELL.STUDENT_GU = STUDENT.STUDENT_GU

COMMIT