/* Brian Rieb
 * 8/14/2014
 *
 * Removes ALL GPA records for a given year (in where clause)
 */

BEGIN TRANSACTION
/*
SELECT
	SynYear.SCHOOL_YEAR
	,SynYear.EXTENSION
	,Organization.ORGANIZATION_NAME
	,GPA.*
*/
DELETE
	GPA
FROM
	REV.REV_YEAR AS SynYear

	INNER JOIN
	REV.REV_ORGANIZATION_YEAR AS OrgYear
	ON
	SynYear.YEAR_GU = OrgYear.YEAR_GU

	INNER JOIN
	REV.EPC_STU_SCH_YR AS SSY
	ON
	OrgYear.ORGANIZATION_YEAR_GU = SSY.ORGANIZATION_YEAR_GU

	INNER JOIN
	rev.EPC_STU_GPA AS GPA
	ON
	SSY.STUDENT_SCHOOL_YEAR_GU = GPA.STUDENT_SCHOOL_YEAR_GU

	INNER JOIN
	rev.REV_ORGANIZATION AS Organization
	ON
	OrgYear.ORGANIZATION_GU = Organization.ORGANIZATION_GU

WHERE
	SynYear.SCHOOL_YEAR = 2014
	AND SynYear.EXTENSION = 'R'

ROLLBACK
