/* Per Frank the only scores for Istation are for year 2016-2017 */

;with ISTATION_READING
AS
(
SELECT
    LOCAL_SCHOOL_YEAR AS 'School Year'
 
    ,STUDENT_ID AS 'Student APS ID'
    ,TEST_STUDENT_GRADE as 'ISTATION_READING_GRADE'
    ,TEST_PRIMARY_RESULT AS ISTATION_READING_PERFORMANCE_LEVEL
    ,TEST_ADMIN_PERIOD
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_NAME = 'iStation - Reading - Overall - English'
AND LOCAL_SCHOOL_YEAR = '2016-2017'
)
--SELECT * FROM ISTATION_READING

,ISTATION_SPANISH
AS
(
SELECT 
    LOCAL_SCHOOL_YEAR AS 'School Year'
 
    ,STUDENT_ID AS 'Student APS ID'
    ,TEST_STUDENT_GRADE as 'ISTATION_SPANISH_GRADE'
    ,TEST_PRIMARY_RESULT AS ISTATION_SPANISH_PERFORMANCE_LEVEL
    ,TEST_ADMIN_PERIOD
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_NAME = 'iStation - Reading - Overall - Spanish'
AND LOCAL_SCHOOL_YEAR = '2016-2017'
)
--SELECT * FROM ISTATION_SPANISH 

,RESULTSCTE
AS
(
SELECT
	R.[Student APS ID],
	'Reading' as SUBJECT,
	R.ISTATION_READING_GRADE as GRADE,
	R.ISTATION_READING_PERFORMANCE_LEVEL AS PERF_LEVEL,
	R.TEST_ADMIN_PERIOD
FROM
	ISTATION_READING r
union all
select
	s.[Student APS ID],
	'Spanish',
	s.ISTATION_SPANISH_GRADE,
	s.ISTATION_SPANISH_PERFORMANCE_LEVEL,
	s.TEST_ADMIN_PERIOD
from
	istation_spanish S

)
--select * from RESULTSCTE
SELECT * INTO DBO.ISTATION_2016 FROM RESULTScte 

