;with MATH AS
(
SELECT DISTINCT
    SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC MATHEMATICS Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC MATHEMATICS Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'MATHEMATICS'
AND TEST_SUBGROUP = 'OVERALL'
AND LOCAL_SCHOOL_YEAR = '2014-2015'
)
--select * from MATH
,ELA AS
(
SELECT DISTINCT
    SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC ELA Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC ELA Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'ELA'
AND TEST_SUBGROUP = 'OVERALL'
AND LOCAL_SCHOOL_YEAR = '2014-2015'
)
--select * from ela
,RESULTSCTE
AS
(
SELECT

	M.[Student APS ID],
	'Math' as SUBJECT,
	M.[PARCC MATHEMATICS Overall Performance Level] as PERF_LEVEL,
	M.[PARCC MATHEMATICS Scale Score] AS SCALED_SCORE
FROM
	MATH M
union all
select
	E.[Student APS ID],
	'ELA',
	E.[PARCC ELA Overall Performance Level],
	E.[PARCC ELA Scale Score]
from
	ELA E
)
--SELECT * FROM RESULTScte 
SELECT  * INTO DBO.PARCC_ELA_MATH_2014 FROM RESULTSCTE
--where [Student APS ID] is not null
--order by [Student APS ID]
