


SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[COURSES].[COURSE_ID]
	,[COURSES].[COURSE_TITLE]
	,[COURSES].[COURSE_ENTER_DATE]
	,[COURSES].[COURSE_LEAVE_DATE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	
FROM
	(
	SELECT DISTINCT
		[SCHEDULE].[STUDENT_GU]
		,[SCHEDULE].[ORGANIZATION_YEAR_GU]
		,[SCHEDULE].[COURSE_ID]
		,[SCHEDULE].[COURSE_TITLE]
		,[SCHEDULE].[COURSE_ENTER_DATE]
		,[SCHEDULE].[COURSE_LEAVE_DATE]
	FROM
		APS.StudentScheduleDetails AS [SCHEDULE]
		
		INNER JOIN 
		rev.REV_YEAR AS [RevYear] -- Contains the School Year
		ON 
		[SCHEDULE].[YEAR_GU] = [RevYear].[YEAR_GU]
		
	WHERE
		[RevYear].[SCHOOL_YEAR] = '2015'
		AND [RevYear].[EXTENSION] = 'R'
		AND [SCHEDULE].[COURSE_ENTER_DATE] > '08/13/2015'
		--AND [SCHEDULE].[COURSE_ENTER_DATE] = '08/13/2015'
		AND [SCHEDULE].[COURSE_ENTER_DATE] != '01/05/2016'
	) AS [COURSES]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[COURSES].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	APS.StudentEnrollmentDetails AS [ENROLLMENTS]
	ON
	[COURSES].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]
	AND [COURSES].[ORGANIZATION_YEAR_GU] = [ENROLLMENTS].[ORGANIZATION_YEAR_GU]