



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[SCHEDULE].[COURSE_ID]
	,[SCHEDULE].[COURSE_TITLE]
	,[SCHEDULE].[SECTION_ID]
	,[SCHEDULE].[TEACHER NAME]
	,CONVERT(VARCHAR(10),[SCHEDULE].[COURSE_ENTER_DATE],101) AS [COURSE_ENTER_DATE]
	,CONVERT(VARCHAR(10),[SCHEDULE].[COURSE_LEAVE_DATE],101) AS [COURSE_LEAVE_DATE]
	
FROM
	APS.StudentEnrollmentDetails AS [ENROLLMENTS]
	
	INNER JOIN
	APS.StudentScheduleDetails AS [SCHEDULE]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [SCHEDULE].[STUDENT_GU]
	AND [ENROLLMENTS].[ORGANIZATION_YEAR_GU] = [SCHEDULE].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[SCHEDULE].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	--[ENROLLMENTS].[SCHOOL_YEAR] = '2015'
	--AND [ENROLLMENTS].[EXTENSION] = 'R'
	[ENROLLMENTS].[YEAR_GU] = @Year
	AND [ENROLLMENTS].[ORGANIZATION_GU] LIKE @School
	AND [ENROLLMENTS].[LEAVE_DATE] IS NOT NULL
	AND [SCHEDULE].[COURSE_LEAVE_DATE] IS NULL
	