

--EXIT YEAR PROCESS

-------------------------------------------------------------------------------------------------------

--RULES FOR INCREASING EXIT YEAR 1 TO 2'S AND EXIT YEAR 2'S TO 3'S
SELECT 
	SIS_NUMBER, EXIT_DATE, EXIT_REASON, LU.VALUE_DESCRIPTION AS EXIT_DESCRIPTION
FROM 
rev.EPC_STU_PGM_ELL AS ELL
INNER JOIN
rev.EPC_STU AS STU
ON
ELL.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
	APS.LOOKUPTABLE ('K12.ProgramInfo', 'ELL_EXIT_REASON') AS LU
ON
LU.VALUE_CODE = ELL.EXIT_REASON

WHERE 

EXIT_DATE IS NOT NULL

ORDER BY EXIT_REASON, EXIT_DATE

-----------------------------------------------------------------------------------------------------
--RULES FOR EXIT YEAR 1 STUDENTS

SELECT SIS_NUMBER, VALUE_DESCRIPTION AS GRADE, TEST_NAME, PERFORMANCE_LEVEL, ADMIN_DATE  FROM 
APS.LCELatestEvaluationAsOf('2015-07-01') AS LCE
INNER JOIN
rev.EPC_STU AS STU
ON
LCE.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
APS.LookupTable ('K12', 'Grade') AS LU
ON
LU.VALUE_CODE = LCE.GRADE

WHERE
TEST_NAME = 'ACCESS'
AND PERFORMANCE_LEVEL IN ('ADV','BRIDG', 'FEP', 'REACH','C-PRO')

ORDER BY ORGANIZATION_NAME, SIS_NUMBER