
/*
BEGIN TRANSACTION
DELETE 
rev.EPC_STAFF_SCH_YR
WHERE
STAFF_SCHOOL_YEAR_GU = 'ED7F72CA-BB42-4EB3-8789-08B688BB2A30'
ROLLBACK
*/

SELECT 
STFYR.STAFF_SCHOOL_YEAR_GU,
PERS.LAST_NAME, PERS.FIRST_NAME, ORGANIZATION_NAME, YRS.SCHOOL_YEAR,STFYR.STAFF_GU, STFYR.ADD_ID_STAMP, STFYR.ADD_DATE_TIME_STAMP  ,STFYR.CHANGE_ID_STAMP

 FROM 
	rev.EPC_STAFF_SCH_YR AS STFYR
	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS ORGYR
	ON
	STFYR.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
	INNER JOIN 
	rev.EPC_STAFF AS STF
	ON
	STF.STAFF_GU = STFYR.STAFF_GU
	INNER JOIN 
	rev.REV_ORGANIZATION AS ORG
	ON
	ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
	INNER JOIN 
	rev.REV_YEAR AS YRS
	ON
	ORGYR.YEAR_GU = YRS.YEAR_GU
	INNER JOIN 
	rev.REV_PERSON AS PERS
	ON
	PERS.PERSON_GU = STF.STAFF_GU

	WHERE
	SCHOOL_YEAR = 2016
	AND STF.BADGE_NUM = 'e118143'