EXECUTE AS LOGIN='QueryFileUser'
GO

with TESTCTE
AS
(
SELECT 
	ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
	--,PERSON.FIRST_NAME
	--,PERSON.LAST_NAME
	,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
	,TEST.TEST_NAME
	,STU_PART.PERFORMANCE_LEVEL AS PL
	,SCORES.TEST_SCORE
	,STUDENTTEST.ADMIN_DATE
FROM
	
	rev.EPC_STU_TEST AS StudentTest

	JOIN
	rev.EPC_TEST_PART AS PART
	ON StudentTest.TEST_GU = PART.TEST_GU

	JOIN
	rev.EPC_STU_TEST_PART AS STU_PART
	ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
	AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

	INNER JOIN
	rev.EPC_STU_TEST_PART_SCORE AS SCORES
	ON
	SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

	LEFT JOIN
	rev.EPC_TEST_SCORE_TYPE AS SCORET
	ON
	SCORET.TEST_GU = StudentTest.TEST_GU
	AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

	LEFT JOIN
	rev.EPC_TEST_DEF_SCORE AS SCORETDEF
	ON
	SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

	LEFT JOIN
	rev.EPC_TEST AS TEST
	ON TEST.TEST_GU = StudentTest.TEST_GU

	INNER JOIN
	rev.EPC_STU AS Student
	ON Student.STUDENT_GU = StudentTest.STUDENT_GU

	--INNER JOIN
	--rev.REV_PERSON AS Person
	--ON Person.PERSON_GU = StudentTest.STUDENT_GU

	LEFT JOIN
	APS.PrimaryEnrollmentsAsOf('2017-05-22') AS Enroll
	ON
	StudentTest.STUDENT_GU = Enroll.STUDENT_GU

	LEFT JOIN
	rev.REV_ORGANIZATION_YEAR AS OrgYear
	ON
	Enroll.ORGANIZATION_YEAR_GU = OrgYear.ORGANIZATION_YEAR_GU

	LEFT JOIN
	rev.REV_ORGANIZATION AS Org
	ON
	OrgYear.ORGANIZATION_GU = Org.ORGANIZATION_GU

	LEFT JOIN
	APS.LookupTable('K12','Grade') AS GradeLevel
	ON
	Enroll.GRADE = GradeLevel.VALUE_CODE


WHERE
1 = 1
	--AND TEST_NAME = 'WAPT'
	AND TEST.TEST_NAME LIKE '%WAPT%'
	AND SCORE_DESCRIPTION IN ('Overall LP')
	--AND LAST_NAME LIKE '%IBRAHIMU'

)
--SELECT * FROM TESTCTE
	SELECT
	 T1.[Student Last Name] as	STUDENT_LAST_NAME, 
	 T1.[Student First Name] AS STUDENT_FIRST_NAME,
	 T1.APS_ID AS STUDENT_APS_ID,
	 t.TEST_NAME,
	 t.PL,
	 t.TEST_SCORE,
	 t.ADMIN_DATE

	 --ROWNUM, FIRSTNAME, LASTNAME, SISNUMBER, TESTNAME,  PERFLEVEL, TESTSCORE, ADMINDATE           
FROM
	OPENROWSET (
		'Microsoft.ACE.OLEDB.12.0', 
		'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
		'SELECT * from Lutheran_Family_Services_2016.csv'
                ) AS [T1]

INNER JOIN
	APS.BasicStudentWithMoreInfo BS
	ON T1.aps_id = BS.SIS_NUMBER
LEFT JOIN
	TESTCTE T
	ON T.SIS_NUMBER = T1.APS_id
ORDER BY
	T1.aps_id
	REVERT
	GO