DECLARE @AsOfDate DATETIME  = GETDATE()




SELECT
	ZONE
	,SCHOOL_NAME
	,GRADE
	,HERITAGE_1_HOUR_EL
	,HERITAGE_1_HOUR_NEL
	,HERITAGE_1_HOUR_EL + HERITAGE_1_HOUR_NEL AS HERITAGE_1_TOTAL
	,HERITAGE_2_HOUR_EL
	,HERITAGE_2_HOUR_NEL
	,HERITAGE_2_HOUR_EL + HERITAGE_2_HOUR_NEL AS HERITAGE_2_TOTAL
	,HERITAGE_3_HOUR_EL
	,HERITAGE_3_HOUR_NEL
	,HERITAGE_3_HOUR_EL + HERITAGE_3_HOUR_NEL AS HERITAGE_3_TOTAL
	,DUAL_EL
	,DUAL_NEL
	,DUAL_EL + DUAL_NEL AS DUAL_TOTAL
	,VALUE_CODE
FROM
(
SELECT
	ZONE
	,SCHOOL_NAME
	,GRADE
	,SUM (HERITAGE_1_HOUR_EL) AS HERITAGE_1_HOUR_EL
	,SUM (HERITAGE_1_HOUR_NEL) AS HERITAGE_1_HOUR_NEL
	,SUM (HERITAGE_2_HOUR_EL) AS HERITAGE_2_HOUR_EL
	,SUM (HERITAGE_2_HOUR_NEL) AS HERITAGE_2_HOUR_NEL
	,SUM (HERITAGE_3_HOUR_EL) AS HERITAGE_3_HOUR_EL
	,SUM (HERITAGE_3_HOUR_NEL) AS HERITAGE_3_HOUR_NEL
	,SUM (DUAL_EL) AS DUAL_EL
	,SUM (DUAL_NEL) AS DUAL_NEL
	,VALUE_CODE
FROM
(
SELECT-- DISTINCT MODEL.SCHOOL_NAME, ORG.ORGANIZATION_NAME
	SCH.ALT_ID AS ZONE
	,MODEL.SCHOOL_NAME
	,EY.GRADE
	,EY.LEAVE_CODE
	,GR.VALUE_CODE
	,CASE WHEN MODEL.EL = 'Y' AND MODEL.[HOUR] = 1 AND MODEL = 'Heritage/Indigenous Language' THEN 1 ELSE 0
	END AS HERITAGE_1_HOUR_EL
	,CASE WHEN MODEL.EL = 'N' AND MODEL.[HOUR] = 1 AND MODEL = 'Heritage/Indigenous Language' THEN 1 ELSE 0
	END AS HERITAGE_1_HOUR_NEL
	,CASE WHEN MODEL.EL = 'Y' AND MODEL.[HOUR] = 2 AND MODEL = 'Heritage/Indigenous Language' THEN 1 ELSE 0
	END AS HERITAGE_2_HOUR_EL
	,CASE WHEN MODEL.EL = 'N' AND MODEL.[HOUR] = 2 AND MODEL = 'Heritage/Indigenous Language' THEN 1 ELSE 0
	END AS HERITAGE_2_HOUR_NEL
	,CASE WHEN MODEL.EL = 'Y' AND MODEL.[HOUR] = 3 AND MODEL = 'Heritage/Indigenous Language' THEN 1 ELSE 0
	END AS HERITAGE_3_HOUR_EL
	,CASE WHEN MODEL.EL = 'N' AND MODEL.[HOUR] = 3 AND MODEL = 'Heritage/Indigenous Language' THEN 1 ELSE 0
	END AS HERITAGE_3_HOUR_NEL
	,CASE WHEN MODEL.EL = 'Y' AND MODEL = '2-Way Dual' THEN 1 ELSE 0
	END AS DUAL_EL
	,CASE WHEN MODEL.EL = 'N' AND MODEL = '2-Way Dual' THEN 1 ELSE 0
	END AS DUAL_NEL
FROM 
	APS.NewBEPStudentsModelsAndHoursAsOf (@AsOfDate) MODEL
	JOIN
		APS.LatestPrimaryEnrollmentInYear('A3F9F1FB-4706-49AA-B3A3-21F153966191') EY
		ON MODEL.SIS_NUMBER = EY.SIS_NUMBER
	LEFT JOIN
		REV.REV_ORGANIZATION ORG
		ON ORG.ORGANIZATION_NAME = MODEL.SCHOOL_NAME
	JOIN
		REV.EPC_SCH SCH
		ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU
	JOIN
	rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') GR
	ON GR.VALUE_DESCRIPTION = EY.GRADE
) T1
GROUP BY
	ZONE
	,SCHOOL_NAME
	,GRADE
	,VALUE_CODE
) SUMS
ORDER BY
	SCHOOL_NAME, VALUE_CODE