USE [SchoolNet]
GO

UPDATE
	dbo.STUDENT_COURSES
SET
	ELEM_TEACHER = ST.[ELEMENTARY_COURSE]
	,ELA_TEACHER = ST.ELA
	,MATH_TEACHER = ST.MATH
	,SCIENCE_TEACHER = ST.SCIENCE

--SELECT [ID_NUMBER]
--      ,[ELEMENTARY_COURSE]
--      ,[ELA]
--      ,[MATH]
--      ,[SCIENCE]
--      ,[ELEM_TEACHER]
--      ,[ELA_TEACHER]
--      ,[MATH_TEACHER]
--      ,[SCIENCE_TEACHER]
  FROM [dbo].[STUDENT_COURSES] SC
  JOIN
	dbo.STUDENT_TEACHERS ST
	ON SC.ID_NUMBER = ST.ID_NUMBER
GO


