--declare @ASSESSMENT_NAME varchar(100) = '2015-2016 Senior Retakes EOC ELA III Reading 9 12 V006'
SELECT --- distinct testname
	'001' AS [DISTRICT CODE]
	,'EOC' AS [TEST DESCRIPTION]
	,'2016-06-30' [ASSESSMENT SCHOOL YEAR DATE]
	,LTRIM(RTRIM(STARS_NAME)) AS [ITEM DESCRIPTION CODE]
	,ASSESSMENT_TEST_DATE AS [TEST DATE]
	,STUDENTID AS [STUDENT ID]
	,'' AS [LOCATION CODE]
	,NUMBER_CORRECT AS [RAW SCORE]


	
FROM
(       
select  stu.LASTNAME+', ' +stu.FIRSTNAME STUDENT_NAME
	   ,stu.STUDENTID
       ,t.TESTNAME
	   --,cs.STARS_NAME
       ,convert(date,convert(varchar(11),min(r.RESPONSEDATE))) TEST_DATE
       , SUM(case when r.CORRECT=1 then 1 else 0 end) as NUMBER_CORRECT
       , SUM(case when r.CORRECT=0 then 1 else 0 end) as NUMBER_INCORRECT
       , COUNT(r.id) as NUMBER_OF_QUESTIONS
       ,convert(decimal(6,1), SUM(case when r.CORRECT=1 then 1.0 else 0.0 end) / COUNT(r.ID)*100.0,1) PCT_CORRECT
from EGB_TEST t
       join EGB_TEST_SCHEDULED sch on sch.TESTID = t.id
       join EGB_TEST_STUDENTRESPONSES r on r.SCHEDULEDTESTID = sch.ID 
       join EGB_TEST_STUDENTS ts on ts.STUDENTID = r.STUDENTID and ts.SCHEDULEDTESTID = sch.ID
       join .EGB_PEOPLE stu on stu.ID = r.STUDENTID
where ts.COMPLETEDATE is not null
and t.TESTNAME LIKE '%EOC%'
	--AND T.TESTNAME LIKE '%WRITING%'
--AND T.TESTNAME LIKE '%SPRING%'

--AND CS.ASSESSMENT_ID BETWEEN 1001 AND 1086
--AND STU.STUDENTID = '104306162'
group by stu.LASTNAME+', ' +stu.FIRSTNAME, stu.STUDENTID 
       ,t.TESTNAME 

) AS EOC
LEFT JOIN
[RDAVM.APS.EDU.ACTD].ASSESSMENTS.DBO.EOC_CUT_SCORES AS CS
ON EOC.TESTNAME = CS.ASSESSMENT_NAME

WHERE 1 = 1
--AND CS.CUT_SCORE < '1'
--AND CS.ASSESSMENT_NAME = '2015-2016 Senior Retakes EOC Algebra I 7 12 V003'
--AND CS.STARS_NAME = 'Algebra I 7 12 V003'
--AND CS.STARS_NAME = 'ALGEBRA II 9 12 V006'
--AND CS.STARS_NAME = 'ANATOMY AND PHYSIOLOGY 9 12 V002'
--AND CS.STARS_NAME = 'Biology 9 12 V007'
--AND CS.STARS_NAME = 'Chemistry 9 12 V008'
--AND CS.STARS_NAME = 'Economics 9 12 V004'
--AND CS.STARS_NAME = 'ELA III READING 9 12 V006'
--AND CS.STARS_NAME = 'ELA IV READING 9 12 V003'
--AND CS.STARS_NAME = 'ENGLISH III WRITING 9 12 V006'  --- Don't load Senior Retakes or Winter
--or CS.STARS_NAME = 'ENGLISH IV WRITING 9 12 V003'	--- Don't load Senior Retakes or Winter
--AND CS.STARS_NAME = 'ENVIRONMENTAL SCIENCE 9 12 V001'
AND CS.STARS_NAME = 'Financial Literacy 9 12 V003'
--AND CS.STARS_NAME = 'Geometry 9 12 V003'
--or CS.STARS_NAME = 'HEALTH 9 12 V002'
----AND CS.STARS_NAME = 'KEYBOARDING 6 8 V003'
--AND CS.STARS_NAME = 'NEW MEXICO HISTORY 9 12 V004'
----AND CS.STARS_NAME = 'PHYSICAL EDUCATION 9 12 V002'
--AND CS.STARS_NAME = 'Physics 9 12 V003'
--AND CS.STARS_NAME = 'Pre-Calculus 9 12 V004'
or CS.STARS_NAME = 'SPANISH 1 9 12 V003'
or CS.STARS_NAME = 'Spanish I 7 12 V003'
or cs.assessment_name = '2015-2016 Spring EOC Physical Education 9 12 V002 '
--AND CS.STARS_NAME = 'Spanish Language Arts III Writing 9 12 V001'
--AND CS.STARS_NAME = 'US Government Comprehensive 9 12 V005'
--AND CS.STARS_NAME = 'US History 9 12 V007'
--AND CS.STARS_NAME = 'Spanish Language Arts III Reading 9 12 V001'
--AND CS.STARS_NAME = 'World History And Geography 9 12 V003'
--AND (TESTNAME LIKE '%SENIOR RETAKES%' OR TESTNAME LIKE '%WINTER%')
--and STUDENT_NAME = 'abbott, dominic'
--and cs.assessment_test_date = '04/01/2016'
--AND STUDENT_NAME = 'CORDOVA, MIGUEL'
--AND TESTNAME NOT IN ('2015-2016 Senior Retakes EOC English III Writing 9 12 V006','')


ORDER BY TESTNAME

