USE [Assessments]
GO
SELECT
	  [AGAID]
      ,[schnumb]
      ,[schnumborig]
      ,[distcode]
      ,[schcode]
      ,[schname]
      ,[schtype]
      ,[StudentID]
	  ,student_code
      ,[Gender]
      ,[Ethnicity]
      ,[EverELL]
      ,[EverIEP]
      ,[FRLX]
      ,[MIGRANTX]
      ,[DUALX]
      ,[snapsch]
      ,[snaptot]
      ,[Outcome]
      ,[gradcode]
      ,[Out]
      ,[graduated]
      ,[ALLSTU]
      ,[WHITE]
      ,[BLACK]
      ,[HISPANIC]
      ,[ASIAN]
      ,[NATIVE]
      ,[FEMALE]
      ,[MALE]
      ,[FRL]
      ,[SWD]
      ,[ELL]
      ,[MIGRANT]
      ,[DUAL]
      ,[CERTIF]
      ,[STILL]
      ,[DROP]
      ,[EXIT]
      ,[DISTNAME]
      ,[SCHWEIGHT]
      ,[SCHNUM]
      ,[SCHDENOM]
      ,[snapdist]
      ,[DISTWEIGHT]
      ,[DISTNUM]
      ,[DISTDENOM]
      ,[filter_$]
      ,[PrimaryLast]
	  ,CASE WHEN ACC.[TEST_SCORE] IS NULL THEN '' ELSE ACC.[TEST_SCORE] END AS 'ACCESS OVERALL PL'
FROM
(
SELECT
	  RN
	  ,[AGAID]
      ,[schnumb]
      ,[schnumborig]
      ,[distcode]
      ,[schcode]
      ,[schname]
      ,[schtype]
      ,[StudentID]
	  ,student_code
      ,[Gender]
      ,[Ethnicity]
      ,[EverELL]
      ,[EverIEP]
      ,[FRLX]
      ,[MIGRANTX]
      ,[DUALX]
      ,[snapsch]
      ,[snaptot]
      ,[Outcome]
      ,[gradcode]
      ,[Out]
      ,[graduated]
      ,[ALLSTU]
      ,[WHITE]
      ,[BLACK]
      ,[HISPANIC]
      ,[ASIAN]
      ,[NATIVE]
      ,[FEMALE]
      ,[MALE]
      ,[FRL]
      ,[SWD]
      ,[ELL]
      ,[MIGRANT]
      ,[DUAL]
      ,[CERTIF]
      ,[STILL]
      ,[DROP]
      ,[EXIT]
      ,[DISTNAME]
      ,[SCHWEIGHT]
      ,[SCHNUM]
      ,[SCHDENOM]
      ,[snapdist]
      ,[DISTWEIGHT]
      ,[DISTNUM]
      ,[DISTDENOM]
      ,[filter_$]
      ,[PrimaryLast]
FROM
(
SELECT 
	  ROW_NUMBER () OVER (PARTITION BY [StudentID] ORDER BY [StudentID] DESC) AS RN
	  ,[AGAID]
      ,[schnumb]
      ,[schnumborig]
      ,[distcode]
      ,[schcode]
      ,[schname]
      ,[schtype]
      ,[StudentID]
	  ,STUD.student_code
      ,[Gender]
      ,[Ethnicity]
      ,[EverELL]
      ,[EverIEP]
      ,[FRLX]
      ,[MIGRANTX]
      ,[DUALX]
      ,[snapsch]
      ,[snaptot]
      ,[Outcome]
      ,[gradcode]
      ,[Out]
      ,[graduated]
      ,[ALLSTU]
      ,[WHITE]
      ,[BLACK]
      ,[HISPANIC]
      ,[ASIAN]
      ,[NATIVE]
      ,[FEMALE]
      ,[MALE]
      ,[FRL]
      ,[SWD]
      ,[ELL]
      ,[MIGRANT]
      ,[DUAL]
      ,[CERTIF]
      ,[STILL]
      ,[DROP]
      ,[EXIT]
      ,[DISTNAME]
      ,[SCHWEIGHT]
      ,[SCHNUM]
      ,[SCHDENOM]
      ,[snapdist]
      ,[DISTWEIGHT]
      ,[DISTNUM]
      ,[DISTDENOM]
      ,[filter_$]
      ,[PrimaryLast]
  FROM [dbo].[TRASH_APS_w_Offsites] OFFS
  LEFT JOIN
  allstudents_ALL AS STUD
  ON OFFS.StudentID = STUD.state_id
) AS T1


WHERE RN = 1
--ORDER BY StudentID
)AS T2

LEFT JOIN
TRASH_ACCESS_SCORES AS ACC
ON ACC.SIS_NUMBER = student_code
AND ACC.SCORE_DESCRIPTION = 'Overall LP'

--WHERE ACC.SCORE_DESCRIPTION = 'Overall LP'
GO


