BEGIN TRAN

USE Assessments
GO

    
TRUNCATE  TABLE [CCR_FOR_STARS]
INSERT INTO [CCR_FOR_STARS]

SELECT
	[DISTRICT CODE]
	,[TEST DESCRIPTION]
	,[ASSESSMENT SCHOOL YEAR DATE]
	,[ITEM DESCRITPION CODE]
	,[TEST DATE]
	,[STUDENT ID]
	,CASE	
		WHEN [LOCATION CODE] IS NULL THEN school_code
		ELSE [LOCATION CODE]
    END AS [LOCATION CODE]	
    ,[RAW SCORE]
FROM
(
SELECT
	'001' AS [DISTRICT CODE]
	,'ACT' AS [TEST DESCRIPTION]
	,'2015-06-30' AS [ASSESSMENT SCHOOL YEAR DATE]
	,CASE WHEN test_section_name = 'MATHEMATICS' THEN 'MATH'
		  ELSE UPPER(Test_section_name)
	END AS  [ITEM DESCRITPION CODE]
	,test_date_code AS [TEST DATE]
	,STUD.[STUDENT ID] AS 'STUDENT ID'
	,SSN.STATE_SCH AS [LOCATION CODE]
	,scaled_score AS [RAW SCORE]
	,ACT.school_code
FROM
	test_result_ACT AS ACT
	LEFT JOIN
	[046-WS02].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	ON
	ACT.student_code = STUD.[ALTERNATE STUDENT ID]
	
	LEFT JOIN
	[State School Number] AS SSN
	ON 
	ACT.school_code = SSN.SCH_NBR
WHERE
	test_section_name IN ('READING','MATHEMATICS','SCIENCE','ENGLISH')
	AND stud.SY = '2015'
	AND (ACT.school_code > '500' OR ACT.school_code = '048')
	AND STUD.[DISTRICT CODE] = '001'
	AND STUD.PERIOD = '2015-03-01'
	--AND (STUD.[STATE_ID] > '1')
) AS ACT
ORDER BY [STUDENT ID]


ROLLBACK
