SELECT
	DISTINCT LTRIM (PARTS.HAPPY_ADDY) + ' ' + LTRIM (PARTS.POBOX) + ' ' + LTRIM (PARTS.STR_TAG) + ' ' + LTRIM (PARTS.STR_DIR) + ' ' + LTRIM (PARTS.CITY) + ' ' + LTRIM (PARTS.[STATE]) + ' ' + LTRIM (PARTS.ZIP) AS ADDRESS_HOME
	,PARTS.HSE_NBR
	,PARTS.STR_NME
	,PARTS.POBOX
	,PARTS.HAPPY_ADDY
FROM	
(
SELECT
	CASE
	WHEN DWELLING.HSE_NBR != '' AND DWELLING.STR_NME LIKE 'PO %' THEN  '' 
	WHEN DWELLING.HSE_NBR = '' AND (DWELLING.STR_NME NOT LIKE 'PO %')  THEN '' 
	ELSE DWELLING.HSE_NBR
	END AS HAPPY_ADDY
	,DWELLING.HSE_NBR
	,DWELLING.STR_NME
	,CASE
	WHEN DWELLING.STR_NME LIKE 'PO %' 
		THEN ('P.O.' + ' '+ SUBSTRING(DWELLING.STR_NME, 3,9)) 
	--WHEN DWELLING.STR_NME LIKE 'PO %' AND DWELLING.HSE_NBR != '' 
		--THEN DWELLING.HSE_NBR = 'TOM'	
		ELSE DWELLING.STR_NME
		END AS POBOX
	,CASE
	WHEN DWELLING.HSE_NBR = '' AND (DWELLING.STR_NME NOT LIKE 'PO %')  THEN 'HEY THERE' ELSE DWELLING.HSE_NBR END AS HSE_NBR_2
	,DWELLING.STR_TAG
	,DWELLING.STR_DIR
	,DWELLING.CITY
	,DWELLING.[STATE]
	,LEFT (DWELLING.ZIP_CD, 5) AS ZIP

	
FROM
	DBTSIS.CE005_V AS DWELLING
--WHERE DWELLING.STR_NME LIKE 'PO%'	

) AS PARTS

--WHERE PARTS.STR_NME LIKE 'PO %'
ORDER BY HSE_NBR