BEGIN TRAN

SELECT
	S_Id
	,STUDENT.ID_NBR AS fld_ID_NBR
	,STUDENT.STATE_ID AS fld_STATE_ID
	,STUDENT.LST_NME AS fld_LST_NME
	,STUDENT.FRST_NME AS fld_FRST_NME
	,STUDENT.M_NME AS fld_M_NME
	,STUDENT.BRTH_DT AS fld_BRTH_DT
	,STUDENT.GENDER AS fld_GENDER
	,CASE
		WHEN FRPL = 'Free Lunch' THEN 'F'
		WHEN FRPL = 'Non-Participant' THEN 'N'
		WHEN FRPL = 'Reduced Lunch' THEN 'R'
		WHEN FRPL = 'Priority 2' THEN '2'
		ELSE FRPL
		END
	AS fld_LNCH_FLG
	,ENROLLMENT.GRDE
	,ENROLLMENT.SCH_NBR
	
FROM
	PR.APS.BasicStudent	AS STUDENT
	LEFT JOIN
	PR.APS.PrimaryEnrollmentsAsOf (GETDATE()) AS ENROLLMENT
	ON
	STUDENT.ID_NBR = ENROLLMENT.ID_NBR
ROLLBACK