
SELECT
	FIRST_NAME
	,LAST_NAME
	,BIRTH_DATE
	,GENDER
	,RESOLVED_RACE
	,HISPANIC_INDICATOR
	,LUNCH_STATUS
	,HIGH_SCHOOL
	,SCHOOL_CODE
	,T1.SIS_NUMBER
	,AP_NUMBER
	,T2.TEST_NAME
	,COURSE_TITLE
	,TERM_CODE
	,T2.TEST_SCORE AP_EXAM_GRADE
	,MARK
	,TEACHER_NAME
	,BADGE_NUM
FROM
(
SELECT 
	BS.FIRST_NAME
	,BS.LAST_NAME	
	,BS.BIRTH_DATE
	,BS.GENDER
	,BS.RESOLVED_RACE
	,BS.HISPANIC_INDICATOR
	,BS.LUNCH_STATUS
	,ORG.ORGANIZATION_NAME HIGH_SCHOOL
	,SCH.SCHOOL_CODE
	,BS.SIS_NUMBER
	,'' AP_NUMBER
	,CASE WHEN CRS.COURSE_TITLE = 'AP ART HISTORY' THEN 'AP Art History'
		  WHEN CRS.COURSE_TITLE = 'AP BIOLOGY' THEN 'AP Biology'
		  WHEN CRS.COURSE_TITLE = 'AP CALC AB' THEN 'AP Calculus BC'
		  WHEN CRS.COURSE_TITLE = 'AP CALC BC' THEN 'AP Caluclus AB'
		  WHEN CRS.COURSE_TITLE = 'AP CHEMISTRY' THEN 'AP Chemistry'
		  WHEN CRS.COURSE_TITLE = 'AP CHINESE' THEN 'AP Chinese Language and Culture'
		  WHEN CRS.COURSE_TITLE = 'AP COMP SCI A' THEN 'AP Computer Science A'
		  WHEN CRS.COURSE_TITLE = 'AP ECON SEM' THEN 'AP Macroeconomics'
		  WHEN CRS.COURSE_TITLE = 'AP ECON SEM' THEN 'AP Microeconomics'
		  WHEN CRS.COURSE_TITLE = 'AP ENGLITCOMP11' OR CRS.COURSE_TITLE = 'AP ENGLITCOMP12' THEN 'AP English Literature And Composition'
		  WHEN CRS.COURSE_TITLE = 'AP ENGLNGCOMP11' OR CRS.COURSE_TITLE = 'AP ENGLNGCOMP12' OR CRS.COURSE_TITLE = 'APENGLNGCOMP11' THEN 'AP English Language and Composition'
		  WHEN CRS.COURSE_TITLE = 'AP ENVRN SCI' THEN 'AP Environmental Science'
		  WHEN CRS.COURSE_TITLE = 'AP EUROPEAN HST' THEN 'AP European History'
		  WHEN CRS.COURSE_TITLE = 'AP FRENCH V' THEN 'AP French Language'
		  WHEN CRS.COURSE_TITLE = 'AP JAPANESE' THEN 'AP Japanese Language And Culture'
		  WHEN CRS.COURSE_TITLE = 'AP MUSIC THEORY' THEN 'AP Music Theory'
		  WHEN CRS.COURSE_TITLE = 'AP PHYSICS B' THEN 'AP Physics C Electricity and Magnetism'
		  WHEN CRS.COURSE_TITLE = 'AP PHYSICS C' THEN 'AP Physics C Mechanics'
		  WHEN CRS.COURSE_TITLE = 'AP PHYSICS I' THEN 'AP Physics 1 Algebra based'
		  WHEN CRS.COURSE_TITLE = 'AP PHYSICS II' THEN 'AP Physics 2 Algebra Based'
		  WHEN CRS.COURSE_TITLE = 'AP PSYCHOLOGY' THEN 'AP Psychology'
		  WHEN CRS.COURSE_TITLE = 'AP RESEARCH' OR CRS.COURSE_TITLE = 'AP RESEARCH ENG 12' THEN 'AP Research'
		  WHEN CRS.COURSE_TITLE = 'AP SEMINAR' THEN 'AP Seminar'
		  WHEN CRS.COURSE_TITLE = 'AP SPAN V LIT' THEN 'AP Spanish Literature'
		  WHEN CRS.COURSE_TITLE = 'AP SPAN V LNG' THEN 'AP Spanish Language'
		  WHEN CRS.COURSE_TITLE = 'AP STATISTICS' THEN 'AP Statistics'
		  WHEN CRS.COURSE_TITLE = 'AP STUDIO ART' THEN 'AP Studio Art Drawing'
		  WHEN CRS.COURSE_TITLE = 'AP STUDIO ART2D' THEN 'AP Studio Art: 2-D Design'
		  WHEN CRS.COURSE_TITLE = 'AP STUDIO ART3D' THEN 'AP Studio Art: 3-D Design'
		  WHEN CRS.COURSE_TITLE = 'AP US GOV/POL' THEN 'AP Government and Politics: United States'
		  WHEN CRS.COURSE_TITLE = 'AP US HIST/GEO' OR CRS.COURSE_TITLE = 'AP US HIST/GEO  BIL' OR CRS.COURSE_TITLE = 'AP US HIST/GEO BIL' THEN 'AP US History'
		  WHEN CRS.COURSE_TITLE = 'AP W HIST/GEOG' OR CRS.COURSE_TITLE = 'AP W HIST/GEOG BIL' THEN 'AP World History'
		  WHEN CRS.COURSE_TITLE = '' THEN ''
		  WHEN CRS.COURSE_TITLE = '' THEN ''
		  WHEN CRS.COURSE_TITLE = '' THEN ''
	END AS TEST_NAME
	,CRS.COURSE_TITLE
	,CRH.TERM_CODE
	,'' AP_EXAM_GRADE
	,CRH.MARK
	,CRH.TEACHER_NAME
	,STAFF.BADGE_NUM

FROM rev.EPC_STU_CRS_HIS CRH
JOIN 
REV.EPC_STU STU
ON STU.STUDENT_GU = CRH.STUDENT_GU

JOIN REV.EPC_CRS CRS
ON CRS.COURSE_GU = CRH.COURSE_GU


JOIN REV.EPC_SCH_YR_SECT SECT
ON SECT.SECTION_GU = CRH.SECTION_GU

JOIN APS.SectionsAndAllStaffAssigned SA
ON SA.SECTION_GU = SECT.SECTION_GU

JOIN REV.EPC_STAFF STAFF
ON STAFF.STAFF_GU = SA.STAFF_GU

JOIN APS.BasicStudentWithMoreInfo BS
ON BS.STUDENT_GU = CRH.STUDENT_GU

JOIN REV.REV_ORGANIZATION_YEAR ORGY
ON ORGY.ORGANIZATION_YEAR_GU = SECT.ORGANIZATION_YEAR_GU

JOIN REV.REV_ORGANIZATION ORG
ON ORG.ORGANIZATION_GU = ORGY.ORGANIZATION_GU

JOIN REV.EPC_SCH SCH
ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU



WHERE 1 = 1
--AND STU.SIS_NUMBER = '100502996' 
AND SCHOOL_YEAR = '2016'
AND CRS.AP_INDICATOR = 'Y'

) T1

LEFT JOIN
(
SELECT 
       SIS_NUMBER
	   ,TEST.TEST_NAME
       ,SCORE_DESCRIPTION
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
	   AND TEST_NAME LIKE 'AP %'
	   AND ADMIN_DATE = '2017-05-01 00:00:00' 
) AS T2
ON T2.SIS_NUMBER = T1.SIS_NUMBER
AND T2.TEST_NAME = T1.TEST_NAME

ORDER BY SIS_NUMBER, COURSE_TITLE, TERM_CODE