USE Assessments
GO

BEGIN TRAN
      
--INSERT INTO [CCR_FOR_STARS]
SELECT
	[DISTRICT CODE]
	,[TEST DESCRIPTION]
	,[ASSESSMENT SCHOOL YEAR DATE]
	,[ITEM DESCRITPION CODE]
	,[TEST DATE]
	,[STUDENT ID]
	,[LOCATION CODE]
	,[RAW SCORE]
FROM
(
SELECT
	
	ROW_NUMBER () OVER (PARTITION BY [student_code], [test_section_name], [test_date_code] ORDER BY [school_code]) AS RN
	,'001' AS [DISTRICT CODE]
	,'AP' AS [TEST DESCRIPTION]
	,'2015-06-30' AS [ASSESSMENT SCHOOL YEAR DATE]
	,CASE 
		WHEN test_section_name = 'FRENCH LANGUAGE AND CULTURE' THEN 'FRENCH LANGUAGE'
		WHEN test_section_name = 'GERMAN LANGUAGE AND CULTURE' THEN 'GERMAN LANGUAGE'
		WHEN test_section_name = 'SPANISH LANGUAGE AND CULTURE' THEN 'SPANISH LANGUAGE'
		WHEN test_section_name = 'SPANISH LITERATURE AND CULTURE' THEN 'SPANISH LITERATURE'
		WHEN test_section_name = 'STUDIO ART: 2-D DESIGN PORTFOLIO' THEN 'STUDIO ART: 2-D DESIGN'
		WHEN test_section_name = 'STUDIO ART: 3-D DESIGN PORTFOLIO' THEN 'STUDIO ART: 3-D DESIGN'
		WHEN test_section_name = 'STUDIO ART: DRAWING PORTFOLIO' THEN 'STUDIO ART: DRAWING'
		WHEN test_section_name = 'UNITED STATES GOVERNMENT AND POLITICS' THEN 'GOVERNMENT AND POLITICS: UNITED STATES'
		WHEN test_section_name = 'UNITED STATES HISTORY' THEN 'US HISTORY'
		ELSE UPPER (test_section_name) 
	END AS [ITEM DESCRITPION CODE]
	,test_date_code AS [TEST DATE]
	,STUD.[STUDENT ID] AS 'STUDENT ID'
	,CASE WHEN SSN.STATE_SCH IS NULL THEN [LOCATION CODE] ELSE SSN.STATE_SCH
	END AS [LOCATION CODE]
	,scaled_score AS [RAW SCORE]
FROM
	test_result_AP AS AP
	-- LEFT JOIN
	--allstudents_ALL AS STUD
	--ON
	--AP.student_code = STUD.student_code
	--AND STUD.school_year = '2014'
	--AND AP.school_code != '533'
	LEFT JOIN
	[046-WS02].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	ON
	AP.student_code = STUD.[ALTERNATE STUDENT ID]
	AND STUD.SY = '2015'
	AND STUD.Period = '2015-06-01'
		
	LEFT JOIN
	[State School Number] AS SSN
	ON 
	AP.school_code = SSN.SCH_NBR
WHERE STUD.[STUDENT ID] IS NOT NULL
AND test_section_name NOT LIKE '%SUBSCORE'
AND test_section_name != 'PHYSICS 1'
AND test_section_name != 'SEMINAR'
--AND AP.school_code > '500' OR AP.school_code = '048'
--AND [STUDENT ID] = '970062057'
) AS T1
WHERE [LOCATION CODE] IS NOT NULL
AND RN = 1
ORDER BY [ITEM DESCRITPION CODE]

ROLLBACK
