
BEGIN TRAN

UPDATE
	CCR
SET
	CCR.STID = STUDENT.[STUDENT ID]
   ,CCR.[APS_ID_2] = STUDENT.[ALTERNATE STUDENT ID]	
   ,CCR.DOB = STUDENT.BIRTHDATE
	
--SELECT
--	STUDENT.[ALTERNATE STUDENT ID]
--	,STUDENT.[STUDENT ID]
--	,CCR.F_Name
--	,CCR.L_Name
--	,CCR.DOB_NEW
--	,STUDENT.BIRTHDATE
--	,STUDENT.Period
FROM
	[180-SMAXODS-01].SchoolNet.dbo.CCR_PLAN AS CCR
	
LEFT JOIN
	[046-WS02].[db_STARS_History].[dbo].[STUDENT] AS STUDENT
	ON
	--CCR.APS_ID = STUDENT.[ALTERNATE STUDENT ID]
	STUDENT.[LAST NAME LONG] = CCR.LName
	AND STUDENT.[FIRST NAME LONG] = CCR.FName
	--AND STUDENT.BIRTHDATE = SUBSTRING (CCR.DOB,1,4) + '-' + SUBSTRING (CCR.DOB, 5,2) + '-' + SUBSTRING (CCR.DOB, 7,2)
	--AND CCR.APS_ID IS NULL
	--STUDENT.[LAST NAME LONG] = CCR.L_Name
	--AND STUDENT.[FIRST NAME LONG] = CCR.F_Name
	--AND STUDENT.[BIRTHDATE] = SUBSTRING (DOB_NEW,1,4)+'-'+ SUBSTRING (DOB_NEW, 5,2)+'-'+ SUBSTRING (DOB_NEW, 7,2)
	--AND STUDENT.[SY] = 2012
	--AND STUDENT.[CURRENT GRADE LEVEL] = CCR.test_level_name
	--AND STUDENT.Period = '2013-06-01'
WHERE	
	--CCR.[School Year] = '2013-2014'
	STUDENT.SY = '2014'
	AND (CCR.APS_ID_2 IS NULL AND CCR.STID IS NULL)
	

ROLLBACK
