USE Assessments
GO

BEGIN TRAN

--INSERT INTO [CCR_FOR_STARS]


SELECT
	[DISTRICT CODE]
	,[TEST DESCRIPTION]
	,[ASSESSMENT SCHOOL YEAR DATE]
	,[ITEM DESCRIPTION CODE]
	,[TEST DATE]
	,[STUDENT ID]
	--,student_code
	,[LOCATION CODE]
	,[RAW SCORE]
FROM
(
SELECT 
		ROW_NUMBER () OVER (PARTITION BY CCR.STUDENT_CODE, CCR.TEST_SECTION_NAME, CCR.TEST_DATE_CODE, CCR.SCALED_SCORE ORDER BY CCR.STUDENT_CODE, CCR.TEST_SECTION_NAME, CCR.TEST_DATE_CODE, CCR.SCALED_SCORE, STUD.PERIOD DESC) AS RN
	   ,'001' AS 'DISTRICT CODE'
	   ,'PSAT' AS 'TEST DESCRIPTION'
	   ,'2015-06-30' AS 'ASSESSMENT SCHOOL YEAR DATE'
	   ,CASE	
			WHEN CCR.test_section_name = 'CRITICAL READING' THEN 'CRITICAL READING'
			WHEN CCR.test_section_name = 'MATHEMATICS' THEN 'MATH'
			WHEN CCR.test_section_name = 'WRITING' THEN 'WRITING'
		END AS 'ITEM DESCRIPTION CODE'
	   --,SUBSTRING ([test_date_code],6,2)+'/'+ SUBSTRING ([test_date_code],9,2) +'/' + SUBSTRING ([test_date_code], 1,4) AS 'TEST DATE'
	   ,SUBSTRING ([test_date_code],1,4)+'-'+SUBSTRING([TEST_DATE_CODE],6,2) + '-' + SUBSTRING([TEST_DATE_CODE],9,2) AS 'TEST DATE'
	   ,STUD.[STUDENT ID] AS 'STUDENT ID'
	   --,student_code
      --,[ID Number] AS 'STUDENT ALTERNATE ID'
	  --,School AS 'APS LOCATION CODES'
	  ,CASE WHEN CCR.school_code IS NULL OR CCR.school_code = '' THEN STUD.[LOCATION CODE] ELSE CCR.school_code
	  END AS 'LOCATION CODE'
	  ,scaled_score AS 'RAW SCORE'
	  ,student_code
  FROM [test_result_PSAT] AS CCR
 -- LEFT JOIN
	--SMAXDBPROD.[PR].[DBTSIS].[CE020_V] AS STUD
	--ON
	--CCR.student_code = STUD.[ID_NBR]

  LEFT JOIN
	[046-WS02].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	ON
	CAST (LTRIM(RTRIM(CCR.student_code)) AS VARCHAR (50)) = LTRIM(RTRIM(STUD.[ALTERNATE STUDENT ID]))
	AND STUD.PERIOD = '2015-06-01'
	AND STUD.SY = '2015'
	--LEFT JOIN
	--[180-SMAXODS-01].SCHOOLNET.DBO.[State School Number] AS SSN
	--ON 
	--CCR.school_code = SSN.SCH_NBR
	--WHERE CCR.[ID Number] != 'NULL'
	
	WHERE test_section_name IN ('CRITICAL READING','MATHEMATICS','WRITING')
AND CCR.[school_year] = '2014'
AND CCR.scaled_score > '1'
) AS T1
WHERE
[STUDENT ID] IS NOT NULL
AND RN = 1
--AND ([LOCATION CODE] = '048' OR [LOCATION CODE] > '150')
ORDER BY [LOCATION CODE]

ROLLBACK