USE [Assessments]
GO

SELECT
	  [DISTRICT CODE]
      ,[TEST DESCRIPTION]
      ,[ASSESSMENT SCHOOL YEAR DATE]
      ,CASE	
			WHEN STARS IS NOT NULL THEN STARS
			ELSE [ITEM DESCRIPTION CODE]
      END AS [ITEM DESCRIPTION CODE]
      ,[TEST DATE]
      ,[STUDENT ID]
      ,[LOCATION CODE]
      ,[RAW SCORE]
FROM
(

SELECT
	   ROW_NUMBER () OVER (PARTITION BY [STUDENT ID],[TEST DESCRIPTION], [ITEM DESCRIPTION CODE], [TEST DATE], [LOCATION CODE], [RAW SCORE] ORDER BY [ASSESSMENT SCHOOL YEAR DATE]) AS RN
	  ,[DISTRICT CODE]
      ,[TEST DESCRIPTION]
      ,[ASSESSMENT SCHOOL YEAR DATE]
      ,[ITEM DESCRIPTION CODE]
      ,[TEST DATE]
      ,[STUDENT ID]
      ,[LOCATION CODE]
      ,[RAW SCORE]
	  ,CS.STARS_name_V2 AS STARS
  FROM [dbo].[CCR_FOR_STARS] AS CCR
  LEFT JOIN 
  EoC_Cut_Scores AS CS
  ON CCR.[ITEM DESCRIPTION CODE] = CS.STARS_name
  --AND CCR.[TEST DESCRIPTION] = 'EOC'
) AS NEW
WHERE RN = 1

ORDER BY [ITEM DESCRIPTION CODE]
GO


