BEGIN TRAN

UPDATE
	CCR_ACT
SET
	--SchoolNet.dbo.CCR_ACT.[APS_Sch_Code] = STUDENT.[LOCATION CODE]
	CCR_ACT.APS_ID = STUDENT.[ALTERNATE STUDENT ID]
	,CCR_ACT.State_ID = STUDENT.[STUDENT ID]
	,[Assessment School Year Date] = '2015-6-30'
	,[Test Description] = 'ACT'
	

	
--SELECT
--	STUDENT.[ALTERNATE STUDENT ID]
--	,STUDENT.[STUDENT ID]
--	,ACT.F_Name
--	,ACT.L_Name
--	,ACT.DOB_NEW
--	,STUDENT.BIRTHDATE
--	,STUDENT.Period
FROM
	CCR_ACT AS ACT
	
LEFT JOIN
	[046-WS02].[db_STARS_History].[dbo].[STUDENT] AS STUDENT
	ON
	ACT.L_Name = STUDENT.[LAST NAME LONG]
	AND ACT.F_Name = STUDENT.[FIRST NAME LONG]
	--AND ACT.APS_Sch_Code = STUDENT.[LOCATION CODE]
	--AND ACT.MI = STUDENT.[MIDDLE INITIAL]
	--AND ACT.Grade = STUDENT.[CURRENT GRADE LEVEL]
	AND STUDENT.[BIRTHDATE] = SUBSTRING (DOB_NEW,1,4)+'-'+ SUBSTRING (DOB_NEW, 5,2)+'-'+ SUBSTRING (DOB_NEW, 7,2)
	--LTRIM (RTRIM (STUDENT.[LAST NAME LONG])) = LTRIM (RTRIM (IAAT.Lastname))
	--AND LTRIM (RTRIM (STUDENT.[FIRST NAME LONG])) = LTRIM (RTRIM (IAAT.Firstname))
	----AND LTRIM (RTRIM (STUDENT.[MIDDLE INITIAL])) = LTRIM (RTRIM (CCR.MI))
	--AND STUDENT.[BIRTHDATE] = SUBSTRING (DOB_NEW,1,4)+'-'+ SUBSTRING (DOB_NEW, 5,2)+'-'+ SUBSTRING (DOB_NEW, 7,2)
	--AND STUDENT.[SY] = 2012
	--AND STUDENT.[CURRENT GRADE LEVEL] = CCR.Grade
	AND STUDENT.SY = '2015'
	--AND STUDENT.[DISTRICT CODE] = '001'
WHERE ACT.APS_ID IS NULL
AND ACT.SCH_YR = '2014-2015'
--AND ACT.[District Code] = 'FRANK'
--AND STUDENT.[DISTRICT CODE] = '001'
AND ACT.APS_ID IS NULL

--2014-03-01

