


UPDATE
	[180-SMAXODS-01].SchoolNet.dbo.CCR_PSAT
SET
	SchoolNet.dbo.CCR_PSAT.[State_ID] = STUDENT.[STUDENT ID]
   ,SchoolNet.dbo.CCR_PSAT.[APS_ID] = STUDENT.[ALTERNATE STUDENT ID]
   --,SchoolNet.dbo.CCR_PSAT.[APS Sch Code] = STUDENT.[LOCATION CODE]	
   ,SchoolNet.dbo.CCR_PSAT.[DOB] = STUDENT.[BIRTHDATE]	
   ,SchoolNet.dbo.CCR_PSAT.TEST = 'PSAT'
   --,SCHOOLnET.DBO.CCR_PSAT.Grade = STUDENT.[CURRENT GRADE LEVEL]
 

	
--SELECT
--	STUDENT.[ALTERNATE STUDENT ID]
--	,STUDENT.[STUDENT ID]
--	,CCR.FirstName
--	,CCR.LastName
--	,ccr.DOB
--	,SUBSTRING (CCR.DOB_orig,7,4) + '-' + SUBSTRING (CCR.DOB_orig, 1,2) + '-' + SUBSTRING (CCR.DOB_orig, 4,2) AS DOB
--	,STUDENT.BIRTHDATE
--	,STUDENT.Period
FROM
	[180-SMAXODS-01].SchoolNet.dbo.CCR_PSAT AS CCR
	
INNER JOIN
	[046-WS02].[db_STARS_History].[dbo].[STUDENT] AS STUDENT
	ON
	--CCR.APS_ID = STUDENT.[ALTERNATE STUDENT ID]
	 STUDENT.[LAST NAME LONG] = REPLACE (LTRIM(RTRIM(CCR.LastName)),' ','')
	--AND STUDENT.[FIRST NAME LONG] = REPLACE(LTRIM(RTRIM(CCR.FirstName)),' ','')
	AND STUDENT.[MIDDLE INITIAL] = LTRIM(RTRIM(CCR.MI))
	AND CCR.GRADE != 'NO RESPONSE   '
	AND CCR.GRADE != 'OTHER         '
	AND student.[current grade level] != 'KF'
	AND student.[current grade level] != 'PK'
AND RIGHT('0'+CCR.Grade,2) = (STUDENT.[CURRENT GRADE LEVEL] + 1)
	--STUDENT.[ALTERNATE STUDENT ID] = CCR.LocalID1
	AND STUDENT.BIRTHDATE = SUBSTRING (CCR.DOB_orig,7,4) + '-' + SUBSTRING (CCR.DOB_orig, 1,2) + '-' + SUBSTRING (CCR.DOB_orig, 4,2)
	--STUDENT.[LAST NAME LONG] = CCR.L_Name
	--AND STUDENT.[FIRST NAME LONG] = CCR.F_Name
	--AND STUDENT.[BIRTHDATE] = SUBSTRING (DOB,1,4)+'-'+ SUBSTRING (DOB, 5,2)+'-'+ SUBSTRING (DOB, 7,2)
	--AND STUDENT.[SY] = '2012'
	--AND CCR.APS_ID = 0
	--AND STUDENT.[CURRENT GRADE LEVEL] = CCR.Grade
	--AND STUDENT.Period = '2012-06-01'
WHERE	
STUDENT.SY = '2014'
--AND STUDENT.[DISTRICT CODE] = '001'
--AND
AND CCR.SCH_YR = '2014-2015'
AND CCR.APS_ID IS NULL

