
SELECT
	[DISTRICT CODE]
	,[TEST DESCRIPTION]
	,[ASSESSMENT SCHOOL YEAR DATE]
	,[ITEM DESCRIPTION CODE]
	,[TEST DATE]
	,[STUDENT ID]
	,[LOCATION CODE]
	,[RAW SCORE]
FROM
(
SELECT 
		ROW_NUMBER () OVER (PARTITION BY CCR.STUDENT_CODE, CCR.TEST_SECTION_NAME, CCR.TEST_DATE_CODE, CCR.SCALED_SCORE ORDER BY CCR.STUDENT_CODE, CCR.TEST_SECTION_NAME, CCR.TEST_DATE_CODE, CCR.SCALED_SCORE, STUD.PERIOD DESC) AS RN
	   ,'1' AS 'DISTRICT CODE'
	   ,'ACT' AS 'TEST DESCRIPTION'
	   ,'6/30/2014' AS 'ASSESSMENT SCHOOL YEAR DATE'
	   ,CASE	
			WHEN CCR.test_section_name = 'English' THEN 'ENGLISH'
			WHEN CCR.test_section_name = 'READING' THEN 'READING'
			WHEN CCR.test_section_name = 'SCIENCE' THEN 'SCIENCE'
			WHEN CCR.test_section_name = 'MATHEMATICS' THEN 'MATH'
		END AS 'ITEM DESCRIPTION CODE'
	   ,SUBSTRING ([test_date_code],6,2)+'/'+ SUBSTRING ([test_date_code],9,2) +'/' + SUBSTRING ([test_date_code], 1,4) AS 'TEST DATE'
	   ,STUD.[STUDENT ID] AS 'STUDENT ID'
	   --,student_code
      --,[ID Number] AS 'STUDENT ALTERNATE ID'
	  --,School AS 'APS LOCATION CODES'
	  ,CASE WHEN CCR.school_code IS NULL OR CCR.school_code = '' THEN STUD.[LOCATION CODE] ELSE CCR.school_code
	  END AS 'LOCATION CODE'
	  ,RIGHT ('0'+ scaled_score,2) AS 'RAW SCORE'
  FROM [180-SMAXODS-01].[SchoolNet].[dbo].[test_result_ACT] AS CCR
 -- LEFT JOIN
	--SMAXDBPROD.[PR].[DBTSIS].[CE020_V] AS STUD
	--ON
	--CCR.student_code = STUD.[ID_NBR]

  LEFT JOIN
	[046-WS02].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	ON
	CAST (LTRIM(RTRIM(CCR.student_code)) AS VARCHAR (50)) = LTRIM(RTRIM(STUD.[ALTERNATE STUDENT ID]))
	--AND STUD.PERIOD = '2014-06-01'
	AND STUD.SY = '2014'
	--LEFT JOIN
	--[180-SMAXODS-01].SCHOOLNET.DBO.[State School Number] AS SSN
	--ON 
	--CCR.school_code = SSN.SCH_NBR
	--WHERE CCR.[ID Number] != 'NULL'
	
	WHERE test_section_name IN ('MATH','Science','Reading','English','MATHEMATICS')
AND CCR.[school_year] = '2013'
) AS T1
WHERE
[STUDENT ID] IS NOT NULL
AND RN = 1
AND [RAW SCORE] != '--'
--AND [STUDENT ID] = '100111905'
ORDER BY [ASSESSMENT SCHOOL YEAR DATE]
