BEGIN TRAN


UPDATE
	[180-SMAXODS-01].SchoolNet.dbo.CCR_AP
SET
	SchoolNet.dbo.CCR_AP.[State_ID] = STUDENT.[STUDENT ID]

FROM
	[SchoolNet].[dbo].[CCR_AP] AS CCR
	
INNER JOIN
	[046-WS02].[db_STARS_History].[dbo].[STUDENT] AS STUDENT
	ON
	STUDENT.[ALTERNATE STUDENT ID] = CCR.APS_ID
	
WHERE	
--CCR.SCH_YR = '2012-2013'
CCR.STATE_ID = '' OR CCR.State_ID IS NULL
	
	

ROLLBACK
