

UPDATE
	[180-SMAXODS-01].SchoolNet.dbo.IAAT
SET
	SchoolNet.dbo.IAAT.[School Code] = STUDENT.[LOCATION CODE]

	
--SELECT
--	STUDENT.[ALTERNATE STUDENT ID]
--	,STUDENT.[STUDENT ID]
--	,CCR.F_Name
--	,CCR.L_Name
--	,CCR.DOB_NEW
--	,STUDENT.BIRTHDATE
--	,STUDENT.Period
FROM
	[180-SMAXODS-01].SchoolNet.dbo.IAAT AS IAAT
	
LEFT JOIN
	[046-WS02].[db_STARS_History].[dbo].[STUDENT] AS STUDENT
	ON
	IAAT.[Student ID] = STUDENT.[ALTERNATE STUDENT ID]
	--LTRIM (RTRIM (STUDENT.[LAST NAME LONG])) = LTRIM (RTRIM (IAAT.Lastname))
	--AND LTRIM (RTRIM (STUDENT.[FIRST NAME LONG])) = LTRIM (RTRIM (IAAT.Firstname))
	----AND LTRIM (RTRIM (STUDENT.[MIDDLE INITIAL])) = LTRIM (RTRIM (CCR.MI))
	--AND STUDENT.[BIRTHDATE] = SUBSTRING (DOB_NEW,1,4)+'-'+ SUBSTRING (DOB_NEW, 5,2)+'-'+ SUBSTRING (DOB_NEW, 7,2)
	--AND STUDENT.[SY] = 2012
	--AND STUDENT.[CURRENT GRADE LEVEL] = CCR.Grade
	--AND STUDENT.Period = '2013-06-01'
WHERE	

--CCR.SCH_YR = '2013-2014'
--AND CCR.APS_ID IS NULL
STUDENT.SY = 2014
AND IAAT.[School Code] = '' OR IAAT.[School Code] IS NULL
	
