

UPDATE
	[180-SMAXODS-01].[SchoolNet].[dbo].[IAAT]
SET
	--SchoolNet.dbo.CCR_ACT.[APS_Sch_Code] = STUDENT.[LOCATION CODE]
	[SchoolNet].[dbo].[IAAT].[School Code] = STUDENT.[LOCATION CODE]
	--SchoolNet.dbo.CCR_ACCESS.[State Student ID] = STUDENT.[STUDENT ID]
	--,[Assessment School Year Date] = '2013-6-30'
	--,[Test Description] = 'ACT'
	

	
--SELECT
--	STUDENT.[ALTERNATE STUDENT ID]
--	,STUDENT.[STUDENT ID]
--	,CCR.F_Name
--	,CCR.L_Name
--	,CCR.DOB_NEW
--	,STUDENT.BIRTHDATE
--	,STUDENT.Period
FROM
	[180-SMAXODS-01].[SchoolNet].[dbo].[IAAT] AS IAAT
	
LEFT JOIN
	[046-WS02].[db_STARS_History].[dbo].[STUDENT] AS STUDENT
	ON
	IAAT.[Student ID]= STUDENT.[ALTERNATE STUDENT ID]
	--AND ACCESS.F_Name = STUDENT.[FIRST NAME LONG]
	--AND ACCESS.MI = STUDENT.[MIDDLE INITIAL]
	--AND ACT.Grade = STUDENT.[CURRENT GRADE LEVEL]
	--AND STUDENT.[BIRTHDATE] = SUBSTRING (DOB_NEW,1,4)+'-'+ SUBSTRING (DOB_NEW, 5,2)+'-'+ SUBSTRING (DOB_NEW, 7,2)
	--LTRIM (RTRIM (STUDENT.[LAST NAME LONG])) = LTRIM (RTRIM (IAAT.Lastname))
	--AND LTRIM (RTRIM (STUDENT.[FIRST NAME LONG])) = LTRIM (RTRIM (IAAT.Firstname))
	----AND LTRIM (RTRIM (STUDENT.[MIDDLE INITIAL])) = LTRIM (RTRIM (CCR.MI))
	--AND STUDENT.[BIRTHDATE] = SUBSTRING (DOB_NEW,1,4)+'-'+ SUBSTRING (DOB_NEW, 5,2)+'-'+ SUBSTRING (DOB_NEW, 7,2)
	--AND STUDENT.[SY] = 2012
	--AND STUDENT.[CURRENT GRADE LEVEL] = CCR.Grade
	AND STUDENT.SY = '2014'
WHERE IAAT.[School Code] IS NULL OR IAAT.[School Code] = ''



