USE
Assessments
GO

BEGIN TRAN


UPDATE
	CCR_SAT
SET
	[State_ID] = STUDENT.[STUDENT ID]
   ,[APS_ID] = STUDENT.[ALTERNATE STUDENT ID]	
   ,CCR_SAT.DOB = STUDENT.BIRTHDATE
   --,SchoolNet.dbo.CCR_SAT.LOCATION_CODE = STUDENT.[LOCATION CODE]
   ,CCR_SAT.TEST_DESCRIPTION = 'SAT'
   ,CCR_SAT.ASSESSMENT_SCHOOL_YEAR_DATE = '2015'
   --,SchoolNet.dbo.CCR_SAT.DOB = STUDENT.[BIRTHDATE]
   --,SchoolNet.dbo.CCR_SAT.DISTRICT_CODE = '001'
	
--SELECT
--	STUDENT.[ALTERNATE STUDENT ID]
--	,STUDENT.[STUDENT ID]
--	,CCR.F_Name
--	,CCR.L_Name
--	,CCR.DOB
--	,STUDENT.BIRTHDATE
--	,CCR.DOB_old
--	,STUDENT.Period
--	,STUDENT.[LOCATION CODE]
FROM
	CCR_SAT AS CCR
	
LEFT JOIN
	[046-WS02].[db_STARS_History].[dbo].[STUDENT] AS STUDENT
	ON
	RTRIM(LTRIM(STUDENT.[LAST NAME LONG])) = CCR.L_Name
	AND RTRIM(LTRIM(STUDENT.[FIRST NAME LONG])) = CCR.F_Name
	--AND STUDENT.[MIDDLE INITIAL] = CCR.MI
	AND STUDENT.BIRTHDATE = '19' + SUBSTRING (CCR.DOB_old,5,2) + '-' + SUBSTRING (CCR.DOB_old, 1,2) + '-' + SUBSTRING (CCR.DOB_old, 3,2)
	--AND CCR.SCH_YR IS NULL
	--AND STUDENT.[SY] = 2014
	--AND CCR.SCH_YR = '2013-2014'
	--AND STUDENT.[CURRENT GRADE LEVEL] = CCR.Grade
	--AND STUDENT.Period = '2013-12-15'
	AND STUDENT.SY = '2015'
WHERE	
	CCR.SCH_YR = '2014-2015'
	--AND CCR.DISTRICT_CODE = 'FRANK'
	AND CCR.APS_ID IS NULL
----	
ROLLBACK

