
--/*
BEGIN TRANSACTION
USE MASTER
GO
INSERT INTO [046-WS02].[db_Logon].[dbo].[Class_Lists] (ID_NBR, EMP_NBR, SCH_NBR, DATE_CREATE, CRS_ASG)
--*/

SELECT
	ID_NBR
	,EMP_NBR
	,SCH_NBR
	,DATE_CREATE
	,CRS_ASG
FROM    
(
SELECT
	ROW_NUMBER () OVER (PARTITION BY ID_NBR, EMP_NBR, COURSE  ORDER BY SCH_NBR)AS RN
    ,CAST (ID_NBR AS INT) AS ID_NBR
	,CAST (EMP_NBR AS INT) AS EMP_NBR
	,CAST (SCH_NBR AS INT) AS SCH_NBR
	,COURSE AS CRS_ASG
	,CONVERT (VARCHAR (55), GETDATE (),113) AS DATE_CREATE
FROM
	PR.APS.CurrentScheduleWithMoreInfo 
WHERE
	 EMP_NBR IS NOT NULL AND DST_NBR = 1
) AS ROWS
WHERE RN = '1' AND EMP_NBR != 777777777
ORDER BY ID_NBR

COMMIT

