SELECT
	  NEW.[State Abbreviation]
      ,NEW.[Testing District]
      ,NEW.[Testing School]
      ,NEW.[Responsible District Identifier]
      ,NEW.[School Institution Identifier]
      ,NEW.[State Student Identifier]
      ,NEW.[Local Student Identifier]
      ,NEW.[PARCC Student ID]
      ,NEW.[Last or Surname]
      ,NEW.[First Name]
      ,NEW.[Middle Name]
      ,NEW.[Birthdate]
      ,NEW.[Sex]
      ,NEW.[Optional State Data 1]
      ,NEW.[Grade Level When Assessed]
      ,NEW.[Hispanic or Latino Ethnicity]
      ,NEW.[American Indian or Alaska Native]
      ,NEW.[Asian]
      ,NEW.[Black or African American]
      ,NEW.[Native Hawaiian or Other Pacific Islander]
      ,NEW.[White]
      ,NEW.[English Learner  (EL)]
      ,NEW.[Title III Limited English Proficient Participation Status]
      ,NEW.[Gifted and Talented]
      ,NEW.[Migrant Status]
      ,NEW.[Economic Disadvantage Status]
      ,NEW.[Student With Disabilities ]
      ,NEW.[Primary Disability Type]
      ,NEW.[Optional State Data 2]
      ,NEW.[Optional State Data 3]
      ,NEW.[Optional State Data 4]
      ,NEW.[Optional State Data 5]
      ,NEW.[Optional State Data 6]
      ,NEW.[Optional State Data 7]
      ,NEW.[Optional State Data 8]
      ,NEW.[Assessment Session Location]
      ,NEW.[Assessment Session Test Administrator Identifier]
      ,NEW.[Classroom Identifier]
      ,NEW.[Staff Member Identifier]
      ,NEW.[Test Code]
      ,NEW.[Test Format ]
      ,NEW.[Retest]
      ,NEW.[Assessment Accommodation   English learner (EL)]
      ,NEW.[Assessment Accommodation  504 ]
      ,NEW.[Assessment Accommodation  Individualized Educational Plan (IEP)]
      ,NEW.[Alternate Representation - Paper Test]
      ,NEW.[Translation of the Mathematics Assessment in Paper]
      ,NEW.[Human Reader or Human Signer]
      ,NEW.[Large Print]
      ,NEW.[Braille with Tactile Graphics]
      ,NEW.[End of Record]
      ,NEW.[Column 51]
FROM
	[TRASH_Student Registration Export 2015-02-06T22_25_10.059+0000] AS STUD
RIGHT JOIN
	[TRASH_New Student Registration - Completed] AS NEW
	ON NEW.[State Student Identifier] = STUD.[State Student Identifier]
WHERE
	STUD.[State Student Identifier] IS NULL