SELECT
	DCT.[Student ID]
	,DCT.[2014-2015  Withdrawal Type] DCT_WD
	,PROD.[2014-2015  Withdrawal Type] PROD_WD
FROM
	AHS_CURRENT_ENROLLMENTS_DCT DCT
	LEFT JOIN
	AHS_CURRENT_ENROLLMENTS_PROD PROD
	ON DCT.[Student ID] = PROD.[Student ID]
ORDER BY PROD.[2014-2015  Withdrawal Type]