BEGIN TRAN
SELECT
(
SELECT
	COUNT (CAST(NOT_SERVED.ID_NBR AS DECIMAL(3,2))) AS NO_SERVICES
FROM
	APS.LCEStudentsAndProvidersAsOf (GETDATE()) AS NOT_SERVED
WHERE
	NOT_SERVED.DST_NBR = 1
	AND NOT_SERVED.COURSE IS NULL
	AND NOT_SERVED.PARENT_REFUSAL = 'N'
)
/
(
SELECT
	COUNT (CAST(ELL.ID_NBR AS DECIMAL(5,2))) AS ELL_STUDENTS
FROM
	APS.ELLStudentsAsOf	(GETDATE())AS ELL
)	
AS RESULT


				
	

ROLLBACK