

; WITH 
-- From Student School Year [EPC_STU_SCH_YR]
SSY_ENROLLMENTS AS
(
SELECT
	[StudentSchoolYear].[STUDENT_GU]
	,[StudentSchoolYear].[ORGANIZATION_YEAR_GU]
	,[Organization].[ORGANIZATION_GU]
	,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
	,[School].[SCHOOL_CODE]
	,[Organization].[ORGANIZATION_NAME] AS [SCHOOL_NAME]
	,[StudentSchoolYear].[ENTER_DATE]
	,[StudentSchoolYear].[LEAVE_DATE]
	,[StudentSchoolYear].[EXCLUDE_ADA_ADM]
	,[RevYear].[SCHOOL_YEAR]
	,[RevYear].[EXTENSION]
FROM
	rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
	
	INNER JOIN 
	rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
	ON 
	[StudentSchoolYear].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
	
	INNER JOIN 
	rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	ON 
	[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
	
	INNER JOIN 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[OrgYear].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	LEFT OUTER JOIN
	APS.LookupTable('K12','Grade') AS [Grades]
	ON
	[StudentSchoolYear].[GRADE] = [Grades].[VALUE_CODE]
	
	INNER JOIN 
	rev.EPC_SCH AS [School] -- Contains the School Code / Number
	ON 
	[Organization].[ORGANIZATION_GU] = [School].[ORGANIZATION_GU]
	
WHERE
	[StudentSchoolYear].[NO_SHOW_STUDENT] = 'N'
)


SELECT DISTINCT--TOP 100
	[STUDENT].[SIS_NUMBER]
	--,[SCHEDULE].[STUDENT_GU]
	,[PERSON].[FIRST_NAME]
	,[PERSON].[LAST_NAME]
	,[PERSON].[MIDDLE_NAME]
	,[STUDENT].HISPANIC_INDICATOR
	,[STUDENT].[RACE_1]
	,[STUDENT].[RACE_2]
	,[STUDENT].[RACE_3]
	,[STUDENT].[RACE_4]
	,[STUDENT].[RACE_5]
	,[STUDENT].[RESOLVED_RACE]
	,[STUDENT].[LUNCH_STATUS]
	,[ENROLLMENTS].[GRADE]
	--,CASE WHEN [Organization].[ORGANIZATION_NAME] IS NULL THEN [Organization_S].[ORGANIZATION_NAME] ELSE [Organization].[ORGANIZATION_NAME] END AS [SOR_NAME]
	--,[Organization].[ORGANIZATION_NAME]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENT_ENTER_DATE]
	,[ENROLLMENT_LEAVE_DATE]
	,[COURSE].[COURSE_ID]
	,[COURSE].[COURSE_TITLE]
	,[SCHEDULE].[COURSE_ENTER_DATE]
	,[SCHEDULE].[COURSE_LEAVE_DATE]
	,[SCHEDULE].[SECTION_ID]
	,COURSE_HISTORY.SECTION_ID
	,[SCHEDULE].[TERM_CODE]
	,[COURSE].[DUAL_CREDIT]
	,[COURSE].[OTHER_PROVIDER_NAME]
	,[COURSE].[CREDIT]
	
	--,[ENROLLMENTS].*
	
	,[COURSE_HISTORY].[MARK]
	,REPEAT_CODE
	,[COURSE_HISTORY].[CREDIT_COMPLETED]
	
FROM
	APS.StudentScheduleDetails AS [SCHEDULE]
	
	INNER JOIN
	rev.EPC_CRS AS [COURSE]
	ON
	[SCHEDULE].[COURSE_GU] = [COURSE].[COURSE_GU]
	AND COURSE.COURSE_ID = SCHEDULE.COURSE_ID
	
	INNER JOIN
	REV.EPC_SCH_YR_SECT AS SECT
	ON SECT.SCHOOL_YEAR_COURSE_GU = SCHEDULE.SCHOOL_YEAR_COURSE_GU
	AND SCHEDULE.SECTION_GU = SECT.SECTION_GU

	INNER JOIN 
	rev.REV_YEAR AS [RevYear] -- Contains the School Year
	ON 
	[SCHEDULE].[YEAR_GU] = [RevYear].[YEAR_GU]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[SCHEDULE].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.REV_PERSON AS [PERSON]
	ON
	[SCHEDULE].[STUDENT_GU] = [PERSON].[PERSON_GU]
	
	--LEFT OUTER JOIN
	--APS.PrimaryEnrollmentsAsOF(GETDATE()) AS [ENROLLMENTS]
	--ON
	--[SCHEDULE].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]
	
	--LEFT OUTER JOIN 
	--rev.REV_ORGANIZATION_YEAR AS [OrgYear] -- Links between School and Year
	--ON 
	--[ENROLLMENTS].[ORGANIZATION_YEAR_GU] = [OrgYear].[ORGANIZATION_YEAR_GU]
	
	--LEFT OUTER JOIN 
	--rev.REV_ORGANIZATION AS [Organization] -- Contains the School Name
	--ON 
	--[OrgYear].[ORGANIZATION_GU] = [Organization].[ORGANIZATION_GU]
	
	--LEFT OUTER JOIN 
	--rev.REV_ORGANIZATION_YEAR AS [OrgYear_S] -- Links between School and Year
	--ON 
	--[SCHEDULE].[ORGANIZATION_YEAR_GU] = [OrgYear_S].[ORGANIZATION_YEAR_GU]
	
	--LEFT OUTER JOIN 
	--rev.REV_ORGANIZATION AS [Organization_S] -- Contains the School Name
	--ON 
	--[OrgYear_S].[ORGANIZATION_GU] = [Organization_S].[ORGANIZATION_GU]
	
	LEFT OUTER JOIN
	SSY_ENROLLMENTS AS [ENROLLMENTS]
	ON
	[SCHEDULE].[STUDENT_GU] = [ENROLLMENTS].[STUDENT_GU]
	
	LEFT OUTER JOIN
	rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
	ON
	[SCHEDULE].[COURSE_ID] = [COURSE_HISTORY].[COURSE_ID]
	AND [SCHEDULE].[STUDENT_GU] = [COURSE_HISTORY].[STUDENT_GU]
	AND [RevYear].[SCHOOL_YEAR] = [COURSE_HISTORY].[SCHOOL_YEAR]
	AND COURSE_HISTORY.TERM_CODE = SCHEDULE.TERM_CODE --REMOVES ALL COURSE HISTORY COURSES THAT WERE NOT ON SCHEDULE
	--AND COURSE_HISTORY.COURSE_GU = SCHEDULE.COURSE_GU
	--AND COURSE_HISTORY.STU_COURSE_HISTORY_GU = COURSE.COURSE_GU
			LEFT JOIN
			[rev].[EPC_REPEAT_TAG] AS [Repeat]
			ON
			COURSE_HISTORY.[REPEAT_TAG_GU]=[Repeat].[REPEAT_TAG_GU]
WHERE
	([COURSE].[DUAL_CREDIT] = 'Y' OR [COURSE].[OTHER_PROVIDER_NAME] IN ('CNM','UNM'))
	AND [ENROLLMENTS].[SCHOOL_YEAR] = '2015'
	AND [ENROLLMENTS].[EXTENSION] = 'R'
	AND [RevYear].[SCHOOL_YEAR] = '2015'
	AND [RevYear].[EXTENSION] = 'R'
	AND [ENROLLMENTS].[EXCLUDE_ADA_ADM] IS NULL
	AND [STUDENT].[SIS_NUMBER] = '102985124'
 --'102757721'
	--AND [SCHEDULE].[TERM_CODE] IN ('S1','T1')

