DECLARE @ADC_TESTS
	TABLE
		(
		SIS_NUMBER VARCHAR (50)
		,MATH VARCHAR (50)
		,[READ] VARCHAR (50)
		,SCI VARCHAR (50)
		,WRITE VARCHAR (50)
		,SOC VARCHAR (50)
		,REWR VARCHAR (50)
		)
INSERT INTO @ADC_TESTS
SELECT 
	SIS_NUMBER
	,MATH
	,[READ]
	,SCI
	,WRITE
	,SOC
	,REWR
	
FROM
(
SELECT 
       SIS_NUMBER
       ,STU_PART.PERFORMANCE_LEVEL
	   ,test.TEST_COMPARE_CODE

FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

		INNER JOIN
		rev.EPC_STU_TEST_PART_SCORE AS SCORES
		ON
		SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU
		AND SCORES.TEST_SCORE != '--'

		LEFT JOIN
		rev.EPC_TEST_SCORE_TYPE AS SCORET
		ON
		SCORET.TEST_GU = StudentTest.TEST_GU
		AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

		LEFT JOIN
		rev.EPC_TEST_DEF_SCORE AS SCORETDEF
		ON
		SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

       INNER JOIN
       rev.REV_PERSON AS Person
       ON Person.PERSON_GU = StudentTest.STUDENT_GU

WHERE
       TEST_COMPARE_CODE IN ('SCI', 'MATH','READ','WRITE','REWR','SOC') 
	   AND SCORE_DESCRIPTION IN ('RAW','SCALE')
	   AND PERFORMANCE_LEVEL = 'P'

) AS T1

PIVOT
	(MAX (PERFORMANCE_LEVEL) FOR TEST_COMPARE_CODE IN ([MATH],[READ],[SCI],[WRITE],[SOC],[REWR])) AS PF


WHERE 1 = 1
--AND SIS_NUMBER = '100000678'
AND REWR = 'P'
ORDER BY SIS_NUMBER

SELECT * FROM @ADC_TESTS