USE [Assessments]
GO

SELECT [SCHOOL]
      ,[LAST_NAME]
      ,[FIRST_NAME]
      ,EES.[SIS_NUMBER]
	  ,STU.STATE_STUDENT_NUMBER
      ,[GRADE]
      ,[GSY]
      ,EES.[DIPLOMA_TYPE]
      --,[PARCC_GEOM]
      --,[PARCC_GEOM_PASS_FAIL]
      --,[PARCC_ALG_II]
      --,[PARCC_ALG_II_PASS_FAIL]
      --,[MATH_ATTEMPTS]
	  ,CASE WHEN PARCC_GEOM_PASS_FAIL = 'PASS' OR PARCC_ALG_II_PASS_FAIL = 'PASS' THEN 'PASS'
	        WHEN PARCC_GEOM_PASS_FAIL = 'FAIL' OR PARCC_ALG_II_PASS_FAIL = 'FAIL' THEN 'FAIL'
			ELSE ''
	  END AS 'PARCC_MATH_PASS/FAIL'
      ,[MATH REQUIREMENTS]
      ,[SBA_SLA_SS]
      --,[SBA_SLA_PL]
      --,[PARCC_ELA_11]
      ,[PARCC_ELA_11_PASS_FAIL]
	  ,CASE WHEN PARCC_ELA_11_PASS_FAIL = 'PASS' THEN 'PASSED PARCC ELA 11'
	        WHEN PARCC_ELA_11_PASS_FAIL = 'FAIL' THEN 'TAKE PARCC ELA 11'
			ELSE 'TAKE PARCC ELA 11'
	  END AS 'PARCC ELA 11 REQUIREMENTS'
      --,[PARCC_ELA_READ]
      --,[PARCC_ELA_WRIT]
      --,[READING_ATTEMPTS]
      ,[READING REQUIREMENTS]
      --,[WRITING ATTEMPTS]
      ,[WRITING REQUIREMENTS]
      --,[SBA_SCIENCE]
      ,[SBA_SCIENCE_PASS_FAIL]
      --,[SCIENCE_ATTEMPTS]
      ,CASE WHEN [SCIENCE REQUIREMENTS] = 'NULL' THEN 'USE ADC' 
	        WHEN [SCIENCE REQUIREMENTS] = 'PASSED (EOC Physics 9 12 V003)' THEN 'PASSED SECONDARY (EOC Physics 9 12 V003)'
			ELSE [SCIENCE REQUIREMENTS]
	  END AS 'SCIENCE REQUIREMENTS'
      --,[SS_ATTEMPTS]
	  ,CASE WHEN [SS REQUIREMENTS] LIKE 'PASSED%' THEN 'PASSED'
	        ELSE ''
	  END AS 'SS PASS/FAILED'
      ,[SS REQUIREMENTS]
  FROM [dbo].[EES_GSY_2017_2019] EES
  LEFT JOIN
  [SYNERGYDBDC].[ST_Production].[rev].[EPC_STU] AS STU
  ON STU.SIS_NUMBER = EES.SIS_NUMBER
WHERE STATE_STUDENT_NUMBER IS NOT NULL
ORDER BY [SCIENCE REQUIREMENTS]

GO


