			SELECT 
			DISTINCT 
			SCH.ORGANIZATION_NAME
			,SCH.COURSE_TITLE
			,SCH.COURSE_ID 
			,SCH.PERIOD_BEGIN AS PERIOD
			--,SCH.PERIOD_END
			--,SCH.YEAR_GU
			--,SCH.PRIMARY_STAFF
			--,YR.SCHOOL_YEAR
			,PER.FIRST_NAME
			,PER.LAST_NAME
			--,ST.BADGE_NUM
			--,PER.EMAIL
			--,SCH.ORGANIZATION_NAME
			,CAST(replace(lower(st.BADGE_NUM), 'e', '')AS INT) AS STAFF_ID
	
			FROM 
			APS.ScheduleDetailsAsOf (GETDATE()) AS SCH

			LEFT JOIN
			REV.REV_YEAR AS YR
			ON YR.YEAR_GU = SCH.YEAR_GU

			LEFT JOIN
			REV.REV_PERSON AS PER
			ON SCH.STAFF_GU = PER.PERSON_GU

			LEFT JOIN 
			REV.EPC_STAFF AS ST
			ON PER.PERSON_GU = ST.STAFF_GU
			WHERE 1 = 1
			AND SCHOOL_YEAR = (SELECT * FROM rev.SIF_22_Common_CurrentYear)
			AND EXTENSION = 'R'
			AND PERIOD_BEGIN = 9
			AND PRIMARY_STAFF = 1
			AND SCH.ENROLLMENT_ENTER_DATE IS NOT NULL
			AND SCH.DEPARTMENT = 'ELEM'
