SELECT
  EMPLOYEE_ID
  ,DATE_ASSIGN
  ,RN
  ,LOC_NUM
  ,LOC_DESCRIPTION
  ,ACCESS_CODE
  ,FIRST_NAME
  ,LAST_NAME
  ,LAWSON_JOB_TITLE
  ,JOB_TITLE_ABBREVIATION
  ,[GROUP]
  ,SECURITY_LVL
  ,DATE_CREATE
  ,BIRTHYEAR
  ,EMAIL_ADDRESS
FROM
	(
	SELECT
	  ROW_NUMBER () OVER (PARTITION BY EMPLOYEE.EMPLOYEE_ID, EMPLOYEE.LOC_NUM  ORDER BY EMPLOYEE.DATE_ASSIGN DESC)AS RN
	  ,[DATE_ASSIGN]
	  ,EMPLOYEE_ID
	  ,LOC_NUM
	  ,LOC_DESCRIPTION
	  ,ACCESS_CODE
	  ,FIRST_NAME
	  ,LAST_NAME
	  ,LAWSON_JOB_TITLE
	  ,JOB_TITLE_ABBREVIATION
	  ,[GROUP]
	  ,SECURITY_LVL
	  ,DATE_CREATE
	  ,BIRTHYEAR
	  ,EMAIL_ADDRESS
	FROM
	  EMPLOYEE_FILE_TEMP AS EMPLOYEE
	)AS A
--WHERE RN = 1	
ORDER BY
	EMPLOYEE_ID	  
