BEGIN TRAN

UPDATE
	[180-SMAXODS-01].[SchoolNet].[dbo].[EOC_SOAP]
	SET STID_2 = STUD.[STUDENT ID]
FROM
	[180-SMAXODS-01].[SchoolNet].[dbo].[EOC_SOAP] AS SOAP1
	INNER JOIN
	[046-WS02].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	ON SOAP1.STID = STUD.[ALTERNATE STUDENT ID]

ROLLBACK
