BEGIN TRAN

USE Assessments
GO
   
--TRUNCATE TABLE CCR_FOR_STARS
--INSERT INTO [CCR_FOR_STARS]

SELECT
	[DISTRICT CODE]
	,[TEST DESCRIPTION]
	,[ASSESSMENT SCHOOL YEAR DATE]
	,[ITEM DESCRIPTION CODE]
	,[TEST DATE]
	,[STUDENT ID]
	,[LOCATION CODE]
	,[RAW SCORE]


FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY EOC.[ID NUMBER], SUBTEST, [test Date] ORDER BY EOC.School DESC) AS RN
	   ,'001' AS 'DISTRICT CODE'
	   ,[Test ID] AS 'TEST DESCRIPTION'
	   ,'2015-06-30' AS 'ASSESSMENT SCHOOL YEAR DATE'
	   ,CASE	
			WHEN SUBTEST ='US HISTORY 9-12 V002' THEN 'US HISTORY 9 12 V002' 
			WHEN Subtest = 'NM History 7 12 V001' THEN 'NEW MEXICO HISTORY 7 12 V001'
			ELSE 
				 CASE WHEN CS.STARS_name_V2 IS NULL THEN UPPER (CS.STARS_name)
				 ELSE UPPER (CS.STARS_name_V2)
			END
		END AS 'ITEM DESCRIPTION CODE'
	   ,SUBSTRING ([test Date],1,4)+'-'+ SUBSTRING ([test Date],6,2) +'-' + SUBSTRING ([test Date], 9,2) AS 'TEST DATE'
	   ,[test Date] as td
	   ,STUD.[STUDENT ID] AS 'STUDENT ID'
	  ,STUD.[LOCATION CODE] AS [LOCATION CODE]
	  ,Score1 AS 'RAW SCORE'
  FROM EOC_ AS EOC
LEFT JOIN	
	[046-WS02].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	ON EOC.[ID Number] = STUD.[ALTERNATE STUDENT ID]
	AND STUD.SY = '2015'
	AND STUD.PERIOD = '2015-06-01'

	LEFT JOIN
	EoC_Cut_Scores AS CS
	ON EOC.assessment_id = CS.assessment_id

	WHERE EOC.[ID Number] != 'NULL'
	AND [test Date] IN ('2015-04-27','2015-07-15','2015-05-11')
) AS T1
WHERE
[LOCATION CODE] IS NOT NULL
AND RN = 1
ORDER BY [STUDENT ID] 

ROLLBACK

