SELECT 
    K12INTEL_DW.DTBL_STUDENTS.STUDENT_ID AS SIS_NUMBER
	,STUDENT_STATE_ID
    ,DTBL_STUDENTS.STUDENT_GRADUATION_COHORT
    TEST_NAME
	,SCHOOL_CODE
    ,TEST_STUDENT_GRADE
     ,TEST_PRODUCT 
    ,TEST_SUBJECT AS CONTENT_AREA
    , DATE_VALUE AS TEST_DATE
    ,TEST_RAW_SCORE AS RAW_SCORE
    ,TEST_SCALED_SCORE AS SCALE_SCORE
    ,TEST_SCORE_VALUE 
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
--other fields
    ,TEST_NAME
    ,TEST_CLASS
    ,TEST_GROUP
    ,TEST_SUBGROUP
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
LEFT JOIN
K12INTEL_DW.DTBL_STUDENT_DETAILS
ON K12INTEL_DW.DTBL_STUDENT_DETAILS.STUDENT_ID = K12INTEL_DW.DTBL_STUDENTS.STUDENT_ID
WHERE TEST_PRODUCT LIKE 'eoc'
--AND TEST_SUBJECT IN ('English','Reading','Math','Science')
--and STUDENT_GRADUATION_COHORT = 2017
--WHERE TEST_PRODUCT = 'Stepping Stones'
--AND DATE_VALUE IN ('2015-02-09 00:00:00.000','2014-12-01 00:00:00.000','2015-02-02 00:00:00.000','2014-09-01 00:00:00.000')

AND DATE_VALUE BETWEEN '2014-12-08 00:00:00.000' AND '2015-06-25 00:00:00.000'

--ORDER BY SCHOOL_CODE
ORDER BY STUDENT_STATE_ID

