/*** Add Teacher Info ***/
ALTER TABLE [EOC_SOAP_2]
  ADD [TID] VARCHAR(50)
  
  ALTER TABLE [EOC_SOAP_2]
  ADD [TNAME] VARCHAR(50)
  
  ALTER TABLE [EOC_SOAP_2]
  ADD [TFNAME] VARCHAR(50)

  ALTER TABLE [EOC_SOAP_2]
  ADD [TLNAME] VARCHAR(50)  

	ALTER TABLE [EOC_SOAP_2]
	ADD [Certificate_Number] VARCHAR(20)


  BEGIN TRAN
  
update [180-SMAXODS-01].SCHOOLNET.DBO.[EOC_SOAP_2] 
set [TID] = t2.[PRIMINSTID], TFNAME = T2.[STAFFNAME]
FROM [180-SMAXODS-01].SCHOOLNET.DBO.[EOC_SOAP_2] AS SOAPS
INNER JOIN [046-WS02].[db_STARS_History].[dbo].[CRSE_INSTRUCT] AS T2
ON SOAPS.[SECCODELONG] = T2.[SECTIONCODELONG]
AND SOAPS.[SCHNUMB] = T2.[LOCATION CODE]
AND SOAPS.[Period] = T2.[Period] 

ROLLBACK

BEGIN TRAN

UPDATE [180-SMAXODS-01].SCHOOLNET.DBO.[EOC_SOAP_2] 
SET [Certificate_Number] = T2.[Certificate_Number]
FROM [180-SMAXODS-01].SCHOOLNET.DBO.[EOC_SOAP_2] AS SOAPS
INNER JOIN [180-SMAXODS-01].[HELPER].[dbo].[Licensure] AS T2
ON SOAPS.[TID] = T2.[STAFF_ID]


ROLLBACK