USE
ST_Production


SELECT
	*
FROM
(
SELECT
	[ALTERNATE STUDENT ID] AS SIS_NUMBER
	,[LOCATION CODE] AS SCHOOL_CODE
	,ORG.ORGANIZATION_NAME
	,BS.RESOLVED_RACE
FROM
	[RDAVM.APS.EDU.ACTD].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	JOIN
	REV.EPC_STU STU
	ON STUD.[ALTERNATE STUDENT ID] = STU.SIS_NUMBER
	LEFT HASH JOIN 
	APS.BasicStudentWithMoreInfo AS BS
	ON BS.SIS_NUMBER = STUD.[ALTERNATE STUDENT ID]
	JOIN
	REV.EPC_SCH SCH
	ON STUD.[LOCATION CODE] = SCH.SCHOOL_CODE
	LEFT JOIN
	REV.REV_ORGANIZATION ORG
	ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU

WHERE 1 = 1
	AND Period = '2016-10-01'
	AND [DISTRICT CODE] = '001'
	AND (STUD.[LOCATION CODE] > '500' OR STUD.[LOCATION CODE] = '048')
	AND STUD.[LOCATION CODE] NOT IN ('983','998','973','900','611','840')
) T1
PIVOT
	(COUNT([SIS_NUMBER]) FOR RESOLVED_RACE IN ([WHITE],[HISPANIC],[NATIVE AMERICAN],[AFRICAN-AMERICAN],[ASIAN],[PACIFIC ISLANDER],[TWO OR MORE])) AS UP1

ORDER BY ORGANIZATION_NAME



USE
ST_Production



SELECT
	COUNT ([ALTERNATE STUDENT ID]) AS SIS_NUMBER
	,[LOCATION CODE] AS SCHOOL_CODE
	,ORG.ORGANIZATION_NAME
	--,BS.RESOLVED_RACE
FROM
	[RDAVM.APS.EDU.ACTD].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	JOIN
	REV.EPC_STU STU
	ON STUD.[ALTERNATE STUDENT ID] = STU.SIS_NUMBER
	LEFT HASH JOIN 
	APS.BasicStudentWithMoreInfo AS BS
	ON BS.SIS_NUMBER = STUD.[ALTERNATE STUDENT ID]
	JOIN
	REV.EPC_SCH SCH
	ON STUD.[LOCATION CODE] = SCH.SCHOOL_CODE
	LEFT JOIN
	REV.REV_ORGANIZATION ORG
	ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU

WHERE 1 = 1
	AND Period = '2016-10-01'
	AND [DISTRICT CODE] = '001'
	AND (STUD.[LOCATION CODE] > '500' OR STUD.[LOCATION CODE] = '048')
	AND STUD.[LOCATION CODE] NOT IN ('983','998','973','900','611','840')
GROUP BY [LOCATION CODE],ORGANIZATION_NAME

--PIVOT
--	(COUNT([SIS_NUMBER]) FOR RESOLVED_RACE IN ([WHITE],[HISPANIC],[NATIVE AMERICAN],[AFRICAN-AMERICAN],[ASIAN],[PACIFIC ISLANDER],[TWO OR MORE])) AS UP1
--GROUP BY SIS_NUMBER, SCHOOL_CODE, ORGANIZATION_NAME
ORDER BY ORGANIZATION_NAME