SELECT
	SS.ID_NBR
	,ECA.[PERM ID]
	,SS.LAST_NAME
	,SS.FIRST_NAME
	,SS.[CURRENT SY2014 GRADE]
	,STUD.[LOCATION CODE]
	,SS.[PASSED ALL REQUIRED TESTS]
	,SS.TAKE_SBA
	,SS.TAKE_EOC
	,SS.[MATH SBA ATTEMPTS]
	,SS.[READING SBA ATTEMPTS]
	,SS.[SCIENCE SBA ATTEMPTS]
	,ECA.[COURSE ID]
	,ECA.[COURSE TITLE]
FROM
	[ECA_SS_LIST_WITH_EOC_REQ] AS ECA
	INNER JOIN
	EES_FOR_SUMMER_SCHOOL AS SS
	ON
	ECA.[PERM ID] = SS.[ID_NBR]
	LEFT JOIN
	[046-WS02].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	ON ECA.[PERM ID] = STUD.[ALTERNATE STUDENT ID]
	AND STUD.PERIOD = '2014-06-01'
	--WHERE LAST_NAME = 'GUTIERREZ'
	--WHERE [CURRENT SY2014 GRADE] = '11'
ORDER BY ID_NBR DESC