USE Assessments
GO

BEGIN TRAN
      
--INSERT INTO [CCR_FOR_STARS]
SELECT
	[DISTRICT CODE]
	,[TEST DESCRIPTION]
	,[ASSESSMENT SCHOOL YEAR DATE]
	,[ITEM DESCRITPION CODE]
	--,test_section_name
	,[TEST DATE]
	,[STUDENT ID]
	,[LOCATION CODE]
	,[RAW SCORE]
FROM
(
SELECT
	
	ROW_NUMBER () OVER (PARTITION BY [student_code], [test_section_name], [test_date_code] ORDER BY [school_code]) AS RN
	,'001' AS [DISTRICT CODE]
	,'IB' AS [TEST DESCRIPTION]
	,'2015-06-30' AS [ASSESSMENT SCHOOL YEAR DATE]
	,CASE 
		WHEN test_section_name = 'BIOLOGY' THEN 'EXPERIMENTAL SCIENCES'
		WHEN test_section_name = 'CHEMISTRY' THEN 'EXPERIMENTAL SCIENCES'
		WHEN test_section_name = 'SPORTS EX SCI' THEN 'EXPERIMENTAL SCIENCES'
		--WHEN test_section_name = 'THEORY KNOWL.' THEN 'EXPERIMENTAL SCIENCES'
		WHEN test_section_name = 'PSYCHOLOGY' THEN 'EXPERIMENTAL SCIENCES'
		WHEN test_section_name = 'PHILOSOPHY' THEN 'INDIVIDUALS AND SOCIETY'
		WHEN test_section_name = 'PHYSICS' THEN 'EXPERIMENTAL SCIENCES'
		WHEN test_section_name = 'HISTORY' THEN 'INDIVIDUALS AND SOCIETY'
		WHEN test_section_name = 'MATHEMATICS' THEN 'MATHEMATICS'
		WHEN test_section_name = 'MATH.STUDIES' THEN 'MATHEMATICS'
		WHEN test_section_name = 'VISUAL ARTS' THEN 'ARTS'
		WHEN test_section_name = 'MUSIC' THEN 'ARTS'
		WHEN test_section_name = 'ENGLISH A LIT' THEN 'LANGUAGE A'
		WHEN test_section_name = 'FRENCH AB.' THEN 'LANGUAGE B'
		WHEN test_section_name = 'SPANISH B' THEN 'LANGUAGE B'
		WHEN test_section_name = 'SPANISH AB.' THEN 'LANGUAGE B'
		--ELSE UPPER (test_section_name) 
	END AS [ITEM DESCRITPION CODE]
	,test_section_name
	,test_date_code AS [TEST DATE]
	,STUD.[STUDENT ID] AS 'STUDENT ID'
	,CASE WHEN SSN.STATE_SCH IS NULL THEN [LOCATION CODE] ELSE SSN.STATE_SCH
	END AS [LOCATION CODE]
	,score_3 AS [RAW SCORE]
FROM
	test_result_IB AS CCR	
	LEFT JOIN
	[046-WS02].DB_STARS_HISTORY.DBO.STUDENT AS STUD
	ON
	CCR.student_code = STUD.[ALTERNATE STUDENT ID]
	AND STUD.SY = '2015'
	AND STUD.Period = '2015-06-01'
		
	LEFT JOIN
	[State School Number] AS SSN
	ON 
	CCR.school_code = SSN.SCH_NBR
WHERE STUD.[STUDENT ID] IS NOT NULL
--AND [STUDENT ID] = '756962353'
) AS T1
WHERE [ITEM DESCRITPION CODE] IS NOT NULL
AND RN = 1
ORDER BY [RAW SCORE]

ROLLBACK
