USE Assessments
GO

--BEGIN TRAN

SELECT
	SIS_NUMBER
	,GRADE
	,TEST_DATE
	,SCHOOL
	,[TEST DESCRIPTION]
	,[ITEM DESCRITPION CODE]
	,TEST_NAME
	,[RAW SCORE]
	,PERFORMANCE_LEVEL
	--,RN

FROM
(
SELECT 
	ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER, [ITEM DESCRITPION CODE] ORDER BY [TEST_DATE] ASC) AS RN
	,SIS_NUMBER
	,GRADE
	,TEST_DATE
	,SCHOOL
	,[TEST DESCRIPTION]
	,[ITEM DESCRITPION CODE]
	,TEST_NAME
	,[RAW SCORE]
	,PERFORMANCE_LEVEL
	

FROM
(
SELECT
	
	student_code AS SIS_NUMBER
	,test_level_name AS GRADE
	,test_date_code AS TEST_DATE
	,school_code AS SCHOOL
	,'IB' AS [TEST DESCRIPTION]
	,CASE 
		WHEN test_section_name IN ('BIOLOGY','CHEMISTRY','SPORTS EX SCI','THEORY KNOWL.','PSYCHOLOGY','PHYSICS') THEN 'EXPERIMENTAL SCIENCES'
		--WHEN test_section_name = 'CHEMISTRY' THEN 'EXPERIMENTAL SCIENCES'
		--WHEN test_section_name = 'SPORTS EX SCI' THEN 'EXPERIMENTAL SCIENCES'
		--WHEN test_section_name = 'THEORY KNOWL.' THEN 'EXPERIMENTAL SCIENCES'
		--WHEN test_section_name = 'PSYCHOLOGY' THEN 'EXPERIMENTAL SCIENCES'
		WHEN test_section_name IN ('PHILOSOPHY','HISTORY') THEN 'INDIVIDUALS AND SOCIETY'
		--WHEN test_section_name = 'PHYSICS' THEN 'EXPERIMENTAL SCIENCES'
		--WHEN test_section_name = 'HISTORY' THEN 'INDIVIDUALS AND SOCIETY'
		WHEN test_section_name IN ('MATHEMATICS','MATH.STUDIES') THEN 'MATHEMATICS'
		--WHEN test_section_name = 'MATH.STUDIES' THEN 'MATHEMATICS'
		WHEN test_section_name IN ('VISUAL ARTS','MUSIC') THEN 'ARTS'
		--WHEN test_section_name = 'MUSIC' THEN 'ARTS'
		WHEN test_section_name IN ('ENGLISH A LIT','ENGLISH A LAL') THEN 'LANGUAGE A'
		WHEN test_section_name IN ('FRENCH AB.','SPANISH B','SPANISH AB.') THEN 'LANGUAGE B'
		--WHEN test_section_name = 'SPANISH B' THEN 'LANGUAGE B'
		--WHEN test_section_name = 'SPANISH AB.' THEN 'LANGUAGE B'
		--ELSE UPPER (test_section_name) 
	END AS [ITEM DESCRITPION CODE]
	,test_section_name AS TEST_NAME
	,score_3 AS [RAW SCORE]
	,score_2 AS PERFORMANCE_LEVEL
FROM
	test_result_IB AS CCR	
) AS T1

) T2
WHERE
	1 = 1
	--AND RN = 1
	AND [ITEM DESCRITPION CODE] = 'EXPERIMENTAL SCIENCES'
    --AND [ITEM DESCRITPION CODE] = 'INDIVIDUALS AND SOCIETY'
	--AND [ITEM DESCRITPION CODE] = 'MATHEMATICS'
	--AND [ITEM DESCRITPION CODE] = 'ARTS'
	--AND [ITEM DESCRITPION CODE] = 'LANGUAGE A'
	--AND [ITEM DESCRITPION CODE] = 'LANGUAGE B'
ORDER BY SIS_NUMBER

