USE [SchoolNet]
GO
SELECT 
	ID_NBR
	,CASE WHEN MATH IS NOT NULL THEN MATH ELSE '' END AS MATH
	,CASE WHEN READING IS NOT NULL THEN READING ELSE '' END AS READING
	,CASE WHEN SCHOOL_YEAR IS NOT NULL THEN CAST(SCHOOL_YEAR AS VARCHAR (4)) + '-'+CAST((school_year +1) AS VARCHAR (4)) ELSE '' END AS SCHOOL_YEAR
FROM [180-SMAXODS-01].SCHOOLNET.[dbo].IDsForQuery AS REQUEST
  LEFT JOIN
(
SELECT
	STUDENT_CODE
	,MATH
	,READING
	,SCHOOL_YEAR
FROM
(
SELECT	
STUDENT_CODE
,SCHOOL_YEAR
,SCORE_GROUP_NAME
,TEST_SECTION_NAME
FROM

	[180-SMAXODS-01].SCHOOLNET.[dbo].SBA AS SBA
  
  WHERE SBA.school_year = '2013'
  AND test_section_name IN ('READING', 'MATH')
  ) AS T1
pivot
(max([SCORE_GROUP_NAME]) FOR test_section_name IN ([MATH],[READING])) AS UP1
) AS SBA2

ON SBA2.student_code = REQUEST.[ID_NBR]






