SELECT
	BS.SIS_NUMBER
	,BS.STATE_STUDENT_NUMBER
	,LAST_NAME
	,FIRST_NAME
	,BIRTH_DATE
	,GENDER
	,SCH.SCHOOL_CODE
	,ES.SCHOOL_CODE AS ELEMENTARY_SCHOOL
	,ES.ES_NAME
	,grade.VALUE_DESCRIPTION  AS GRADE
	,YR.SCHOOL_YEAR
	,SSY.ENTER_DATE
	,BS.HOME_LANGUAGE
	,LUNCH_STATUS
	,ELL_STATUS
	,PRIMARY_DISABILITY_CODE
	,GIFTED_STATUS
	,HISPANIC_INDICATOR
	,RESOLVED_RACE
	,OYR.YEAR_GU
FROM
	APS.BasicStudentWithMoreInfo AS BS
LEFT JOIN
	rev.EPC_STU AS STU
	ON BS.SIS_NUMBER = STU.SIS_NUMBER
       JOIN rev.EPC_STU_SCH_YR        ssy  ON ssy.STUDENT_GU = stu.STUDENT_GU
	   join rev.EPC_STU_YR AS SOR		   ON SOR.STU_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU  
       JOIN rev.REV_ORGANIZATION_YEAR oyr  ON oyr.ORGANIZATION_YEAR_GU = ssy.ORGANIZATION_YEAR_GU
                                              and oyr.YEAR_GU = (select YEAR_GU from rev.SIF_22_Common_CurrentYearGU)
       JOIN rev.REV_YEAR              yr   ON yr.YEAR_GU          = oyr.YEAR_GU
       JOIN rev.REV_ORGANIZATION      org  ON org.ORGANIZATION_GU = oyr.ORGANIZATION_GU
       JOIN rev.EPC_SCH               sch  ON sch.ORGANIZATION_GU = oyr.ORGANIZATION_GU
	   LEFT JOIN rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade ON grade.VALUE_CODE = ssy.GRADE
	   LEFT JOIN
	   (SELECT
			*
			FROM
			(
			SELECT
				ROW_NUMBER () OVER (PARTITION BY BS.SIS_NUMBER  ORDER BY grade.VALUE_DESCRIPTION DESC, SSY.ENTER_DATE DESC) AS RN
				,BS.SIS_NUMBER
				,SCH.SCHOOL_CODE
				,grade.VALUE_DESCRIPTION  AS GRADE
				,YR.SCHOOL_YEAR
				,ORG.ORGANIZATION_NAME AS ES_NAME
			FROM
				APS.BasicStudentWithMoreInfo AS BS
			LEFT JOIN
				rev.EPC_STU AS STU
				ON BS.SIS_NUMBER = STU.SIS_NUMBER
				   JOIN rev.EPC_STU_SCH_YR        ssy  ON ssy.STUDENT_GU = stu.STUDENT_GU
				   join rev.EPC_STU_YR AS SOR		   ON SOR.STU_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU  
				   JOIN rev.REV_ORGANIZATION_YEAR oyr  ON oyr.ORGANIZATION_YEAR_GU = ssy.ORGANIZATION_YEAR_GU
														  --and oyr.YEAR_GU = (select YEAR_GU from rev.SIF_22_Common_CurrentYearGU)
				   JOIN rev.REV_YEAR              yr   ON yr.YEAR_GU          = oyr.YEAR_GU
				   JOIN rev.REV_ORGANIZATION      org  ON org.ORGANIZATION_GU = oyr.ORGANIZATION_GU
				   JOIN rev.EPC_SCH               sch  ON sch.ORGANIZATION_GU = oyr.ORGANIZATION_GU
				   LEFT JOIN rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade ON grade.VALUE_CODE = ssy.GRADE
			WHERE 1 = 1
			AND SSY.ENTER_DATE IS NOT NULL
			AND YR.EXTENSION = 'R'
			AND grade.VALUE_DESCRIPTION  IN ('01','02','03','04','05')
			) T1
			WHERE RN = 1
		) AS ES
		ON ES.SIS_NUMBER = BS.SIS_NUMBER

WHERE 1 = 1
AND PRIMARY_DISABILITY_CODE = 'GI'
AND SCH.SCHOOL_CODE = '425'
AND SSY.ENTER_DATE IS NOT NULL
AND YR.EXTENSION = 'R'

ORDER BY STU.SIS_NUMBER
