SELECT
	student_code
	,[ADVANCED ALGEBR],[ALGEBRA I],[ALGEBRA I BIL],[ALGEBRA I H BIL],[ALGEBRA I HON],[ALGEBRA II],[ALGEBRA II BIL],[ALGEBRAIC MODEL],[APP LINEAR ALG],[BLOCKALG],[BUSINESS MATH]
,[COLL ALGEBRA WK],[COLLEGE ALGEBRA],[ELECTRICAL MATH I],[ELEM MATH STATS],[GEOMETRY],[GEOMETRY BIL],[GEOMETRY HON],[HON ALG II/TRIG],[IB MATH HL 1],[IB MATH HL 2],[IB MATH SL 1],
[IB MATH SL 2],[INTERMED ALGEBR],[INTERMEDIATE ALGEBRA III],[INTRMD ALGEBRA],[LINEAR ALGEBRA],[MATH 1],[MATH 2],[MATH 3],[MATH 4],[MATH 6],[MATH 7],[MATH 8],[MATH FOR TCHRS],
[MATH STRATEGY 2],[MATH STRATEGY 3],[MATH STRATEGY I],[MATH STRATS BIL],[MATH TM],[MATHLAB],[SURVEY OF MATH],[TRANS COLL MATH],[TRNS COLLEGE MATH],[TRNS TO COLMATH]
FROM
(
SELECT	
	student_code
	,mark_code
	,COURSE_SHORT_TITLE
	
FROM
	CHRIS_HS_MATH_COURSES
) AS T1
PIVOT
(MAX([mark_code]) FOR course_short_title IN ([ADVANCED ALGEBR],[ALGEBRA I],[ALGEBRA I BIL],[ALGEBRA I H BIL],[ALGEBRA I HON],[ALGEBRA II],[ALGEBRA II BIL],[ALGEBRAIC MODEL],[APP LINEAR ALG],[BLOCKALG],[BUSINESS MATH]
,[COLL ALGEBRA WK],[COLLEGE ALGEBRA],[ELECTRICAL MATH I],[ELEM MATH STATS],[GEOMETRY],[GEOMETRY BIL],[GEOMETRY HON],[HON ALG II/TRIG],[IB MATH HL 1],[IB MATH HL 2],[IB MATH SL 1],
[IB MATH SL 2],[INTERMED ALGEBR],[INTERMEDIATE ALGEBRA III],[INTRMD ALGEBRA],[LINEAR ALGEBRA],[MATH 1],[MATH 2],[MATH 3],[MATH 4],[MATH 6],[MATH 7],[MATH 8],[MATH FOR TCHRS],
[MATH STRATEGY 2],[MATH STRATEGY 3],[MATH STRATEGY I],[MATH STRATS BIL],[MATH TM],[MATHLAB],[SURVEY OF MATH],[TRANS COLL MATH],[TRNS COLLEGE MATH],[TRNS TO COLMATH])) AS P1

ORDER BY student_code