USE 
PR
GO

SELECT 
	SCH_NBR
	,GRDE
	,COUNT (*) AS 'STUDENTS NOT RECIEVING SERVICES 2013-2014'
FROM 
	APS.LCEStudentsAndProvidersAsOf('2014-05-22')
WHERE 
	TCH_NME IS NULL
	AND PARENT_REFUSAL != 'Y'
GROUP BY
	SCH_NBR
	,GRDE
ORDER BY SCH_NBR, GRDE