SELECT
	--TOP 500
	DISTINCT 
	SIS_NUMBER
	,STATE_STUDENT_NUMBER
	,STU.LAST_NAME
	,STU.FIRST_NAME
	,GRADE.VALUE_DESCRIPTION AS GRADE
	--,OPT.ASSESSMENT
	,LU.VALUE_DESCRIPTION AS ASSESSMENT_NAME
	,RESOLVED_RACE
	,ELL_STATUS
	,SPED_STATUS
	,LUNCH_STATUS
	,YR.SCHOOL_YEAR
	--,SBA.TEST_SECTION_NAME
	--,TESTS.
	
FROM
	APS.BasicStudentWithMoreInfo AS STU
	JOIN rev.EPC_STU_SCH_YR AS ssy  
	ON ssy.STUDENT_GU = stu.STUDENT_GU

	LEFT JOIN rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade ON grade.VALUE_CODE = ssy.GRADE

	LEFT JOIN
	UD_OPT_OUT AS OPT
	ON OPT.STUDENT_GU = STU.STUDENT_GU

  LEFT JOIN APS.LookupTable ('REVELATION.UD.OPTOUT','ASSESSMENT') AS LU
  ON LU.VALUE_CODE = OPT.ASSESSMENT

  LEFT JOIN rev.REV_ORGANIZATION_YEAR oyr  ON oyr.ORGANIZATION_YEAR_GU = ssy.ORGANIZATION_YEAR_GU
                                        and oyr.YEAR_GU = (select YEAR_GU from rev.SIF_22_Common_CurrentYearGU)
  LEFT JOIN rev.REV_YEAR              yr   ON yr.YEAR_GU          = oyr.YEAR_GU

WHERE GRADE.VALUE_DESCRIPTION NOT IN ('PK','P1','P2','C1','C2','C3','C4','K','01','02','T4','T3','T2','T1')
AND ASSESSMENT IS NOT NULL
AND LU.VALUE_DESCRIPTION LIKE '%PARCC%'

ORDER BY SIS_NUMBER