



SELECT
	ID_NBR
	,CASE WHEN STATE_ID IS NULL THEN '' ELSE STATE_ID END AS 'STATE ID'
	,CASE WHEN PARCC.SCH_YR IS NULL THEN '' ELSE PARCC.SCH_YR END AS SCH_YR
	,CASE WHEN PARCC.Subtest IS NULL THEN '' ELSE PARCC.Subtest END AS 'PARCC SUBTEST'
	,CASE WHEN PARCC.SS IS NULL THEN '' ELSE PARCC.SS END AS 'PARCC OVERALL SS'
	,CASE WHEN PARCC.PL IS NULL THEN '' ELSE PARCC.PL END AS 'PARCC PL'
FROM
(
SELECT
	DISTINCT ID_NBR
	,STUD.state_id
FROM
	[TRASH_Student K3Plus SmartStart Demographics and Attendance 031816] AS K3

LEFT JOIN
	allstudents_ALL AS STUD
	ON K3.ID_NBR = STUD.student_code
) AS IDS
LEFT JOIN
	PARCC_ES_MS AS PARCC
	ON IDS.state_id = PARCC.StudentID

ORDER BY 
	ID_NBR, Subtest