USE [Assessments]
GO

SELECT DISTINCT 
	   [State Abbreviation]
      ,[Testing District Code]
      ,[Testing School Code]
      ,[Responsible District Code]
      ,[Responsible School Code]
      , [State Student Identifier]
      , [Local Student Identifier]
      ,[PARCC Student ID]
      ,[Last or Surname]
      ,[First Name]
      ,[Middle Name]
      ,STUD.DOB [Birthdate]
      ,BS.GENDER AS [Sex]
      ,[State Field 1]
      ,STUD.grade_code AS [Grade Level When Assessed]
      ,CASE WHEN BS.HISPANIC_INDICATOR = 'Y' THEN 'Y' ELSE 'N' END AS [Hispanic or Latino Ethnicity]
      ,CASE WHEN BS.RACE_1 = 'NATIVE AMERICAN' THEN 'Y' ELSE 'N' END AS [American Indian or Alaska Native]
      ,CASE WHEN BS.RACE_1 = 'ASIAN' THEN 'Y' ELSE 'N' END AS [Asian]
      ,CASE WHEN BS.RACE_1 = 'AFRICAN-AMERICAN' THEN 'Y' ELSE 'N' END AS [Black or African American]
      ,CASE WHEN BS.RACE_1 = 'PACIFIC ISLANDER' THEN 'Y' ELSE 'N' END AS [Native Hawaiian or Other Pacific Islander]
      ,CASE WHEN BS.RACE_1 = 'WHITE' THEN 'Y' ELSE 'N' END AS [White]
      ,[Filler Field]
      ,CASE WHEN BS.RESOLVED_RACE = 'TWO OR MORE' THEN 'Y' ELSE 'N' END AS [Two or More Races]
      ,CASE WHEN BS.ELL_STATUS = 'Y' THEN 'Y' ELSE 'N' END AS [English Learner  (EL)]
      ,CASE WHEN BS.ELL_STATUS = 'Y' THEN 'Y' ELSE 'N' END AS [Title III Limited English Proficient Participation Status]
      ,CASE WHEN BS.GIFTED_STATUS = 'Y' THEN 'Y' ELSE 'N' END AS [Gifted and Talented]
      ,'N' [Migrant Status]
      ,CASE WHEN BS.LUNCH_STATUS IN ('R','2','F') THEN 'Y' ELSE 'N' END AS [Economic Disadvantage Status]
      ,CASE WHEN BS.PRIMARY_DISABILITY_CODE = 'NULL' OR BS.PRIMARY_DISABILITY_CODE IS NULL THEN 'N' ELSE 'IEP' END AS [Student With Disabilities ]
      ,CASE WHEN BS.PRIMARY_DISABILITY_CODE = 'NULL' OR BS.PRIMARY_DISABILITY_CODE IS NULL THEN '' ELSE BS.PRIMARY_DISABILITY_CODE END AS [Primary Disability Type]
      ,[State Field 2]
      ,[State Field 3]
      ,[State Field 4]
      ,[State Field 5]
      ,[State Field 6]
      ,[State Field 7]
      ,[State Field 8]
      ,[State Field 9]
      ,[State Field 10]
      ,[State Field 11]
      ,[State Field 12]
      ,[Session Name]
      ,[Class Name]
      ,[Test Administrator ]
      ,[Staff Member Identifier]
      ,[Test Code]
      ,[Test Format ]
      ,[Retest]
      ,[EL Accommodation ]
      ,[Frequent Breaks]
      ,[Separate Alternate Location]
      ,[Small Testing Group]
      ,[Specialized Equipment or Furniture]
      ,[Specified Area or Setting]
      ,[Time of Day]
      ,[Answer Masking]
      ,[Filler Field]
      ,[Color Contrast]
      ,[ASL Video]
      ,[Assistive Technology - Screen Reader]
      ,[Assistive Technology - Non-Screen Reader ]
      ,[Closed Captioning for ELA L]
      ,[Refreshable Braille Display for ELA L]
      ,[Alternate Representation - Paper Test]
      ,[Large Print]
      ,[Braille with Tactile Graphics]
      ,[Student Reads Assessment Aloud to Themselves]
      ,[Human Signer for Test Directions]
      ,[Answers Recorded in Test Book]
      ,[Braille Response]
      ,[Calculation Device and Mathematics Tools]
      ,[ELA L Constructed Response]
      ,[ELA L Selected Response or Technology Enhanced Items]
      ,[Mathematics Response]
      ,[Monitor Test Response]
      ,[Word Prediction]
      ,[Administration Directions Clarified in Student’s Native Language ]
      ,[Administration Directions Read Aloud in Student’s Native Language]
      ,[Mathematics Response - EL]
      ,[Translation of the Mathematics Assessment]
      ,[Word to Word Dictionary (English Native Language)]
      ,[Text-to-Speech]
      ,[Human Reader or Human Signer]
      ,[Unique Accommodation  ]
      ,[Emergency Accommodation]
      ,[Extended Time]
  FROM [dbo].[TRASH_560_Student Registration IMPORT_FINLIT] AS PARCC
  LEFT JOIN
  BASIC_STUDENT_WITH_MORE_INFORMATION AS BS
  ON PARCC.[State Student Identifier] = BS.STATE_STUDENT_NUMBER

  LEFT JOIN 
  ALLSTUDENTS AS STUD
  ON PARCC.[State Student Identifier] = STUD.STATE_ID

  --WHERE [State Student Identifier] != 'null'

  --ORDER BY STATE_STUDENT_NUMBER
GO


