USE
ST_Production
GO

SELECT
	LOCATION
	,ORG.ORGANIZATION_NAME AS SCHOOL_LOCATION
	,SCH_YR_1
	,Student_Exemptions_2015
	,[2015 Students Tested]
	,[2015 % of Opt Outs]
	,SCH_YR_2
	,Student_Exemptions_2016
	,[2016 STUDENTS TESTED]
	,[2016 % of Opt Outs]
	,DIFDIF
FROM
(
SELECT
	CASE WHEN SCHOOL_LOCATION IS NULL THEN LOC2
	     WHEN LOC2 IS NULL THEN SCHOOL_LOCATION
		 ELSE SCHOOL_LOCATION
	END AS LOCATION
	--,ORG.ORGANIZATION_NAME AS SCHOOL_LOCATION
	,SCH_YR_1
	,Student_Exemptions_2015
	,[2015 Students Tested]
	,[2015 % of Opt Outs]
	,'2016' AS SCH_YR_2
	,Student_Exemptions_2016
	,[2016 STUDENTS TESTED]
	,[2016 % of Opt Outs]
	,DIFDIF
	--,CASE WHEN ORG.ORGANIZATION_NAME LIKE '%ELEMENTARY SCHOOL' THEN '1'
	--      WHEN ORG.ORGANIZATION_NAME LIKE '%MIDDLE SCHOOL' THEN '2'
	--	  WHEN ORG.ORGANIZATION_NAME LIKE '%HIGH SCHOOL' THEN '3'
	--END AS SCHOOL_TYPE
FROM
(
SELECT
	SCHOOL_LOCATION AS SCHOOL_LOCATION
	,LOC2
	,'2015' AS SCH_YR_1
	,Student_Exemptions_2015
	,[2015 Students Tested]
	,[2015 % of Opt Outs]
	,'2016' AS SCH_YR_2
	,Student_Exemptions_2016
	,[2016 STUDENTS TESTED]
	,[2016 % of Opt Outs]
	,CASE WHEN [2015 % of Opt Outs] = 0 THEN [2016 % of Opt Outs]
	      WHEN [2016 % of Opt Outs] = 0 THEN [2016 % of Opt Outs]-[2015 % of Opt Outs]
		  WHEN [2015 % of Opt Outs] > [2016 % of Opt Outs] THEN [2016 % of Opt Outs]-[2015 % of Opt Outs]
		  WHEN [2016 % of Opt Outs] > [2015 % of Opt Outs] THEN [2016 % of Opt Outs]-[2015 % of Opt Outs]
		  --ELSE 100*([2016 % of Opt Outs]-[2015 % of Opt Outs]/[2015 % of Opt Outs])
	END AS DIFDIF
	--,DIFFERENCE ([2016 % of Opt Outs],[2015 % of Opt Outs]) AS CHANGE
	--,CASE WHEN [2015 % of Opt Outs] != 0 THEN 100*[2016 % of Opt Outs]-[2015 % of Opt Outs]/[2015 % of Opt Outs]
	--ELSE [2016 % of Opt Outs]
	--END  AS PDIF
	--,CASE WHEN [2016 % of Opt Outs]>[2015 % of Opt Outs] THEN [2016 % of Opt Outs]-[2015 % of Opt Outs]
	--      WHEN [2016 % of Opt Outs]<[2015 % of Opt Outs] THEN [2015 % of Opt Outs]-[2016 % of Opt Outs]
	--END AS PDDIF
FROM
(
SELECT
	SCHOOL_LOCATION
	,SCH_YR
	,CASE WHEN Student_Exemptions_2015 IS NULL THEN 0 ELSE Student_Exemptions_2015
	END AS Student_Exemptions_2015
	,CASE WHEN STUDS1 IS NULL THEN 0 ELSE STUDS1
	END AS '2015 Students Tested'
	,CASE WHEN [2015 % of Opt Outs] IS NULL THEN 0 ELSE [2015 % of Opt Outs]
	END AS [2015 % of Opt Outs]
	,LOC2
	,SCH_YR2
	,CASE WHEN Student_Exemptions_2016 IS NULL THEN 0 ELSE Student_Exemptions_2016
	END AS Student_Exemptions_2016
	,CASE WHEN STUDS IS NULL THEN 0 ELSE STUDS
	END AS '2016 STUDENTS TESTED'
	,CASE WHEN [2016 % of Opt Outs] IS NULL THEN 0 ELSE [2016 % of Opt Outs]
	END AS [2016 % of Opt Outs]
FROM
(
SELECT
	OPTS.SCHOOL_LOCATION
	,OPTS.SCH_YR
	,OPTS.Student_Exemptions AS Student_Exemptions_2015
	,SCH_COUNTS.STUDS AS STUDS1
	,CAST((100*OPTS.Student_Exemptions+0.0)/(SCH_COUNTS.STUDS+0.0) AS decimal(4,2)) AS '2015 % of Opt Outs'
	,TTTS.SCHOOL_LOCATION AS LOC2
	,TTTS.SCH_YR AS SCH_YR2
	,TTTS.Student_Exemptions AS Student_Exemptions_2016
	,TTTS.STUDS
	,CAST((100*TTTS.Student_Exemptions+0.0)/(TTTS.STUDS+0.0) AS decimal(4,2)) AS '2016 % of Opt Outs'
FROM
(
SELECT 
       OO.SCHOOL_LOCATION
       ,OO.SCH_YR
       --,count(*) AS Assessment_Exemptions
       ,CAST(count(distinct [oo].[STUDENT_GU])AS INT) as Student_Exemptions

  FROM
       [rev].[UD_OPT_OUT] AS [oo]
	   JOIN
	   APS.LookupTable('REVELATION.UD.OPTOUT','ASSESSMENT') OOA
	   ON OO.ASSESSMENT = OOA.VALUE_CODE

WHERE
      OO.SCH_YR = '2015'
	  AND END_DATE IS NULL
	  AND SCHOOL_LOCATION IS NOT NULL
	  AND VALUE_DESCRIPTION LIKE 'PARCC%'
	  AND SCHOOL_LOCATION IS NOT NULL

GROUP BY
	ROLLUP(SCHOOL_LOCATION),SCH_YR
) AS OPTS
JOIN
(
SELECT 
	CAST(COUNT (ENR.STUDENT_GU)AS INT) STUDS
	--,ENR.ORGANIZATION_GU
	--,ENR.YEAR_GU
	--,ENR.LEAVE_DATE
	--,GRADE.VALUE_DESCRIPTION GRADE
	,SCH.SCHOOL_CODE
	,ORG.ORGANIZATION_NAME 
	--,ENR.EXCLUDE_ADA_ADM
FROM APS.EnrollmentsForYear('F7D112F7-354D-4630-A4BC-65F586BA42EC') ENR

LEFT JOIN rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade 
	 ON grade.VALUE_CODE = ENR.GRADE

JOIN REV.REV_ORGANIZATION AS ORG
     ON ORG.ORGANIZATION_GU = ENR.ORGANIZATION_GU

JOIN REV.EPC_SCH AS SCH
	 ON SCH.ORGANIZATION_GU = ENR.ORGANIZATION_GU

WHERE LEAVE_DATE IS NULL AND EXCLUDE_ADA_ADM IS NULL
      AND GRADE.VALUE_DESCRIPTION IN ('03','04','05','06','07','08','09','10','11')

GROUP BY ORGANIZATION_NAME, SCHOOL_CODE
) AS SCH_COUNTS
ON SCH_COUNTS.SCHOOL_CODE = OPTS.SCHOOL_LOCATION

FULL OUTER JOIN

(

SELECT
	OPTS.SCHOOL_LOCATION
	,OPTS.SCH_YR
	,Student_Exemptions
	,SCH_COUNTS.STUDS
	,CAST((100*OPTS.Student_Exemptions+0.0)/(SCH_COUNTS.STUDS+0.0) AS decimal(4,2)) AS '% of Opt Outs'
FROM
(
SELECT 
       OO.SCHOOL_LOCATION
       ,OO.SCH_YR
       --,count(*) AS Assessment_Exemptions
       ,CAST(count(distinct [oo].[STUDENT_GU])AS INT) as Student_Exemptions

  FROM
       [rev].[UD_OPT_OUT] AS [oo]
	   JOIN
	   APS.LookupTable('REVELATION.UD.OPTOUT','ASSESSMENT') OOA
	   ON OO.ASSESSMENT = OOA.VALUE_CODE

WHERE
      OO.SCH_YR = '2016'
	  AND END_DATE IS NULL
	  AND SCHOOL_LOCATION IS NOT NULL
	  AND VALUE_DESCRIPTION LIKE 'PARCC%'
	  AND SCHOOL_LOCATION IS NOT NULL

GROUP BY
	ROLLUP(SCHOOL_LOCATION),SCH_YR
) AS OPTS
JOIN
(
SELECT 
	CAST(COUNT (ENR.STUDENT_GU)AS INT) STUDS
	--,ENR.ORGANIZATION_GU
	--,ENR.YEAR_GU
	--,ENR.LEAVE_DATE
	--,GRADE.VALUE_DESCRIPTION GRADE
	,SCH.SCHOOL_CODE
	,ORG.ORGANIZATION_NAME 
	--,ENR.EXCLUDE_ADA_ADM
FROM APS.EnrollmentsForYear('BCFE2270-A461-4260-BA2B-0087CB8EC26A') ENR

LEFT JOIN rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade 
	 ON grade.VALUE_CODE = ENR.GRADE

JOIN REV.REV_ORGANIZATION AS ORG
     ON ORG.ORGANIZATION_GU = ENR.ORGANIZATION_GU

JOIN REV.EPC_SCH AS SCH
	 ON SCH.ORGANIZATION_GU = ENR.ORGANIZATION_GU

WHERE LEAVE_DATE IS NULL AND EXCLUDE_ADA_ADM IS NULL
      AND GRADE.VALUE_DESCRIPTION IN ('03','04','05','06','07','08','09','10','11')

GROUP BY SCHOOL_CODE, ORGANIZATION_NAME
) AS SCH_COUNTS
ON SCH_COUNTS.SCHOOL_CODE = OPTS.SCHOOL_LOCATION

) AS TTTS
ON TTTS.SCHOOL_LOCATION = OPTS.SCHOOL_LOCATION
) YRS
)DIFF
)TOTS
)SCHS
JOIN
REV.EPC_SCH AS SCH
ON SCH.SCHOOL_CODE = SCHS.LOCATION

JOIN
REV.REV_ORGANIZATION AS ORG
ON ORG.ORGANIZATION_GU = SCH.ORGANIZATION_GU

--ORDER BY SCHOOL_TYPE, ORG.ORGANIZATION_NAME