WITH PARCC_FAILL_1415 AS
(
SELECT * FROM
(
SELECT 
	   --ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER, TEST_NAME ORDER BY TEST_SCORE DESC) AS RN
	   PERSON.FIRST_NAME
       ,PERSON.LAST_NAME
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
	   ,GRADE.VALUE_DESCRIPTION AS GRADE
	   ,ORG.ORGANIZATION_NAME
       ,TEST.TEST_NAME
	   ,PART.PART_DESCRIPTION
	   ,TEST.TEST_LEVEL
	   ,TEST.TEST_FORM
	   ,'' AS SCHOOL_YEAR
	   ,'' AS TEST_DESCRIPTION
	   ,TEST.TEST_TYPE
	   ,TEST.TEST_GROUP
	   ,TEST.TEST_DEF_CODE
       --,PART.PART_DESCRIPTION
       ,SCORE_DESCRIPTION
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
       ,PART.PART_NUMBER
	   ,TST_GRPYT.TEST_REQ_MIN_SCORE
	   ,TST_GRPY.TEST_GROUP_NAME
	   ,DEF_GRPYT.TEST_ATTEMPTS_MIN
	   ,GRPYT_PL.PERFORMANCE_LEVEL
	   ,StudentTest.STUDENT_GU
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

       INNER JOIN
       rev.REV_PERSON AS Person
       ON Person.PERSON_GU = StudentTest.STUDENT_GU

       LEFT JOIN
       APS.EnrollmentsForYear ('26F066A3-ABFC-4EDB-B397-43412EDABC8B') AS Enroll
       ON
       StudentTest.STUDENT_GU = Enroll.STUDENT_GU

       --LEFT JOIN
       --rev.REV_ORGANIZATION_YEAR AS OrgYear
       --ON
       --OrgYear.ORGANIZATION_GU = Enroll.ORGANIZATION_GU

       LEFT JOIN
       rev.REV_ORGANIZATION AS Org
       ON
       Enroll.ORGANIZATION_GU = Org.ORGANIZATION_GU

       LEFT JOIN
       APS.LookupTable('K12','Grade') AS GradeLevel
       ON
       Enroll.GRADE = GradeLevel.VALUE_CODE

	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_TST_GRPYT AS TST_GRPYT
	   ON
	   TEST.TEST_GU = TST_GRPYT.TEST_GU
	   AND PART.TEST_PART_GU = TST_GRPYT.TEST_PART_GU
	   
	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_TST_GRPY AS TST_GRPY
	   ON 
	   TST_GRPY.GRAD_REQ_DEF_TST_GRPY_GU = TST_GRPYT.GRAD_REQ_DEF_TST_GRPY_GU

	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_GRPYT_REQ AS DEF_GRPYT
	   ON
	   DEF_GRPYT.TEST_GU = TEST.TEST_GU
	   AND DEF_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU = TST_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU

	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_GRPYT_PL AS GRPYT_PL
	   ON GRPYT_PL.GRAD_REQ_DEF_TST_GRPTY_GU = DEF_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU

	   LEFT JOIN
	   rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade ON grade.VALUE_CODE = Enroll.GRADE
WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME NOT LIKE ' ES '
	   AND TEST_NAME LIKE '%parc%'

       --AND SIS_NUMBER = '104570981'
       --AND SCORE_DESCRIPTION IN ('Overall LP')
	   --AND TEST_SCORE != 'NA'
       --AND TEST_NAME = 'EOC Music 9 12 V001'
) AS T1
WHERE 1 = 1
--AND RN = 1
AND ADMIN_DATE = '2015-04-01 00:00:00'
AND PL NOT IN ('EXEX','METX','PASS')
--ORDER BY SIS_NUMBER,ADMIN_DATE, PART_DESCRIPTION, SCORE_DESCRIPTION
--AND SIS_NUMBER = '114291'
--ORDER BY  SIS_NUMBER
--ORDER BY TEST_SCORE
)
, PARCC_PASS_1516 AS
(
SELECT * FROM
(
SELECT 
	   --ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER, TEST_NAME ORDER BY TEST_SCORE DESC) AS RN
	   PERSON.FIRST_NAME
       ,PERSON.LAST_NAME
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
	   ,GRADE.VALUE_DESCRIPTION AS GRADE
	   ,ORG.ORGANIZATION_NAME
       ,TEST.TEST_NAME
	   ,PART.PART_DESCRIPTION
	   ,TEST.TEST_LEVEL
	   ,TEST.TEST_FORM
	   ,'' AS SCHOOL_YEAR
	   ,'' AS TEST_DESCRIPTION
	   ,TEST.TEST_TYPE
	   ,TEST.TEST_GROUP
	   ,TEST.TEST_DEF_CODE
       --,PART.PART_DESCRIPTION
       ,SCORE_DESCRIPTION
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
       ,PART.PART_NUMBER
	   ,TST_GRPYT.TEST_REQ_MIN_SCORE
	   ,TST_GRPY.TEST_GROUP_NAME
	   ,DEF_GRPYT.TEST_ATTEMPTS_MIN
	   ,GRPYT_PL.PERFORMANCE_LEVEL
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

       INNER JOIN
       rev.REV_PERSON AS Person
       ON Person.PERSON_GU = StudentTest.STUDENT_GU

       LEFT JOIN
       APS.EnrollmentsForYear ('BCFE2270-A461-4260-BA2B-0087CB8EC26A') AS Enroll
       ON
       StudentTest.STUDENT_GU = Enroll.STUDENT_GU

       LEFT JOIN
       rev.REV_ORGANIZATION_YEAR AS OrgYear
       ON
       OrgYear.ORGANIZATION_GU = Enroll.ORGANIZATION_GU

       LEFT JOIN
       rev.REV_ORGANIZATION AS Org
       ON
       OrgYear.ORGANIZATION_GU = Org.ORGANIZATION_GU

       LEFT JOIN
       APS.LookupTable('K12','Grade') AS GradeLevel
       ON
       Enroll.GRADE = GradeLevel.VALUE_CODE

	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_TST_GRPYT AS TST_GRPYT
	   ON
	   TEST.TEST_GU = TST_GRPYT.TEST_GU
	   AND PART.TEST_PART_GU = TST_GRPYT.TEST_PART_GU
	   
	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_TST_GRPY AS TST_GRPY
	   ON 
	   TST_GRPY.GRAD_REQ_DEF_TST_GRPY_GU = TST_GRPYT.GRAD_REQ_DEF_TST_GRPY_GU

	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_GRPYT_REQ AS DEF_GRPYT
	   ON
	   DEF_GRPYT.TEST_GU = TEST.TEST_GU
	   AND DEF_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU = TST_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU

	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_GRPYT_PL AS GRPYT_PL
	   ON GRPYT_PL.GRAD_REQ_DEF_TST_GRPTY_GU = DEF_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU

	   LEFT JOIN
	   rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade ON grade.VALUE_CODE = Enroll.GRADE



WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME NOT LIKE ' ES '
	   AND TEST_NAME LIKE '%parc%'
       --AND SIS_NUMBER = '102955598'
       --AND SCORE_DESCRIPTION IN ('Overall LP')
	   --AND TEST_SCORE != 'NA'
       --AND TEST_NAME = 'EOC Music 9 12 V001'
) AS T1
WHERE 1 = 1
--AND RN = 1
AND ADMIN_DATE = '2016-03-15 00:00:00'
AND PL IN ('EXEX','METX','PASS')


--ORDER BY SIS_NUMBER,ADMIN_DATE, PART_DESCRIPTION, SCORE_DESCRIPTION
--AND SIS_NUMBER = '104570981'
--ORDER BY  SIS_NUMBER
--ORDER BY TEST_SCORE
)
SELECT
	*
FROM
(
SELECT
	DISTINCT
	ROW_NUMBER () OVER (PARTITION BY FAIL.SIS_NUMBER ORDER BY FAIL.SIS_NUMBER) AS RN
	,FAIL.LAST_NAME
	,FAIL.FIRST_NAME
	,FAIL.SIS_NUMBER
	,PE.SCHOOL_CODE AS CURRENT_SCHOOL
	,PE.SCHOOL_NAME AS CURRENT_SCHOOL_NAME
	,PE.SCHOOL_YEAR
	,FAIL.ORGANIZATION_NAME AS SCHOOL_1415
	,pss.ORGANIZATION_NAME AS SCHOOL_1516
	,FAIL.GRADE AS GRADE_1415
	,PSS.GRADE AS GRADE_1516
	,FAIL.TEST_NAME
	,FAIL.TEST_GROUP
	,FAIL.TEST_GROUP_NAME
	,FAIL.TEST_SCORE AS TEST_SCORE_1415
	,PSS.TEST_SCORE AS TEST_SCORE_1516
	,FAIL.PL AS PL_1415
	,PSS.PL AS PL_1516
	
FROM
	PARCC_FAILL_1415 AS FAIL

	LEFT JOIN
	PARCC_PASS_1516 AS PSS
	ON FAIL.SIS_NUMBER = PSS.SIS_NUMBER
	AND FAIL.TEST_NAME = PSS.TEST_NAME

	LEFT JOIN
	APS.PrimaryEnrollmentDetailsAsOf (GETDATE()) AS PE
	ON PE.STUDENT_GU = FAIL.STUDENT_GU

	where 1 = 1
	AND pss.TEST_SCORE is not null
	AND FAIL.TEST_GROUP = '10'
) AS PASSED
WHERE 1 = 1
AND RN = 1
	ORDER BY SIS_NUMBER

