

/**
 * 
 * $LastChangedBy: Frank Garcia
 * $LastChangedDate: 4/5/2013 $
 *
 * Request By: SYNERGY CONVERSION
 * InitialRequestDate: 
 * 
 * Initial Request:
 * 
 * PARENT TEMPLATE CONVERSION
 * 
 *
 *	NOTES:  Synergy Parent template spells CUSTODY 'CUSTORY'
 *
 * 
 */

USE
PR
GO

DECLARE @SynergyParent

		TABLE
		(
		 SIS_NUMBER NVARCHAR(20)
		 ,RELATION_TYPE NVARCHAR(5)
		 ,LAST_NAME	nvarchar(60)
		 ,FIRST_NAME	nvarchar(60)
		 ,MIDDLE_NAME	nvarchar(20)
		 ,SUFFIX	nvarchar(10)
		 ,HOME_ADDRESS	nvarchar(50)
		 ,HOME_CITY	nvarchar(50)
		 ,HOME_STATE	nvarchar(5)
		 ,HOME_ZIPCODE	nvarchar(6)
		 ,MAIL_ADDRESS	nvarchar(50)
		 ,MAIL_CITY	nvarchar(50)
		 ,MAIL_STATE	nvarchar(5)
		 ,MAIL_ZIPCODE	nvarchar(6)
		 ,PHONE	nvarchar(10)
		 ,PHONE_TYPE	nvarchar(20)
		 ,PHONE_EXTN	nvarchar(5)
		 ,PHONE_LISTED	varchar(1) DEFAULT ''
		 ,PHONE_CONTACT	varchar(1) DEFAULT ''
		 ,PHONE_PRIMARY	varchar(1) DEFAULT ''
		 ,PHONE2	nvarchar(10)
		 ,PHONE2_TYPE	nvarchar(20)
		 ,PHONE2_EXTN	nvarchar(5)
		 ,PHONE2_LISTED	varchar(1) DEFAULT ''
		 ,PHONE2_CONTACT	varchar(1) DEFAULT ''
		 ,PHONE2_PRIMARY	varchar(1) DEFAULT ''
		 ,PHONE3	nvarchar(10)
		 ,PHONE3_TYPE	nvarchar(20)
		 ,PHONE3_EXTN	nvarchar(5)
		 ,PHONE3_LISTED	varchar(1) DEFAULT ''
		 ,PHONE3_CONTACT	varchar(1) DEFAULT ''
		 ,PHONE3_PRIMARY	varchar(1) DEFAULT ''
		 ,PHONE4	nvarchar(10)
		 ,PHONE4_TYPE	nvarchar(20)
		 ,PHONE4_EXTN	nvarchar(5)
		 ,PHONE4_LISTED	varchar(1) DEFAULT ''
		 ,PHONE4_CONTACT	varchar(1) DEFAULT ''
		 ,PHONE4_PRIMARY	varchar(1) DEFAULT ''
		 ,GENDER	nvarchar(5)
		 ,ETHNIC_CODE	nvarchar(5)
		 ,RACE1	nvarchar(5)
		 ,RACE2	nvarchar(5)
		 ,RACE3	nvarchar(5)
		 ,RACE4	nvarchar(5)
		 ,RACE5	nvarchar(5)
		 ,HISPANIC_INDICATOR	varchar(1) DEFAULT ''
		 ,BIRTHDATE	datetime
		 ,BIRTHPLACE	nvarchar(30)
		 ,SOCIAL_SECURITY_NUMBER	nvarchar(10)
		 ,PRIMARY_LANGUAGE	nvarchar(5)
		 ,US_CITIZEN	varchar(1) DEFAULT ''
		 ,E_MAIL	nvarchar(100)
		 ,TITLE	nvarchar(10)
		 ,EMPLOYER	nvarchar(40)
		 ,JOB_TITLE	nvarchar(50)
		 ,ADDITIONALINFO	nvarchar(50)
		 ,COMMENT	ntext
		 ,CONTACT_ALLOWED	varchar(1) DEFAULT ''
		 ,EDUCATIONAL_RIGHTS	varchar(1) DEFAULT ''
		 ,HAS_CUSTORY	varchar(1) DEFAULT ''
		 ,LIVES_WITH	varchar(1) DEFAULT ''
		 ,MAILINGS_ALLOWED	varchar(1) DEFAULT ''
	 	 ,ORDERBY	numeric(2,0)
		 ,EDUCATION_CODE	nvarchar(5)
		 ,WORK_ADDRESS	nvarchar(50)
		  ,WORK_CITY	nvarchar(50)
		 ,WORK_STATE	nvarchar(5)
		 ,WORK_ZIPCODE	nvarchar(6)
		 ,FEEDER_DISTRICT_ID	nvarchar(10)
		 ,FEEDER_STUDENT_ID	nvarchar(20)
		 ,RELEASE_TO	varchar(1) DEFAULT ''
		 ,ENROLLING_PARENT	varchar(1) DEFAULT ''
		 --,HH_NBR numeric
		 --,FAM_NBR numeric
		 )
		 
INSERT INTO @SynergyParent

SELECT
	SIS_NUMBER
	,RELATION_TYPE
	,LAST_NAME
	,FIRST_NAME
	,MIDDLE_NAME
	,SUFFIX
	,HOME_ADDRESS
	,HOME_CITY
	,HOME_STATE
	,HOME_ZIPCODE
	,MAIL_ADDRESS
	,MAIL_CITY
	,MAIL_STATE
	,MAIL_ZIPCODE
    ,PHONE
	,PHONE_TYPE
	,PHONE_EXTN
	,PHONE_LISTED
	,PHONE_CONTACT
	,PHONE_PRIMARY
	,PHONE2
	,PHONE2_TYPE
	,PHONE2_EXTN
	,PHONE2_LISTED
	,PHONE2_CONTACT
	,PHONE2_PRIMARY
	,PHONE3
	,PHONE3_TYPE
	,PHONE3_EXTN
	,PHONE3_LISTED
	,PHONE3_CONTACT
	,PHONE3_PRIMARY
	,PHONE4
	,PHONE4_TYPE
	,PHONE4_EXTN
	,PHONE4_LISTED
	,PHONE4_CONTACT
	,PHONE4_PRIMARY
	,GENDER
	,ETHNIC_CODE
	,RACE1
	,RACE2
	,RACE3
	,RACE4
	,RACE5
	,HISPANIC_INDICATOR
	,BIRTHDATE
	,BIRTHPLACE
	,SOCIAL_SECURITY_NUMBER
	,PRIMARY_LANGUAGE
	,US_CITIZEN
	,E_MAIL
	,TITLE
	,EMPLOYER
	,JOB_TITLE
	,ADDITIONALINFO
	,COMMENT
	,CONTACT_ALLOWED
	,EDUCATIONAL_RIGHTS
	,HAS_CUSTORY
	,LIVES_WITH
	,MAILINGS_ALLOWED
	,ORDERBY
	,EDUCATION_CODE
	,WORK_ADDRESS
	,WORK_CITY
	,WORK_STATE
	,WORK_ZIPCODE
	,FEEDER_DISTRICT_ID
	,FEEDER_STUDENT_ID
	,RELEASE_TO
	,ENROLLING_PARENT
	--,HH_NBR  -- FOR INFORMATIONAL PURPOSES
	--,FAM_NBR  -- FOR INFORMATIONAL PURPOSES
	
FROM
	(
	SELECT
	ROW_NUMBER () OVER (PARTITION BY FAMILY.ID_NBR ORDER BY FAMILY.PRIM_FAM DESC, PARENT.HH_NBR) AS ORDERBY	
	,FAMILY.ID_NBR AS SIS_NUMBER
	--,FAMILY.FAM_NBR AS FAM_NBR  -- FOR INFORMATIONAL PURPOSES
	--,PARENT.HH_NBR  -- FOR INFORMATIONAL PURPOSES
	
	-- As per Jude Garcia, family members whose relationship is blank should be given the caregiver relationhip
	,CASE
		WHEN PARENT.HH_NBR = 1 AND FAMILY.RLTN_HH1 != 0  THEN FAMILY.RLTN_HH1
		WHEN PARENT.HH_NBR = 2 AND FAMILY.RLTN_HH2 != 0  THEN FAMILY.RLTN_HH2 
		ELSE 22
		END
		AS RELATION_TYPE
		
	--,FAMILY.RLTN_HH2  -- FOR INFORMATIONAL PURPOSES
	--,FAMILY.HH_LGL  -- FOR INFORMATIONAL PURPOSES
	,APS.FormatTitleCase (PARENT.LST_NME) AS LAST_NAME
	,APS.FormatTitleCase (PARENT.FRST_NME) AS FIRST_NAME
	,PARENT.M_NME AS MIDDLE_NAME
	,'' AS SUFFIX
	--,FAMILY.PRIM_FAM AS PRIMARY_FAMILY  -- FOR INFORMATIONAL PURPOSES

	--------DWELLING ADDRESS-----------------------------------------------------------------------------------
	,REPLACE(REPLACE(REPLACE(
	ISNULL(CASE WHEN DWELL IS NULL THEN '' ELSE APS.FormatTitleCase(DWL_ADDR) END, '') 
	, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')
	AS HOME_ADDRESS
	
	,ISNULL(CASE WHEN DWELL IS NULL THEN '' ELSE APS.FormatTitleCase(GOODDWELL.CITY) END, '') AS HOME_CITY
	,ISNULL(CASE WHEN DWELL IS NULL THEN '' ELSE GOODDWELL.STATE END, '')	AS HOME_STATE
	--The ZIP is already formatted in the Family Information Read
	,CASE WHEN DWELL IS NULL THEN '' ELSE LEFT(GOODDWELL.ZIP_CD, 5) END AS HOME_ZIPCODE
	
	----------COMPARE DWELLING ADDRESS AND MAILING ADDRESS-----------------------------------------------------
	,ISNULL(CASE WHEN 
		REPLACE(REPLACE(REPLACE(
		ISNULL(CASE WHEN MAIL.ADDR_LNE_1 IS NULL THEN '' ELSE APS.FormatTitleCase(DWL_ADDR) END, '')
		, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')
	!= ISNULL(CASE WHEN GOODMAIL.FAM_NBR IS NULL THEN '' ELSE APS.FormatTitleCase(GOODMAIL.ADDR_LNE1) END, '') 
	THEN APS.FormatTitleCase(GOODMAIL.ADDR_LNE1) ELSE '' END,'') AS MAIL_ADDRESS	
	
	,ISNULL(CASE WHEN 
		REPLACE(REPLACE(REPLACE(
		ISNULL(CASE WHEN DWELL IS NULL THEN '' ELSE APS.FormatTitleCase(DWL_ADDR) END, '')
		, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')
	!= ISNULL(CASE WHEN GOODMAIL.FAM_NBR IS NULL THEN '' ELSE  APS.FormatTitleCase(GOODMAIL.CITY) END, '') 
	THEN APS.FormatTitleCase(GOODMAIL.CITY) ELSE ''  END,'')  AS MAIL_CITY
	
	,ISNULL(CASE WHEN 
		REPLACE(REPLACE(REPLACE(
		ISNULL(CASE WHEN DWELL IS NULL THEN '' ELSE APS.FormatTitleCase(DWL_ADDR) END, '')
		, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')
	!= ISNULL(CASE WHEN GOODMAIL.FAM_NBR IS NULL THEN '' ELSE GOODMAIL.STATE END, '') 
	THEN GOODMAIL.STATE ELSE ''  END,'')AS MAIL_STATE

	,ISNULL(CASE WHEN 
		REPLACE(REPLACE(REPLACE(
		ISNULL(CASE WHEN DWELL IS NULL THEN '' ELSE APS.FormatTitleCase(DWL_ADDR) END, '')
		, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')
	!= ISNULL(CASE WHEN GOODMAIL.FAM_NBR IS NULL THEN '' ELSE APS.FormatZip(GOODMAIL.ZIP_CD) END, '') 
	THEN LEFT(GOODMAIL.ZIP_CD, 5) ELSE '' END,'') AS MAIL_ZIPCODE

	---------------------------------------------------------------------------------------------------------------
	
	,CASE
		WHEN MAIL.HM_AREA_CD = 00 THEN '' ELSE CAST (MAIL.HM_AREA_CD AS VARCHAR(3)) + CAST (MAIL.HM_PHNE AS VARCHAR (7)) END AS PHONE
	,CASE 
		WHEN MAIL.HM_PHNE = 00 THEN '' ELSE 'H' END AS PHONE_TYPE
	,'' AS PHONE_EXTN
	
	,CASE 
		  WHEN MAIL.UNLISTED != '' THEN '' 
	      WHEN MAIL.HM_PHNE = 00 THEN ''
	      ELSE 'Y' END AS PHONE_LISTED 
	      
	,CASE WHEN MAIL.HM_PHNE = 0 THEN '' ELSE 'Y' END AS PHONE_CONTACT
	,CASE WHEN MAIL.HM_PHNE = 0 THEN '' ELSE 'Y' END AS PHONE_PRIMARY
	,CASE 
		WHEN PARENT.F1_PHNE = 00 THEN '' 
		ELSE (CAST (PARENT.F1_AREA_CD AS VARCHAR (3))+ CAST (PARENT.F1_PHNE AS VARCHAR (7))) 
		END AS PHONE2
		
	,PARENT.F1_TYPE AS PHONE2_TYPE
	,PARENT.F1_PH_EXT AS PHONE2_EXTN
	,'' AS PHONE2_LISTED
	
	,CASE 
		WHEN PARENT.F1_DAY != '' THEN 'Y' ELSE '' END AS PHONE2_CONTACT
		
	,'' AS PHONE2_PRIMARY
	,CASE 
		WHEN PARENT.F2_PHNE = 00 THEN '' 
		ELSE (CAST (PARENT.F2_AREA_CD AS VARCHAR (3))+ CAST (PARENT.F2_PHNE AS VARCHAR (7))) 
		END AS PHONE3
		
	,PARENT.F2_TYPE AS PHONE3_TYPE
	,'' AS PHONE3_EXTN
	,'' AS PHONE3_LISTED
	,CASE WHEN PARENT.F2_DAY != '' THEN 'Y' ELSE '' END AS PHONE3_CONTACT
	,'' AS PHONE3_PRIMARY
	,CASE 
		WHEN PARENT.F3_PHNE = 00 THEN '' 
		ELSE (CAST (PARENT.F3_AREA_CD AS VARCHAR (3))+ CAST (PARENT.F3_PHNE AS VARCHAR (7))) 
		END AS PHONE4
		
	,PARENT.F3_TYPE AS PHONE4_TYPE
	,'' AS PHONE4_EXTN
	,'' AS PHONE4_LISTED
	,CASE WHEN PARENT.F3_DAY != '' THEN 'Y' ELSE '' END AS PHONE4_CONTACT
	,'' AS PHONE4_PRIMARY
	
	,PARENT.HH_GENDER AS GENDER
	,'' AS ETHNIC_CODE
	,'' AS RACE1
	,'' AS RACE2
	,'' AS RACE3
	,'' AS RACE4
	,'' AS RACE5
	,'' AS HISPANIC_INDICATOR
	,CASE WHEN PARENT.HH_BRTH != 0
		THEN
		CONVERT (VARCHAR(12),PARENT.HH_BRTH, 112) 
		ELSE '' 
		END AS BIRTHDATE
		
	,'' AS BIRTHPLACE
	,'' AS SOCIAL_SECURITY_NUMBER	
	,RIGHT('00'+ CAST(PARENT.HH_LANG_CD AS VARCHAR),3)	AS PRIMARY_LANGUAGE	
	,'' AS US_CITIZEN
	,PARENT.EMAIL AS E_MAIL
	
	,'' AS TITLE
	/* -- PARENT.PRE_NAME HAS TO MANY WEIRD ENTRIES. DON'T USE
	,APS.FormatTitleCase (PARENT.PRE_NME) AS TITLE
	*/
	,CASE WHEN EMPLOYEE.EMP_ABBR IS NOT NULL THEN EMPLOYEE.EMP_ABBR ELSE '' END AS EMPLOYER
	
	--,PARENT.HH_OC_CD AS ACTIVE_MILITARY
	,CASE WHEN PARENT.HH_OC_CD = 'Y' THEN 'ACTIVE MILITARY' ELSE '' END AS JOB_TITLE
	,'' AS ADDITIONALINFO
	,'' AS COMMENT
	
	-- IF 0 NEITHER PARENT LGL 1 = HH1 LGL 2 = HH2 LGL 3 = BOTH LGL
	,CASE WHEN PARENT.HH_NBR = 1 AND FAMILY.RSTRCT_HH1 = '' THEN 'Y'
		  WHEN PARENT.HH_NBR = 2 AND FAMILY.RSTRCT_HH2 = '' THEN 'Y'
		  ELSE ''
		  END AS CONTACT_ALLOWED
		  
	,CASE WHEN FAMILY.HH_LGL != 0 THEN 'Y' ELSE 'N' END AS EDUCATIONAL_RIGHTS
	
	,CASE WHEN FAMILY.HH_LGL = 0 AND (HH_NBR = 1 OR HH_NBR = 2) THEN ''
		  WHEN FAMILY.HH_LGL = 1  AND (HH_NBR = 1) THEN 'Y'
		  WHEN FAMILY.HH_LGL = 2  AND (HH_NBR = 2) THEN 'Y'
		  WHEN FAMILY.HH_LGL = 3 AND (HH_NBR = 1 OR HH_NBR = 2) THEN 'Y'
		  ELSE ''
		  END AS HAS_CUSTORY
		  
	,CASE WHEN FAMILY.LIVE_WITH = 'X' THEN 'Y' ELSE '' END AS LIVES_WITH
	,CASE WHEN FAMILY.LIVE_WITH = 'X' THEN 'Y' ELSE '' END AS MAILINGS_ALLOWED
	
	,'' AS EDUCATION_CODE
	-- SOME PARENTS HAVE AN EDUCATION CODE. DON'T USE!
	--,PARENT.HH_ED_CD AS EDUCATION_CODE
	
	,'' AS WORK_ADDRESS
	,'' AS WORK_CITY
	,'' AS WORK_STATE
	,'' AS WORK_ZIPCODE
	,'' AS FEEDER_DISTRICT_ID
	,'' AS FEEDER_STUDENT_ID
	,CASE WHEN FAMILY.HH_LGL = 0 AND (HH_NBR = 1 OR HH_NBR = 2) AND (FAMILY.RSTRCT_HH1 = 'X' OR FAMILY.RSTRCT_HH2 = 'X') THEN ''
		  WHEN FAMILY.HH_LGL = 1  AND (HH_NBR = 1) AND (FAMILY.RSTRCT_HH1 != 'X') THEN 'Y'
		  WHEN FAMILY.HH_LGL = 2  AND (HH_NBR = 2) AND (FAMILY.RSTRCT_HH2 != 'X') THEN 'Y'
		  WHEN FAMILY.HH_LGL = 3 AND (HH_NBR = 1 AND FAMILY.RSTRCT_HH1 != 'X') OR (HH_NBR = 2 AND FAMILY.RSTRCT_HH2 != 'X') THEN 'Y'
		  ELSE ''
	 END AS  RELEASE_TO
	,'' AS ENROLLING_PARENT

	FROM
		-- JOIN STUDENT TO FAMILY RELATIONSHIP
		--DBTSIS.CE020_V AS STUDENT	
		--LEFT HASH JOIN
		DBTSIS.CE810_V	AS FAMILY
		--ON
		--.ID_NBR = FAMILY.ID_NBR	
		--AND FAMILY.DST_NBR = FAMILY.DST_NBR
				-- JOIN FAMILY NUMBERS
		INNER HASH JOIN
		APS.FamilyInformation AS FAMINFO
		ON
		FAMILY.DST_NBR = FAMINFO.DST_NBR
		AND FAMILY.FAM_NBR = FAMINFO.FAM_NBR
		
		INNER JOIN
		DBTSIS.CE015_V AS PARENT
		ON
		FAMILY.FAM_NBR = PARENT.FAM_NBR
		AND FAMILY.DST_NBR = PARENT.DST_NBR
		
		-- FAMILY INFORMATION	
		INNER JOIN -- ADDED HASH, NO TIME DIFFERENCE
		DBTSIS.CE010 AS MAIL WITH (NOLOCK) 
		ON
		MAIL._Id = FAMINFO.[Family _Id]	
		
		-- GETTING FEDERAL EMPLOYEE INFORMATION
		LEFT JOIN 
		DBTSIS.CE055_V AS EMPLOYEE
		ON
		PARENT.HH_EMP_CD = EMPLOYEE.EMP_CD
		AND FAMILY.DST_NBR = EMPLOYEE.DST_NBR
		
		-- FAMILY DWELLING INFORMATION
		LEFT HASH JOIN
		DBTSIS.CE005_V AS DWELLING
		ON
		MAIL.DWL_NBR = DWELLING.DWL_NBR
		AND FAMILY.DST_NBR = DWELLING.DST_NBR
		
				-------------READ BAD DWELLINGS TO BLANK OUT--------------------------------
		LEFT HASH JOIN  -- REMOVED HASH, RAN ABOUT 20 SEC LONGER
			(
				SELECT
					DWL_NBR AS DWELL
					,LTRIM(HSE_NBR)+' '+STR_NME+' '+STR_TAG+' '+STR_DIR AS DWL_ADDR
					,CITY
					,STATE
					,ZIP_CD
				FROM
					DBTSIS.CE005_V
				WHERE
					DST_NBR = 1
					AND (
						HSE_NBR > ''
						OR STR_NME LIKE '%P.O. BOX%'
						OR STR_NME LIKE '%PO BOX%'
						)
					AND STR_NME NOT LIKE ''
					AND STR_NME NOT LIKE '%ABANDONED%'
					AND STR_NME NOT LIKE '%UNKNOWN%'
					AND ZIP_CD != 0
			) AS GOODDWELL

		ON
		FAMINFO.DWL_NBR = GOODDWELL.[DWELL]
		
		-------------READ BAD MAILING ADDRESSES TO BLANK OUT------------------------
		LEFT HASH JOIN  -- REMOVED HASH, RAN ABOUT 20 SEC LONGER
			(
			SELECT
					LTRIM(ADDR_LNE_1) AS ADDR_LNE1
					,ADDR_LNE_2
					,CITY
					,STATE
					,ZIP_CD
					,FAM_NBR
				FROM
				DBTSIS.CE010_V

				WHERE
					DST_NBR = 1
					AND ADDR_LNE_1 != ''
					AND ADDR_LNE_1 > '001'
					AND ADDR_LNE_1 NOT LIKE '%UNKNOWN%'
					AND ADDR_LNE_1 NOT LIKE '%unknown%'
					AND ADDR_LNE_1 != '1'
					AND ZIP_CD != 0
					AND ADDR_LNE_1 != '999'
					AND ADDR_LNE_1 != '999 999999 SE'
					AND (
						ADDR_LNE_1 < '9995'
						OR
						ADDR_LNE_1 LIKE 'PO BOX%'
						OR ADDR_LNE_1 LIKE 'PO Box%'
						)
			) AS GOODMAIL
		ON
		FAMINFO.FAM_NBR = GOODMAIL.[FAM_NBR]

		
	WHERE 
		FAMILY.DST_NBR = 1	
		
	)AS RN	
	

UPDATE @SynergyParent
SET MAIL_CITY = '', MAIL_STATE = '', MAIL_ZIPCODE = ''
WHERE MAIL_ADDRESS = ''


SELECT
	*
FROM
	@SynergyParent	
