
(
SELECT DISTINCT TEST_NAME
		--FIRST_NAME
		--,LAST_NAME
		--,SIS_NUMBER
		--,TEST_NAME
		----,PL
		--,[2012 Fall]
		--,[2012 Spring]
		--,[2013 Fall]
		--,[2013 Spring]
		--,[2014 Fall]
		--,[2014 Spring]
		--,[2015 Fall]
		--,[2015 Spring]
		--,[2016 Fall]
		--,[2016 Spring] 
		FROM
(
SELECT 
	   --ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_NAME, ADMIN_DATE DESC) AS RN
	   PERSON.FIRST_NAME
       ,PERSON.LAST_NAME
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,CASE WHEN TEST.TEST_NAME = 'PARCC HS Algebra II' THEN 'PARCCALG02'
	         WHEN TEST.TEST_NAME = 'PARCC HS Algebra 1' THEN 'PARCCALG01'
			 WHEN TEST.TEST_NAME = 'PARCC HS ELA/L English 10' THEN 'PARCCELA10'
			 WHEN TEST.TEST_NAME = 'PARCC HS ELA/L English 11' THEN 'PARCCELA11'
			 WHEN TEST.TEST_NAME = 'PARCC HS ELA/L English 9' THEN 'PARCCELA09'
			 WHEN TEST.TEST_NAME = 'PARCC HS Geometry' THEN 'PARCCGEO01'
			 WHEN TEST.TEST_NAME = 'SBA HS Math 2011+' THEN 'SBAMath'
			 WHEN TEST.TEST_NAME = 'SBA HS Reading 2011+' THEN 'SBAReading'
			 WHEN TEST.TEST_NAME = 'SBA HS Science 2011+' THEN 'SBAScience'
			 WHEN TEST.TEST_NAME = 'NMAPA' AND PART_DESCRIPTION = 'MATH' THEN 'NMAPAMath'
			 WHEN TEST.TEST_NAME = 'NMAPA' AND PART_DESCRIPTION = 'READING' THEN 'NMAPAReading'
			 WHEN TEST.TEST_NAME = 'NMAPA' AND PART_DESCRIPTION = 'SCIENCE' THEN 'NMAPAScience'
			 WHEN TEST.TEST_NAME = 'NMAPA' AND PART_DESCRIPTION = 'SOCIAL STUDIES' THEN 'NMAPASocialStudies'
			 ELSE TEST.TEST_NAME
	   END AS TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       --,SCORES.TEST_SCORE
	   ,CASE
			WHEN ADMIN_DATE = '2011-04-01 00:00:00' THEN '2011 Spring'
			WHEN ADMIN_DATE = '2011-10-01 00:00:00' THEN '2011 Fall'
			WHEN ADMIN_DATE = '2012-04-01 00:00:00' THEN '2012 Spring'
			WHEN ADMIN_DATE = '2012-10-01 00:00:00' THEN '2012 Fall'
			WHEN ADMIN_DATE = '2013-04-01 00:00:00' THEN '2013 Spring'
			WHEN ADMIN_DATE = '2013-10-01 00:00:00' THEN '2013 Fall'
			WHEN ADMIN_DATE = '2014-04-01 00:00:00' THEN '2014 Spring'
			WHEN ADMIN_DATE = '2014-10-01 00:00:00' THEN '2014 Fall'
			WHEN ADMIN_DATE = '2015-04-01 00:00:00' THEN '2015 Spring'
			WHEN ADMIN_DATE = '2015-10-01 00:00:00' THEN '2015 Fall'
			WHEN ADMIN_DATE = '2016-03-15 00:00:00' THEN '2016 Spring'
			WHEN ADMIN_DATE = '2016-04-01 00:00:00' THEN '2016 Spring'
		END AS TEST_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest
       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU
       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU
    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU
    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU
    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU
       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU
       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU
       INNER JOIN
       rev.REV_PERSON AS Person
       ON Person.PERSON_GU = StudentTest.STUDENT_GU
       LEFT JOIN
       APS.PrimaryEnrollmentsAsOf(GETDATE()) AS Enroll
       ON
       StudentTest.STUDENT_GU = Enroll.STUDENT_GU
       LEFT JOIN
       rev.REV_ORGANIZATION_YEAR AS OrgYear
       ON
       Enroll.ORGANIZATION_YEAR_GU = OrgYear.ORGANIZATION_YEAR_GU
       LEFT JOIN
       rev.REV_ORGANIZATION AS Org
       ON
       OrgYear.ORGANIZATION_GU = Org.ORGANIZATION_GU
       LEFT JOIN
       APS.LookupTable('K12','Grade') AS GradeLevel
       ON
       Enroll.GRADE = GradeLevel.VALUE_CODE
	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_TST_GRPYT AS TST_GRPYT
	   ON
	   TEST.TEST_GU = TST_GRPYT.TEST_GU
	   AND PART.TEST_PART_GU = TST_GRPYT.TEST_PART_GU
	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_TST_GRPY AS TST_GRPY
	   ON 
	   TST_GRPY.GRAD_REQ_DEF_TST_GRPY_GU = TST_GRPYT.GRAD_REQ_DEF_TST_GRPY_GU
	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_GRPYT_REQ AS DEF_GRPYT
	   ON
	   DEF_GRPYT.TEST_GU = TEST.TEST_GU
	   AND DEF_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU = TST_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU
	   LEFT JOIN
	   REV.EPC_GRAD_REQ_DEF_GRPYT_PL AS GRPYT_PL
	   ON GRPYT_PL.GRAD_REQ_DEF_TST_GRPTY_GU = DEF_GRPYT.GRAD_REQ_DEF_TST_GRPTY_GU
WHERE
1 = 1
--AND SCORE_DESCRIPTION IN ('SCALE')
) AS T1
PIVOT
(MAX(PL) FOR TEST_DATE IN ([2012 Fall],[2012 Spring],[2013 Fall],[2013 Spring],[2014 Fall],[2014 Spring],[2015 Fall],[2015 Spring],[2016 Fall],[2016 Spring])) AS PT1

WHERE 1 = 1
--AND RN = 1
--AND TEST_NAME = 'SBAMath'
)
