	
	SELECT
		*
	FROM
	(
	SELECT 
	   STUDENT_GU
	   ,PARENT_GU
	   ,CASE WHEN ORDERBY IS NULL THEN 0 ELSE ORDERBY END AS ORDERBY
	FROM
	REV.EPC_STU_PARENT
	) AS ST
	pivot
	(max(PARENT_GU) FOR ORDERBY IN ([0],[1],[2],[3],[4],[5],[6],[7],[8])) AS UP1

	ORDER BY [8] DESC
