BEGIN TRAN

DECLARE @SY INT = 2009
DECLARE @SN_SY INT = 2008
DECLARE @PERIOD VARCHAR(10) = '2009-03-01'

UPDATE
	SchoolNet.dbo.[CCR_PLAN]
SET
	SchoolNet.dbo.[CCR_PLAN].APS_ID = STUD.[ALTERNATE STUDENT ID]
	,SchoolNet.dbo.[CCR_PLAN].[SCHOOL YEAR] = @SN_SY
	,SchoolNet.dbo.[CCR_PLAN].school_code = STUD.[LOCATION CODE]
	,SchoolNet.dbo.[CCR_PLAN].test_date_code = '2009-10-01'
	,SchoolNet.dbo.[CCR_PLAN].test_level_name = STUD.[CURRENT GRADE LEVEL]

FROM
	SchoolNet.dbo.[CCR_PLAN] AS P
	LEFT JOIN
	[046-WS02].db_STARS_History.dbo.STUDENT AS STUD
	ON
	P.STID = STUD.[ALTERNATE STUDENT ID]
WHERE
	STUD.[DISTRICT CODE] = 1
	AND STUD.SY = @SY
	AND STUD.PERIOD = @PERIOD
	AND P.APS_ID = ''

ROLLBACK
