USE [Assessments]
GO

SELECT 
	  --[Student Name]
      [APS STUDENT ID]
      ,[STATE ID]
      ,CASE WHEN [PLAN TEST LEVEL] = 'Twelfth Grade' THEN '12'
		    WHEN [PLAN TEST LEVEL] = 'Tenth Grade' THEN '10'
			WHEN [PLAN TEST LEVEL] = 'Eleventh Grade' THEN '11'
			WHEN [PLAN TEST LEVEL] = 'Ninth Grade' THEN '9'
			WHEN [PLAN TEST LEVEL] = 'Continuing YR 1 (SPED ONLY)' THEN 'C1'
			WHEN [PLAN TEST LEVEL] = 'TRANSITION 3RD YEAR' THEN 'T3'
			WHEN [PLAN TEST LEVEL] = 'TRANSITION 2ND YEAR' THEN 'T2'
			WHEN [PLAN TEST LEVEL] = 'TRANSITION 1ST YEAR' THEN 'T1'
			WHEN [PLAN TEST LEVEL] = 'TRANSITION 3RD YEAR' THEN 'T3'
			ELSE [PLAN TEST LEVEL]
	  END AS [PLAN TEST LEVEL]
      ,[PLAN ENGLISH SCALED SCROE] AS 'PLAN ENGLISH SCALED SCORE'
	  ,CASE WHEN [PLAN ENGLISH SCALED SCROE] < '15' THEN 'FAIL' ELSE 'PASS'
	  END AS 'PSAT ENGLISH PERFORMANCE LEVEL'
      ,[PLAN MATH PERFROMANCE LEVEL] AS 'PLAN MATH SCALED SCORE'
	  ,CASE WHEN [PLAN MATH PERFROMANCE LEVEL] < '19' THEN 'FAIL' ELSE 'PASS'
	  END AS 'PLAN MATH PERFORMANCE LEVEL'
      ,[PLAN READING SCALED SCORE]
	  ,CASE WHEN [PLAN READING SCALED SCORE] < '17' THEN 'FAIL' ELSE 'PASS'
	  END AS 'PLAN READING PERFROMANCE LEVEL'
      ,[PLAN SCIENCE SCALED SCORE]
	  ,CASE WHEN [PLAN SCIENCE SCALED SCORE] < '21' THEN 'FAIL' ELSE 'PASS'
	  END AS 'PLAN SCIENCE PERFROMANCE LEVEL'
      ,[PLAN COMPOSITE SCALED SCORE]
	  ,'' AS 'PLAN COMPOSITE PERFORMANCE LEVEL'
  FROM [dbo].[CCR_PLAN_2011-2012]
  ORDER BY [APS STUDENT ID]
GO


