SELECT 
	 PE.SCHOOL_CODE
	 ,PE.GRADE
	 ,PER.FIRST_NAME
	 ,PER.LAST_NAME
	 ,REPLACE(CONVERT(CHAR(10), BS.BIRTH_DATE, 101),'/','') AS birthdate
	 ,BS.RESOLVED_RACE
	 ,BS.GENDER
	 ,BS.STATE_STUDENT_NUMBER
	 ,BS.SIS_NUMBER
FROM APS.PrimaryEnrollmentDetailsAsOf (GETDATE()) AS PE
JOIN
REV.EPC_STU AS STU
ON STU.STUDENT_GU = PE.STUDENT_GU

JOIN
REV.REV_PERSON AS PER
ON PER.PERSON_GU = PE.STUDENT_GU

JOIN
APS.BasicStudentWithMoreInfo AS BS
ON BS.STUDENT_GU = PE.STUDENT_GU