USE [Assessments]
GO
SELECT
	APS_ID
	,SCHOOL
	,TEST_DATE
	,GRADE
	,LATEST_PSAT_EBRW
	,LATEST_PSAT_MATH_SECTION
	,EBRW_PERFORMANCE_LEVEL
	,MATH_PERFORMANCE_LEVEL
FROM
(
SELECT 
	  ROW_NUMBER () OVER (PARTITION BY SECONDARY_ID, [LATEST_PSAT_DATE] ORDER BY [LATEST_PSAT_DATE] DESC) AS RN
	  ,SECONDARY_ID AS APS_ID
	  ,[AI_CODE]
      ,CDS.[PED APS LOC] AS SCHOOL
      ,LATEST_PSAT_DATE AS TEST_DATE
      ,[COHORT_YEAR]
      ,PSAT.[NAME_LAST]
      ,PSAT.[NAME_FIRST]
      ,[NAME_MI]
      ,PSAT.[BIRTH_DATE]
      ,STUD.grade_code AS GRADE
      ,[LATEST_PSAT_TOTAL]
      ,[LATEST_PSAT_EBRW]
      ,[LATEST_PSAT_MATH_SECTION]
	  ,CASE WHEN LATEST_PSAT_EBRW >= '360' THEN 'PASS'
			ELSE 'FAIL'
	  END AS EBRW_PERFORMANCE_LEVEL
	  ,CASE WHEN LATEST_PSAT_MATH_SECTION >= '470' THEN 'PASS'
			ELSE 'FAIL'
	  END AS MATH_PERFORMANCE_LEVEL
      ,[SCH_YR]
	  --BEGIN TRAN
	  --UPDATE [CCR_PSAT_2015-2016] SET SECONDARY_ID = LU.APS_STUDENT_ID
  FROM [dbo].[CCR_PSAT_2015-2016] PSAT

  JOIN
  ALLSTUDENTS AS STUD
  ON STUD.student_code = PSAT.SECONDARY_ID

  LEFT JOIN
  school_codes_ACT_SAT_To_APS AS CDS
  ON CDS.[ACT SAT HS Code] = PSAT.AI_CODE

 -- JOIN
 -- [TRASH_PSAT_2015-2016_ID_LOOKUPS] LU
 -- ON 
	--PSAT.NAME_LAST = LU.NAME_LAST
	--AND PSAT.NAME_FIRST = LU.NAME_FIRST
	--AND PSAT.AI_CODE = CDS.[ACT SAT HS Code]
	--AND PSAT.BIRTH_DATE = LU.BIRTH_DATE
  --ROLLBACK
  WHERE 1 = 1
  --AND [PED APS LOC] > '500'
)T1
--WHERE RN = 1
  ORDER BY SCHOOL
GO


