SELECT
	*
FROM
		(
		SELECT
			ROW_NUMBER () OVER (PARTITION BY DST_NBR, ID_NBR ORDER BY DT_ASSGN DESC) AS RN
			,*
		FROM
			DBTSIS.NM030_V AS PHLOTES
		)
		AS CURRENPHLOTES
WHERE
	RN = 1 AND DST_NBR = 1