USE Assessments
GO


SELECT
	SIS_NUMBER
	,FILE_NAME
FROM
(
SELECT
	  RIGHT('0000'+STU.SIS_NUMBER,12) AS SIS_NUMBER
	  ,[Column 0] AS [FILE_NAME]
      --,[LAST_NAME]
      --,[FIRST_NAME]
      --,[GRADE]
      --,[GUID]
  FROM [dbo].[matchfile] MF

  LEFT JOIN
  [SYNERGYDBDC].ST_PRODUCTION.REV.EPC_STU STU
  ON MF.[Column 4] = CAST(STU.STUDENT_GU AS VARCHAR (50))
  --where GUID = 'FFFEF5CB-2BAD-4C97-BD0B-DCEF67BB7E8A'
) AS T1
--WHERE SIS_NUMBER IS NOT NULL
where FILE_NAME like 'FFEAC725-B068-4589-81F2-8DA8E9E551F2%'
  ORDER BY SIS_NUMBER
GO


