USE [SchoolNetDevelopment]
GO
SELECT
	*
FROM
(
SELECT 
	  ROW_NUMBER () OVER (PARTITION BY [STUDENT #] ORDER BY [STUDENT #]) AS RN
	  ,[LOC NUMBER]
      ,[FIRST NAME]
      ,[LAST NAME]
      ,[STUDENT #]
      ,[GRADE]
      ,[TEST DATE]
      ,[SPEAKING SCALE SCORE]
      ,[LISTENING SCALE SCORE]
      ,[READING  SCALE SCORE]
      ,[WRITING  SCALE SCORE]
      ,[OVER ALL SCALE SCORE]
      ,[COMPREHENSION SCALE SCORE]
      ,[ORAL SCALE SCORE]
      ,[SPEAKING  PROFICIENCY LEVEL]
      ,[LISTENING PROFICIENCY LEVEL]
      ,[READING PROFICIENCY LEVEL]
      ,[WRITING PROFICIENCY  LEVEL]
      ,[OVERALL PROFICIENCY LEVEL]
      ,[COMPREHENSION PROFICIENCY LEVEL]
      ,[ORAL PROFICIENCY LEVEL]
      ,[SCH_YR]
  FROM [dbo].[SP_LAS_LINKS]
  WHERE SCH_YR = '2014-2015'
) AS T1

--WHERE [STUDENT #] IN ('970058329')
WHERE RN > 1

ORDER BY [TEST DATE]
GO


