USE Assessments
GO
SELECT
	GRDE
	,cast (ID_NBR as int) as ID_NBR
	,SCH_NBR
	,SCH_YR
	,SCORE_1
	,SCORE_2
	,SCORE_3
	,TEST_DT
	,TEST_ID
	,TEST_SUB
	,[PROFICIENCY LEVEL]
FROM
(
SELECT 
	  ROW_NUMBER () OVER (PARTITION BY [STUDENT #] ORDER BY [TEST DATE]) AS RN 
	  ,CASE 
		WHEN GRADE = 'K' THEN 'K'
		ELSE RIGHT ('0'+[GRADE],2) 
	  END AS GRDE
      ,[STUDENT #] AS [ID_NBR]
	  ,[LOC NUMBER] AS SCH_NBR
	  ,'2015' AS SCH_YR
	  ,CASE WHEN [OVERALL PROFICIENCY LEVEL] = '' THEN '0' ELSE [OVERALL PROFICIENCY LEVEL] END AS SCORE_1
	  ,CASE WHEN [OVER ALL SCALE SCORE] = '' THEN '0' ELSE [OVER ALL SCALE SCORE] END AS SCORE_2
	  ,CASE WHEN [ORAL SCALE SCORE] = '' THEN '0' ELSE [ORAL SCALE SCORE] END AS SCORE_3
      ,[TEST DATE] AS TEST_DT
	  ,'SPANISH PROF' AS TEST_ID
	  ,'SP-LAS-LINKS' AS TEST_SUB
	  ,CASE
		WHEN [OVERALL PROFICIENCY LEVEL] BETWEEN 1 AND 1.9 THEN 'Beginning' 
		WHEN [OVERALL PROFICIENCY LEVEL] BETWEEN 2 AND 2.9 THEN 'Early Intermediate'
		WHEN [OVERALL PROFICIENCY LEVEL] BETWEEN 3 AND 3.9 THEN 'Intermediate'
		WHEN [OVERALL PROFICIENCY LEVEL] BETWEEN 4 AND 4.9 THEN 'Proficient'
		WHEN [OVERALL PROFICIENCY LEVEL] BETWEEN 5 AND 6.9 THEN  'Above Proficient'
		--WHEN SCORE_1 IN ('5', '6') THEN 'Advanced'
		ELSE 'INCOMPLETE'
	END AS 'PROFICIENCY LEVEL'
      --,[SPEAKING  PROFICIENCY LEVEL]
      --,[LISTENING PROFICIENCY LEVEL]
      --,[READING PROFICIENCY LEVEL]
      --,[WRITING PROFICIENCY  LEVEL]
      
      --,[COMPREHENSION PROFICIENCY LEVEL]
      --,[ORAL PROFICIENCY LEVEL]
      --,[SCH_YR]
  FROM [dbo].[SP_LAS_LINKS]
  WHERE SCH_YR = '2016-2017'
  --AND [STUDENT #] NOT IN ('970106021','970068092')
) AS T1

WHERE 1 = 1
AND RN = 1
--and SCORE_1 != ''
--AND ID_NBR = '970050094'
order by TEST_DT
GO


