USE [Assessments]
GO

SELECT [LOC NUMBER]
      ,[FIRST NAME]
	  ,STUD.last_name
      ,[LAST NAME]
	  ,STUD.first_name
      ,[STUDENT #]
	  ,STUD.student_code
      ,[GRADE]
      ,[TEST DATE]
      ,[SPEAKING SCALE SCORE]
      ,[LISTENING SCALE SCORE]
      ,[READING  SCALE SCORE]
      ,[WRITING  SCALE SCORE]
      ,[OVER ALL SCALE SCORE]
      ,[COMPREHENSION SCALE SCORE]
      ,[ORAL SCALE SCORE]
      ,[SPEAKING  PROFICIENCY LEVEL]
      ,[LISTENING PROFICIENCY LEVEL]
      ,[READING PROFICIENCY LEVEL]
      ,[WRITING PROFICIENCY  LEVEL]
      ,[OVERALL PROFICIENCY LEVEL]
      ,[COMPREHENSION PROFICIENCY LEVEL]
      ,[ORAL PROFICIENCY LEVEL]
      ,[SCH_YR]
  FROM [dbo].[SP_LAS_LINKS] AS LINK
  LEFT JOIN
  ALLSTUDENTS AS STUD
  ON LINK.[STUDENT #] = STUD.student_code
  WHERE SCH_YR = '2015-2016'
  AND LEFT(first_name,3) != LEFT([FIRST NAME],3)
  --AND [STUDENT #] IN ('970079157','970085591','980006169')
  ORDER BY student_code

GO


