

--select * from rev.EPC_TEST_PART AS PART

--WHERE TEST_GU = '683E6CF6-0CD6-4E3D-8305-E025A853F63A'

--SELECT * FROM rev.EPC_STU_TEST_PART AS STU_PART
--WHERE TEST_PART_GU = '66F85721-489B-401D-B420-3AD023F524F7'

SELECT
	CASE WHEN SSY.STUDENT_GU IS NOT NULL THEN 'X'
		ELSE ''
	END AS ENROLLED
	,SOMETHING_SPECIAL.*
FROM
(

SELECT 

	SYN.FIRST_NAME
	,SYN.LAST_NAME
	,SBA.LAST_NAME  FILE_LNAME
	,SBA.FIRST_NAME FILE_FNAME
	,SIS_NUMBER	 AS SYNERGY_SIS_NUMBER  
	,SBA.STUDENT_CODE  FILE_SIS_NUMBER
	,SBA.DOB
	--,SSY.STUDENT_GU
	,TEST_NAME
	,PART_DESCRIPTION
	,SBA.TEST_SECTION_NAME
	,SCORE_DESCRIPTION
	,PERFORMANCE_LEVEL
	,TEST_SCORE
	,SBA.SCALED_SCORE FILE_SSCORE
	,SBA.TEST_DATE_CODE
	,CAST (ADMIN_DATE AS DATE) AS DATES
	,ADMIN_DATE
	,PART_NUMBER
	,STUDENT_GU
FROM
(
SELECT
	PERSON.FIRST_NAME
	,PERSON.LAST_NAME
	,SIS_NUMBER
	,TEST.TEST_NAME
	,PART_DESCRIPTION
	,SCORE_DESCRIPTION
	,STU_PART.PERFORMANCE_LEVEL
	,SCORES.TEST_SCORE
	,STUDENTTEST.ADMIN_DATE
	,PART.PART_NUMBER
	,StudentTest.STUDENT_GU
FROM
	rev.EPC_STU_TEST AS StudentTest

	JOIN
	rev.EPC_TEST_PART AS PART
	ON StudentTest.TEST_GU = PART.TEST_GU

	JOIN
	rev.EPC_STU_TEST_PART AS STU_PART
	ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
	AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

	LEFT JOIN
	rev.EPC_TEST AS TEST
	ON TEST.TEST_GU = StudentTest.TEST_GU

	INNER JOIN
	rev.EPC_STU AS Student
	ON Student.STUDENT_GU = StudentTest.STUDENT_GU

	INNER JOIN
	rev.REV_PERSON AS Person
	ON Person.PERSON_GU = StudentTest.STUDENT_GU

	LEFT JOIN
	APS.PrimaryEnrollmentsAsOf(GETDATE()) AS Enroll
	ON
	StudentTest.STUDENT_GU = Enroll.STUDENT_GU

	LEFT JOIN
	rev.REV_ORGANIZATION_YEAR AS OrgYear
	ON
	Enroll.ORGANIZATION_YEAR_GU = OrgYear.ORGANIZATION_YEAR_GU

	LEFT JOIN
	rev.REV_ORGANIZATION AS Org
	ON
	OrgYear.ORGANIZATION_GU = Org.ORGANIZATION_GU

	LEFT JOIN
	APS.LookupTable('K12','Grade') AS GradeLevel
	ON
	Enroll.GRADE = GradeLevel.VALUE_CODE


WHERE
	TEST_NAME like '%SBA%'
	--AND SIS_NUMBER = '100035039'
	AND SCORE_DESCRIPTION IN ('Scale')


) AS SYN

RIGHT JOIN
	[RDAVM.APS.EDU.ACTD].ASSESSMENTS.DBO.SBA AS SBA
	ON SYN.SIS_NUMBER = SBA.STUDENT_CODE
	AND SYN.PART_DESCRIPTION = SBA.TEST_SECTION_NAME
	AND SYN.TEST_SCORE = SBA.SCALED_SCORE
	AND CAST(SYN.ADMIN_DATE AS DATE) = SBA.TEST_DATE_CODE

WHERE SBA.TEST_SECTION_NAME IN ('MATH','READING','SCIENCE')
--AND SBA.STUDENT_CODE = '100035039'
AND SBA.SCHOOL_YEAR > '2009'
--AND SBA.school_code NOT IN ('006','007','016','017','027','028','047','061','063','069','095','098','7','118','6','035','116','17')
AND SBA.scaled_score NOT LIKE '99%'
) AS SOMETHING_SPECIAL
LEFT JOIN
	(SELECT DISTINCT STUDENT_GU FROM REV.EPC_STU_SCH_YR ) AS SSY
	ON SSY.STUDENT_GU = SOMETHING_SPECIAL.STUDENT_GU	

WHERE SOMETHING_SPECIAL.SYNERGY_SIS_NUMBER IS NULL
ORDER BY 
	test_section_name,FILE_SSCORE

