

SELECT
	ORGANIZATION_NAME
	,Assessment_Exemptions
	,Student_Exemptions
	,SCHOOL_TYPE
	,SCHOOL_YEAR
FROM
(
SELECT
	ORGA.ORGANIZATION_NAME
	,SCH.SCHOOL_CODE
	,CASE WHEN T1.Assessment_Exemptions IS NULL THEN 0 ELSE T1.Assessment_Exemptions
	END AS Assessment_Exemptions
	,CASE WHEN T1.Student_Exemptions IS NULL THEN 0 ELSE T1.Student_Exemptions
	END AS Student_Exemptions
	,CASE WHEN ORGA.ORGANIZATION_NAME LIKE '%MIDDLE SCHOOL' THEN 'MS'
	      WHEN ORGA.ORGANIZATION_NAME LIKE '%ELEMENTARY SCHOOL' THEN 'ES'
		  WHEN ORGA.ORGANIZATION_NAME = 'George I. Sanchez Collaborative Community School' THEN 'ES'
		  WHEN ORGA.ORGANIZATION_NAME LIKE '%HIGH SCHOOL' THEN 'HS'
		  WHEN ORGA.ORGANIZATION_NAME IN ('Juvenile Detention Center','eCADEMY','Nex Gen Academy','eCademy Virtual','BlendED Studio','Career Enrichment Center','Early College Academy') THEN 'AS'
		  WHEN (T1.SCHOOL_LOCATION IS NULL AND T1.Assessment_Exemptions > 0) THEN 'TOTAL'
	END AS SCHOOL_TYPE
	--,OPT.SCHOOL_TYPE
	,T1.SCH_YR
	,YR.SCHOOL_YEAR
FROM

	   REV.EPC_SCH AS SCH

FULL OUTER JOIN

(
SELECT 
       OO.SCHOOL_LOCATION
       ,OO.SCH_YR
       ,count(*) AS Assessment_Exemptions
       ,count(distinct [oo].[STUDENT_GU]) as Student_Exemptions

  FROM
       [rev].[UD_OPT_OUT] AS [oo]

WHERE
      OO.SCH_YR = '2015'
	  AND END_DATE IS NULL
	  AND SCHOOL_LOCATION IS NOT NULL

GROUP BY
	ROLLUP(SCHOOL_LOCATION),SCH_YR
) AS T1
ON T1.SCHOOL_LOCATION = SCH.SCHOOL_CODE
       LEFT JOIN
       REV.REV_YEAR AS YR
       ON YR.SCHOOL_YEAR = T1.SCH_YR
       AND YR.EXTENSION = 'R'

	   LEFT JOIN REV.REV_ORGANIZATION AS ORGA
	   ON ORGA.ORGANIZATION_GU = SCH.ORGANIZATION_GU

       LEFT JOIN
       REV.REV_ORGANIZATION_YEAR AS ORGY
       ON ORGY.ORGANIZATION_GU = ORGA.ORGANIZATION_GU
       AND ORGY.YEAR_GU = YR.YEAR_GU

       LEFT JOIN 
       REV.REV_ORGANIZATION AS ORG
       ON ORG.ORGANIZATION_GU = SCH.ORGANIZATION_GU

       LEFT JOIN
       REV.EPC_SCH_YR_OPT AS OPT
       ON OPT.ORGANIZATION_YEAR_GU = ORGY.ORGANIZATION_YEAR_GU

) OPTS
WHERE (SCHOOL_TYPE IS NOT NULL)
ORDER BY SCHOOL_TYPE, ORGANIZATION_NAME