
BEGIN TRAN

UPDATE
	CCR_ACT
	SET APS_Sch_Code = CODES.[PED APS LOC]
	--WHERE APS_Sch_Code LIKE '320%'
	----WHERE ACT_HS_Code IS NULL
	--AND SCH_YR = '2014-2015'

FROM
	CCR_ACT
LEFT JOIN
	school_codes_ACT_SAT_To_APS AS CODES
	ON CCR_ACT.ACT_HS_Code = CODES.[ACT SAT HS Code]

WHERE 
	SCH_YR = '2014-2015'
	AND CCR_ACT.ACT_HS_Code = APS_Sch_Code

ROLLBACK