SELECT
	   LUTH.[APS ID Number]
      ,LUTH.[FIRST_NAME]
      ,LUTH.[LAST_NAME]
	  ,'WAPT' AS WAPT
	  ,CASE WHEN WAP.ADMIN_DATE IS NULL THEN '' ELSE WAP.ADMIN_DATE END AS 'WAPT Test Date'
	  ,CASE WHEN WAP.TEST_SCORE IS NULL THEN '' ELSE WAP.TEST_SCORE END AS 'WAPT Score'
	  ,CASE WHEN WAP.PL IS NULL THEN '' ELSE WAP.PL END AS 'WAPT Proficiency Level'
	  ,'ACCESS' AS ACCESS
	  ,CASE WHEN ACC.ADMIN_DATE IS NULL THEN '' ELSE ACC.ADMIN_DATE END AS 'ACCESS Test Date'
	  ,CASE WHEN ACC.TEST_SCORE IS NULL THEN '' ELSE ACC.TEST_SCORE END AS 'ACCESS Score'
	  ,CASE WHEN ACC.PL IS NULL THEN '' ELSE ACC.PL END AS 'ACCESS Proficiency Level'
FROM
	[TRASH_Lutheran Family Services Request for SIS - Fall 2015 Data - Rev0] AS LUTH
LEFT JOIN
	TRASH_WENDY_ACCESS_ AS ACC
	ON LUTH.[APS ID Number] = ACC.SIS_NUMBER
LEFT JOIN
	TRASH_WENDY_WAPT_ AS WAP
	ON LUTH.[APS ID Number] = WAP.SIS_NUMBER