
SELECT 
LFS.[APS ID]
,[WAPT SCORE]
,[WAPT PL]
,[WAPT TEST DATE]
,WAPT.[Test Date]
  FROM [dbo].[Lutheran_Family_Services] AS LFS
  LEFT JOIN
	LUTHERIN_WAPT AS WAPTS
	ON LFS.[APS ID] = WAPTS.[APS ID]
 LEFT JOIN
 WAPT
 ON WAPT.IDNum = LFS.[APS ID]
 ORDER BY [WAPT SCORE]



