
BEGIN TRANSACTION

DELETE  REV.EPC_STU_PGM_ELL_HIS

FROM (
	SELECT OLD.SIS_NUMBER, WTF.* FROM 
	(
	SELECT DISTINCT
	HIST.STUDENT_GU,SIS_NUMBER FROM 
	rev.EPC_STU_PGM_ELL_HIS AS HIST
	INNER JOIN 
	REV.EPC_STU AS STU
	ON
	HIST.STUDENT_GU = STU.STUDENT_GU
	) AS OLD

	LEFT JOIN 
	(SELECT STUDENT_GU FROM 
	APS.LCEFirstEvaluationAsOf('20170814') AS GETELL
	WHERE IS_ELL = 1
	) AS NEW
	ON
	NEW.STUDENT_GU = OLD.STUDENT_GU

	LEFT JOIN 
	(SELECT STUDENT_GU, TEST_NAME, ADMIN_DATE, PERFORMANCE_LEVEL FROM 
	APS.LCEFirstEvaluationAsOf('20170814') AS GETELL
	) AS WTF
	ON
	WTF.STUDENT_GU = OLD.STUDENT_GU

	WHERE
	NEW.STUDENT_GU IS NULL
	AND TEST_NAME NOT IN  ('WAPT', 'PRE-LAS', 'SCREENER')

) AS T1

WHERE
T1.STUDENT_GU != REV.EPC_STU_PGM_ELL_HIS.STUDENT_GU

COMMIT

