

SELECT COUNT(*) AS ELL_COUNT, 
SUM(CASE WHEN HIST.PARTICIPATION_STATUS = 6 THEN 1 ELSE 0 END) AS PARENT_REF_COUNT
,SUM(CASE WHEN HIST.PARTICIPATION_STATUS = 8 THEN 1 ELSE 0 END) AS ELEMENTARY_COUNT
,SUM(CASE WHEN HIST.PARTICIPATION_STATUS = 9 THEN 1 ELSE 0 END) AS SECONDARY_COUNT
 FROM 
REV.EPC_STU_PGM_ELL_HIS AS HIST
INNER JOIN 
APS.PrimaryEnrollmentDetailsAsOf('20170814') AS PRIM
ON
HIST.STUDENT_GU = PRIM.STUDENT_GU
WHERE
EXIT_DATE IS NULL

