
SELECT 
	SIS_NUMBER, STATE_STUDENT_NUMBER, HIST.ENTRY_DATE, HIST.EXIT_DATE, EXIT_REASON
FROM 
APS.PrimaryEnrollmentDetailsAsOf('20170814') AS PRIM
INNER JOIN 
REV.EPC_STU_PGM_ELL_HIS AS HIST
ON
PRIM.STUDENT_GU = HIST.STUDENT_GU
INNER JOIN 
REV.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU 

WHERE
EXIT_REASON = 'EY5'
AND ENTRY_DATE = '20170701'
--EXIT_DATE IS NULL
