
/*
	Created by Debbie Ann Chavez
	Date 6/8/2016

	*** THIS HAS A HARD-CODED SCHOOL YEAR *** CHANGE AFTER SCHOOL YEAR HAS ROLLED OVER

*/


ALTER VIEW APS.BusinessSystemsSpedInfo AS


SELECT 
	LAST_NAME, FIRST_NAME,
	ENR.SIS_NUMBER, ENR.GRADE, SCHOOL_CODE, SCHOOL_NAME 
	,ENTER_DATE
	,LEAVE_DATE
	,BS.PRIMARY_DISABILITY_CODE AS EXCEPTIONALITY 
	, GIFTED_STATUS
	,SPED.EXIT_DATE AS IEP_EXIT_DATE

   FROM
        REV.EP_STUDENT_SPECIAL_ED AS SPED
		INNER JOIN
		rev.EPC_STU AS STU
		ON
		SPED.STUDENT_GU = STU.STUDENT_GU
		INNER JOIN 
		APS.StudentEnrollmentDetails AS ENR
		ON
		STU.STUDENT_GU = ENR.STUDENT_GU
		
INNER HASH JOIN 
APS.BasicStudentWithMoreInfo AS BS
ON
ENR.STUDENT_GU = BS.STUDENT_GU


WHERE
SCHOOL_YEAR = 2016
AND EXTENSION = 'R'
AND EXCLUDE_ADA_ADM IS NULL

