
/********************************************************************************
	CREATED BY DEBBIE ANN CHAVEZ
	DATE 11/22/2016

	This pulls students that have the SAME STATE ID

*********************************************************************************/

CREATE VIEW APS.StudentsSameStateID AS

SELECT STU2.SIS_NUMBER, STU2.STATE_STUDENT_NUMBER, LAST_NAME, FIRST_NAME, MIDDLE_NAME, BIRTH_DATE
,PRIM.SCHOOL_NAME AS PRIMARILY_ENROLLED
--,MAX(SOR.SCHOOL_YEAR) AS LAST_YEAR_ENROLLED
,MAX(CAST(SOR.SCHOOL_YEAR AS VARCHAR) +' ' + SOR.SCHOOL_NAME) AS LAST_SCHOOL_AND_YEAR_ENROLLED

 FROM (
SELECT * FROM (
SELECT 
	SIS_NUMBER, STATE_STUDENT_NUMBER,	
	ROW_NUMBER() OVER (PARTITION BY STATE_STUDENT_NUMBER ORDER BY SIS_NUMBER DESC) AS RN

 FROM 
rev.EPC_STU 
WHERE
STATE_STUDENT_NUMBER IS NOT NULL
) AS T1
WHERE
RN > 1
) AS T2
INNER JOIN 
rev.EPC_STU AS STU2
ON
T2.STATE_STUDENT_NUMBER = STU2.STATE_STUDENT_NUMBER
INNER JOIN 
rev.REV_PERSON AS PERS
ON
STU2.STUDENT_GU = PERS.PERSON_GU

LEFT JOIN 
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS PRIM
ON
PRIM.STUDENT_GU = STU2.STUDENT_GU

LEFT JOIN 
APS.StudentSchoolOfRecord AS SOR
ON
SOR.STUDENT_GU = STU2.STUDENT_GU

GROUP BY 
STU2.SIS_NUMBER, STU2.STATE_STUDENT_NUMBER, LAST_NAME, FIRST_NAME, MIDDLE_NAME, BIRTH_DATE
,PRIM.SCHOOL_NAME 





