

SELECT 
DISTRICT
,ESL1
,ESL2
,LEFT(CAST(ESL2 AS DECIMAL)/CAST(ESL1 AS DECIMAL) * 100,5) AS ESLP1
,ESL3
,ESL4
,LEFT(CAST(ESL4 AS DECIMAL)/CAST(ESL3 AS DECIMAL) * 100,5) AS ESLP2
,ESL5
,ESL6
,LEFT(CAST(ESL6 AS DECIMAL)/CAST(ESL5 AS DECIMAL) * 100,5) AS ESLP3

 FROM 
(
SELECT 
	DISTRICT
	,SUM(ESL1) AS ESL1
	,SUM(ESL2) AS ESL2

	,SUM(ESL3) AS ESL3
	,SUM(ESL4) AS ESL4

	,SUM(ESL5) AS ESL5
	,SUM(ESL6) AS ESL6

 FROM 
APS.LCEALS2ACLUSTER

GROUP BY 
	DISTRICT
) AS GETPERCENT


