


ALTER VIEW [APS].[ConcurrentEnrollmentsWithHomeSchool] AS


SELECT 
	ENROLLMENTS.SIS_NUMBER, LAST_NAME, FIRST_NAME, ENROLLMENTS.GRADE, ENROLLMENTS.SCHOOL_CODE, ENROLLMENTS.SCHOOL_NAME
	,CAST(ENROLLMENTS.ENTER_DATE AS DATE) AS ENTER_DATE, ENROLLMENTS.ENTER_CODE, ENROLLMENTS.ENTER_DESCRIPTION,
	CAST(ENROLLMENTS.LEAVE_DATE AS DATE) AS LEAVE_DATE, ENROLLMENTS.LEAVE_CODE, ENROLLMENTS.LEAVE_DESCRIPTION,
ENROLL.SCHOOL_CODE AS HOME_SCHOOL_CODE, ENROLL.SCHOOL_NAME AS HOME_SCHOOL_NAME
,ENROLLMENTS.ORGANIZATION_GU
FROM
	(
	SELECT
		SIS_NUMBER, GRADE, SCHOOL_CODE, SCHOOL_NAME, ENTER_DATE, ENTER_CODE, ENTER_DESCRIPTION,
	LEAVE_DATE, LEAVE_CODE, LEAVE_DESCRIPTION, STUDENT_GU, ORGANIZATION_GU
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = (SELECT * FROM REV.SIF_22_Common_CurrentYear)
			AND EXTENSION = 'R'
			AND EXCLUDE_ADA_ADM IS NOT NULL
		
	) AS [ENROLLMENTS]
	
INNER JOIN
APS.BasicStudent AS [STUDENT]
ON
[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]


LEFT JOIN 
(
	SELECT * FROM 
	(
	SELECT
		SCHOOL_CODE, SCHOOL_NAME,STUDENT_GU
		,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU ORDER BY ENTER_DATE DESC, EXCLUDE_ADA_ADM ASC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = (SELECT * FROM REV.SIF_22_Common_CurrentYear)
			AND EXTENSION = 'R'
			AND EXCLUDE_ADA_ADM IS NULL
	) AS T1
	WHERE
	RN = 1	
	) AS [ENROLL]

ON
ENROLLMENTS.STUDENT_GU = ENROLL.STUDENT_GU
GO


