

/*
	Created By:  Debbie Ann Chavez
	Date:  6/3/2015

*/


IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[APS].[LCEALS2ACLUSTER]'))
	EXEC ('CREATE VIEW APS.LCEALS2ACLUSTER AS SELECT 0 AS DUMMY')
GO

ALTER VIEW APS.LCEALS2ACLUSTER AS


SELECT 
	CLUSTER
	,ESL1
	,ESL2
	,LEFT(CAST(ESL2 AS DECIMAL)/CAST(ESL1 AS DECIMAL) * 100,5) AS ESLP1

	,ESL3
	,ESL4
	,LEFT(CAST(ESL4 AS DECIMAL)/CAST(ESL3 AS DECIMAL) * 100,5) AS ESLP2

	,ESL5
	,ESL6
	,LEFT(CAST(ESL6 AS DECIMAL)/CAST(ESL5 AS DECIMAL) * 100,5) AS ESLP3


 FROM 

(
SELECT 
	CLUSTER
	,SUM([Req ESL Current]) AS ESL1
	,SUM([Received ESL Current Quarter]) AS [ESL2]

	,SUM([Req ESL Prior]) AS [ESL3]
	,SUM([Received ESL Prior Quarter]) AS [ESL4]

	,SUM([Year Ago 5/22/2014 Req ESL]) AS [ESL5]
	,SUM([Year Ago 5/22/2014 Received ESL]) AS [ESL6]
	

 FROM 
APS.LCEALS2A

GROUP BY 
	CLUSTER

) AS T1

