/**
 * $LastChangedBy: 104090	 
 * $LastChangedDate: 2015-01-30
 *
 * This view pulls Period Attendance for current regular school year - takes about 34 seconds to run for 2,225,530 records (so far).
 *
 */
 
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[APS].[AttendanceDaily]'))
	EXEC ('CREATE VIEW APS.AttendanceDaily AS SELECT 0 AS DUMMY')
GO

ALTER VIEW APS.AttendanceDaily AS

SELECT SIS_NUMBER, ORG.ORGANIZATION_NAME, ESAD.ABS_DATE,  ECAR.ABBREVIATION  AS [ABSENCE CODE],
S.STUDENT_GU, SSY.STUDENT_SCHOOL_YEAR_GU, ESAD.DAILY_ATTEND_GU

FROM rev.EPC_STU_ATT_DAILY        AS ESAD
INNER  JOIN rev.EPC_STU_ENROLL           AS ESE    ON ESE.ENROLLMENT_GU                = ESAD.ENROLLMENT_GU 
INNER  JOIN rev.EPC_STU_SCH_YR           AS SSY    ON SSY.STUDENT_SCHOOL_YEAR_GU       = ESE.STUDENT_SCHOOL_YEAR_GU 
INNER  JOIN rev.EPC_STU								AS S      ON S.STUDENT_GU = SSY.STUDENT_GU 
INNER  JOIN rev.REV_ORGANIZATION_YEAR AS ORGYR ON SSY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER  JOIN rev.REV_ORGANIZATION AS ORG ON ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

INNER  JOIN rev.EPC_CODE_ABS_REAS_SCH_YR AS ECARSY ON ECARSY.CODE_ABS_REAS_SCH_YEAR_GU    = ESAD.CODE_ABS_REAS1_GU 											
AND ECARSY.ORGANIZATION_YEAR_GU     = ORGYR.ORGANIZATION_YEAR_GU 

INNER  JOIN rev.EPC_CODE_ABS_REAS        AS ECAR   ON ECARSY.CODE_ABS_REAS_GU             = ECAR.CODE_ABS_REAS_GU 

INNER  JOIN rev.REV_YEAR                 AS Y      ON Y.YEAR_GU                           = ORGYR.YEAR_GU 
--This view only runs for the current school year and Regular Extension
AND Y.SCHOOL_YEAR  = (SELECT SCHOOL_YEAR FROM rev.SIF_22_Common_CurrentYear)
AND Y.EXTENSION  = 'R'

WHERE
--DAILY CONTAINS PERIOD TOO, SO EXCLUDE MID AND HIGH
ORGANIZATION_NAME LIKE '%Elementary%'
--THIS EXCLUDES TARDIES
AND ISNUMERIC(ECAR.ABBREVIATION) != 1 AND ECAR.ABBREVIATION != 'T'

GO