
/*****************************************************************************************

Created by Debbie Ann Chavez
Date 1/11/2017

If there are any records they need to be fixed ASAP, this effects attendance
If there Meet Day Codes that are not on the Calendar rotation, attendance is missing


*****************************************************************************************/


IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[APS].[MeetCodeRotationMismatch]'))
	EXEC ('CREATE VIEW APS.MeetCodeRotationMismatch AS SELECT 0 AS DUMMY')
GO

ALTER VIEW [APS].[MeetCodeRotationMismatch] AS


SELECT MEETS.*, ROTATION FROM 

(
SELECT DISTINCT SCHOOL_YEAR, EXTENSION, ORGANIZATION_NAME, MEET_DAY_CODE
FROM 
rev.EPC_SCH_YR_MET_DY AS CAL
INNER JOIN 
rev.REV_ORGANIZATION_YEAR AS ORG
ON
CAL.ORGANIZATION_YEAR_GU = ORG.ORGANIZATION_YEAR_GU
INNER JOIN 
rev.REV_YEAR AS YRS
ON
ORG.YEAR_GU = YRS.YEAR_GU 

INNER JOIN 
REV.REV_ORGANIZATION AS ORG2
ON
ORG2.ORGANIZATION_GU = ORG.ORGANIZATION_GU

INNER JOIN 
rev.EPC_SCH AS SCH
ON
ORG2.ORGANIZATION_GU = SCH.ORGANIZATION_GU

WHERE
YRS.SCHOOL_YEAR >=2014
AND SCH.SCHOOL_CODE >'400'

--ORDER BY SCHOOL_YEAR, EXTENSION, ORGANIZATION_NAME
) AS MEETS

LEFT JOIN 
(
---------------------------------------------------------------------------
SELECT DISTINCT SCHOOL_YEAR, EXTENSION, ORGANIZATION_NAME, ROTATION 

FROM 
[rev].[EPC_SCH_ATT_CAL] AS CAL
INNER JOIN 
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
CAL.SCHOOL_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN 
rev.REV_YEAR AS YRS
ON
ORGYR.YEAR_GU = YRS.YEAR_GU 

INNER JOIN 
REV.REV_ORGANIZATION AS ORG2
ON
ORG2.ORGANIZATION_GU = ORGYR.ORGANIZATION_GU

INNER JOIN 
rev.EPC_SCH AS SCH
ON
ORG2.ORGANIZATION_GU = SCH.ORGANIZATION_GU

WHERE
YRS.SCHOOL_YEAR >=2014
AND SCH.SCHOOL_CODE >'400'

--ORDER BY SCHOOL_YEAR, EXTENSION, ORGANIZATION_NAME

) AS CAL

ON
MEETS.SCHOOL_YEAR = CAL.SCHOOL_YEAR
AND MEETS.EXTENSION = CAL.EXTENSION
AND MEETS.ORGANIZATION_NAME = CAL.ORGANIZATION_NAME
AND MEETS.MEET_DAY_CODE = CAL.ROTATION

WHERE
CAL.ROTATION IS NULL