

/***NOTE KIDS THAT HAVE EXITED "TODAY" ARE IN THE FUNCTION AND DO EXIST IN THE TABLE AND ARE NOT NULL */

SELECT BEP.* FROM 
APS.NewBEPStudentsModelsAndHoursAsOf(GETDATE()) AS BEP

--WHERE SIS_NUMBER = 970050716
LEFT JOIN (
SELECT DISTINCT BEP2.STUDENT_GU, SIS_NUMBER  FROM 
REV.EPC_STU_PGM_ELL_BEP AS BEP2 INNER JOIN REV.EPC_STU AS STU ON BEP2.STUDENT_GU = STU.STUDENT_GU
WHERE
EXIT_DATE IS NULL
AND ENTER_DATE >= '20170701'
) AS TABLE1
ON
BEP.SIS_NUMBER = TABLE1.SIS_NUMBER

WHERE
TABLE1.STUDENT_GU IS NULL

