

/**************************************************************

--THIS NEEDS TO BE STEP2

-- CLOSE OUT RECORDS WHERE THE MODEL AND HOURS DO NOT MATCH

**************************************************************/

BEGIN TRAN

UPDATE REV.EPC_STU_PGM_ELL_BEP 
	SET EXIT_DATE = CASE WHEN COURSE_EXIT_DATE IS NULL THEN GETDATE() ELSE COURSE_EXIT_DATE END
, [CHANGE_ID_STAMP] = '27CDCD0E-BF93-4071-94B2-5DB792BB735F', [CHANGE_DATE_TIME_STAMP] = GETDATE()

FROM 
(
SELECT 
	
	SIS_NUMBER
	,CLOSEMEOUT.STUDENT_GU
	,TABLE_PROG_CODE
	,TABLE_HOURS
	,TABLE_ENTER
	,TABLE_EXIT
	,ESLBEPCLASSES.COURSE_EXIT_DATE
	,STU_PGM_ELL_BEP_GU
 FROM 
 (
SELECT 	
	T1.SIS_NUMBER,
	T1.PROGRAM_CODE
	,T1.PROGRAM_INTENSITY
	,T1.ENTER_DATE
	,T1.EXIT_DATE

	,BEP2.STUDENT_GU
	,BEP2.STU_PGM_ELL_BEP_GU
	,BEP2.PROGRAM_CODE AS TABLE_PROG_CODE
	,BEP2.PROGRAM_INTENSITY AS TABLE_HOURS
	,BEP2.ENTER_DATE AS TABLE_ENTER
	,BEP2.EXIT_DATE AS TABLE_EXIT
FROM(

SELECT DISTINCT 
------- THIS IS TO DEBUG ---------------------------------
	STU.SIS_NUMBER
	,STU.STUDENT_GU
	,LU.VALUE_CODE AS PROGRAM_CODE
	,BEP.[HOUR] AS PROGRAM_INTENSITY
	,MAX(SCH.COURSE_ENTER_DATE) AS ENTER_DATE
	,SCH.COURSE_LEAVE_DATE AS EXIT_DATE

---------------------------------------------------------

 FROM 
	APS.NewBEPStudentsModelsAndHoursAsOf(GETDATE()) AS BEP
	INNER HASH JOIN 
	REV.EPC_STU AS STU
	ON
	BEP.SIS_NUMBER = STU.SIS_NUMBER
	INNER HASH JOIN 
	APS.NewBEPModelsAndHoursDetailsAsOf(GETDATE()) AS MODELS
	ON
	BEP.SIS_NUMBER = MODELS.SIS_NUMBER
	INNER HASH JOIN 
	APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
	ON
	SCH.SIS_NUMBER = MODELS.SIS_NUMBER
	AND SCH.ORGANIZATION_NAME = MODELS.SCHOOL_NAME
	AND SCH.COURSE_ID = MODELS.COURSE_ID
	AND SCH.SECTION_ID = MODELS.SECTION_ID
	INNER JOIN 
	APS.LookupTable ('K12.ProgramInfo', 'BEP_PROGRAM_CODE') AS LU
	ON
	LU.VALUE_DESCRIPTION = BEP.MODEL

--WHERE STU.SIS_NUMBER = 103470191

GROUP BY STU.STUDENT_GU, STU.SIS_NUMBER, BEP.[HOUR], BEP.MODEL, VALUE_CODE, COURSE_LEAVE_DATE

) AS T1

LEFT HASH JOIN 
(SELECT * FROM REV.EPC_STU_PGM_ELL_BEP WHERE ENTER_DATE > '20170701') AS BEP2
ON
BEP2.STUDENT_GU = T1.STUDENT_GU

WHERE 
	BEP2.STUDENT_GU = T1.STUDENT_GU
	AND (
	-- PULL RECORDS WHERE PROGRAM CODE OR MODEL DOES NOT MATCH 
	COALESCE(BEP2.PROGRAM_CODE, '') != T1.PROGRAM_CODE
	OR COALESCE(BEP2.PROGRAM_INTENSITY, '') != T1.PROGRAM_INTENSITY)

) AS CLOSEMEOUT

	--PULL COURSE EXIT DATE IF THERE IS ONE
LEFT JOIN 
(
SELECT 
	SCH.STUDENT_GU, MAX(COURSE_LEAVE_DATE) AS COURSE_EXIT_DATE
 FROM 
APS.ScheduleForYear('A3F9F1FB-4706-49AA-B3A3-21F153966191') AS SCH
INNER JOIN 
REV.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
WHERE COURSE_LEVEL IN ('BEP', 'ESL') AND COURSE_LEAVE_DATE IS NOT NULL
GROUP BY STUDENT_GU 
) AS ESLBEPCLASSES

ON
CLOSEMEOUT.STUDENT_GU = ESLBEPCLASSES.STUDENT_GU

) AS UPDATEALLOFTHIS

WHERE

REV.EPC_STU_PGM_ELL_BEP.STU_PGM_ELL_BEP_GU = UPDATEALLOFTHIS.STU_PGM_ELL_BEP_GU

COMMIT