
/*******************************************************************************************
-- THIS IS STEP 4 -- LASTLY 
-- CREATE NEW RECORDS WHERE THEY DO NOT HAVE A RECORD OR AN OPEN RECORD IN THE BEP TABLE

********************************************************************************************/


BEGIN TRAN

INSERT INTO REV.EPC_STU_PGM_ELL_BEP

SELECT DISTINCT 

	T1.STU_PGM_ELL_BEP
	,T1.STUDENT_GU
	,T1.ENTER_DATE
	,T1.PROGRAM_CODE
	,T1.PROGRAM_INTENSITY
	,T1.EXIT_DATE
	,T1.[ADD_ID_STAMP]
	,T1.ADD_DATE_TIME_STAMP
	,T1.CHANGE_ID_STAMP
	,T1.CHANGE_DATE_TIME_STAMP

FROM (
	SELECT DISTINCT 
	NEWID() AS STU_PGM_ELL_BEP
	,STU.STUDENT_GU AS STUDENT_GU
	,STU.SIS_NUMBER
	,MAX(SCH.COURSE_ENTER_DATE) AS ENTER_DATE
	,LU.VALUE_CODE AS PROGRAM_CODE
	,BEP.[HOUR] AS PROGRAM_INTENSITY
	--, BEP.MODEL, 
	,SCH.COURSE_LEAVE_DATE AS EXIT_DATE
	,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS [ADD_ID_STAMP]
	,GETDATE() AS [ADD_DATE_TIME_STAMP]
	, NULL AS [CHANGE_ID_STAMP]
	, NULL AS [CHANGE_DATE_TIME_STAMP]

 FROM 
	APS.NewBEPStudentsModelsAndHoursAsOf(GETDATE()) AS BEP
	INNER HASH JOIN 
	REV.EPC_STU AS STU
	ON
	BEP.SIS_NUMBER = STU.SIS_NUMBER
	INNER HASH JOIN 
	APS.NewBEPModelsAndHoursDetailsAsOf(GETDATE()) AS MODELS
	ON
	BEP.SIS_NUMBER = MODELS.SIS_NUMBER
	INNER HASH JOIN 
	APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
	ON
	SCH.SIS_NUMBER = MODELS.SIS_NUMBER
	AND SCH.ORGANIZATION_NAME = MODELS.SCHOOL_NAME
	AND SCH.COURSE_ID = MODELS.COURSE_ID
	AND SCH.SECTION_ID = MODELS.SECTION_ID
	INNER JOIN 
	APS.LookupTable ('K12.ProgramInfo', 'BEP_PROGRAM_CODE') AS LU
	ON
	LU.VALUE_DESCRIPTION = BEP.MODEL

--WHERE STU.SIS_NUMBER = 104457650

GROUP BY STU.STUDENT_GU, STU.SIS_NUMBER, BEP.[HOUR], BEP.MODEL, VALUE_CODE, COURSE_LEAVE_DATE
	) AS T1
	
LEFT JOIN 
(SELECT * FROM REV.EPC_STU_PGM_ELL_BEP WHERE ENTER_DATE > '20170701' AND EXIT_DATE IS NULL) AS BEPTABLE
ON
T1.STUDENT_GU = BEPTABLE.STUDENT_GU

WHERE
BEPTABLE.STUDENT_GU IS NULL
AND T1.EXIT_DATE IS NULL

COMMIT
