/***********************************************************************************************

TWO HOUR HERITAGE FOR EL STUDENTS


*************************************************************************************************/

DECLARE @TEMP TABLE

(
	SCHOOL_NAME VARCHAR(50)
	,STUDENT_GU VARCHAR(300)
	,SIS_NUMBER VARCHAR(9)
	,COURSE_ID VARCHAR(20)
	,COURSE_TITLE VARCHAR(50)
	,COURSE_LEVEL VARCHAR(10)
	,STATE_COURSE_CODE VARCHAR(20)
	,GRADE VARCHAR(2)
	,[01] VARCHAR (3)
	   ,[03] VARCHAR (3)
      ,[04] VARCHAR (3)
      ,[05] VARCHAR (3)
      ,[10] VARCHAR (3)
      ,[20] VARCHAR (3)
      ,[27] VARCHAR (3)
      ,[32] VARCHAR (3)
      ,[45] VARCHAR (3)
      ,[47] VARCHAR (3)
      ,[51] VARCHAR (3)
      ,[60] VARCHAR (3)
      ,[67] VARCHAR (3)
      ,[ELEM] VARCHAR (3)
      ,[MID] VARCHAR (3)
      ,[HIGH] VARCHAR (3)
	  ,[TEACHER NAME] VARCHAR (100)
	  ,BADGE_NUM VARCHAR (10)
	  ,EL VARCHAR (10)
	  ,DEPARTMENT VARCHAR (10)
	  ,LAST_NAME VARCHAR (50)
	  ,FIRST_NAME VARCHAR (50)
	  ,[HOUR] VARCHAR (2)
	  ,MODEL VARCHAR (20)
	  ,QUALIFIED VARCHAR (10)

)
--DECLARE '20170928' DATE = '20170928'


INSERT INTO 
	@TEMP

SELECT * FROM 
(
SELECT 
	T6.SCHOOL_NAME, T6.STUDENT_GU, T6.SIS_NUMBER, T6.COURSE_ID, T6.COURSE_TITLE, T6.COURSE_LEVEL, T6.STATE_COURSE_CODE, T6.GRADE, 
	[01],[03],[04],[05],[10],[20],[27],[32],[45],[47],[51],[60],[67],[ELEM],[MID],[HIGH],[TEACHER NAME],BADGE_NUM, EL, DEPARTMENT AS DEPARTMENT


	,PERS.LAST_NAME, PERS.FIRST_NAME
	, 2 AS [HOUR]
	,'Heritage' AS MODEL

	, CASE 
			WHEN GRADE IN ('K', '01', '02', '03', '04', '05') AND [67] = '67' AND ELEM = 'Y' THEN 'Y'
			WHEN GRADE IN ('K', '01', '02', '03', '04', '05') AND LEFT(T6.STATE_COURSE_CODE,4) = '1062' AND ELEM = 'Y' AND [27] = '27' THEN 'Y'

			--SECONDARY
			-- (1202-1203, 1254-1255, 1299)
			
			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND [60] = '60' AND MID = 'Y' AND LEFT(STATE_COURSE_CODE,4) BETWEEN '1202' AND '1203'  THEN 'Y' 
			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND [60] = '60' AND MID = 'Y' AND LEFT(STATE_COURSE_CODE,4) BETWEEN '1254' AND '1255'  THEN 'Y' 
			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND [60] = '60' AND MID = 'Y' AND LEFT(STATE_COURSE_CODE,4) = '1299'  THEN 'Y' 
			
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND [60] = '60' AND HIGH = 'Y' AND LEFT(STATE_COURSE_CODE,4) BETWEEN '1202' AND '1203'  THEN 'Y' 
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND [60] = '60' AND HIGH = 'Y' AND LEFT(STATE_COURSE_CODE,4) BETWEEN '1254' AND '1255'  THEN 'Y' 
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND [60] = '60' AND HIGH = 'Y' AND LEFT(STATE_COURSE_CODE,4) = '1299'  THEN 'Y' 


			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND [60] = '60' AND MID = 'Y' AND LEFT(T6.STATE_COURSE_CODE,4) BETWEEN '1271' AND '1274'  THEN 'Y' 
			WHEN GRADE IN ('06', '07', '08') AND [27] = '27' AND [20] = '20' AND MID = 'Y' AND LEFT(T6.STATE_COURSE_CODE,4) = '1063'  THEN 'Y' 
			
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND [60] = '60' AND HIGH = 'Y' AND LEFT(T6.STATE_COURSE_CODE,4) BETWEEN '1271' AND '1274'  THEN 'Y' 
			WHEN GRADE IN ('09', '10', '11', '12') AND [27] = '27' AND [20] = '20' AND HIGH = 'Y' AND LEFT(T6.STATE_COURSE_CODE,4) = '1063'   THEN 'Y' 

			--1150
			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND [01] = '01' AND MID = 'Y' AND LEFT(STATE_COURSE_CODE,4) = '1150'  THEN 'Y'			
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND [01] = '01'  AND HIGH = 'Y' AND LEFT(STATE_COURSE_CODE,4) = '1150'   THEN 'Y' 

			--0304	
			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND ([03] = '03' OR [45] = '45' OR [47] = '47') AND MID = 'Y' AND LEFT(STATE_COURSE_CODE,4) = '0304'  THEN 'Y'			
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND ([03] = '03' OR [45] = '45' OR [47] = '47') AND HIGH = 'Y' AND LEFT(STATE_COURSE_CODE,4) = '0304'   THEN 'Y' 

			--Health
			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND [04] = '04' AND [05] = '05'AND MID = 'Y' AND DEPARTMENT = 'Hea'  THEN 'Y' 
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND [04] = '04' AND [05] = '05' AND HIGH = 'Y' AND DEPARTMENT = 'Hea'  THEN 'Y' 

			--Math
			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND [51] = '51' AND MID = 'Y' AND DEPARTMENT = 'Math'  THEN 'Y' 
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND [51] = '51' AND HIGH = 'Y' AND DEPARTMENT = 'Math'  THEN 'Y' 

			--Social Studies
			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND [10] = '10' AND MID = 'Y' AND DEPARTMENT = 'Soc'  THEN 'Y' 
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND [10] = '10' AND HIGH = 'Y' AND DEPARTMENT = 'Soc'  THEN 'Y' 

			--Science
			WHEN GRADE IN ('06', '07', '08') AND [67] = '67' AND [32] = '32' AND MID = 'Y' AND DEPARTMENT = 'Sci'  THEN 'Y' 
			WHEN GRADE IN ('09', '10', '11', '12') AND [67] = '67' AND [32] = '32' AND HIGH = 'Y' AND DEPARTMENT = 'Sci'  THEN 'Y' 



			ELSE 'N' END AS QUALIFIED


FROM
(
--THIS PULLS THRU T5
SELECT 
	DISTINCT STUDENT_GU
FROM 
(
-------------------------------------------------------------------------------------------------
--FIRST PULL ELL STUDENTS THAT HAVE A BEP TAGGED COURSE BETWEEN 1274-1274 STATE COURSE CODES
-------------------------------------------------------------------------------------------------

SELECT 
	STUDENT_GU, SIS_NUMBER, COURSE_ID, COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE

 FROM(
SELECT 
	PRIM.STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, CRS.STATE_COURSE_CODE
 FROM 
APS.PrimaryEnrollmentDetailsAsOf('20170928') AS PRIM
INNER JOIN 
APS.ELLCalculatedAsOf('20170928') AS ELL
ON
PRIM.STUDENT_GU = ELL.STUDENT_GU

INNER JOIN 
APS.ScheduleDetailsAsOf('20170928') AS SCH
ON
PRIM.STUDENT_GU = SCH.STUDENT_GU
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU
WHERE
(LST.COURSE_LEVEL = 'BEP'
AND LEFT(CRS.STATE_COURSE_CODE,4) BETWEEN '1271' AND '1274')
) AS T1

---------------------------------------------------------------------------------------------------------------
-- REMOVE STUDENTS ABOVE IF THEY HAVE ANY OTHER COURSES TAGGED BEP THAT IS NOT IN THE COURSE CODE RANGE
---------------------------------------------------------------------------------------------------------------

LEFT JOIN 
(SELECT DISTINCT RESTOFSCH.STUDENT_GU AS RESTSCHGU
FROM
APS.ScheduleDetailsAsOf('20170928') AS RESTOFSCH
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
RESTOFSCH.COURSE_GU = LST.COURSE_GU
AND LST.COURSE_LEVEL IN ('BEP') 
INNER JOIN 
REV.EPC_CRS AS CRS2
ON
RESTOFSCH.COURSE_GU = CRS2.COURSE_GU
AND LEFT(CRS2.STATE_COURSE_CODE,4) NOT BETWEEN '1271' AND '1274'
) AS T2

ON
T1.STUDENT_GU = T2.RESTSCHGU

WHERE
T2.RESTSCHGU IS NULL

)AS T3

--640 ROWS

INNER JOIN 
-------------------------------------------------------------------------------------------------
--PULL ELL STUDENTS ABOVE THAT ALSO HAVE AN ESL TAGGED COURSE
-------------------------------------------------------------------------------------------------
(
SELECT DISTINCT PRIM.STUDENT_GU AS HASESLGU
	--PRIM.STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE
 FROM 
APS.PrimaryEnrollmentDetailsAsOf('20170928') AS PRIM
INNER JOIN 
APS.ELLCalculatedAsOf('20170928') AS ELL
ON
PRIM.STUDENT_GU = ELL.STUDENT_GU

INNER JOIN 
APS.ScheduleDetailsAsOf('20170928') AS SCH
ON
PRIM.STUDENT_GU = SCH.STUDENT_GU
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU
WHERE
COURSE_LEVEL = 'ESL'

) AS T4

ON T3.STUDENT_GU = T4.HASESLGU

) AS T5

--488 ROWS

-------------------------------------------------------------------------------------------------
--FOR STUDENTS ABOVE PULL ALL BEP AND ESL CLASSES NOW
-------------------------------------------------------------------------------------------------

INNER JOIN 
(
SELECT 
	prim.SCHOOL_CODE, SCHOOL_NAME,
	PRIM.STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE
	,PRIM.GRADE
	,[01]
      ,[03]
      ,[04]
      ,[05]
      ,[10]
      ,[20]
      ,[27]
      ,[32]
      ,[45]
      ,[47]
      ,[51]
      ,[60]
      ,[67]
      ,[ELEM]
      ,[MID]
      ,[HIGH]
	  ,SCH.[TEACHER NAME]
	  ,STF.BADGE_NUM
	  ,CASE WHEN ADMIN_DATE IS NOT NULL THEN 'Y' ELSE 'N' END AS EL
	  ,SCH.DEPARTMENT
 FROM 
APS.PrimaryEnrollmentDetailsAsOf('20170928') AS PRIM
INNER JOIN 
APS.ELLCalculatedAsOf('20170928') AS ELL
ON
PRIM.STUDENT_GU = ELL.STUDENT_GU

INNER JOIN 
APS.ScheduleDetailsAsOf('20170928') AS SCH
ON
PRIM.STUDENT_GU = SCH.STUDENT_GU
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU

LEFT JOIN 
APS.LCETeacherEndorsements AS CRED
ON
SCH.STAFF_GU = CRED.STAFF_GU

LEFT JOIN 
rev.EPC_STAFF AS STF
ON
CRED.STAFF_GU = STF.STAFF_GU

WHERE
COURSE_LEVEL IN ('BEP','ESL')

) AS T6

ON
T5.STUDENT_GU = T6.STUDENT_GU

INNER JOIN 
REV.REV_PERSON AS PERS
ON
T6.STUDENT_GU = PERS.PERSON_GU

) AS FINAL


--LEFT JOIN 

--(
--	SELECT DISTINCT SIS_NUMBER FROM @TEMP  

--	WHERE
--		(COURSE_LEVEL = 'BEP'
--AND LEFT(STATE_COURSE_CODE,4) BETWEEN '1271' AND '1274')
--AND QUALIFIED = 'N' 

--) AS REMOVEKIDS

--ON
--FINAL.SIS_NUMBER ! = REMOVEKIDS.SIS_NUMBER
