
SELECT 
	MIN(startDate) AS startDate
	,MAX(endDate) AS endDate
	,org_year_gu
	,STUID
	,MIN(ORIGENTERDATE) AS ORIGENTERDATE
	,SCHOOL
	,SCHOOL_CODE
	,EXCLUDE_ADA_ADM
,SUM(CAST(MEMBER_DAYS AS INT)) AS MEMBER_DAYS

 FROM 
  STUDENT_SCHOOL_MEMBERDAYS_80D AS ENROLLMENT

  GROUP BY 
  	org_year_gu
	,STUID
	,SCHOOL
	,SCHOOL_CODE
	,EXCLUDE_ADA_ADM