



--DECLARE @AsOfDate DATETIME = '10/08/2014'
--DECLARE @AsOfDate DATETIME = '12/01/2014'
--DECLARE @AsOfDate DATETIME = '1/11/2015'
DECLARE @AsOfDate DATETIME = '5/22/2015'

SELECT
	'2014-2015' AS [SCHOOL_YEAR]
	--,'FALL' AS [SEMESTER]
	--,'SPRING' AS [SEMESTER]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	--,[ENROLLMENTS].[GRADE]
	--,[ENROLLMENTS].[ENTER_DATE]
	--,[ENROLLMENTS].[LEAVE_DATE]
	--,[ENROLLMENTS].[LEAVE_CODE]
	--,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	----,CASE WHEN [ENTER_DATE] > '08/13/2014' OR ([LEAVE_DATE] IS NOT NULL AND [LEAVE_DATE] < '01/01/2015') THEN 'Y' ELSE 'N' END AS [MOBILITY]
	--,CASE WHEN [ENTER_DATE] > '01/01/2015' OR ([LEAVE_DATE] IS NOT NULL AND [LEAVE_DATE] < '05/23/2015') THEN 'Y' ELSE 'N' END AS [MOBILITY]
	--,[STUDENT].[GENDER]
	--,[STUDENT].[RESOLVED_RACE]
	--,[STUDENT].[LUNCH_STATUS]
	--,[STUDENT].[ELL_STATUS]
	--,[STUDENT].[SPED_STATUS]
	--,[DAILY_ATT].[Full-Day Excused]
	--,[DAILY_ATT].[Full-Day Unexcused]
	--,[DAILY_ATT].[Half-Day Excused]
	--,[DAILY_ATT].[Half-Day Unexcused]
	--,[PERIOD_ATT].*
	,[DAILY_ATT].[DAILY TARDY]
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2014
		AND EXTENSION = 'R'
		AND EXCLUDE_ADA_ADM IS NULL
		AND SCHOOL_CODE IN ('207', '255', '260', '270', '276', '279', '285', '333', '379', '405', '410', '413', '415', '416', '425', '427', '445', '460', '470', '496', '520', '540', '570', '576', '496')
		AND [ENTER_DATE] <= @AsOfDate -- FALL
		--AND [ENTER_DATE] < '05/23/2015' AND (LEAVE_DATE > '01/01/2015' OR LEAVE_DATE IS NULL)  -- SPRING
		
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	--LEFT OUTER JOIN
	--(
	--SELECT	
	--	[ATT].[SIS_NUMBER]
	--	,SUM([ATT].[Full-Day Excused]) AS [Full-Day Excused]
	--	,SUM([ATT].[Full-Day Unexcused]) AS [Full-Day Unexcused]
	--	,SUM([ATT].[Half-Day Excused]) AS [Half-Day Excused]
	--	,SUM([ATT].[Half-Day Unexcused]) AS [Half-Day Unexcused]
	--FROM
	--	APS.DailyAttendanceAsOf(@AsOfDate) AS [ATT]
	--GROUP BY
	--	[ATT].[SIS_NUMBER]
	--) AS [DAILY_ATT]
	--ON
	--[STUDENT].[SIS_NUMBER] = [DAILY_ATT].[SIS_NUMBER]
	
	--LEFT OUTER JOIN
	--APS.PeriodUnexcusedAsOf(@AsOfDate) AS [PERIOD_ATT]
	--ON
	--[STUDENT].[SIS_NUMBER] = [PERIOD_ATT].[SIS_NUMBER]
	
	LEFT OUTER JOIN
	(
	SELECT
		[STUDENT_GU]
		-- GROUP DAILY TOTALS BY ABSENCE TYPE
		--,SUM(CASE WHEN [ABSENCE CODE] = 'UX' THEN [ABSENCE PERIODS] ELSE 0 END) AS 'DAILY UNEXCUSED'
		--,SUM(CASE WHEN [ABSENCE CODE] = 'EX' THEN [ABSENCE PERIODS] ELSE 0 END) AS 'DAILY EXCUSED'
		,SUM(CASE WHEN [ABSENCE CODE] = 'T' THEN [ABSENCE PERIODS] ELSE 0 END) AS 'DAILY TARDY'
		--,SUM(CASE WHEN [ABSENCE CODE] = 'UF' THEN [ABSENCE PERIODS] ELSE 0 END) AS 'UF'
	FROM
		(
		SELECT
			[STUDENT_GU]
			-- GET TOTAL DAYS
			,COUNT(ABS_DATE) AS [ABSENCE PERIODS]
			,[ABSENCE CODE]
		FROM	
			(
			SELECT 
			SIS_NUMBER
			, ORG.ORGANIZATION_NAME
			, ESAD.ABS_DATE
			, CASE
					WHEN ISNUMERIC(ECAR.ABBREVIATION) = 1 OR ECAR.ABBREVIATION = 'T' THEN 'T'  
					WHEN ECAR.ABBREVIATION = 'ABS' THEN 'UX'
					--WHEN ECAR.ABBREVIATION = 'UF' THEN 'UF'
					WHEN ECAR.ABBREVIATION = 'UP' THEN 'UX'
					ELSE 'EX'END 
				AS [ABSENCE CODE]
			--, ECAR.ABBREVIATION  AS [ABSENCE CODE]
			, S.STUDENT_GU
			, SSY.STUDENT_SCHOOL_YEAR_GU
			, ESAD.DAILY_ATTEND_GU

			FROM rev.EPC_STU_ATT_DAILY        AS ESAD
			INNER  JOIN rev.EPC_STU_ENROLL           AS ESE    ON ESE.ENROLLMENT_GU                = ESAD.ENROLLMENT_GU 
			INNER  JOIN rev.EPC_STU_SCH_YR           AS SSY    ON SSY.STUDENT_SCHOOL_YEAR_GU       = ESE.STUDENT_SCHOOL_YEAR_GU 
			INNER  JOIN rev.EPC_STU								AS S      ON S.STUDENT_GU = SSY.STUDENT_GU 
			INNER  JOIN rev.REV_ORGANIZATION_YEAR AS ORGYR ON SSY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
			INNER  JOIN rev.REV_ORGANIZATION AS ORG ON ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

			INNER  JOIN rev.EPC_CODE_ABS_REAS_SCH_YR AS ECARSY ON ECARSY.CODE_ABS_REAS_SCH_YEAR_GU    = ESAD.CODE_ABS_REAS1_GU 											
			AND ECARSY.ORGANIZATION_YEAR_GU     = ORGYR.ORGANIZATION_YEAR_GU 

			INNER  JOIN rev.EPC_CODE_ABS_REAS        AS ECAR   ON ECARSY.CODE_ABS_REAS_GU             = ECAR.CODE_ABS_REAS_GU 

			INNER  JOIN rev.REV_YEAR                 AS Y      ON Y.YEAR_GU                           = ORGYR.YEAR_GU 
			--This view only runs for the current school year and Regular Extension
			AND Y.SCHOOL_YEAR  = (2014)
			AND Y.EXTENSION  = 'R'

			WHERE
			--DAILY CONTAINS PERIOD TOO, SO EXCLUDE MID AND HIGH
			ORGANIZATION_NAME LIKE '%Elementary%'
			--AND ESAD.ABS_DATE BETWEEN '08/13/2014' AND '02/11/2015'
			AND ESAD.ABS_DATE <= @AsOfDate
			) AS [DAILY_ATT]
			
		GROUP BY
			[STUDENT_GU]
			,[ABSENCE CODE]
		) AS [DAILY_ATT]
		
	GROUP BY
		[STUDENT_GU]
	) AS [DAILY_ATT]
	ON
	[STUDENT].[STUDENT_GU] = [DAILY_ATT].[STUDENT_GU] 

	
WHERE
	[ENROLLMENTS].[RN] = 1
	AND [ENROLLMENTS].[SCHOOL_CODE] < '400'