





SELECT
	'2014-2015' AS [SCHOOL_YEAR]
	--,'FALL' AS [SEMESTER]
	,'SPRING' AS [SEMESTER]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	--,[ENROLLMENTS].[GRADE]
	--,[ENROLLMENTS].[ENTER_DATE]
	--,[ENROLLMENTS].[LEAVE_DATE]
	--,[ENROLLMENTS].[LEAVE_CODE]
	--,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	----,CASE WHEN [ENTER_DATE] > '08/13/2014' OR ([LEAVE_DATE] IS NOT NULL AND [LEAVE_DATE] < '01/01/2015') THEN 'Y' ELSE 'N' END AS [MOBILITY]
	--,CASE WHEN [ENTER_DATE] > '01/01/2015' OR ([LEAVE_DATE] IS NOT NULL AND [LEAVE_DATE] < '05/23/2015') THEN 'Y' ELSE 'N' END AS [MOBILITY]
	--,[STUDENT].[GENDER]
	--,[STUDENT].[RESOLVED_RACE]
	--,[STUDENT].[LUNCH_STATUS]
	--,[STUDENT].[ELL_STATUS]
	--,[STUDENT].[SPED_STATUS]
	
	--,[HISTORY].[TERM_CODE]
	--,[HISTORY].[COURSE_ID]
	--,[HISTORY].[SECTION_ID]
	--,[HISTORY].[CLASS_BEGIN_DATE]
	--,[HISTORY].[CLASS_END_DATE]
	--,[HISTORY].[COURSE_TITLE]
	--,[COURSE].[DEPARTMENT]
	--,[HISTORY].[MARK]
	--,[HISTORY].[CREDIT_COMPLETED]
	
	,[CUM_GPA].[HS Cum Flat]
	,[CUM_GPA].[HS Cum Weighted]
	,[CUM_GPA].[MS Cum Flat]
	--,[CUM_GPA].*
	
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2014
		AND EXTENSION = 'R'
		AND EXCLUDE_ADA_ADM IS NULL
		AND SCHOOL_CODE IN ('207', '255', '260', '270', '276', '279', '285', '333', '379', '405', '410', '413', '415', '416', '425', '427', '445', '460', '470', '496', '520', '540', '570', '576', '496')
		--AND [ENTER_DATE] < '01/01/2015' -- FALL
		AND [ENTER_DATE] < '05/23/2015' AND (LEAVE_DATE > '01/01/2015' OR LEAVE_DATE IS NULL)  -- SPRING
		
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	--INNER HASH JOIN
	--rev.EPC_STU_CRS_HIS AS [HISTORY]
	--ON
	--[ENROLLMENTS].[STUDENT_GU] = [HISTORY].[STUDENT_GU]
	--AND [ENROLLMENTS].[ORGANIZATION_GU] = [HISTORY].[SCHOOL_IN_DISTRICT_GU]
	--AND [HISTORY].[SCHOOL_YEAR] = '2014'
	--AND [HISTORY].[TERM_CODE] IN ('S2','FY','YR')
	
	--INNER JOIN
	--rev.EPC_CRS AS [COURSE]
	--ON
	--[HISTORY].[COURSE_ID] = [COURSE].[COURSE_ID]
	
	LEFT OUTER JOIN
		(
		SELECT --DISTINCT
			[GPA].*
			--,[GPA_DEF].[GPA_CODE]
			--[GPA].[STUDENT_SCHOOL_YEAR_GU]
			
			--,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] = 'HSCF' THEN [GPA].[GPA] ELSE 0 END) AS [HS Cum Flat]
			--,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] = 'HSCW' THEN [GPA].[GPA] ELSE 0 END) AS [HS Cum Weighted]
			--,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] = 'MSCF' THEN [GPA].[GPA] ELSE 0 END) AS [MS Cum Flat]
			
			,CASE WHEN [GPA_DEF].[GPA_CODE] = 'HSCF' THEN [GPA].[GPA] ELSE 0 END AS [HS Cum Flat]
			,CASE WHEN [GPA_DEF].[GPA_CODE] = 'HSCW' THEN [GPA].[GPA] ELSE 0 END AS [HS Cum Weighted]
			,CASE WHEN [GPA_DEF].[GPA_CODE] = 'MSCF' THEN [GPA].[GPA] ELSE 0 END AS [MS Cum Flat]
			
		FROM	
			rev.[EPC_STU_GPA] AS [GPA]  
				
			INNER JOIN
			rev.[EPC_SCH_YR_GPA_TYPE_RUN] [GPA_RUN]
			ON
			[GPA].[SCHOOL_YEAR_GPA_TYPE_RUN_GU] = [GPA_RUN].[SCHOOL_YEAR_GPA_TYPE_RUN_GU]
			AND [GPA_RUN].[SCHOOL_YEAR_GRD_PRD_GU] IS NULL
			
			INNER JOIN
			rev.[EPC_GPA_DEF_TYPE] [GPA_TYPE] 
			ON 
			[GPA_RUN].[GPA_DEF_TYPE_GU] = [GPA_TYPE].[GPA_DEF_TYPE_GU]
			AND (
				[GPA_TYPE].[GPA_TYPE_NAME] = 'HS Cum Flat' 
				OR
				[GPA_TYPE].[GPA_TYPE_NAME] = 'HS Cum Weighted' 
				OR
				[GPA_TYPE].[GPA_TYPE_NAME] = 'MS Cum Flat'
				)
					
			INNER JOIN 
			rev.[EPC_GPA_DEF] [GPA_DEF]  
			ON 
			[GPA_TYPE].[GPA_DEF_GU] = [GPA_DEF].[GPA_DEF_GU]
			
		--GROUP BY
		--	[GPA].[STUDENT_SCHOOL_YEAR_GU]
		) AS [CUM_GPA]
		ON
		[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [CUM_GPA].[STUDENT_SCHOOL_YEAR_GU]
	
WHERE
	[ENROLLMENTS].[RN] = 1
	--AND [COURSE].[DEPARTMENT] IN ('Math','Sci','Eng','Soc')