





SELECT
	'2014-2015' AS [SCHOOL_YEAR]
	--,'FALL' AS [SEMESTER]
	,'SPRING' AS [SEMESTER]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[ENTER_DATE]
	,[ENROLLMENTS].[LEAVE_DATE]
	,[ENROLLMENTS].[LEAVE_CODE]
	,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	--,CASE WHEN [ENTER_DATE] > '08/13/2014' OR ([LEAVE_DATE] IS NOT NULL AND [LEAVE_DATE] < '01/01/2015') THEN 'Y' ELSE 'N' END AS [MOBILITY]
	,CASE WHEN [ENTER_DATE] > '01/01/2015' OR ([LEAVE_DATE] IS NOT NULL AND [LEAVE_DATE] < '05/23/2015') THEN 'Y' ELSE 'N' END AS [MOBILITY]
	,[STUDENT].[GENDER]
	,[STUDENT].[RESOLVED_RACE]
	,[STUDENT].[LUNCH_STATUS]
	,[STUDENT].[ELL_STATUS]
	,[STUDENT].[SPED_STATUS]
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2014
		AND EXTENSION = 'R'
		AND EXCLUDE_ADA_ADM IS NULL
		AND SCHOOL_CODE IN ('207', '255', '260', '270', '276', '279', '285', '333', '379', '405', '410', '413', '415', '416', '425', '427', '445', '460', '470', '496', '520', '540', '570', '576', '496')
		--AND [ENTER_DATE] < '01/01/2015' -- FALL
		AND [ENTER_DATE] < '05/23/2015' AND (LEAVE_DATE > '01/01/2015' OR LEAVE_DATE IS NULL)  -- SPRING
		
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER HASH JOIN
	rev.EPC_STU_CRS_HIS AS [HISTORY]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [HISTORY].[STUDENT_GU]
	AND [ENROLLMENTS].[ORGANIZATION_GU] = [HISTORY].[SCHOOL_IN_DISTRICT_GU]
	AND [HISTORY].[SCHOOL_YEAR] = '2014'
	AND [HISTORY].[TERM_CODE] = 'S1'
	
WHERE
	[ENROLLMENTS].[RN] = 1