





	SELECT
		'2014-2015' AS [SCHOOL_YEAR]
		,'SPRING' AS [SEMESTER]
		,[STUDENT].[SIS_NUMBER]
		,[STUDENT].[STATE_STUDENT_NUMBER]
		--,[STUDENT].[FIRST_NAME]
		--,[STUDENT].[LAST_NAME]
		--,[STUDENT].[MIDDLE_NAME]
		,[ENROLLMENT].[SCHOOL_CODE]
		,[ENROLLMENT].[SCHOOL_NAME]		
		,[ENROLLMENT].[GRADE]
		
		,[ENROLLMENT].[ENTER_DATE]
		,[ENROLLMENT].[LEAVE_DATE]
		,[ENROLLMENT].[LEAVE_CODE]
		,[ENROLLMENT].[LEAVE_DESCRIPTION]
		,[StudentSchoolYear].[YEAR_END_STATUS]
		,'' AS [MOBILITY]
		,[STUDENT].[GENDER]
		,[STUDENT].[RESOLVED_RACE]
		,[STUDENT].[LUNCH_STATUS]
		,[STUDENT].[ELL_STATUS]
		,[STUDENT].[SPED_STATUS]
		,[CUM_GPA].[HS Cum Flat]
		,[CUM_GPA].[HS Cum Weighted]
		,[CUM_GPA].[MS Cum Flat]		
		
	FROM		
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		
		INNER JOIN
		(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY STUDENT_GU, SCHOOL_YEAR ORDER BY ENTER_DATE DESC) AS RN
		FROM
			APS.[StudentEnrollmentDetails]
		WHERE
			SCHOOL_YEAR = '2014'
			AND EXTENSION = 'R'
		
		)  AS [ENROLLMENT]
		ON
		[STUDENT].[STUDENT_GU] = [ENROLLMENT].[STUDENT_GU]
		AND [ENROLLMENT].[RN] = 1
		
		INNER JOIN
		rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
		ON
		[ENROLLMENT].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
		
		LEFT OUTER JOIN
		(
		SELECT DISTINCT
			[GPA].[STUDENT_SCHOOL_YEAR_GU]
			
			,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] = 'HSCF' THEN [GPA].[GPA] ELSE 0 END) AS [HS Cum Flat]
			,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] = 'HSCW' THEN [GPA].[GPA] ELSE 0 END) AS [HS Cum Weighted]
			,SUM(CASE WHEN [GPA_DEF].[GPA_CODE] = 'MSCF' THEN [GPA].[GPA] ELSE 0 END) AS [MS Cum Flat]
			
		FROM	
			rev.[EPC_STU_GPA] AS [GPA]  
				
			INNER JOIN
			rev.[EPC_SCH_YR_GPA_TYPE_RUN] [GPA_RUN]
			ON
			[GPA].[SCHOOL_YEAR_GPA_TYPE_RUN_GU] = [GPA_RUN].[SCHOOL_YEAR_GPA_TYPE_RUN_GU]
			AND [GPA_RUN].[SCHOOL_YEAR_GRD_PRD_GU] IS NULL
			
			INNER JOIN
			rev.[EPC_GPA_DEF_TYPE] [GPA_TYPE] 
			ON 
			[GPA_RUN].[GPA_DEF_TYPE_GU] = [GPA_TYPE].[GPA_DEF_TYPE_GU]
			AND (
				[GPA_TYPE].[GPA_TYPE_NAME] = 'HS Cum Flat' 
				OR
				[GPA_TYPE].[GPA_TYPE_NAME] = 'HS Cum Weighted' 
				OR
				[GPA_TYPE].[GPA_TYPE_NAME] = 'MS Cum Flat'
				)
					
			INNER JOIN 
			rev.[EPC_GPA_DEF] [GPA_DEF]  
			ON 
			[GPA_TYPE].[GPA_DEF_GU] = [GPA_DEF].[GPA_DEF_GU]
			
		GROUP BY
			[GPA].[STUDENT_SCHOOL_YEAR_GU]
		) AS [CUM_GPA]
		ON
		[ENROLLMENT].[STUDENT_SCHOOL_YEAR_GU] = [CUM_GPA].[STUDENT_SCHOOL_YEAR_GU]
		
		WHERE
			[ENROLLMENT].[SCHOOL_CODE] IN ('255','260','279','270','285','333','379','410','413','416','425','460','470','520','540','570','576')
			AND [ENROLLMENT].[SCHOOL_YEAR] = '2014'
			AND [ENROLLMENT].[EXTENSION] = 'R'
			AND [ENROLLMENT].[ENTER_DATE] IS NOT NULL
			AND ([ENROLLMENT].[LEAVE_DATE] IS NULL OR [ENROLLMENT].[LEAVE_DATE] > '01/01/2015')
	
