




SELECT
	[ENROLLMENT].[SCHOOL_YEAR]
	,[ENROLLMENT].[SCHOOL_CODE]
	,[ENROLLMENT].[SCHOOL_NAME]
	,[ENROLLMENT].[GRADE]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[STUDENT].[BIRTH_DATE]
	,[STUDENT].[RESOLVED_RACE]
	,[STUDENT].[GENDER]
	,[STUDENT].[LUNCH_STATUS]
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS [ENROLLMENT]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo [STUDENT]
	ON
	[ENROLLMENT].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[ENROLLMENT].[SCHOOL_CODE] BETWEEN '200' AND '599'