



SELECT DISTINCT
	[ENROLLMENTS].[SCHOOL_YEAR]
	,[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS_2013].[SCHOOL_CODE]
	,[ENROLLMENTS_2013].[SCHOOL_NAME]
	,[STUDENT].[BIRTH_DATE]
	,[STUDENT].[RESOLVED_RACE]
	,[STUDENT].[GENDER]
	,[STUDENT].[LUNCH_STATUS]
	,[STUDENT].[ELL_STATUS]
	,[STUDENT].[SPED_STATUS]
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [ENR].[STUDENT_GU] ORDER BY [ENR].[ENTER_DATE] DESC) AS [RN]
	FROM
		APS.StudentEnrollmentDetails AS [ENR]
		
	WHERE
		[ENR].SCHOOL_YEAR = '2014'
		AND [ENR].[EXTENSION] = 'R'
		AND [ENR].[EXCLUDE_ADA_ADM] IS NULL
		AND [ENR].[SUMMER_WITHDRAWL_CODE] IS NULL
	) AS [ENROLLMENTS]
	
	LEFT OUTER JOIN
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [ENR].[STUDENT_GU] ORDER BY [ENR].[ENTER_DATE] DESC) AS [RN]
	FROM
		APS.StudentEnrollmentDetails AS [ENR]
		
	WHERE
		[ENR].SCHOOL_YEAR = '2013'
		AND [ENR].[EXTENSION] = 'R'
		AND [ENR].[EXCLUDE_ADA_ADM] IS NULL
		AND [ENR].[SUMMER_WITHDRAWL_CODE] IS NULL
	) AS [ENROLLMENTS_2013]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [ENROLLMENTS_2013].[STUDENT_GU]	
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[ENROLLMENTS].[RN] = 1