


DECLARE @SCHOOLYEAR INT = 2014

SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[BIRTH_DATE]
	,[ENROLLMENTS].[SCHOOL_YEAR]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[GRADE]
	
	,[COURSE_HISTORY].[TERM_CODE]
	,[COURSE_HISTORY].[COURSE_ID]
	,[COURSE_HISTORY].[COURSE_TITLE]
	,[COURSE].[DEPARTMENT]	
	
	----,'COURSE HISTORY/TRANSCRIPT' AS [TYPE]
	--,[COURSE].[SUBJECT_AREA_1]
	--,[COURSE].[SUBJECT_AREA_2]
	--,[COURSE].[SUBJECT_AREA_3]
	--,[COURSE].[SUBJECT_AREA_4]
	--,[COURSE].[SUBJECT_AREA_5]
	,[COURSE_HISTORY].[MARK] AS [GRADE]
	,[COURSE_HISTORY].[TEACHER_NAME]
	,[COURSE_HISTORY].[TEACHER_ID]
	
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = @SCHOOLYEAR
		AND EXTENSION = 'R'
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	INNER JOIN
	rev.[EPC_STU_CRS_HIS] AS [COURSE_HISTORY]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [COURSE_HISTORY].[STUDENT_GU]
	AND [COURSE_HISTORY].[SCHOOL_YEAR] = @SCHOOLYEAR
	
	INNER JOIN
	-- Get Course details
	rev.EPC_CRS AS [COURSE]
	ON
	[COURSE_HISTORY].[COURSE_GU] = [COURSE].[COURSE_GU]
	
WHERE
	[ENROLLMENTS].[RN] = 1
	AND [COURSE].[DEPARTMENT] = 'Math'
	AND [ENROLLMENTS].[GRADE] >= '08'