



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[ENROLLMENTS].[SCHOOL_YEAR]
	,[STUDENT].[BIRTH_DATE]
	,[ENROLLMENTS].[GRADE]
	,[STUDENT].[GENDER]
	,[STUDENT].[HISPANIC_INDICATOR]
	,[STUDENT].[RACE_1]
	,[STUDENT].[RACE_2]
	,[STUDENT].[RACE_3]
	,[STUDENT].[RACE_4]
	,[STUDENT].[RACE_5]
	,[STUDENT].[RESOLVED_RACE]
	,[STUDENT].[LUNCH_STATUS]
	,[STUDENT].[ELL_STATUS]
	,[STUDENT].[PRIMARY_DISABILITY_CODE]
	, rpt.ROLE_NAME_LARGE	   			     AS [Program Involvment]
	, rpt.LEVEL_INTEGRATION			 	     AS [Level Of Service]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	
FROM
	(
	SELECT
		*
		,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN
	FROM
		APS.StudentEnrollmentDetails
		
	WHERE
		SCHOOL_YEAR = 2014
		AND EXTENSION = 'R'
		AND EXCLUDE_ADA_ADM IS NULL
		
	) AS [ENROLLMENTS]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT JOIN 
    (
	   SELECT 
		  rpt.[STUDENT_GU]
		  ,rpt.[LEVEL_INTEGRATION]
		  ,rol.ROLE_NAME_LARGE
		  ,ROW_NUMBER() OVER (PARTITION BY rpt.[STUDENT_GU] ORDER BY rpt.[CHANGE_DATE_TIME_STAMP] DESC) AS [rn] 
	   FROM 
		  [rev].[EPC_NM_STU_SPED_RPT] rpt
    
		  LEFT JOIN
		  [rev].[EP_STAFF_ROLE_SPED] sprl
		  ON
		  rpt.CASE_MANAGER_GU=sprl.STAFF_GU
    
		  LEFT JOIN
		  [rev].[REV_ROLE] rol
		  ON
		  sprl.ROLE_GU=rol.ROLE_GU

	   WHERE 
		  [SCHOOL_YEAR]=2014

    ) rpt
    ON
    [ENROLLMENTS].STUDENT_GU=rpt.STUDENT_GU
    AND rpt.rn=1
	
WHERE
	[ENROLLMENTS].[RN] = 1