SELECT
	--SIS_NUMBER
	--,SCHOOL_CODE
	--,TEST_STUDENT_GRADE
	--,CONTENT_AREA
	--,SCORE
	--,CASE WHEN SCORE >= 18 THEN 'PASS' ELSE 'FAIL'
	--END AS PERFORMANCE_LEVEL

	distinct CONVERT (CHAR(10), TEST_DATE,126) AS TEST_DATE
	,test_product
	,test_name

FROM
(
SELECT
    ROW_NUMBER () OVER (PARTITION BY STUDENT_ID ORDER BY DTBL_CALENDAR_DATES.DATE_VALUE) AS RN
	,STUDENT_ID AS SIS_NUMBER
    ,DTBL_STUDENTS.STUDENT_GRADUATION_COHORT
    ,TEST_NAME
    ,TEST_EXTERNAL_CODE AS TEST_WINDOW
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
    ,YEAR_VALUE AS YEAR
    ,TEST_PRODUCT 
    ,TEST_SUBJECT AS CONTENT_AREA
    ,DTBL_CALENDAR_DATES.DATE_VALUE AS TEST_DATE
    ,CAST(TEST_SCORE_VALUE AS INT) AS SCORE
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
    --,TEST_NAME
	,SIS_SCHOOL_YEAR
    ,TEST_CLASS
    ,TEST_GROUP
    ,TEST_SUBGROUP
    ,TEST_ADMIN_PERIOD
	--,TEST_PRODUCT
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 1 = 1

--and TEST_PRODUCT = 'act'
--AND TEST_NAME = 'ACT'
--AND TEST_SUBGROUP IN ('TOT','Composite')
--AND LOCAL_SCHOOL_YEAR = '2016-2017'
and SIS_SCHOOL_YEAR = '2016'
--AND STUDENT_ID = '980002497'
)T1
WHERE 1 = 1
AND RN = 1
--ORDER BY SIS_NUMBER