
SELECT 
	COURSE_ID
	,COURSE_TITLE
	,SECTION.SECTION_ID
	,SECTION.ORGANIZATION_GU
	,CRS.INACTIVE
	,ST.VALUE_DESCRIPTION AS SCHOOL_TYPE

FROM REV.EPC_CRS AS CRS

LEFT JOIN
(
SELECT 
	DISTINCT
	YCRS.COURSE_GU
	,SECTION_ID
	,ORGANIZATION_GU
	
FROM
	REV.EPC_SCH_YR_CRS AS YCRS

INNER JOIN
	REV.EPC_SCH_YR_SECT AS SECT
	ON SECT.SCHOOL_YEAR_COURSE_GU = YCRS.SCHOOL_YEAR_COURSE_GU

INNER JOIN
	REV.REV_ORGANIZATION_YEAR AS OYR
	ON OYR.ORGANIZATION_YEAR_GU = ycrs.ORGANIZATION_YEAR_GU
	AND OYR.YEAR_GU = (select YEAR_GU from rev.SIF_22_Common_CurrentYearGU)

INNER JOIN
	REV.REV_YEAR AS YR
	ON YR.YEAR_GU = OYR.YEAR_GU
) AS SECTION
ON SECTION.COURSE_GU = CRS.COURSE_GU

LEFT JOIN
	REV.EPC_CRS_SCH_TYP_LST AS LST
	ON LST.COURSE_GU = CRS.COURSE_GU

LEFT JOIN APS.LookupTable ('K12','SCHOOL_TYPE') ST
	ON ST.VALUE_CODE = LST.SCHOOL_TYPE

WHERE 1 = 1
	AND CRS.INACTIVE = 'N'
	AND ORGANIZATION_GU IS NULL

ORDER BY COURSE_ID


