
DECLARE @asofDate date = getdate()
--SELECT
--	SY
--	,[SCHOOL LOCATION]
--	,[COURSE NUMBER]
--	,[COURSE NAME]
--	,COUNT (ID) AS 'COUNT OF STUDENT TOOK'
--FROM
--(
SELECT 
	DISTINCT 
	'2016' AS SY
	,ORGANIZATION_NAME AS 'SCHOOL LOCATION'
	,COURSE_ID AS 'COURSE NUMBER'
	,COURSE_TITLE AS 'COURSE NAME'
	,PER.LAST_NAME + ', '+PER.FIRST_NAME AS 'STUDENT NAME'
	,SCH.SIS_NUMBER AS ID
	,GRADE.VALUE_DESCRIPTION AS 'GRADE LEVEL'
	,SECT.SECTION_ID AS 'SECTION NUMBER'
	,SECT.TERM_CODE AS 'TERM CODE'
	--,* 
FROM 
	(
	SELECT
	ORG.ORGANIZATION_NAME
	,SIS_NUMBER
	,CourseMaster.COURSE_ID
	,CourseMaster.COURSE_TITLE
	,CourseMaster.CREDIT
	-- I am sure we will want to add more Course Level info here (Dual credit... etc.)
	,CourseMaster.DEPARTMENT
	,CourseMaster.GRADE_RANGE_LOW
	,CourseMaster.GRADE_RANGE_HIGH
	,CourseMaster.COURSE_HISTORY_TYPE
	,CourseMaster.ACADEMIC_TYPE
	,CourseMaster.SUBJECT_AREA_1
	,CourseMaster.SUBJECT_AREA_2
	,CourseMaster.SUBJECT_AREA_3
	,CourseMaster.SUBJECT_AREA_4
	,CourseMaster.SUBJECT_AREA_5
	,CourseMaster.PROGRAM_3Y
	,CourseMaster.PROGRAM_4Y
	,CourseMaster.ONLINE_COURSE
	,CourseMaster.DISTANCE_LEARNING
	,CourseMaster.AP_INDICATOR
	,CourseMaster.COURSE_DURATION
	,BasicSchedule.*
FROM
	APS.BasicSchedule
	INNER JOIN
	rev.EPC_CRS AS CourseMaster
	ON
	BasicSchedule.COURSE_GU = CourseMaster.COURSE_GU
	INNER JOIN
	rev.REV_ORGANIZATION AS ORG
	ON
	BasicSchedule.ORGANIZATION_GU = ORG.ORGANIZATION_GU
	INNER JOIN
	rev.EPC_STU AS STU
	ON
	STU.STUDENT_GU = BasicSchedule.STUDENT_GU
	
WHERE
	@asOfDate BETWEEN BasicSchedule.COURSE_ENTER_DATE AND COALESCE(BasicSchedule.COURSE_LEAVE_DATE, @asOfDate)
	AND CourseMaster.COURSE_ID IN ('205751','205752','215361','215362','215371','215372','515041','515042','51504c','515071','515072','afst1150','amst183','amst185','amst186','CCS201')
) AS SCH
LEFT JOIN
REV.EPC_STU AS STU
ON STU.STUDENT_GU = SCH.STUDENT_GU
LEFT JOIN
REV.REV_PERSON AS PER
ON PER.PERSON_GU = SCH.STUDENT_GU
LEFT JOIN rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade 
ON grade.VALUE_CODE = SCH.ENROLLMENT_GRADE_LEVEL
LEFT JOIN
rev.EPC_SCH_YR_SECT AS SECT
ON SECT.SECTION_GU = SCH.SECTION_GU
WHERE 1 = 1
--) AS T1

--GROUP BY SY, [SCHOOL LOCATION], [COURSE NUMBER], [COURSE NAME]
ORDER BY [SCHOOL LOCATION], [COURSE NUMBER]