



SELECT
	SCH.SCHOOL_CODE
	,STU.STATE_STUDENT_NUMBER
	,LEFT(CS.MARK,1) AS MARK
	,CS.CREDIT_COMPLETED
	,CRS.STATE_COURSE_CODE
	,CS.COURSE_ID + '-'+ CS.SECTION_ID + '-' + STF.STATE_ID
FROM
	APS.EnrollmentsAsOf (GETDATE()) ENR

JOIN
	REV.REV_ORGANIZATION_YEAR OYR
	ON OYR.ORGANIZATION_YEAR_GU = ENR.ORGANIZATION_YEAR_GU
JOIN
	REV.EPC_STU STU
	ON STU.STUDENT_GU = ENR.STUDENT_GU
JOIN
	rev.[EPC_STU_CRS_HIS] AS CS
	ON CS.STUDENT_GU = STU.STUDENT_GU
	AND CS.SCHOOL_IN_DISTRICT_GU = OYR.ORGANIZATION_GU
JOIN
	REV.EPC_CRS CRS
	ON CRS.COURSE_GU = CS.COURSE_GU
JOIN
	REV.REV_ORGANIZATION ORG
	ON ORG.ORGANIZATION_GU = OYR.ORGANIZATION_GU
JOIN
	REV.EPC_SCH SCH
	ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU
JOIN
	APS.SectionsAndAllStaffAssigned AS SS
	ON SS.SECTION_GU = CS.SECTION_GU
JOIN
	REV.EPC_STAFF STF
	ON STF.STAFF_GU = SS.STAFF_GU

WHERE 1 = 1
AND CS.SCHOOL_YEAR = '2016'
AND SCH.SCHOOL_CODE IN ('701','702','703')
AND CRS.DUAL_CREDIT = 'Y'
--and STATE_STUDENT_NUMBER = '100503838'

ORDER BY SIS_NUMBER