

SELECT DISTINCT
	DISC.SIS_NUMBER
	,VIOLATION_DESCRIPTION
	,INCIDENT_ID
	--,RN1
	--,[DESCRIPTION]
	--,COUNTS
FROM
	[RDAVM.APS.EDU.ACTD].DB_STARS_HISTORY.[DBO].[STUDENT] STU	
JOIN
(
SELECT
	SIS_NUMBER
	,VIOLATION_DESCRIPTION
	,INCIDENT_ID
	,RN1
	--,COUNT (VIOLATION_DESCRIPTION) COUNTS
FROM
	(

	SELECT 
		ROW_NUMBER () OVER (PARTITION BY [STUDENT].[SIS_NUMBER], INCIDENT.INCIDENT_ID ORDER BY [Disposition].[DISPOSITION_DATE] DESC) AS RN1
		,[ENROLLMENTS].[SCHOOL_CODE]
		,[ENROLLMENTS].[SCHOOL_NAME]
		,[STUDENT].[SIS_NUMBER]
		--,[ENROLLMENTS].[GRADE]
		--,[Disposition].[DISPOSITION_DATE]
		--,[Disposition_Code].STATE_CODE
		--,[Discipline].[DAYS]
		--,[Disposition_Code].[DISP_CODE]
		--,[Disposition_Code].[DESCRIPTION] AS [DISPOSITION_DESCRIPTION]
		--,[Disposition].[REASSIGNMENT_DAYS]
		--,[Violation_Code].[DISC_CODE]
		,INCIDENT.INCIDENT_ID
		,[Violation_Code].[DESCRIPTION] AS [VIOLATION_DESCRIPTION]
	FROM
		(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN2
		FROM
			APS.StudentEnrollmentDetails
			
		WHERE
			SCHOOL_YEAR = 2014
			AND EXTENSION = 'R'
			AND EXCLUDE_ADA_ADM IS NULL
		) AS [ENROLLMENTS]
		
		INNER JOIN
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		ON
		[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		INNER JOIN
		[rev].[EPC_STU_INC_DISCIPLINE] AS [Discipline]
		ON
		[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [Discipline].[STUDENT_SCHOOL_YEAR_GU]
	    
		INNER JOIN
		rev.EPC_SCH_INCIDENT AS [INCIDENT]
		ON
		[Discipline].[SCH_INCIDENT_GU] = [INCIDENT].[SCH_INCIDENT_GU]
	    
		INNER JOIN
		[rev].[EPC_STU_INC_DISPOSITION] AS [Disposition]
		ON
		[Discipline].[STU_INC_DISCIPLINE_GU] = [Disposition].[STU_INC_DISCIPLINE_GU]
	    
		INNER JOIN
		[rev].[EPC_CODE_DISP] AS [Disposition_Code]
		ON
		[Disposition].[CODE_DISP_GU] = [Disposition_Code].[CODE_DISP_GU]
		AND Disposition_Code.SCHOOL_YEAR = '2014'
	    
		LEFT OUTER JOIN
		[rev].[EPC_STU_INC_VIOLATION] AS [Violation]
		ON
		[Discipline].[SCH_INCIDENT_GU] = [Violation].[SCH_INCIDENT_GU]
	    
		LEFT OUTER JOIN
		[rev].[EPC_CODE_DISC] AS [Violation_Code]
		ON
		[Violation].[CODE_DISC_GU] = [Violation_Code].[CODE_DISC_GU]
		AND Violation_Code.SCHOOL_YEAR = '2014'

	WHERE 1 = 1
		AND RN2 = 1
) T1
--WHERE RN1 = 1
--GROUP BY SIS_NUMBER, VIOLATION_DESCRIPTION
) AS DISC
ON DISC.SIS_NUMBER = SIS_NUMBER
WHERE 1 = 1
    AND RN1 = 1
	AND STU.PERIOD = '2016-03-01'
	AND STU.[DISTRICT CODE] = '001'
	--AND SIS_NUMBER = '100003896'

ORDER BY SIS_NUMBER
