
WITH ALGII_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS Algebra II'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)

,ALGI_15 AS
(SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS Algebra 1'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ELA9_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS ELA/L English 9'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ELA10_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS ELA/L English 10'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ELA11_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS ELA/L English 11'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,GEOM_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS Geometry'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ES_ELA_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC ES ELA'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ES_MATH_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC ES Math'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,MS_MATH_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC MS Math 06-08'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,MS_ELA_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC MS ELA 06-08'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)

,HS_SBA_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'SBA HS Science 2011+'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ES_SBA_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
	   ,PART.PART_DESCRIPTION

FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'SBA ES 2011 Plus'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
	   AND PART_DESCRIPTION = 'SCIENCE'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,MS_SBA_15 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
	   ,PART.PART_DESCRIPTION

FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'SBA MS 2011 Plus'
       AND ADMIN_DATE BETWEEN '2015-08-01 00:00:00' AND '2016-05-31 00:00:00'
	   AND PART_DESCRIPTION = 'SCIENCE'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ALGII_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS Algebra II'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)

,ALGI_14 AS
(SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS Algebra 1'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ELA9_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS ELA/L English 9'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ELA10_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS ELA/L English 10'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ELA11_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS ELA/L English 11'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,GEOM_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC HS Geometry'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ES_ELA_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC ES ELA'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ES_MATH_14 AS
(
SELECT  ---distinct test_name
	STUDENT_ID AS SIS_NUMBER
	,TEST_PRIMARY_RESULT AS PL
	,TEST_NAME
	,DTBL_CALENDAR_DATES.DATE_VALUE AS ADMIN_DATE
FROM [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
--AND TEST_NAME LIKE '%parcc%'
AND TEST_GROUP = 'MATHEMATICS'
AND TEST_SUBGROUP IN ('overall')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
AND TEST_NAME IN ('PARCC Grade 03 – Mathematics – Overall','PARCC Grade 04 – Mathematics – Overall','PARCC Grade 05 – Mathematics – Overall')
)
,MS_MATH_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC MS Math 06-08'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,MS_ELA_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'PARCC MS ELA 06-08'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,HS_SBA_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'SBA HS Science 2011+'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,ES_SBA_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
	   ,PART.PART_DESCRIPTION

FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'SBA ES 2011 Plus'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
	   AND PART_DESCRIPTION = 'SCIENCE'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,MS_SBA_14 AS
(
SELECT DISTINCT
	SIS_NUMBER
	,PL
	,TEST_NAME
	,ADMIN_DATE
FROM
(
SELECT 
	   ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY TEST_SCORE DESC) AS RN
       ,CAST (SIS_NUMBER AS INT) AS SIS_NUMBER
       ,TEST.TEST_NAME
       ,STU_PART.PERFORMANCE_LEVEL AS PL
       ,SCORES.TEST_SCORE
       ,STUDENTTEST.ADMIN_DATE
	   ,PART.PART_DESCRIPTION

FROM
       rev.EPC_STU_TEST AS StudentTest

       JOIN
       rev.EPC_TEST_PART AS PART
       ON StudentTest.TEST_GU = PART.TEST_GU

       JOIN
       rev.EPC_STU_TEST_PART AS STU_PART
       ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
       AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU

       LEFT JOIN
       rev.EPC_TEST AS TEST
       ON TEST.TEST_GU = StudentTest.TEST_GU

       INNER JOIN
       rev.EPC_STU AS Student
       ON Student.STUDENT_GU = StudentTest.STUDENT_GU

WHERE
1 = 1
       --AND TEST_NAME = 'WAPT'
	   AND TEST_NAME = 'SBA MS 2011 Plus'
       AND ADMIN_DATE BETWEEN '2014-08-01 00:00:00' AND '2015-05-31 00:00:00'
	   AND PART_DESCRIPTION = 'SCIENCE'
) AS T1
WHERE 1 = 1
AND RN = 1
)
,DIB_BOY_15 AS
(
SELECT 
    STUDENT_ID AS SIS_NUMBER
    ,TEST_NAME
	,TEST_ADMIN_PERIOD
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
FROM [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_PRODUCT = 'DIBELS Next'
AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2015-2016'
AND TEST_ADMIN_PERIOD IN ('BEG','BOY')
)
,DIB_EOY_15 AS
(
SELECT
    STUDENT_ID AS SIS_NUMBER
    ,TEST_NAME
	,TEST_ADMIN_PERIOD
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
FROM [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_PRODUCT = 'DIBELS Next'
AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_ADMIN_PERIOD IN ('BOY','BEG')
AND TEST_ADMIN_PERIOD IN ('EOY')
--AND TEST_ADMIN_PERIOD IN ('MID','MOY')
)
,DIB_MOY_15 AS
(
SELECT
    STUDENT_ID AS SIS_NUMBER
    ,TEST_NAME
	,TEST_ADMIN_PERIOD
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
FROM [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_PRODUCT = 'DIBELS Next'
AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_ADMIN_PERIOD IN ('BOY','BEG')
--AND TEST_ADMIN_PERIOD IN ('EOY')
AND TEST_ADMIN_PERIOD IN ('MID','MOY')
)
,DIB_BOY_14 AS
(
SELECT 
    STUDENT_ID AS SIS_NUMBER
    ,TEST_NAME
	,TEST_ADMIN_PERIOD
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
FROM [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_PRODUCT = 'DIBELS Next'
AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
AND TEST_ADMIN_PERIOD IN ('BEG','BOY')
)
,DIB_EOY_14 AS
(
SELECT
    STUDENT_ID AS SIS_NUMBER
    ,TEST_NAME
	,TEST_ADMIN_PERIOD
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
FROM [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_PRODUCT = 'DIBELS Next'
AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
--AND TEST_ADMIN_PERIOD IN ('BOY','BEG')
AND TEST_ADMIN_PERIOD IN ('EOY')
--AND TEST_ADMIN_PERIOD IN ('MID','MOY')
)
,DIB_MOY_14 AS
(
SELECT
    STUDENT_ID AS SIS_NUMBER
    ,TEST_NAME
	,TEST_ADMIN_PERIOD
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
FROM [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN [VERSIFIT.APS.EDU.ACTD].K12INTEL.K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 
1 = 1
AND TEST_PRODUCT = 'DIBELS Next'
AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
--AND TEST_ADMIN_PERIOD IN ('BOY','BEG')
--AND TEST_ADMIN_PERIOD IN ('EOY')
AND TEST_ADMIN_PERIOD IN ('MID','MOY')
)
,INCIDENCES_15 AS
(
SELECT
	SIS_NUMBER
	,COUNT(INCIDENT_ID) INCIDENCES
FROM
	(

	SELECT 
		ROW_NUMBER () OVER (PARTITION BY [STUDENT].[SIS_NUMBER], INCIDENT_ID ORDER BY [Disposition].[DISPOSITION_DATE] DESC) AS RN1
		,[STUDENT].[SIS_NUMBER]
		,Violation_Code.SCHOOL_YEAR
		,INCIDENT_ID
	FROM
		(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN2
		FROM
			APS.StudentEnrollmentDetails
			
		WHERE
			SCHOOL_YEAR = 2015
			AND EXTENSION = 'R'
			AND EXCLUDE_ADA_ADM IS NULL
		) AS [ENROLLMENTS]
		
		INNER JOIN
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		ON
		[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		INNER JOIN
		[rev].[EPC_STU_INC_DISCIPLINE] AS [Discipline]
		ON
		[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [Discipline].[STUDENT_SCHOOL_YEAR_GU]
	    
		INNER JOIN
		rev.EPC_SCH_INCIDENT AS [INCIDENT]
		ON
		[Discipline].[SCH_INCIDENT_GU] = [INCIDENT].[SCH_INCIDENT_GU]
	    
		INNER JOIN
		[rev].[EPC_STU_INC_DISPOSITION] AS [Disposition]
		ON
		[Discipline].[STU_INC_DISCIPLINE_GU] = [Disposition].[STU_INC_DISCIPLINE_GU]
	    
		INNER JOIN
		[rev].[EPC_CODE_DISP] AS [Disposition_Code]
		ON
		[Disposition].[CODE_DISP_GU] = [Disposition_Code].[CODE_DISP_GU]
		AND Disposition_Code.SCHOOL_YEAR =  2015
	    
		LEFT OUTER JOIN
		[rev].[EPC_STU_INC_VIOLATION] AS [Violation]
		ON
		[Discipline].[SCH_INCIDENT_GU] = [Violation].[SCH_INCIDENT_GU]
	    
		LEFT OUTER JOIN
		[rev].[EPC_CODE_DISC] AS [Violation_Code]
		ON
		[Violation].[CODE_DISC_GU] = [Violation_Code].[CODE_DISC_GU]
		AND Violation_Code.SCHOOL_YEAR = 2015

	WHERE 1 = 1
		AND RN2 = 1
) T1
WHERE 1 = 1
AND RN1 = 1
GROUP BY SIS_NUMBER

)
,INCIDENCES_14 AS
(
SELECT
	SIS_NUMBER
	,COUNT(INCIDENT_ID) INCIDENCES
FROM
	(

	SELECT 
		ROW_NUMBER () OVER (PARTITION BY [STUDENT].[SIS_NUMBER], INCIDENT_ID ORDER BY [Disposition].[DISPOSITION_DATE] DESC) AS RN1
		,[STUDENT].[SIS_NUMBER]
		,Violation_Code.SCHOOL_YEAR
		,INCIDENT_ID
	FROM
		(
		SELECT
			*
			,ROW_NUMBER() OVER (PARTITION BY [STUDENT_GU] ORDER BY [ENTER_DATE] DESC) AS RN2
		FROM
			APS.StudentEnrollmentDetails
			
		WHERE
			SCHOOL_YEAR = 2014
			AND EXTENSION = 'R'
			AND EXCLUDE_ADA_ADM IS NULL
		) AS [ENROLLMENTS]
		
		INNER JOIN
		APS.BasicStudentWithMoreInfo AS [STUDENT]
		ON
		[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
		
		INNER JOIN
		[rev].[EPC_STU_INC_DISCIPLINE] AS [Discipline]
		ON
		[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [Discipline].[STUDENT_SCHOOL_YEAR_GU]
	    
		INNER JOIN
		rev.EPC_SCH_INCIDENT AS [INCIDENT]
		ON
		[Discipline].[SCH_INCIDENT_GU] = [INCIDENT].[SCH_INCIDENT_GU]
	    
		INNER JOIN
		[rev].[EPC_STU_INC_DISPOSITION] AS [Disposition]
		ON
		[Discipline].[STU_INC_DISCIPLINE_GU] = [Disposition].[STU_INC_DISCIPLINE_GU]
	    
		INNER JOIN
		[rev].[EPC_CODE_DISP] AS [Disposition_Code]
		ON
		[Disposition].[CODE_DISP_GU] = [Disposition_Code].[CODE_DISP_GU]
		AND Disposition_Code.SCHOOL_YEAR =  2014
	    
		LEFT OUTER JOIN
		[rev].[EPC_STU_INC_VIOLATION] AS [Violation]
		ON
		[Discipline].[SCH_INCIDENT_GU] = [Violation].[SCH_INCIDENT_GU]
	    
		LEFT OUTER JOIN
		[rev].[EPC_CODE_DISC] AS [Violation_Code]
		ON
		[Violation].[CODE_DISC_GU] = [Violation_Code].[CODE_DISC_GU]
		AND Violation_Code.SCHOOL_YEAR = 2014

	WHERE 1 = 1
		AND RN2 = 1
) T1
WHERE 1 = 1
AND RN1 = 1
			--and SIS_NUMBER = '100003896'

GROUP BY SIS_NUMBER
)
, ABSENSES_14 AS
(
SELECT
	[SIS Number]
	,[Total Excused]
	,[Total Unexcused]
FROM
(
SELECT
	ROW_NUMBER () OVER (PARTITION BY [SIS Number] ORDER BY SA.[School Code]) AS RN
	,[SIS Number]
	,[Total Excused]
	,[Total Unexcused]
	,SA.[School Code]
	
FROM
	STUDENT_ATTENDANCE_2014 SA
	JOIN
	REV.EPC_STU STU
	ON STU.SIS_NUMBER = SA.[SIS Number]
	JOIN
	APS.EnrollmentsForYear ('26F066A3-ABFC-4EDB-B397-43412EDABC8B') YR
	ON YR.STUDENT_GU = STU.STUDENT_GU
	AND YR.ORGANIZATION_GU = SA.ORGANIZATION_GU

) A
WHERE RN = 1
)
,ABSENSES_15 AS
(
SELECT
	[SIS Number]
	,[Total Excused]
	,[Total Unexcused]
FROM
(
SELECT
	ROW_NUMBER () OVER (PARTITION BY [SIS Number] ORDER BY SA.[School Code]) AS RN
	,[SIS Number]
	,[Total Excused]
	,[Total Unexcused]
	,SA.[School Code]
	
FROM
	STUDENT_ATTENDANCE_2015 SA
	JOIN
	REV.EPC_STU STU
	ON STU.SIS_NUMBER = SA.[SIS Number]
	JOIN
	APS.EnrollmentsForYear ('BCFE2270-A461-4260-BA2B-0087CB8EC26A') YR
	ON YR.STUDENT_GU = STU.STUDENT_GU
	AND YR.ORGANIZATION_GU = SA.ORGANIZATION_GU

) A
WHERE RN = 1
)


, ABSENSES_11 AS
(
SELECT
	SIS_NUMBER
	,UNFD + UNHD AS [Total Unexcused]
	,UNFD
	,UNHD
	,RN
FROM
(
	SELECT
			ROW_NUMBER () OVER (PARTITION BY RDA.[STUDENT ID] ORDER BY RDA.[STUDENT ID]) AS RN	 
			,RDA.[STUDENT ID] AS SIS_NUMBER
			,YR2011.UNFD
			,YR2011.UNHD
	FROM
	[RDAVM.APS.EDU.ACTD].db_STARS_History.dbo.STUDENT AS RDA

	LEFT JOIN
	(
		SELECT 
			SY
			,[STUDENT ID]
			--,[LOCATION CODE]
			,SUM (CASE WHEN ([ATTENDANCE CODE LONG]) = 'UNFD' THEN 1 ELSE 0 END) AS UNFD
			,SUM (CASE WHEN ([ATTENDANCE CODE LONG]) = 'UNHD' THEN 1 ELSE 0 END) AS UNHD
		FROM
			[RDAVM.APS.EDU.ACTD].db_STARS_History.DBO.STUD_ATTEND_DAY AS SAD


		WHERE 1 = 1
			AND SAD.SY = 2012
			AND SAD.[DISTRICT CODE] = '001'
		GROUP BY
			SAD.SY
			,SAD.[STUDENT ID]
			--,SAD.[LOCATION CODE]
	) AS YR2011
	ON RDA.[STUDENT ID] = YR2011.[STUDENT ID]
	WHERE 1 = 1
	AND RDA.Period = '2016-03-01'
	AND RDA.[DISTRICT CODE] = '001'
) AS UX2011
WHERE 1 = 1
--AND RN = 1)
)

, ABSENSES_12 AS
(
SELECT
	SIS_NUMBER
	,UNFD + UNHD AS [Total Unexcused]
	,UNFD
	,UNHD
	,RN
FROM
(
	SELECT
			ROW_NUMBER () OVER (PARTITION BY RDA.[STUDENT ID] ORDER BY RDA.[STUDENT ID]) AS RN	 
			,RDA.[STUDENT ID] AS SIS_NUMBER
			,YR2011.UNFD
			,YR2011.UNHD
	FROM
	[RDAVM.APS.EDU.ACTD].db_STARS_History.dbo.STUDENT AS RDA

	LEFT JOIN
	(
		SELECT 
			SY
			,[STUDENT ID]
			--,[LOCATION CODE]
			,SUM (CASE WHEN ([ATTENDANCE CODE LONG]) = 'UNFD' THEN 1 ELSE 0 END) AS UNFD
			,SUM (CASE WHEN ([ATTENDANCE CODE LONG]) = 'UNHD' THEN 1 ELSE 0 END) AS UNHD
		FROM
			[RDAVM.APS.EDU.ACTD].db_STARS_History.DBO.STUD_ATTEND_DAY AS SAD


		WHERE 1 = 1
			AND SAD.SY = 2013
			AND SAD.[DISTRICT CODE] = '001'
		GROUP BY
			SAD.SY
			,SAD.[STUDENT ID]
			--,SAD.[LOCATION CODE]
	) AS YR2011
	ON RDA.[STUDENT ID] = YR2011.[STUDENT ID]
	WHERE 1 = 1
	AND RDA.Period = '2016-03-01'
	AND RDA.[DISTRICT CODE] = '001'
) AS UX2011
WHERE 1 = 1
--AND RN = 1)
)


, ABSENSES_13 AS
(
SELECT
	SIS_NUMBER
	,UNFD + UNHD AS [Total Unexcused]
	,UNFD
	,UNHD
	,RN
FROM
(
	SELECT
			ROW_NUMBER () OVER (PARTITION BY RDA.[STUDENT ID] ORDER BY RDA.[STUDENT ID]) AS RN	 
			,RDA.[STUDENT ID] AS SIS_NUMBER
			,YR2011.UNFD
			,YR2011.UNHD
	FROM
	[RDAVM.APS.EDU.ACTD].db_STARS_History.dbo.STUDENT AS RDA

	LEFT JOIN
	(
		SELECT 
			SY
			,[STUDENT ID]
			--,[LOCATION CODE]
			,SUM (CASE WHEN ([ATTENDANCE CODE LONG]) = 'UNFD' THEN 1 ELSE 0 END) AS UNFD
			,SUM (CASE WHEN ([ATTENDANCE CODE LONG]) = 'UNHD' THEN 1 ELSE 0 END) AS UNHD
		FROM
			[RDAVM.APS.EDU.ACTD].db_STARS_History.DBO.STUD_ATTEND_DAY AS SAD


		WHERE 1 = 1
			AND SAD.SY = 2014
			AND SAD.[DISTRICT CODE] = '001'
		GROUP BY
			SAD.SY
			,SAD.[STUDENT ID]
			--,SAD.[LOCATION CODE]
	) AS YR2011
	ON RDA.[STUDENT ID] = YR2011.[STUDENT ID]
	WHERE 1 = 1
	AND RDA.Period = '2016-03-01'
	AND RDA.[DISTRICT CODE] = '001'
) AS UX2011
WHERE 1 = 1
--AND RN = 1)
)

SELECT DISTINCT
	[ALTERNATE STUDENT ID] AS [Student ID]
	,[STUDENT ID] AS [STARS ID]
	,[CURRENT GRADE LEVEL] AS [Grade Level]
	,[GENDER CODE] AS Gender
	,BS.HISPANIC_INDICATOR AS [Hispanic Indicator]
	,BS.RESOLVED_RACE AS [Resolved Race]
	,BS.RACE_1
	,BS.RACE_2
	,BS.RACE_3
	,BS.RACE_4
	,BS.RACE_5
	,BS.LUNCH_STATUS AS [FRPL Status]
	,BS.ELL_STATUS AS [ELL Status]
	,BS.SPED_STATUS AS [SPED Status]
	,CASE WHEN ALGI_15.PL IS NULL THEN '' ELSE ALGI_15.PL
	END AS [PARCC ALGI Proficiency Level 2015-16]
	,CASE WHEN ALGII_15.PL IS NULL THEN '' ELSE ALGII_15.PL
	END AS [PARCC ALGII Proficiency Level 2015-16]
	,CASE WHEN GEOM_15.PL IS NULL THEN '' ELSE GEOM_15.PL
	END AS [PARCC GEOM Proficiency Level 2015-16]
	,CASE WHEN ELA9_15.PL IS NULL THEN '' ELSE ELA9_15.PL
	END AS [PARCC ELA9 Proficiency Level 2015-16]
	,CASE WHEN ELA10_15.PL IS NULL THEN '' ELSE ELA10_15.PL
	END AS [PARCC ELA10 Proficiency Level 2015-16]
	,CASE WHEN ELA11_15.PL IS NULL THEN '' ELSE ELA11_15.PL
	END AS [PARCC ELA11 Proficiency Level 2015-16]

	,CASE WHEN MS_ELA_15.PL IS NULL THEN '' ELSE MS_ELA_15.PL
	END AS [PARCC MS ELA Proficiency Level 2015-16]
	,CASE WHEN MS_MATH_15.PL IS NULL THEN '' ELSE MS_MATH_15.PL
	END AS [PARCC MS MATH Proficiency Level 2015-16]

	,CASE WHEN ES_ELA_15.PL IS NULL THEN '' ELSE ES_ELA_15.PL
	END AS [PARCC ES ELA Proficiency Level 2015-16]
	,CASE WHEN ES_MATH_15.PL IS NULL THEN '' ELSE ES_MATH_15.PL
	END AS [PARCC ES MATH Proficiency Level 2015-16]

	,CASE WHEN HS_SBA_15.PL IS NULL THEN '' ELSE HS_SBA_15.PL
	END AS [SBA HS SCIENCE Proficiency Level 2015-16]
	,CASE WHEN MS_SBA_15.PL IS NULL THEN '' ELSE MS_SBA_15.PL
	END AS [SBA MS SCIENCE Proficiency Level 2015-16]
	,CASE WHEN ES_SBA_15.PL IS NULL THEN '' ELSE ES_SBA_15.PL
	END AS [SBA ES SCIENCE Proficiency Level 2015-16]

	,CASE WHEN DIB_BOY_15.PERFORMANCE_LEVEL IS NULL THEN '' ELSE DIB_BOY_15.PERFORMANCE_LEVEL
	END AS [DIBELS BOY Level 2015-16]
	,CASE WHEN DIB_MOY_15.PERFORMANCE_LEVEL IS NULL THEN '' ELSE DIB_MOY_15.PERFORMANCE_LEVEL
	END AS [DIBELS MOY Level 2015-16]
	,CASE WHEN DIB_EOY_15.PERFORMANCE_LEVEL IS NULL THEN '' ELSE DIB_EOY_15.PERFORMANCE_LEVEL
	END AS [DIBELS EOY Level 2015-16]

	,CASE WHEN DIB_BOY_14.PERFORMANCE_LEVEL IS NULL THEN '' ELSE DIB_BOY_14.PERFORMANCE_LEVEL
	END AS [DIBELS BOY Level 2014-15]
	,CASE WHEN DIB_MOY_14.PERFORMANCE_LEVEL IS NULL THEN '' ELSE DIB_MOY_14.PERFORMANCE_LEVEL
	END AS [DIBELS MOY Level 2014-15]
	,CASE WHEN DIB_EOY_14.PERFORMANCE_LEVEL IS NULL THEN '' ELSE DIB_EOY_14.PERFORMANCE_LEVEL
	END AS [DIBELS EOY Level 2014-15]

	,CASE WHEN ALGI_14.PL IS NULL THEN '' ELSE ALGI_14.PL
	END AS [PARCC ALGI Proficiency Level 2014-15]
	,CASE WHEN ALGII_14.PL IS NULL THEN '' ELSE ALGII_14.PL
	END AS [PARCC ALGII Proficiency Level 2014-15]
	,CASE WHEN GEOM_14.PL IS NULL THEN '' ELSE GEOM_14.PL
	END AS [PARCC GEOM Proficiency Level 2014-15]
	,CASE WHEN ELA9_14.PL IS NULL THEN '' ELSE ELA9_14.PL
	END AS [PARCC ELA9 Proficiency Level 2014-15]
	,CASE WHEN ELA10_14.PL IS NULL THEN '' ELSE ELA10_14.PL
	END AS [PARCC ELA10 Proficiency Level 2014-15]
	,CASE WHEN ELA11_14.PL IS NULL THEN '' ELSE ELA11_14.PL
	END AS [PARCC ELA11 Proficiency Level 2014-15]

	,CASE WHEN MS_ELA_14.PL IS NULL THEN '' ELSE MS_ELA_14.PL
	END AS [PARCC MS ELA Proficiency Level 2014-15]
	,CASE WHEN MS_MATH_14.PL IS NULL THEN '' ELSE MS_MATH_14.PL
	END AS [PARCC MS MATH Proficiency Level 2014-15]

	,CASE WHEN ES_ELA_14.PL IS NULL THEN '' ELSE ES_ELA_14.PL
	END AS [PARCC ES ELA Proficiency Level 2014-15]
	,CASE WHEN ES_MATH_14.PL IS NULL THEN '' ELSE ES_MATH_14.PL
	END AS [PARCC ES MATH Proficiency Level 2014-15]

	,CASE WHEN HS_SBA_14.PL IS NULL THEN '' ELSE HS_SBA_14.PL
	END AS [SBA HS SCIENCE Proficiency Level 2014-15]
	,CASE WHEN MS_SBA_14.PL IS NULL THEN '' ELSE MS_SBA_14.PL
	END AS [SBA MS SCIENCE Proficiency Level 2014-15]
	,CASE WHEN ES_SBA_14.PL IS NULL THEN '' ELSE ES_SBA_14.PL
	END AS [SBA ES SCIENCE Proficiency Level 2014-15]

	,CASE WHEN STUD.GRADUATION_DATE = '1900-01-01 00:00:00' OR STUD.GRADUATION_DATE IS NULL THEN '' 
	      ELSE CONVERT(VARCHAR,STUD.GRADUATION_DATE, 101)
	END AS 'Graduation Date'
	,CASE WHEN STUD.GRADUATION_STATUS IS NULL THEN '' ELSE STUD.GRADUATION_STATUS
	END AS 'Graduation Status'

	,CASE WHEN INCIDENCES_14.INCIDENCES IS NULL THEN '' ELSE INCIDENCES_14.INCIDENCES
	END AS [#Behavioral Incidences 2014]
	,CASE WHEN INCIDENCES_15.INCIDENCES IS NULL THEN '' ELSE INCIDENCES_15.INCIDENCES
	END AS [#Behavioral Incidences 2015]

	,ABSENSES_11.[Total Unexcused] AS [#Total Unexcused Absenses 2011]
	,ABSENSES_12.[Total Unexcused] AS [#Total Unexcused Absenses 2012]
	,ABSENSES_13.[Total Unexcused] AS [#Total Unexcused Absenses 2013]
	,ABSENSES_14.[Total Excused] AS [#Total Excused Absenses 2014]
	,ABSENSES_14.[Total Unexcused] AS [#Total Unexcused Absenses 2014]
	,ABSENSES_15.[Total Excused] AS [#Total Excused Absenses 2015]
	,ABSENSES_15.[Total Unexcused] AS [#Total Unexcused Absenses 2015]

FROM
	[RDAVM.APS.EDU.ACTD].DB_STARS_HISTORY.[DBO].[STUDENT] STU
	LEFT JOIN
	APS.BasicStudentWithMoreInfo BS
	ON BS.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	REV.EPC_STU STUD
	ON STUD.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ALGII_15
	ON ALGII_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ALGI_15
	ON ALGI_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ELA9_15
	ON ELA9_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ELA10_15
	ON ELA10_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ELA11_15
	ON ELA11_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	GEOM_15
	ON GEOM_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ES_ELA_15
	ON ES_ELA_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ES_MATH_15
	ON ES_MATH_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	MS_MATH_15
	ON MS_MATH_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	MS_ELA_15
	ON MS_ELA_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	HS_SBA_15
	ON HS_SBA_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ES_SBA_15
	ON ES_SBA_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	MS_SBA_15
	ON MS_SBA_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	DIB_BOY_15
	ON DIB_BOY_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	DIB_MOY_15
	ON DIB_MOY_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	DIB_EOY_15
	ON DIB_EOY_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	DIB_BOY_14
	ON DIB_BOY_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	DIB_MOY_14
	ON DIB_MOY_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	DIB_EOY_14
	ON DIB_EOY_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ALGII_14
	ON ALGII_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ALGI_14
	ON ALGI_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ELA9_14
	ON ELA9_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ELA10_14
	ON ELA10_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ELA11_14
	ON ELA11_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	GEOM_14
	ON GEOM_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ES_ELA_14
	ON ES_ELA_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ES_MATH_14
	ON ES_MATH_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	MS_MATH_14
	ON MS_MATH_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	MS_ELA_14
	ON MS_ELA_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	HS_SBA_14
	ON HS_SBA_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ES_SBA_14
	ON ES_SBA_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	MS_SBA_14
	ON MS_SBA_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	INCIDENCES_15
	ON INCIDENCES_15.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	INCIDENCES_14
	ON INCIDENCES_14.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ABSENSES_14
	ON ABSENSES_14.[SIS Number] = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ABSENSES_15
	ON ABSENSES_15.[SIS Number] = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ABSENSES_11
	ON ABSENSES_11.[SIS_Number] = STU.[ALTERNATE STUDENT ID]
LEFT JOIN 
	ABSENSES_12
	ON ABSENSES_12.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
LEFT JOIN
	ABSENSES_13
	ON ABSENSES_13.SIS_NUMBER = STU.[ALTERNATE STUDENT ID]
WHERE 1 = 1
	AND STU.PERIOD = '2016-03-01'
	AND STU.[DISTRICT CODE] = '001'
	--and STU.[ALTERNATE STUDENT ID] = '186787'
ORDER BY [ALTERNATE STUDENT ID]