
SELECT
	ID_NBR
	,EX_FULL_DAY + EX_HALF_DAY AS TOTAL_EXCUSED
	,UX_HALF_DAY + UX_FULL_DAY AS TOTAL_UNEXCUSED
FROM
	(
	SELECT
		IV3.MNT_DT
		,IV3.SCH_NBR
		,CPE.BEG_ENR_DT
		,MEMDAYS.MemberDays
		,IV3.ID_NBR
		,SUM(CASE WHEN (IV3.FIELDNUM=84) THEN 1.0 ELSE 0.0 END) AS EX_FULL_DAY
		,SUM(CASE WHEN (IV3.FIELDNUM=86) THEN 1.0 ELSE 0.0 END) AS EX_HALF_DAY
		,SUM(CASE WHEN (IV3.FIELDNUM=80) THEN 1.0 ELSE 0.0 END) AS UX_FULL_DAY
		,SUM(CASE WHEN (IV3.FIELDNUM=82) THEN 1.0 ELSE 0.0 END) AS UX_HALF_DAY
	--ADD SUMS TO GET TOTAL ABSENCES.    
		,SUM(CASE WHEN (IV3.FIELDNUM=80) THEN 1.0 ELSE 0.0 END) 
		+SUM(CASE WHEN (IV3.FIELDNUM=82) THEN 1.0 ELSE 0.0 END)/2.0
		+SUM(CASE WHEN (IV3.FIELDNUM=84) THEN 1.0 ELSE 0.0 END) 
		+SUM(CASE WHEN (IV3.FIELDNUM=86) THEN 1.0 ELSE 0.0 END)/2.0 AS [TOTAL ABSENCES]
					
	FROM
		--Join IV table to CurrentPrimaryEnrollment 
		DBTSIS.IV030_V AS IV3
		INNER JOIN
		APS.PrimaryEnrollmentsAsOf ('5-5-2014') AS CPE
		ON
		IV3.DST_NBR = CPE.DST_NBR
		AND IV3.ID_NBR = CPE.ID_NBR
		AND IV3.SCH_NBR = CPE.SCH_NBR
		--Add Member days
		LEFT JOIN 
		APS.EnrollmentMemberDaysAsOf('5-5-2014') AS MEMDAYS
		ON 
		CPE._Id = MEMDAYS.Enrollment_Id

	WHERE
		IV3.DST_NBR = 1
		AND CPE.SCH_NBR BETWEEN 200 AND 600
		AND IV3.SCH_YR = 2014
		
	GROUP BY 
		IV3.DST_NBR
		,IV3.ID_NBR
		,IV3.SCH_NBR
		,IV3.MNT_DT
		,CPE.BEG_ENR_DT
		,MEMDAYS.MemberDays
		)

	AS T1
	--INNER HASH JOIN
	----SELECT TOP 50 * FROM
	--[RDAVM.APS.EDU.ACTD].db_STARS_History.dbo.STUDENT AS RDA
	--ON CAST(RDA.[ALTERNATE STUDENT ID] AS VARCHAR) = CAST(ID_NBR AS VARCHAR)
	
	--WHERE RDA.Period = '2016-03-01'
	--where ID_NBR = '74670'
	--ORDER BY 
	--[TOTAL ABSENCES] DESC

