SELECT
	SIS_NUMBER
	,UNFD + UNHD AS [Total Unexcused]
	,UNFD
	,UNHD
	,RN
FROM
(
	SELECT
			ROW_NUMBER () OVER (PARTITION BY RDA.[STUDENT ID] ORDER BY RDA.[STUDENT ID]) AS RN	 
			,RDA.[STUDENT ID] AS SIS_NUMBER
			,YR2011.UNFD
			,YR2011.UNHD
	FROM
	[RDAVM.APS.EDU.ACTD].db_STARS_History.dbo.STUDENT AS RDA

	LEFT JOIN
	(
		SELECT 
			SY
			,[STUDENT ID]
			--,[LOCATION CODE]
			,SUM (CASE WHEN ([ATTENDANCE CODE LONG]) = 'UNFD' THEN 1 ELSE 0 END) AS UNFD
			,SUM (CASE WHEN ([ATTENDANCE CODE LONG]) = 'UNHD' THEN 1 ELSE 0 END) AS UNHD
		FROM
			[RDAVM.APS.EDU.ACTD].db_STARS_History.DBO.STUD_ATTEND_DAY AS SAD


		WHERE 1 = 1
			AND SAD.SY = 2012
			AND SAD.[DISTRICT CODE] = '001'
		GROUP BY
			SAD.SY
			,SAD.[STUDENT ID]
			--,SAD.[LOCATION CODE]
	) AS YR2011
	ON RDA.[STUDENT ID] = YR2011.[STUDENT ID]
	WHERE 1 = 1
	AND RDA.Period = '2016-03-01'
	AND RDA.[DISTRICT CODE] = '001'
) AS UX2011
WHERE 1 = 1
--AND RN = 1)
