SELECT
	BS.SIS_NUMBER
	,ORG.ORGANIZATION_NAME
	,SCH.SCHOOL_CODE
	,BS.GENDER
	,BS.RESOLVED_RACE
	,BS.SPED_STATUS
	,BS.LUNCH_STATUS
	,GRADE.VALUE_DESCRIPTION AS GRADE
	,GPA.[MS Cum Flat]

FROM
	APS.EnrollmentsForYear ('F7D112F7-354D-4630-A4BC-65F586BA42EC') ENR  --- 2016-2017
	
	JOIN
		REV.REV_ORGANIZATION AS ORG
		ON ORG.ORGANIZATION_GU = ENR.ORGANIZATION_GU
	JOIN
		REV.EPC_SCH AS SCH
		ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU
    JOIN
		REV.EPC_STU AS STU
		ON STU.STUDENT_GU = ENR.STUDENT_GU
	JOIN
		APS.BasicStudentWithMoreInfo AS BS
		ON BS.STUDENT_GU = ENR.STUDENT_GU
	JOIN rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade ON grade.VALUE_CODE = ENR.GRADE

	LEFT JOIN
	aps.CumGPAForYear ('2016') AS GPA
	ON GPA.SIS_NUMBER = STU.SIS_NUMBER


WHERE 1 = 1
	--AND ENR.LEAVE_DATE IS NULL
	AND ENR.EXCLUDE_ADA_ADM IS NULL
	AND SCH.SCHOOL_CODE IN ('496','416','413','420','427','450','425','492','457','465','475','448')
	AND GRADE.VALUE_DESCRIPTION IN ('06','07','08')
ORDER BY SCHOOL_CODE