SELECT
	BS.SIS_NUMBER
	,ORG.ORGANIZATION_NAME
	,SCH.SCHOOL_CODE
	,BS.RESOLVED_RACE
	,BS.SPED_STATUS
	,BS.LUNCH_STATUS
	,GRADE.VALUE_DESCRIPTION AS GRADE

FROM
	APS.EnrollmentsForYear ('BCFE2270-A461-4260-BA2B-0087CB8EC26A') ENR
	
	JOIN
		REV.REV_ORGANIZATION AS ORG
		ON ORG.ORGANIZATION_GU = ENR.ORGANIZATION_GU
	JOIN
		REV.EPC_SCH AS SCH
		ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU
    JOIN
		REV.EPC_STU AS STU
		ON STU.STUDENT_GU = ENR.STUDENT_GU
	JOIN
		APS.BasicStudentWithMoreInfo AS BS
		ON BS.STUDENT_GU = ENR.STUDENT_GU
	JOIN rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade ON grade.VALUE_CODE = ENR.GRADE


WHERE 1 = 1
	--AND ENR.LEAVE_DATE IS NULL
	AND ENR.EXCLUDE_ADA_ADM IS NULL
	AND SCH.SCHOOL_CODE IN ('496','416','413','420','427','450','425','492','457','418','475','448')
	AND GRADE.VALUE_DESCRIPTION IN ('06','07','08')
ORDER BY SCHOOL_CODE