SELECT 
	SIS_NUMBER
	,TEST_NAME
	,TEST_DATE
	,SCHOOL
	,GRADE
	,SCH_YR
	,READING_SCORE
	,READING_PL
	,WRITING_SCORE
	,WRITING_PL
	,OVERALL_SCORE
	,OVERALL_PL	
FROM 
	(
	SELECT 
		--ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY OVERALL_SCORE DESC) AS RN  --- ELA 11, 10, 09
		--ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY READING_SCORE DESC) AS RN --- ELA 11 READING
		ROW_NUMBER () OVER (PARTITION BY SIS_NUMBER ORDER BY WRITING_SCORE DESC) AS RN  --- ELA 11 WRITING
		,SIS_NUMBER
		,TEST_NAME
		,TEST_DATE
		,SCHOOL
		,GRADE
		,SCH_YR
		,READING_SCORE
		,CASE WHEN READING_SCORE > '41' THEN 'PASS' ELSE 'FAIL'
		END AS READING_PL
		,WRITING_SCORE
		,CASE WHEN WRITING_SCORE > '30' THEN 'PASS' ELSE 'FAIL'
		END AS WRITING_PL
		,OVERALL_SCORE
		,CASE WHEN OVERALL_PL = 'Did Not Yet Meet Expectations' THEN 'DNME'
				WHEN OVERALL_PL = 'Approached Expectations' THEN 'APEX'
				WHEN OVERALL_PL = 'Partially Met Expectations' THEN 'PART'
				WHEN OVERALL_PL = 'Met Expectations' THEN 'METX'
				WHEN OVERALL_PL = 'Exceeded Expectations' THEN 'EXEX'
		END AS OVERALL_PL
	FROM
			(
			SELECT
				SIS_NUMBER
				,'' AS 'TEST_NAME'
				,TEST_DATE AS 'TEST_DATE'
				,SCHOOL_CODE AS 'SCHOOL'
				,GRADE AS 'GRADE'
				,SIS_SCHOOL_YEAR AS SCH_YR
				,dbo.udf_GetNumeric (READING) READING_SCORE
				,[dbo].[RemoveNumericCharacters] (READING) READING_PL
				,dbo.udf_GetNumeric (WRITING) WRITING_SCORE
				,[dbo].[RemoveNumericCharacters] (WRITING) WRITING_PL
				,dbo.udf_GetNumeric (OVERALL) OVERALL_SCORE
				,[dbo].[RemoveNumericCharacters] (OVERALL) OVERALL_PL
			FROM
				(
				SELECT
					SIS_NUMBER
					,TEST_WINDOW
					,SCHOOL_CODE
					,GRADE
					,YEAR
					,TEST_DATE
					,RAW_SCORE
					,SIS_SCHOOL_YEAR
					,TEST_SUBGROUP
					,TEST_ADMIN_PERIOD
					,TEST_VENDOR
					,PERFORMANCE_LEVEL + ' '+  CAST(SCALED_SCORE AS VARCHAR ) PL_SCORE
				FROM
					(
					SELECT
						STUDENT_ID AS SIS_NUMBER
						,'' AS TEST_WINDOW
						,DTBL_SCHOOLS.SCHOOL_CODE
						,TEST_STUDENT_GRADE AS GRADE
						,YEAR_VALUE AS YEAR
						,TEST_SUBJECT AS CONTENT_AREA
						,CONVERT (CHAR(10), DTBL_CALENDAR_DATES.DATE_VALUE,126) AS TEST_DATE
						,CAST(TEST_SCORE_VALUE AS INT) AS SCALED_SCORE
						,CAST(TEST_RAW_SCORE AS INT) AS RAW_SCORE
						,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
						,SIS_SCHOOL_YEAR
						,TEST_CLASS
						,TEST_GROUP
						,TEST_SUBGROUP
						,TEST_ADMIN_PERIOD
						,TEST_VENDOR
					FROM K12INTEL_DW.FTBL_TEST_SCORES
					INNER JOIN K12INTEL_DW.DTBL_TESTS
					ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 

					INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
					ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 

					INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
					ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY

					INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
					ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY

					INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
					ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 

					WHERE 1 = 1
					AND TEST_VENDOR LIKE '%PARCC%'
					--AND TEST_GROUP = 'Algebra I'
					--AND TEST_GROUP = 'Algebra II'
					--AND TEST_GROUP = 'ELA'+
					--AND (TEST_NAME LIKE 'PARCC GRADE 06%'
					--OR TEST_NAME LIKE 'PARCC GRADE 07%'
					--OR TEST_NAME LIKE 'PARCC GRADE 08%')
					AND TEST_NAME LIKE 'PARCC GRADE 11%'
					AND TEST_NAME LIKE '%ENGLISH%'
					--AND TEST_NAME = 'PARCC Grade 09 – English Language Arts – Overall'
					--AND TEST_GROUP = 'PARCC Grade 10 – English Language Arts – Reading'
					--AND TEST_GROUP = 'PARCC Grade 09 – English Language Arts – Reading'
					--AND TEST_NAME IN ('PARCC Grade 03 – English Language Arts – Overall','PARCC Grade 04 – English Language Arts – Overall','PARCC Grade 05 – English Language Arts – Overall','PARCC Grade 06 – English Language Arts – Overall','PARCC Grade 07 – English Language Arts – Overall')
					--AND TEST_NAME LIKE 'PARCC Grade 03%'
					--AND TEST_GROUP = 'Geometry'
					--AND TEST_GROUP = 'Integrated Mathematics'
					--AND TEST_GROUP = 'Integrated Mathematics II'
					--AND TEST_GROUP = 'Mathematics'
					AND TEST_CLASS = 'COMPONENT'
					--AND DTBL_CALENDAR_DATES.DATE_VALUE = '2016-04-01'
					AND LOCAL_SCHOOL_YEAR = '2015-2016'

					) AS T1

			)T2
				PIVOT (MAX([PL_SCORE]) FOR TEST_SUBGROUP IN ([READING],[WRITING],[OVERALL])) AS UP1
				) AS T222
	)T3
WHERE
	1 = 1
	--AND SIS_NUMBER IN ('970105963','100076108')
	AND RN = 1
order by SIS_NUMBER, OVERALL_PL DESC
