SELECT DISTINCT
	[Student].[LAST_NAME]
	,[Student].[FIRST_NAME]
	--,[Student].[MIDDLE_NAME]
	--,[Student].[SIS_NUMBER]
	--,[Student].[ELL_STATUS]
	--,[Student].[SPED_STATUS]
	--,[Student].[CONTACT_LANGUAGE]
	--,[Student].[GENDER]
	--,[Student].[CLASS_OF]
	--,CONVERT(VARCHAR(10),[Student].[BIRTH_DATE],101) AS [BIRTH_DATE]
	,[Enrollments].[GRADE] AS [GRADE_LEVEL]
 --   ,[Enrollments].[SCHOOL_NAME]
 --   ,[Enrollments].[SCHOOL_CODE]
	,CASE WHEN [Student].[MAIL_ADDRESS] IS NULL THEN [Student].[HOME_ADDRESS] ELSE [Student].[MAIL_ADDRESS] END AS [ADDRESS]
    ,CASE WHEN [Student].[MAIL_ADDRESS] IS NULL THEN [Student].[HOME_ADDRESS_2] ELSE [Student].[MAIL_ADDRESS_2] END AS [ADDRESS_2]
    ,CASE WHEN [Student].[MAIL_CITY] IS NULL THEN [Student].[HOME_CITY] ELSE [Student].[MAIL_CITY] END AS [CITY]
    ,CASE WHEN [Student].[MAIL_STATE] IS NULL THEN [Student].[HOME_STATE] ELSE [Student].[MAIL_STATE] END AS [STATE]
    ,CASE WHEN [Student].[MAIL_ZIP] IS NULL THEN [Student].[HOME_ZIP] ELSE [Student].[MAIL_ZIP] END AS [ZIP]
	,[Student].[PRIMARY_PHONE]
	--,[Student].[Parents]
	,PER.EMAIL AS STUDENT_EMAIL
	
FROM
	APS.PrimaryEnrollmentDetailsAsOf(getdate()) AS [Enrollments]
	
	INNER JOIN
	APS.BasicStudentWithMoreInfo AS [Student] 
	ON
	[Enrollments].[STUDENT_GU] = [Student].[STUDENT_GU]
	
	LEFT JOIN
	rev.[UD_STU] AS [STUDENT_EXCEPTIONS]
	ON
	[Student].[STUDENT_GU] = [STUDENT_EXCEPTIONS].[STUDENT_GU]

	LEFT JOIN
	REV.REV_PERSON AS PER
	ON PER.PERSON_GU = STUDENT.STUDENT_GU
	
	
	
WHERE
	1 = 1
	--[Enrollments].[ORGANIZATION_GU] LIKE @School
	--AND [Enrollments].[GRADE] LIKE @Grade
	
--	--- EXCEPTIONS
	--AND ([STUDENT_EXCEPTIONS].[EXCLUDE_BUSINESS] IS NULL OR [STUDENT_EXCEPTIONS].[EXCLUDE_BUSINESS] != 'N')
	--AND ([STUDENT_EXCEPTIONS].[EXCLUDE_UNIVERSITY] IS NULL OR [STUDENT_EXCEPTIONS].[EXCLUDE_UNIVERSITY] != 'N')
	--AND ([STUDENT_EXCEPTIONS].[EXCLUDE_MILITARY] IS NULL OR [STUDENT_EXCEPTIONS].[EXCLUDE_MILITARY] != 'N')
	AND [Enrollments].[GRADE] IN ('05','06','07','08','09','10','11','12')
	
ORDER BY
	--[Enrollments].[SCHOOL_NAME]
	[Student].[LAST_NAME]