

--SELECT
--	SIS_NUMBER
--	,TEST_NAME
--	,SCHOOL_CODE
--	,GRADE
--	,TEST_DATE
--	,SCORE
--	,PERFORMANCE_LEVEL

--FROM
--(
SELECT 
    ROW_NUMBER () OVER (PARTITION BY STUDENT_ID, TEST_NAME ORDER BY DTBL_CALENDAR_DATES.DATE_VALUE DESC) AS RN
	,STUDENT_ID AS SIS_NUMBER
    ,DTBL_STUDENTS.STUDENT_GRADUATION_COHORT
    ,TEST_NAME
    ,TEST_ADMIN_PERIOD
    ,DTBL_SCHOOLS.SCHOOL_CODE AS SCHOOL_CODE
    ,TEST_STUDENT_GRADE AS GRADE
    ,YEAR_VALUE AS [YEAR]
    ,TEST_SUBJECT AS CONTENT_AREA
	,CONVERT (CHAR(10), DTBL_CALENDAR_DATES.DATE_VALUE,126) AS TEST_DATE
    ,CAST (TEST_SCORE_VALUE AS INT) AS SCORE
    ,TEST_PRIMARY_RESULT
	,CASE WHEN TEST_SCORE_VALUE >= '530' THEN 'PASS'  --- 530 FOR MATH  480 FOR ENGLISH
	      WHEN TEST_SCORE_VALUE < '530' THEN 'FAIL'
    END AS PERFORMANCE_LEVEL
	,SIS_SCHOOL_YEAR
    ,TEST_CLASS
    ,TEST_GROUP
    ,TEST_SUBGROUP
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 1 = 1
AND TEST_PRODUCT like '%sat%'
AND TEST_SUBGROUP IN ('MATHEMATICS')
--AND TEST_SUBGROUP IN ('ENGLISH')
AND TEST_GROUP = 'SECTION'
--AND TEST_NAME = 'MATH'
--AND TEST_NAME = 'SAT - Composite (CR + M)'
AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND STUDENT_ID = '980016541'

--) AS T2
--WHERE 1 = 1
--AND RN = 1
--ORDER BY SCORE
