USE [Assessments]
GO

SELECT
	AI_NAME AS SCHOOL
	,PERFORMANCE_LEVEL
	,COUNT (AI_CODE) MATH_COUNTS
FROM
(
SELECT [AI_CODE]
      ,[AI_NAME]
      ,[FILLER_1]
      ,[COHORT_YEAR]
      ,[DISTRICT_NAME]
      ,[NAME_LAST]
      ,[NAME_FIRST]
      ,[NAME_MI]
      ,[SEX]
      ,[FILLER_2]
      ,[BIRTH_DATE]
      ,[LATEST_ASSESSMENT_DATE]
      ,[LATEST_SAT_TOTAL]
      ,[LATEST_SAT_EBRW]
      ,[LATEST_SAT_MATH_SECTION]
	  ,CASE WHEN LATEST_SAT_EBRW >= '480' THEN 'PASS' ELSE 'FAIL'
	  END AS PERFORMANCE_LEVEL
  FROM [dbo].[CCR_SAT_2015_2016]
  WHERE LATEST_SAT_MATH_SECTION > '0'
) AS T1
GROUP BY
 AI_NAME, PERFORMANCE_LEVEL
  ORDER BY SCHOOL
GO


