--SELECT
--	SCHOOL_CODE
--	,GRADE
--	,PERFORMANCE_LEVEL
--	,COUNT ('SIS_NUMBER') AS NUMBER
--FROM
--(
SELECT 
	rn
	,SIS_NUMBER
	,TEST_NAME
	,TEST_ADMIN_PERIOD
	,SCHOOL_CODE
	,GRADE
	,[YEAR]
	,CONTENT_AREA
	,TEST_DATE
	,SCALED_SCORE
	,RAW_SCORE
	,PERFORMANCE_LEVEL
	,SIS_SCHOOL_YEAR
	,TEST_CLASS
	,TEST_GROUP
	,TEST_SUBGROUP
	,'' AS COLUMN_16

FROM
(
SELECT 
	ROW_NUMBER () OVER (PARTITION BY STUDENT_ID, DTBL_CALENDAR_DATES.DATE_VALUE, TEST_SUBGROUP ORDER BY STUDENT_ID) AS RN
    ,STUDENT_ID AS SIS_NUMBER
    ,TEST_NAME
    ,TEST_ADMIN_PERIOD
    ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE AS GRADE
    ,YEAR_VALUE AS YEAR
    --,TEST_PRODUCT 
    ,TEST_SUBJECT AS CONTENT_AREA
    ,CONVERT (CHAR(10), DTBL_CALENDAR_DATES.DATE_VALUE,126) AS TEST_DATE
    ,CAST(TEST_SCORE_VALUE AS INT) AS SCALED_SCORE
	,CAST(TEST_RAW_SCORE AS INT) AS RAW_SCORE
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
    --,TEST_NAME
	,SIS_SCHOOL_YEAR
    ,TEST_CLASS
    ,TEST_GROUP
    ,TEST_SUBGROUP
    --,TEST_ADMIN_PERIOD
	,FTBL_TEST_SCORES.TESTS_KEY
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 1 = 1
AND TEST_NAME LIKE 'SBA-NM%'
AND TEST_SUBJECT = 'SCIENCE'
AND TEST_CLASS = 'COMPONENT'
--AND DTBL_CALENDAR_DATES.DATE_VALUE = '2015-10-01'
--AND DTBL_CALENDAR_DATES.DATE_VALUE = '2016-04-01'
AND LOCAL_SCHOOL_YEAR = '2015-2016'
AND TEST_RAW_SCORE IS NOT NULL
AND TEST_SCORE_VALUE IS NOT NULL
) AS T1
WHERE 
1 = 1
--AND RN = 1
--WHERE SIS_NUMBER = '102921848'
AND (TEST_ADMIN_PERIOD = 'fall' or TEST_ADMIN_PERIOD = 'spring')
AND SIS_NUMBER = '980021315'
--and TEST_NAME = 'SBA-NM Science'
--and TEST_SUBGROUP = 'science'
----AND TEST_SUBGROUP = 'OVERALL'
--AND GRADE IN ('11','','','','','','','','','','','','','','','')

--) AS T2

--GROUP BY
--SCHOOL_CODE
--,GRADE
--,PERFORMANCE_LEVEL
--ORDER BY SCHOOL_CODE, GRADE
--ORDER BY SIS_NUMBER
