


EXECUTE AS LOGIN='QueryFileUser'
GO


BEGIN TRANSACTION

UPDATE rev.EPC_STU_SCH_YR
	SET YEAR_END_STATUS = 'P'
FROM
(

SELECT SIS_NUMBER AS SIS_NUMBER, YEAR_END_STATUS, ORG.ORGANIZATION_NAME AS SCHOOL, SSY.STUDENT_SCHOOL_YEAR_GU

 FROM 

rev.EPC_STU_SCH_YR AS SSY

INNER JOIN
rev.EPC_STU AS STU
ON
SSY.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
SSY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_YEAR AS YRS
ON
ORGYR.YEAR_GU = YRS.YEAR_GU

INNER JOIN 
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

WHERE
YRS.SCHOOL_YEAR = '2015'
AND YRS.EXTENSION = 'R'
AND SSY.YEAR_END_STATUS IS NULL
AND SSY.EXCLUDE_ADA_ADM IS NULL


) AS T2


WHERE

	T2.STUDENT_SCHOOL_YEAR_GU = rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU

ROLLBACK
      REVERT
GO
