
/*
Created By:  Debbie Ann Chavez
Date:  10/30/2014


*UPDATE STUDENTS MOST RECENT CAREER AND ABILITY RECORD FROM SCHOOLMAX TO SYNERGY, EPC_STU TABLE, DIPLOMA_ATTEMPT_TYPE_1 FIELD.

*/


BEGIN TRANSACTION

UPDATE rev.EPC_STU 
	SET DIPLOMA_ATTEMPT_TYPE_1 = DIPTYPE, CHANGE_DATE_TIME_STAMP = GETDATE(), CHANGE_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F'

FROM
(
SELECT 
	SIS_NUMBER
	,STUDENT_GU
	,CASE WHEN SMAX_GRADUATION = 'A' THEN '03' ELSE '04' END AS DIPTYPE

 FROM (

SELECT 
	
	SPED.ID_NBR AS SMAX_ID_NBR
	,SPED.LST_NME AS SMAX_LAST
	,SPED.FRST_NME AS SMAX_FIRST
	,SPED.GRAD AS SMAX_GRADUATION
	,SPED.EVAL_DATE

	,CASE WHEN ORGANIZATION_NAME IS NOT NULL THEN 'X' ELSE '' END AS ACTIVE_SYNERGY

	,ORGANIZATION_NAME
	,SIS_NUMBER
	,PERS.LAST_NAME
	,PERS.FIRST_NAME
	,Student.DIPLOMA_TYPE AS SYNERGY_DIPLOMA_TYPE
	,Student.STUDENT_GU

	,ROW_NUMBER() OVER (PARTITION BY  SIS_NUMBER ORDER BY EVAL_DATE DESC) AS RN

 FROM 

 (
SELECT DISTINCT
	SPED.ID_NBR
	,LST_NME
	,FRST_NME
	,SPED.GRAD
	,SPED.EVAL_DATE
 FROM
[SMAXDBPROD.APS.EDU.ACTD].[PR].DBTSIS.SP010 AS SPED

INNER JOIN
[SMAXDBPROD.APS.EDU.ACTD].[PR].DBTSIS.CE020 AS NAME
ON
NAME.ID_NBR = SPED.ID_NBR

WHERE
	GRAD != ' '
) AS SPED

LEFT JOIN 
rev.EPC_STU AS Student
ON
SPED.ID_NBR = Student.SIS_NUMBER

LEFT JOIN
APS.PrimaryEnrollmentsAsOf(GETDATE()) AS ENR
ON
ENR.STUDENT_GU = Student.STUDENT_GU
LEFT JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = ENR.ORGANIZATION_YEAR_GU
LEFT JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
LEFT JOIN
rev.REV_PERSON AS PERS
ON
PERS.PERSON_GU = Student.STUDENT_GU

) 
AS T1
WHERE
	ACTIVE_SYNERGY = 'X'
	AND RN = 1
	AND SMAX_GRADUATION IN ('A', 'C')

) AS T1

WHERE
T1.STUDENT_GU = rev.EPC_STU.STUDENT_GU

ROLLBACK

--ORDER BY SPED.ID_NBR, SPED.EVAL_DATE