
EXECUTE AS LOGIN='QueryFileUser'
GO


BEGIN TRANSACTION

UPDATE rev.EPC_STU_SCH_YR
	SET YEAR_END_STATUS = 'G'
FROM
(

SELECT 
	*

FROM
       OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                  'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
                  'SELECT * from 2015Seniors.csv'
                ) AS [Seniors]
				
LEFT JOIN
(
SELECT SIS_NUMBER AS SIS_NUMBER2, YEAR_END_STATUS, ORG.ORGANIZATION_NAME AS SCHOOL, PRIM.STUDENT_SCHOOL_YEAR_GU

 FROM 
 APS.PrimaryEnrollmentsAsOf(GETDATE()) AS PRIM
 INNER JOIN 
rev.EPC_STU_SCH_YR AS SSY
ON
PRIM.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU

INNER JOIN
rev.EPC_STU AS STU
ON
SSY.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
SSY.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_YEAR AS YRS
ON
ORGYR.YEAR_GU = YRS.YEAR_GU

INNER JOIN 
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

WHERE
YRS.SCHOOL_YEAR = '2015'



)
AS PRIMENROLL

ON
[Seniors].[﻿SIS_NUMBER] = PRIMENROLL.SIS_NUMBER2



) AS T2


WHERE

	T2.STUDENT_SCHOOL_YEAR_GU = rev.EPC_STU_SCH_YR.STUDENT_SCHOOL_YEAR_GU

COMMIT

      REVERT
GO
