
/*
	Created by Debbie Ann Chavez
	Date 1/22/2015

	Pull Grade Differences from Student Grades in Synergy (Not Gradebook)

	RUN ON EXPERIMENT!!!!!!!!!!!!!!!!!!!!!!! : )  It reads across to ST_Production from SYNSECONDDB

*/


DECLARE @GRADETEMP TABLE(
	MARK VARCHAR(5)
	,VALUE INT
)

INSERT INTO
	@GRADETEMP 
VALUES
('A+',100)
,('A',99)
,('A-',98)
,('B+',97)
,('B',96)
,('B-',95)
,('C+',94)
,('C',93)
,('C-',92)
,('D+',91)
,('D',90)
,('D-',89)
,('E',88)
,('P',87)

,('F',86)
,('WF',86)

,('N/A',85)
,('N',85)
,('I',85)
,('W',85)



SELECT 
	PRODUCTION.ORGANIZATION_NAME
	,PRODUCTION.SIS_NUMBER
	,PERS.LAST_NAME AS STU_LAST_NAME
	,PERS.FIRST_NAME AS STU_FIRST_NAME
	,Grades.VALUE_DESCRIPTION AS GRADE
	,PRODUCTION.COURSE_ID
	,PRODUCTION.SECTION_ID
	,PRODUCTION.COURSE_TITLE

	,STAFF.LAST_NAME AS TEACHER_LAST_NAME
	,STAFF.FIRST_NAME AS TEACHER_FIRST_NAME
	,STAFF.EMAIL

	,PRODUCTION.GRADE_PERIOD
	
	,EXPERIMENT.MARK AS GRADE_AS_OF_JAN9TH
	,VALUE.VALUE AS [9THVALUE]

	,PRODUCTION.MARK AS GRADE_AS_OF_TODAY
	,VALUE2.VALUE AS [TODAYVALUE]

	,CASE WHEN VALUE2.VALUE >  VALUE.VALUE  THEN 'X' ELSE '' END AS GRADE_WENT_DOWN
    ,CASE WHEN VALUE2.VALUE <  VALUE.VALUE  THEN 'X' ELSE '' END AS GRADE_WENT_UP
   
    ,CASE WHEN 
	EXPERIMENT.GRADE_PERIOD IN ('1st 6 Wk', '2nd 6 Wk',  '1st 6 Wks','Q1', 'Q2') 
	AND EXPERIMENT.MARK IN ('D+', 'D', 'D-') 
	AND PRODUCTION.MARK = 'F' THEN 'X' ELSE '' END AS D_TO_F_IN_FIRST2PERIODS

		
 FROM
APS.StudentGrades AS EXPERIMENT
INNER HASH JOIN
[SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].APS.StudentGrades AS PRODUCTION
ON 
EXPERIMENT.ORGANIZATION_NAME = PRODUCTION.ORGANIZATION_NAME
AND 
EXPERIMENT.SIS_NUMBER = PRODUCTION.SIS_NUMBER
AND 
EXPERIMENT.GRADE_PERIOD = PRODUCTION.GRADE_PERIOD
AND 
EXPERIMENT.COURSE_ID = PRODUCTION.COURSE_ID
AND 
EXPERIMENT.SECTION_ID = PRODUCTION.SECTION_ID

INNER HASH JOIN
rev.REV_PERSON AS PERS
ON
PERS.PERSON_GU = PRODUCTION.STUDENT_GU

INNER HASH JOIN
rev.EPC_STU_SCH_YR AS SSY
ON
PRODUCTION.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU

INNER HASH JOIN
APS.LookupTable('K12','Grade') AS [Grades]
ON
[SSY].[GRADE] = [Grades].[VALUE_CODE]

INNER HASH JOIN
rev.EPC_SCH_YR_SECT AS SECTION
ON
PRODUCTION.SECTION_GU = SECTION.SECTION_GU

INNER HASH JOIN
  rev.EPC_STAFF_SCH_YR AS STFYR
  ON
 SECTION.STAFF_SCHOOL_YEAR_GU = STFYR.STAFF_SCHOOL_YEAR_GU

INNER HASH JOIN
  rev.REV_PERSON AS STAFF
  ON
  STFYR.STAFF_GU = STAFF.PERSON_GU
    
INNER JOIN
  @GRADETEMP AS VALUE2
  ON
  VALUE2.MARK = EXPERIMENT.MARK
  
  INNER JOIN
  @GRADETEMP AS VALUE
  ON
  VALUE.MARK = PRODUCTION.MARK



  

WHERE
EXPERIMENT.MARK != PRODUCTION.MARK


ORDER BY
ORGANIZATION_NAME, SIS_NUMBER, GRADE_PERIOD, PRODUCTION.MARK