USE ST_Experiment


-- HAD TO CREATE 2 TABLES IN EXPERIMENT AND RUN EACH JOIN SEPERATELY -- 
--WOULD NOT RUN ALTOGETHER HERE
-- SEE INDIVIDUAL QUERIES


DECLARE @GRADETEMP TABLE(
	MARK VARCHAR(5)
	,VALUE INT
)

INSERT INTO
	@GRADETEMP 
VALUES
('A+',100)
,('A',99)
,('A-',98)
,('B+',97)
,('B',96)
,('B-',95)
,('C+',94)
,('C',93)
,('C-',92)
,('D+',91)
,('D',90)
,('D-',89)
,('E',88)
,('P',87)

,('F',86)
,('WF',86)

,('N/A',85)
,('N',85)
,('I',85)
,('W',85)


SELECT * FROM

(
SELECT 
PRODUCTION.SCHOOLYEAR
,CURRENTLY_ENROLLED
,PRODUCTION.ORGANIZATION_NAME
,PRODUCTION.SIS_NUMBER
,PRODUCTION.STUDENT_LAST_NAME
,PRODUCTION.STUDENT_FIRST_NAME
,PRODUCTION.GRADE

,PRODUCTION.COURSE_ID
,PRODUCTION.SECTION_ID
, PRODUCTION.COURSE_TITLE
,PRODUCTION.TEACHER_AIDE

,PRODUCTION.TEACHER_LAST_NAME
,PRODUCTION.TEACHER_FIRST_NAME
,PRODUCTION.EMAIL

,PRODUCTION.PERIOD

,EXPERIMENT.GRADE_AS_OF_JAN9TH
,EXPERIMENT.VALUE AS [9VALUE]
,PRODUCTION.GRADE_AS_OF_JAN16TH
,PRODUCTION.VALUE AS [16VALUE]

,CASE WHEN EXPERIMENT.VALUE >  PRODUCTION.VALUE  THEN 'X' ELSE '' END AS GRADE_WENT_DOWN
,CASE WHEN EXPERIMENT.VALUE <  PRODUCTION.VALUE  THEN 'X' ELSE '' END AS GRADE_WENT_UP
,CASE WHEN 
	EXPERIMENT.PERIOD IN ('1st 6 Wk', '2nd 6 Wk',  '1st 6 Wks','Q1', 'Q2') 
	AND EXPERIMENT.GRADE_AS_OF_JAN9TH IN ('D+', 'D', 'D-') 
	AND PRODUCTION.GRADE_AS_OF_JAN16TH = 'F' THEN 'X' ELSE '' END AS D_TO_F_IN_FIRST2PERIODS


FROM
(
SELECT * FROM 
(
SELECT

ORGANIZATION_NAME
,STUDENT.SIS_NUMBER
,PERSON.LAST_NAME AS STUDENT_LAST_NAME
,PERSON.FIRST_NAME AS STUDENT_FIRST_NAME
,[GradeLevel].[VALUE_DESCRIPTION] AS GRADE

,COURSE_ID
,SECTION_ID
, COURSE_TITLE
,CASE WHEN TEACHER_AIDE = 'Y' AND MANUALSCORE = 'N/A' THEN 'DONTWANT' ELSE TEACHER_AIDE END AS TEACHER_AIDE

,STAFF.LAST_NAME AS TEACHER_LAST_NAME
,STAFF.FIRST_NAME AS TEACHER_FIRST_NAME
,STAFF.EMAIL

,[PERIOD]
--,[CALCULATEDSCORE]
,[MANUALSCORE] AS GRADE_AS_OF_JAN9TH
,MARKS.VALUE 

,[SCHOOLYEAR]
,CRS.COURSE_GU
,GRADES.SECTION_GU
,GRADES.PERSON_GU

  FROM [rev].[EGB_VIEWSTUDENTSECTIONMARK] AS GRADES
  INNER JOIN
  rev.REV_PERSON AS PERSON
  ON
  GRADES.PERSON_GU = PERSON.PERSON_GU
  INNER JOIN
  rev.EPC_STU AS STUDENT
  ON
  PERSON.PERSON_GU = STUDENT.STUDENT_GU
  INNER JOIN
  rev.EPC_SCH_YR_SECT AS SECTION
  ON
  GRADES.SECTION_GU = SECTION.SECTION_GU
  INNER JOIN
  rev.EPC_SCH_YR_CRS AS CRSYR
  ON
  SECTION.SCHOOL_YEAR_COURSE_GU = CRSYR.SCHOOL_YEAR_COURSE_GU
  INNER JOIN
  rev.EPC_CRS AS CRS
  ON
  CRSYR.COURSE_GU = CRS.COURSE_GU

  INNER JOIN
  rev.REV_ORGANIZATION_YEAR AS ORGYR
  ON
  ORGYR.ORGANIZATION_YEAR_GU = CRSYR.ORGANIZATION_YEAR_GU
  INNER JOIN
  rev.REV_ORGANIZATION AS ORG
  ON
  ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
  
  INNER JOIN
  @GRADETEMP AS MARKS
  ON
  MARKS.MARK = GRADES.MANUALSCORE
  
  INNER JOIN
  rev.EPC_STU_SCH_YR AS SSY
  ON
  CRSYR.ORGANIZATION_YEAR_GU = SSY.ORGANIZATION_YEAR_GU
  AND SSY.STUDENT_GU = STUDENT.STUDENT_GU

  INNER JOIN
  rev.EPC_STAFF_SCH_YR AS STFYR
  ON
 SECTION.STAFF_SCHOOL_YEAR_GU = STFYR.STAFF_SCHOOL_YEAR_GU

  INNER JOIN
  rev.REV_PERSON AS STAFF
  ON
  STFYR.STAFF_GU = STAFF.PERSON_GU

 INNER JOIN
APS.LookupTable('K12','Grade') AS [GradeLevel]
ON
[SSY].[GRADE] = [GradeLevel].[VALUE_CODE]
    
  WHERE
 --PERSON.PERSON_GU = 'A33C78F4-2C03-4434-8113-6280F7802499'
 --AND 
  SCHOOLYEAR = '2014-2015'
  AND PERIOD IN ('1st 6 Wk', '2nd 6 Wk', '3rd 6 Wk', 'S1 Exam', 'S1 Grade', 
  
  '1st 6 Wks', 'EXPL Q1 Exam', 'EXPL Q2 or S1 Exam', 'P1', 'P2', 'Q1', 'Q1 Exam', 'Q2', 'Q2 Exam', 'Sem Exam'
  )
  ) AS T1

   WHERE 
 TEACHER_AIDE ! = 'DONTWANT'
 
  ) AS EXPERIMENT

INNER HASH JOIN
(SELECT * FROM
  (
SELECT

CASE WHEN [PRIMARY].STUDENT_GU IS NULL THEN 'Not Active' ELSE 'Active' END AS CURRENTLY_ENROLLED
,ORGANIZATION_NAME
,STUDENT.SIS_NUMBER
,PERSON.LAST_NAME AS STUDENT_LAST_NAME
,PERSON.FIRST_NAME AS STUDENT_FIRST_NAME
,[GradeLevel].[VALUE_DESCRIPTION] AS GRADE

,COURSE_ID
,SECTION_ID
,COURSE_TITLE
,CASE WHEN TEACHER_AIDE = 'Y' AND MANUALSCORE = 'N/A' THEN 'DONTWANT' ELSE TEACHER_AIDE END AS TEACHER_AIDE

,STAFF.LAST_NAME AS TEACHER_LAST_NAME
,STAFF.FIRST_NAME AS TEACHER_FIRST_NAME
,STAFF.EMAIL

,[PERIOD]

,[MANUALSCORE] AS GRADE_AS_OF_JAN16TH
,MARKS.VALUE 

,[SCHOOLYEAR]
,CRS.COURSE_GU
,GRADES.SECTION_GU
,GRADES.PERSON_GU

  FROM [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].[rev].[EGB_VIEWSTUDENTSECTIONMARK] AS GRADES
  INNER JOIN
   [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.REV_PERSON AS PERSON
  ON
  GRADES.PERSON_GU = PERSON.PERSON_GU
  INNER JOIN
   [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.EPC_STU AS STUDENT
  ON
  PERSON.PERSON_GU = STUDENT.STUDENT_GU
  INNER JOIN
   [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.EPC_SCH_YR_SECT AS SECTION
  ON
  GRADES.SECTION_GU = SECTION.SECTION_GU

  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production]. rev.EPC_SCH_YR_CRS AS CRSYR
  ON
  SECTION.SCHOOL_YEAR_COURSE_GU = CRSYR.SCHOOL_YEAR_COURSE_GU
  INNER JOIN
   [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.EPC_CRS AS CRS
  ON
  CRSYR.COURSE_GU = CRS.COURSE_GU

  INNER JOIN
   [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.REV_ORGANIZATION_YEAR AS ORGYR
  ON
  ORGYR.ORGANIZATION_YEAR_GU = CRSYR.ORGANIZATION_YEAR_GU
  INNER JOIN
   [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.REV_ORGANIZATION AS ORG
  ON
  ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
  
  INNER JOIN
  @GRADETEMP AS MARKS
  ON
  MARKS.MARK = GRADES.MANUALSCORE
  
  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production]. rev.EPC_STU_SCH_YR AS SSY
  ON
  CRSYR.ORGANIZATION_YEAR_GU = SSY.ORGANIZATION_YEAR_GU
  AND SSY.STUDENT_GU = STUDENT.STUDENT_GU

  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production]. rev.EPC_STAFF_SCH_YR AS STFYR
  ON
 SECTION.STAFF_SCHOOL_YEAR_GU = STFYR.STAFF_SCHOOL_YEAR_GU

  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production]. rev.REV_PERSON AS STAFF
  ON
  STFYR.STAFF_GU = STAFF.PERSON_GU

 INNER JOIN
 APS.LookupTable('K12','Grade') AS [GradeLevel]
ON
[SSY].[GRADE] = [GradeLevel].[VALUE_CODE]

LEFT JOIN
APS.PrimaryEnrollmentsAsOf (GETDATE()) AS [PRIMARY]
ON
SSY.STUDENT_GU = [PRIMARY].STUDENT_GU

    
  WHERE
 
  SCHOOLYEAR = '2014-2015'
  AND PERIOD IN ('1st 6 Wk', '2nd 6 Wk', '3rd 6 Wk', 'S1 Exam', 'S1 Grade', 

    '1st 6 Wks', 'EXPL Q1 Exam', 'EXPL Q2 or S1 Exam', 'P1', 'P2', 'Q1', 'Q1 Exam', 'Q2', 'Q2 Exam', 'Sem Exam'
  )

    ) AS T1

   WHERE 
 TEACHER_AIDE ! = 'DONTWANT'
 
  ) AS PRODUCTION

  ON
  EXPERIMENT.PERSON_GU = PRODUCTION.PERSON_GU
  AND EXPERIMENT.SECTION_GU = PRODUCTION.SECTION_GU
  AND EXPERIMENT.PERIOD = PRODUCTION.PERIOD
  AND EXPERIMENT.GRADE_AS_OF_JAN9TH != PRODUCTION.GRADE_AS_OF_JAN16TH
  
  ) AS T3
  
   
ORDER BY 
ORGANIZATION_NAME
,TEACHER_LAST_NAME
,TEACHER_FIRST_NAME
,STUDENT_LAST_NAME
,STUDENT_FIRST_NAME
,PERIOD
