
DECLARE @GRADETEMP TABLE(
	MARK VARCHAR(5)
	,VALUE INT
)

INSERT INTO
	@GRADETEMP 
VALUES
('A+',100)
,('A',99)
,('A-',98)
,('B+',97)
,('B',96)
,('B-',95)
,('C+',94)
,('C',93)
,('C-',92)
,('D+',91)
,('D',90)
,('D-',89)
,('E',88)
,('P',87)

,('F',86)
,('WF',86)

,('N/A',85)
,('N',85)
,('I',85)
,('W',85)


SELECT DISTINCT SIS_NUMBER FROM

(
SELECT 
PRODUCTION.SCHOOLYEAR
,PRODUCTION.ORGANIZATION_NAME
,PRODUCTION.SIS_NUMBER
,PRODUCTION.LAST_NAME
,PRODUCTION.FIRST_NAME
,PRODUCTION.COURSE_ID
,PRODUCTION.SECTION_ID
, PRODUCTION.COURSE_TITLE
,PRODUCTION.PERIOD
,EXPERIMENT.[CALCULATEDSCORE] AS FRIDAY_CALCULATEDSCORE
,EXPERIMENT.[MANUALSCORE] AS FRIDAY_MANUALSCORE
,PRODUCTION.CALCULATEDSCORE AS LIVE_CALCULATEDSCORE
,PRODUCTION.MANUALSCORE AS LIVE_MANUALSCORE
,CASE WHEN EXPERIMENT.PERIOD = 'S1 Grade' AND EXPERIMENT.MANUALSCORE < 'F' AND PRODUCTION.MANUALSCORE >'E' THEN 'X' ELSE '' END AS CHG_SEM_TO_FAIL
,CASE WHEN EXPERIMENT.PERIOD = 'S1 Grade' AND EXPERIMENT.MANUALSCORE > 'E' AND PRODUCTION.MANUALSCORE <'F' THEN 'X' ELSE '' END AS CHG_SEM_TO_PASS

FROM

(
SELECT

ORGANIZATION_NAME
,STUDENT.SIS_NUMBER
,PERSON.LAST_NAME
,PERSON.FIRST_NAME
,SSY.GRADE
,COURSE_ID
,SECTION_ID
, COURSE_TITLE
,[PERIOD]
,[CALCULATEDSCORE]
,[MANUALSCORE]
,MARKS.VALUE AS FRIDAY_MARKVALUE
,[SCHOOLYEAR]
,GRADES.SECTION_GU
,GRADES.PERSON_GU

  FROM [rev].[EGB_VIEWSTUDENTSECTIONMARK] AS GRADES
  INNER JOIN
  rev.REV_PERSON AS PERSON
  ON
  GRADES.PERSON_GU = PERSON.PERSON_GU
  INNER JOIN
  rev.EPC_STU AS STUDENT
  ON
  PERSON.PERSON_GU = STUDENT.STUDENT_GU
  INNER JOIN
  rev.EPC_SCH_YR_SECT AS SECTION
  ON
  GRADES.SECTION_GU = SECTION.SECTION_GU
  INNER JOIN
  rev.EPC_SCH_YR_CRS AS CRSYR
  ON
  SECTION.SCHOOL_YEAR_COURSE_GU = CRSYR.SCHOOL_YEAR_COURSE_GU
  INNER JOIN
  rev.EPC_CRS AS CRS
  ON
  CRSYR.COURSE_GU = CRS.COURSE_GU

  INNER JOIN
  rev.REV_ORGANIZATION_YEAR AS ORGYR
  ON
  ORGYR.ORGANIZATION_YEAR_GU = CRSYR.ORGANIZATION_YEAR_GU
  INNER JOIN
  rev.REV_ORGANIZATION AS ORG
  ON
  ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU

  INNER JOIN
  @GRADETEMP AS MARKS
  ON
  MARKS.MARK = GRADES.MANUALSCORE

  INNER JOIN
  rev.EPC_STU_SCH_YR AS SSY
  ON
  CRSYR.ORGANIZATION_YEAR_GU = SSY.ORGANIZATION_YEAR_GU
  AND SSY.STUDENT_GU = STUDENT.STUDENT_GU

    
  WHERE
 --PERSON.PERSON_GU = 'A33C78F4-2C03-4434-8113-6280F7802499'
 --AND 
  SCHOOLYEAR = '2014-2015'
  AND PERIOD IN ('1st 6 Wk', '2nd 6 Wk', '3rd 6 Wk', 'S1 Exam', 'S1 Grade', 
  
  '1st 6 Wks', 'EXPL Q1 Exam', 'EXPL Q2 or S1 Exam', 'P1', 'P2', 'Q1', 'Q1 Exam', 'Q2', 'Q2 Exam', 'Sem Exam'
  )

  ) AS EXPERIMENT

INNER HASH JOIN

  (
SELECT

ORGANIZATION_NAME
,STUDENT.SIS_NUMBER
,PERSON.LAST_NAME
,PERSON.FIRST_NAME
,COURSE_ID
,SECTION_ID
,COURSE_TITLE
      ,[PERIOD]
      ,[CALCULATEDSCORE]
      ,[MANUALSCORE]
      ,[SCHOOLYEAR]

	  	 ,GRADES.SECTION_GU
	  ,GRADES.PERSON_GU

  FROM [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].[rev].[EGB_VIEWSTUDENTSECTIONMARK] AS GRADES
  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.REV_PERSON AS PERSON
  ON
  GRADES.PERSON_GU = PERSON.PERSON_GU
  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.EPC_STU AS STUDENT
  ON
  PERSON.PERSON_GU = STUDENT.STUDENT_GU
  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.EPC_SCH_YR_SECT AS SECTION
  ON
  GRADES.SECTION_GU = SECTION.SECTION_GU
  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.EPC_SCH_YR_CRS AS CRSYR
  ON
  SECTION.SCHOOL_YEAR_COURSE_GU = CRSYR.SCHOOL_YEAR_COURSE_GU
  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.EPC_CRS AS CRS
  ON
  CRSYR.COURSE_GU = CRS.COURSE_GU

  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.REV_ORGANIZATION_YEAR AS ORGYR
  ON
  ORGYR.ORGANIZATION_YEAR_GU = CRSYR.ORGANIZATION_YEAR_GU
  INNER JOIN
  [SYNERGYDBDC.APS.EDU.ACTD].[ST_Production].rev.REV_ORGANIZATION AS ORG
  ON
  ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
    
  WHERE
 --PERSON.PERSON_GU = 'A33C78F4-2C03-4434-8113-6280F7802499'
 --AND 
  SCHOOLYEAR = '2014-2015'
  AND PERIOD IN ('1st 6 Wk', '2nd 6 Wk', '3rd 6 Wk', 'S1 Exam', 'S1 Grade', 
  
  '1st 6 Wks', 'EXPL Q1 Exam', 'EXPL Q2 or S1 Exam', 'P1', 'P2', 'Q1', 'Q1 Exam', 'Q2', 'Q2 Exam', 'Sem Exam'
  )

  ) AS PRODUCTION

  ON
  EXPERIMENT.PERSON_GU = PRODUCTION.PERSON_GU
  AND EXPERIMENT.SECTION_GU = PRODUCTION.SECTION_GU
  AND EXPERIMENT.PERIOD = PRODUCTION.PERIOD
  AND EXPERIMENT.MANUALSCORE != PRODUCTION.MANUALSCORE
   

  ) AS T1
  

WHERE
PERIOD = '1st 6 Wk' AND FRIDAY_MANUALSCORE != LIVE_MANUALSCORE
 
 /*
  ORDER BY 
  ORGANIZATION_NAME
  ,SIS_NUMBER
  ,COURSE_ID
  ,SECTION_ID
  ,LIVE_MANUALSCORE DESC  
	*/