
SELECT * FROM
(
SELECT 
	T1.LAST_NAME
	,T1.FIRST_NAME
	,T1.SIS_NUMBER
	,T1.ORGANIZATION_NAME
	, T1.GRADE
	,GETALLGRADES.MARK
	,GETALLGRADES.DEPARTMENT

FROM 
(
SELECT DISTINCT
	PERS.LAST_NAME
	,PERS.FIRST_NAME
	,STU.SIS_NUMBER
	,ORG.ORGANIZATION_NAME
	,VALUE_DESCRIPTION AS GRADE

 FROM
APS.StudentGrades AS GRADES
INNER JOIN
APS.PrimaryEnrollmentsAsOf (GETDATE()) AS PE
ON
GRADES.STUDENT_GU = PE.STUDENT_GU
INNER JOIN
rev.EPC_STU AS STU
ON
PE.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
rev.REV_PERSON AS PERS
ON
STU.STUDENT_GU = PERS.PERSON_GU
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = PE.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN
APS.LookupTable('K12', 'Grade') AS GRADE
ON
PE.GRADE = GRADE.VALUE_CODE

WHERE
GRADE_PERIOD = 'S1 Grade'
AND MARK IN ('F', 'WF')

) AS T1

INNER JOIN
APS.StudentGrades AS GETALLGRADES
ON
T1.SIS_NUMBER = GETALLGRADES.SIS_NUMBER

WHERE
GRADE_PERIOD = 'S1 Grade'
) AS T2

PIVOT
(
MAX(MARK)
FOR DEPARTMENT IN ([Math],[Eng],[Sci],[Soc],[PE],[Hea],[Ele],[P/FA],[Advis],[Sped], [NOC], [Off])
) AS PIVOTME

ORDER BY ORGANIZATION_NAME, GRADE, LAST_NAME
