



SELECT  D1.[State ID] AS DROPOUT_FILE_STATEID,ID_NBR, STATE_ID
, CASE WHEN ENR._Id IS NULL THEN 'NO ENROLLMENT FOUND' ELSE 'Y' END AS PRIMARY_ENROLLMENT_FOUND
,ENR.*

 FROM
 (
 SELECT * FROM 
	OPENROWSET ('MSDASQL', 'Driver={Microsoft Access Text Driver (*.txt, *.csv)};DBQ=E:\SQLWorkingFiles;', 'SELECT * from "Dropout2013.csv"')
) AS D1

LEFT JOIN 
(SELECT DISTINCT ENR.ID_NBR, CEN.STATE_ID, MRE.SCH_NBR, MRE.BEG_ENR_DT, MRE.END_ENR_DT, ENR.END_STAT, ENR._Id
 FROM 
APS.MostRecentPrimaryEnrollBySchYr(2013) AS MRE
INNER JOIN 
DBTSIS.ST010 AS ENR
ON
MRE._Id= ENR._Id
INNER JOIN 
DBTSIS.CE020_V AS CEN
ON
ENR.ID_NBR = CEN.ID_NBR
WHERE
MRE.DST_NBR = 1
) AS ENR
ON
ENR.ID_NBR = D1.[State ID]



ORDER BY ENR._Id


SELECT  D1.[State_ID] AS DROPOUT_FILE_STATEID,ID_NBR, STATE_ID
, CASE WHEN ENR._Id IS NULL THEN 'NO ENROLLMENT FOUND' ELSE 'Y' END AS PRIMARY_ENROLLMENT_FOUND
,ENR.*

 FROM
 (
 SELECT * FROM 
	OPENROWSET ('MSDASQL', 'Driver={Microsoft Access Text Driver (*.txt, *.csv)};DBQ=E:\SQLWorkingFiles;', 'SELECT * from "Dropout2014.csv"')
) AS D1

LEFT JOIN 
(SELECT DISTINCT ENR.ID_NBR, CEN.STATE_ID, MRE.SCH_NBR, MRE.BEG_ENR_DT, MRE.END_ENR_DT, ENR.END_STAT, ENR._Id
 FROM 
APS.MostRecentPrimaryEnrollBySchYr(2014) AS MRE
INNER JOIN 
DBTSIS.ST010 AS ENR
ON
MRE._Id= ENR._Id
INNER JOIN 
DBTSIS.CE020_V AS CEN
ON
ENR.ID_NBR = CEN.ID_NBR
WHERE
MRE.DST_NBR = 1
) AS ENR
ON
ENR.ID_NBR = D1.[State_ID]



ORDER BY ENR._Id

