

EXECUTE AS LOGIN='QueryFileUser'
GO


SELECT 
	T1.*
	,stu.EXPECTED_GRADUATION_YEAR, GRADUATION_DATE, LU.VALUE_DESCRIPTION AS GRAD_STATUS, LU2.VALUE_DESCRIPTION AS DIPLOMA_TYPE, LU3.VALUE_DESCRIPTION AS POST_SECONDARY
	, ENROLL.SCHOOL_CODE,ENROLL.SCHOOL_NAME, ENROLL.SCHOOL_YEAR, ENROLL.EXTENSION, ENROLL.EXCLUDE_ADA_ADM, ENROLL.GRADE, ENROLL.ENTER_DATE, ENROLL.ENTER_DESCRIPTION, ENROLL.LEAVE_DATE, ENROLL.LEAVE_DESCRIPTION, ENROLL.SUMMER_WITHDRAWL_CODE, ENROLL.SUMMER_WITHDRAWL_DATE


	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from META1516.csv'
                ) AS [T1]

INNER JOIN 
REV.EPC_STU AS STU
ON
STU.SIS_NUMBER = T1.SIS_NUMBER

LEFT JOIN 
APS.STUDENTENROLLMENTDETAILS AS ENROLL
ON
STU.STUDENT_GU = ENROLL.STUDENT_GU

LEFT JOIN 
APS.LookupTable('K12', 'GRADUATION_STATUS') AS LU
ON
LU.VALUE_CODE = STU.GRADUATION_STATUS

LEFT JOIN 
APS.LookupTable('K12', 'DIPLOMA_TYPE') AS LU2
ON
LU2.VALUE_CODE = STU.DIPLOMA_TYPE

LEFT JOIN 
APS.LookupTable('K12.DEMOGRAPHICS', 'POST_SECONDARY') AS LU3
ON
LU3.VALUE_CODE = STU.POST_SECONDARY


WHERE
ENROLL.SCHOOL_YEAR > = '2012'
AND STU.EXPECTED_GRADUATION_YEAR = 2016

ORDER BY STU.SIS_NUMBER, ENROLL.SCHOOL_YEAR, ENROLL.EXTENSION, ENROLL.ENTER_DATE





	
REVERT
GO