DECLARE @TEMP TABLE
(
DistrictNumber VARCHAR (3), 
SchoolYear VARCHAR (8),
StudentIDNumber VARCHAR (9),
SORSchoolNumber VARCHAR(3),
SchoolName VARCHAR (100),
Grade VARCHAR (2),
EnterDate VARCHAR (8),
AddDelStatus VARCHAR (1),
LastName VARCHAR (100),
FirstName VARCHAR (100),
StudentMiddleName VARCHAR (100),
SchooLOfRecord VARCHAR (1)
)

INSERT INTO 
	@TEMP
EXEC APS.ActiveDirectoryStudents

----------------------------------------------------------------------------------------------
--UPDATE IF THEY EXIST
--this will only be run once, if they exist, update their userid

/*
UPDATE rev.REV_USER_NON_SYS
SET USER_ID = SIS_NUMBER

--SELECT *

FROM 
(
SELECT DISTINCT 
	STUDENT_GU,
	SIS_NUMBER
FROM 
 @TEMP AS TEMP
 INNER JOIN
 rev.EPC_STU AS STU
 ON
 TEMP.StudentIDNumber = STU.SIS_NUMBER
 INNER JOIN
 rev.REV_USER_NON_SYS AS SYSUSER
 ON
 STU.STUDENT_GU = SYSUSER.PERSON_GU
 ) AS FOUNDSTUDENTVUEKIDS

  WHERE
  rev.REV_USER_NON_SYS.PERSON_GU = FOUNDSTUDENTVUEKIDS.STUDENT_GU
*/
-----------------------------------------------------------------------------------------------
--INSERT IF THEY DON'T EXIST


INSERT INTO rev.REV_USER_NON_SYS

SELECT 
NEWSTUDENTVUEKIDS.STUDENT_GU AS PERSON_GU
,NEWSTUDENTVUEKIDS.SIS_NUMBER AS USER_ID
,NULL AS ACTIVATE_KEY
, NULL AS PASSWORD
,NULL AS LAST_ACCESSED
,NULL AS LAST_ACCESSED_IP
,NULL AS ACTIVATION_DATE_TIME
,NULL AS ACTIVATE_KEY_DATETIME
,1 AS USER_TYPE
,'N' AS DISABLED
,NULL AS LOGIN_ATTEMPTS
,NULL AS PREFERENCES
,'N' AS ACTIVATED_VIA_REG

FROM 
(
SELECT DISTINCT 
	STUDENT_GU,
	SIS_NUMBER

FROM 
 @TEMP AS TEMP
 INNER JOIN
 rev.EPC_STU AS STU
 ON
 TEMP.StudentIDNumber = STU.SIS_NUMBER
 LEFT JOIN
 rev.REV_USER_NON_SYS AS SYSUSER
 ON
 STU.STUDENT_GU = SYSUSER.PERSON_GU

 WHERE
 SYSUSER.PERSON_GU IS NULL

 ) AS NEWSTUDENTVUEKIDS