--Created by: e207878/Sean McMurray
--Created on: 1/25/2016
--Purpose: Data extract to pull truancy information
--Note: Need to create function/report



Select
  rev.EPC_STU.SIS_NUMBER AS [Student ID]
  ,TRUANCYLOG.ADD_DATE_TIME_STAMP AS [Date Added]
  ,rev.REV_PERSON.LAST_NAME AS [Last Name]
  ,rev.REV_PERSON.FIRST_NAME AS [First Name]
  ,rev.REV_PERSON.MIDDLE_NAME AS [Middle Name]
  ,MOSTRECENTENROLL.GRADE AS [Grade]
  ,MOSTRECENTENROLL.SCHOOL_NAME [School]
  ,TRUANCYLOG.CONTACT_TYPE AS [Contact Type]
  ,CONTACT.VALUE_DESCRIPTION AS [Contact With]
  ,LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CAST(TRUANCYLOG.NOTES AS VARCHAR), CHAR(9), ' '), CHAR(13), ' '), CHAR(10), ' '))) AS [Notes]
  ,OUTCOME1.VALUE_DESCRIPTION AS [Outcome]
  ,OUTCOME2.VALUE_DESCRIPTION AS [Outcome 2]
  ,STAFF.VALUE_DESCRIPTION AS [Staff]
  ,TITLE.VALUE_DESCRIPTION AS [Staff Title]  
  ,rev.UD_TRUANT_STUDENT.SCHOOL_YEAR AS [School Year]
  ,rev.UD_TRUANT_STUDENT.FIVE_DAY_TRUANT AS [Five Day Truant]
  ,rev.UD_TRUANT_STUDENT.TEN_DAY_TRUANT AS [Ten Day Truant]
  ,rev.UD_TRUANT_STUDENT.TWO_DAY_TRUANT AS [Two Day Truant]
  
From
  rev.UD_TRUANCY_LOG AS TRUANCYLOG
  INNER JOIN 
  rev.EPC_STU
  ON
  rev.EPC_STU.STUDENT_GU = TRUANCYLOG.STUDENT_GU
 
  INNER JOIN
  rev.REV_PERSON ON rev.EPC_STU.STUDENT_GU = rev.REV_PERSON.PERSON_GU
  INNER JOIN
  rev.UD_TRUANT_STUDENT on rev.EPC_STU.STUDENT_GU = rev.UD_TRUANT_STUDENT.STUDENT_GU
  INNER JOIN
  (
  SELECT * FROM (
  SELECT 
	ROW_NUMBER() OVER (PARTITION BY STU.STUDENT_GU ORDER BY ENTER_DATE DESC, EXCLUDE_ADA_ADM) AS RN
	,GRADE
	,SCHOOL_NAME
	,STU.STUDENT_GU
   FROM 
 APS.StudentEnrollmentDetails AS ENR
INNER JOIN
rev.EPC_STU AS STU
ON
ENR.STUDENT_GU = STU.STUDENT_GU
WHERE
ENR.EXCLUDE_ADA_ADM IS NULL
AND ENR.SCHOOL_YEAR = '2015'
AND ENR.EXTENSION = 'R'
) AS T1
WHERE RN = 1
) AS MOSTRECENTENROLL

ON
MOSTRECENTENROLL.STUDENT_GU = rev.EPC_STU.STUDENT_GU

--Lookup Table Joins
INNER JOIN
APS.LookupTable('Revelation.UD.Truancy','Outcome_1') AS OUTCOME1
ON
TRUANCYLOG.OUTCOME_1 = OUTCOME1.VALUE_CODE
LEFT JOIN
APS.LookupTable('Revelation.UD.Truancy','Outcome_2') AS OUTCOME2
ON
TRUANCYLOG.OUTCOME_2 = OUTCOME2.VALUE_CODE
LEFT JOIN
APS.LookupTable('Revelation.UD.Truancy','Truancy_Staff') AS STAFF
ON
TRUANCYLOG.TRUANCY_STAFF = STAFF.VALUE_CODE
LEFT JOIN
APS.LookupTable('Revelation.UD.Truancy','Truancy_Staff_Title') AS TITLE
ON
TRUANCYLOG.TRUANCY_STAFF_TITLE = TITLE.VALUE_CODE
LEFT JOIN
APS.LookupTable('revelation.ud.truancy','contact_with') AS CONTACT
ON
TRUANCYLOG.CONTACT_WITH = CONTACT.VALUE_CODE

WHERE 
TRUANCYLOG.UDTRUANCY_LOG_GU IS NOT NULL

ORDER BY
SCHOOL_NAME
