
SELECT 
	STUID AS SIS_NUMBER
	,SCHOOL AS SCHOOL_NAME
	,ENROLLMENT.SCHOOL_CODE
	,MEMBERDAY AS DAYS_ATTENDED
	,CASE 
		WHEN PERIOD.[Total Unexcused] IS NOT NULL THEN MEMBERDAY - PERIOD.[Total Unexcused] 
		WHEN DAILY.[Total Unexcused] IS NOT NULL THEN MEMBERDAY - DAILY.[Total Unexcused] 
		ELSE MemberDay 
	END AS DAYS_PRESENT
	,ORIGENTERDATE AS ENTER_DATE
	,endDate AS LEAVE_DATE
	,STU.STATE_STUDENT_NUMBER
	 
  FROM STUDENT_SCHOOL_MEMBERDAYS AS ENROLLMENT

  LEFT HASH JOIN 
(SELECT
			[udr].[SIS_NUMBER]
			,CAST([udr].[SCHOOL_CODE] AS VARCHAR) AS [SCHOOL_CODE]
			,SUM([udr].[Total Unexcused]) AS [Total Unexcused]
			,[o].[ORGANIZATION_NAME]

		FROM
			[APS].[PeriodUnexcusedDateRange]('20151202','20160210') AS [udr]
			
			INNER JOIN
			[rev].[EPC_SCH] AS [s]
			ON
			[udr].[SCHOOL_CODE]=[s].[SCHOOL_CODE]

			INNER JOIN
			[rev].[REV_ORGANIZATION] AS [o]
			ON
			[s].[ORGANIZATION_GU]=[o].[ORGANIZATION_GU]

		GROUP BY
			[udr].[SIS_NUMBER]
			,CAST([udr].[SCHOOL_CODE] AS VARCHAR)
			,[o].[ORGANIZATION_NAME]
		) AS PERIOD

		ON
		PERIOD.SIS_NUMBER = ENROLLMENT.STUID
		AND PERIOD.SCHOOL_CODE = ENROLLMENT.SCHOOL_CODE

LEFT HASH JOIN 

(SELECT
			[udr].[SIS_NUMBER]
			,CAST([udr].[SCHOOL_CODE] AS VARCHAR) AS [SCHOOL_CODE]
			,SUM([udr].[Unexcused Absence Count]) AS [Total Unexcused]
			,[o].[ORGANIZATION_NAME]
		FROM	
			[APS].[DailyUnexcusedDateRange]('20151202','20160210') AS [udr]

			INNER JOIN
			[rev].[EPC_SCH] AS [s]
			ON
			[udr].[SCHOOL_CODE]=[s].[SCHOOL_CODE]

			INNER JOIN
			[rev].[REV_ORGANIZATION] AS [o]
			ON
			[s].[ORGANIZATION_GU]=[o].[ORGANIZATION_GU]
			
		GROUP BY
			[udr].[SIS_NUMBER]
			,CAST([udr].[SCHOOL_CODE] AS VARCHAR)
			,[o].[ORGANIZATION_NAME]
) AS DAILY

ON
ENROLLMENT.STUID = DAILY.SIS_NUMBER
AND ENROLLMENT.SCHOOL_CODE = DAILY.SCHOOL_CODE

INNER JOIN 
rev.EPC_STU AS STU
ON
ENROLLMENT.STUID = STU.SIS_NUMBER

WHERE
ENROLLMENT.SCHOOL_CODE = '303'
  
  

