
SELECT 
	STUID AS SIS_NUMBER
	,SCHOOL AS SCHOOL_NAME
	,ENROLLMENT.SCHOOL_CODE
	,SCH.STATE_SCHOOL_CODE
	,ENROLLMENT.EXCLUDE_ADA_ADM
	,MEMBER_DAYS AS DAYS_ATTENDED
	,CASE 
		WHEN PERIOD.[Total Unexcused] IS NOT NULL THEN MEMBER_DAYS - PERIOD.[Total Unexcused] 
		WHEN DAILY.[Total Unexcused] IS NOT NULL THEN MEMBER_DAYS - DAILY.[Total Unexcused] 
		ELSE MEMBER_DAYS 
	END AS DAYS_PRESENT
	,ORIGENTERDATE AS ENTER_DATE
	,endDate AS LEAVE_DATE
	,STU.STATE_STUDENT_NUMBER
	 
  FROM 
  
  (  
 SELECT 
	MIN(startDate) AS startDate
	,MAX(endDate) AS endDate
	,org_year_gu
	,STUID
	,MIN(ORIGENTERDATE) AS ORIGENTERDATE
	,SCHOOL
	,SCHOOL_CODE
	,EXCLUDE_ADA_ADM
,SUM(CAST(MEMBER_DAYS AS INT)) AS MEMBER_DAYS
 FROM 
  STUDENT_SCHOOL_MEMBERDAYS_80D
  WHERE
	SCHOOL_CODE != '517'

  GROUP BY 
  	org_year_gu
	,STUID
	,SCHOOL
	,SCHOOL_CODE
	,EXCLUDE_ADA_ADM ) AS ENROLLMENT

  LEFT HASH JOIN 
(SELECT
			[udr].[SIS_NUMBER]
			,CAST([udr].[SCHOOL_CODE] AS VARCHAR) AS [SCHOOL_CODE]
			,SUM([udr].[Total Unexcused]) AS [Total Unexcused]
			,[o].[ORGANIZATION_NAME]

		FROM
			[APS].[PeriodAllDateRange]('20161013','20161201') AS [udr]
			
			INNER JOIN
			[rev].[EPC_SCH] AS [s]
			ON
			[udr].[SCHOOL_CODE]=[s].[SCHOOL_CODE]

			INNER JOIN
			[rev].[REV_ORGANIZATION] AS [o]
			ON
			[s].[ORGANIZATION_GU]=[o].[ORGANIZATION_GU]

		GROUP BY
			[udr].[SIS_NUMBER]
			,CAST([udr].[SCHOOL_CODE] AS VARCHAR)
			,[o].[ORGANIZATION_NAME]
		) AS PERIOD

		ON
		PERIOD.SIS_NUMBER = ENROLLMENT.STUID
		AND PERIOD.SCHOOL_CODE = ENROLLMENT.SCHOOL_CODE

LEFT HASH JOIN 

(SELECT
			[udr].[SIS_NUMBER]
			,CAST([udr].[SCHOOL_CODE] AS VARCHAR) AS [SCHOOL_CODE]
			,SUM([udr].[Unexcused Absence Count]) AS [Total Unexcused]
			,[o].[ORGANIZATION_NAME]
		FROM	
			[APS].[DailyAllDateRange]('20161013','20161201') AS [udr]

			INNER JOIN
			[rev].[EPC_SCH] AS [s]
			ON
			[udr].[SCHOOL_CODE]=[s].[SCHOOL_CODE]

			INNER JOIN
			[rev].[REV_ORGANIZATION] AS [o]
			ON
			[s].[ORGANIZATION_GU]=[o].[ORGANIZATION_GU]
			
		GROUP BY
			[udr].[SIS_NUMBER]
			,CAST([udr].[SCHOOL_CODE] AS VARCHAR)
			,[o].[ORGANIZATION_NAME]
) AS DAILY

ON
ENROLLMENT.STUID = DAILY.SIS_NUMBER
AND ENROLLMENT.SCHOOL_CODE = DAILY.SCHOOL_CODE

INNER JOIN 
rev.EPC_STU AS STU
ON
ENROLLMENT.STUID = STU.SIS_NUMBER

LEFT JOIN 
rev.EPC_SCH AS SCH
ON
ENROLLMENT.SCHOOL_CODE = SCH.SCHOOL_CODE


  
  

