EXECUTE AS LOGIN='QueryFileUser'
GO


BEGIN TRAN

UPDATE REV.EPC_STU_SCH_YR 

SET
	GRADE = '090' ,
	CHANGE_DATE_TIME_STAMP = GETDATE(),
	CHANGE_ID_STAMP = 'CCD645FF-DA2A-489D-8FDB-2B3E650E6E85'
      
FROM
	OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from T1.csv'
                ) AS [T1]

INNER JOIN REV.EPC_STU AS STU

ON
	T1.[PERM ID] = STU.SIS_NUMBER 
INNER JOIN
	REV.EPC_STU_SCH_YR SSY 
ON
	SSY.STUDENT_GU = STU.STUDENT_GU
INNER JOIN
	REV.REV_YEAR YR
ON
	SSY.YEAR_GU = YR.YEAR_GU
AND
	YR.SCHOOL_YEAR = '2016'

WHERE
	SSY.GRADE = '050'
AND 
	T1.[PERM ID] = STU.SIS_NUMBER





COMMIT
       
REVERT
GO
