


SELECT 
       SIS_NUMBER AS 'APS STUDENT ID'
       ,STATE_ID AS 'STATE ID'
       ,CASE WHEN TEST_LEVEL NOT IN ('09','10','11','12') THEN '12' ELSE TEST_LEVEL
       END AS 'PSAT TEST LEVEL'
       ,[English Language Arts] AS 'PSAT ELA SCALED SCORE'
         ,CASE WHEN [English Language Arts] >= '360' THEN 'PASS'
                    ELSE 'FAIL'
         END AS 'PSAT ELA PERFORMANCE LEVEL'
       ,Math AS 'PSAT MATH SCALED SCORE'
         ,CASE WHEN Math >= '470' THEN 'PASS'
                    ELSE 'FAIL'
         END AS 'PSAT MATH PERFORMANCE LEVEL'
         ,STUDENT_LAST_NAME
         ,STUDENT_FIRST_NAME
FROM 
(
SELECT 
    DTBL_STUDENTS.STUDENT_ID AS SIS_NUMBER
       ,SD.STUDENT_STATE_ID AS STATE_ID
       ,ATT.STUDENT_CURRENT_GRADE_CODE AS TEST_LEVEL
    ,DTBL_STUDENTS.STUDENT_GRADUATION_COHORT
    ,YEAR_VALUE AS YEAR
    ,TEST_PRODUCT 
       ,STUDENT_LAST_NAME
       ,STUDENT_FIRST_NAME
    ,TEST_SUBJECT AS CONTENT_AREA
    ,TEST_SCORE_VALUE AS SCORE
    --,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENT_ATTRIBS AS ATT
ON ATT.STUDENT_ATTRIB_KEY = K12INTEL_DW.FTBL_TEST_SCORES.STUDENT_ATTRIB_KEY
INNER JOIN K12INTEL_DW.DTBL_STUDENT_DETAILS AS SD
ON SD.STUDENT_ID = DTBL_STUDENTS.STUDENT_ID
WHERE 
1 = 1
AND (TEST_NAME LIKE '%PSAT%' AND TEST_NAME LIKE '%OVERALL')
--AND TEST_PRODUCT = 'DIBELS Next'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUDENT_ID = '104220389'
) AS PSAT
PIVOT
       (MAX(SCORE) FOR CONTENT_AREA IN ([Math],[English Language Arts])) AS UP1
       
ORDER BY SIS_NUMBER


