
WITH 
SCORE_1516 AS
(
SELECT
	[School Year]
	,[Student APS ID]
	,[Student STATE_ID]
	,BOY AS [BOY_15-16]
	,MOY AS [MOY_15-16]
	,EOY AS [EOY_15-16]
FROM
(
SELECT DISTINCT
    SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    --,TEST_PRIMARY_RESULT AS 'Dibels Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'Dibels Raw Score'
	
    ,TEST_ADMIN_PERIOD
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'DIBELS NEXT'
AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
) AS STT
	pivot
	(max([Dibels Raw Score]) FOR TEST_ADMIN_PERIOD IN ([BEG],[BOY],[MOY],[EOY])) AS UP1
)

,PL_1516 AS
(
SELECT
	[School Year]
	,[Student APS ID]
	,[Student STATE_ID]
	,BOY AS [BOY_15-16]
	,MOY AS [MOY_15-16]
	,EOY AS [EOY_15-16]
FROM
(
SELECT DISTINCT
    SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'Dibels Performance Level'
    --,CAST(TEST_SCORE_VALUE AS INT) AS 'Dibels Raw Score'
    ,TEST_ADMIN_PERIOD
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'DIBELS NEXT'
AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
) AS STT
	pivot
	(max([Dibels Performance Level]) FOR TEST_ADMIN_PERIOD IN ([BEG],[BOY],[MOY],[EOY])) AS UP1
)

SELECT
	STUDS.[School Year]
	,STUDS.[Student APS ID]
	,STUDS.[Student STATE_ID]
	,SCORE_1516.[BOY_15-16] AS BOY_SCORE
	,PL_1516.[BOY_15-16] AS BOY_PL
	,SCORE_1516.[MOY_15-16] AS MOY_SCORE
	,PL_1516.[MOY_15-16] AS MOY_PL
	,SCORE_1516.[EOY_15-16] AS EOY_SCORE
	,PL_1516.[EOY_15-16] AS EOY_PL
FROM    (
		SELECT DISTINCT
			SIS_SCHOOL_YEAR AS 'School Year'
			,STUD.STUDENT_ID AS 'Student APS ID'
			,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
		FROM K12INTEL_DW.FTBL_TEST_SCORES
		INNER JOIN K12INTEL_DW.DTBL_TESTS
		ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
		INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
		ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
		INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
		ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
		INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
		ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
		INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
		ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
		JOIN
		[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
		ON SDET.STUDENT_ID = STUD.STUDENT_ID
		WHERE 
		1 = 1
		AND TEST_PRODUCT = 'DIBELS Next'
		AND LOCAL_SCHOOL_YEAR = '2014-2015'
		) STUDS
		LEFT JOIN
		SCORE_1516
		ON SCORE_1516.[Student APS ID] = STUDS.[Student APS ID]
		LEFT JOIN
		PL_1516
		ON PL_1516.[Student APS ID] = STUDS.[Student APS ID]
		--AND TEST_PRODUCT = 'PARCC'
