

WITH ALGII AS

(
SELECT * FROM
(
SELECT DISTINCT
    ROW_NUMBER () OVER (PARTITION BY STUD.STUDENT_ID ORDER BY TEST_SCORE_VALUE DESC) AS RN
    ,SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC Algebra II Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC Algebra II Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'ALGEBRA II'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'
) A
WHERE RN = 1
)

,ALGII_2015 AS
(
SELECT * FROM
(
SELECT DISTINCT
    ROW_NUMBER () OVER (PARTITION BY STUD.STUDENT_ID ORDER BY TEST_SCORE_VALUE DESC) AS RN
    ,SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC Algebra II Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC Algebra II Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'ALGEBRA II'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'
) A
WHERE RN = 1
)

,MATH AS
(
SELECT DISTINCT
    SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC MATHEMATICS Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC MATHEMATICS Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'MATHEMATICS'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'

)
,MATH15 AS
(
SELECT DISTINCT
    SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC MATHEMATICS Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC MATHEMATICS Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'MATHEMATICS'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'

)

,ALGI AS
(
SELECT * FROM
(
SELECT DISTINCT
    ROW_NUMBER () OVER (PARTITION BY STUD.STUDENT_ID ORDER BY TEST_SCORE_VALUE DESC) AS RN
    ,SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC Algebra I Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC Algebra I Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'ALGEBRA I'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'
) A
WHERE RN = 1
)

,ALGI2015 AS
(
SELECT * FROM
(
SELECT DISTINCT
    ROW_NUMBER () OVER (PARTITION BY STUD.STUDENT_ID ORDER BY TEST_SCORE_VALUE DESC) AS RN
    ,SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC Algebra I Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC Algebra I Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'ALGEBRA I'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'
) A
WHERE RN = 1
)

,ELA AS
(
SELECT * FROM
(
SELECT DISTINCT
    ROW_NUMBER () OVER (PARTITION BY STUD.STUDENT_ID ORDER BY TEST_SCORE_VALUE DESC) AS RN
    ,SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC ELA Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC ELA Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'ELA'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'
) A
WHERE RN = 1
)

,ELA_2015 AS
(
SELECT * FROM
(
SELECT DISTINCT
    ROW_NUMBER () OVER (PARTITION BY STUD.STUDENT_ID ORDER BY TEST_SCORE_VALUE DESC) AS RN
    ,SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC ELA Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC ELA Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'ELA'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'
) A
WHERE RN = 1
)

,GEOM AS
(
SELECT * FROM
(
SELECT DISTINCT
    ROW_NUMBER () OVER (PARTITION BY STUD.STUDENT_ID ORDER BY TEST_SCORE_VALUE DESC) AS RN
    ,SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC GEOMETRY Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC GEOMETRY Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'GEOMETRY'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2014-2015'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'
) A
WHERE RN = 1
)

,GEOM15 AS
(
SELECT * FROM
(
SELECT DISTINCT
    ROW_NUMBER () OVER (PARTITION BY STUD.STUDENT_ID ORDER BY TEST_SCORE_VALUE DESC) AS RN
    ,SIS_SCHOOL_YEAR AS 'School Year'
	,STUD.STUDENT_ID AS 'Student APS ID'
	,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
    ,TEST_PRIMARY_RESULT AS 'PARCC GEOMETRY Overall Performance Level'
    ,CAST(TEST_SCORE_VALUE AS INT) AS 'PARCC GEOMETRY Scale Score'
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
JOIN
[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
ON SDET.STUDENT_ID = STUD.STUDENT_ID
WHERE 
1 = 1
AND TEST_PRODUCT = 'PARCC'
AND TEST_GROUP = 'GEOMETRY'
AND TEST_SUBGROUP = 'OVERALL'
--AND TEST_SUBGROUP IN ('TOT','Composite')
AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND TEST_EXTERNAL_CODE = 'BEG'
--AND STUD.STUDENT_ID = '970084689'
) A
WHERE RN = 1
)


SELECT
	STUDS.[School Year]
	,STUDS.[Student APS ID]
	,STUDS.[Student STATE_ID]
	--,ELA.[PARCC ELA Overall Performance Level]
	--,ELA.[PARCC ELA Scale Score]
	,ELA_2015.[PARCC ELA Overall Performance Level]
	,ELA_2015.[PARCC ELA Scale Score]
	--,MATH.[PARCC MATHEMATICS Overall Performance Level]
	--,MATH.[PARCC MATHEMATICS Scale Score]
	,MATH15.[PARCC MATHEMATICS Overall Performance Level]
	,MATH15.[PARCC MATHEMATICS Scale Score]
	--,ALGI.[PARCC Algebra I Overall Performance Level]
	--,ALGI.[PARCC Algebra I Scale Score]
	,ALGI2015.[PARCC Algebra I Overall Performance Level]
	,ALGI2015.[PARCC Algebra I Scale Score]
	--,ALGII.[PARCC Algebra II Overall Performance Level]
	--,ALGII.[PARCC Algebra II Scale Score]
	,ALGII_2015.[PARCC Algebra II Overall Performance Level]
	,ALGII_2015.[PARCC Algebra II Scale Score]
	--,GEOM.[PARCC GEOMETRY Overall Performance Level]
	--,GEOM.[PARCC GEOMETRY Scale Score]
	,GEOM15.[PARCC GEOMETRY Overall Performance Level]
	,GEOM15.[PARCC GEOMETRY Scale Score]
FROM    (
		SELECT DISTINCT
			SIS_SCHOOL_YEAR AS 'School Year'
			,STUD.STUDENT_ID AS 'Student APS ID'
			,SDET.STUDENT_STATE_ID AS 'Student STATE_ID'
		FROM K12INTEL_DW.FTBL_TEST_SCORES
		INNER JOIN K12INTEL_DW.DTBL_TESTS
		ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
		INNER JOIN K12INTEL_DW.DTBL_STUDENTS STUD
		ON STUD.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
		INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
		ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
		INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
		ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
		INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
		ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
		JOIN
		[K12INTEL_DW].[DTBL_STUDENT_DETAILS] AS SDET
		ON SDET.STUDENT_ID = STUD.STUDENT_ID
		WHERE 
		1 = 1
		AND TEST_PRODUCT = 'PARCC'
		) STUDS
		LEFT JOIN
		ELA
		ON ELA.[Student APS ID] = STUDS.[Student APS ID]
		AND ELA.[School Year] = STUDS.[School Year]
		LEFT JOIN
		ELA_2015
		ON ELA_2015.[Student APS ID] = STUDS.[Student APS ID]
		AND ELA_2015.[School Year] = STUDS.[School Year]
		LEFT JOIN
		ALGI
		ON ALGI.[Student APS ID] = STUDS.[Student APS ID]
		AND ALGI.[School Year] = STUDS.[School Year]
		LEFT JOIN
		ALGI2015
		ON ALGI2015.[Student APS ID] = STUDS.[Student APS ID]
		AND ALGI2015.[School Year] = STUDS.[School Year]
		LEFT JOIN
		ALGII
		ON ALGII.[Student APS ID] = STUDS.[Student APS ID]
		AND ALGII.[School Year] = STUDS.[School Year]
		LEFT JOIN
		ALGII_2015
		ON ALGII_2015.[Student APS ID] = STUDS.[Student APS ID]
		AND ALGII_2015.[School Year] = STUDS.[School Year]
		LEFT JOIN
		GEOM
		ON GEOM.[Student APS ID] = STUDS.[Student APS ID]
		AND GEOM.[School Year] = STUDS.[School Year]
		LEFT JOIN
		GEOM15
		ON GEOM15.[Student APS ID] = STUDS.[Student APS ID]
		AND GEOM15.[School Year] = STUDS.[School Year]
		LEFT JOIN
		MATH
		ON MATH.[Student APS ID] = STUDS.[Student APS ID]
		AND MATH.[School Year] = STUDS.[School Year]
		LEFT JOIN
		MATH15
		ON MATH15.[Student APS ID] = STUDS.[Student APS ID]
		AND MATH15.[School Year] = STUDS.[School Year]
WHERE
	STUDS.[School Year] = '2015'
	--AND STUDS.[Student APS ID] = '100029149'
ORDER BY STUDS.[Student APS ID], STUDS.[School Year]

