SELECT 
                b.TEST_ADMIN_KEY
               ,b.STUDENT_MATCH_TYPE 
    ,b.STUDENT_MATCH_RESULT                
    ,b.SYS_LINEAGE 
                ,b.VENDOR_STUDENT_ID 
                ,b.DISTRICT_STUDENT_ID 
                ,b.STUDENT_FIRST_NAME VENDOR_STUDENT_FIRST_NAME 
                ,c.STUDENT_FIRST_NAME 
                ,b.STUDENT_LAST_NAME VENDOR_STUDENT_LAST_NAME 
                ,c.STUDENT_LAST_NAME 
                ,b.STUDENT_BIRTHDATE_STR VENDOR_BIRTHDATE 
                ,c.STUDENT_BIRTHDATE 
                ,b.VENDOR_SCHOOL_ID 
                ,b.STATE_SCHOOL_ID 
                ,b.DISTRICT_SCHOOL_ID 
				,b.STUDENT_MATCH_QUALITY

FROM K12INTEL_USERDATA.XTBL_TEST_BATCH_IDS a 
INNER JOIN K12INTEL_USERDATA.XTBL_TEST_ADMIN b 
                ON (b.BATCH_ID = a.BATCH_ID) 
LEFT JOIN K12INTEL_DW.DTBL_STUDENT_DETAILS c 
                ON (c.STUDENT_ID = b.DISTRICT_STUDENT_ID) 
WHERE 1=1
    --and a.BATCH_ID = 981
    and b.STUDENT_MATCH_QUALITY <> '[High]'
	and SYS_LINEAGE like '%ACT\001\APS\2016-2017\Sep-Nov\Sep-Nov%'


SELECT b.*--STUDENT_MATCH_TYPE, b.STUDENT_MATCH_QUALITY, COUNT(*)
FROM k12intel_userdata.XTBL_TEST_BATCH_IDS a
LEFT JOIN k12intel_userdata.XTBL_TEST_ADMIN b
ON a.BATCH_ID = b.BATCH_ID
--LEFT JOIN k12intel_userdata.XTBL_TEST_SCORES c
--ON b.TEST_ADMIN_KEY = c.TEST_ADMIN_KEY
WHERE 1=1
    --and a.BATCH_ID = 1157
    AND B.STUDENT_MATCH_QUALITY <> '[High]'
	and SYS_LINEAGE like '%ACT\001\APS\2016-2017\Sep-Nov\Sep-Nov%'
