
SELECT SIS_NUMBER, SCHOOL_NAME, PRIM.GRADE 

FROM 

APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS PRIM
INNER JOIN 
rev.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU
LEFT JOIN 
STUDENT_ATTENDANCE AS ATT
ON
STU.SIS_NUMBER = ATT.[SIS Number]

WHERE
ATT.[SIS Number] IS NULL

ORDER BY SCHOOL_NAME, GRADE