

/**
 * CREATED BY DEBBIE ANN CHAVEZ
 *	DATE 8/15/2014
 *
 */
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[APS].[MostRecentHLSAsOf]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
	EXEC('CREATE FUNCTION APS.MostRecentHLSAsOf()RETURNS TABLE AS RETURN (SELECT 0 AS DUMMY)')
GO

/*
 * FUNCTION APS.MostRecentHLSAsOf
 *
 *	Pull most recent HLS Record from the User Defined UD_HLS_HISTORY table
 * 
 * 
 */ 
 
 
ALTER FUNCTION APS.MostRecentHLSAsOf(@asOfDate DATETIME)
RETURNS TABLE
AS
RETURN

		SELECT 
			SIS_NUMBER
			,DATE_ASSIGNED
			,Q1LANG.VALUE_DESCRIPTION AS Q1_LANG_MOST_TIME
			,Q2LANG.VALUE_DESCRIPTION AS Q2_CHILDS_FIRST_LANGUAGE
			,Q3LANG.VALUE_DESCRIPTION AS Q3_OTHER_LANGUAGES_SPOKEN
			,Q4LANG.VALUE_DESCRIPTION AS Q4_OTHER_LANGUAGES_UNDERSTOOD
			,Q5LANG.VALUE_DESCRIPTION AS Q5_OTHER_FAMILY_COMMINICATION
			,STUDENT_GU
		 FROM				
						(
						SELECT 
								*
								FROM
										(
											SELECT 
												ROW_NUMBER() OVER (PARTITION BY HISTORY.STUDENT_GU ORDER BY DATE_ASSIGNED DESC) AS RN
												,DATE_ASSIGNED
												,HISTORY.STUDENT_GU
												,Q1_LANGUAGE_MOST_TIME
												,Q2_CHILDS_FIRST_LANGUAGE
												,Q3_OTHER_LANGUAGES_SPOKEN
												,Q4_OTHER_LANGUAGES_UNDERSTA
												,Q5_OTHER_FAMILY_COMMUNICAT
												,STUDENT.SIS_NUMBER
											FROM
												rev.UD_UD_HLSHISTORY AS HISTORY
												INNER JOIN
												rev.EPC_STU AS STUDENT
												ON
												HISTORY.STUDENT_GU = STUDENT.STUDENT_GU
										WHERE
												DATE_ASSIGNED <= @AsOfDate

											) AS HLS

								WHERE
								RN = 1

								) AS MOST_RECENT_HLS

								--JOIN TO LOOKUP TABLES FOR LANGUAGE DESCRIPTION
								INNER JOIN
								APS.LookupTable ('K12', 'Language') AS Q1LANG
								ON
								Q1LANG.VALUE_CODE = MOST_RECENT_HLS.Q1_LANGUAGE_MOST_TIME												
								INNER JOIN
								APS.LookupTable ('K12', 'Language') AS Q2LANG
								ON
								Q2LANG.VALUE_CODE = MOST_RECENT_HLS.Q2_CHILDS_FIRST_LANGUAGE
								INNER JOIN
								APS.LookupTable ('K12', 'Language') AS Q3LANG
								ON
								Q3LANG.VALUE_CODE = MOST_RECENT_HLS.Q3_OTHER_LANGUAGES_SPOKEN
								INNER JOIN
								APS.LookupTable ('K12', 'Language') AS Q4LANG
								ON
								Q4LANG.VALUE_CODE = MOST_RECENT_HLS.Q4_OTHER_LANGUAGES_UNDERSTA
								INNER JOIN
								APS.LookupTable ('K12', 'Language') AS Q5LANG
								ON
								Q5LANG.VALUE_CODE = MOST_RECENT_HLS.Q5_OTHER_FAMILY_COMMUNICAT