SELECT 
       [SCHOOL CODE], [School Name]
       , M_HIS_AP, M_AME_AP, M_ASI_AP, M_HI_PAC_AP, M_BLA_AP, M_WHI_AP, M_2_OR_MORE_AP, M_TOT_AP, M_DIS_AP, M_ELL_AP, M_504_AP
       , F_HIS_AP, F_AME_AP, F_ASI_AP, F_HI_PAC_AP, F_BLA_AP, F_WHI_AP, F_2_OR_MORE_AP, F_TOT_AP, F_DIS_AP, F_ELL_AP, F_504_AP

FROM 
(
SELECT 
              [SCHOOL CODE]
              ,[School Name]
              ,SUM(CASE WHEN [TWO_OR_MORE]='Hispanic' AND Gender = 'M' THEN 1 ELSE 0 END) AS [M_HIS_AP]
              ,SUM(CASE WHEN [TWO_OR_MORE]='Native American' AND Gender = 'M' THEN 1 ELSE 0 END) AS [M_AME_AP]  
              ,SUM(CASE WHEN [TWO_OR_MORE]='Asian' AND Gender = 'M' THEN 1 ELSE 0 END) AS [M_ASI_AP]
              ,SUM(CASE WHEN [TWO_OR_MORE]='Pacific Islander' AND Gender = 'M' THEN 1 ELSE 0 END) AS [M_HI_PAC_AP]
              ,SUM(CASE WHEN [TWO_OR_MORE]='African-American' AND Gender = 'M' THEN 1 ELSE 0 END) AS [M_BLA_AP]
              ,SUM(CASE WHEN [TWO_OR_MORE]='White' AND Gender = 'M' THEN 1 ELSE 0 END) AS [M_WHI_AP]
              ,SUM(CASE WHEN [TWO_OR_MORE]='Two or more races' AND Gender = 'M' THEN 1 ELSE 0 END) AS [M_2_OR_MORE_AP]

              ,SUM(CASE WHEN Gender = 'M' THEN 1 ELSE 0 END) AS [M_TOT_AP]

              ,SUM(CASE WHEN Gender = 'M'  AND SPED_STATUS='Y' THEN 1 ELSE 0 END) AS [M_DIS_AP]
              ,SUM(CASE WHEN Gender = 'M'  AND ELL_STATUS='Y' THEN 1 ELSE 0 END) AS [M_ELL_AP]
              ,SUM(CASE WHEN Gender = 'M'  AND [ACCESS_504]='Y' THEN 1 ELSE 0 END) AS [M_504_AP]
              
              ,SUM(CASE WHEN [TWO_OR_MORE]='Hispanic' AND Gender = 'F' THEN 1 ELSE 0 END) AS [F_HIS_AP]
              ,SUM(CASE WHEN [TWO_OR_MORE]='Native American' AND Gender = 'F' THEN 1 ELSE 0 END) AS [F_AME_AP]  
              ,SUM(CASE WHEN [TWO_OR_MORE]='Asian' AND Gender = 'F' THEN 1 ELSE 0 END) AS [F_ASI_AP]  
              ,SUM(CASE WHEN [TWO_OR_MORE]='Pacific Islander' AND Gender = 'F' THEN 1 ELSE 0 END) AS [F_HI_PAC_AP]
              ,SUM(CASE WHEN [TWO_OR_MORE]='African-American' AND Gender = 'F' THEN 1 ELSE 0 END) AS [F_BLA_AP]
              ,SUM(CASE WHEN [TWO_OR_MORE]='White' AND Gender = 'F' THEN 1 ELSE 0 END) AS [F_WHI_AP]
              ,SUM(CASE WHEN [TWO_OR_MORE]='Two or more races' AND Gender = 'F' THEN 1 ELSE 0 END) AS [F_2_OR_MORE_AP]

              ,SUM(CASE WHEN Gender = 'F' THEN 1 ELSE 0 END) AS [F_TOT_AP]

              ,SUM(CASE WHEN Gender = 'F'  AND SPED_STATUS='Y' THEN 1 ELSE 0 END) AS [F_DIS_AP]
              ,SUM(CASE WHEN Gender = 'F'  AND ELL_STATUS='Y' THEN 1 ELSE 0 END) AS [F_ELL_AP]
              ,SUM(CASE WHEN Gender = 'F'  AND [ACCESS_504]='Y' THEN 1 ELSE 0 END) AS [F_504_AP]

FROM 
(
--SELECT DISTINCT 
--	SIS_NUMBER
--	,RACE_1
--	,RACE_2
--	,HISPANIC_INDICATOR
--	,SPED_STATUS
--	,GENDER
--	,ELL_STATUS
--	,ACCESS_504
--	,TWO_OR_MORE
--	,[SCHOOL CODE]
--	,[SCHOOL NAME]
--FROM
--(
SELECT DISTINCT 
	SIS_NUMBER
	,RACE_1
	,RACE_2
	,HISPANIC_INDICATOR
	,SPED_STATUS
	,GENDER
	,ELL_STATUS
	,ACCESS_504
	,TWO_OR_MORE
	,GRADE
	,ORGANIZATION_NAME AS 'SCHOOL NAME'
	,SCHOOL_CODE AS 'SCHOOL CODE'
FROM
(
SELECT 
	   --ROW_NUMBER () OVER (PARTITION BY StudentTest.STUDENT_GU ORDER BY StudentTest.STUDENT_GU) AS RN
	   PERSON.FIRST_NAME
       ,PERSON.LAST_NAME
       ,CAST (Student.SIS_NUMBER AS INT) AS SIS_NUMBER
       ,STUDENTTEST.ADMIN_DATE
	   ,BS.RACE_1
	   ,CASE WHEN BS.RACE_2 IS NULL THEN '' ELSE BS.RACE_2
	   END AS RACE_2
	   ,CASE 
       WHEN (BS.Race_1 != '' AND BS.Race_2 != '') THEN 'Two or more races' 
       WHEN BS.Race_1 = 'White' AND BS.HISPANIC_INDICATOR = 'Y' THEN 'Hispanic' 
       ELSE BS.Race_1 END AS TWO_OR_MORE
	   ,BS.HISPANIC_INDICATOR
	   ,BS.SPED_STATUS
	   ,BS.GENDER
	   ,BS.ELL_STATUS
	   ,CASE WHEN SSY.ACCESS_504 IS NULL THEN '' ELSE SSY.ACCESS_504 
	   END AS ACCESS_504
	   ,GRADE.VALUE_DESCRIPTION AS GRADE
	   ,ORG.ORGANIZATION_NAME
	   ,SCH.SCHOOL_CODE
	   --,TEST_NAME
FROM
    rev.EPC_STU_TEST AS StudentTest

    JOIN
    rev.EPC_TEST_PART AS PART
    ON StudentTest.TEST_GU = PART.TEST_GU

	JOIN
	rev.EPC_STU_TEST_PART AS STU_PART
	ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
	AND STU_PART.STUDENT_TEST_GU = StudentTest.STUDENT_TEST_GU

    INNER JOIN
    rev.EPC_STU_TEST_PART_SCORE AS SCORES
    ON
    SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = StudentTest.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST AS TEST
    ON TEST.TEST_GU = StudentTest.TEST_GU

    INNER JOIN
    rev.EPC_STU AS Student
    ON Student.STUDENT_GU = StudentTest.STUDENT_GU

    INNER JOIN
    rev.REV_PERSON AS Person
    ON Person.PERSON_GU = StudentTest.STUDENT_GU

	JOIN
	APS.BasicStudentWithMoreInfo AS BS
	ON BS.STUDENT_GU = StudentTest.STUDENT_GU

	JOIN
	APS.EnrollmentsForYear ('BCFE2270-A461-4260-BA2B-0087CB8EC26A') ENR
	ON ENR.STUDENT_GU = StudentTest.STUDENT_GU

	JOIN
	rev.EPC_STU_SCH_YR AS SSY
	ON SSY.STUDENT_SCHOOL_YEAR_GU = ENR.STUDENT_SCHOOL_YEAR_GU

	JOIN
	rev.SIF_22_Common_GetLookupValues('K12', 'GRADE') grade ON grade.VALUE_CODE = ENR.GRADE

	JOIN
	REV.REV_ORGANIZATION AS ORG
	ON ORG.ORGANIZATION_GU = ENR.ORGANIZATION_GU

	JOIN
	REV.EPC_SCH SCH
	ON SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU

	--JOIN

WHERE
1 = 1
	   AND TEST_NAME LIKE '%ap %'
	   AND ADMIN_DATE = '2016-05-01 00:00:00'
	   AND ENR.EXCLUDE_ADA_ADM IS NULL
) AS T1
WHERE 1 = 1
--) AS T22
) T2
GROUP BY
[SCHOOL NAME], [SCHOOL CODE]

)T3
GROUP BY 
	[School Code], [School Name]
	, M_HIS_AP, M_AME_AP, M_ASI_AP, M_HI_PAC_AP, M_BLA_AP, M_WHI_AP, M_2_OR_MORE_AP, M_TOT_AP, M_DIS_AP, M_ELL_AP, M_504_AP
	, F_HIS_AP, F_AME_AP, F_ASI_AP, F_HI_PAC_AP, F_BLA_AP, F_WHI_AP, F_2_OR_MORE_AP, F_TOT_AP, F_DIS_AP, F_ELL_AP, F_504_AP
ORDER BY [School Code]
	,[School Name]