
BEGIN TRANSACTION 

UPDATE rev.EPC_NM_STU_SPED_RPT

SET SPED_GIFTED_TYPE = 6
	,CHANGE_DATE_TIME_STAMP = GETDATE()
	,CHANGE_ID_STAMP = '27CDCD0E-BF93-4071-94B2-5DB792BB735F'

FROM 

(SELECT DISTINCT 
--SCHOOL_CODE, SCHOOL_NAME, 
STU.SIS_NUMBER, ACCESS_504, PRIM.STUDENT_GU
FROM 
APS.StudentEnrollmentDetails AS PRIM 
INNER JOIN 
REV.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU
WHERE
	PRIM.[ACCESS_504] IS NOT NULL
	AND SCHOOL_YEAR = 2015
	AND EXTENSION = 'R'
) AS T1

WHERE 
SCHOOL_YEAR = 2015 AND SNAPSHOT_TYPE = 1
AND T1.STUDENT_GU = rev.EPC_NM_STU_SPED_RPT.STUDENT_GU

COMMIT

BEGIN TRANSACTION 
INSERT rev.EPC_NM_STU_SPED_RPT

SELECT 
NEWID() AS STU_SEPD_RPT_GU
,T1.STUDENT_GU
,'2015' AS SCHOOL_YEAR
,1 AS SNAPSHOT_TYPE
, 'Y' AS INCLUDE_IN_SNAPSHOT
,6 AS SPED_GIFTED_TYPE
,'N' AS TRANSITION_SERVICES
,NULL AS EARLY_CHILD_REFERRAL
,NULL AS LEVEL_INTEGRATION
,NULL AS DISABILITY_PRIMARY
, NULL AS DISABILITY_SECONDARY
, NULL AS DISABILITY_TERTIARY
,NULL AS DISABILITY_QUATERNARY
,NULL AS PRIMARY_SETTING
,NULL AS PLACEMENT
,NULL AS LAST_IEP_DATE
,NULL AS LAST_EVAL_DATE
,NULL AS CASE_MANAGER_GU
,NULL AS CASE_MANAGER_SSN
,NULL AS CASE_MANAGER_NAME
,NULL AS DIPLOMA_TYPE
,'N' AS ESY
,NULL AS SPED_ENTRY_DATE
,NULL AS PRIMARY_CAUSE
,NULL AS LIVING_SETTING
,NULL AS LEVEL_HEARING
,NULL AS LEVEL_VISION
,NULL AS IEP_TRANSITION_STATUS
,'Y' AS ENROLLED_AT_START
,'N' AS QUAL_MENTAL_HEALTH
,'N' AS QUAL_VOC_REHAB
, 'N' AS QUAL_DEV_DISABLED
,'N' AS QUAL_IND_LIVING
,'N' AS QUAL_POST_SEC
,NULL AS IEP_GU
,GETDATE() AS ADD_DATE_TIME_STAMP
,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS ADD_ID_STAMP
,NULL AS CHANGE_ID_STAMP
,NULL AS CHANGE_DATE_TIME_STAMP
,'N' AS LOCKED
,NULL AS PROJ_GRAD_EXIT_DATE
,NULL AS BRAILLE_INSTRUCTIONS

FROM 
(
SELECT DISTINCT 
--SCHOOL_CODE, SCHOOL_NAME, 
STU.SIS_NUMBER, ACCESS_504, PRIM.STUDENT_GU
FROM 
APS.StudentEnrollmentDetails AS PRIM 
INNER JOIN 
REV.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU
WHERE
	PRIM.[ACCESS_504] IS NOT NULL
	AND SCHOOL_YEAR = 2015
	AND EXTENSION = 'R'
) AS T1
LEFT JOIN 
rev.EPC_NM_STU_SPED_RPT AS RPT
ON
T1.STUDENT_GU = RPT.STUDENT_GU

WHERE
RPT.STUDENT_GU IS NULL 

COMMIT