
/*************************************************************************
	THIS READS A FILE FROM CMP AND COMPARES TO SEE WHICH EXIST IN SYNERGY

	CREATE A FILE OF THE RECORDS THAT DO NOT EXIST TO INSERT IN STEP 2

*************************************************************************/



EXECUTE AS LOGIN='QueryFileUser'
GO

SELECT * FROM (

SELECT *
	FROM 
(
SELECT 
	
	T1.*
	,GRID.GRID_CODE
	,STREET.SCHOOL_YEAR
	,STREET.STREET_LOW_ADDRESS
	,STREET.STREET_NAME
	,STREET.STREET_TYPE
	,STREET.[STREET_POST_DIRECTION]
	,STREET.CITY AS STREET_CITY
	,STREET.STATE AS STREET_STATE
	,STREET.ZIP_5
	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from CMPFILE.csv'
                ) AS [T1]

	LEFT JOIN 
	(SELECT * FROM 
	rev.EPC_STREET
	LEFT JOIN 
	 [APS].[LookupTable]('K12.AddressInfo','STREET_TYPE') AS LU
	 ON
	 LU.VALUE_CODE = STREET_TYPE 
	 WHERE rev.EPC_STREET.SCHOOL_YEAR = 2016
	 ) AS STREET
	ON
	STREET.STREET_LOW_ADDRESS = T1.[HOUSE NUMBER]
	AND STREET.STREET_NAME = T1.STREET
	--AND STREET.[STREET_POST_DIRECTION] = T1.QUADRANT
	AND STREET.ZIP_5 = T1.ZIPCODE
	AND STREET.SCHOOL_YEAR = 2016
	--AND T1.[STREET TYPE] = STREET.VALUE_DESCRIPTION
	
	LEFT JOIN 
	rev.EPC_GRID AS GRID
	ON
	GRID.GRID_GU = STREET.GRID_GU
	AND GRID.SCHOOL_YEAR = STREET.SCHOOL_YEAR
	
)AS T2

) AS T3
--WHERE RN> 1

WHERE 
T3.GRID_CODE IS NULL



ORDER BY  STREET_NAME, STREET_LOW_ADDRESS
	
REVERT
GO