WITH STUDENT_CTE
AS
(
select
	 STU.SIS_NUMBER,
	 STU.LAST_NAME,
	 STU.FIRST_NAME,
	 SED.SCHOOL_YEAR,
	 SED.SCHOOL_CODE,
	 SED.SCHOOL_NAME,
	 SED.GRADE,
	 STU.RESOLVED_RACE,
	 STU.BIRTH_DATE,
	 STU.GENDER,
	 --frpl status
	 STU.ELL_STATUS,
	 STU.SPED_STATUS,
	 STU.PRIMARY_DISABILITY_CODE


from
	 aps.BasicStudentWithMoreInfo STU 

inner join aps.StudentEnrollmentDetails SED on STU.STUDENT_GU = SED.STUDENT_GU
)
	select distinct STUDENT_CTE.SIS_NUMBER,
		STUDENT_CTE.LAST_NAME,
		STUDENT_CTE.FIRST_NAME,
		STUDENT_CTE.SCHOOL_YEAR,
		STUDENT_CTE.SCHOOL_CODE,
		STUDENT_CTE.SCHOOL_NAME,
		STUDENT_CTE.GRADE,
		STUDENT_CTE.RESOLVED_RACE,
		STUDENT_CTE.BIRTH_DATE,
		STUDENT_CTE.GENDER,
		--frpl status
		STUDENT_CTE.ELL_STATUS,
		
		--CHECK FOR GIFTED
		CASE WHEN STUDENT_CTE.PRIMARY_DISABILITY_CODE != 'GI' AND STUDENT_CTE.PRIMARY_DISABILITY_CODE IS NOT NULL THEN 'Y' ELSE 'N' END AS [SPED_STATUS],
		CASE WHEN STUDENT_CTE.PRIMARY_DISABILITY_CODE = 'GI' OR STUDENT_CTE.PRIMARY_DISABILITY_CODE = 'GI' THEN 'Y' ELSE 'N' END AS [GIFTED_STATUS],

		STUDENT_CTE.SPED_STATUS
	
	from
		STUDENT_CTE 
	where
		
		STUDENT_CTE.SCHOOL_YEAR in ('2015', '2016')
		--exclude gifted
		AND STUDENT_CTE.SPED_STATUS != 'Y'



