

--CREATE VERSIFIT TABLE - DAILY RUN, INCLUDES PERFECT ATTENDANCE STUDENTS

DROP TABLE dbo.ATTENDANCE_2016
CREATE TABLE dbo.ATTENDANCE_2016

( 
	SCHOOL_YEAR VARCHAR (4)
	  ,[SIS_NUMBER]  VARCHAR (9)
      ,[SCHOOL_CODE]  VARCHAR (4)
      ,[GRADE]  VARCHAR (2)
	  ,[MEMBERDAYS]  VARCHAR (4)
	  ,[Total Excused] VARCHAR (9)
	  ,[Total Unexcused] VARCHAR (9)
,[TOTAL_ABSENCES]  VARCHAR (9)
) 

INSERT INTO dbo.ATTENDANCE_2016

SELECT 
'2016' AS SCHOOL_YEAR
,SIS_NUMBER
,SCHOOL_CODE 
,GRADE
,MEMBERDAYS
,[Total Excused]
,[Total Unexcused]
,CASE WHEN Total_Exc_Unex IS NULL THEN '0.00' ELSE Total_Exc_Unex END AS TOTAL_ABSENCES

 
FROM (

SELECT 

AT16.Total_Exc_Unex
,[Total Excused]
,[Total Unexcused]
, MEM16.SIS_NUMBER
, MEM16.SCHOOL_CODE
, MEM16.MEMBERDAYS
, MEM16.GRADE
  
  
  FROM [STUDENT_ATTENDANCE] AS AT16
  RIGHT JOIN 
   (SELECT 
	SIS_NUMBER
	,FIRST_NAME
	,LAST_NAME
	,GRADE
	,SCHOOL_YEAR
	,SCHOOL_CODE
	,EXCLUDE_ADA_ADM
	,MEMBERDAYS
	,MIN(CAST(ENTER_DATE AS DATE)) AS ENTER_DATE
	,MAX(CAST(LEAVE_DATE AS DATE)) AS LEAVE_DATE

 FROM 
STUDENT_SCHOOL_MEMBERDAYS AS MEM

GROUP BY
	SIS_NUMBER
	,FIRST_NAME
	,LAST_NAME
	,GRADE
	,SCHOOL_YEAR
	,SCHOOL_CODE
	,EXCLUDE_ADA_ADM
	,MEMBERDAYS
	) AS MEM16
  ON
AT16.[SIS Number] = MEM16.SIS_NUMBER
AND AT16.[School Code] = MEM16.SCHOOL_CODE

  LEFT JOIN 
  (SELECT GRADE,SIS_NUMBER FROM 
APS.LatestPrimaryEnrollmentInYear('F7D112F7-354D-4630-A4BC-65F586BA42EC')
) AS ENR16
ON
ENR16.SIS_NUMBER = MEM16.SIS_NUMBER


) AS T1
  ORDER BY SCHOOL_CODE, SIS_NUMBER

  ----------------------------------------------------------------------------------------