
/*
*	Created By:  Debbie Ann Chavez
*	Date:  7/2/2014
*
*	This is how to create a Lookup Definition
*	(Used this to create a lookup node for Revelation.Person, Federal_Employee Lookup
*
*/


BEGIN TRANSACTION

INSERT INTO  rev.REV_BOD_LOOKUP_DEF

	(LOOKUP_DEF_GU, LOOKUP_NAMESPACE, LOOKUP_DEF_CODE, OWNED_BY_PRODUCT, EDITABLE_WIDTH, DEPLOY_LOCATION
	,OLD_SIS_LOOKUP_DEF_ID, USE_CODE_REPORT_TO_STATE, EDFI_MAPPING)

SELECT 
	NEWID() AS LOOKUP_DEF_GU
	,'K12.NativeAmerican' AS LOOKUP_NAMESPACE
	,'506_IE' AS LOOKUP_DEF_CODE
	,'N' AS OWNED_BY_PRODUCT
	,5 AS EDITABLE_WIDTH
	,'USA.NM.ABQ' AS DEPLOY_LOCATION
	,NULL AS OLD_SIS_LOOKUP_DEF_ID
	,'N' AS USE_CODE_REPORT_TO_STATE
	,NULL AS EDFI_MAPPING

FROM 
	rev.REV_BOD_LOOKUP_DEF

WHERE 
	EDITABLE_WIDTH = 1

ROLLBACK