


SELECT
	[XTBL_TEST_ADMIN.PROD_TEST_ID]
	,[XTBL_TEST_ADMIN.DISTRICT_CODE]
	,[XTBL_TEST_ADMIN.DISTRICT_STUDENT_ID]
	,[XTBL_TEST_ADMIN.DISTRICT_SCHOOL_ID]
	,[XTBL_TEST_ADMIN.TEST_ADMIN_PERIOD]
	,[XTBL_TEST_ADMIN.TEST_ADMIN_DATE_STR]
	,[XTBL_TEST_ADMIN.STUDENT_LAST_NAME]
	,[XTBL_TEST_ADMIN.STUDENT_FIRST_NAME]
	,[XTBL_TEST_ADMIN.TEST_LANGUAGE]
	,[XTBL_TESTS.TEST_NUMBER]
	,[XTBL_TESTS.DISTRICT_CODE]
	,[XTBL_TESTS.TEST_CLASS]
	,[XTBL_TESTS.TEST_NAME]
	,[XTBL_TESTS.TEST_SUBJECT]
	,[XTBL_TESTS.TEST_VENDOR]
	,[XTBL_TESTS.TEST_PRODUCT]
	,[XTBL_TESTS.TEST_GROUP]
	,[XTBL_TESTS.TEST_VERSION]
	,[XTBL_TEST_SCORES.TEST_NUMBER]
	,[XTBL_TEST_SCORES.TEST_RAW_SCORE]
	,[XTBL_TEST_SCORES.TEST_PRIMARY_RESULT]
	,[XTBL_TEST_SCORES.TEST_SECONDARY_RESULT]
FROM
(
SELECT
	ROW_NUMBER () OVER (PARTITION BY STUDENT_ID ORDER BY Overall_ADMIN_DATE DESC) AS RN
	,'ISTATION'+ Overall_ADMIN_DATE + STUDENT_ID AS [XTBL_TEST_ADMIN.PROD_TEST_ID]
	,'001' AS [XTBL_TEST_ADMIN.DISTRICT_CODE]
	,STUDENT_ID AS [XTBL_TEST_ADMIN.DISTRICT_STUDENT_ID]
	,CASE WHEN ISTA.DOMAIN = IDC.DOMAIN THEN IDC.loc_num ELSE ISTA.DOMAIN
	END AS [XTBL_TEST_ADMIN.DISTRICT_SCHOOL_ID]
	,'BOY' AS [XTBL_TEST_ADMIN.TEST_ADMIN_PERIOD]
	,Overall_ADMIN_DATE AS [XTBL_TEST_ADMIN.TEST_ADMIN_DATE_STR]
	,LNAME AS [XTBL_TEST_ADMIN.STUDENT_LAST_NAME]
	,FNAME AS [XTBL_TEST_ADMIN.STUDENT_FIRST_NAME]
	,[LANGUAGE] AS [XTBL_TEST_ADMIN.TEST_LANGUAGE]


	,'ISTATION' AS [XTBL_TESTS.TEST_NUMBER]
	,'001' AS [XTBL_TESTS.DISTRICT_CODE]
	,'COMPOSITE' AS [XTBL_TESTS.TEST_CLASS]
	,'ISTATION' AS [XTBL_TESTS.TEST_NAME]
	,'ELA' AS [XTBL_TESTS.TEST_SUBJECT]
	,'ISTATION' AS [XTBL_TESTS.TEST_VENDOR]
	,'ISTATION' AS [XTBL_TESTS.TEST_PRODUCT]
	,'READING' AS [XTBL_TESTS.TEST_GROUP]
	,datename (m, overall_admin_date) AS [XTBL_TESTS.TEST_VERSION]


	,'ISTATION' AS [XTBL_TEST_SCORES.TEST_NUMBER]
	,ROUND (Overall_SCORE,2) AS [XTBL_TEST_SCORES.TEST_RAW_SCORE]
	,Overall_TIER AS [XTBL_TEST_SCORES.TEST_PRIMARY_RESULT]
	,datename (m, overall_admin_date) AS [XTBL_TEST_SCORES.TEST_SECONDARY_RESULT]

FROM
	ISTATION_2016_2017 AS ISTA
	LEFT JOIN
	istation_domain_crosswalk AS IDC
	ON IDC.domain = ISTA.DOMAIN
WHERE Overall_ADMIN_DATE > '1'
) AS T1
WHERE 1 = 1
AND RN = 1
ORDER BY  [XTBL_TEST_ADMIN.DISTRICT_STUDENT_ID]