SELECT 
	NA.[STUDENT NAME]
	,NA.[PERM ID]
	,NA.[ETHNIC CODE]
	,NA.[GRADE]
	,NA.SCHOOL
	,NA.[Tribal Community]
	,NA.[506]
	,NA.[Cert Indian Blood]
	,NA.DateSigned
	,NA.Address
	,NA.[City, State Zip]
	,NA.Phone
	,PARCC.TEST_NAME
	,PARCC.SCORE
	,PARCC.PERFORMANCE_LEVEL
FROM
[APS_2015-2016 Native American students 062716 (002)] AS NA

LEFT JOIN 
(
SELECT 
    STUDENT_ID AS SIS_NUMBER
    ,DTBL_STUDENTS.STUDENT_GRADUATION_COHORT
    ,TEST_NAME
       ,TEST_EXTERNAL_CODE AS TEST_WINDOW
                                ,DTBL_SCHOOLS.SCHOOL_CODE
    ,TEST_STUDENT_GRADE
       ,YEAR_VALUE AS YEAR
    ,TEST_PRODUCT 
    ,TEST_SUBJECT AS CONTENT_AREA
    ,DTBL_CALENDAR_DATES.DATE_VALUE AS TEST_DATE
    ,TEST_SCORE_VALUE AS SCORE
    ,TEST_PRIMARY_RESULT AS PERFORMANCE_LEVEL
	,SIS_SCHOOL_YEAR
    ,TEST_CLASS
    ,TEST_GROUP
    ,TEST_SUBGROUP
    ,TEST_ADMIN_PERIOD
FROM K12INTEL_DW.FTBL_TEST_SCORES
INNER JOIN K12INTEL_DW.DTBL_TESTS
ON DTBL_TESTS.TESTS_KEY = FTBL_TEST_SCORES.TESTS_KEY 
INNER JOIN K12INTEL_DW.DTBL_STUDENTS 
ON DTBL_STUDENTS.STUDENT_KEY = FTBL_TEST_SCORES.STUDENT_KEY 
INNER JOIN K12INTEL_DW.DTBL_SCHOOLS
ON DTBL_SCHOOLS.SCHOOL_KEY = FTBL_TEST_SCORES.SCHOOL_KEY
INNER JOIN K12INTEL_DW.DTBL_CALENDAR_DATES
ON DTBL_CALENDAR_DATES.CALENDAR_DATE_KEY= FTBL_TEST_SCORES.CALENDAR_DATE_KEY
INNER JOIN K12INTEL_DW.DTBL_SCHOOL_DATES
ON DTBL_SCHOOL_DATES.SCHOOL_DATES_KEY = FTBL_TEST_SCORES.SCHOOL_DATES_KEY 
WHERE 1 = 1
--AND TEST_PRODUCT = 'DIBELS Next'
--AND TEST_SUBJECT = 'MATHEMATICS'
AND TEST_GROUP IN ('Algebra II','Geometry','Mathematics','Algebra I','Integrated Mathematics II','Integrated Mathematics','Integrated Mathematics III')
AND TEST_NAME LIKE '%OVERALL%'
AND TEST_NAME LIKE 'PARCC%'
--AND TEST_SUBGROUP IN ('TOT','Composite')
--AND LOCAL_SCHOOL_YEAR = '2015-2016'
--AND STUDENT_ID = '970042832'
) AS PARCC
ON PARCC.SIS_NUMBER = NA.[Perm ID]
ORDER BY SCORE