
BEGIN TRAN

INSERT INTO K12INTEL_USERDATA.XTBL_TESTS
	  (
	  [TEST_NUMBER]
      ,[DISTRICT_CODE]
      ,[TEST_CLASS]
      ,[TEST_NAME]
      ,[TEST_SHORT_NAME]
      ,[TEST_GROUP]
      ,[TEST_SUBGROUP]
      ,[TEST_TYPE]
      ,[TEST_SUBJECT]
      ,[COURSES_SUBJECT]
      ,[CURRICULUM_CODE]
      ,[TEST_GRADE_GROUP]
      ,[TEST_METHOD]
      ,[TEST_EXTERNAL_CODE]
      ,[TEST_GROUP_LEVEL_1]
      ,[TEST_GROUP_LEVEL_2]
      ,[TEST_GROUP_LEVEL_3]
      ,[TEST_GROUP_LEVEL_4]
      ,[TEST_STATUS]
      ,[TEST_VENDOR]
      ,[TEST_PRODUCT]
      ,[TEST_VERSION]
      ,[TEST_SORT_ORDER]
      ,[TEST_ALPHA_SORT]
      ,[TEST_DESCRIPTION]
      ,[TEST_SCORE_FACTOR]
      ,[ETL_REF_BNCH_TYPE]
      ,[ETL_REF_BNCH_TEST_NUMBER]
      ,[ETL_REF_BNCH_ADMIN_PERIOD]
      ,[ETL_REF_BNCH_SUBJECT]
      ,[ETL_REF_BNCH_GRADE_GROUP]
      ,[ETL_REF_BNCH_MEASURE]
      ,[ETL_CUST_BNCH_TYPE]
      ,[ETL_CUST_BNCH_TEST_NUMBER]
      ,[ETL_CUST_BNCH_ADMIN_PERIOD]
      ,[ETL_CUST_BNCH_SUBJECT]
      ,[ETL_CUST_BNCH_GRADE_GROUP]
      ,[ETL_CUST_BNCH_MEASURE]
      ,[ATTENTION_REQUIRED]
      ,[APPROVE_FOR_ETL_IND]
      ,[TEST_UUID]
      ,[MOD_USER]
      ,[MOD_DATE]
	  )
SELECT
	'ISTATION' AS TEST_NUMBER
	,'001' AS DISTRICT_CODE
	,'COMOPOSITE' AS TEST_CLASS
	,'ISTATION' AS TEST_NAME
	,'--' AS TEST_SHORT_NAME
	,'ELA' AS TEST_GROUP
	,'--' AS TEST_SUBGROUP
	,'Standardized' AS TEST_TYPE
	,'ELA' AS TEST_SUBJECT
	,'--' AS COURSES_SUBJECT
	,'--' AS CURRICULUM_CODE
	,'--' AS TEST_GRADE_GROUP
	,'--' AS TEST_METHOD
	,'--' AS TEST_EXTERNAL_CODE
	,'--' AS TEST_GROUP_LEVEL_1
	,'--' AS TEST_GROUP_LEVEL_2
	,'--' AS TEST_GROUP_LEVEL_3
	,'--' AS TEST_GROUP_LEVEL_4
	,'1' AS TEST_STATUS
	,'ISTATION' AS TEST_VENDOR
	,'ISTATION' AS TEST_PRODUCT
	,'' AS TEST_VERSION
	,'' AS TEST_SORT_ORDER
	,'1' AS TEST_ALPHA_SORT
	,'ISTATION' AS TEST_DESCRIPTION
	,'1.0000' AS TEST_SCORE_FACT
    ,'' AS [ETL_REF_BNCH_TYPE]
    ,'N' AS [ETL_REF_BNCH_TEST_NUMBER]
    ,'N' AS [ETL_REF_BNCH_ADMIN_PERIOD]
    ,'N' AS [ETL_REF_BNCH_SUBJECT]
    ,'N' AS [ETL_REF_BNCH_GRADE_GROUP]
    ,'' AS [ETL_REF_BNCH_MEASURE]
    ,'' AS [ETL_CUST_BNCH_TYPE]
    ,'N' AS [ETL_CUST_BNCH_TEST_NUMBER]
    ,'N' AS [ETL_CUST_BNCH_ADMIN_PERIOD]
    ,'N' AS [ETL_CUST_BNCH_SUBJECT]
    ,'N' AS [ETL_CUST_BNCH_GRADE_GROUP]
    ,'' AS [ETL_CUST_BNCH_MEASURE]
    ,'N' AS [ATTENTION_REQUIRED]
    ,'Y' AS [APPROVE_FOR_ETL_IND]
    ,NEWID() AS [TEST_UUID]
    ,'VERSIFIT' AS [MOD_USER]
    ,GETDATE() AS[MOD_DATE]


ROLLBACK
