SELECT * FROM K12INTEL_USERDATA.XTBL_TEST_BATCH_IDS batch
WHERE BATCH_NAME LIKE '%sat%'


SELECT scores.*
FROM K12INTEL_DW.DTBL_TESTS tests WITH (NOLOCK)
INNER JOIN K12INTEL_DW.FTBL_TEST_SCORES scores WITH (NOLOCK)
    ON tests.TESTS_KEY = scores.TESTS_KEY
WHERE 1=1
	AND tests.TEST_PRODUCT = 'sat'
	--AND CONVERT(DATE, scores.SYS_CREATED) = '04/26/2016'
	ORDER BY TEST_ADMIN_CODE

