declare @AsOfDate datetime2 = '2016-12-01'


SELECT DISTINCT 
PRIM.Non_Primary_School,STU.SIS_NUMBER, STU.STATE_STUDENT_NUMBER, 

PRIM.GRADE, 
SCH.ORGANIZATION_NAME AS SCHEDULE_SCHOOL,
SCH.COURSE_ID, SECTION_ID, COURSE_TITLE, COURSE_ENTER_DATE, COURSE_LEAVE_DATE, TERM_CODE,
SSY.ENR_USER_DD_4,
SCH.ORGANIZATION_GU

FROM 
APS.OpenNonPrimaryEnrollments AS PRIM
LEFT JOIN 
APS.PrimaryEnrollmentDetailsAsOf(@AsOfDate) AS ADA
ON
PRIM.STUDENT_GU = ADA.STUDENT_GU

INNER JOIN 
rev.EPC_STU AS STU
ON 
PRIM.STUDENT_GU = STU.STUDENT_GU
INNER JOIN 
APS.ScheduleDetailsAsOf(@AsOfDate) AS SCH
ON
PRIM.STUDENT_GU = SCH.STUDENT_GU

INNER JOIN 
rev.EPC_STU_SCH_YR AS SSY
ON
PRIM.STUDENT_SCHOOL_YEAR_GU = SSY.STUDENT_SCHOOL_YEAR_GU


WHERE
ADA.STUDENT_GU IS NULL

AND ORGANIZATION_GU LIKE @School

ORDER BY SIS_NUMBER, SCHEDULE_SCHOOL, COURSE_ID
