



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[ENROLL_2015].[SCHOOL_CODE]
	,[ENROLL_2015].[SCHOOL_NAME] 
	,[ENROLL_2015].[SCHOOL_YEAR]
	,[ENROLL_2015].[GRADE]
	,[ENROLL_2015].[ENTER_DATE]
	,[ENROLL_2015].[LEAVE_DATE]
	,[ENROLL_2015].[LEAVE_DESCRIPTION]
	,[ENROLL_2015].ELA_TEACHER_NAME
	,[ENROLL_2015].COURSE_TITLE
	,''
	,[ENROLL_2016].[SCHOOL_CODE]
	,[ENROLL_2016].[SCHOOL_NAME]
	,[ENROLL_2016].[SCHOOL_YEAR]
	,[ENROLL_2016].[GRADE]
	,[ENROLL_2016].[ENTER_DATE]
	,[ENROLL_2016].[LEAVE_DATE]
	,[ENROLL_2016].[LEAVE_DESCRIPTION]
	,[ENROLL_2016].ELA_TEACHER_NAME
	,[ENROLL_2016].COURSE_TITLE
FROM
	(
	SELECT
		ENROLLMENT.SIS_NUMBER
		,SCHOOL_CODE
		,SCHOOL_NAME
		,ENTER_DATE
		,ENTER_CODE
		,ENTER_DESCRIPTION
		,LEAVE_DATE
		,LEAVE_CODE
		,LEAVE_DESCRIPTION
		,SUMMER_WITHDRAWL_CODE
		,SUMMER_WITHDRAWL_DATE
		,YEAR_END_STATUS
		,GRADE
		,LIST_ORDER
		,EXCLUDE_ADA_ADM
		,ACCESS_504
		,ENROLLMENT.SCHOOL_YEAR
		,EXTENSION
		,STUDENT_GU
		,STUDENT_SCHOOL_YEAR_GU
		,ORGANIZATION_YEAR_GU
		,ORGANIZATION_GU
		,ENROLLMENT.YEAR_GU
		,HOMEROOM_SECTION_GU
		,TCH.SCHOOL_YEAR AS TCH_SCHOOL_YEAR
		,TCH.DEPARTMENT
		,TCH.COURSE_ID
		,TCH.ELA_TEACHER_NAME
		,TCH.COURSE_TITLE
	FROM
		APS.StudentEnrollmentDetails AS [ENROLLMENT]
		LEFT JOIN 
			(
			SELECT  
			SCH.SIS_NUMBER
			,SCH.COURSE_ID
			,SCH.COURSE_TITLE 
			,SCH.PERIOD_BEGIN
			,SCH.PERIOD_END
			,SCH.YEAR_GU
			,SCH.PRIMARY_STAFF
			,YR.SCHOOL_YEAR
			,PER.FIRST_NAME
			,PER.LAST_NAME
			,PER.LAST_NAME + ', '+PER.FIRST_NAME AS ELA_TEACHER_NAME
			,ST.BADGE_NUM
			,PER.EMAIL
			,SCH.DEPARTMENT
			,CAST(replace(lower(st.BADGE_NUM), 'e', '')AS VARCHAR(9)) AS EMP_ID
			,SCH.ORGANIZATION_NAME
	
			FROM 
			APS.ScheduleDetailsAsOf ('2016-05-10') AS SCH 

			LEFT JOIN
			REV.REV_YEAR AS YR
			ON YR.YEAR_GU = SCH.YEAR_GU

			LEFT JOIN
			REV.REV_PERSON AS PER
			ON SCH.STAFF_GU = PER.PERSON_GU

			LEFT JOIN 
			REV.EPC_STAFF AS ST
			ON PER.PERSON_GU = ST.STAFF_GU
			WHERE 1 = 1
			AND SCHOOL_YEAR = '2015'
			AND DEPARTMENT = 'ENG'
			AND PERIOD_BEGIN = 1
			AND PRIMARY_STAFF = 1
			) AS TCH
		ON
		ENROLLMENT.SIS_NUMBER = TCH.SIS_NUMBER
		AND TCH.ORGANIZATION_NAME = ENROLLMENT.SCHOOL_NAME
		
	WHERE
		[ENROLLMENT].[SCHOOL_YEAR] = '2015'
		AND [ENROLLMENT].[EXTENSION] = 'R'
		--AND [ENROLLMENT].[GRADE] IN ('05','08')
		AND [ENROLLMENT].[ENTER_DATE] IS NOT NULL
		AND [ENROLLMENT].[EXCLUDE_ADA_ADM] IS NULL
	) AS [ENROLL_2015]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLL_2015].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	(
	SELECT
		ENROLLMENT.SIS_NUMBER
		,SCHOOL_CODE
		,SCHOOL_NAME
		,ENTER_DATE
		,ENTER_CODE
		,ENTER_DESCRIPTION
		,LEAVE_DATE
		,LEAVE_CODE
		,LEAVE_DESCRIPTION
		,SUMMER_WITHDRAWL_CODE
		,SUMMER_WITHDRAWL_DATE
		,YEAR_END_STATUS
		,GRADE
		,LIST_ORDER
		,EXCLUDE_ADA_ADM
		,ACCESS_504
		,ENROLLMENT.SCHOOL_YEAR
		,EXTENSION
		,STUDENT_GU
		,STUDENT_SCHOOL_YEAR_GU
		,ORGANIZATION_YEAR_GU
		,ORGANIZATION_GU
		,ENROLLMENT.YEAR_GU
		,HOMEROOM_SECTION_GU
		,TCH.SCHOOL_YEAR AS TCH_SCHOOL_YEAR
		,TCH.DEPARTMENT
		,TCH.COURSE_ID
		,TCH.ELA_TEACHER_NAME
		,TCH.COURSE_TITLE
	FROM
		APS.StudentEnrollmentDetails AS [ENROLLMENT]
		LEFT JOIN 
			(
			SELECT  
			SCH.SIS_NUMBER
			,SCH.COURSE_ID
			,SCH.COURSE_TITLE 
			,SCH.PERIOD_BEGIN
			,SCH.PERIOD_END
			,SCH.YEAR_GU
			,SCH.PRIMARY_STAFF
			,YR.SCHOOL_YEAR
			,PER.FIRST_NAME
			,PER.LAST_NAME
			,PER.LAST_NAME + ', '+PER.FIRST_NAME AS ELA_TEACHER_NAME
			,ST.BADGE_NUM
			,PER.EMAIL
			,SCH.DEPARTMENT
			,CAST(replace(lower(st.BADGE_NUM), 'e', '')AS VARCHAR(9)) AS EMP_ID
			,SCH.ORGANIZATION_NAME
	
			FROM 
			APS.ScheduleDetailsAsOf (GETDATE()) AS SCH 

			LEFT JOIN
			REV.REV_YEAR AS YR
			ON YR.YEAR_GU = SCH.YEAR_GU

			LEFT JOIN
			REV.REV_PERSON AS PER
			ON SCH.STAFF_GU = PER.PERSON_GU

			LEFT JOIN 
			REV.EPC_STAFF AS ST
			ON PER.PERSON_GU = ST.STAFF_GU
			WHERE 1 = 1
			AND SCHOOL_YEAR = '2016'
			AND DEPARTMENT = 'ENG'
			AND PERIOD_BEGIN = 1
			AND PRIMARY_STAFF = 1
			) AS TCH
		ON
		ENROLLMENT.SIS_NUMBER = TCH.SIS_NUMBER
		AND TCH.ORGANIZATION_NAME = ENROLLMENT.SCHOOL_NAME

		
	WHERE
		[ENROLLMENT].[SCHOOL_YEAR] = '2016'
		AND [ENROLLMENT].[EXTENSION] = 'R'
		--AND [ENROLLMENT].[GRADE] IN ('05','08')
		AND [ENROLLMENT].[ENTER_DATE] IS NOT NULL
		AND [ENROLLMENT].[EXCLUDE_ADA_ADM] IS NULL
	) AS [ENROLL_2016]
	ON
	[ENROLL_2015].[STUDENT_GU] = [ENROLL_2016].[STUDENT_GU]


	ORDER BY SIS_NUMBER