
SELECT
	SCHOOL_YEAR
	,Organization.ORGANIZATION_NAME
	,Student.SIS_NUMBER
	,Person.LAST_NAME
	,Person.FIRST_NAME
	,Person.MIDDLE_NAME
	,GradeLevel.VALUE_DESCRIPTION AS GRADE
	,HIST.COURSE_ID
	,HIST.COURSE_TITLE
	,HIST.MARK

FROM
	rev.EPC_STU_SCH_YR AS SSY
	INNER JOIN
	rev.REV_ORGANIZATION_YEAR AS OrgYear
	ON
	SSY.ORGANIZATION_YEAR_GU = OrgYear.ORGANIZATION_YEAR_GU
	
	INNER JOIN
	rev.EPC_STU AS Student
	ON
	SSY.STUDENT_GU = Student.STUDENT_GU

	LEFT JOIN
	APS.LookupTable('K12','Grade') AS GradeLevel
	ON
	SSY.GRADE = GradeLevel.VALUE_CODE

	INNER JOIN
	rev.REV_ORGANIZATION AS Organization
	ON
	OrgYear.ORGANIZATION_GU = Organization.ORGANIZATION_GU

	INNER JOIN
	rev.REV_PERSON As Person
	ON
	SSY.STUDENT_GU = Person.PERSON_GU

	INNER JOIN
	rev.EPC_STU_CRS_HIS AS HIST
	ON
	Student.STUDENT_GU = HIST.STUDENT_GU

	WHERE
	SCHOOL_YEAR = 2013
	AND COURSE_ID IN ('10043DE', '48010DE')
	AND VALUE_DESCRIPTION = '08'

	ORDER BY 
	ORGANIZATION_NAME, SIS_NUMBER, COURSE_ID