
/***********************************************************************************************

THREE HOUR HERITAGE FOR NON EL STUDENTS

--HERITAGE 3 HOUR IS ONLY FOR THE REST OF THE SCHOOLS THAT ARE NOT IN THIS LIST:  
NOT IN ('206', '210', '213', '215', '216', '225', '339', '243', '244', '249', '252', '262', '255',
 '496', '285', '291', '300', '250', '327', '275', '333', '330', '392', '280', '370', '376', '379', '385', 
 '405', '450', '415', '416', '475', '465', '470', '590', '576' )

*************************************************************************************************/


SELECT 
	T6.ORGANIZATION_NAME, T6.SIS_NUMBER, T6.COURSE_ID, T6.COURSE_TITLE, T6.COURSE_LEVEL, T6.STATE_COURSE_CODE,
	T6.LAST_NAME AS TEACHER_LAST_NAME, T6.FIRST_NAME AS TEACHER_FIRST_NAME, T6.CRD00, T6.CRD01, T6.CRD02,
	T6.CRD03, T6.CRD08, T6.CRD09, T6.CRD10, T6.CRD10, T6.CRD20, T6.CRD24, T6.CRD27, T6.CRD32, T6.CRD43,
	T6.CRD45, T6.CRD47, T6.CRD51, T6.CRD52, T6.CRD60, T6.CRD64, T6.CRD67, T6.CRD72, T6.CRD82, T6.CRD90,	
	CONVERT(VARCHAR(101),T6.DATE_ACQUIRED,101) AS DATE_ACQUIRED
FROM (
SELECT * FROM 
(
SELECT 
	STUDENT_GU, SIS_NUMBER, MAX(RN) AS MAXCOUNT 
FROM( 
--THIS IS BOTH T1 AND T2
SELECT 
	T2.STUDENT_GU, T2.SIS_NUMBER
	,ROW_NUMBER() OVER (PARTITION BY SIS_NUMBER, COURSE_LEVEL ORDER BY STATE_COURSE_CODE) AS RN
FROM 
(
-------------------------------------------------------------------------------------------------
--FIRST PULL NON ELL STUDENTS THAT HAVE A BEP TAGGED COURSE BETWEEN 1274-1274 STATE COURSE CODES
-------------------------------------------------------------------------------------------------

SELECT DISTINCT PRIM.STUDENT_GU
 FROM 
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS PRIM
LEFT JOIN 
APS.ELLCalculatedAsOf(GETDATE()) AS ELL
ON
PRIM.STUDENT_GU = ELL.STUDENT_GU
LEFT JOIN 
APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
ON
PRIM.STUDENT_GU = SCH.STUDENT_GU
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU
WHERE
LST.COURSE_LEVEL = 'BEP'
AND LEFT(CRS.STATE_COURSE_CODE,4) BETWEEN '1271' AND '1274'
-- non-EL STUDENTS
AND ELL.STUDENT_GU IS NULL

--HERITAGE 3 HOUR IS ONLY FOR THE FOLLOWING SCHOOLS
AND PRIM.SCHOOL_CODE NOT IN ('206', '210', '213', '215', '216', '225', '339', '243', '244', '249', '252', '262', '255',
 '496', '285', '291', '300', '250', '327', '275', '333', '330', '392', '280', '370', '376', '379', '385', 
 '405', '450', '415', '416', '475', '465', '470', '590', '576' )


) AS T1

--6,173 ROWS

-------------------------------------------------------------------------------------------------
--FOR STUDENTS ABOVE PULL ALL BEP CLASSES THEN FILTER FOR STUDENTS THAT HAVE 3 TOTAL
-------------------------------------------------------------------------------------------------

INNER JOIN 
(
SELECT 
	STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE
 FROM 

APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU
WHERE
COURSE_LEVEL IN ('BEP')

) AS T2
ON
T1.STUDENT_GU = T2.STUDENT_GU
) AS T3
GROUP BY STUDENT_GU, SIS_NUMBER

) AS T4

WHERE
	MAXCOUNT > 2
) AS T5

---------------------------------------------------------------------------------------------------
----FOR STUDENTS ABOVE THAT HAVE MORE THAN 2 OTHER BEP COURSES PULL DETAILS
---------------------------------------------------------------------------------------------------

INNER JOIN 
(
SELECT
	ROW_NUMBER() OVER(PARTITION BY SIS_NUMBER, SCH.COURSE_ID ORDER BY SIS_NUMBER) AS RN,
	ORGANIZATION_NAME,
	STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE,
	PER.LAST_NAME, PER.FIRST_NAME,
	TC.CRD00, TC.CRD01, TC.CRD02,
	TC.CRD03, TC.CRD04, TC.CRD05, TC.CRD07, TC.CRD08, TC.CRD09, TC.CRD10, TC.CRD20, TC.CRD24, TC.CRD27, TC.CRD32, TC.CRD43,
	TC.CRD45, TC.CRD47, TC.CRD51, TC.CRD52, TC.CRD60, TC.CRD64, TC.CRD67, TC.CRD72, TC.CRD82, TC.CRD90, TC.DATE_ACQUIRED
 FROM 

APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU
INNER JOIN
REV.EPC_STAFF STF
ON
STF.STAFF_GU = SCH.STAFF_GU
LEFT JOIN
REV.REV_PERSON PER
ON
PER.PERSON_GU = SCH.STAFF_GU
LEFT JOIN
[180-SMAXODS-01.APS.EDU.ACTD].[LAWSON].aps.TeacherCredentials TC
on
STF.BADGE_NUM = TC.BADGE_NUMBER
WHERE
COURSE_LEVEL IN ('BEP')


) AS T6

ON
T5.STUDENT_GU = T6.STUDENT_GU

INNER JOIN 
REV.REV_PERSON AS PERS
ON
T6.STUDENT_GU = PERS.PERSON_GU
WHERE RN = 1
ORDER BY ORGANIZATION_NAME,SIS_NUMBER, STATE_COURSE_CODE