

/***********************************************************************************************

ONE HOUR HERITAGE FOR NON EL STUDENTS


*************************************************************************************************/

-------------------------------------------------------------------------------------------------
--FIRST PULL NON-ELL STUDENTS THAT HAVE A BEP TAGGED COURSE BETWEEN 1274-1274 STATE COURSE CODES

-------------------------------------------------------------------------------------------------

SELECT 
	T1.SCHOOL_NAME, T1.SIS_NUMBER, PERS.LAST_NAME, PERS.FIRST_NAME, T1.COURSE_ID, T1.COURSE_TITLE, T1.COURSE_LEVEL, T1.STATE_COURSE_CODE,
	T1.LAST_NAME AS TEACHER_LAST_NAME, T1.FIRST_NAME AS TEACHER_FIRST_NAME, T1.CRD00, T1.CRD01, T1.CRD02,
	T1.CRD03, T1.CRD08, T1.CRD09, T1.CRD10, T1.CRD10, T1.CRD20, T1.CRD24, T1.CRD27, T1.CRD32, T1.CRD43,
	T1.CRD45, T1.CRD47, T1.CRD51, T1.CRD52, T1.CRD60, T1.CRD64, T1.CRD67, T1.CRD72, T1.CRD82, T1.CRD90,	
	CONVERT(VARCHAR(101),T1.DATE_ACQUIRED,101) AS DATE_ACQUIRED	
	--T1.*, PERS.LAST_NAME, PERS.FIRST_NAME		
FROM 
(
SELECT

	ROW_NUMBER() OVER(PARTITION BY SIS_NUMBER, SCH.COURSE_ID ORDER BY SIS_NUMBER) AS RN,
	SCHOOL_NAME,
	PRIM.STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE,
	PER.LAST_NAME, PER.FIRST_NAME,
	TC.CRD00, TC.CRD01, TC.CRD02,
	TC.CRD03, TC.CRD04, TC.CRD05, TC.CRD07, TC.CRD08, TC.CRD09, TC.CRD10, TC.CRD20, TC.CRD24, TC.CRD27, TC.CRD32, TC.CRD43,
	TC.CRD45, TC.CRD47, TC.CRD51, TC.CRD52, TC.CRD60, TC.CRD64, TC.CRD67, TC.CRD72, TC.CRD82, TC.CRD90, TC.DATE_ACQUIRED
 
	--PRIM.SCHOOL_CODE, SCHOOL_NAME,
	--PRIM.STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE
 FROM 
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS PRIM
LEFT JOIN 
APS.ELLCalculatedAsOf(GETDATE()) AS ELL
ON
PRIM.STUDENT_GU = ELL.STUDENT_GU
LEFT JOIN 
APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
ON
PRIM.STUDENT_GU = SCH.STUDENT_GU
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU
INNER JOIN
REV.EPC_STAFF STF
ON
STF.STAFF_GU = SCH.STAFF_GU
LEFT JOIN
REV.REV_PERSON PER
ON
PER.PERSON_GU = SCH.STAFF_GU
LEFT JOIN
[180-SMAXODS-01.APS.EDU.ACTD].[LAWSON].aps.TeacherCredentials TC
on
STF.BADGE_NUM = TC.BADGE_NUMBER


WHERE
LST.COURSE_LEVEL = 'BEP'
AND LEFT(CRS.STATE_COURSE_CODE,4) BETWEEN '1271' AND '1274'
-- non-EL STUDENTS
AND ELL.STUDENT_GU IS NULL
) AS T1

---------------------------------------------------------------------------------------------------------------
-- REMOVE STUDENTS ABOVE IF THEY HAVE ANY OTHER COURSES TAGGED BEP AND/OR ESL THAT IS NOT IN THE COURSE CODE RANGE
---------------------------------------------------------------------------------------------------------------

LEFT JOIN 
(SELECT DISTINCT RESTOFSCH.STUDENT_GU 
FROM
APS.ScheduleDetailsAsOf(GETDATE()) AS RESTOFSCH
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
RESTOFSCH.COURSE_GU = LST.COURSE_GU
AND LST.COURSE_LEVEL IN ('BEP', 'ESL') 
INNER JOIN 
REV.EPC_CRS AS CRS2
ON
RESTOFSCH.COURSE_GU = CRS2.COURSE_GU
AND LEFT(CRS2.STATE_COURSE_CODE,4) NOT BETWEEN '1271' AND '1274'


) AS T2

ON
T1.STUDENT_GU = T2.STUDENT_GU
INNER JOIN 
REV.REV_PERSON AS PERS
ON
T1.STUDENT_GU = PERS.PERSON_GU


WHERE
T2.STUDENT_GU IS NULL
AND RN = 1


ORDER BY SCHOOL_NAME, SIS_NUMBER




