

/***********************************************************************************************

THREE HOUR HERITAGE FOR EL STUDENTS

--HERITAGE 3 HOUR IS ONLY FOR SCHOOLS NOT IN LIST BELOW:  

('206', '210', '213', '215', '216', '225', '339', '243', '244', '249', '252', '262', '255',
 '496', '285', '291', '300', '250', '327', '275', '333', '330', '392', '280', '370', '376', '379', '385', 
 '405', '450', '415', '416', '475', '465', '470', '590', '576' )

*************************************************************************************************/

SELECT ORGANIZATION_NAME, T7.SIS_NUMBER, COURSE_ID, COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE,
	   pers.LAST_NAME, pers.FIRST_NAME, STAFF_GU, T7.FIRST_NAME as TEACHER_FIRST_NAME, T7.LAST_NAME AS TEACHER_LAST_NAME, T7.CRD00, CRD01, CRD02, CRD03,
	   CRD04, CRD05, CRD07, CRD08, CRD09, CRD10, CRD20, CRD24, CRD27, CRD32, CRD43, CRD45, CRD47, CRD51, CRD52, CRD60, CRD64, CRD67, CRD72, 
	   CRD82, CRD90, CONVERT(VARCHAR(101),T7.DATE_ACQUIRED,101) AS DATE_ACQUIRED
FROM
 (
SELECT 
	DISTINCT STUDENT_GU
FROM( 
SELECT 
	T4.*
	,ROW_NUMBER() OVER (PARTITION BY SIS_NUMBER, COURSE_LEVEL ORDER BY COURSE_LEVEL, STATE_COURSE_CODE) AS RN
 FROM
(

-------------------------------------------------------------------------------------------------
--FIRST PULL ELL STUDENTS THAT HAVE A BEP TAGGED COURSE BETWEEN 1274-1274 STATE COURSE CODES
-------------------------------------------------------------------------------------------------

SELECT DISTINCT PRIM.STUDENT_GU
	--PRIM.STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE
 FROM 
APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS PRIM
INNER JOIN 
APS.ELLCalculatedAsOf(GETDATE()) AS ELL
ON
PRIM.STUDENT_GU = ELL.STUDENT_GU

INNER JOIN 
APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
ON
PRIM.STUDENT_GU = SCH.STUDENT_GU
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU
WHERE
(LST.COURSE_LEVEL = 'BEP'
AND LEFT(CRS.STATE_COURSE_CODE,4) BETWEEN '1271' AND '1274')
--HERITAGE 3 HOUR IS ONLY FOR THE FOLLOWING SCHOOLS
AND PRIM.SCHOOL_CODE NOT IN ('206', '210', '213', '215', '216', '225', '339', '243', '244', '249', '252', '262', '255',
 '496', '285', '291', '300', '250', '327', '275', '333', '330', '392', '280', '370', '376', '379', '385', 
 '405', '450', '415', '416', '475', '465', '470', '590', '576' )
) AS T1

---------------------------------------------------------------------------------------------------------------
-- AND STUDENTS HAVE TO HAVE A COURSE TAGGED ESL
---------------------------------------------------------------------------------------------------------------

INNER JOIN 
(SELECT DISTINCT RESTOFSCH.STUDENT_GU AS ESLGU
FROM
APS.ScheduleDetailsAsOf(GETDATE()) AS RESTOFSCH
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
RESTOFSCH.COURSE_GU = LST.COURSE_GU
AND LST.COURSE_LEVEL IN ('ESL') 
INNER JOIN 
REV.EPC_CRS AS CRS2
ON
RESTOFSCH.COURSE_GU = CRS2.COURSE_GU
) AS T2

ON
T1.STUDENT_GU = T2.ESLGU

---------------------------------------------------------------------------------------------------------------
-- AND STUDENTS HAVE TO HAVE ONE *OTHER* BEP COURSE TAGGED
---------------------------------------------------------------------------------------------------------------

INNER JOIN 
(SELECT DISTINCT RESTOFSCH.STUDENT_GU AS BEPGU
FROM
APS.ScheduleDetailsAsOf(GETDATE()) AS RESTOFSCH
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
RESTOFSCH.COURSE_GU = LST.COURSE_GU
AND LST.COURSE_LEVEL IN ('BEP') 
INNER JOIN 
REV.EPC_CRS AS CRS2
ON
RESTOFSCH.COURSE_GU = CRS2.COURSE_GU
) AS T3

ON
T2.ESLGU = T3.BEPGU


---------------------------------------------------------------------------------------------------
----FOR STUDENTS ABOVE THAT HAVE ALL 3 CONDITIONS PULL ALL THEIR BEP AND ESL CLASSES AND COUNT THEM
---------------------------------------------------------------------------------------------------

INNER JOIN 
(
SELECT 
	STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE
 FROM 

APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU
WHERE
COURSE_LEVEL IN ('BEP', 'ESL')

) AS T4

ON
T3.BEPGU = T4.STUDENT_GU
) AS T5
--STUDENTS ALL HAVE ESL SO CHOOSE STUDENTS THAT HAVE MORE THAN ONE BEP ROW
WHERE
	COURSE_LEVEL = 'BEP' AND RN >2

) AS T6

---------------------------------------------------------------------------------------------------
----FOR STUDENTS ABOVE THAT HAVE ALL 3 CONDITIONS AND MORE THAN 2 BEP CLASSES PULL DETAILS
---------------------------------------------------------------------------------------------------

INNER JOIN 
(
SELECT 

	ROW_NUMBER() OVER(PARTITION BY SIS_NUMBER, SCH.COURSE_ID ORDER BY SIS_NUMBER) AS RN,

    SCH.ORGANIZATION_NAME,
    STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE, SCH.STAFF_GU,
	PER.LAST_NAME, PER.FIRST_NAME,
	TC.CRD00, TC.CRD01, TC.CRD02,
	TC.CRD03, TC.CRD04, TC.CRD05, TC.CRD07, TC.CRD08, TC.CRD09, TC.CRD10, TC.CRD20, TC.CRD24, TC.CRD27, TC.CRD32, TC.CRD43,
	TC.CRD45, TC.CRD47, TC.CRD51, TC.CRD52, TC.CRD60, TC.CRD64, TC.CRD67, TC.CRD72, TC.CRD82, TC.CRD90, TC.DATE_ACQUIRED

	--ORGANIZATION_NAME,
	--STUDENT_GU, SIS_NUMBER, SCH.COURSE_ID, SCH.COURSE_TITLE, COURSE_LEVEL, STATE_COURSE_CODE
 FROM 

APS.ScheduleDetailsAsOf(GETDATE()) AS SCH
INNER JOIN 
rev.EPC_CRS_LEVEL_LST AS LST
ON
SCH.COURSE_GU = LST.COURSE_GU
INNER JOIN 
REV.EPC_CRS AS CRS
ON
SCH.COURSE_GU = CRS.COURSE_GU

INNER JOIN
REV.EPC_STAFF STF
ON
STF.STAFF_GU = SCH.STAFF_GU
LEFT JOIN
REV.REV_PERSON PER
ON
PER.PERSON_GU = STF.STAFF_GU
LEFT JOIN
[180-SMAXODS-01.APS.EDU.ACTD].[LAWSON].aps.TeacherCredentials TC
on
STF.BADGE_NUM = TC.BADGE_NUMBER
WHERE
COURSE_LEVEL IN ('BEP', 'ESL')

) AS T7

ON T6.STUDENT_GU = T7.STUDENT_GU 

INNER JOIN 
REV.REV_PERSON AS PERS
ON
T7.STUDENT_GU = PERS.PERSON_GU

WHERE RN = 1

ORDER BY ORGANIZATION_NAME, SIS_NUMBER, COURSE_LEVEL, STATE_COURSE_CODE
