/*
	Created by Debbie Ann Chavez
	Date 2016-04-12

	JUST CHANGE:  

		REFRESH DATE
		ENTER THE URL
		NOTES
		AND ROLLBACK IF LOOKS GOOD THEN COMMIT

*/



BEGIN TRANSACTION

INSERT INTO rev.UD_VER

SELECT
	MOSTRECENTVER.VER_GU AS VER_GU
	,GETDATE() AS ADD_DATE_TIME_STAMP
	,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS ADD_ID_STAMP
	,NULL AS CHANGE_DATE_TIME_STAMP
	,NULL AS CHANGE_ID_STAMP
		
	--ENTER IN THE REFRESH DATE
	,'2016-05-25' AS REFRESH_DATE
	
	--ENTER THE USER INTERFACE URL
	,'http://synexp.aps.edu.actd/' AS URL

	--ENTER IN ANY NOTES FOR ENVIRONMENT
	,'Shayne working on Audit Trail' AS NOTES

		

FROM 
(
SELECT * FROM (
SELECT 
	ROW_NUMBER() OVER (ORDER BY DEPLOYMENT_DATE DESC) AS RN
	,VER_GU
 FROM 
REV.REV_VER
) AS T1
WHERE
RN = 1
) AS MOSTRECENTVER

SELECT *  FROM 
rev.UD_VER

ROLLBACK