
EXECUTE AS LOGIN='QueryFileUser'
GO

SELECT 
GRADE, SCHOOL_NAME, COUNT (*) AS NUMBER_OF_STUDENTS
FROM
(

SELECT 
DISTINCT SIS_NUMBER, GRADE, SCHOOL_NAME 
	/*
	PERS.LAST_NAME
	,PERS.FIRST_NAME
	,SCH.SIS_NUMBER
	,ENR.GRADE
	,ENR.SCHOOL_CODE
	,ENR.SCHOOL_NAME
	,SCH.TERM_CODE
	,SCH.COURSE_ID
	,SCH.SECTION_ID
	,SCH.PERIOD_BEGIN
	,SCH.PERIOD_END
	,SCH.COURSE_TITLE
	,SCH.COURSE_ENTER_DATE
	,SCH.COURSE_LEAVE_DATE
	*/

	FROM
            OPENROWSET (
                  'Microsoft.ACE.OLEDB.12.0', 
                 'Text;Database=\\SYNTEMPSSIS\Files\TempQuery;',
                  'SELECT * from ACE.csv'
                ) AS [T1]

	INNER JOIN 
	APS.ScheduleDetailsAsOf('2017-05-25') AS SCH
	ON
	T1.[Course ID] = SCH.COURSE_ID

	INNER JOIN 
	APS.PrimaryEnrollmentDetailsAsOf(GETDATE()) AS ENR
	ON
	SCH.STUDENT_GU = ENR.STUDENT_GU
	AND SCH.STUDENT_SCHOOL_YEAR_GU = ENR.STUDENT_SCHOOL_YEAR_GU

	INNER JOIN 
	rev.REV_PERSON AS PERS
	ON
	PERS.PERSON_GU = ENR.STUDENT_GU

) AS T2

GROUP BY 
GRADE, SCHOOL_NAME

ORDER BY SCHOOL_NAME, GRADE

REVERT
GO