DECLARE @PARCC_ALG_II
	TABLE
		(
		SIS_NUMBER VARCHAR (50)
		,TEST_NAME VARCHAR (50)
		,TEST VARCHAR (50)
		,SCALE_SCORE VARCHAR (50)
		,PL VARCHAR (50)
		)
INSERT INTO @PARCC_ALG_II
SELECT 
	SIS_NUMBER
	,TEST_NAME
	,TEST
	,SCALE_SCORE
	,CASE WHEN PL = 'DNME' THEN '1'
		  WHEN PL = 'PART' THEN '2'
		  WHEN PL = 'APEX' THEN '3'
		  WHEN PL = 'METX' THEN '4'
		  WHEN PL = 'EXEX' THEN '5' 
		  ELSE PL
	END AS PL
FROM
	APS.STUDENTTESTPARCC ('PARCC HS Algebra II')

SELECT * FROM @PARCC_ALG_II
WHERE SIS_NUMBER = '970026508'
