

BEGIN TRAN

--UPDATE rev.REV_PERSON_NOT 

--SET END_DATE = '20170630'


INSERT INTO rev.REV_PERSON_NOT

SELECT 
--SIS_NUMBER,
NEWID() AS PERSON_NOT_GU
,STU.STUDENT_GU AS PERSON_GU
,'256096C9-A40D-4654-8322-3E17FAF8EE2D' AS NOT_CFG_GU
,ELL.ADMIN_DATE AS BEGIN_DATE
,NULL AS END_DATE
,NULL AS COMMENT
,NULL AS CHANGE_DATE_TIME_STAMP
,NULL AS CHANGE_ID_STAMP
,GETDATE() AS ADD_DATE_TIME_STAMP
,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS ADD_ID_STAMP
,'N' AS ADDED_BY_RULE
,NULL AS RULE_GU

FROM 
APS.ELLCalculatedAsOf(GETDATE()) AS ELL
LEFT JOIN 
rev.REV_PERSON_NOT AS NOTE
ON
NOTE.PERSON_GU = ELL.STUDENT_GU
AND NOTE.NOT_CFG_GU = '256096C9-A40D-4654-8322-3E17FAF8EE2D'

INNER JOIN 
REV.epc_stu as stu
ON 
STU.STUDENT_GU = ELL.STUDENT_GU

WHERE

NOTE.PERSON_GU IS NULL




UPDATE REV.REV_PERSON_NOT
SET END_DATE = GETDATE() 

FROM 
(SELECT * FROM
(SELECT * FROM rev.REV_PERSON_NOT WHERE NOT_CFG_GU = '256096C9-A40D-4654-8322-3E17FAF8EE2D' AND END_DATE IS NULL)  AS NOTE
LEFT JOIN 
APS.ELLCalculatedAsOf(GETDATE()) AS ELL
ON
NOTE.PERSON_GU = ELL.STUDENT_GU

WHERE
ELL.STUDENT_GU IS NULL 
) AS T1

WHERE 
T1.PERSON_NOT_GU = REV.REV_PERSON_NOT.PERSON_NOT_GU


COMMIT