USE ST_Production
GO



BEGIN TRANSACTION

INSERT INTO  rev.UD_PARENT

(PARENT_GU, ACTIVE_MILITARY, ADD_DATE_TIME_STAMP, ADD_ID_STAMP, BRANCH_OF_SERVICE, CHANGE_DATE_TIME_STAMP, CHANGE_ID_STAMP
,FEDERAL_EMPLOYER, MILITARY_RANK, TRIBAL_LAND)


SELECT 
	SMAX.PARENT_GU AS PARENT_GU
	,SMAX.SMAX_ACTIVE_MILITARY AS ACTIVE_MILITARY
	,GETDATE() AS ADD_DATE_TIME_STAMP
	,'27CDCD0E-BF93-4071-94B2-5DB792BB735F' AS ADD_ID_STAMP
	,NULL AS BRANCH_OF_SERVICE
	,NULL AS CHANGED_DATE_TIME_STAMP
	,NULL AS CHANGED_ID_STAMP

	--change this to the code need from jude
	,SMAX.SYNERGY_NEW_CODE AS FEDERAL_EMPLOYER
	,NULL AS MILITARY_RANK
	,NULL AS TRIBAL_LAND 
	
FROM 
[SMAXDBPROD.APS.EDU.ACTD].[SynergyConversion].dbo.ParentImpactAide AS SMAX

LEFT JOIN
rev.UD_PARENT AS SYNERGY
ON
SYNERGY.PARENT_GU = SMAX.PARENT_GU

WHERE
UPDATES = 'ADD' 
AND SYNERGY.PARENT_GU IS NULL

ROLLBACK