
/*
	CREATED BY:  DEBBIE ANN CHAVEZ
	DATE:  10/8/2014

	FOR UD_PARENT RECORDS THAT ALREADY EXIST AND THE FEDERAL EMPLOYER FIELD IS NULL,
	UPDATE THE FEDERAL EMPLOYER FROM SCHOOLMAX
	DO NOT UPDATE THE 34'S IN SCHOOLMAX
*/

EXECUTE AS LOGIN='QueryFileUser'
GO

/*
BEGIN TRANSACTION

UPDATE rev.UD_PARENT
	SET FEDERAL_EMPLOYER = VALUE_CODE

*/

SELECT 
	T1.ACTIVE_MILITARY
	,T1.FEDERAL_EMPLOYER
	,T1.ADULTID
	,PARENT.PARENT_GU
	,CODES.ALT_CODE_1 

FROM 

	OPENROWSET (
		'Microsoft.ACE.OLEDB.12.0', 
		'Text;Database=\\SynTempSSIS\Files\TempQuery\;', 
		'SELECT * from ADULTID.csv'
	    ) AS T1

	INNER JOIN
	rev.EPC_PARENT AS PARENT
	ON
	PARENT.ADULT_ID = ADULTID
	
	INNER JOIN
	rev.UD_PARENT AS UDPARENT
	ON
	PARENT.PARENT_GU = UDPARENT.PARENT_GU

	
	INNER JOIN
	APS.LookupTable ('Revelation.Person', 'FEDERAL_EMPLOYER') AS CODES
	ON
	LEFT(CODES.ALT_CODE_1,2) = T1.FEDERAL_EMPLOYER
	
	WHERE
	T1.FEDERAL_EMPLOYER != '34'
	AND
	UDPARENT.FEDERAL_EMPLOYER IS NULL
	
--ROLLBACK

REVERT
GO


/*
DECLARE @TEMPTABLE TABLE
	 (
	 PARENT_GU VARCHAR (128),
	ALT_CODE_1 VARCHAR (10)
	)

	INSERT INTO 
	@TEMPTABLE

SELECT * FROM @TEMPTABLE
*/



