DECLARE @AsOfDate AS DATETIME = '2014-12-15'
	   
	 
	 SELECT * FROM 
	   (
	   SELECT 
		'2015' AS SY
		
		, CASE WHEN [LOCATION CODE] > '900' THEN ENR.SCHOOL_CODE ELSE [LOCATION CODE] END AS SCHOOL
		
		,ALS.SIS_NUMBER
		
		,ENR.GRADE
		,CASE WHEN PHL.DATE_ASSIGNED IS NULL THEN 'N' ELSE 'Y' END AS PHLOTE
		,LCETEST.PERFORMANCE_LEVEL
		,LCETEST.TEST_NAME
		
		,SCORES.TEST_SCORE
		,SCORE_DESCRIPTION
				
		,CASE
			WHEN FEP.STUDENT_GU IS NOT NULL THEN 'FEP'
			WHEN [ENGLISH PROFICIENCY] IN (2,3) THEN 'FEPM'
			WHEN [ENGLISH PROFICIENCY] = 4 THEN 'FEPE'
			WHEN [ENGLISH PROFICIENCY] = 1 THEN 'ELL'
			ELSE '' 
		END AS [ENGLISH PROFICIENCY]


	    FROM 
	  
	  (
	   SELECT 
				[SY]
				, [LOCATION CODE]
				,[LAST NAME LONG]
				,[FIRST NAME LONG]
				,[HISPANIC INDICATOR]
				,[ETHNIC CODE SHORT]
				,[GENDER CODE]
				,[Field11]
				,[ENGLISH PROFICIENCY]
				,[Field13]
	           ,SIS_NUMBER
			   ,STATE_STUDENT_NUMBER
		  ,STUDENT_GU
		  --SELECT * 
		  FROM
				--Uses the 80th Day Stars File
				[RDAVM.APS.EDU.ACTD].[db_STARS_History].[dbo].[STUD_SNAPSHOT] AS STARS
				INNER JOIN 
				REV.EPC_STU AS STU
				ON STARS.[STUDENT ID] = STU.STATE_STUDENT_NUMBER
				           
		  WHERE
				[Period] = @AsOfDate
				--[Period] =  '2014-12-15'
				AND [DISTRICT CODE] = '001'

) AS ALS

LEFT JOIN 
APS.PHLOTEAsOf(@AsOfDate) AS PHL
ON
ALS.STUDENT_GU = PHL.STUDENT_GU

LEFT JOIN 
(SELECT * FROM 
rev.EPC_STU_PGM_ELL_HIS
WHERE
EXIT_DATE BETWEEN  '2014-06-01' AND '2014-08-14'
) AS FEP
ON
ALS.STUDENT_GU = FEP.STUDENT_GU

---------GET SCHOOL NAME FOR GOOD STARS LOCATIONS------------------------------------
LEFT JOIN 
rev.EPC_SCH AS SCH
ON
ALS.[LOCATION CODE] = SCH.SCHOOL_CODE

LEFT JOIN 
rev.REV_ORGANIZATION AS ORG
ON
SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU
-------------------------------------------------------------------------------------

--GET SYNERGY LOCATION AND NAME WHERE STARS LOCATIONS ARE ROLLED UP, STATE LOCATIONS
LEFT JOIN 
APS.PrimaryEnrollmentDetailsAsOf('2014-12-15') AS ENR
ON
ALS.STUDENT_GU = ENR.STUDENT_GU
----------------------------------------------------------------------------------------

INNER HASH JOIN 
APS.LCELatestEvaluationAsOf('2014-12-15') AS LCETEST
ON
LCETEST.STUDENT_GU = ALS.STUDENT_GU

INNER HASH JOIN
rev.EPC_TEST_PART AS PART
ON LCETEST.TEST_GU = PART.TEST_GU

INNER HASH JOIN
rev.EPC_STU_TEST_PART AS STU_PART
ON PART.TEST_PART_GU = STU_PART.TEST_PART_GU
AND STU_PART.STUDENT_TEST_GU = LCETEST.STUDENT_TEST_GU

INNER HASH JOIN
rev.EPC_STU_TEST_PART_SCORE AS SCORES
ON
SCORES.STU_TEST_PART_GU = STU_PART.STU_TEST_PART_GU

    LEFT JOIN
    rev.EPC_TEST_SCORE_TYPE AS SCORET
    ON
    SCORET.TEST_GU = LCETEST.TEST_GU
    AND SCORES.TEST_SCORE_TYPE_GU = SCORET.TEST_SCORE_TYPE_GU

    LEFT JOIN
    rev.EPC_TEST_DEF_SCORE AS SCORETDEF
    ON
    SCORETDEF.TEST_DEF_SCORE_GU = SCORET.TEST_DEF_SCORE_GU


) AS T1

WHERE
[ENGLISH PROFICIENCY] = 'ELL'
AND SCORE_DESCRIPTION = 'Overall LP'

ORDER BY SIS_NUMBER