/**
 * $Revision: 1 $
 * $LastChangedBy: e104090 $
 * $LastChangedDate: 2015-05-22 $
 */


 /*  
	1.  Must change the last day of school it is hardcoded.


 */


IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[APS].[LCEALS1A]'))
	EXEC ('CREATE VIEW APS.LCEALS1A AS SELECT 0 AS DUMMY')
GO

ALTER VIEW APS.LCEALS1A AS



SELECT 
--SCHOOL_CODE, ORGANIZATION_NAME, K12_STUS 
	*
	--,PHLOTE - [Total ELL] AS [FEP Bridging/Reaching]
FROM 

(
SELECT 
	SCHOOL.SCHOOL_CODE AS [School Number]
	,ORG.ORGANIZATION_NAME AS [School Name]
	,CLUSTERNAME.ORGANIZATION_NAME AS Cluster
	,COUNT(*) AS [K12 Stus] 
	,COUNT(PHL.STUDENT_GU) AS PHLOTE 
	,SUM(CASE WHEN HLS.STUDENT_GU IS NULL THEN 1 ELSE 0 END) AS [No HLS]
	
	,SUM(CASE WHEN ELL.STUDENT_GU IS NOT NULL THEN 1 ELSE 0 END) AS [Total ELL]
	,SUM(CASE WHEN KINDERWAPT.STUDENT_GU IS NOT NULL THEN 1 ELSE 0 END) AS ELL

	,SUM(CASE WHEN NEW_PERFORMANCE_LEVEL.STUDENT_GU IS NOT NULL AND NEW_PERFORMANCE_LEVEL.NEW_PERFORMANCE_LEVEL = 'Entering' THEN 1 ELSE 0 END) AS Entering
	,SUM(CASE WHEN NEW_PERFORMANCE_LEVEL.STUDENT_GU IS NOT NULL AND NEW_PERFORMANCE_LEVEL.NEW_PERFORMANCE_LEVEL = 'Emerging' THEN 1 ELSE 0 END) AS Emerging
	,SUM(CASE WHEN NEW_PERFORMANCE_LEVEL.STUDENT_GU IS NOT NULL AND NEW_PERFORMANCE_LEVEL.NEW_PERFORMANCE_LEVEL = 'Developing' THEN 1 ELSE 0 END) AS Developing
	,SUM(CASE WHEN NEW_PERFORMANCE_LEVEL.STUDENT_GU IS NOT NULL AND NEW_PERFORMANCE_LEVEL.NEW_PERFORMANCE_LEVEL = 'Expanding' THEN 1 ELSE 0 END) AS Expanding
	,SUM(CASE WHEN FEPLOGIC.STUDENT_GU IS NOT NULL THEN 1 ELSE 0 END) AS [FEP Bridging/Reaching]

 FROM
APS.PrimaryEnrollmentsAsOf('2015-05-22')AS PE
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
PE.ORGANIZATION_YEAR_GU = ORGYR.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORGYR.ORGANIZATION_GU = ORG.ORGANIZATION_GU
INNER JOIN
rev.EPC_SCH AS SCHOOL
ON
SCHOOL.ORGANIZATION_GU = ORG.ORGANIZATION_GU

------------------------------------------------
INNER JOIN
rev.EPC_SCH AS CLUSTER
ON
SCHOOL.ALT_FUNDING_SCHOOL_CODE = CLUSTER.SCHOOL_CODE

INNER JOIN
rev.REV_ORGANIZATION AS CLUSTERNAME
ON
CLUSTER.ORGANIZATION_GU = CLUSTERNAME.ORGANIZATION_GU
-----------------------------------------------------------

LEFT JOIN
APS.PHLOTEAsOf('2015-05-22') AS PHL
ON
PHL.STUDENT_GU = PE.STUDENT_GU

----------------------------------------------------------------------------------------------
LEFT JOIN
(SELECT DISTINCT NOHLS.STUDENT_GU FROM rev.UD_HLS_HISTORY AS NOHLS
INNER JOIN APS.PrimaryEnrollmentsAsOf('2015-05-22') AS PRIM
ON
PRIM.STUDENT_GU = NOHLS.STUDENT_GU
WHERE 
PRIM.GRADE NOT IN  ('050', '070', '090', '230', '240', '250', '260', '270', '280', '290', '300')
) AS HLS
ON
HLS.STUDENT_GU = PE.STUDENT_GU

----------------------COUNT ONLY THE ELL STUDENTS IN THE ESL REPORT----------------------------
LEFT JOIN
(
	
	SELECT 
			*
	FROM 
	(
	SELECT 
			ESL.*
			,STU.STUDENT_GU 
			,ROW_NUMBER() OVER (PARTITION BY ESL.SIS_NUMBER ORDER BY STATUS DESC) AS RN
	 FROM 
	APS.LCEStudentsAndProvidersAsOf('2015-05-22') AS ESL
	INNER JOIN
	rev.EPC_STU AS STU
	ON
	ESL.SIS_NUMBER = STU.SIS_NUMBER

	) AS T1
	WHERE RN =1
	AND GRADE NOT IN ('P1', 'P2', 'PK', 'T1', 'T2', 'T3', 'T4', 'C1', 'C2', 'C3', 'C4')

) AS ELL

ON
ELL.STUDENT_GU = PE.STUDENT_GU

-------------------------------------------------------------------------------------------------
--GET KINDER WAPTS
LEFT JOIN

		(SELECT 
			SIS_NUMBER
			,GRADE
			,TEST_NAME
			,STUDENT_GU
		FROM
			(SELECT 
				ESL.*
				,STU.STUDENT_GU
				,ROW_NUMBER() OVER (PARTITION BY ESL.SIS_NUMBER ORDER BY STATUS DESC) AS RN
			FROM 
			APS.LCEStudentsAndProvidersAsOf('2015-05-22') AS ESL
			INNER JOIN
			rev.EPC_STU AS STU
			ON
			ESL.SIS_NUMBER = STU.SIS_NUMBER
			WHERE
				TEST_NAME = 'WAPT' 
				AND GRADE = 'K'
				AND PERFORMANCE_LEVEL = 'ELL'
			)AS KINDERWAPTDUPS
		WHERE
			RN = 1
		) AS KINDERWAPT
ON
PE.STUDENT_GU = KINDERWAPT.STUDENT_GU


----------------------------------------------------------------------------------------------------------
LEFT JOIN
		(
		SELECT 
			STUDENT_GU
			,CASE WHEN PERFORMANCE_LEVEL = 'Beginning' THEN 'Entering'
				  WHEN PERFORMANCE_LEVEL = 'Early Intermediate' THEN 'Emerging'
				  WHEN (PERFORMANCE_LEVEL = 'ELL' AND GRADE != 'K') THEN 'Entering'
				  WHEN PERFORMANCE_LEVEL = 'Intermediate' THEN 'Developing'
				  WHEN PERFORMANCE_LEVEL = 'LEP' THEN 'Emerging'
				  WHEN PERFORMANCE_LEVEL = 'NEP' THEN 'Entering'
			ELSE PERFORMANCE_LEVEL END AS NEW_PERFORMANCE_LEVEL

		FROM 
		(
		SELECT 
				ESL.*
				,STU.STUDENT_GU
				,ROW_NUMBER() OVER (PARTITION BY ESL.SIS_NUMBER ORDER BY STATUS DESC) AS RN
			FROM 
			APS.LCEStudentsAndProvidersAsOf('2015-05-22') AS ESL
			INNER JOIN
			rev.EPC_STU AS STU
			ON
			ESL.SIS_NUMBER = STU.SIS_NUMBER
		) AS TESTSONESL
		WHERE
			RN = 1
			AND GRADE NOT IN ('P1', 'P2', 'PK', 'T1', 'T2', 'T3', 'T4', 'C1', 'C2', 'C3', 'C4')		
		) AS NEW_PERFORMANCE_LEVEL
ON
PE.STUDENT_GU = NEW_PERFORMANCE_LEVEL.STUDENT_GU
------------------------------------------------------------------------------------------------------------
--FEP LOGIC
LEFT JOIN 
(
SELECT PRIM.STUDENT_GU, PERFORMANCE_LEVEL, PRIM.GRADE, TEST_NAME, SCHOOL.ALT_FUNDING_SCHOOL_CODE FROM 
APS.PHLOTEAsOf('2015-05-22') AS PHL
INNER JOIN
APS.PrimaryEnrollmentsAsOf('2015-05-22') AS PRIM
ON
PHL.STUDENT_GU = PRIM.STUDENT_GU
INNER JOIN
APS.LCELatestEvaluationAsOf('2015-05-22') AS LCE
ON
LCE.STUDENT_GU = PRIM.STUDENT_GU
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = PRIM.ORGANIZATION_YEAR_GU
INNER JOIN
rev.EPC_SCH AS SCHOOL
ON
SCHOOL.ORGANIZATION_GU = ORGYR.ORGANIZATION_GU

WHERE
	PRIM.GRADE NOT IN  ('050', '070', '090', '230', '240', '250', '260', '270', '280', '290', '300')
	AND PERFORMANCE_LEVEL IN ('ADV','BRIDG', 'FEP', 'REACH','C-PRO')
) AS FEPLOGIC

ON
FEPLOGIC.STUDENT_GU = PE.STUDENT_GU

----------------------------------------------------------------------------------------------------------
/* -- JUST REMOVE THIS AND SUBTRACT THE TOTAL ELL'S FROM THE PHLOTES
LEFT JOIN
		(
		SELECT 
			STUDENT_GU
			,CASE WHEN VALUE_DESCRIPTION = 'Advanced' THEN 'FEP Bridging/Reaching'
				  WHEN VALUE_DESCRIPTION = 'Bridging' THEN 'FEP Bridging/Reaching'
				  WHEN VALUE_DESCRIPTION = 'FEP' THEN 'FEP Bridging/Reaching'
				  WHEN VALUE_DESCRIPTION = 'Proficient' THEN 'FEP Bridging/Reaching'
				  WHEN VALUE_DESCRIPTION = 'Reaching' THEN 'FEP Bridging/Reaching'
			ELSE VALUE_DESCRIPTION END AS FEPLEVEL

		 FROM
		APS.LCELatestEvaluationAsOf('2015-05-22') AS LCE
		INNER JOIN
		APS.LookupTable('K12.TestInfo', 'PERFORMANCE_LEVELS') AS LEVEL
		ON
		LCE.PERFORMANCE_LEVEL = LEVEL.VALUE_CODE
		
		) AS NEW_PERFORMANCE_LEVEL2
ON
PE.STUDENT_GU = NEW_PERFORMANCE_LEVEL2.STUDENT_GU
*/
--------------------------------------------------------------------------------------------------------------


--DO NOT COUNT PRESCHOOL - K-12 ONLY
--'050' = P1, '070' = P2, '090' = PK
WHERE
	PE.GRADE NOT IN  ('050', '070', '090', '230', '240', '250', '260', '270', '280', '290', '300')

GROUP BY 
	SCHOOL.SCHOOL_CODE
	,ORG.ORGANIZATION_NAME
	,CLUSTERNAME.ORGANIZATION_NAME
		
		
) AS K12STUS