
/*

	Created By:  Debbie Ann Chavez
	Date:  6/4/2015

*/


IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[APS].[LCEALS1BDISTRICT]'))
	EXEC ('CREATE VIEW APS.LCEALS1BDISTRICT AS SELECT 0 AS DUMMY')
GO

ALTER VIEW APS.LCEALS1BDISTRICT AS


SELECT 
	DISTRICT 
	,SUM(CURRTOT) AS CURRTOT
	,SUM(PRIORTOT) AS PRIORTOT
	,SUM(YAGOTOT) AS YAGOTOT

	,SUM(CURRTOT1) AS CURRTOT1
	,SUM(PRIORTOT1) AS PRIORTOT1
	,SUM(YAGOTOT1) AS YAGOTOT1

 FROM 

APS.LCEALS1BCLUSTER

GROUP BY DISTRICT

