

/*
	Created By:  Debbie Ann Chavez
	Date:  6/4/2015

*/


IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[APS].[LCEALS1BCLUSTER]'))
	EXEC ('CREATE VIEW APS.LCEALS1BCLUSTER AS SELECT 0 AS DUMMY')
GO

ALTER VIEW APS.LCEALS1BCLUSTER AS


SELECT 
	CLUSTER.CLUSTER
	,'SCHOOL' AS SCHOOL_FILLER
	,'District' AS DISTRICT
	
	,CASE WHEN SUM(T4.[Current Quarter 5/22/2015 no HLS]) IS NULL THEN 0 ELSE SUM(T4.[Current Quarter 5/22/2015 no HLS]) END AS CURRTOT
	,CASE WHEN SUM(T2.[Prior Quarter 2/12/2015])IS NULL THEN 0 ELSE SUM(T2.[Prior Quarter 2/12/2015]) END AS PRIORTOT
	,CASE WHEN SUM([LASTYEAR NOHLS]) IS NULL THEN 0 ELSE SUM([LASTYEAR NOHLS]) END AS YAGOTOT

	,CASE WHEN SUM([Current Quarter 5/22/2014]) IS NULL THEN 0 ELSE  SUM([Current Quarter 5/22/2014]) END AS CURRTOT1
	,CASE WHEN SUM(T3.[Prior Quarter 2/12/2015]) IS NULL THEN 0 ELSE SUM(T3.[Prior Quarter 2/12/2015])  END AS PRIORTOT1
	,CASE WHEN SUM([LAST YEAR NOTEST]) IS NULL THEN 0 ELSE SUM([LAST YEAR NOTEST]) END AS YAGOTOT1
	

FROM

 
 ---------------------------------------------------------------------------------------------------
 --THIS TABLE IS THE YEAR AGO DATA 

           dbo.[LCE_NO_HLS]  AS CLUSTER

			LEFT JOIN
			rev.REV_ORGANIZATION AS ORG
			ON
			ORG.ORGANIZATION_NAME = CLUSTER.SCHOOL
			

-----------Current Quarter Needs Testing----------------------------------------------------------------
			LEFT JOIN
			(SELECT 
				SchoolName
				,COUNT (*) AS [Current Quarter 5/22/2014]
			 FROM 
			APS.LCEStudentsNeedingTestingAsOf('2015-05-22')
			GROUP BY 
				SchoolName
			) AS T1

			ON 
			T1.SchoolName = ORG.ORGANIZATION_NAME

			LEFT JOIN
			rev.EPC_SCH AS SCH
			ON
			SCH.ORGANIZATION_GU = ORG.ORGANIZATION_GU
-------------------------------------------------------------------------------------------------------
--PRIOR QUARTER NO HLS

	LEFT JOIN
	(		
	SELECT [LOCATION CODE],COUNT(*) AS [Prior Quarter 2/12/2015]
	--[LOCATION CODE], SIS_NUMBER 
	FROM 

	[046-WS02.APS.EDU.ACTD].[db_STARS_History].[dbo].[STUD_SNAPSHOT] AS STUDENT_SNAPSHOT
	INNER JOIN 
	rev.EPC_STU AS STU
	ON
	STU.SIS_NUMBER = STUDENT_SNAPSHOT.[ALTERNATE STUDENT ID]
	
	LEFT JOIN
	rev.UD_HLS_HISTORY AS HLS
	ON
	HLS.STUDENT_GU = STU.STUDENT_GU

	INNER JOIN
	rev.EPC_SCH AS SCHOOL
	ON
	STUDENT_SNAPSHOT.[LOCATION CODE] = SCHOOL.SCHOOL_CODE

WHERE
	[DISTRICT CODE] = '001'
	AND [Period] = '2015-03-01'
	
	AND HLS.STUDENT_GU IS NULL
GROUP BY 
	[LOCATION CODE]
) AS T2

ON 
T2.[LOCATION CODE] = SCH.SCHOOL_CODE
--------------------------------------------------------------------------------------------------------------
--PRIOR QUARTER NO TESTING
LEFT JOIN
(
SELECT [LOCATION CODE],COUNT(*) AS [Prior Quarter 2/12/2015]
	--[LOCATION CODE], SIS_NUMBER 
	FROM 

	[046-WS02.APS.EDU.ACTD].[db_STARS_History].[dbo].[STUD_SNAPSHOT] AS STUDENT_SNAPSHOT
	INNER JOIN 
	rev.EPC_STU AS STU
	ON
	STU.SIS_NUMBER = STUDENT_SNAPSHOT.[ALTERNATE STUDENT ID]
	
	INNER JOIN
	APS.LCEStudentsNeedingTestingAsOf('2015-03-15') AS NPT
	ON
	NPT.STUDENT_GU = STU.STUDENT_GU

	INNER JOIN
	rev.EPC_SCH AS SCHOOL
	ON
	STUDENT_SNAPSHOT.[LOCATION CODE] = SCHOOL.SCHOOL_CODE

WHERE
	[DISTRICT CODE] = '001'
	AND [Period] = '2015-03-01'
		
GROUP BY 
	[LOCATION CODE]
	) AS T3
ON
T3.[LOCATION CODE] = SCH.SCHOOL_CODE
------------------------------------------------------------------------------------------------------------------
--CURRENT QUARTER NO HLS
LEFT JOIN
(SELECT 
	ORG.ORGANIZATION_GU, ORGANIZATION_NAME, COUNT(*) AS [Current Quarter 5/22/2015 no HLS] 
FROM 
APS.PrimaryEnrollmentsAsOf('2015-05-22') AS PRIM
LEFT JOIN
rev.UD_HLS_HISTORY AS NOHLS
ON
PRIM.STUDENT_GU = NOHLS.STUDENT_GU
INNER JOIN
rev.REV_ORGANIZATION_YEAR AS ORGYR
ON
ORGYR.ORGANIZATION_YEAR_GU = PRIM.ORGANIZATION_YEAR_GU
INNER JOIN
rev.REV_ORGANIZATION AS ORG
ON
ORG.ORGANIZATION_GU = ORGYR.ORGANIZATION_GU
INNER JOIN
rev.EPC_STU AS STU
ON
PRIM.STUDENT_GU = STU.STUDENT_GU

WHERE
NOHLS.STUDENT_GU IS NULL 
AND GRADE NOT IN ('050', '070', '090')

GROUP BY ORG.ORGANIZATION_GU, ORGANIZATION_NAME
) AS T4

ON
T4.ORGANIZATION_GU = ORG.ORGANIZATION_GU

	WHERE
		CLUSTER.SCHOOL NOT LIKE '%Cluster'

GROUP BY
CLUSTER
