

/*
	Created By:  Debbie Ann Chavez
	Date:  6/4/2015
*/



IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[APS].[LCEALS1BCLUSTER]'))
	EXEC ('CREATE VIEW APS.LCEALS1BCLUSTER AS SELECT 0 AS DUMMY')
GO

ALTER VIEW APS.LCEALS1BCLUSTER AS


SELECT 
	CLUSTER
	,'SCHOOL' AS SCHOOL_FILLER
	,'District' AS DISTRICT
	
	,SUM([Current Quarter 5/22/2015 no HLS])  AS CURRTOT
	,SUM([Prior Quarter 2/12/2015 No HLS]) AS PRIORTOT
	,SUM([Year Ago 5/22/2014 No HLS]) AS YAGOTOT

	,SUM([Current Quarter 5/22/2015 Needs EPT])  AS CURRTOT1
	,SUM([Prior Quarter 2/12/2015 NEEDS EPT]) AS PRIORTOT1
	,SUM([Year Ago 5/22/2014 No EPT]) AS YAGOTOT1
	
FROM

APS.LCEALS1B

GROUP BY
CLUSTER
