



SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	,[STUDENT].[BIRTH_DATE]
	
	,[ENROLLMENTS].[GRADE]
	,[ENROLLMENTS].[SCHOOL_CODE]
	,[ENROLLMENTS].[SCHOOL_NAME]
	,[ENROLLMENTS].[SCHOOL_YEAR]
	,[ENROLLMENTS].[EXCLUDE_ADA_ADM]
	,[ENROLLMENTS].[ENTER_DATE]
	,[ENROLLMENTS].[ENTER_CODE]
	,[ENROLLMENTS].[ENTER_DESCRIPTION]
	,[ENROLLMENTS].[LEAVE_DATE]
	,[ENROLLMENTS].[LEAVE_CODE]
	,[ENROLLMENTS].[LEAVE_DESCRIPTION]
	,[ENROLLMENTS].[YEAR_END_STATUS]
	,[ENROLLMENTS].[SUMMER_WITHDRAWL_CODE]
	,[SSY].[SUMMER_WITHDRAWL_DATE]
	
FROM
	APS.StudentEnrollmentDetails AS [ENROLLMENTS]
	
	INNER JOIN
	rev.EPC_STU_SCH_YR AS [SSY]
	ON
	[ENROLLMENTS].[STUDENT_SCHOOL_YEAR_GU] = [SSY].[STUDENT_SCHOOL_YEAR_GU]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[ENROLLMENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
WHERE
	[SSY].[SUMMER_WITHDRAWL_DATE] BETWEEN '5/23/2015' AND '8/23/2015'