SELECT 
	SIS_NUMBER, LASTTEST.PERFORMANCE_LEVEL, LASTTEST.TEST_NAME, LASTTEST.ADMIN_DATE, HISTORY.ENTRY_DATE, HISTORY.PROGRAM_CODE, EXIT_DATE, EXIT_REASON
 
FROM 
APS.LCELatestEvaluationAsOf('2016-07-01') AS LASTTEST
INNER JOIN 
rev.EPC_STU AS STU 
ON
LASTTEST.STUDENT_GU = STU.STUDENT_GU
LEFT JOIN
rev.EPC_STU_PGM_ELL_HIS AS HISTORY
ON
STU.STUDENT_GU = HISTORY.STUDENT_GU

WHERE 
IS_ELL = 0
AND ADMIN_DATE BETWEEN '2015-07-01' AND '2016-07-01'
--AND HISTORY.STUDENT_GU IS NULL
--AND ENTRY_DATE IS NOT NULL