


DECLARE @SCHOOL_YEAR INT = 2014


	
	
SELECT
	[STUDENT].[SIS_NUMBER]
	,[STUDENT].[STATE_STUDENT_NUMBER]
	,[STUDENT].[FIRST_NAME]
	,[STUDENT].[LAST_NAME]
	,[STUDENT].[MIDDLE_NAME]
	--,[AVID_STUDENTS].[GRADE] AS [CURRENT_GRADE]
	--,[ENROLLMENTS].[SCHOOL_NAME] AS [CURRENT_LOCATION]
	
	,[STARS_ATTENDANCE].[TOTAL UNEXCUSED]

FROM
	(
	SELECT DISTINCT
		[SCHEDULE].[STUDENT_GU]
		,[Grades].[VALUE_DESCRIPTION] AS [GRADE]
	FROM
		-- Get full schedule
		APS.BasicSchedule AS [SCHEDULE]
		
		INNER JOIN
		-- Get Course details
		rev.EPC_CRS AS [COURSE]
		ON
		[SCHEDULE].[COURSE_GU] = [COURSE].[COURSE_GU]
		
		INNER JOIN 
		rev.REV_YEAR AS [RevYear] -- Contains the School Year
		ON 
		[SCHEDULE].[YEAR_GU] = [RevYear].[YEAR_GU]
		
		INNER JOIN
		rev.EPC_STU_SCH_YR AS [StudentSchoolYear]
		ON
		[SCHEDULE].[STUDENT_SCHOOL_YEAR_GU] = [StudentSchoolYear].[STUDENT_SCHOOL_YEAR_GU]
		
		LEFT OUTER JOIN
		APS.LookupTable('K12','Grade') AS [Grades]
		ON
		[StudentSchoolYear].[GRADE] = [Grades].[VALUE_CODE]
		
	WHERE
		[COURSE].[COURSE_ID] IN ('55507','555071','555072','55508','555081','555082','555091','555092','555101','555102','555111','555112','555121','555122')
		AND [RevYear].[SCHOOL_YEAR] = @SCHOOL_YEAR
		AND [RevYear].[EXTENSION] = 'R'
		
	) AS [AVID_STUDENTS]
	
	INNER JOIN
	APS.BasicStudent AS [STUDENT]
	ON
	[AVID_STUDENTS].[STUDENT_GU] = [STUDENT].[STUDENT_GU]
	
	LEFT OUTER JOIN
	(
		SELECT --TOP 100
		[STUD_ATTEND_DAY].[SY]
		,[STUD_ATTEND_DAY].[STUDENT ID]
		,COUNT([STUD_ATTEND_DAY].[ATTENDANCE DATE]) AS [TOTAL UNEXCUSED]
	FROM
		[046-WS02.APS.EDU.ACTD].[db_STARS_History].[dbo].[STUD_ATTEND_DAY]
		
	WHERE
		[STUD_ATTEND_DAY].[DISTRICT CODE] = '001'
		AND [STUD_ATTEND_DAY].[SY] = '2014'
		
	GROUP BY
		[STUD_ATTEND_DAY].[SY]
		,[STUD_ATTEND_DAY].[STUDENT ID]
	) AS [STARS_ATTENDANCE]
	ON
	[STUDENT].[STATE_STUDENT_NUMBER] = [STARS_ATTENDANCE].[STUDENT ID]
	
ORDER BY
	[STUDENT].[SIS_NUMBER]